// Achats (web/moduli/acquisti.js) : réapprovisionnement, commandes en arrivée, réceptions, factures fournisseurs.
export default {
  'acquisti.titolo': "Achats",
  'acquisti.scheda-riordino': "À réapprovisionner",
  'acquisti.scheda-arrivo': "En arrivée",
  'acquisti.scheda-fatture': "Factures fournisseurs",
  'acquisti.stato-bozza': "Brouillon",
  'acquisti.stato-inviato': "Envoyée",
  'acquisti.stato-parziale': "Reçue en partie",
  'acquisti.stato-arrivato': "Reçue",
  'acquisti.stato-annullato': "Annulée",
  'acquisti.serve-magazzino': "Les achats ont besoin d'une section avec le stock (articles, pièces détachées, matériaux…).",
  'acquisti.non-pronti': "Les achats ne sont pas encore prêts.",
  'acquisti.chiedi-titolare': "Demandez à quelqu'un qui peut personnaliser le logiciel.",
  'acquisti.magazzino': "Section du stock",
  'acquisti.prepara-titolo': "Préparer les achats",
  'acquisti.prepara-nota': "Kubo utilise les « Commandes fournisseurs » existantes, ou les crée, et ajoute la quantité reçue, l'état « reçue en partie », le bon de livraison et la facture du fournisseur. Vos données ne changent pas.",
  'acquisti.prepara': "Préparer",
  'acquisti.preparati': {"one": "{n} élément ajouté", "other": "{n} éléments ajoutés"},
  'acquisti.niente-riordino': "Rien sous le seuil : tout est au-dessus, ou déjà commandé.",
  'acquisti.fornitore': "Fournisseur",
  'acquisti.scegli-fornitore': "Choisissez le fournisseur…",
  'acquisti.da-ordinare': "À commander",
  'acquisti.senza-fornitore': "Sans fournisseur",
  'acquisti.senza-fornitore-nota': "Ces articles n'ont pas de fournisseur dans leur fiche : choisissez-le ici.",
  'acquisti.articolo': "Article",
  'acquisti.giacenza': "Stock",
  'acquisti.soglia': "Seuil",
  'acquisti.in-arrivo': "En arrivée",
  'acquisti.costo': "Coût",
  'acquisti.totale-stimato': "Total estimé : {importo}",
  'acquisti.niente-scelto': "Vous n'avez rien choisi à commander",
  'acquisti.ordini-creati': {"one": "{n} commande créée en brouillon", "other": "{n} commandes créées en brouillon"},
  'acquisti.riordino-nota': "Sous le seuil veut dire stock plus quantités déjà commandées pas au-delà du seuil. Kubo propose de revenir au double du seuil : ajustez les quantités comme vous voulez.",
  'acquisti.crea-ordini': "Créer les commandes",
  'acquisti.crea-nota': "Une commande en brouillon par fournisseur : vérifiez-la et envoyez-la.",
  'acquisti.in-ritardo': "En retard : prévue le {data}",
  'acquisti.previsto': "Prévue le {data}",
  'acquisti.ricevi': "Réceptionner",
  'acquisti.ricevute-di': "{ricevuta} sur {quantita}",
  'acquisti.niente-arrivo': "Aucune commande en arrivée.",
  'acquisti.ordine-chiuso': "Cette commande est déjà clôturée.",
  'acquisti.vedi-confronto': "Voir la comparaison",
  'acquisti.ddt-segnaposto': "Numéro et date du bon de livraison",
  'acquisti.ricevuto-tutto': "Marchandise reçue : commande complète",
  'acquisti.ricevuto-parte': "Marchandise reçue : la commande reste ouverte pour le reste",
  'acquisti.ricevi-titolo': "Réceptionner : {numero}, {fornitore}",
  'acquisti.ddt': "Bon de livraison du fournisseur",
  'acquisti.data': "Date",
  'acquisti.ordinate': "Commandées",
  'acquisti.gia-ricevute': "Déjà reçues",
  'acquisti.arrivate-ora': "Arrivées maintenant",
  'acquisti.ricevi-nota': "Les quantités arrivées entrent tout de suite en stock et le coût de l'article devient le coût moyen pondéré. Ce qui manque reste en arrivée.",
  'acquisti.carica': "Entrer en stock",
  'acquisti.annulla': "Annuler",
  'acquisti.senza-fatture': "Pour rapprocher les factures, il faut le modèle « Factures et facture électronique ».",
  'acquisti.ordine': "Commande",
  'acquisti.ricevuto': "Reçu",
  'acquisti.fattura-proposta': "Facture proposée",
  'acquisti.candidata': "{numero} : {importo}",
  'acquisti.nessuna-fattura': "Aucune facture de ce fournisseur",
  'acquisti.confronta': "Comparer",
  'acquisti.tutto-fatturato': "Chaque réception a sa facture.",
  'acquisti.fatture-nota': "Kubo compare la valeur de la marchandise reçue avec le montant HT des factures du fournisseur. C'est bon si l'écart ne dépasse pas 1 € ou 1 %.",
  'acquisti.abbinata': "Facture rapprochée",
  'acquisti.tolta': "Facture retirée",
  'acquisti.ordinato': "Commandé",
  'acquisti.fatturato': "Facturé",
  'acquisti.confronto-titolo': "{numero} · {fornitore}",
  'acquisti.torna': "Correspond à la facture {numero}.",
  'acquisti.non-torna': "La facture {numero} ne correspond pas : écart {importo}.",
  'acquisti.togli': "Retirer",
  'acquisti.candidate': "Factures candidates",
  'acquisti.fattura': "Facture",
  'acquisti.imponibile': "Montant HT",
  'acquisti.differenza': "Écart",
  'acquisti.abbina': "Rapprocher",
  'acquisti.ricevimenti': "Réceptions",
  'acquisti.quantita': "Quantité",
};
