// Area «avvio» (web/moduli/avvio.js) · Français.
export default {
  'avvio.avanti': "Suivant",
  'avvio.indietro': "← Retour",
  'avvio.azienda-es': "ex. Atelier Ferri",
  'avvio.sottotitolo': "Dix questions et votre logiciel de gestion est prêt, taillé pour votre métier. Tout se change ensuite.",
  'avvio.nome-attivita': "Comment s'appelle votre entreprise ?",
  'avvio.d-settore': "Quel est votre métier ?",
  'avvio.a-settore': "Choisissez le plus proche. Tout se change ensuite.",
  'avvio.o-settore-negozio': "Boutique et commerce",
  'avvio.sd-negozio': "Je vends au comptoir, avec articles et stock",
  'avvio.o-settore-ristorante': "Restaurant et bar",
  'avvio.sd-ristorante': "Tables, commandes, menus avec allergènes, réservations",
  'avvio.o-settore-laboratorio': "Atelier et artisan",
  'avvio.sd-laboratorio': "Devis, commandes par étapes, matériaux",
  'avvio.o-settore-officina': "Garage et réparation",
  'avvio.sd-officina': "Véhicules ou appareils, interventions, pièces détachées, garanties",
  'avvio.o-settore-studio': "Cabinet et services",
  'avvio.sd-studio': "Agenda, fiches client, forfaits de séances",
  'avvio.o-settore-beauty': "Beauté et esthétique",
  'avvio.sd-beauty': "Agenda par cabine, soins, forfaits, produits",
  'avvio.o-settore-palestra': "Salle de sport et association",
  'avvio.sd-palestra': "Adhérents, abonnements et renouvellements, cours et présences",
  'avvio.o-settore-professionista': "Indépendant et agence",
  'avvio.sd-professionista': "Clients, projets, heures, échéances, devis",
  'avvio.o-settore-noleggio': "Location",
  'avvio.sd-noleggio': "Biens, disponibilités, contrats du/au, cautions",
  'avvio.o-settore-altro': "Autre, je pars de zéro",
  'avvio.sd-altro': "Un logiciel vide : c'est vous qui créez les sections",
  'avvio.d-offerta': "Vous vendez des produits, des services ou les deux ?",
  'avvio.o-offerta-prodotti': "Produits",
  'avvio.o-offerta-servizi': "Services",
  'avvio.o-offerta-entrambi': "Les deux",
  'avvio.d-magazzino': "Vous gérez un stock ?",
  'avvio.a-magazzino': "Quantités en stock, stocks minimum, ce qu'il faut recommander.",
  'avvio.d-su_misura': "Vous travaillez sur mesure, avec des devis ?",
  'avvio.a-su_misura': "Le devis avec ses lignes ; quand le client accepte, le travail s'ouvre.",
  'avvio.d-appuntamenti': "Vous prenez des rendez-vous ou des réservations ?",
  'avvio.a-appuntamenti': "Un agenda par personne ou par ressource.",
  'avvio.d-fornitori': "Vous achetez auprès de fournisseurs ?",
  'avvio.a-fornitori': "Le fichier des fournisseurs et, si vous gérez un stock, les commandes avec la réception.",
  'avvio.d-fatture': "Vous émettez des factures ?",
  'avvio.a-fatture': "Numérotées par année, avec TVA, échéances et le fichier de la facture électronique.",
  'avvio.d-persone': "Combien de personnes utiliseront Kubo ?",
  'avvio.o-persone-solo': "Juste moi",
  'avvio.o-persone-poche': "De 2 à 5",
  'avvio.o-persone-molte': "Plus de 5",
  'avvio.d-squadra': "Qui travaille avec vous ?",
  'avvio.a-squadra': "Chacun se connecte avec son e-mail et voit ce dont son rôle a besoin. Vous pouvez aussi le faire plus tard.",
  'avvio.d-lumi': "Voulez-vous Lumi, l'assistant ?",
  'avvio.a-lumi': "Vous lui demandez les choses avec vos mots : « combien ai-je vendu cette semaine ? », « ajoute la taille aux articles ». Il propose, vous confirmez.",
  'avvio.d-esempi': "Voulez-vous voir Kubo avec des données d'exemple ?",
  'avvio.a-esempi': "Des clients, ventes et rendez-vous fictifs mais crédibles, pour tout essayer. Ils s'effacent en un clic.",
  'avvio.o-si': "Oui",
  'avvio.o-no': "Non",
  'avvio.collaboratore': "Collaborateur (voit et modifie, ne supprime pas)",
  'avvio.lettura': "Lecture seule",
  'avvio.nome': "Nom",
  'avvio.ruolo': "Rôle",
  'avvio.togli': "Retirer",
  'avvio.altra-persona': "+ Une autre personne",
  'avvio.password-provvisoria': "Chacun reçoit un mot de passe provisoire, que vous verrez à la fin.",
  'avvio.sezioni': "Je vous prépare ces sections",
  'avvio.nessuna-sezione': "Aucune : vous partez de zéro",
  'avvio.campi-spenti': { one: "{n} champ dont vous n'avez pas besoin reste désactivé (il se réactive depuis {personalizza})", other: "{n} champs dont vous n'avez pas besoin restent désactivés (ils se réactivent depuis {personalizza})" },
  'avvio.persone-ruolo': { one: "Une personne avec son rôle", other: "{n} personnes, chacune avec son rôle" },
  'avvio.lumi-acceso': "Lumi allumé",
  'avvio.lumi-spento': "Lumi éteint (vous l'allumez quand vous voulez)",
  'avvio.con-esempi': "Avec des données d'exemple, à retirer en un clic",
  'avvio.senza-esempi': "Sans données d'exemple",
  'avvio.ci-siamo': "On y est presque",
  'avvio.chi-sei': "Dernière chose : qui êtes-vous ? Vous serez le gérant, celui qui peut tout faire.",
  'avvio.preparo': "Préparation de Kubo…",
  'avvio.prepara': "Préparer Kubo",
  'avvio.pronto': "Kubo est prêt",
  'avvio.consegna': "Donnez à chacun son mot de passe provisoire. Cet écran ne s'affichera plus : copiez-les maintenant.",
  'avvio.entra': "Entrer dans Kubo",
  'avvio.tappa-sezioni': "Vos sections",
  'avvio.tappa-sezioni-testo': "Tout le logiciel est ici{esempi}. Chaque section est une liste que vous pouvez rechercher, filtrer, trier et afficher en colonnes.",
  'avvio.tappa-personalizza-testo': "Il manque un champ ? Il y en a un de trop ? D'ici, vous ajoutez, renommez et déplacez les champs sans jamais perdre de données. Les nouvelles sections se créent depuis « {nuova} ».",
  'avvio.tappa-lumi-testo': "Demandez avec vos mots : « combien ai-je vendu cette semaine ? », « ajoute la taille aux articles ». Lumi lit avec vos autorisations et propose ; c'est vous qui décidez.",
  'avvio.tappa-cruscotto': "Le tableau de bord",
  'avvio.tappa-cruscotto-testo': "Les chiffres qui comptent et ce qui demande votre attention, à jour pendant que vous travaillez. Il se modifie avec « {modifica} », en haut.",
  'avvio.n-di': "{n} sur {tot}",
  'avvio.salta': "Passer",
  'avvio.capito': "J'ai compris",
  'avvio.promemoria': "Vous regardez des données d'exemple",
  'avvio.toglili': "Les retirer",
  'avvio.conferma-togli': "Retirer toutes les données d'exemple ? Ce que vous avez ajouté reste.",
  'avvio.tolte': { one: "{n} ligne d'exemple retirée", other: "{n} lignes d'exemple retirées" },
  'avvio.aggiunte': { one: "{n} ligne d'exemple ajoutée", other: "{n} lignes d'exemple ajoutées" },
  'avvio.togli-esempi': "Retirer les données d'exemple",
  'avvio.rimetti-esempi': "Remettre les données d'exemple",
  'avvio.pagina-titolo': "Données d'exemple et visite guidée",
  'avvio.ci-sono': { one: "Il y a {n} ligne d'exemple, pour essayer Kubo sans crainte. Quand vous êtes prêt, retirez-la : elle disparaît (même si vous l'avez retouchée), ce que vous avez saisi reste et, là où il n'y a encore rien à vous, la numérotation repart de 1.", other: "Il y a {n} lignes d'exemple : des clients, mouvements et rendez-vous fictifs, pour essayer Kubo sans crainte. Quand vous êtes prêt, retirez-les : elles disparaissent toutes (même celles que vous avez retouchées), ce que vous avez saisi reste et, là où il n'y a encore rien à vous, la numérotation repart de 1." },
  'avvio.solo-titolare': "Seul le gérant peut les retirer.",
  'avvio.nessun-esempio': "Il n'y a pas de données d'exemple.",
  'avvio.rivedere': "Vous voulez revoir où se trouvent les choses ?",
  'avvio.rifai-giro': "Refaire la visite guidée",
  'avvio.lato': "Données d'exemple et visite",
  'avvio.lato-sezione': "Premiers pas",
};
