export default {
  'comune.benvenuto': 'Bienvenue dans Kubo',
  'comune.benvenuto-sotto': 'Le logiciel de gestion que vous montez à votre façon. Partez d\'un modèle, puis changez tout ce que vous voulez.',
  'comune.nome-azienda': 'Nom de l\'entreprise',
  'comune.tuo-nome': 'Votre nom',
  'comune.email': 'E-mail',
  'comune.password': 'Mot de passe',
  'comune.password-nuova': 'Mot de passe (8 caractères minimum)',
  'comune.valuta': 'Devise',
  'comune.da-dove': 'Par où commencer ? (vous pourrez en ajouter d\'autres ensuite)',
  'comune.codice-avvio': "Code de démarrage (affiché dans le terminal ou le journal où tourne Kubo)",
  'comune.codice-avvio-es': "ex. 3FA9C2D1",
  'comune.inizia': 'Commencer',
  'comune.lingua': 'Langue',
  'comune.accedi-per': 'Connectez-vous pour continuer.',
  'comune.accedi': 'Se connecter',
  'comune.gestione': 'Gestion',
  'comune.nuova-sezione': 'Nouvelle section',
  'comune.persone-permessi': 'Personnes et autorisations',
  'comune.esci': 'Se déconnecter',
  'comune.personalizza': 'Personnaliser',
  'comune.personalizza-sezione': 'Personnaliser cette section',
  'comune.nessuna-sezione': 'Aucune section pour l\'instant.',
  'comune.creane-una': 'En créer une',
  'comune.chiedi-titolare': 'Demandez au gérant d\'en créer une.',
  'comune.qualcosa-non-va': 'Un problème est survenu',
  'comune.errore-n': 'Erreur {stato}',
  'comune.percento': '{n} %',
  'comune.si': 'Oui',
  'comune.no': 'Non',
  'comune.si-min': 'oui',
  'comune.no-min': 'non',
  'comune.su': 'Monter',
  'comune.giu': 'Descendre',
  'comune.togli': 'Retirer',
  'comune.cerca': 'Rechercher…',
  'comune.carico': 'Chargement…',
};
