export default {
  'connettori.terzi': "Un connecteur tiers se copie dans le dossier « connettori » à côté des données : vous l'allumez ici après avoir vérifié sa somme.",
  'connettori.locale': "Installé à la main",
  'connettori.rotto': "Le connecteur ne se charge pas : vérifiez le fichier connettore.js",
  'connettori.stato-acceso': "Allumé",
  'connettori.stato-spento': "Éteint",
  'connettori.stato-incompleto': "À compléter",
  'connettori.stato-cambiato': "Modifié",
  'connettori.stato-rotto': "Cassé",
  'connettori.mancano': "Il manque encore : {cosa}",
  'connettori.cambiato': "Le fichier du connecteur a changé après son allumage : il reste arrêté jusqu'à ce que vous le rallumiez en vérifiant la somme.",
  'connettori.accendi': "Allumer",
  'connettori.spegni': "Éteindre",
  'connettori.accendi-titolo': "Allumer {nome} ?",
  'connettori.potra': "Il pourra :",
  'connettori.permesso': "{sezione} : {cosa}",
  'connettori.p-leggi': "lire",
  'connettori.p-crea': "créer",
  'connettori.p-modifica': "modifier",
  'connettori.p-elimina': "supprimer",
  'connettori.somma': "Somme de contrôle (SHA-256) du fichier : comparez-la avec celle publiée par son auteur.",
  'connettori.da-approvare': "Le code de ce connecteur n'a pas encore été exécuté : Kubo ne le charge qu'après que vous avez confirmé la somme ci-dessous. Vous verrez ensuite les sections qu'il peut utiliser.",
  'connettori.impostazioni': "Réglages",
  'connettori.salvato-segreto': "Enregistré",
  'connettori.cambia': "Changer",
  'connettori.togli': "Retirer",
  'connettori.interni': "Autoriser les adresses du réseau interne (un serveur au magasin, une caisse)",
  'connettori.salva': "Enregistrer",
  'connettori.salvato': "Enregistré",
  'connettori.prova': "Tester la connexion",
  'connettori.provo': "Test en cours…",
  'connettori.prova-ok': "Connexion réussie",
  'connettori.prova-no': "Ça ne marche pas : {motivo}",
  'connettori.collegamento': "Connexion",
  'connettori.webhook': "Adresse du webhook",
  'connettori.webhook-aiuto': "Collez-la dans les réglages des webhooks du service.",
  'connettori.indirizzo-segreto': "Adresse secrète",
  'connettori.indirizzo-aiuto': "Qui a cette adresse voit les données : ne la donnez qu'à ceux qui en ont besoin.",
  'connettori.account': "Compte",
  'connettori.collegato': "Connecté",
  'connettori.scollegato': "Non connecté",
  'connettori.scade': "Expire {quando}",
  'connettori.collega': "Connecter le compte",
  'connettori.ricollega': "Reconnecter",
  'connettori.oauth-ok': "Compte connecté",
  'connettori.oauth-scaduto': "La connexion a expiré : réessayez",
  'connettori.oauth-errore': "La connexion a échoué : consultez le journal",
  'connettori.abbinamenti': "Correspondance des champs",
  'connettori.abbinamenti-aiuto': "Les champs du connecteur et ceux de Kubo : si vous renommez un champ, la correspondance reste.",
  'connettori.sezione-manca': "La section « {nome} » manque",
  'connettori.facoltativo': "facultatif",
  'connettori.salva-abbinamenti': "Enregistrer les correspondances",
  'connettori.sincronizzazioni': "Synchronisations",
  'connettori.ogni': "toutes les {ogni}",
  'connettori.alle': "à {alle}",
  'connettori.ultimo': "Dernier passage : {quando}",
  'connettori.prossimo': "prochain : {quando}",
  'connettori.sincronizza': "Synchroniser maintenant",
  'connettori.giro-ok': "Fait",
  'connettori.coda': "En file : {attesa} · échouées : {fallite}",
  'connettori.riprova': "Relancer les échouées",
  'connettori.registro': "Journal",
  'connettori.registro-vuoto': "Rien pour l'instant : ici vous voyez ce qui arrive et ce qui part.",
  'connettori.col-quando': "Quand",
  'connettori.col-verso': "Sens",
  'connettori.col-esito': "Résultat",
  'connettori.col-cosa': "Quoi",
  'connettori.verso-entrata': "entrant",
  'connettori.verso-uscita': "sortant",
  'connettori.verso-giro': "tâche planifiée",
  'connettori.verso-azione': "action",
  'connettori.verso-prova': "test",
  'connettori.verso-oauth': "compte",
  'connettori.verso-sistema': "système",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "erreur",
  'connettori.esito-avviso': "alerte",
  'connettori.esito-ignorato': "ignoré",
  'connettori.copia': "Copier",
  'connettori.copiato': "Copié",
  'connettori.annulla': "Annuler",
  'connettori.conferma': "Confirmer",
  'connettori.fatto': "Fait",
  // la libreria delle integrazioni e le ricette
  'connettori.libreria': "Bibliothèque d'intégrations",
  'connettori.libreria-sotto': "{n} intégrations · {accese} actives. Les clés restent chiffrées dans Kubo et ne reviennent jamais au navigateur.",
  'connettori.cerca': "Rechercher : Stripe, facture, WhatsApp, livraison…",
  'connettori.categorie': "Catégories",
  'connettori.tutte': "Toutes",
  'connettori.trovate': "{n} trouvées",
  'connettori.le-tue': "Actives",
  'connettori.nessuna': "Aucune intégration trouvée.",
  'connettori.prova-http': "Absent ? Connectez-le avec HTTP / API REST",
  'connettori.smanettoni': "Pour les bricoleurs : l'API de Kubo est décrite en OpenAPI 3.1 sur /api/openapi-3.1.json, et un nouveau connecteur est un dossier avec un fichier (docs/CONNETTORI.md).",
  'connettori.f-gratis': "Gratuit",
  'connettori.f-facili': "Faciles",
  'connettori.f-italia': "Italie",
  'connettori.stato-da-approvare': "À approuver",
  'connettori.cat-pagamenti': "Paiements",
  'connettori.cat-cassa': "Caisse et TPE",
  'connettori.cat-negozi-online': "Boutiques en ligne",
  'connettori.cat-marketplace': "Places de marché",
  'connettori.cat-fatturazione': "Facturation",
  'connettori.cat-contabilita': "Comptabilité",
  'connettori.cat-banche': "Banques",
  'connettori.cat-spedizioni': "Livraisons",
  'connettori.cat-whatsapp': "WhatsApp",
  'connettori.cat-messaggi': "Messagerie",
  'connettori.cat-email': "E-mail",
  'connettori.cat-sms': "SMS",
  'connettori.cat-calendario': "Calendrier",
  'connettori.cat-prenotazioni': "Réservations",
  'connettori.cat-archivio': "Stockage et fichiers",
  'connettori.cat-produttivita': "Productivité",
  'connettori.cat-marketing': "Marketing",
  'connettori.cat-recensioni': "Avis",
  'connettori.cat-firma': "Signature",
  'connettori.cat-dati-aziende': "Données d'entreprises",
  'connettori.cat-automazione': "Automatisation",
  'connettori.cat-ia': "Intelligence artificielle",
  'connettori.cat-altro': "Autres",
  'connettori.costo-gratis': "Gratuit",
  'connettori.costo-a-consumo': "À l'usage",
  'connettori.costo-abbonamento': "Abonnement",
  'connettori.costo-contratto': "Sur contrat",
  'connettori.diff-facile': "Facile",
  'connettori.diff-media': "Moyenne",
  'connettori.diff-difficile': "Pour bricoleurs",
  'connettori.zona-IT': "Italie",
  'connettori.zona-UE': "Europe",
  'connettori.zona-mondo': "Monde",
  'connettori.prova-finto': "Testé avec un faux service",
  'connettori.prova-vero': "Testé avec le vrai service",
  'connettori.prova-finto-aiuto': "Les tests automatiques utilisent un faux service qui répond comme le vrai, selon la documentation des sources : avant de vous y fier, essayez en mode test.",
  'connettori.prova-vero-aiuto': "Ce connecteur a aussi été testé avec le vrai service.",
  'connettori.sito': "Site du service",
  'connettori.apri': "Ouvrir",
  'connettori.cosa-serve': "Ce qu'il vous faut",
  'connettori.passi': "Pas à pas",
  'connettori.costo': "Coût",
  'connettori.difficolta': "Difficulté",
  'connettori.fonti': "Sources ({n})",
  'connettori.permessi-titolo': "Ce qu'il pourra toucher",
  'connettori.nessun-permesso': "Aucune section de Kubo : seulement les appels que vous configurez.",
  'connettori.r-nessuna': "Pas encore de recette. Ajoutez-en une :",
  'connettori.r-tipo-uscita': "Sortante : quand une ligne change",
  'connettori.r-tipo-azione': "Bouton sur la fiche et Lumi",
  'connettori.r-tipo-entrata': "Entrante : le service écrit dans Kubo",
  'connettori.r-nome': "Nom de la recette",
  'connettori.r-attiva': "Active",
  'connettori.r-sezione': "Section",
  'connettori.r-eventi': "Quand la ligne est",
  'connettori.ev-crea': "créée",
  'connettori.ev-modifica': "modifiée",
  'connettori.ev-elimina': "supprimée",
  'connettori.ev-ripristina': "restaurée",
  'connettori.r-metodo': "Méthode",
  'connettori.r-percorso': "Chemin (après l'adresse de base) ou adresse complète",
  'connettori.r-indirizzo': "Adresse fournie par la plateforme (https://…)",
  'connettori.r-corpo': "Corps (JSON avec des repères ; vide = toute la ligne)",
  'connettori.r-segnaposto': "Repères : {campi}",
  'connettori.r-scrive': "Affiche un aperçu et demande confirmation avant l'envoi",
  'connettori.r-modo': "Si la ligne existe déjà",
  'connettori.modo-crea-o-aggiorna': "la mettre à jour, sinon la créer",
  'connettori.modo-crea': "toujours créer une nouvelle ligne",
  'connettori.modo-aggiorna': "mettre à jour seulement",
  'connettori.r-chiave': "Champ clé (pour retrouver la ligne)",
  'connettori.r-elenco': "Liste dans le JSON (facultatif, ex. items)",
  'connettori.r-idevento': "Id de l'événement dans le JSON (facultatif, contre les doublons)",
  'connettori.r-campi': "Correspondances (vide = les clés du JSON portant le nom des champs)",
  'connettori.r-da': "Chemin dans le JSON (ex. client.email)",
  'connettori.r-a': "Champ de Kubo",
  'connettori.r-aggiungi-campo': "Ajouter une correspondance",
  'connettori.r-indirizzo-entrata': "Adresse à donner au service (POST JSON)",
  'connettori.r-salva-prima': "Enregistrez et activez pour voir l'adresse.",
  'connettori.copia': "Connecter un autre service ainsi",
  'connettori.copia-aiuto': "Un second service avec son adresse, son authentification et ses recettes.",
  'connettori.copia-nome': "Nom du service (ex. CRM)",
  'connettori.copia-crea': "Créer",
  'connettori.copia-di': "Copie de « {nome} »",
  'connettori.togli-copia': "Retirer ce service",
  'connettori.togli-copia-conferma': "Retirer « {nome} » avec ses réglages, ses secrets et son journal ?",
  'connettori.tutte-lettura': "Toutes les sections (lecture seule)",
  'connettori.tutte-sezioni': "Toutes les sections",
  'connettori.dispositivo': "Connecter avec un code",
  'connettori.dispositivo-titolo': "Connecter {nome} avec un code",
  'connettori.dispositivo-passi': "Ouvre l'adresse ci-dessous (même depuis le téléphone), connecte-toi au service et saisis ce code. Kubo vérifie tout seul toutes les quelques secondes : tu peux laisser cette fenêtre ouverte.",
  'connettori.dispositivo-attesa': "En attente de la confirmation…",
  'connettori.dispositivo-scaduto': "Le code a expiré ou la fenêtre a été fermée : appuie à nouveau sur « Connecter avec un code ».",
  'connettori.dispositivo-chiudi': "Fermer",
  'connettori.ritorno': "Adresse de retour (à enregistrer dans le service)",
  'connettori.pubblico-titolo': "Adresse publique de Kubo",
  'connettori.pubblico-aiuto': "L'adresse par laquelle les services joignent Kubo depuis internet (ex. https://kubo.boutique.fr). Les webhooks et les retours de tous les connecteurs l'utilisent ; vide = celle du navigateur.",
  'connettori.pubblico-salvato': "Adresse enregistrée",
  'connettori.r-con-accesso': "Envoyer la clé ou le jeton même si l'adresse est sur un autre site",
};
