export default {
  'connettori.titolo': "Connecteurs",
  'connettori.spiega': "Reliez Kubo aux services que vous utilisez déjà : paiements, boutique en ligne, facturation électronique, e-mail, calendrier. Les clés restent chiffrées dans Kubo et ne reviennent jamais au navigateur.",
  'connettori.terzi': "Un connecteur tiers se copie dans le dossier « connettori » à côté des données : vous l'allumez ici après avoir vérifié sa somme.",
  'connettori.ufficiale': "Officiel",
  'connettori.locale': "Installé à la main",
  'connettori.rotto': "Le connecteur ne se charge pas : vérifiez le fichier connettore.js",
  'connettori.stato-acceso': "Allumé",
  'connettori.stato-spento': "Éteint",
  'connettori.stato-incompleto': "À compléter",
  'connettori.stato-cambiato': "Modifié",
  'connettori.stato-rotto': "Cassé",
  'connettori.mancano': "Il manque encore : {cosa}",
  'connettori.cambiato': "Le fichier du connecteur a changé après son allumage : il reste arrêté jusqu'à ce que vous le rallumiez en vérifiant la somme.",
  'connettori.accendi': "Allumer",
  'connettori.spegni': "Éteindre",
  'connettori.accendi-titolo': "Allumer {nome} ?",
  'connettori.potra': "Il pourra :",
  'connettori.permesso': "{sezione} : {cosa}",
  'connettori.p-leggi': "lire",
  'connettori.p-crea': "créer",
  'connettori.p-modifica': "modifier",
  'connettori.p-elimina': "supprimer",
  'connettori.somma': "Somme de contrôle (SHA-256) du fichier : comparez-la avec celle publiée par son auteur.",
  'connettori.da-approvare': "Le code de ce connecteur n'a pas encore été exécuté : Kubo ne le charge qu'après que vous avez confirmé la somme ci-dessous. Vous verrez ensuite les sections qu'il peut utiliser.",
  'connettori.impostazioni': "Réglages",
  'connettori.salvato-segreto': "Enregistré",
  'connettori.cambia': "Changer",
  'connettori.togli': "Retirer",
  'connettori.interni': "Autoriser les adresses du réseau interne (un serveur au magasin, une caisse)",
  'connettori.salva': "Enregistrer",
  'connettori.salvato': "Enregistré",
  'connettori.prova': "Tester la connexion",
  'connettori.provo': "Test en cours…",
  'connettori.prova-ok': "Connexion réussie",
  'connettori.prova-no': "Ça ne marche pas : {motivo}",
  'connettori.collegamento': "Connexion",
  'connettori.webhook': "Adresse du webhook",
  'connettori.webhook-aiuto': "Collez-la dans les réglages des webhooks du service.",
  'connettori.indirizzo-segreto': "Adresse secrète",
  'connettori.indirizzo-aiuto': "Qui a cette adresse voit les données : ne la donnez qu'à ceux qui en ont besoin.",
  'connettori.account': "Compte",
  'connettori.collegato': "Connecté",
  'connettori.scollegato': "Non connecté",
  'connettori.scade': "Expire {quando}",
  'connettori.collega': "Connecter le compte",
  'connettori.ricollega': "Reconnecter",
  'connettori.oauth-ok': "Compte connecté",
  'connettori.oauth-scaduto': "La connexion a expiré : réessayez",
  'connettori.oauth-errore': "La connexion a échoué : consultez le journal",
  'connettori.abbinamenti': "Correspondance des champs",
  'connettori.abbinamenti-aiuto': "Les champs du connecteur et ceux de Kubo : si vous renommez un champ, la correspondance reste.",
  'connettori.sezione-manca': "La section « {nome} » manque",
  'connettori.facoltativo': "facultatif",
  'connettori.salva-abbinamenti': "Enregistrer les correspondances",
  'connettori.sincronizzazioni': "Synchronisations",
  'connettori.ogni': "toutes les {ogni}",
  'connettori.alle': "à {alle}",
  'connettori.ultimo': "Dernier passage : {quando}",
  'connettori.prossimo': "prochain : {quando}",
  'connettori.sincronizza': "Synchroniser maintenant",
  'connettori.giro-ok': "Fait",
  'connettori.coda': "En file : {attesa} · échouées : {fallite}",
  'connettori.riprova': "Relancer les échouées",
  'connettori.registro': "Journal",
  'connettori.registro-vuoto': "Rien pour l'instant : ici vous voyez ce qui arrive et ce qui part.",
  'connettori.col-quando': "Quand",
  'connettori.col-verso': "Sens",
  'connettori.col-esito': "Résultat",
  'connettori.col-cosa': "Quoi",
  'connettori.verso-entrata': "entrant",
  'connettori.verso-uscita': "sortant",
  'connettori.verso-giro': "tâche planifiée",
  'connettori.verso-azione': "action",
  'connettori.verso-prova': "test",
  'connettori.verso-oauth': "compte",
  'connettori.verso-sistema': "système",
  'connettori.copia': "Copier",
  'connettori.copiato': "Copié",
  'connettori.annulla': "Annuler",
  'connettori.conferma': "Confirmer",
  'connettori.fatto': "Fait",
};
