// Area «desktop» (web/moduli/desktop.js): rete, backup e versioni nuove.
export default {
  'desktop.tipo-giornaliero': "Du jour",
  'desktop.tipo-modifica': "Avant une modification",
  'desktop.tipo-manuale': "Manuelle",
  'desktop.tipo-sicurezza': "Avant une restauration",
  'desktop.tipo-caricato': "Importée",
  'desktop.qr': "QR code avec l'adresse",
  'desktop.rete-titolo': "Connecter d'autres appareils",
  'desktop.lato-rete': "Connecter des appareils",
  'desktop.un-momento': "Un instant…",
  'desktop.copiato': "Copié",
  'desktop.copia-fallita': "Copie impossible : sélectionnez-le à la main",
  'desktop.indirizzo': "Adresse",
  'desktop.altra-rete': "Ou, sur un autre réseau du bureau",
  'desktop.copia-indirizzo': "Copier l'adresse",
  'desktop.codice': "Code",
  'desktop.passo-telefono': "Téléphone ou tablette :",
  'desktop.passo-telefono-testo': "visez le code avec l'appareil photo et touchez le lien.",
  'desktop.passo-computer': "Un autre ordinateur :",
  'desktop.passo-computer-codice': "ouvrez le navigateur et tapez l'adresse. Avec l'appli Lumi, choisissez « Se connecter à Lumi sur le réseau » et tapez le code.",
  'desktop.passo-computer-indirizzo': "ouvrez le navigateur et tapez l'adresse. Avec l'appli Lumi, choisissez « Se connecter à Lumi sur le réseau » et tapez l'adresse.",
  'desktop.solo-qui': "Pour le moment, Lumi ne répond qu’à cet ordinateur.",
  'desktop.apri-rete': "Pour l'utiliser aussi depuis d'autres appareils, ouvrez dans l'appli Lumi le menu de la barre du haut (ou de la zone de notification) et activez « Ouvert au réseau local ».",
  'desktop.da-terminale': "Si vous le lancez depuis un terminal :",
  'desktop.non-in-rete': "Cet ordinateur ne semble connecté à aucun réseau. Branchez-le au Wi-Fi ou au câble du bureau et rechargez la page.",
  'desktop.stessa-rete': "Les autres appareils doivent être sur le même réseau (le même Wi-Fi ou le même câble). S'ils ne se connectent pas, vérifiez que le pare-feu de cet ordinateur laisse passer Lumi.",
  'desktop.backup': "Sauvegardes",
  'desktop.fai-adesso': "Sauvegarder maintenant",
  'desktop.copia-in-corso': "Copie en cours…",
  'desktop.fatto': "Sauvegarde effectuée",
  'desktop.ultimo': "Dernière sauvegarde",
  'desktop.nessuno-ancora': "Aucune pour l’instant",
  'desktop.copie-tenute': "Copies conservées",
  'desktop.in-tutto': "{peso} au total",
  'desktop.spiega-automatici': "Chaque jour, Lumi fait tout seul une copie de la base de données, et une autre avant chaque modification de la structure ou chaque import. Il garde {giornalieri} copies quotidiennes, {settimanali} hebdomadaires et {mensili} mensuelles ; celles faites à la main restent jusqu'à ce que vous les supprimiez. Les pièces jointes vont dans le dossier « allegati », en ne copiant que les nouvelles.",
  'desktop.spiega-spenti': "Les sauvegardes automatiques sont désactivées (LUMI_BACKUP=0) : pensez à les faire à la main ou avec vos propres outils.",
  'desktop.cartella-esempio': "Par exemple {a} ou {b}",
  'desktop.cartella-nuova': "Désormais, les sauvegardes vont là",
  'desktop.cartella-tornata': "Les sauvegardes reviennent à côté des données",
  'desktop.scegli-cartella': "Choisir un dossier…",
  'desktop.dove': "Où vont les sauvegardes",
  'desktop.in-memoria': "(base de données en mémoire : pas de sauvegarde)",
  'desktop.nota-esterna': "Un dossier choisi par vous. Si le disque n'est pas branché, la copie du jour va à côté des données et un avertissement s'affiche ici.",
  'desktop.nota-accanto': "À côté des données, sur cet ordinateur. Mieux vaut une seconde copie ailleurs : un disque externe, ou un dossier synchronisé (Dropbox, OneDrive, iCloud, Google Drive).",
  'desktop.usa-cartella': "Utiliser ce dossier",
  'desktop.torna-accanto': "Revenir à côté des données",
  'desktop.vuoto': "Pas encore de sauvegarde. La première arrive toute seule d'ici quelques minutes, ou faites-la maintenant.",
  'desktop.col-quando': "Quand",
  'desktop.col-tipo': "Type",
  'desktop.col-dimensione': "Taille",
  'desktop.accanto-ai-dati': "à côté des données",
  'desktop.scarica': "Télécharger",
  'desktop.ripristina': "Restaurer",
  'desktop.elimina': "Supprimer cette sauvegarde",
  'desktop.elimina-conferma': "Supprimer la sauvegarde du {quando} ? Elle ne pourra plus être restaurée.",
  'desktop.eliminato': "Sauvegarde supprimée",
  'desktop.ripristino-titolo': "Revenir à cette sauvegarde ?",
  'desktop.ripristino-prima': "Tout redeviendra comme le",
  'desktop.ripristino-dopo': ". Tout ce qui a été fait après disparaît de la vue.",
  'desktop.ripristino-nota': "Avant, Lumi fait une copie de l'état actuel (« {tipo} ») : si vous changez d'avis, vous restaurez celle-là et vous ne perdez rien. Ceux qui travaillent sur d'autres appareils verront la page se recharger.",
  'desktop.capito': "J’ai compris, je veux revenir à ce moment-là",
  'desktop.annulla': "Annuler",
  'desktop.ripristino-in-corso': "Restauration en cours…",
  'desktop.ripristinato': "Restauré",
  'desktop.ripristinato-altro': "Le gérant a restauré une sauvegarde : rechargement…",
  'desktop.caricato': "Sauvegarde importée : {azienda}, {persone}, {sezioni}. Vous la trouverez en haut de la liste.",
  'desktop.persone': {"one": "{n} personne", "other": "{n} personnes"},
  'desktop.sezioni': {"one": "{n} section", "other": "{n} sections"},
  'desktop.carica': "Importer une sauvegarde",
  'desktop.carica-nota': "Un fichier .db téléchargé d'ici, même depuis un autre ordinateur. Lumi le vérifie et l'ajoute à la liste : ensuite, c'est vous qui décidez de le restaurer ou non.",
  'desktop.scegli-file': "Choisir le fichier…",
  'desktop.uscita-versione': "Nouvelle version disponible :",
  'desktop.novita': "les nouveautés",
  'desktop.aggiornato': "Vous avez la dernière version.",
  'desktop.versioni': "Nouvelles versions",
  'desktop.stai-usando': "Vous utilisez Lumi",
  'desktop.controlla-ogni-giorno': "Vérifier chaque jour si une nouvelle version est sortie et me prévenir",
  'desktop.versioni-nota': "Lumi demande seulement à GitHub le numéro de la dernière version publiée : il n'envoie aucune donnée de l'entreprise et n'installe rien tout seul. C'est vous qui mettez à jour, quand vous voulez, après une sauvegarde.",
  'desktop.controlla-adesso': "Vérifier maintenant",
  'desktop.avviso-versione': "Nouvelle version de Lumi :",
  'desktop.dettagli': "Détails",
  'desktop.chiudi': "Fermer",
  'desktop.solo-titolare': "Les sauvegardes sont gérées par le gérant.",
};
