// E-invoices (web/moduli/fatture.js): received invoices, virtual stamp duty, numbering.
export default {
  'fatture.aggiorna-chiedi': "Les factures de Lumi se sont enrichies : prix jusqu'à 8 décimales, caisse de prévoyance, Administration publique, factures reçues. Ajouter les nouveaux champs maintenant ? Aucune donnée n'est perdue.",
  'fatture.aggiornato': "Factures mises à jour",
  'fatture.bloccata': "Émise · verrouillée",
  'fatture.bloccata-nota': "Une facture émise ne se modifie plus : on la corrige avec un avoir ou une note de débit. Vous pouvez changer le statut du paiement et les notes internes.",
  'fatture.bollo': "Timbre virtuel",
  'fatture.bollo-nota': "Le timbre se paie avec le F24 (codes 2521-2524) ou depuis l'espace réservé de l'Agence des recettes, qui calcule le montant chaque trimestre. Comptent les factures émises avec le timbre coché.",
  'fatture.chiudi': "Fermer",
  'fatture.codice-tributo': "Code de l'impôt",
  'fatture.crea-integrazione': "Créer l'intégration",
  'fatture.da-integrare': "À intégrer",
  'fatture.da-pagare': "À payer",
  'fatture.da-versare': "À verser",
  'fatture.emesse': "Émises",
  'fatture.entro': "Avant le",
  'fatture.fatture-con-bollo': "Factures avec timbre",
  'fatture.fornitore-nuovo': "nouveau",
  'fatture.gia-importata': "{numero} était déjà là",
  'fatture.importa': "Importer des factures",
  'fatture.importata': "{numero} du {data} · {totale}",
  'fatture.integra-conferma': "Créer l'intégration (ou l'autofacture) de la facture {numero} ? Elle naît en brouillon : vous la vérifiez et l'émettez.",
  'fatture.integra-nota': "Facture reçue en autoliquidation ou d'un fournisseur étranger : il faut l'intégration TD16-TD19.",
  'fatture.integrazione-creata': "Intégration {tipo} créée en brouillon",
  'fatture.intestata-ad-altri': "n'est pas adressée à votre numéro de TVA",
  'fatture.leggo': "Lecture…",
  'fatture.manca-modello': "Ajoutez d'abord le modèle « Factures et facture électronique ».",
  'fatture.mancano': "Numéros manquants",
  'fatture.nessun-buco': "aucun trou",
  'fatture.nessuna-emessa': "Aucune facture émise cette année.",
  'fatture.niente-da-integrare': "Rien à intégrer.",
  'fatture.niente-da-pagare': "Rien à payer.",
  'fatture.numerazione': "Numérotation",
  'fatture.numerazione-nota': "Les numéros se suivent par série et par année, sans trou. Un trou vient souvent d'une facture saisie à la main : vérifiez avant d'émettre la suivante.",
  'fatture.ricevute': "Reçues",
  'fatture.ricevute-nota': "Téléchargez les factures depuis le tiroir fiscal ou la PEC et déposez-les ici : aussi les .p7m signés et les fichiers à plusieurs factures. Lumi crée le fournisseur, enregistre la charge et l'échéance.",
  'fatture.serie': "Série",
  'fatture.serie-principale': "principale",
  'fatture.solo-xml': "Fichiers .xml ou .p7m uniquement",
  'fatture.stampa': "Imprimer",
  'fatture.titolo': "Factures électroniques",
  'fatture.totale': "Total",
  'fatture.trascina': "Déposez ici les factures reçues",
  'fatture.trascina-nota': "ou touchez pour choisir les fichiers (.xml, .xml.p7m)",
  'fatture.trimestre': "Trimestre",
  'fatture.trimestre-n': "{n}e trimestre",
  'fatture.troppo-grande': "Fichier trop volumineux (3,5 Mo au maximum)",
  'fatture.tutte-le-ricevute': "Toutes les factures reçues →",
  'fatture.ultimo': "Dernier",
  'fatture.vedi': "Voir la facture",
  'fatture.vista': "Facture reçue",
};
