// Fiscalité (web/moduli/fisco.js).
export default {
  'fisco.titolo': "Fiscalité",
  'fisco.anno': "Année",
  'fisco.responsabilita': "Kubo calcule et prépare à partir de vos données : vérifiez avant de payer ou d'envoyer. La responsabilité reste celle du contribuable.",
  'fisco.scheda-riepilogo': "À payer",
  'fisco.scheda-iva': "TVA",
  'fisco.scheda-forfettario': "Forfaitaire",
  'fisco.scheda-f24': "F24",
  'fisco.scheda-ritenute': "Retenues",
  'fisco.scheda-scadenze': "Échéances",
  'fisco.scheda-commercialista': "Pour l'expert-comptable",
  'fisco.scheda-impostazioni': "Paramètres",
  'fisco.da-pagare-anno': "Reste à payer cette année",
  'fisco.prossimo': "Prochain versement",
  'fisco.niente': "Rien en vue.",
  'fisco.regime': "Régime",
  'fisco.coeff': "coefficient {n} %",
  'fisco.regime-forfettario': "Forfaitaire (forfettario)",
  'fisco.regime-semplificato': "Simplifié",
  'fisco.regime-ordinario': "Ordinaire",
  'fisco.periodicita-trimestrale': "TVA trimestrielle",
  'fisco.periodicita-mensile': "TVA mensuelle",
  'fisco.manca-ricevute': "Pour la TVA sur les achats et les retenues, ajoutez la section « Factures reçues ».",
  'fisco.apri-impostazioni': "Ouvrir les paramètres",
  'fisco.prossimi-versamenti': "Prochains versements",
  'fisco.data': "Date",
  'fisco.cosa': "Quoi",
  'fisco.codice': "Code",
  'fisco.anno-rif': "Année réf.",
  'fisco.importo': "Montant",
  'fisco.vedi-f24': "F24",
  'fisco.prossime-scadenze': "Prochaines échéances",
  'fisco.mese-n': "Mois {n}",
  'fisco.trimestre-n': "{n}e trimestre",
  'fisco.lipe-trimestre': "LIPE {n}e trimestre",
  'fisco.liquidazioni': "Liquidations périodiques",
  'fisco.periodo': "Période",
  'fisco.iva-vendite': "TVA ventes",
  'fisco.iva-acquisti': "TVA déductible",
  'fisco.riporti': "Reports",
  'fisco.interessi': "Intérêts 1 %",
  'fisco.da-versare': "À verser",
  'fisco.scadenza': "Échéance",
  'fisco.a-credito': "crédit {importo}",
  'fisco.riportato': "reporté (jusqu'à 100 €)",
  'fisco.acconto-dicembre': "Acompte de TVA de décembre",
  'fisco.acconto-dovuto': "Acompte de {importo} avec la méthode {metodo} : code {codice}, avant le {data}.",
  'fisco.acconto-no': "Acompte non dû (moins de 103,29 € ou données manquantes : ajoutez-les dans les paramètres).",
  'fisco.acconto-nota': "Historique : 88 % du montant versé pour la dernière période de l'an dernier. Prévisionnel : 88 % de ce que vous prévoyez pour la dernière période de cette année. Kubo choisit le plus bas.",
  'fisco.metodo-storico': "historique",
  'fisco.metodo-previsionale': "prévisionnelle",
  'fisco.lipe': "Déclaration des liquidations périodiques (LIPE)",
  'fisco.lipe-passo-1': "Téléchargez ci-dessus le fichier XML du trimestre.",
  'fisco.lipe-passo-2': "Connectez-vous à « Fatture e Corrispettivi » sur le site de l'Agenzia delle Entrate avec SPID, CIE ou CNS.",
  'fisco.lipe-passo-3': "Ouvrez le service des liquidations périodiques de TVA et choisissez l'envoi d'un fichier déjà prêt.",
  'fisco.lipe-passo-4': "Chargez le fichier et confirmez : le système le contrôle tout de suite.",
  'fisco.lipe-passo-5': "Téléchargez l'accusé de réception après quelques minutes et conservez-le.",
  'fisco.lipe-nota': "Échéances : 31 mai, 30 septembre, 30 novembre et fin février. Si quelque chose ne colle pas, la déclaration préremplie de l'Agence aide à comparer.",
  'fisco.registri': "Registres de TVA",
  'fisco.registri-nota': "Les registres des ventes, des achats et des recettes journalières sont dans le dossier pour l'expert-comptable, en CSV et Excel.",
  'fisco.debito-prec': "dette préc. {importo}",
  'fisco.credito-prec': "crédit préc. {importo}",
  'fisco.credito-anno': "crédit année préc. {importo}",
  'fisco.meno-acconto': "acompte {importo}",
  'fisco.non-forfettario': "L'entreprise n'est pas au régime forfaitaire : changez-le dans les paramètres.",
  'fisco.sim-quanto': "Si j'encaisse encore (€)",
  'fisco.sim-esito': "En encaissant {piu} de plus, vous payez environ {tasse} de plus en impôt et cotisations : il vous reste {resta}.",
  'fisco.niente-acconti': "Aucun acompte dû.",
  'fisco.incassato': "Encaissé",
  'fisco.incassato-nota': "factures avec « Payée le » cette année",
  'fisco.reddito': "Revenu",
  'fisco.contributi': "Cotisations INPS",
  'fisco.imposta': "Impôt de substitution",
  'fisco.aliquota-n': "taux {n} %",
  'fisco.soglia': "Seuil de 85 000 €",
  'fisco.soglia-nota': "Vous avez utilisé {usato} % du seuil : il reste {margine}. Au-delà de 100 000 €, vous sortez du régime immédiatement.",
  'fisco.simulazione': "Simulation",
  'fisco.simula': "Calculer",
  'fisco.acconti-anno': "Acomptes {anno}",
  'fisco.acconti-base': "Calculés sur l'impôt de l'année précédente : {importo}.",
  'fisco.saldo-stima': "Solde estimé à payer l'an prochain : {importo}.",
  'fisco.gestione-artigiani': "INPS artisans",
  'fisco.gestione-commercianti': "INPS commerçants",
  'fisco.gestione-separata': "Gestion séparée",
  'fisco.gestione-cassa': "Caisse professionnelle",
  'fisco.gestione-nessuna': "Aucune",
  'fisco.stampa-f24': "Imprimer le F24",
  'fisco.stampa': "Imprimer ou enregistrer en PDF",
  'fisco.chiudi': "Fermer",
  'fisco.f24-del': "F24 du {data}",
  'fisco.sezione': "Section",
  'fisco.rateazione': "Échelonnement / période",
  'fisco.sezione-erario': "Trésor",
  'fisco.sezione-inps': "INPS",
  'fisco.sezione-locali': "Impôts locaux",
  'fisco.f24-come': "Recopiez les lignes dans F24 web (Agenzia delle Entrate) ou dans votre banque en ligne. Si vous compensez un crédit, ou si le solde est nul, vous devez utiliser les services de l'Agence.",
  'fisco.registro-ritenute': "Retenues effectuées",
  'fisco.pagata-il': "Payée le",
  'fisco.percipiente': "Bénéficiaire",
  'fisco.compenso': "Honoraires",
  'fisco.ritenuta': "Retenue",
  'fisco.versare-entro': "À verser avant le",
  'fisco.ritenute-vuoto': "Aucune retenue : elles s'enregistrent sur les factures reçues des professionnels (retenue et date de paiement).",
  'fisco.riepilogo-cu': "Récapitulatif pour la CU et le 770",
  'fisco.cf': "Code fiscal",
  'fisco.causale': "Motif",
  'fisco.cu-nota': "Ce sont les données à déclarer : la CU se remet avant le 16 mars et s'envoie à l'Agence ; le 770 avant le 31 octobre. Kubo ne les envoie pas.",
  'fisco.scadenze-anno': "Échéances {anno}",
  'fisco.scadenze-nota': "Seulement les échéances de votre régime. Les dates tombant un samedi ou un jour férié sont déjà reportées au jour ouvrable suivant.",
  'fisco.dal': "Du",
  'fisco.al': "Au",
  'fisco.scarica-pacchetto': "Télécharger le zip",
  'fisco.pacchetto': "Dossier pour l'expert-comptable",
  'fisco.pacchetto-cosa': "Un zip avec les copies XML des factures émises, les registres de TVA, les liquidations, le livre de caisse et les retenues en CSV et Excel, et un récapitulatif en PDF.",
  'fisco.quando-professionista': "Quand il faut vraiment un professionnel",
  'fisco.pro-dichiarazioni': "Vous pouvez envoyer vous-même les déclarations (revenus, TVA annuelle, 770) avec SPID ; pour les faire envoyer par quelqu'un, il faut un intermédiaire habilité.",
  'fisco.pro-visto': "Pour compenser dans le F24 un crédit de TVA de plus de 5 000 €, il faut le visa de conformité d'un professionnel.",
  'fisco.pro-consulenza': "Choix du régime, réduction INPS de 35 %, échelonnements, contrôles et avis : c'est du conseil, demandez à un expert-comptable.",
  'fisco.pro-redditi': "L'IRPEF, l'IRES et l'IRAP du régime ordinaire ou simplifié sont calculés par l'expert-comptable ou la préremplie, pas par Kubo.",
  'fisco.salva': "Enregistrer",
  'fisco.salvate': "Paramètres enregistrés",
  'fisco.sezioni': "Sections pour la fiscalité",
  'fisco.sezioni-cosa': "Ajoute « Factures reçues » (achats et retenues) et, si vous vendez au comptoir, « Recettes journalières ».",
  'fisco.anche-corrispettivi': "Aussi les recettes journalières",
  'fisco.aggiungi-sezioni': "Ajouter les sections",
  'fisco.sezioni-aggiunte': "Sections ajoutées",
  'fisco.manca-piva': "Il manque le numéro de TVA ou le code fiscal de l'entreprise.",
  'fisco.apri-documenti': "Ajoutez-les dans Documents",
  'fisco.gruppo-regime': "Régime et activité",
  'fisco.gruppo-inps': "Cotisations INPS",
  'fisco.gruppo-forfettario': "Forfaitaire",
  'fisco.gruppo-iva': "TVA",
  'fisco.gruppo-altro': "Autres",
  'fisco.promemoria': "Fiscalité : {cosa} le {data}",
  'fisco.imp-regime': "Régime fiscal",
  'fisco.impn-regime': "Si vous ne le savez pas, demandez à votre expert-comptable : ce choix change tout.",
  'fisco.imp-periodicita': "Liquidation de la TVA",
  'fisco.impn-periodicita': "Trimestrielle avec 1 % d'intérêts, si votre chiffre d'affaires le permet.",
  'fisco.imp-ateco': "Code ATECO",
  'fisco.impn-ateco': "Il figure sur le certificat d'attribution du numéro de TVA.",
  'fisco.imp-coefficiente': "Coefficient de rentabilité %",
  'fisco.impn-coefficiente': "Vide : celui du tableau officiel pour votre ATECO.",
  'fisco.imp-gestione': "Régime de cotisation",
  'fisco.impn-gestione': "Pour les caisses professionnelles, Kubo ne calcule pas les cotisations.",
  'fisco.imp-riduzione35': "Réduction de 35 % des cotisations",
  'fisco.impn-riduzione35': "Seulement les artisans et commerçants forfaitaires qui l'ont demandée à l'INPS.",
  'fisco.imp-ante1996': "Cotisations versées avant 1996",
  'fisco.impn-ante1996': "Si vous avez cotisé avant le 31/12/1995, le plafond est de 93 707 € au lieu de 122 295 €.",
  'fisco.imp-aliquotaridotta': "Taux de 5 % (cinq premières années)",
  'fisco.impn-aliquotaridotta': "Pour les nouvelles activités qui remplissent les conditions ; sinon 15 %.",
  'fisco.imp-impostaannoprecedente': "Impôt de substitution de l'an dernier (€)",
  'fisco.impn-impostaannoprecedente': "Base des acomptes. Vide : Kubo le calcule à partir des données.",
  'fisco.imp-accontiversatiannoprecedente': "Acomptes versés l'an dernier (€)",
  'fisco.impn-accontiversatiannoprecedente': "Pour calculer le solde de juin.",
  'fisco.imp-contributiversati': "Cotisations versées cette année (€)",
  'fisco.impn-contributiversati': "Elles se déduisent du revenu. Vide : on utilise l'estimation.",
  'fisco.imp-sedeinps': "Code du bureau INPS",
  'fisco.impn-sedeinps': "Pour la section INPS du F24.",
  'fisco.imp-matricolainps': "Matricule ou code INPS",
  'fisco.impn-matricolainps': "Dans la gestion séparée, c'est votre code fiscal.",
  'fisco.imp-creditoannoprecedente': "Crédit de TVA de l'an dernier (€)",
  'fisco.impn-creditoannoprecedente': "Utilisé dans les liquidations tant qu'il en reste.",
  'fisco.imp-accontoivastorico': "Versé pour la dernière période de l'an dernier (€)",
  'fisco.impn-accontoivastorico': "Pour l'acompte selon la méthode historique.",
  'fisco.imp-accontoivaprevisto': "Prévu pour la dernière période de cette année (€)",
  'fisco.impn-accontoivaprevisto': "Pour la méthode prévisionnelle. Vide : méthode historique seule tant que la dernière période n'est pas close.",
  'fisco.imp-camerale': "Droit annuel de la Chambre de commerce (€)",
  'fisco.impn-camerale': "Votre Chambre de commerce vous indique le montant.",
  'fisco.imp-provinciacciaa': "Province de la Chambre de commerce",
  'fisco.impn-provinciacciaa': "Sigle, par exemple MI.",
  'fisco.imp-bollo': "Timbre virtuel sur les factures",
  'fisco.impn-bollo': "Toujours actif au régime forfaitaire.",
  'fisco.imp-sostituto': "Je suis agent de retenue",
  'fisco.impn-sostituto': "Vous payez des professionnels en retenant l'impôt.",
  'fisco.v-iva': "TVA de la période {periodo}",
  'fisco.v-iva-saldo': "Solde annuel de TVA",
  'fisco.v-iva-acconto': "Acompte de TVA",
  'fisco.v-forf-saldo': "Solde de l'impôt de substitution {anno}",
  'fisco.v-forf-acconto': "Acompte de l'impôt de substitution {anno}",
  'fisco.v-inps-acconto': "Acompte de cotisations INPS {anno}",
  'fisco.v-inps-fissi': "Cotisations INPS fixes",
  'fisco.v-iva-integrazioni': "TVA des intégrations, mois {periodo}",
  'fisco.v-bollo': "Timbre virtuel, {periodo}e trimestre",
  'fisco.v-ritenute': "Retenues du mois {periodo}",
  'fisco.v-camerale': "Droit de la Chambre de commerce {anno}",
  'fisco.sc-iva-mese': "Versement de TVA du mois {periodo}",
  'fisco.sc-iva-trimestre': "Versement de TVA du {periodo}e trimestre",
  'fisco.sc-iva-saldo': "Solde annuel de TVA",
  'fisco.sc-iva-acconto': "Acompte de TVA",
  'fisco.sc-lipe': "LIPE du {periodo}e trimestre",
  'fisco.sc-dichiarazione-iva': "Déclaration de TVA {anno}",
  'fisco.sc-forf-saldo-acconto': "Solde et premier acompte de l'impôt de substitution",
  'fisco.sc-redditi-saldo-acconto': "Solde et premier acompte des impôts sur le revenu",
  'fisco.sc-forf-acconto2': "Second acompte de l'impôt de substitution",
  'fisco.sc-redditi-acconto2': "Second acompte des impôts sur le revenu",
  'fisco.sc-dichiarazione-redditi': "Déclaration de revenus {anno}",
  'fisco.sc-inps-fissi': "Cotisations INPS fixes, échéance {periodo}",
  'fisco.sc-inps-saldo-acconto': "Cotisations INPS : solde et acompte",
  'fisco.sc-inps-riduzione': "Demande de réduction INPS de 35 %",
  'fisco.sc-bollo': "Timbre virtuel, {periodo}e trimestre {anno}",
  'fisco.sc-ritenute': "Retenues du mois {periodo}",
  'fisco.sc-cu-consegna': "CU aux bénéficiaires",
  'fisco.sc-cu-invio': "CU à l'Agence (travail indépendant)",
  'fisco.sc-modello-770': "Modèle 770",
  'fisco.sc-camerale': "Droit de la Chambre de commerce",
  'fisco.av-da-integrare': "Des factures reçues en autoliquidation ou de l'étranger sont encore à intégrer : tant que vous n'émettez pas l'intégration (TD16-TD19, depuis Factures électroniques), elles restent hors des registres de TVA.",
  'fisco.av-vicino-85': "Vous approchez du seuil de 85 000 € : si vous le dépassez, vous sortez du forfaitaire l'an prochain.",
  'fisco.av-oltre-85': "Vous avez dépassé 85 000 € : vous sortez du forfaitaire l'an prochain. Parlez-en à un expert-comptable.",
  'fisco.av-oltre-100': "Vous avez dépassé 100 000 € : vous sortez du forfaitaire immédiatement, avec la TVA dès l'opération qui a franchi le seuil. Il vous faut un expert-comptable.",
  'fisco.av-fuori-dal-regime': "L'an dernier vous avez encaissé plus de 85 000 € : cette année vous ne pourriez pas être au forfaitaire. Vérifiez avec un expert-comptable.",
  'fisco.av-contributi-stimati': "Les cotisations déduites sont estimées : indiquez dans les paramètres celles réellement versées cette année.",
  'fisco.av-cassa-professionale': "Avec une caisse professionnelle, c'est la caisse qui calcule les cotisations : Kubo ne les compte pas.",
  'fisco.av-incassi-senza-data': "Certaines factures payées n'ont pas de « Payée le » : elles comptent à la date de la facture.",
  'fisco.av-visto-conformita': "Le crédit de TVA dépasse 5 000 € : pour le compenser dans le F24, il faut le visa de conformité.",
  'fisco.av-forfettario-niente-iva': "Au forfaitaire, il n'y a ni TVA à liquider ni LIPE : voyez le tableau de bord du forfaitaire.",
  'fisco.av-redditi-professionista': "L'IRPEF, l'IRES et l'IRAP ne sont pas ici : l'expert-comptable ou la préremplie les calculent.",
  'fisco.av-inps-cassetto': "Les échéances fixes INPS sont une estimation : le F24 officiel est dans le Cassetto previdenziale.",
  'fisco.av-cu-intermediario': "Avec 20 CU ou plus, vos identifiants ne suffisent pas : il faut Entratel ou un intermédiaire.",
  'fisco.av-cu-fisconline': "Avec moins de 20 CU, vous pouvez les envoyer vous-même avec vos identifiants.",
  'fisco.imp-anno-rif': "Les valeurs « de l'an dernier » valent pour les comptes de {anno} : mets-les à jour en début d'année. Pour les autres années, Kubo utilise les données.",
};
