export default {
  'gestione.tipo-testo': 'Texte',
  'gestione.tipo-testo_lungo': 'Texte long',
  'gestione.tipo-numero': 'Nombre',
  'gestione.tipo-valuta': 'Montant ({simbolo})',
  'gestione.tipo-percentuale': 'Pourcentage',
  'gestione.tipo-data': 'Date',
  'gestione.tipo-data_ora': 'Date et heure',
  'gestione.tipo-si_no': 'Oui / Non',
  'gestione.tipo-scelta': 'Choix',
  'gestione.tipo-scelta_multipla': 'Choix multiple',
  'gestione.tipo-stato': 'Statut (flux)',
  'gestione.tipo-relazione': 'Lien',
  'gestione.tipo-righe': 'Lignes (sous-tableau)',
  'gestione.tipo-calcolato': 'Calculé (formule)',
  'gestione.tipo-contatore': 'Numérotation',
  'gestione.tipo-email': 'E-mail',
  'gestione.tipo-telefono': 'Téléphone',
  'gestione.tipo-url': 'Site web',
  'gestione.tipo-indirizzo': 'Adresse',
  'gestione.tipo-codice_a_barre': 'Code-barres',
  'gestione.tipo-durata': 'Durée (minutes)',
  'gestione.tipo-immagine': 'Image',
  'gestione.tipo-file': 'Fichier',
  'gestione.nome': 'Nom',
  'gestione.esempio-sezione': 'ex. Locations',
  'gestione.archivia-campo': 'Archiver le champ (les valeurs sont conservées)',
  'gestione.obbligatorio': 'Obligatoire',
  'gestione.senza-doppioni': 'Sans doublons',
  'gestione.prima-opzione': 'Première option',
  'gestione.opzioni': 'Options, une par ligne (couleurs : {colori})',
  'gestione.righe-di': 'Lignes de',
  'gestione.collegato-a': 'Lié à',
  'gestione.piu-di-uno': 'Plusieurs',
  'gestione.campo-punta': 'Champ qui pointe ici (dans l\'autre entité)',
  'gestione.formula': 'Formule (ex. quantite * prix · SOMME(lignes.total) · SI(stock <= seuil; "oui"; "non"))',
  'gestione.mostra-come': 'Afficher comme',
  'gestione.automatico': 'Automatique',
  'gestione.importo': 'Montant',
  'gestione.formato-contatore': 'Format ({AAAA} année, {N:4} numéro à 4 chiffres)',
  'gestione.salva-modifiche': 'Enregistrer les modifications',
  'gestione.dai-nome': 'Donnez un nom',
  'gestione.piu-campo': '+ Champ',
  'gestione.personalizza-nome': 'Personnaliser · {nome}',
  'gestione.icona': 'Icône',
  'gestione.nome-elemento': 'Nom de chaque élément',
  'gestione.nota-dati': 'Renommer et déplacer ne touchent pas aux données. Un champ retiré est archivé avec ses valeurs et peut être restauré. Si un changement de type faisait perdre des valeurs, l\'enregistrement s\'arrête et vous dit lesquelles.',
  'gestione.password-8': 'Mot de passe (8+)',
  'gestione.aggiungi': 'Ajouter',
  'gestione.aggiunto': 'Ajouté',
  'gestione.ruolo-cambiato': 'Rôle modifié',
  'gestione.disattiva': 'Désactiver',
  'gestione.riattiva': 'Réactiver',
  'gestione.ruolo': 'Rôle',
  'gestione.nuova-persona': 'Nouvelle personne',
  'gestione.ruoli': 'Rôles',
  'gestione.nota-ruoli': 'Le gérant peut tout faire. Pour les autres rôles, choisissez section par section ce qu\'ils peuvent faire.',
  'gestione.nuovo-ruolo': '+ Nouveau rôle',
  'gestione.nome-ruolo': 'Nom du rôle (ex. Comptoir, Atelier)',
  'gestione.vede': 'Voit',
  'gestione.modifica': 'Modifie',
  'gestione.campi-nascosti-ruolo': 'Champs masqués pour ce rôle',
  'gestione.salva-ruolo': 'Enregistrer le rôle',
  'gestione.ruolo-salvato': 'Rôle enregistré',
  'gestione.puo-personalizzare': 'Peut personnaliser',
  'gestione.sezione': 'Section',
  'gestione.campi-nascosti': 'Champs masqués (⌘/Ctrl pour en choisir plusieurs)',
  'gestione.ruolo-titolare': 'Gérant',
  'gestione.ruolo-collaboratore': 'Collaborateur',
  'gestione.ruolo-lettura': 'Lecture seule',
  'gestione.lingua-valuta': 'Langue et devise',
  'gestione.tua-lingua': 'Votre langue',
  'gestione.tua-lingua-nota': 'Ne vaut que pour vous, sur tous vos appareils.',
  'gestione.azienda': 'Pour toute l\'entreprise',
  'gestione.lingua-modelli': 'Langue des nouveaux modèles',
  'gestione.lingua-modelli-nota': 'Les modèles que vous ajouterez désormais arriveront avec les noms dans cette langue. Les sections existantes ne changent pas.',
  'gestione.valuta-nota': 'Les montants s\'affichent dans cette devise. Les valeurs enregistrées ne changent pas : seuls le symbole et le format changent.',
  'gestione.esempio': 'Aperçu : {numero} · {soldi} · {data}',
  'gestione.salvato-ricarico': 'Enregistré : je recharge la page',
  'gestione.settimana-da': 'La semaine commence le {giorno}.',
};
