// Stock (web/moduli/magazzino.js) : valeur, inventaire, mouvements.
export default {
  'magazzino.titolo': "Stock",
  'magazzino.scheda-valore': "Valeur",
  'magazzino.scheda-inventario': "Inventaire",
  'magazzino.scheda-movimenti': "Mouvements",
  'magazzino.sezione': "Section du stock",
  'magazzino.nessuna-sezione': "Aucune section avec un stock : ajoutez le champ « giacenza » aux articles.",
  'magazzino.valore': "Valeur",
  'magazzino.al-costo': "au coût des articles",
  'magazzino.pezzi': "Pièces",
  'magazzino.articoli-n': {"one": "{n} article", "other": "{n} articles"},
  'magazzino.sotto-scorta': "Sous le seuil",
  'magazzino.negativi': {"one": "{n} article avec un stock négatif : {nomi}", "other": "{n} articles avec un stock négatif : {nomi}"},
  'magazzino.senza-costo': {"one": "{n} article en stock n'a pas de coût : il n'entre pas dans la valeur.", "other": "{n} articles en stock n'ont pas de coût : ils n'entrent pas dans la valeur."},
  'magazzino.per-categoria': "Par catégorie",
  'magazzino.categoria': "Catégorie",
  'magazzino.articoli': "Articles",
  'magazzino.senza-categoria': "Sans catégorie",
  'magazzino.per-articolo': "Par article",
  'magazzino.codice': "Code",
  'magazzino.articolo': "Article",
  'magazzino.giacenza': "Stock",
  'magazzino.costo': "Coût",
  'magazzino.scarica-csv': "Télécharger en CSV",
  'magazzino.nota-valore': "La valeur est stock × coût. Les achats tiennent le coût au coût moyen pondéré. C'est la donnée des stocks de fin d'exercice pour le comptable.",
  'magazzino.inventario-nota': "Comptez la marchandise en rayon : les stocks actuels restent la référence, et à la clôture chaque article compté est corrigé de l'écart. Les ventes faites pendant le comptage restent justes.",
  'magazzino.continua': "Continuer « {nome} »",
  'magazzino.nuovo-inventario': "Commencer un inventaire",
  'magazzino.inventari': "Inventaires",
  'magazzino.nome': "Nom",
  'magazzino.iniziato': "Commencé",
  'magazzino.contati': "Comptés",
  'magazzino.stato': "État",
  'magazzino.chiuso-il': "Clôturé le {data}",
  'magazzino.aperto': "Ouvert",
  'magazzino.leggi-codice': "Lire un code (lecteur ou clavier, puis Entrée)",
  'magazzino.letto': "{nome} : {n}",
  'magazzino.cerca': "Chercher un article ou un code",
  'magazzino.attesa': "Attendu",
  'magazzino.contata': "Compté",
  'magazzino.differenza': "Écart",
  'magazzino.chiudi-conferma': {"one": "Clôturer l'inventaire ? {n} stock sera corrigé.", "other": "Clôturer l'inventaire ? {n} stocks seront corrigés."},
  'magazzino.chiuso': {"one": "Inventaire clôturé : {n} régularisation, {importo}", "other": "Inventaire clôturé : {n} régularisations, {importo}"},
  'magazzino.differenze': "Écarts",
  'magazzino.valore-differenze': "Valeur des écarts",
  'magazzino.chiudi': "Clôturer l'inventaire",
  'magazzino.chiudi-nota': "Les articles non comptés restent tels quels.",
  'magazzino.quando': "Quand",
  'magazzino.movimento': "Mouvement",
  'magazzino.origine': "Origine",
  'magazzino.chi': "Qui",
  'magazzino.origine-iniziale': "Stock initial",
  'magazzino.origine-modifica': "Modification",
  'magazzino.origine-automazione': "Automatique (ventes, commandes, consommations)",
  'magazzino.origine-inventario': "Inventaire",
  'magazzino.niente-movimenti': "Aucun mouvement pour l'instant.",
  'magazzino.nota-movimenti': "Chaque changement de stock arrive ici tout seul, d'où qu'il vienne : fiches, ventes, commandes reçues, imports, inventaires.",
};
