export default {
  'moduli.lumi-serve-chiave': "Pour répondre, j'ai besoin de la clé Claude. Je vous ouvre **Gestion → Lumi** : ça prend une minute.",
  'moduli.lumi-serve-chiave-spento': "Pour répondre, j'ai besoin de la clé Claude et d'être rallumé. Je vous ouvre **Gestion → Lumi** : ça prend une minute.",
  'moduli.lumi-chiedi-titolare': "Pour répondre, j'ai besoin de la clé Claude : demandez au gérant de l'ajouter dans **Gestion → Lumi**.",
  'moduli.lumi-spento': "Lumi est éteint : il se rallume dans Gestion → Lumi.",
  'moduli.lumi-file-pronto': 'Fichier prêt : {nome}',
  'moduli.lumi-quasi-pronto': "Lumi est presque prêt : il manque la clé Claude.",
  'moduli.lumi-apri': "Ouvrir",
  'moduli.lumi-settimana': "Comment va la semaine",
  'moduli.lumi-settimana-domanda': "Comment s'est passée cette semaine ? Donne-moi les chiffres principaux.",
  'moduli.lumi-accendi': "Allumer Lumi",
  'moduli.lumi-solo-titolare': "Les réglages de Lumi sont réservés au gérant.",
  'moduli.lumi-gia-salvata': "•••••••• (déjà enregistrée)",
  'moduli.lumi-stato-spento': "Éteint",
  'moduli.lumi-stato-acceso': "Allumé",
  'moduli.lumi-stato-manca': "Clé manquante",
  'moduli.lumi-fonte-ambiente': "La clé vient de la variable ANTHROPIC_API_KEY du serveur.",
  'moduli.lumi-fonte-file': "Clé enregistrée sur cet ordinateur.",
  'moduli.lumi-cos-e': "Lumi est l'assistant de Kubo. Vous lui parlez ou lui écrivez depuis la pastille en haut : il cherche, compte, prépare des fiches et change la forme du logiciel. Chaque modification attend votre « Confirmer », et chacun ne voit que ce que ses autorisations lui permettent.",
  'moduli.lumi-chiave': "Clé Claude",
  'moduli.lumi-salva-chiave': "Enregistrer la clé",
  'moduli.lumi-incolla': "Collez la clé",
  'moduli.lumi-togliere': "Retirer la clé ? Lumi ne répondra plus.",
  'moduli.lumi-dove-chiave': "Créez-la sur console.anthropic.com, rubrique API Keys. Elle reste sur cet ordinateur, dans un fichier à côté des données que seul Kubo lit, et n'arrive jamais aux navigateurs.",
  'moduli.lumi-acceso': "Lumi allumé",
  'moduli.lumi-limite': "Questions par minute et par personne",
  'moduli.lumi-da-provare': "À essayer",
  'moduli.lumi-esempio-1': "Combien ai-je vendu cette semaine ?",
  'moduli.lumi-esempio-2': "Que dois-je recommander ?",
  'moduli.lumi-esempio-3': "Ajoute la taille aux articles avec S, M, L et XL",
  'moduli.lumi-esempio-4': "Crée-moi une section locations avec client, outil, du, au et statut",
  'moduli.lumi-esempio-5': "Quand une location passe à rendue, préviens-moi",
  'moduli.lumi-modello': "Modèle : {modello}.",
  'moduli.lumi-voce-accesa': "Voix en temps réel activée.",
  'moduli.lumi-voce-browser': "Voix : celle du navigateur, quand elle existe.",
  'moduli.lumi-voce-locale': "Voix locale : Parakeet, sur cet ordinateur, comprend 25 langues européennes et l'audio ne quitte pas l'entreprise.",
  'moduli.ag-adesso': "à l'instant",
  'moduli.ag-agenda': "Agenda",
  'moduli.ag-calendario': "Calendrier",
  'moduli.ag-cruscotto': "Tableau de bord",
  'moduli.ag-aggiungi-voce': "Ajouter l'élément",
  'moduli.ag-altri': {"one": "+{n} autre", "other": "+{n} autres"},
  'moduli.ag-e-altri': {"one": "et un autre", "other": "et {n} autres"},
  'moduli.ag-aria-grafico': "{titolo} : graphique",
  'moduli.ag-barre': "Barres",
  'moduli.ag-linea': "Ligne",
  'moduli.ag-buongiorno': "Bonjour",
  'moduli.ag-buon-pomeriggio': "Bon après-midi",
  'moduli.ag-buonasera': "Bonsoir",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Modifier",
  'moduli.ag-cambia-widget': "Modifier le widget",
  'moduli.ag-nuovo-widget': "Nouveau widget",
  'moduli.ag-campo': "Champ",
  'moduli.ag-colonne-per': "Colonnes : {nome}",
  'moduli.ag-una-colonna': "Une colonne",
  'moduli.ag-come-oggi': "comme hier",
  'moduli.ag-come-settimana': "comme la semaine dernière",
  'moduli.ag-come-mese': "comme le mois dernier",
  'moduli.ag-come-anno': "comme l'an dernier",
  'moduli.ag-rispetto-oggi': "{diff} par rapport à hier ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} par rapport à la semaine dernière ({prima})",
  'moduli.ag-rispetto-mese': "{diff} par rapport au mois dernier ({prima})",
  'moduli.ag-rispetto-anno': "{diff} par rapport à l'an dernier ({prima})",
  'moduli.ag-data-rif': "Date de référence",
  'moduli.ag-prima': "Précédent",
  'moduli.ag-dopo': "Suivant",
  'moduli.ag-fatto': "Terminé",
  'moduli.ag-forma': "Forme",
  'moduli.ag-ha-creato': "a créé",
  'moduli.ag-ha-modificato': "a modifié",
  'moduli.ag-ha-archiviato': "a archivé",
  'moduli.ag-ha-ripristinato': "a restauré",
  'moduli.ag-in-sezione': "dans {nome}",
  'moduli.ag-un-elemento': "un élément",
  'moduli.ag-lista': "Liste",
  'moduli.ag-torna-lista': "Retour à la liste",
  'moduli.ag-media': "Moyenne de…",
  'moduli.ag-somma': "Somme de…",
  'moduli.ag-quanti': "Combien",
  'moduli.ag-misura': "Mesure",
  'moduli.ag-modifica': "Modifier",
  'moduli.ag-nome-voce': "Nom de l'élément",
  'moduli.ag-nuova-voce': "Nouvel élément",
  'moduli.ag-un-filtro': "Ajoutez au moins un filtre à l'élément",
  'moduli.ag-non-disegno': "Impossible de l'afficher",
  'moduli.ag-oggi': "Aujourd'hui",
  'moduli.ag-per': "Par",
  'moduli.ag-periodo': "Période",
  'moduli.ag-periodo-oggi': "Aujourd'hui",
  'moduli.ag-periodo-settimana': "Cette semaine",
  'moduli.ag-periodo-mese': "Ce mois-ci",
  'moduli.ag-periodo-anno': "Cette année",
  'moduli.ag-periodo-ultimi_7': "7 derniers jours",
  'moduli.ag-periodo-ultimi_30': "30 derniers jours",
  'moduli.ag-periodo-ultimi_84': "12 dernières semaines",
  'moduli.ag-periodo-ultimi_365': "Dernière année",
  'moduli.ag-periodo-sempre': "Depuis toujours",
  'moduli.ag-piede-grafico': "{periodo} · {totale} au total",
  'moduli.ag-piu-aggiungi': "+ Ajouter",
  'moduli.ag-quale-data': "Quelle date",
  'moduli.ag-senza-titolo': "Sans titre",
  'moduli.ag-spostato': "Déplacé",
  'moduli.ag-tipo': "Type",
  'moduli.ag-titolo': "Titre",
  'moduli.ag-titolo-widget': "Donnez un titre au widget",
  'moduli.ag-tutti': "tous",
  'moduli.ag-utente-non-attivo': "Utilisateur inactif",
  'moduli.ag-vedi-calendario': "Voir dans le calendrier",
  'moduli.ag-vedi-elenco': "Voir la liste",
  'moduli.ag-vedi-giorno': "Voir la journée",
  'moduli.ag-vista-giorno': "Jour",
  'moduli.ag-vista-settimana': "Semaine",
  'moduli.ag-vista-mese': "Mois",
  'moduli.ag-w-numero': "Nombre",
  'moduli.ag-w-grafico': "Graphique",
  'moduli.ag-w-attenzione': "À surveiller",
  'moduli.ag-w-ultime': "Dernières modifications",
  'moduli.ag-def-incassato-oggi': "Encaissé aujourd'hui",
  'moduli.ag-def-incassato-mese': "Encaissé ce mois-ci",
  'moduli.ag-def-vendite-oggi': "Ventes du jour",
  'moduli.ag-def-incassi-30': "Encaissements des 30 derniers jours",
  'moduli.ag-def-appuntamenti-oggi': "Rendez-vous du jour",
  'moduli.ag-def-appuntamenti-settimana': "Rendez-vous par semaine",
  'moduli.ag-def-preventivi-attesa': "Devis en attente",
  'moduli.ag-def-commesse-aperte': "Commandes en cours",
  'moduli.ag-def-accettato-mese': "Accepté ce mois-ci",
  'moduli.ag-def-preventivi-mese': "Devis acceptés par mois",
  'moduli.ag-def-articoli-riordinare': "Articles à recommander",
  'moduli.ag-def-materiali-riordinare': "Matériaux à recommander",
  'moduli.ag-def-ordini-ritardo': "Commandes en retard",
  'moduli.ag-def-vendite-aperte': "Ventes ouvertes depuis plus de 2 jours",
  'moduli.ag-def-commesse-ritardo': "Commandes en retard",
  'moduli.ag-def-preventivi-senza-risposta': "Devis sans réponse depuis 7 jours",
  'moduli.ag-def-appuntamenti-chiudere': "Rendez-vous passés à clôturer",
  'moduli.ag-def-pacchetti-scaduti': "Forfaits expirés avec des séances",
  'moduli.ag-def-attenzione': "À surveiller",
  'moduli.ag-def-ultime': "Dernières modifications",
  'moduli.ag-def-nuovi-mese': "{nome} : nouveaux ce mois-ci",
  'moduli.ag-tutto-ok': "✓ Tout est en ordre : rien à régler.",
  'moduli.ag-nessuna-modifica': "Aucune modification pour l'instant.",
  'moduli.ag-es-titolo': "Ex. Encaissé aujourd'hui",
  'moduli.im-menu': "Importer depuis un tableur, ou exporter la liste avec les filtres actuels",
  'moduli.im-importa-da': "Importer depuis Excel ou CSV…",
  'moduli.im-esporta-xlsx': "Exporter vers Excel (.xlsx)",
  'moduli.im-esporta-csv': "Exporter en CSV",
  'moduli.im-nuova-dal-foglio': "+ Une nouvelle section à partir de la feuille",
  'moduli.im-scegli-file': "Choisissez un fichier Excel (.xlsx) ou CSV",
  'moduli.im-trascina': "ou glissez-le ici. La première ligne doit contenir les noms des colonnes.",
  'moduli.im-esporta-tutto': "Tout exporter",
  'moduli.im-backup': "Sauvegarde complète",
  'moduli.im-backup-nota': "Un zip avec la copie de la base de données (cohérente même pendant le travail) et les pièces jointes. Gardez-le sur un disque externe ou dans votre propre cloud.",
  'moduli.im-scarica-backup': "Télécharger la sauvegarde",
  'moduli.im-importa-esporta': "Importer et exporter",
  'moduli.im-api': "API et intégrations",
  'moduli.im-dati': "Données",
  'moduli.im-dove': "Où vont les lignes",
  'moduli.im-non-importare': "— ne pas importer",
  'moduli.im-crea-campo': "+ Créer le champ « {nome} » ({tipo})",
  'moduli.im-non-controllare': "Ne pas vérifier : chaque ligne est nouvelle",
  'moduli.im-stesso': "Même « {nome} »",
  'moduli.im-stesso-unico': "Même « {nome} » (sans doublons)",
  'moduli.im-aggiorna': "mettre à jour celle qui existe",
  'moduli.im-salta': "la laisser, ignorer la ligne",
  'moduli.im-controllo': "Vérification…",
  'moduli.im-importo': "Importation…",
  'moduli.im-importato': "Importé",
  'moduli.im-prova': "Essayer sans enregistrer",
  'moduli.im-importa-n': {"one": "Importer {n} ligne", "other": "Importer {n} lignes"},
  'moduli.im-righe-in': {"one": "{n} ligne dans « {file} »", "other": "{n} lignes dans « {file} »"},
  'moduli.im-riga': "Ligne",
  'moduli.im-errore': "Erreur",
  'moduli.im-file-errori': "lignes à corriger.csv",
  'moduli.im-prova-esito': "Essai : rien n'a été enregistré",
  'moduli.im-esito-create': {"one": "créée", "other": "créées"},
  'moduli.im-esito-aggiornate': {"one": "mise à jour", "other": "mises à jour"},
  'moduli.im-esito-saltate': {"one": "ignorée", "other": "ignorées"},
  'moduli.im-esito-errori': "avec erreurs",
  'moduli.im-cosa-non-va': "Ce qui ne va pas",
  'moduli.im-e-altre': {"one": "…et une autre.", "other": "…et {n} autres."},
  'moduli.im-scarica-errori': "Télécharger les lignes en erreur (.csv)",
  'moduli.im-correggi': "Corrigez-les dans le fichier et importez-les à nouveau : avec le contrôle des doublons, rien n'est dupliqué.",
  'moduli.im-vai-a': "Aller à {nome}",
  'moduli.im-abbina': "Associez les colonnes aux champs de {nome}. Les premières lignes :",
  'moduli.im-ogni-colonna': "Chaque colonne devient un champ : vérifiez les noms et les types.",
  'moduli.im-nome-sezione': "Nom de la nouvelle section",
  'moduli.im-gia-presenti': "Lignes déjà présentes",
  'moduli.im-se-trovo': "si je les trouve :",
  'moduli.im-formati': "Les nombres comme « 1 234,50 » ou « 12 € », les dates comme « 31/12/2026 » et « 1 / 0 » ou « yes / no » sont acceptés. Les cellules vides n'effacent rien.",
  'moduli.doc-campo-ragione_sociale': "Raison sociale",
  'moduli.doc-campo-piva': "Numéro de TVA",
  'moduli.doc-campo-codice_fiscale': "Code fiscal",
  'moduli.doc-campo-regime': "Régime fiscal",
  'moduli.doc-campo-via': "Adresse (rue et numéro)",
  'moduli.doc-campo-cap': "Code postal",
  'moduli.doc-campo-comune': "Commune",
  'moduli.doc-campo-provincia': "Province (sigle)",
  'moduli.doc-campo-telefono': "Téléphone",
  'moduli.doc-campo-email': "E-mail",
  'moduli.doc-campo-pec': "PEC",
  'moduli.doc-campo-codice_destinatario': "Votre code destinataire",
  'moduli.doc-campo-iban': "IBAN",
  'moduli.doc-campo-banca': "Banque",
  'moduli.doc-campo-aliquota': "TVA par défaut %",
  'moduli.doc-campo-colore': "Couleur des documents",
  'moduli.doc-chiudi': "Fermer (Échap)",
  'moduli.doc-anteprima': "Aperçu avant impression",
  'moduli.doc-stampa-pdf': "Imprimer ou enregistrer en PDF",
  'moduli.doc-modifica-modello': "Modifier le modèle",
  'moduli.doc-xml-manca': "Il manque quelque chose avant le fichier XML",
  'moduli.doc-sistema': "Corrigez ces points et réessayez :",
  'moduli.doc-apri-dati': "Ouvrir les données de l'entreprise",
  'moduli.doc-scaricato': "{nome} téléchargé : envoyez-le maintenant sur le portail de votre intermédiaire ou sur Fatture e Corrispettivi",
  'moduli.doc-dati-azienda': "Données de l'entreprise",
  'moduli.doc-modelli-stampa': "Modèles d'impression",
  'moduli.doc-documenti': "Documents",
  'moduli.doc-dati-salvati': "Données de l'entreprise enregistrées",
  'moduli.doc-logo': "Logo",
  'moduli.doc-nessun-logo': "Aucun logo",
  'moduli.doc-logo-tipo': "Le logo doit être un PNG ou un JPEG",
  'moduli.doc-logo-grande': "Le logo est trop volumineux : 300 Ko maximum",
  'moduli.doc-logo-caricato': "Logo envoyé",
  'moduli.doc-carica-logo': "Envoyer le logo",
  'moduli.doc-logo-nota': "PNG ou JPEG, 300 Ko maximum. Il figure en tête de chaque document.",
  'moduli.doc-indirizzo-completo': "Adresse complète",
  'moduli.doc-fattura-elettronica': "Facture électronique (Italie)",
  'moduli.doc-fatturapa-nota': "Kubo prépare le fichier FatturaPA (XML). Pour l'envoyer au SDI, déposez-le sur le portail Fatture e Corrispettivi de l'Agenzia delle Entrate ou chez votre intermédiaire : les étapes sont dans docs/DOCUMENTI.md.",
  'moduli.doc-nessuna-stampa': "Aucune section avec des lignes à imprimer. Ajoutez un modèle (boutique, atelier, factures) ou une section avec des lignes.",
  'moduli.doc-elenco-nota': "Chaque section avec des lignes a son document A4. Modifiez textes, colonnes et pied de page : l'aperçu se met à jour pendant que vous écrivez.",
  'moduli.doc-documento': "Document",
  'moduli.doc-modello': "Modèle",
  'moduli.doc-personalizzato': "personnalisé",
  'moduli.doc-predefinito': "par défaut",
  'moduli.doc-sinistra': "à gauche",
  'moduli.doc-destra': "à droite",
  'moduli.doc-salva-modello': "Enregistrer le modèle",
  'moduli.doc-modello-salvato': "Modèle enregistré",
  'moduli.doc-torna-predefinito': "Revenir au modèle par défaut",
  'moduli.doc-torna-conferma': "Revenir au modèle par défaut ? Les modifications de ce modèle seront perdues.",
  'moduli.doc-modello-predefinito': "Modèle par défaut",
  'moduli.doc-crea-uno': "Créez au moins un document dans {nome} pour voir l'aperçu.",
  'moduli.doc-segnaposto': "Champs de fusion disponibles",
  'moduli.doc-seg-campi': "Champs du document : ",
  'moduli.doc-seg-collegati': "Liés (chacun de leurs champs) : ",
  'moduli.doc-seg-azienda': "Votre entreprise : ",
  'moduli.doc-seg-colonne': "Dans les colonnes, chaque ligne : ",
  'moduli.doc-seg-campi-riga': " et les champs de la ligne : ",
  'moduli.doc-seg-totali': "Totaux : ",
  'moduli.doc-seg-oggi': " · aujourd'hui : ",
  'moduli.doc-seg-se': "Un passage visible seulement si le champ est rempli : ",
  'moduli.doc-seg-se-manca': "; seulement s'il est vide : ",
  'moduli.doc-ed-titolo': "Titre du document",
  'moduli.doc-ed-sopra-destinatario': "Au-dessus du destinataire",
  'moduli.doc-ed-destinatario': "Destinataire",
  'moduli.doc-ed-dettagli': "Détails en haut à droite",
  'moduli.doc-ed-colonne': "Colonnes des lignes",
  'moduli.doc-ed-riepilogo-iva': "Récapitulatif de TVA par taux",
  'moduli.doc-ed-prezzi-ivati': "Les prix sont TTC",
  'moduli.doc-ed-note': "Notes",
  'moduli.doc-ed-pagamento': "Paiement",
  'moduli.doc-ed-piede': "Pied de page",
  'moduli.doc-ed-colore-label': "Couleur",
  'moduli.doc-ed-colore-azienda': "celle de l'entreprise",
  'moduli.doc-crea-fattura': "Créer une facture",
  'moduli.doc-crea-fattura-nota': "Une facture brouillon avec le client et les lignes de ce document",
  'moduli.doc-fattura-creata': "Facture brouillon créée",
  'moduli.doc-nota-credito': "Avoir",
  'moduli.doc-nota-credito-nota': "Annuler cette facture avec un avoir brouillon",
  'moduli.doc-nota-conferma': "Créer un avoir qui annule la facture {numero} ?",
  'moduli.doc-nota-creata': "Avoir brouillon créé",
  'moduli.doc-fatturapa-titolo': "Vérifier et télécharger le fichier XML pour le SDI",
  'moduli.doc-stampa-titolo': "Aperçu, impression et PDF",
  'moduli.doc-stampa': "Imprimer",
  'moduli.im-scarica-modello': "Télécharger le modèle à remplir",
  'moduli.api-f-valuta': "nombre (19.9)",
  'moduli.api-f-data': "AAAA-MM-JJ",
  'moduli.api-f-uno-fra': "l'un de : {fra}",
  'moduli.api-f-multipla': "liste d'identifiants d'options",
  'moduli.api-f-rel-molti': "liste d'identifiants de {entita}",
  'moduli.api-f-rel': "identifiant de {entita} (en lecture { id, titolo })",
  'moduli.api-f-righe': "liste de lignes de {entita}",
  'moduli.api-f-lettura': "lecture seule",
  'moduli.api-f-contatore': "lecture seule, automatique",
  'moduli.api-f-file': "liste [{ id, nome }] des envois",
  'moduli.api-copia': "Copier",
  'moduli.api-copiato': "Copié",
  'moduli.api-copia-mano': "Sélectionnez et copiez à la main",
  'moduli.api-inizia': "Commence par",
  'moduli.api-creato': "Créé",
  'moduli.api-scade': "Expire",
  'moduli.api-ultimo-uso': "Dernière utilisation",
  'moduli.api-mai': "jamais",
  'moduli.api-revocato': "révoqué",
  'moduli.api-revoca': "Révoquer",
  'moduli.api-revocare': "Révoquer « {nome} » ? Ceux qui l'utilisent ne pourront plus entrer.",
  'moduli.api-nessun-token': "Aucun jeton pour l'instant.",
  'moduli.api-a-cosa': "À quoi il sert (ex. Site, Comptabilité)",
  'moduli.api-30': "30 jours",
  'moduli.api-90': "90 jours",
  'moduli.api-anno': "un an",
  'moduli.api-non-scade': "n'expire pas",
  'moduli.api-crea-token': "Créer le jeton",
  'moduli.api-ecco': "Voici le jeton. Copiez-le maintenant : il ne sera plus affiché.",
  'moduli.api-valore': "Valeur",
  'moduli.api-elenco': "Liste (q = recherche, f = filtres JSON, o = tri champ:desc, p = page, n = par page jusqu'à 500)",
  'moduli.api-una-riga': "Une ligne",
  'moduli.api-modifica': "Modifier (seulement les champs envoyés)",
  'moduli.api-esporta': "Exporter vers Excel",
  'moduli.api-tutte': "Toutes les sections",
  'moduli.api-ev-crea': "créé",
  'moduli.api-ev-modifica': "modifié",
  'moduli.api-ev-elimina': "archivé",
  'moduli.api-ev-ripristina': "restauré",
  'moduli.api-consegnate': {"one": "{n} livrée", "other": "{n} livrées"},
  'moduli.api-fallite': {"one": "{n} échouée", "other": "{n} échouées"},
  'moduli.api-in-attesa': "{n} en attente",
  'moduli.api-segreto': "Secret : ",
  'moduli.api-mostra': "Afficher",
  'moduli.api-prova': "Envoyer un test",
  'moduli.api-prova-partenza': "Test en cours d'envoi",
  'moduli.api-registro': "Journal",
  'moduli.api-elimina-webhook': "Supprimer le webhook « {nome} » ?",
  'moduli.api-evento': "Événement",
  'moduli.api-stato': "Statut",
  'moduli.api-tentativi': "Tentatives",
  'moduli.api-risposta': "Réponse",
  'moduli.api-quando': "Quand",
  'moduli.api-st-ok': "livrée",
  'moduli.api-st-attesa': "en attente",
  'moduli.api-st-invio': "en cours d'envoi",
  'moduli.api-st-fallita': "échouée",
  'moduli.api-riprova': "Réessayer",
  'moduli.api-nessuna-consegna': "Aucune livraison pour l'instant.",
  'moduli.api-nessun-webhook': "Aucun webhook pour l'instant.",
  'moduli.api-nome-wh': "Nom (ex. Comptabilité)",
  'moduli.api-url-wh': "https://… l'adresse qui reçoit",
  'moduli.api-aggiungi-wh': "Ajouter le webhook",
  'moduli.api-wh-aggiunto': "Webhook ajouté",
  'moduli.api-intro': "Reliez Kubo à votre site, à la comptabilité ou à une automatisation. Chaque appel a les mêmes autorisations que votre rôle.",
  'moduli.api-tuoi-token': "Vos jetons",
  'moduli.api-documentazione': "Documentation",
  'moduli.api-doc-1': "Chaque requête porte l'en-tête ",
  'moduli.api-doc-2': ". Les réponses sont en JSON ; les erreurs ont ",
  'moduli.api-doc-3': " et le bon code HTTP (401, 403, 404, 422).",
  'moduli.api-openapi-1': "La description OpenAPI 3 (pour Postman, Swagger ou pour générer un client) se trouve à ",
  'moduli.api-openapi-2': ", avec seulement les sections que le jeton peut voir.",
  'moduli.api-allegati': "Les pièces jointes s'envoient d'abord par morceaux (POST /api/file/carica, puis /api/file/carica/<id> avec { da, pezzo en base64 }), puis se placent dans le champ sous la forme [{ \"id\": \"<id>\" }].",
  'moduli.api-wh-intro': "Quand quelque chose change, Kubo envoie un POST JSON signé à l'adresse choisie. Sans réponse, il réessaie après 30 secondes, 2, 10 et 30 minutes, puis 2 heures.",
  'moduli.api-sezioni': "Sections (aucune = toutes)",
  'moduli.api-quando-riga': "Quand une ligne est",
  'moduli.api-firma': "Comment vérifier la signature",
  'moduli.lumi-dv-ferme': "{sezione} : bloqués sur « {stato} » depuis plus d'une semaine",
  'moduli.lumi-dv-oltre': "{sezione} : date « {campo} » passée",
  'moduli.ag-niente': "Rien à signaler.",
  'moduli.doc-prepara-chiedi': "La facture électronique demande quelques champs dans « {nome} » : code destinataire, PEC, rue, code postal, commune et province. L'adresse saisie jusqu'ici est répartie dans ces champs ; l'ancienne reste archivée. Je les ajoute maintenant ?",
  'moduli.doc-prepara-fatto': "Clients prêts pour la facture électronique",
};
