export default {
  'moduli.lumi-serve-chiave': "Pour répondre, j'ai besoin de la clé Claude. Je vous ouvre **Gestion → Lumi** : ça prend une minute.",
  'moduli.lumi-serve-chiave-spento': "Pour répondre, j'ai besoin de la clé Claude et d'être rallumé. Je vous ouvre **Gestion → Lumi** : ça prend une minute.",
  'moduli.lumi-chiedi-titolare': "Pour répondre, j'ai besoin de la clé Claude : demandez au gérant de l'ajouter dans **Gestion → Lumi**.",
  'moduli.lumi-spento': "Lumi est éteint : il se rallume dans Gestion → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi est presque prêt : il manque la clé Claude.",
  'moduli.lumi-apri': "Ouvrir",
  'moduli.lumi-settimana': "Comment va la semaine",
  'moduli.lumi-settimana-domanda': "Comment s'est passée cette semaine ? Donne-moi les chiffres principaux.",
  'moduli.lumi-accendi': "Allumer Lumi",
  'moduli.lumi-solo-titolare': "Les réglages de Lumi sont réservés au gérant.",
  'moduli.lumi-gia-salvata': "•••••••• (déjà enregistrée)",
  'moduli.lumi-stato-spento': "Éteint",
  'moduli.lumi-stato-acceso': "Allumé",
  'moduli.lumi-stato-manca': "Clé manquante",
  'moduli.lumi-fonte-ambiente': "La clé vient de la variable ANTHROPIC_API_KEY du serveur.",
  'moduli.lumi-fonte-file': "Clé enregistrée sur cet ordinateur.",
  'moduli.lumi-cos-e': "Lumi est l'assistant de Kubo. Vous lui parlez ou lui écrivez depuis la pastille en haut : il cherche, compte, prépare des fiches et change la forme du logiciel. Chaque modification attend votre « Confirmer », et chacun ne voit que ce que ses autorisations lui permettent.",
  'moduli.lumi-chiave': "Clé Claude",
  'moduli.lumi-salva-chiave': "Enregistrer la clé",
  'moduli.lumi-incolla': "Collez la clé",
  'moduli.lumi-togliere': "Retirer la clé ? Lumi ne répondra plus.",
  'moduli.lumi-dove-chiave': "Créez-la sur console.anthropic.com, rubrique API Keys. Elle reste sur cet ordinateur, dans un fichier à côté des données que seul Kubo lit, et n'arrive jamais aux navigateurs.",
  'moduli.lumi-acceso': "Lumi allumé",
  'moduli.lumi-limite': "Questions par minute et par personne",
  'moduli.lumi-da-provare': "À essayer",
  'moduli.lumi-esempio-1': "Combien ai-je vendu cette semaine ?",
  'moduli.lumi-esempio-2': "Que dois-je recommander ?",
  'moduli.lumi-esempio-3': "Ajoute la taille aux articles avec S, M, L et XL",
  'moduli.lumi-esempio-4': "Crée-moi une section locations avec client, outil, du, au et statut",
  'moduli.lumi-esempio-5': "Quand une location passe à rendue, préviens-moi",
  'moduli.lumi-modello': "Modèle : {modello}.",
  'moduli.lumi-voce-accesa': "Voix en temps réel activée.",
  'moduli.lumi-voce-browser': "Voix : celle du navigateur, quand elle existe.",
};
