export default {
  'moduli.lumi-serve-chiave': "Pour répondre, j'ai besoin de la clé Claude. Je vous ouvre **Gestion → Lumi** : ça prend une minute.",
  'moduli.lumi-serve-chiave-spento': "Pour répondre, j'ai besoin de la clé Claude et d'être rallumé. Je vous ouvre **Gestion → Lumi** : ça prend une minute.",
  'moduli.lumi-chiedi-titolare': "Pour répondre, j'ai besoin de la clé Claude : demandez au gérant de l'ajouter dans **Gestion → Lumi**.",
  'moduli.lumi-spento': "Lumi est éteint : il se rallume dans Gestion → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi est presque prêt : il manque la clé Claude.",
  'moduli.lumi-apri': "Ouvrir",
  'moduli.lumi-settimana': "Comment va la semaine",
  'moduli.lumi-settimana-domanda': "Comment s'est passée cette semaine ? Donne-moi les chiffres principaux.",
  'moduli.lumi-accendi': "Allumer Lumi",
  'moduli.lumi-solo-titolare': "Les réglages de Lumi sont réservés au gérant.",
  'moduli.lumi-gia-salvata': "•••••••• (déjà enregistrée)",
  'moduli.lumi-stato-spento': "Éteint",
  'moduli.lumi-stato-acceso': "Allumé",
  'moduli.lumi-stato-manca': "Clé manquante",
  'moduli.lumi-fonte-ambiente': "La clé vient de la variable ANTHROPIC_API_KEY du serveur.",
  'moduli.lumi-fonte-file': "Clé enregistrée sur cet ordinateur.",
  'moduli.lumi-cos-e': "Lumi est l'assistant de Kubo. Vous lui parlez ou lui écrivez depuis la pastille en haut : il cherche, compte, prépare des fiches et change la forme du logiciel. Chaque modification attend votre « Confirmer », et chacun ne voit que ce que ses autorisations lui permettent.",
  'moduli.lumi-chiave': "Clé Claude",
  'moduli.lumi-salva-chiave': "Enregistrer la clé",
  'moduli.lumi-incolla': "Collez la clé",
  'moduli.lumi-togliere': "Retirer la clé ? Lumi ne répondra plus.",
  'moduli.lumi-dove-chiave': "Créez-la sur console.anthropic.com, rubrique API Keys. Elle reste sur cet ordinateur, dans un fichier à côté des données que seul Kubo lit, et n'arrive jamais aux navigateurs.",
  'moduli.lumi-acceso': "Lumi allumé",
  'moduli.lumi-limite': "Questions par minute et par personne",
  'moduli.lumi-da-provare': "À essayer",
  'moduli.lumi-esempio-1': "Combien ai-je vendu cette semaine ?",
  'moduli.lumi-esempio-2': "Que dois-je recommander ?",
  'moduli.lumi-esempio-3': "Ajoute la taille aux articles avec S, M, L et XL",
  'moduli.lumi-esempio-4': "Crée-moi une section locations avec client, outil, du, au et statut",
  'moduli.lumi-esempio-5': "Quand une location passe à rendue, préviens-moi",
  'moduli.lumi-modello': "Modèle : {modello}.",
  'moduli.lumi-voce-accesa': "Voix en temps réel activée.",
  'moduli.lumi-voce-browser': "Voix : celle du navigateur, quand elle existe.",
  'moduli.ag-adesso': "à l'instant",
  'moduli.ag-agenda': "Agenda",
  'moduli.ag-calendario': "Calendrier",
  'moduli.ag-cruscotto': "Tableau de bord",
  'moduli.ag-aggiungi-voce': "Ajouter l'élément",
  'moduli.ag-altri': {"one": "+{n} autre", "other": "+{n} autres"},
  'moduli.ag-e-altri': {"one": "et un autre", "other": "et {n} autres"},
  'moduli.ag-aria-grafico': "{titolo} : graphique",
  'moduli.ag-barre': "Barres",
  'moduli.ag-linea': "Ligne",
  'moduli.ag-buongiorno': "Bonjour",
  'moduli.ag-buon-pomeriggio': "Bon après-midi",
  'moduli.ag-buonasera': "Bonsoir",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Modifier",
  'moduli.ag-cambia-widget': "Modifier le widget",
  'moduli.ag-nuovo-widget': "Nouveau widget",
  'moduli.ag-campo': "Champ",
  'moduli.ag-colonne-per': "Colonnes : {nome}",
  'moduli.ag-una-colonna': "Une colonne",
  'moduli.ag-come-oggi': "comme hier",
  'moduli.ag-come-settimana': "comme la semaine dernière",
  'moduli.ag-come-mese': "comme le mois dernier",
  'moduli.ag-come-anno': "comme l'an dernier",
  'moduli.ag-rispetto-oggi': "{diff} par rapport à hier ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} par rapport à la semaine dernière ({prima})",
  'moduli.ag-rispetto-mese': "{diff} par rapport au mois dernier ({prima})",
  'moduli.ag-rispetto-anno': "{diff} par rapport à l'an dernier ({prima})",
  'moduli.ag-data-rif': "Date de référence",
  'moduli.ag-prima': "Précédent",
  'moduli.ag-dopo': "Suivant",
  'moduli.ag-fatto': "Terminé",
  'moduli.ag-forma': "Forme",
  'moduli.ag-ha-creato': "a créé",
  'moduli.ag-ha-modificato': "a modifié",
  'moduli.ag-ha-archiviato': "a archivé",
  'moduli.ag-ha-ripristinato': "a restauré",
  'moduli.ag-in-sezione': "dans {nome}",
  'moduli.ag-un-elemento': "un élément",
  'moduli.ag-lista': "Liste",
  'moduli.ag-torna-lista': "Retour à la liste",
  'moduli.ag-media': "Moyenne de…",
  'moduli.ag-somma': "Somme de…",
  'moduli.ag-quanti': "Combien",
  'moduli.ag-misura': "Mesure",
  'moduli.ag-modifica': "Modifier",
  'moduli.ag-nome-voce': "Nom de l'élément",
  'moduli.ag-nuova-voce': "Nouvel élément",
  'moduli.ag-un-filtro': "Ajoutez au moins un filtre à l'élément",
  'moduli.ag-non-disegno': "Impossible de l'afficher",
  'moduli.ag-oggi': "Aujourd'hui",
  'moduli.ag-per': "Par",
  'moduli.ag-periodo': "Période",
  'moduli.ag-periodo-oggi': "Aujourd'hui",
  'moduli.ag-periodo-settimana': "Cette semaine",
  'moduli.ag-periodo-mese': "Ce mois-ci",
  'moduli.ag-periodo-anno': "Cette année",
  'moduli.ag-periodo-ultimi_7': "7 derniers jours",
  'moduli.ag-periodo-ultimi_30': "30 derniers jours",
  'moduli.ag-periodo-ultimi_84': "12 dernières semaines",
  'moduli.ag-periodo-ultimi_365': "Dernière année",
  'moduli.ag-periodo-sempre': "Depuis toujours",
  'moduli.ag-piede-grafico': "{periodo} · {totale} au total",
  'moduli.ag-piu-aggiungi': "+ Ajouter",
  'moduli.ag-quale-data': "Quelle date",
  'moduli.ag-senza-titolo': "Sans titre",
  'moduli.ag-spostato': "Déplacé",
  'moduli.ag-tipo': "Type",
  'moduli.ag-titolo': "Titre",
  'moduli.ag-titolo-widget': "Donnez un titre au widget",
  'moduli.ag-tutti': "tous",
  'moduli.ag-utente-non-attivo': "Utilisateur inactif",
  'moduli.ag-vedi-calendario': "Voir dans le calendrier",
  'moduli.ag-vedi-elenco': "Voir la liste",
  'moduli.ag-vedi-giorno': "Voir la journée",
  'moduli.ag-vista-giorno': "Jour",
  'moduli.ag-vista-settimana': "Semaine",
  'moduli.ag-vista-mese': "Mois",
  'moduli.ag-w-numero': "Nombre",
  'moduli.ag-w-grafico': "Graphique",
  'moduli.ag-w-attenzione': "À surveiller",
  'moduli.ag-w-ultime': "Dernières modifications",
  'moduli.ag-def-incassato-oggi': "Encaissé aujourd'hui",
  'moduli.ag-def-incassato-mese': "Encaissé ce mois-ci",
  'moduli.ag-def-vendite-oggi': "Ventes du jour",
  'moduli.ag-def-incassi-30': "Encaissements des 30 derniers jours",
  'moduli.ag-def-appuntamenti-oggi': "Rendez-vous du jour",
  'moduli.ag-def-appuntamenti-settimana': "Rendez-vous par semaine",
  'moduli.ag-def-preventivi-attesa': "Devis en attente",
  'moduli.ag-def-commesse-aperte': "Commandes en cours",
  'moduli.ag-def-accettato-mese': "Accepté ce mois-ci",
  'moduli.ag-def-preventivi-mese': "Devis acceptés par mois",
  'moduli.ag-def-articoli-riordinare': "Articles à recommander",
  'moduli.ag-def-materiali-riordinare': "Matériaux à recommander",
  'moduli.ag-def-ordini-ritardo': "Commandes en retard",
  'moduli.ag-def-vendite-aperte': "Ventes ouvertes depuis plus de 2 jours",
  'moduli.ag-def-commesse-ritardo': "Commandes en retard",
  'moduli.ag-def-preventivi-senza-risposta': "Devis sans réponse depuis 7 jours",
  'moduli.ag-def-appuntamenti-chiudere': "Rendez-vous passés à clôturer",
  'moduli.ag-def-pacchetti-scaduti': "Forfaits expirés avec des séances",
  'moduli.ag-def-attenzione': "À surveiller",
  'moduli.ag-def-ultime': "Dernières modifications",
  'moduli.ag-def-nuovi-mese': "{nome} : nouveaux ce mois-ci",
  'moduli.ag-tutto-ok': "✓ Tout est en ordre : rien à régler.",
  'moduli.ag-nessuna-modifica': "Aucune modification pour l'instant.",
  'moduli.ag-es-titolo': "Ex. Encaissé aujourd'hui",
};
