// Area «sicurezza» (web/moduli/sicurezza.js): password, dispositivi collegati, impostazioni dell'azienda, poteri dei ruoli.
export default {
  'sicurezza.titolo': 'Sécurité',
  'sicurezza.la-tua-password': 'Votre mot de passe',
  'sicurezza.dispositivi-collegati': 'Appareils connectés',
  'sicurezza.dispositivo': '{browser} sur {sistema}',
  'sicurezza.dispositivo-sconosciuto': 'Appareil inconnu',
  'sicurezza.app-kubo': 'Application Kubo',
  'sicurezza.iphone-ipad': 'iPhone ou iPad',
  'sicurezza.password-diverse': 'Les deux nouveaux mots de passe ne sont pas identiques',
  'sicurezza.password-cambiata': 'Mot de passe modifié. Les autres appareils ont été déconnectés.',
  'sicurezza.password-attuale': 'Mot de passe actuel',
  'sicurezza.password-nuova': 'Nouveau mot de passe',
  'sicurezza.password-regole': 'Au moins 8 caractères ; en dessous de 12, mélangez lettres, chiffres ou symboles.',
  'sicurezza.password-ripeti': 'Répétez le nouveau mot de passe',
  'sicurezza.cambia-password': 'Changer le mot de passe',
  'sicurezza.col-dispositivo': 'Appareil',
  'sicurezza.col-ultimo-uso': 'Dernière utilisation',
  'sicurezza.col-indirizzo': 'Adresse',
  'sicurezza.questo': 'celui-ci',
  'sicurezza.scollega': 'Déconnecter',
  'sicurezza.scollegati': { one: '{n} appareil déconnecté', other: '{n} appareils déconnectés' },
  'sicurezza.scollega-altri': 'Déconnecter tous les autres',
  'sicurezza.impostazioni': "Réglages de l'entreprise",
  'sicurezza.inattivita': 'Fermer les sessions inactives depuis (minutes)',
  'sicurezza.allegati': 'Pièces jointes : au maximum (Mo)',
  'sicurezza.fuso': 'Fuseau horaire',
  'sicurezza.lumi-budget': 'Lumi : jetons par mois (0 = sans limite)',
  'sicurezza.lumi-usati': 'Utilisés ce mois-ci : {usati}',
  'sicurezza.webhook-interni': "Autoriser les webhooks vers le réseau interne (127.0.0.1, 192.168…). Laissez désactivé si vous ne savez pas à quoi ça sert.",
  'sicurezza.salvate': 'Réglages enregistrés',
  'sicurezza.salva': 'Enregistrer',
  'sicurezza.ruoli': 'Pouvoirs des rôles',
  'sicurezza.ruoli-nota': "Exporter la facture électronique consomme un numéro d'envoi ; Lumi utilise les jetons de l'entreprise.",
  'sicurezza.col-ruolo': 'Rôle',
  'sicurezza.potere-fatturapa': 'Exporter FatturaPA',
  'sicurezza.potere-lumi': 'Utiliser Lumi',
  'sicurezza.potere-aria': '{potere} pour {ruolo}',
  'sicurezza.salvato': 'Enregistré',
  'sicurezza.persone': 'Personnes',
  'sicurezza.col-nome': 'Nom',
  'sicurezza.obbliga-cambio': 'Obliger à changer le mot de passe',
  'sicurezza.obbligo-fatto': '{nome} changera son mot de passe à la prochaine connexion',
  'sicurezza.scollega-ovunque': 'Déconnecter partout',
  'sicurezza.scollegato-ovunque': 'Sessions de {nome} fermées sur tous les appareils',
  'sicurezza.nessun-altro': 'Personne d\'autre.',
  'sicurezza.scegli-password': 'Choisissez votre mot de passe',
  'sicurezza.provvisoria': 'Le mot de passe qui vous a été donné était provisoire. Choisissez le vôtre pour continuer.',
};
