// Trésorerie (web/moduli/tesoreria.js) : échéancier, rapprochement bancaire, prévision de trésorerie, relances, remises.
export default {
  'tesoreria.titolo': "Trésorerie",
  'tesoreria.scheda-scadenze': "Échéancier",
  'tesoreria.scheda-banca': "Banque",
  'tesoreria.scheda-cassa': "Prévision de trésorerie",
  'tesoreria.scheda-solleciti': "Relances",
  'tesoreria.scheda-distinte': "Remises",
  'tesoreria.scheda-impostazioni': "Réglages",
  'tesoreria.manca-fatture': "L'échéancier vient des factures : ajoutez le modèle « Factures et facture électronique » depuis Personnaliser.",
  'tesoreria.da-incassare': "À encaisser",
  'tesoreria.da-pagare': "À payer",
  'tesoreria.di-cui-scaduto': "dont échu {importo}",
  'tesoreria.saldo-netto': "Différence",
  'tesoreria.verso-attiva': "Encaissements clients",
  'tesoreria.verso-passiva': "Paiements fournisseurs",
  'tesoreria.solo-scadute': "Échues seulement",
  'tesoreria.cerca': "Chercher un client ou un document",
  'tesoreria.scadenza': "Échéance",
  'tesoreria.documento': "Document",
  'tesoreria.cliente': "Client",
  'tesoreria.fornitore': "Fournisseur",
  'tesoreria.importo': "Montant",
  'tesoreria.residuo': "Reste dû",
  'tesoreria.stato': "État",
  'tesoreria.pagata': "Payée",
  'tesoreria.in-distinta': "En remise",
  'tesoreria.scaduta-da': { one: "Échue depuis {n} jour", other: "Échue depuis {n} jours" },
  'tesoreria.parziale': "Acompte",
  'tesoreria.aperta': "Ouverte",
  'tesoreria.incassata': "Encaissée",
  'tesoreria.pagata-btn': "Payée",
  'tesoreria.acconto': "Acompte",
  'tesoreria.niente-scadenze': "Aucune échéance ouverte.",
  'tesoreria.scegli-nota': "Cochez les échéances pour les marquer payées ou préparer le fichier pour la banque.",
  'tesoreria.scelte': { one: "{n} choisie · {importo}", other: "{n} choisies · {importo}" },
  'tesoreria.segna-incassate': "Marquer encaissées",
  'tesoreria.segna-pagate': "Marquer payées",
  'tesoreria.distinta-riba': "Remise Ri.Ba.",
  'tesoreria.distinta-sdd': "Prélèvement SDD",
  'tesoreria.distinta-sct': "Virements SEPA",
  'tesoreria.data-pagamento': "Date du paiement (AAAA-MM-JJ)",
  'tesoreria.data-esecuzione': "Date d'exécution à la banque (AAAA-MM-JJ)",
  'tesoreria.data-accredito': "Date du crédit ou du paiement (AAAA-MM-JJ)",
  'tesoreria.importo-acconto': "Montant encaissé ou payé",
  'tesoreria.importo-non-valido': "Montant non valide",
  'tesoreria.incassi-registrati': { one: "Encaissement enregistré", other: "{n} encaissements enregistrés" },
  'tesoreria.pagamenti-registrati': { one: "Paiement enregistré", other: "{n} paiements enregistrés" },
  'tesoreria.distinta-creata': "{nome} prête : {importo}. Déposez le fichier sur la banque en ligne.",
  'tesoreria.nota-termini': "Les échéances viennent des échéances de la facture, de sa date d'échéance ou des conditions de paiement du client ou du fournisseur (par exemple 30/60/90 DFFM).",
  'tesoreria.err-sia': "Le code SIA de l'entreprise manque (la banque le fournit) : saisissez-le dans les réglages de la trésorerie.",
  'tesoreria.err-iban-azienda': "L'IBAN de l'entreprise manque ou est erroné : Documents → données de l'entreprise.",
  'tesoreria.err-banca-debitore': "{nome} : l'IBAN de la banque du client manque dans sa fiche.",
  'tesoreria.err-cf-debitore': "{nome} : le numéro de TVA ou le code fiscal manque.",
  'tesoreria.err-importo': "{nome} : montant à encaisser non valide.",
  'tesoreria.err-id-creditore': "L'identifiant créancier SEPA manque (la banque le délivre) : réglages de la trésorerie.",
  'tesoreria.err-iban-debitore': "{nome} : IBAN du client manquant ou erroné.",
  'tesoreria.err-mandato': "{nome} : la référence et la date du mandat SDD manquent dans la fiche du client.",
  'tesoreria.err-iban-beneficiario': "{nome} : IBAN du fournisseur manquant ou erroné.",
  'tesoreria.banca-titolo': "Relevé et rapprochement",
  'tesoreria.manca-movimenti': "Pour importer un relevé, il faut la section « Mouvements bancaires ».",
  'tesoreria.prepara': "Préparer la trésorerie",
  'tesoreria.preparata': { one: "{n} élément ajouté", other: "{n} éléments ajoutés" },
  'tesoreria.chiedi-titolare': "Demandez à quelqu'un qui peut personnaliser le logiciel.",
  'tesoreria.file-grande': "{nome} est trop volumineux",
  'tesoreria.importati': "{n} mouvements importés, {doppi} déjà présents",
  'tesoreria.saldo-aggiornato': "Solde de la prévision mis à jour : {importo} au {data}",
  'tesoreria.carica-estratto': "Déposez le relevé ici, ou cliquez",
  'tesoreria.formati': "CAMT.053 (XML), CBI, CSV ou Excel de la banque",
  'tesoreria.abbinato': "Rapproché : échéances marquées payées",
  'tesoreria.abbinato-differenza': "Rapproché ; il reste {importo}",
  'tesoreria.abbina-a': "Rapprocher de…",
  'tesoreria.abbina': "Rapprocher",
  'tesoreria.ignora': "Ignorer",
  'tesoreria.ignora-nota': "Frais, virements internes, salaires : des mouvements qui ne soldent pas une facture",
  'tesoreria.nessuna-proposta': "Aucune proposition : choisissez à la main ci-dessous.",
  'tesoreria.da-abbinare': { one: "{n} mouvement à rapprocher", other: "{n} mouvements à rapprocher" },
  'tesoreria.tutto-abbinato': "Tout est rapproché.",
  'tesoreria.abbinati-recenti': "Rapprochés récemment",
  'tesoreria.data': "Date",
  'tesoreria.descrizione': "Libellé",
  'tesoreria.mov-abbinato': "Rapproché",
  'tesoreria.mov-ignorato': "Ignoré",
  'tesoreria.mov-da_abbinare': "À rapprocher",
  'tesoreria.annulla': "Annuler",
  'tesoreria.nota-movimenti': "Les mouvements sont dans la section « {sezione} » : les connexions bancaires (open banking) la remplissent aussi.",
  'tesoreria.perche-importo': "même montant",
  'tesoreria.perche-importo-vicino': "montant proche",
  'tesoreria.perche-acconto': "acompte",
  'tesoreria.perche-numero': "numéro de facture",
  'tesoreria.perche-iban': "même IBAN",
  'tesoreria.perche-nome': "nom",
  'tesoreria.perche-data': "date proche",
  'tesoreria.perche-somma': "plusieurs factures ensemble",
  'tesoreria.perche-distinta': "crédit de la remise",
  'tesoreria.grafico': "Entrées, sorties et solde prévus",
  'tesoreria.passo-settimana': "Semaines",
  'tesoreria.passo-mese': "Mois",
  'tesoreria.senza-saldo': "Le solde de départ manque : saisissez-le dans les réglages ou importez un relevé CAMT.053.",
  'tesoreria.apri-impostazioni': "Ouvrir les réglages",
  'tesoreria.scoperto': "Attention : la trésorerie passe sous zéro, jusqu'à {importo} le {data}.",
  'tesoreria.saldo-oggi': "Solde aujourd'hui",
  'tesoreria.saldo-dal': "depuis le solde du {data} plus les mouvements",
  'tesoreria.saldo-fine': "Solde prévu",
  'tesoreria.punto-basso': "Point le plus bas",
  'tesoreria.entrate': "Entrées",
  'tesoreria.uscite': "Sorties",
  'tesoreria.saldo': "Solde",
  'tesoreria.periodi': "Par période",
  'tesoreria.periodo': "Période",
  'tesoreria.voci': "D'où viennent les chiffres",
  'tesoreria.tipo': "Type",
  'tesoreria.voce-incasso': "Encaissement",
  'tesoreria.voce-pagamento': "Paiement",
  'tesoreria.voce-previsione': "Prévision",
  'tesoreria.voce-contratto': "Contrat récurrent",
  'tesoreria.voce-tasse': "Impôts",
  'tesoreria.ritardo-medio': { one: "le client paie en moyenne {n} jour en retard", other: "le client paie en moyenne {n} jours en retard" },
  'tesoreria.niente-voci': "Rien de prévu sur la période.",
  'tesoreria.aggiungi-previsione': "Ajoutez loyer, salaires, emprunts et autres prévisions",
  'tesoreria.sollecito-segnato': "Relance enregistrée",
  'tesoreria.livello-1': "Rappel courtois",
  'tesoreria.livello-2': "Relance",
  'tesoreria.livello-3': "Mise en demeure",
  'tesoreria.appena-sollecitato': "Relancé récemment",
  'tesoreria.ritardo-giorni': { one: "{n} jour de retard", other: "{n} jours de retard" },
  'tesoreria.ultimo-sollecito': "Dernière relance le {data} (niveau {livello})",
  'tesoreria.lettera': "Texte de la relance",
  'tesoreria.copia': "Copier le texte",
  'tesoreria.copiato': "Copié",
  'tesoreria.copia-no': "Copie impossible : sélectionnez le texte à la main",
  'tesoreria.oggetto-sollecito': "Rappel de paiement",
  'tesoreria.scrivi-email': "Écrire l'e-mail",
  'tesoreria.segna-mandato': "Marquer comme envoyée",
  'tesoreria.niente-solleciti': "Aucun client en retard.",
  'tesoreria.distinta-chiusa': "Remise clôturée : échéances marquées payées",
  'tesoreria.distinta': "Remise",
  'tesoreria.creata': "Créée",
  'tesoreria.quante': "Échéances",
  'tesoreria.pagata-il': "Payée le {data}",
  'tesoreria.accreditata-il': "Créditée le {data}",
  'tesoreria.in-attesa': "En attente",
  'tesoreria.scarica': "Télécharger",
  'tesoreria.segna-pagati': "Marquer payés",
  'tesoreria.segna-accreditata': "Marquer créditée",
  'tesoreria.niente-distinte': "Pas encore de remise : elles se préparent depuis l'échéancier.",
  'tesoreria.nota-distinte': "Le fichier se dépose sur la banque en ligne (Ri.Ba. au format CBI, SDD et virements en SEPA XML). Quand la banque crédite la remise, le rapprochement la propose tout seul.",
  'tesoreria.salvate': "Réglages enregistrés",
  'tesoreria.sia': "Code SIA",
  'tesoreria.bic': "BIC de votre banque (facultatif)",
  'tesoreria.id-creditore': "Identifiant créancier SEPA (pour les SDD)",
  'tesoreria.saldo-banca': "Solde du compte",
  'tesoreria.saldo-data': "Solde au",
  'tesoreria.sequenza-sdd': "Type de prélèvement SDD",
  'tesoreria.seq-rcur': "Récurrent (RCUR)",
  'tesoreria.seq-frst': "Premier d'une série (FRST)",
  'tesoreria.seq-ooff': "Ponctuel (OOFF)",
  'tesoreria.sezione-movimenti': "Section des mouvements bancaires",
  'tesoreria.ritardo-clienti': "Dans la prévision, décaler les encaissements du retard moyen de chaque client",
  'tesoreria.salva': "Enregistrer",
  'tesoreria.banca-azienda': "Le compte de l'entreprise",
  'tesoreria.iban-azienda': "IBAN utilisé pour Ri.Ba., SDD et virements : {iban}",
  'tesoreria.manca-iban': "L'IBAN de l'entreprise manque.",
  'tesoreria.dati-azienda': "Données de l'entreprise",
  'tesoreria.nota-sia': "La banque fournit le code SIA et l'identifiant créancier quand vous activez Ri.Ba. et SDD. L'identifiant proposé est calculé à partir du numéro de TVA : vérifiez-le avec la banque.",
  'tesoreria.sezioni': "Sections",
  'tesoreria.sezioni-mancano': "Il manque « Mouvements bancaires » ou « Prévisions de trésorerie », et les champs de paiement des clients et fournisseurs (conditions, IBAN, mandat SDD).",
  'tesoreria.sezioni-ci-sono': "Elles y sont toutes.",
  'tesoreria.termini': "Conditions de paiement",
  'tesoreria.termini-nota': "Elles s'écrivent dans la fiche du client ou du fournisseur. DF = date de facture, FM = fin de mois, +10 = le 10 du mois suivant. 30, 60 et 90 jours comptent comme des mois.",
};
