export default {
  'viste.cerca-in': 'Rechercher dans {nome}…',
  'viste.nuovo': '+ Nouveau',
  'viste.tabella': 'Tableau',
  'viste.kanban': 'Kanban',
  'viste.archiviati': 'Archivés',
  'viste.viste-salvate': 'Vues enregistrées',
  'viste.colonne': 'Colonnes',
  'viste.raggruppa': 'Regrouper',
  'viste.senza-gruppi': 'Sans regroupement',
  'viste.gruppi-per': 'Groupes : {nome}',
  'viste.salva-vista': 'Enregistrer la vue',
  'viste.tutti': 'Tous',
  'viste.per-tutti': 'Pour tous',
  'viste.mie': 'Les miennes',
  'viste.filtri-tolti': 'Certains filtres de cette vue utilisent des champs que vous ne voyez pas : je les ai retirés',
  'viste.salva-modifiche': 'Enregistrer les modifications…',
  'viste.esempio-vista': 'Ex. À livrer cette semaine',
  'viste.nome-vista': 'Donnez un nom à la vue',
  'viste.salvata-tutti': 'Vue enregistrée pour tous',
  'viste.salvata-te': 'Vue enregistrée pour vous',
  'viste.vista-nome': 'Vue « {nome} »',
  'viste.salva-questa': 'Enregistrer cette vue',
  'viste.cosa-salva': 'Les filtres, colonnes, groupes et tri actuels.',
  'viste.la-vedono-tutti': 'Visible par tous',
  'viste.solo-tu': 'Vous seul la verrez.',
  'viste.elimina': 'Supprimer',
  'viste.elimina-vista': 'Supprimer la vue « {nome} » ?',
  'viste.vista-eliminata': 'Vue supprimée',
  'viste.salva-nuova': 'Enregistrer comme nouvelle',
  'viste.aggiorna': 'Mettre à jour',
  'viste.salva': 'Enregistrer',
  'viste.come-inizio': 'Réinitialiser',
  'viste.nessuno': 'Aucun',
  'viste.nessun-risultato': 'Aucun résultat.',
  'viste.niente-archivio': 'Rien dans les archives.',
  'viste.ancora-nessuno': 'Encore rien dans {nome}.',
  'viste.crea-primo': '+ Créer le premier',
  'viste.totale': 'Total ({n})',
  'viste.prime-di': 'J\'affiche les {k} premiers sur {n} (les totaux comptent tout)',
  'viste.in-tutto': { one: '{n} au total', other: '{n} au total' },
  'viste.crea': 'Créer',
  'viste.creato': 'Créé',
  'viste.salvato': 'Enregistré',
  'viste.nuovo-in': 'Nouveau dans {nome}',
  'viste.archivia': 'Archiver',
  'viste.archiviare': 'Archiver ? Vous pourrez le restaurer depuis les archives.',
  'viste.archiviato': 'Archivé',
  'viste.ripristina': 'Restaurer',
  'viste.ripristinato': 'Restauré',
  'viste.storia': 'Historique',
  'viste.archiviato-min': 'archivé',
  'viste.automazione': 'automatisation',
  'viste.storia-creato': 'créé',
  'viste.storia-ripristinato': 'restauré',
  'viste.non-si-passa': 'Impossible de venir ici depuis « {da} »',
  'viste.al-salvataggio': 'à l\'enregistrement',
  'viste.piu-immagine': '+ Image',
  'viste.piu-file': '+ Fichier',
  'viste.non-immagine': '« {nome} » n\'est pas une image',
  'viste.o-trascina': 'ou glissez-le ici',
  'viste.righe-non-trovata': 'Entité des lignes introuvable',
  'viste.aggiungi-riga': '+ Ajouter une ligne',
  'viste.creato-il': 'Créé le',
  'viste.modificato-il': 'Modifié le',
  'viste.periodo-oggi': 'aujourd\'hui',
  'viste.periodo-ieri': 'hier',
  'viste.periodo-settimana': 'cette semaine',
  'viste.periodo-mese': 'ce mois-ci',
  'viste.periodo-ultimi_7': '7 derniers jours',
  'viste.periodo-ultimi_30': '30 derniers jours',
  'viste.periodo-anno': 'cette année',
  'viste.op-uguale': 'est',
  'viste.op-diverso': 'n\'est pas',
  'viste.op-tra': 'entre',
  'viste.op-contiene': 'contient',
  'viste.op-inizia': 'commence par',
  'viste.op-vuoto': 'est vide',
  'viste.op-nonvuoto': 'n\'est pas vide',
  'viste.op-in': 'est parmi',
  'viste.op-prima': 'avant le',
  'viste.op-dopo': 'à partir du',
  'viste.op-vero': 'est vrai',
  'viste.op-falso': 'est faux',
  'viste.o': ' ou ',
  'viste.tra-e': '{a} et {b}',
  'viste.io': 'moi',
  'viste.me': 'moi',
  'viste.io-maiuscolo': 'Moi',
  'viste.piu-filtro': '+ Filtre',
  'viste.cambia-filtro': 'Modifier le filtre',
  'viste.togli-tutti': 'Tout retirer',
  'viste.scegli-campo': 'Choisissez le champ…',
  'viste.nel-periodo': 'sur la période',
  'viste.testo': 'texte',
  'viste.scegli-un-campo': 'Choisissez un champ',
  'viste.manca-valore': 'La valeur manque',
  'viste.nuovo-filtro': 'Nouveau filtre',
  'viste.applica': 'Appliquer',
};
