// Il modulo WhatsApp dell'interfaccia (web/moduli/whatsapp.js): conversazioni, modelli, automazioni, impostazioni.
export default {
  'whatsapp.s-approvato': "Approuvé",
  'whatsapp.s-in_attesa': "En attente",
  'whatsapp.s-rifiutato': "Refusé",
  'whatsapp.s-in_pausa': "En pause",
  'whatsapp.s-disattivato': "Désactivé",
  'whatsapp.s-inviato': "Envoyé",
  'whatsapp.s-consegnato': "Distribué",
  'whatsapp.s-letto': "Lu",
  'whatsapp.s-fallito': "Échoué",
  'whatsapp.s-bloccato': "Arrêté",
  'whatsapp.s-coda': "En file",
  'whatsapp.s-ricevuto': "Reçu",
  'whatsapp.finestra-aperta': "Fenêtre ouverte jusqu'à {ora}",
  'whatsapp.finestra-chiusa': "Fenêtre fermée : il faut un modèle",
  'whatsapp.attivo': "Actif : {nome}",
  'whatsapp.nessuno': "Aucun service WhatsApp actif.",
  'whatsapp.vai-connettori': "Connectez-le depuis les connecteurs",
  'whatsapp.conversazioni': "Conversations",
  'whatsapp.modelli': "Modèles",
  'whatsapp.automazioni': "Automatisations WhatsApp",
  'whatsapp.impostazioni': "Réglages",
  'whatsapp.vuoto': "Pas encore de messages.",
  'whatsapp.scegli': "Choisissez une conversation.",
  'whatsapp.c-servizio': "Service",
  'whatsapp.c-marketing': "Promotions",
  'whatsapp.si-no-si': "oui",
  'whatsapp.si-no-no': "non",
  'whatsapp.fonte-chiedi': "Comment avez-vous recueilli le choix ? (ex. formulaire en boutique, site, de vive voix)",
  'whatsapp.testo-chiedi': "Les mots exacts acceptés par le client :",
  'whatsapp.testo-predefinito': "J'accepte de recevoir des messages WhatsApp de cette entreprise. Je peux répondre STOP à tout moment.",
  'whatsapp.ok-servizio': "Consentement service",
  'whatsapp.ok-marketing': "Consentement promotions",
  'whatsapp.revoca': "Révoquer",
  'whatsapp.sconosciuto': "Numéro hors du répertoire.",
  'whatsapp.crea-cliente': "Créer un client",
  'whatsapp.crea-lead': "Créer un prospect",
  'whatsapp.scrivi': "Écrivez une réponse…",
  'whatsapp.serve-modello': "Hors de la fenêtre de 24 heures : choisissez un modèle approuvé",
  'whatsapp.testo-libero': "Texte libre",
  'whatsapp.scegli-modello': "Choisissez un modèle",
  'whatsapp.k-servizio': "Service",
  'whatsapp.k-utility': "Utilitaire",
  'whatsapp.k-marketing': "Marketing",
  'whatsapp.k-authentication': "Authentification",
  'whatsapp.costo': "Coût estimé",
  'whatsapp.inviato': "Message envoyé",
  'whatsapp.invia': "Envoyer",
  'whatsapp.anteprima': "Aperçu",
  'whatsapp.sincronizzati': "Modèles mis à jour",
  'whatsapp.sincronizza': "Synchroniser les modèles",
  'whatsapp.salvato': "Enregistré",
  'whatsapp.modelli-nota': "Chaque variable {{n}} prend la valeur d'un champ : par exemple cliente.nome ou riga.quando.",
  'whatsapp.nessun-modello': "Aucun modèle : synchronisez-les ou créez-en un.",
  'whatsapp.corpo-esempio': "Bonjour {{1}}, votre commande est prête.",
  'whatsapp.esempi-esempio': "Mario ; mardi à 15 h",
  'whatsapp.nuovo-modello': "Nouveau modèle",
  'whatsapp.nuovo-nota': "Meta le vérifie avant de l'approuver, en général en quelques minutes. Chaque variable demande un exemple. Les modèles avec un PDF en en-tête se créent dans WhatsApp Manager.",
  'whatsapp.nome': "Nom (minuscules, chiffres, _)",
  'whatsapp.categoria': "Catégorie",
  'whatsapp.lingua': "Langue",
  'whatsapp.testo': "Texte",
  'whatsapp.esempi': "Exemples des variables, séparés par ;",
  'whatsapp.mandato-a-meta': "Modèle envoyé pour approbation",
  'whatsapp.manda-approvazione': "Envoyer pour approbation",
  'whatsapp.automazioni-nota': "Activez celles qui vous servent, choisissez le modèle et le moment. Avant chaque envoi Kubo vérifie consentement, STOP, heures de silence et limites.",
  'whatsapp.o-ore': "Heures avant (ex. 24, 2)",
  'whatsapp.o-giorni': "Après combien de jours",
  'whatsapp.o-mesi': "Inactif depuis mois",
  'whatsapp.o-link': "Lien pour l'avis",
  'whatsapp.o-testo': "Texte de la réponse",
  'whatsapp.esempio-da-approvare': "Exemple de modèle : créez-le et faites-le approuver, puis choisissez-le ici.",
  'whatsapp.mancano': "Variables sans valeur : {n}",
  'whatsapp.salva': "Enregistrer",
  'whatsapp.r-promemoria': "Rappel de rendez-vous",
  'whatsapp.r-conferma': "Confirmation de réservation",
  'whatsapp.r-pronto': "Commande prête ou expédiée",
  'whatsapp.r-documento': "Facture ou devis en PDF",
  'whatsapp.r-sollecito': "Relance de paiement",
  'whatsapp.r-recensione': "Demande d'avis",
  'whatsapp.r-compleanno': "Vœux d'anniversaire",
  'whatsapp.r-riattivazione': "Relancer les clients inactifs",
  'whatsapp.r-fuori_orario': "Réponse hors horaires",
  'whatsapp.rd-promemoria': "Un message avant le rendez-vous (24 et 2 heures avant, ou comme vous voulez).",
  'whatsapp.rd-conferma': "Dès qu'une réservation est créée.",
  'whatsapp.rd-pronto': "Quand le statut passe à prêt ou expédié, avec le numéro de suivi s'il existe.",
  'whatsapp.rd-documento': "Quand la facture est émise ou le devis envoyé : le PDF part avec un modèle à en-tête document.",
  'whatsapp.rd-sollecito': "Chaque matin, pour les factures échues depuis N jours (une fois par facture).",
  'whatsapp.rd-recensione': "N jours après la vente, avec le lien vers votre page d'avis.",
  'whatsapp.rd-compleanno': "Le matin de l'anniversaire du client.",
  'whatsapp.rd-riattivazione': "À ceux qui ne reviennent plus depuis N mois, une seule fois.",
  'whatsapp.rd-fuori_orario': "Quand un client écrit pendant la fermeture : texte libre, au plus une fois toutes les 12 heures.",
  'whatsapp.serve-marketing': "Promotionnel : envoyé seulement à qui a accepté les promotions, jamais pendant les heures de silence.",
  'whatsapp.non-possibile': "Votre gestion n'a pas les sections ou champs nécessaires à cette automatisation.",
  'whatsapp.modello': "Modèle",
  'whatsapp.i-prefisso': "Indicatif par défaut",
  'whatsapp.i-silenzio-da': "Silence à partir de",
  'whatsapp.i-silenzio-a': "jusqu'à",
  'whatsapp.i-silenzio-tutti': "Silence aussi pour les messages automatiques de service",
  'whatsapp.i-limite-giorno': "Modèles par jour, au total",
  'whatsapp.i-limite-cliente': "Modèles par jour et par client",
  'whatsapp.i-marketing-giorni': "Un promotionnel tous les combien de jours",
  'whatsapp.i-sconosciuti': "Expéditeurs hors du répertoire",
  'whatsapp.i-apre': "Ouvre à",
  'whatsapp.i-chiude': "Ferme à",
  'whatsapp.i-giorni': "Jours d'ouverture (0 = dimanche)",
  'whatsapp.i-t-marketing': "Marketing, € par message",
  'whatsapp.i-t-utility': "Utilitaire, € par message",
  'whatsapp.i-t-authentication': "Authentification, € par message",
  'whatsapp.i-t-servizio': "Service, € au-delà du quota gratuit",
  'whatsapp.i-t-servizioGratisMese': "Messages de service gratuits par mois (vide = tous)",
  'whatsapp.i-t-twilio': "Supplément Twilio, € par message",
  'whatsapp.sc-chiedi': "Me demander (reste un numéro)",
  'whatsapp.sc-cliente': "Créer un client",
  'whatsapp.sc-lead': "Créer un prospect",
  'whatsapp.webhook': "Adresse du webhook",
  'whatsapp.webhook-meta': "Collez-la sur Meta (WhatsApp → Configuration) avec le jeton de vérification de la page du connecteur, et abonnez-vous à messages et message_template_status_update. Elle doit être joignable depuis internet en https.",
  'whatsapp.webhook-360': "Kubo l'enregistre seul sur 360dialog quand l'adresse publique est indiquée sur la page du connecteur.",
  'whatsapp.webhook-twilio': "Collez-la dans l'expéditeur WhatsApp de Twilio comme adresse des messages entrants. L'adresse publique du connecteur doit être celle que voit Twilio.",
  'whatsapp.apri-connettore': "Ouvrir le connecteur",
  'whatsapp.costi-mese': "Ce mois-ci",
  'whatsapp.nessun-costo': "Aucun message payant ce mois-ci.",
  'whatsapp.costi-nota': "Estimation avec les tarifs Meta pour l'Italie ({data}) : seule la facture de Meta ou de votre fournisseur fait foi.",
  'whatsapp.regole': "Règles d'envoi",
  'whatsapp.tariffe': "Tarifs",
  'whatsapp.tariffe-nota': "Meta met à jour la grille chaque trimestre : corrigez ici les montants s'ils changent.",
  'whatsapp.registro': "Messages arrêtés ou échoués",
  'whatsapp.registro-vuoto': "Rien à signaler.",
  'whatsapp.storia': "Historique WhatsApp",
  'whatsapp.senza-numero': "Le client n'a pas de numéro de téléphone.",
  'whatsapp.apri-chat': "Ouvrir la conversation",
};
