// Gli acquisti (web/moduli/acquisti.js): riordino, ordini in arrivo, ricevimenti, fatture dei fornitori.
export default {
  'acquisti.titolo': "Acquisti",
  'acquisti.scheda-riordino': "Da riordinare",
  'acquisti.scheda-arrivo': "In arrivo",
  'acquisti.scheda-fatture': "Fatture dei fornitori",
  'acquisti.stato-bozza': "Bozza",
  'acquisti.stato-inviato': "Inviato",
  'acquisti.stato-parziale': "Arrivato in parte",
  'acquisti.stato-arrivato': "Arrivato",
  'acquisti.stato-annullato': "Annullato",
  'acquisti.serve-magazzino': "Per gli acquisti serve una sezione con la giacenza (articoli, ricambi, materiali…).",
  'acquisti.non-pronti': "Gli acquisti non sono ancora pronti.",
  'acquisti.chiedi-titolare': "Chiedi a chi può personalizzare il gestionale.",
  'acquisti.magazzino': "Sezione del magazzino",
  'acquisti.prepara-titolo': "Prepara gli acquisti",
  'acquisti.prepara-nota': "Kubo usa gli «Ordini ai fornitori» che ci sono già, o li crea, e aggiunge la quantità ricevuta, lo stato «arrivato in parte», il DDT e la fattura del fornitore. Non cambia i dati che hai.",
  'acquisti.prepara': "Prepara",
  'acquisti.preparati': {"one": "Aggiunta {n} cosa", "other": "Aggiunte {n} cose"},
  'acquisti.niente-riordino': "Niente sotto scorta: tutto sopra la soglia, o già ordinato.",
  'acquisti.fornitore': "Fornitore",
  'acquisti.scegli-fornitore': "Scegli il fornitore…",
  'acquisti.da-ordinare': "Da ordinare",
  'acquisti.senza-fornitore': "Senza fornitore",
  'acquisti.senza-fornitore-nota': "Questi articoli non hanno un fornitore nella scheda: sceglilo qui.",
  'acquisti.articolo': "Articolo",
  'acquisti.giacenza': "Giacenza",
  'acquisti.soglia': "Soglia",
  'acquisti.in-arrivo': "In arrivo",
  'acquisti.costo': "Costo",
  'acquisti.totale-stimato': "Totale stimato: {importo}",
  'acquisti.niente-scelto': "Non hai scelto niente da ordinare",
  'acquisti.ordini-creati': {"one": "Creato {n} ordine in bozza", "other": "Creati {n} ordini in bozza"},
  'acquisti.riordino-nota': "Sotto scorta vuol dire giacenza più quanto è già ordinato non oltre la soglia. Kubo propone di tornare al doppio della soglia: ritocca le quantità come vuoi.",
  'acquisti.crea-ordini': "Crea gli ordini",
  'acquisti.crea-nota': "Un ordine in bozza per ogni fornitore: controllalo e mandalo.",
  'acquisti.in-ritardo': "In ritardo: previsto il {data}",
  'acquisti.previsto': "Previsto il {data}",
  'acquisti.ricevi': "Ricevi merce",
  'acquisti.ricevute-di': "{ricevuta} di {quantita}",
  'acquisti.niente-arrivo': "Nessun ordine in arrivo.",
  'acquisti.ordine-chiuso': "Questo ordine è già chiuso.",
  'acquisti.vedi-confronto': "Vedi il confronto",
  'acquisti.ddt-segnaposto': "Numero e data del DDT",
  'acquisti.ricevuto-tutto': "Merce ricevuta: ordine arrivato",
  'acquisti.ricevuto-parte': "Merce ricevuta: l'ordine resta aperto per il resto",
  'acquisti.ricevi-titolo': "Ricevi la merce: {numero}, {fornitore}",
  'acquisti.ddt': "DDT del fornitore",
  'acquisti.data': "Data",
  'acquisti.ordinate': "Ordinate",
  'acquisti.gia-ricevute': "Già ricevute",
  'acquisti.arrivate-ora': "Arrivate ora",
  'acquisti.ricevi-nota': "Le quantità arrivate si caricano subito in magazzino e il costo dell'articolo diventa il costo medio ponderato. Quello che manca resta in arrivo.",
  'acquisti.carica': "Carica in magazzino",
  'acquisti.annulla': "Annulla",
  'acquisti.senza-fatture': "Per abbinare le fatture serve il modello «Fatture e fattura elettronica».",
  'acquisti.ordine': "Ordine",
  'acquisti.ricevuto': "Ricevuto",
  'acquisti.fattura-proposta': "Fattura proposta",
  'acquisti.candidata': "{numero}: {importo}",
  'acquisti.nessuna-fattura': "Nessuna fattura di questo fornitore",
  'acquisti.confronta': "Confronta",
  'acquisti.tutto-fatturato': "Ogni merce ricevuta ha la sua fattura.",
  'acquisti.fatture-nota': "Kubo confronta il valore della merce ricevuta con l'imponibile delle fatture del fornitore. Torna se la differenza è entro 1 € o l'1%.",
  'acquisti.abbinata': "Fattura abbinata",
  'acquisti.tolta': "Fattura tolta",
  'acquisti.ordinato': "Ordinato",
  'acquisti.fatturato': "Fatturato",
  'acquisti.confronto-titolo': "{numero} · {fornitore}",
  'acquisti.torna': "Torna con la fattura {numero}.",
  'acquisti.non-torna': "La fattura {numero} non torna: differenza {importo}.",
  'acquisti.togli': "Togli",
  'acquisti.candidate': "Fatture candidate",
  'acquisti.fattura': "Fattura",
  'acquisti.imponibile': "Imponibile",
  'acquisti.differenza': "Differenza",
  'acquisti.abbina': "Abbina",
  'acquisti.ricevimenti': "Ricevimenti",
  'acquisti.quantita': "Quantità",
};
