// Area «avvio» (web/moduli/avvio.js): avvio guidato, giro guidato e dati d'esempio.
export default {
  'avvio.avanti': "Avanti",
  'avvio.indietro': "← Indietro",
  'avvio.azienda-es': "es. Bottega Ferri",
  'avvio.sottotitolo': "Dieci domande e il gestionale è pronto, cucito sul tuo lavoro. Tutto si cambia anche dopo.",
  'avvio.nome-attivita': "Come si chiama la tua attività?",
  'avvio.d-settore': "Che lavoro fai?",
  'avvio.a-settore': "Scegli il più vicino. Dopo si cambia tutto.",
  'avvio.o-settore-negozio': "Negozio e bottega",
  'avvio.sd-negozio': "Vendo al banco, ho articoli e magazzino",
  'avvio.o-settore-ristorante': "Ristorante e bar",
  'avvio.sd-ristorante': "Tavoli, comande, menù con allergeni, prenotazioni",
  'avvio.o-settore-laboratorio': "Laboratorio e artigiano",
  'avvio.sd-laboratorio': "Preventivi, commesse a fasi, materiali",
  'avvio.o-settore-officina': "Officina e assistenza",
  'avvio.sd-officina': "Veicoli o apparecchi, interventi, ricambi, garanzie",
  'avvio.o-settore-studio': "Studio e servizi",
  'avvio.sd-studio': "Agenda, schede cliente, pacchetti di sedute",
  'avvio.o-settore-beauty': "Beauty ed estetica",
  'avvio.sd-beauty': "Agenda per cabina, trattamenti, pacchetti, prodotti",
  'avvio.o-settore-palestra': "Palestra e associazione",
  'avvio.sd-palestra': "Soci, abbonamenti e rinnovi, corsi e presenze",
  'avvio.o-settore-professionista': "Professionista e agenzia",
  'avvio.sd-professionista': "Clienti, progetti, ore, scadenze, preventivi",
  'avvio.o-settore-noleggio': "Noleggio",
  'avvio.sd-noleggio': "Beni, disponibilità, contratti dal/al, cauzioni",
  'avvio.o-settore-altro': "Altro, parto da zero",
  'avvio.sd-altro': "Un gestionale vuoto: le sezioni le crei tu",
  'avvio.d-offerta': "Vendi prodotti, servizi o tutti e due?",
  'avvio.o-offerta-prodotti': "Prodotti",
  'avvio.o-offerta-servizi': "Servizi",
  'avvio.o-offerta-entrambi': "Tutti e due",
  'avvio.d-magazzino': "Tieni un magazzino?",
  'avvio.a-magazzino': "Giacenze, scorte minime, cosa riordinare.",
  'avvio.d-su_misura': "Lavori su misura, con i preventivi?",
  'avvio.a-su_misura': "Il preventivo con le voci; quando il cliente accetta si apre il lavoro.",
  'avvio.d-appuntamenti': "Prendi appuntamenti o prenotazioni?",
  'avvio.a-appuntamenti': "Un'agenda per persona o per risorsa.",
  'avvio.d-fornitori': "Compri da fornitori?",
  'avvio.a-fornitori': "Anagrafica dei fornitori e, se hai un magazzino, gli ordini con il carico.",
  'avvio.d-fatture': "Emetti fatture?",
  'avvio.a-fatture': "Numerate per anno, con IVA, scadenze e il file della fattura elettronica.",
  'avvio.d-persone': "Quante persone useranno Lumi?",
  'avvio.o-persone-solo': "Solo io",
  'avvio.o-persone-poche': "Da 2 a 5",
  'avvio.o-persone-molte': "Più di 5",
  'avvio.d-squadra': "Chi lavora con te?",
  'avvio.a-squadra': "Ognuno entra con la sua email e vede quello che serve al suo ruolo. Si può fare anche dopo.",
  'avvio.d-lumi': "Vuoi Lumi, l'assistente?",
  'avvio.a-lumi': "Gli chiedi le cose a parole: «quanto ho incassato questa settimana?», «aggiungi la taglia agli articoli». Lui propone, tu confermi.",
  'avvio.d-esempi': "Vuoi vedere il gestionale con dei dati d'esempio?",
  'avvio.a-esempi': "Clienti, vendite e appuntamenti finti ma credibili, per provare tutto. Si cancellano con un clic.",
  'avvio.o-si': "Sì",
  'avvio.o-no': "No",
  'avvio.collaboratore': "Collaboratore (vede e modifica, non elimina)",
  'avvio.lettura': "Solo lettura",
  'avvio.nome': "Nome",
  'avvio.ruolo': "Ruolo",
  'avvio.togli': "Togli",
  'avvio.altra-persona': "+ Un'altra persona",
  'avvio.password-provvisoria': "Ognuno riceve una password provvisoria, che vedrai alla fine.",
  'avvio.sezioni': "Ti preparo queste sezioni",
  'avvio.nessuna-sezione': "Nessuna: parti da zero",
  'avvio.campi-spenti': { one: "{n} campo che non ti serve resta spento (si riaccende da {personalizza})", other: "{n} campi che non ti servono restano spenti (si riaccendono da {personalizza})" },
  'avvio.persone-ruolo': { one: "Una persona con il suo ruolo", other: "{n} persone, ognuna con il suo ruolo" },
  'avvio.lumi-acceso': "Lumi acceso",
  'avvio.lumi-spento': "Lumi spento (si accende quando vuoi)",
  'avvio.con-esempi': "Con i dati d'esempio, da togliere con un clic",
  'avvio.senza-esempi': "Senza dati d'esempio",
  'avvio.ci-siamo': "Ci siamo",
  'avvio.chi-sei': "Ultima cosa: chi sei. Sarai il titolare, quello che può tutto.",
  'avvio.preparo': "Preparo Lumi…",
  'avvio.prepara': "Prepara Lumi",
  'avvio.pronto': "Lumi è pronto",
  'avvio.consegna': "Dai a ognuno la sua password provvisoria. Questa schermata non si rivede: copiale ora.",
  'avvio.entra': "Entra in Lumi",
  'avvio.tappa-sezioni': "Le tue sezioni",
  'avvio.tappa-sezioni-testo': "Qui c'è tutto il gestionale{esempi}. Ogni sezione è una lista che puoi cercare, filtrare, ordinare e vedere a colonne.",
  'avvio.tappa-personalizza-testo': "Manca un campo? Ne avanza uno? Da qui aggiungi, rinomini e sposti i campi, senza perdere mai un dato. Le sezioni nuove le crei da «{nuova}».",
  'avvio.tappa-lumi-testo': "Chiedi a parole: «quanto ho incassato questa settimana?», «aggiungi la taglia agli articoli». Lumi legge con i tuoi permessi e propone; decidi tu.",
  'avvio.tappa-cruscotto': "Il cruscotto",
  'avvio.tappa-cruscotto-testo': "I numeri che contano e cosa richiede attenzione, aggiornati mentre lavori. Si cambia con «{modifica}» in alto.",
  'avvio.n-di': "{n} di {tot}",
  'avvio.salta': "Salta",
  'avvio.capito': "Ho capito",
  'avvio.promemoria': "Stai guardando dati d'esempio",
  'avvio.toglili': "Toglili",
  'avvio.conferma-togli': "Tolgo tutti i dati d'esempio? Quello che hai aggiunto tu resta.",
  'avvio.tolte': { one: "Tolta {n} riga d'esempio", other: "Tolte {n} righe d'esempio" },
  'avvio.aggiunte': { one: "Aggiunta {n} riga d'esempio", other: "Aggiunte {n} righe d'esempio" },
  'avvio.togli-esempi': "Togli i dati d'esempio",
  'avvio.rimetti-esempi': "Rimetti i dati d'esempio",
  'avvio.pagina-titolo': "Dati d'esempio e giro guidato",
  'avvio.ci-sono': { one: "C'è {n} riga d'esempio, finta, per provare Lumi senza paura. Quando sei pronto toglila: sparisce (anche se l'hai ritoccata), quello che hai inserito tu resta e, dove non c'è ancora niente di tuo, la numerazione riparte da 1.", other: "Ci sono {n} righe d'esempio: clienti, movimenti e appuntamenti finti, per provare Lumi senza paura. Quando sei pronto toglile: spariscono tutte (anche quelle che hai ritoccato), quello che hai inserito tu resta e, dove non c'è ancora niente di tuo, la numerazione riparte da 1." },
  'avvio.solo-titolare': "Solo il titolare può toglierli.",
  'avvio.nessun-esempio': "Non ci sono dati d'esempio.",
  'avvio.rivedere': "Vuoi rivedere dove sono le cose?",
  'avvio.rifai-giro': "Rifai il giro guidato",
  'avvio.lato': "Dati d'esempio e giro",
  'avvio.lato-sezione': "Primi passi",
};
