// Testi comuni: primo avvio, accesso, barra laterale, formati (web/app.js, web/ui.js) e parole usate da più file.
export default {
  'comune.benvenuto': 'Benvenuto in Kubo',
  'comune.benvenuto-sotto': 'Il gestionale che si monta come vuoi tu. Parti da un modello, poi cambia tutto quello che vuoi.',
  'comune.nome-azienda': 'Nome dell\'azienda',
  'comune.tuo-nome': 'Il tuo nome',
  'comune.email': 'Email',
  'comune.password': 'Password',
  'comune.password-nuova': 'Password (almeno 8 caratteri)',
  'comune.valuta': 'Valuta',
  'comune.da-dove': 'Da dove partiamo? (se ne possono aggiungere altri dopo)',
  'comune.codice-avvio': "Codice di avvio (è scritto nel terminale o nel log dove gira Kubo)",
  'comune.codice-avvio-es': "es. 3FA9C2D1",
  'comune.inizia': 'Inizia',
  'comune.lingua': 'Lingua',
  'comune.accedi-per': 'Accedi per continuare.',
  'comune.accedi': 'Accedi',
  'comune.gestione': 'Gestione',
  'comune.nuova-sezione': 'Nuova sezione',
  'comune.persone-permessi': 'Persone e permessi',
  'comune.esci': 'Esci',
  'comune.personalizza': 'Personalizza',
  'comune.personalizza-sezione': 'Personalizza questa sezione',
  'comune.nessuna-sezione': 'Nessuna sezione.',
  'comune.creane-una': 'Creane una',
  'comune.chiedi-titolare': 'Chiedi al titolare di crearne una.',
  'comune.qualcosa-non-va': 'Qualcosa non va',
  'comune.errore-n': 'Errore {stato}',
  'comune.percento': '{n}%',
  'comune.si': 'Sì',
  'comune.no': 'No',
  'comune.si-min': 'sì',
  'comune.no-min': 'no',
  'comune.su': 'Su',
  'comune.giu': 'Giù',
  'comune.togli': 'Togli',
  'comune.cerca': 'Cerca…',
  'comune.carico': 'Carico…',
  'comune.avviso-esempi-aggiunti': "Dati d'esempio aggiunti",
  'comune.avviso-esempi-tolti': "Dati d'esempio tolti",
};
