// Connettori: catalogo, pagina generata dal manifesto, azioni nelle schede (web/moduli/connettori.js).
export default {
  'connettori.titolo': "Connettori",
  'connettori.spiega': "Collega Kubo ai servizi che usi già: pagamenti, negozio online, fatturazione elettronica, posta, calendario. Le chiavi restano cifrate in Kubo e non tornano mai al browser.",
  'connettori.terzi': "Un connettore di terzi si copia nella cartella «connettori» accanto ai dati: lo accendi qui dopo averne controllato la somma.",
  'connettori.ufficiale': "Ufficiale",
  'connettori.locale': "Installato a mano",
  'connettori.rotto': "Il connettore non si carica: controlla il file connettore.js",
  'connettori.stato-acceso': "Acceso",
  'connettori.stato-spento': "Spento",
  'connettori.stato-incompleto': "Da completare",
  'connettori.stato-cambiato': "Cambiato",
  'connettori.stato-rotto': "Rotto",
  'connettori.mancano': "Manca ancora: {cosa}",
  'connettori.cambiato': "Il file del connettore è cambiato dopo l'accensione: è fermo finché non lo riaccendi controllando la somma.",
  'connettori.accendi': "Accendi",
  'connettori.spegni': "Spegni",
  'connettori.accendi-titolo': "Accendere {nome}?",
  'connettori.potra': "Potrà:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "leggere",
  'connettori.p-crea': "creare",
  'connettori.p-modifica': "modificare",
  'connettori.p-elimina': "eliminare",
  'connettori.somma': "Somma di controllo (SHA-256) del file: confrontala con quella pubblicata da chi l'ha scritto.",
  'connettori.da-approvare': "Il codice di questo connettore non è ancora stato eseguito: Kubo lo legge solo dopo che confermi la somma qui sotto. Poi vedrai le sezioni che può usare.",
  'connettori.impostazioni': "Impostazioni",
  'connettori.salvato-segreto': "Salvato",
  'connettori.cambia': "Cambia",
  'connettori.togli': "Togli",
  'connettori.interni': "Permetti indirizzi della rete interna (un server in negozio, un registratore)",
  'connettori.salva': "Salva",
  'connettori.salvato': "Salvato",
  'connettori.prova': "Prova la connessione",
  'connettori.provo': "Provo…",
  'connettori.prova-ok': "Connessione riuscita",
  'connettori.prova-no': "Non va: {motivo}",
  'connettori.collegamento': "Collegamento",
  'connettori.webhook': "Indirizzo del webhook",
  'connettori.webhook-aiuto': "Incollalo nelle impostazioni dei webhook del servizio.",
  'connettori.indirizzo-segreto': "Indirizzo segreto",
  'connettori.indirizzo-aiuto': "Chi ha questo indirizzo vede i dati: dallo solo a chi serve.",
  'connettori.account': "Account",
  'connettori.collegato': "Collegato",
  'connettori.scollegato': "Non collegato",
  'connettori.scade': "Scade {quando}",
  'connettori.collega': "Collega l'account",
  'connettori.ricollega': "Ricollega",
  'connettori.oauth-ok': "Account collegato",
  'connettori.oauth-scaduto': "Il collegamento è scaduto: riprova",
  'connettori.oauth-errore': "Il collegamento non è riuscito: guarda il registro",
  'connettori.abbinamenti': "Abbinamenti dei campi",
  'connettori.abbinamenti-aiuto': "I campi del connettore e quelli di Kubo: se rinomini un campo l'abbinamento resta.",
  'connettori.sezione-manca': "Manca la sezione «{nome}»",
  'connettori.facoltativo': "facoltativo",
  'connettori.salva-abbinamenti': "Salva gli abbinamenti",
  'connettori.sincronizzazioni': "Sincronizzazioni",
  'connettori.ogni': "ogni {ogni}",
  'connettori.alle': "alle {alle}",
  'connettori.ultimo': "Ultimo giro: {quando}",
  'connettori.prossimo': "prossimo: {quando}",
  'connettori.sincronizza': "Sincronizza ora",
  'connettori.giro-ok': "Fatto",
  'connettori.coda': "In coda: {attesa} · fallite: {fallite}",
  'connettori.riprova': "Riprova le fallite",
  'connettori.registro': "Registro",
  'connettori.registro-vuoto': "Ancora niente: qui vedi cosa arriva e cosa parte.",
  'connettori.col-quando': "Quando",
  'connettori.col-verso': "Verso",
  'connettori.col-esito': "Esito",
  'connettori.col-cosa': "Cosa",
  'connettori.verso-entrata': "in arrivo",
  'connettori.verso-uscita': "in uscita",
  'connettori.verso-giro': "giro pianificato",
  'connettori.verso-azione': "azione",
  'connettori.verso-prova': "prova",
  'connettori.verso-oauth': "account",
  'connettori.verso-sistema': "sistema",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "errore",
  'connettori.esito-avviso': "avviso",
  'connettori.esito-ignorato': "ignorato",
  'connettori.copia': "Copia",
  'connettori.copiato': "Copiato",
  'connettori.annulla': "Annulla",
  'connettori.conferma': "Conferma",
  'connettori.fatto': "Fatto",
};
