// Connettori: catalogo, pagina generata dal manifesto, azioni nelle schede (web/moduli/connettori.js).
export default {
  'connettori.terzi': "Un connettore di terzi si copia nella cartella «connettori» accanto ai dati: lo accendi qui dopo averne controllato la somma.",
  'connettori.locale': "Installato a mano",
  'connettori.rotto': "Il connettore non si carica: controlla il file connettore.js",
  'connettori.stato-acceso': "Acceso",
  'connettori.stato-spento': "Spento",
  'connettori.stato-incompleto': "Da completare",
  'connettori.stato-cambiato': "Cambiato",
  'connettori.stato-rotto': "Rotto",
  'connettori.mancano': "Manca ancora: {cosa}",
  'connettori.cambiato': "Il file del connettore è cambiato dopo l'accensione: è fermo finché non lo riaccendi controllando la somma.",
  'connettori.accendi': "Accendi",
  'connettori.spegni': "Spegni",
  'connettori.accendi-titolo': "Accendere {nome}?",
  'connettori.potra': "Potrà:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "leggere",
  'connettori.p-crea': "creare",
  'connettori.p-modifica': "modificare",
  'connettori.p-elimina': "eliminare",
  'connettori.somma': "Somma di controllo (SHA-256) del file: confrontala con quella pubblicata da chi l'ha scritto.",
  'connettori.da-approvare': "Il codice di questo connettore non è ancora stato eseguito: Kubo lo legge solo dopo che confermi la somma qui sotto. Poi vedrai le sezioni che può usare.",
  'connettori.impostazioni': "Impostazioni",
  'connettori.salvato-segreto': "Salvato",
  'connettori.cambia': "Cambia",
  'connettori.togli': "Togli",
  'connettori.interni': "Permetti indirizzi della rete interna (un server in negozio, un registratore)",
  'connettori.salva': "Salva",
  'connettori.salvato': "Salvato",
  'connettori.prova': "Prova la connessione",
  'connettori.provo': "Provo…",
  'connettori.prova-ok': "Connessione riuscita",
  'connettori.prova-no': "Non va: {motivo}",
  'connettori.collegamento': "Collegamento",
  'connettori.webhook': "Indirizzo del webhook",
  'connettori.webhook-aiuto': "Incollalo nelle impostazioni dei webhook del servizio.",
  'connettori.indirizzo-segreto': "Indirizzo segreto",
  'connettori.indirizzo-aiuto': "Chi ha questo indirizzo vede i dati: dallo solo a chi serve.",
  'connettori.account': "Account",
  'connettori.collegato': "Collegato",
  'connettori.scollegato': "Non collegato",
  'connettori.scade': "Scade {quando}",
  'connettori.collega': "Collega l'account",
  'connettori.ricollega': "Ricollega",
  'connettori.oauth-ok': "Account collegato",
  'connettori.oauth-scaduto': "Il collegamento è scaduto: riprova",
  'connettori.oauth-errore': "Il collegamento non è riuscito: guarda il registro",
  'connettori.abbinamenti': "Abbinamenti dei campi",
  'connettori.abbinamenti-aiuto': "I campi del connettore e quelli di Kubo: se rinomini un campo l'abbinamento resta.",
  'connettori.sezione-manca': "Manca la sezione «{nome}»",
  'connettori.facoltativo': "facoltativo",
  'connettori.salva-abbinamenti': "Salva gli abbinamenti",
  'connettori.sincronizzazioni': "Sincronizzazioni",
  'connettori.ogni': "ogni {ogni}",
  'connettori.alle': "alle {alle}",
  'connettori.ultimo': "Ultimo giro: {quando}",
  'connettori.prossimo': "prossimo: {quando}",
  'connettori.sincronizza': "Sincronizza ora",
  'connettori.giro-ok': "Fatto",
  'connettori.coda': "In coda: {attesa} · fallite: {fallite}",
  'connettori.riprova': "Riprova le fallite",
  'connettori.registro': "Registro",
  'connettori.registro-vuoto': "Ancora niente: qui vedi cosa arriva e cosa parte.",
  'connettori.col-quando': "Quando",
  'connettori.col-verso': "Verso",
  'connettori.col-esito': "Esito",
  'connettori.col-cosa': "Cosa",
  'connettori.verso-entrata': "in arrivo",
  'connettori.verso-uscita': "in uscita",
  'connettori.verso-giro': "giro pianificato",
  'connettori.verso-azione': "azione",
  'connettori.verso-prova': "prova",
  'connettori.verso-oauth': "account",
  'connettori.verso-sistema': "sistema",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "errore",
  'connettori.esito-avviso': "avviso",
  'connettori.esito-ignorato': "ignorato",
  'connettori.copia': "Copia",
  'connettori.copiato': "Copiato",
  'connettori.annulla': "Annulla",
  'connettori.conferma': "Conferma",
  'connettori.fatto': "Fatto",
  // la libreria delle integrazioni e le ricette
  'connettori.libreria': "Libreria delle integrazioni",
  'connettori.libreria-sotto': "{n} integrazioni · {accese} accese. Le chiavi restano cifrate in Kubo e non tornano mai al browser.",
  'connettori.cerca': "Cerca: Stripe, fattura, WhatsApp, spedizioni…",
  'connettori.categorie': "Categorie",
  'connettori.tutte': "Tutte",
  'connettori.trovate': "{n} trovate",
  'connettori.le-tue': "Accese",
  'connettori.nessuna': "Nessuna integrazione trovata.",
  'connettori.prova-http': "Non c'è? Collegalo con HTTP / API REST",
  'connettori.smanettoni': "Per chi smanetta: le API di Kubo sono descritte in OpenAPI 3.1 su /api/openapi-3.1.json, e un connettore nuovo è una cartella con un file (docs/CONNETTORI.md).",
  'connettori.f-gratis': "Gratis",
  'connettori.f-facili': "Facili",
  'connettori.f-italia': "Italia",
  'connettori.stato-da-approvare': "Da approvare",
  'connettori.cat-pagamenti': "Pagamenti",
  'connettori.cat-cassa': "Cassa e POS",
  'connettori.cat-negozi-online': "Negozi online",
  'connettori.cat-marketplace': "Marketplace",
  'connettori.cat-fatturazione': "Fatturazione",
  'connettori.cat-contabilita': "Contabilità",
  'connettori.cat-banche': "Banche",
  'connettori.cat-spedizioni': "Spedizioni",
  'connettori.cat-whatsapp': "WhatsApp",
  'connettori.cat-messaggi': "Messaggi",
  'connettori.cat-email': "Email",
  'connettori.cat-sms': "SMS",
  'connettori.cat-calendario': "Calendario",
  'connettori.cat-prenotazioni': "Prenotazioni",
  'connettori.cat-archivio': "Archivio e file",
  'connettori.cat-produttivita': "Produttività",
  'connettori.cat-marketing': "Marketing",
  'connettori.cat-recensioni': "Recensioni",
  'connettori.cat-firma': "Firma",
  'connettori.cat-dati-aziende': "Dati delle aziende",
  'connettori.cat-automazione': "Automazione",
  'connettori.cat-ia': "Intelligenza artificiale",
  'connettori.cat-altro': "Altro",
  'connettori.costo-gratis': "Gratis",
  'connettori.costo-a-consumo': "A consumo",
  'connettori.costo-abbonamento': "In abbonamento",
  'connettori.costo-contratto': "Con contratto",
  'connettori.diff-facile': "Facile",
  'connettori.diff-media': "Media",
  'connettori.diff-difficile': "Per smanettoni",
  'connettori.zona-IT': "Italia",
  'connettori.zona-UE': "Europa",
  'connettori.zona-mondo': "Mondo",
  'connettori.prova-finto': "Provato con un servizio finto",
  'connettori.prova-vero': "Provato con il servizio vero",
  'connettori.prova-finto-aiuto': "Le prove automatiche usano un servizio finto che risponde come quello vero, secondo la documentazione nelle fonti: prima di affidarti, fai una prova in modalità test.",
  'connettori.prova-vero-aiuto': "Questo connettore è stato provato anche con il servizio vero.",
  'connettori.sito': "Sito del servizio",
  'connettori.apri': "Apri",
  'connettori.cosa-serve': "Cosa ti serve",
  'connettori.passi': "Passo per passo",
  'connettori.costo': "Costo",
  'connettori.difficolta': "Difficoltà",
  'connettori.fonti': "Fonti ({n})",
  'connettori.permessi-titolo': "Cosa potrà toccare",
  'connettori.nessun-permesso': "Nessuna sezione di Kubo: solo le chiamate che configuri.",
  'connettori.r-nessuna': "Ancora nessuna ricetta. Aggiungine una:",
  'connettori.r-tipo-uscita': "In uscita: quando cambia una riga",
  'connettori.r-tipo-azione': "Bottone nella scheda e Lumi",
  'connettori.r-tipo-entrata': "In entrata: il servizio scrive in Kubo",
  'connettori.r-nome': "Nome della ricetta",
  'connettori.r-attiva': "Attiva",
  'connettori.r-sezione': "Sezione",
  'connettori.r-eventi': "Quando la riga è",
  'connettori.ev-crea': "creata",
  'connettori.ev-modifica': "modificata",
  'connettori.ev-elimina': "eliminata",
  'connettori.ev-ripristina': "ripristinata",
  'connettori.r-metodo': "Metodo",
  'connettori.r-percorso': "Percorso (dopo l'indirizzo base) o indirizzo completo",
  'connettori.r-indirizzo': "Indirizzo che ti dà la piattaforma (https://…)",
  'connettori.r-corpo': "Corpo (JSON con i segnaposto; vuoto = tutta la riga)",
  'connettori.r-segnaposto': "Segnaposto: {campi}",
  'connettori.r-scrive': "Mostra l'anteprima e chiede conferma prima di partire",
  'connettori.r-modo': "Se la riga c'è già",
  'connettori.modo-crea-o-aggiorna': "aggiornala, altrimenti creala",
  'connettori.modo-crea': "crea sempre una riga nuova",
  'connettori.modo-aggiorna': "aggiorna soltanto",
  'connettori.r-chiave': "Campo chiave (per ritrovare la riga)",
  'connettori.r-elenco': "Elenco nel JSON (facoltativo, es. items)",
  'connettori.r-idevento': "Id dell'evento nel JSON (facoltativo, contro i doppioni)",
  'connettori.r-campi': "Abbinamenti (vuoto = le chiavi del JSON con gli stessi nomi dei campi)",
  'connettori.r-da': "Percorso nel JSON (es. cliente.email)",
  'connettori.r-a': "Campo di Kubo",
  'connettori.r-aggiungi-campo': "Aggiungi un abbinamento",
  'connettori.r-indirizzo-entrata': "Indirizzo da dare al servizio (POST JSON)",
  'connettori.r-salva-prima': "Salva e accendi per vedere l'indirizzo.",
  'connettori.copia': "Collega un altro servizio così",
  'connettori.copia-aiuto': "Un secondo servizio con il suo indirizzo, la sua autenticazione e le sue ricette.",
  'connettori.copia-nome': "Nome del servizio (es. CRM)",
  'connettori.copia-crea': "Crea",
  'connettori.copia-di': "Copia di «{nome}»",
  'connettori.togli-copia': "Togli questo servizio",
  'connettori.togli-copia-conferma': "Togliere «{nome}» con le sue impostazioni, i segreti e il registro?",
};
