// Area «desktop» (web/moduli/desktop.js): rete, backup e versioni nuove.
export default {
  'desktop.tipo-giornaliero': "Del giorno",
  'desktop.tipo-modifica': "Prima di una modifica",
  'desktop.tipo-manuale': "Fatto a mano",
  'desktop.tipo-sicurezza': "Prima di un ripristino",
  'desktop.tipo-caricato': "Caricato da fuori",
  'desktop.qr': "Codice QR con l'indirizzo",
  'desktop.rete-titolo': "Collega altri dispositivi",
  'desktop.lato-rete': "Collega dispositivi",
  'desktop.un-momento': "Un momento…",
  'desktop.copiato': "Copiato",
  'desktop.copia-fallita': "Copia non riuscita: selezionalo a mano",
  'desktop.indirizzo': "Indirizzo",
  'desktop.altra-rete': "Oppure, su un'altra rete dell'ufficio",
  'desktop.copia-indirizzo': "Copia l'indirizzo",
  'desktop.codice': "Codice",
  'desktop.passo-telefono': "Telefono o tablet:",
  'desktop.passo-telefono-testo': "inquadra il codice con la fotocamera e tocca il collegamento.",
  'desktop.passo-computer': "Un altro computer:",
  'desktop.passo-computer-codice': "apri il browser e scrivi l'indirizzo. Con l'app Kubo scegli «Collegati a un Kubo in rete» e scrivi il codice.",
  'desktop.passo-computer-indirizzo': "apri il browser e scrivi l'indirizzo. Con l'app Kubo scegli «Collegati a un Kubo in rete» e scrivi l'indirizzo.",
  'desktop.solo-qui': "Adesso Kubo risponde solo a questo computer.",
  'desktop.apri-rete': "Per usarlo anche dagli altri dispositivi, nell'app Kubo apri il menu nella barra in alto (o nell'area di notifica) e accendi «Aperto alla rete locale».",
  'desktop.da-terminale': "Se lo avvii da terminale:",
  'desktop.non-in-rete': "Questo computer non sembra collegato a una rete. Collegalo al Wi-Fi o al cavo dell'ufficio e ricarica la pagina.",
  'desktop.stessa-rete': "Gli altri dispositivi devono essere sulla stessa rete (lo stesso Wi-Fi o lo stesso cavo). Se non si collegano, controlla che il firewall di questo computer lasci passare Kubo.",
  'desktop.backup': "Backup",
  'desktop.fai-adesso': "Fai un backup adesso",
  'desktop.copia-in-corso': "Copia in corso…",
  'desktop.fatto': "Backup fatto",
  'desktop.ultimo': "Ultimo backup",
  'desktop.nessuno-ancora': "Ancora nessuno",
  'desktop.copie-tenute': "Copie tenute",
  'desktop.in-tutto': "{peso} in tutto",
  'desktop.spiega-automatici': "Ogni giorno Kubo fa da solo una copia del database, e una prima di ogni modifica alla struttura o di un import. Tiene {giornalieri} copie giornaliere, {settimanali} settimanali e {mensili} mensili; quelle fatte a mano restano finché non le elimini. Gli allegati vanno nella cartella «allegati», copiando solo quelli nuovi.",
  'desktop.spiega-spenti': "I backup automatici sono spenti (KUBO_BACKUP=0): ricordati di farli a mano o con i tuoi strumenti.",
  'desktop.cartella-esempio': "Per esempio {a} oppure {b}",
  'desktop.cartella-nuova': "Da adesso i backup vanno lì",
  'desktop.cartella-tornata': "I backup tornano accanto ai dati",
  'desktop.scegli-cartella': "Scegli una cartella…",
  'desktop.dove': "Dove vanno i backup",
  'desktop.in-memoria': "(database in memoria: niente backup)",
  'desktop.nota-esterna': "Una cartella scelta da te. Se il disco non è collegato, la copia del giorno va accanto ai dati e qui compare un avviso.",
  'desktop.nota-accanto': "Accanto ai dati, su questo computer. Meglio una seconda copia altrove: un disco esterno, oppure una cartella sincronizzata (Dropbox, OneDrive, iCloud, Google Drive).",
  'desktop.usa-cartella': "Usa questa cartella",
  'desktop.torna-accanto': "Torna accanto ai dati",
  'desktop.vuoto': "Nessun backup ancora. Il primo arriva da solo entro pochi minuti, oppure fallo adesso.",
  'desktop.col-quando': "Quando",
  'desktop.col-tipo': "Tipo",
  'desktop.col-dimensione': "Dimensione",
  'desktop.accanto-ai-dati': "accanto ai dati",
  'desktop.scarica': "Scarica",
  'desktop.ripristina': "Ripristina",
  'desktop.elimina': "Elimina questo backup",
  'desktop.elimina-conferma': "Eliminare il backup del {quando}? Non si potrà più ripristinare.",
  'desktop.eliminato': "Backup eliminato",
  'desktop.ripristino-titolo': "Tornare a questo backup?",
  'desktop.ripristino-prima': "Il gestionale tornerà com'era",
  'desktop.ripristino-dopo': ". Tutto quello che è stato fatto dopo sparisce dalla vista.",
  'desktop.ripristino-nota': "Prima Kubo fa una copia di adesso («{tipo}»): se cambi idea, ripristini quella e non perdi niente. Chi sta lavorando sugli altri dispositivi vedrà la pagina ricaricarsi.",
  'desktop.capito': "Ho capito, voglio tornare a quel momento",
  'desktop.annulla': "Annulla",
  'desktop.ripristino-in-corso': "Ripristino in corso…",
  'desktop.ripristinato': "Ripristinato",
  'desktop.ripristinato-altro': "Il titolare ha ripristinato un backup: ricarico…",
  'desktop.caricato': "Backup caricato: {azienda}, {persone}, {sezioni}. Lo trovi in cima all'elenco.",
  'desktop.persone': {"one": "{n} persona", "other": "{n} persone"},
  'desktop.sezioni': {"one": "{n} sezione", "other": "{n} sezioni"},
  'desktop.carica': "Carica un backup",
  'desktop.carica-nota': "Un file .db scaricato da qui, anche da un altro computer. Kubo lo controlla e lo mette nell'elenco: poi scegli tu se ripristinarlo.",
  'desktop.scegli-file': "Scegli il file…",
  'desktop.uscita-versione': "È uscita la versione",
  'desktop.novita': "cosa c'è di nuovo",
  'desktop.aggiornato': "Hai l'ultima versione.",
  'desktop.versioni': "Versioni nuove",
  'desktop.stai-usando': "Stai usando Kubo",
  'desktop.controlla-ogni-giorno': "Controlla ogni giorno se è uscita una versione nuova e avvisami",
  'desktop.versioni-nota': "Kubo chiede solo il numero dell'ultima versione pubblicata su GitHub: non manda dati dell'azienda e non installa niente da solo. Aggiorni tu, quando vuoi, dopo un backup.",
  'desktop.controlla-adesso': "Controlla adesso",
  'desktop.avviso-versione': "È uscita Kubo",
  'desktop.dettagli': "Dettagli",
  'desktop.chiudi': "Chiudi",
  'desktop.solo-titolare': "I backup li gestisce il titolare.",
};
