// Fatture elettroniche (web/moduli/fatture.js): fatture ricevute, bollo virtuale, numerazione.
export default {
  'fatture.aggiorna-chiedi': "Le fatture di Kubo sono cresciute: prezzi fino a 8 decimali, cassa previdenziale, Pubblica Amministrazione, fatture ricevute. Aggiungo i campi nuovi adesso? Nessun dato si perde.",
  'fatture.aggiornato': "Fatture aggiornate",
  'fatture.bloccata': "Emessa · bloccata",
  'fatture.bloccata-nota': "Una fattura emessa non si modifica più: si corregge con una nota di credito o di debito. Puoi cambiare lo stato del pagamento e le note interne.",
  'fatture.bollo': "Bollo virtuale",
  'fatture.bollo-nota': "Il bollo si versa con l'F24 (codici tributo 2521-2524) o dall'area riservata dell'Agenzia delle Entrate, che ogni trimestre prepara l'importo. Contano le fatture emesse con il bollo spuntato.",
  'fatture.chiudi': "Chiudi",
  'fatture.codice-tributo': "Codice tributo",
  'fatture.crea-integrazione': "Crea integrazione",
  'fatture.da-integrare': "Da integrare",
  'fatture.da-pagare': "Da pagare",
  'fatture.da-versare': "Da versare",
  'fatture.emesse': "Emesse",
  'fatture.entro': "Entro il",
  'fatture.fatture-con-bollo': "Fatture con bollo",
  'fatture.fornitore-nuovo': "nuovo",
  'fatture.gia-importata': "{numero} c'era già",
  'fatture.importa': "Importa fatture",
  'fatture.importata': "{numero} del {data} · {totale}",
  'fatture.integra-conferma': "Creo l'integrazione (o autofattura) della fattura {numero}? Nasce in bozza: la controlli e la emetti tu.",
  'fatture.integra-nota': "Fattura ricevuta in reverse charge o da un fornitore estero: serve l'integrazione TD16-TD19.",
  'fatture.integrazione-creata': "Integrazione {tipo} creata in bozza",
  'fatture.intestata-ad-altri': "non è intestata alla tua partita IVA",
  'fatture.leggo': "Leggo…",
  'fatture.manca-modello': "Aggiungi prima il modello «Fatture e fattura elettronica».",
  'fatture.mancano': "Numeri mancanti",
  'fatture.nessun-buco': "nessun buco",
  'fatture.nessuna-emessa': "Nessuna fattura emessa in quest'anno.",
  'fatture.niente-da-integrare': "Niente da integrare.",
  'fatture.niente-da-pagare': "Niente da pagare.",
  'fatture.numerazione': "Numerazione",
  'fatture.numerazione-nota': "I numeri vanno in fila per serie e anno, senza buchi. Un buco di solito viene da una fattura riportata a mano: controlla prima di emettere la prossima.",
  'fatture.ricevute': "Ricevute",
  'fatture.ricevute-nota': "Scarica le fatture dal cassetto fiscale o dalla PEC e trascinale qui: anche le .p7m firmate e i file con più fatture. Kubo crea il fornitore, registra il costo e la scadenza.",
  'fatture.serie': "Serie",
  'fatture.serie-principale': "principale",
  'fatture.solo-xml': "Solo file .xml o .p7m",
  'fatture.stampa': "Stampa",
  'fatture.titolo': "Fatture elettroniche",
  'fatture.totale': "Totale",
  'fatture.trascina': "Trascina qui le fatture ricevute",
  'fatture.trascina-nota': "oppure tocca per scegliere i file (.xml, .xml.p7m)",
  'fatture.trimestre': "Trimestre",
  'fatture.trimestre-n': "{n}° trimestre",
  'fatture.troppo-grande': "File troppo grande (al massimo 5 MB)",
  'fatture.tutte-le-ricevute': "Tutte le fatture ricevute →",
  'fatture.ultimo': "Ultimo",
  'fatture.vedi': "Vedi la fattura",
  'fatture.vista': "Fattura ricevuta",
};
