// Il fisco (web/moduli/fisco.js): IVA, LIPE, forfettario, F24, ritenute, scadenze, pacchetto per il commercialista.
export default {
  'fisco.titolo': "Fisco",
  'fisco.anno': "Anno",
  'fisco.responsabilita': "Kubo calcola e prepara dai dati del gestionale: controlla prima di pagare o inviare. La responsabilità resta del contribuente.",
  'fisco.scheda-riepilogo': "Da pagare",
  'fisco.scheda-iva': "IVA",
  'fisco.scheda-forfettario': "Forfettario",
  'fisco.scheda-f24': "F24",
  'fisco.scheda-ritenute': "Ritenute",
  'fisco.scheda-scadenze': "Scadenze",
  'fisco.scheda-commercialista': "Per il commercialista",
  'fisco.scheda-impostazioni': "Impostazioni",
  'fisco.da-pagare-anno': "Ancora da pagare quest'anno",
  'fisco.prossimo': "Prossimo versamento",
  'fisco.niente': "Niente in vista.",
  'fisco.regime': "Regime",
  'fisco.coeff': "coefficiente {n}%",
  'fisco.regime-forfettario': "Forfettario",
  'fisco.regime-semplificato': "Semplificato",
  'fisco.regime-ordinario': "Ordinario",
  'fisco.periodicita-trimestrale': "IVA trimestrale",
  'fisco.periodicita-mensile': "IVA mensile",
  'fisco.manca-ricevute': "Per l'IVA sugli acquisti e le ritenute aggiungi la sezione «Fatture ricevute».",
  'fisco.apri-impostazioni': "Apri le impostazioni",
  'fisco.prossimi-versamenti': "Prossimi versamenti",
  'fisco.data': "Data",
  'fisco.cosa': "Cosa",
  'fisco.codice': "Codice",
  'fisco.anno-rif': "Anno rif.",
  'fisco.importo': "Importo",
  'fisco.vedi-f24': "F24",
  'fisco.prossime-scadenze': "Prossime scadenze",
  'fisco.mese-n': "Mese {n}",
  'fisco.trimestre-n': "{n}° trimestre",
  'fisco.lipe-trimestre': "LIPE {n}° trimestre",
  'fisco.liquidazioni': "Liquidazioni periodiche",
  'fisco.periodo': "Periodo",
  'fisco.iva-vendite': "IVA vendite",
  'fisco.iva-acquisti': "IVA detraibile",
  'fisco.riporti': "Riporti",
  'fisco.interessi': "Interessi 1%",
  'fisco.da-versare': "Da versare",
  'fisco.scadenza': "Scadenza",
  'fisco.a-credito': "a credito {importo}",
  'fisco.riportato': "si riporta (fino a 100 €)",
  'fisco.acconto-dicembre': "Acconto IVA di dicembre",
  'fisco.acconto-dovuto': "Acconto di {importo} con il metodo {metodo}: codice {codice}, entro il {data}.",
  'fisco.acconto-no': "Acconto non dovuto (sotto 103,29 € o mancano i dati: inseriscili nelle impostazioni).",
  'fisco.acconto-nota': "Storico: 88% di quanto versato per l'ultimo periodo dell'anno scorso. Previsionale: 88% di quanto prevedi per l'ultimo periodo di quest'anno. Kubo sceglie il minore.",
  'fisco.metodo-storico': "storico",
  'fisco.metodo-previsionale': "previsionale",
  'fisco.lipe': "Comunicazione liquidazioni periodiche (LIPE)",
  'fisco.lipe-passo-1': "Scarica il file XML del trimestre qui sopra.",
  'fisco.lipe-passo-2': "Entra in «Fatture e Corrispettivi» sul sito dell'Agenzia delle Entrate con SPID, CIE o CNS.",
  'fisco.lipe-passo-3': "Apri il servizio delle liquidazioni periodiche IVA e scegli l'invio del file già pronto.",
  'fisco.lipe-passo-4': "Carica il file e conferma: il sistema lo controlla subito.",
  'fisco.lipe-passo-5': "Scarica la ricevuta dopo qualche minuto e conservala.",
  'fisco.lipe-nota': "Scadenze: 31 maggio, 30 settembre, 30 novembre e fine febbraio. Se qualcosa non torna, la precompilata dell'Agenzia aiuta a confrontare.",
  'fisco.registri': "Registri IVA",
  'fisco.registri-nota': "I registri delle vendite, degli acquisti e dei corrispettivi sono nel pacchetto per il commercialista, in CSV ed Excel.",
  'fisco.debito-prec': "debito prec. {importo}",
  'fisco.credito-prec': "credito prec. {importo}",
  'fisco.credito-anno': "credito anno prec. {importo}",
  'fisco.meno-acconto': "acconto {importo}",
  'fisco.non-forfettario': "L'azienda non è nel regime forfettario: lo cambi nelle impostazioni.",
  'fisco.sim-quanto': "Se incasso ancora (€)",
  'fisco.sim-esito': "Incassando altri {piu} paghi circa {tasse} in più fra imposta e contributi: te ne restano {resta}.",
  'fisco.niente-acconti': "Nessun acconto dovuto.",
  'fisco.incassato': "Incassato",
  'fisco.incassato-nota': "fatture con «Pagata il» quest'anno",
  'fisco.reddito': "Reddito",
  'fisco.contributi': "Contributi INPS",
  'fisco.imposta': "Imposta sostitutiva",
  'fisco.aliquota-n': "aliquota {n}%",
  'fisco.soglia': "Soglia di 85.000 €",
  'fisco.soglia-nota': "Hai usato il {usato}% della soglia: restano {margine}. Oltre 100.000 € si esce dal regime subito.",
  'fisco.simulazione': "Simulazione",
  'fisco.simula': "Calcola",
  'fisco.acconti-anno': "Acconti {anno}",
  'fisco.acconti-base': "Calcolati sull'imposta dell'anno prima: {importo}.",
  'fisco.saldo-stima': "Saldo stimato da pagare l'anno prossimo: {importo}.",
  'fisco.gestione-artigiani': "INPS artigiani",
  'fisco.gestione-commercianti': "INPS commercianti",
  'fisco.gestione-separata': "Gestione separata",
  'fisco.gestione-cassa': "Cassa professionale",
  'fisco.gestione-nessuna': "Nessuna",
  'fisco.stampa-f24': "Stampa F24",
  'fisco.stampa': "Stampa o salva PDF",
  'fisco.chiudi': "Chiudi",
  'fisco.f24-del': "F24 del {data}",
  'fisco.sezione': "Sezione",
  'fisco.rateazione': "Rateazione / periodo",
  'fisco.sezione-erario': "Erario",
  'fisco.sezione-inps': "INPS",
  'fisco.sezione-locali': "Tributi locali",
  'fisco.f24-come': "Ricopia le righe in F24 web (Agenzia delle Entrate) o nell'home banking. Se compensi un credito, o il saldo è zero, devi usare i servizi dell'Agenzia.",
  'fisco.registro-ritenute': "Ritenute operate",
  'fisco.pagata-il': "Pagata il",
  'fisco.percipiente': "Percipiente",
  'fisco.compenso': "Compenso",
  'fisco.ritenuta': "Ritenuta",
  'fisco.versare-entro': "Versare entro",
  'fisco.ritenute-vuoto': "Nessuna ritenuta: si registrano nelle fatture ricevute dai professionisti (ritenuta e data di pagamento).",
  'fisco.riepilogo-cu': "Riepilogo per la Certificazione Unica e il 770",
  'fisco.cf': "Codice fiscale",
  'fisco.causale': "Causale",
  'fisco.cu-nota': "Sono i dati da riportare: la CU si consegna entro il 16 marzo e si invia all'Agenzia; il 770 entro il 31 ottobre. Kubo non li invia.",
  'fisco.scadenze-anno': "Scadenze {anno}",
  'fisco.scadenze-nota': "Solo le scadenze che riguardano il tuo regime. Le date cadute di sabato o festivo sono già spostate al primo giorno lavorativo.",
  'fisco.dal': "Dal",
  'fisco.al': "Al",
  'fisco.scarica-pacchetto': "Scarica lo zip",
  'fisco.pacchetto': "Pacchetto per il commercialista",
  'fisco.pacchetto-cosa': "Uno zip con le copie XML delle fatture emesse, i registri IVA, le liquidazioni, la prima nota e le ritenute in CSV ed Excel, e un riepilogo in PDF.",
  'fisco.quando-professionista': "Quando serve davvero un professionista",
  'fisco.pro-dichiarazioni': "Le dichiarazioni (Redditi, IVA annuale, 770) puoi inviarle da solo con SPID; per farle inviare a qualcuno serve un intermediario abilitato.",
  'fisco.pro-visto': "Per compensare in F24 un credito IVA oltre 5.000 € serve il visto di conformità di un professionista.",
  'fisco.pro-consulenza': "Scelta del regime, riduzione INPS del 35%, rateazioni, controlli e avvisi: è consulenza, chiedi a un commercialista.",
  'fisco.pro-redditi': "IRPEF, IRES e IRAP del regime ordinario o semplificato le calcola il commercialista o la precompilata, non Kubo.",
  'fisco.salva': "Salva",
  'fisco.salvate': "Impostazioni salvate",
  'fisco.sezioni': "Sezioni per il fisco",
  'fisco.sezioni-cosa': "Aggiunge «Fatture ricevute» (acquisti e ritenute) e, se vendi al banco, «Corrispettivi».",
  'fisco.anche-corrispettivi': "Anche i corrispettivi giornalieri",
  'fisco.aggiungi-sezioni': "Aggiungi le sezioni",
  'fisco.sezioni-aggiunte': "Sezioni aggiunte",
  'fisco.manca-piva': "Mancano la partita IVA o il codice fiscale dell'azienda.",
  'fisco.apri-documenti': "Aprili in Documenti",
  'fisco.gruppo-regime': "Regime e attività",
  'fisco.gruppo-inps': "Contributi INPS",
  'fisco.gruppo-forfettario': "Forfettario",
  'fisco.gruppo-iva': "IVA",
  'fisco.gruppo-altro': "Altro",
  'fisco.promemoria': "Fisco: {cosa} il {data}",
  'fisco.imp-regime': "Regime fiscale",
  'fisco.impn-regime': "Se non lo sai, chiedilo al commercialista: è una scelta che cambia tutto.",
  'fisco.imp-periodicita': "Liquidazione IVA",
  'fisco.impn-periodicita': "Trimestrale con l'1% di interessi, se il volume d'affari lo permette.",
  'fisco.imp-ateco': "Codice ATECO",
  'fisco.impn-ateco': "Lo trovi nel certificato di attribuzione della partita IVA.",
  'fisco.imp-coefficiente': "Coefficiente di redditività %",
  'fisco.impn-coefficiente': "Vuoto: quello della tabella ufficiale per il tuo ATECO.",
  'fisco.imp-gestione': "Gestione previdenziale",
  'fisco.impn-gestione': "Per le casse professionali Kubo non calcola i contributi.",
  'fisco.imp-riduzione35': "Riduzione del 35% dei contributi",
  'fisco.impn-riduzione35': "Solo forfettari artigiani e commercianti che l'hanno chiesta all'INPS.",
  'fisco.imp-aliquotaridotta': "Aliquota del 5% (primi cinque anni)",
  'fisco.impn-aliquotaridotta': "Per le attività nuove con i requisiti di legge; altrimenti 15%.",
  'fisco.imp-impostaannoprecedente': "Imposta sostitutiva dell'anno scorso (€)",
  'fisco.impn-impostaannoprecedente': "Base degli acconti. Vuoto: la calcola Kubo dai dati.",
  'fisco.imp-accontiversatiannoprecedente': "Acconti versati l'anno scorso (€)",
  'fisco.impn-accontiversatiannoprecedente': "Per calcolare il saldo di giugno.",
  'fisco.imp-contributiversati': "Contributi versati quest'anno (€)",
  'fisco.impn-contributiversati': "Si deducono dal reddito. Vuoto: si usa la stima.",
  'fisco.imp-sedeinps': "Codice sede INPS",
  'fisco.impn-sedeinps': "Per la sezione INPS dell'F24.",
  'fisco.imp-matricolainps': "Matricola o codice INPS",
  'fisco.impn-matricolainps': "Nella gestione separata è il tuo codice fiscale.",
  'fisco.imp-creditoannoprecedente': "Credito IVA dell'anno scorso (€)",
  'fisco.impn-creditoannoprecedente': "Si usa nelle liquidazioni finché c'è.",
  'fisco.imp-accontoivastorico': "Versato per l'ultimo periodo dell'anno scorso (€)",
  'fisco.impn-accontoivastorico': "Per l'acconto con il metodo storico.",
  'fisco.imp-accontoivaprevisto': "Previsto per l'ultimo periodo di quest'anno (€)",
  'fisco.impn-accontoivaprevisto': "Per il metodo previsionale. Vuoto: la stima di Kubo.",
  'fisco.imp-camerale': "Diritto camerale annuo (€)",
  'fisco.impn-camerale': "L'importo lo comunica la tua Camera di commercio.",
  'fisco.imp-provinciacciaa': "Provincia della Camera di commercio",
  'fisco.impn-provinciacciaa': "Sigla, per esempio MI.",
  'fisco.imp-bollo': "Bollo virtuale sulle fatture",
  'fisco.impn-bollo': "Nel forfettario è sempre attivo.",
  'fisco.imp-sostituto': "Sono sostituto d'imposta",
  'fisco.impn-sostituto': "Paghi professionisti trattenendo la ritenuta.",
  'fisco.v-iva': "IVA del periodo {periodo}",
  'fisco.v-iva-saldo': "Saldo IVA annuale",
  'fisco.v-iva-acconto': "Acconto IVA",
  'fisco.v-forf-saldo': "Saldo imposta sostitutiva {anno}",
  'fisco.v-forf-acconto': "Acconto imposta sostitutiva {anno}",
  'fisco.v-inps-acconto': "Acconto contributi INPS {anno}",
  'fisco.v-inps-fissi': "Contributi INPS fissi",
  'fisco.v-bollo': "Bollo virtuale, {periodo}° trimestre",
  'fisco.v-ritenute': "Ritenute del mese {periodo}",
  'fisco.v-camerale': "Diritto camerale {anno}",
  'fisco.sc-iva-mese': "Versamento IVA del mese {periodo}",
  'fisco.sc-iva-trimestre': "Versamento IVA del {periodo}° trimestre",
  'fisco.sc-iva-saldo': "Saldo IVA annuale",
  'fisco.sc-iva-acconto': "Acconto IVA",
  'fisco.sc-lipe': "LIPE del {periodo}° trimestre",
  'fisco.sc-dichiarazione-iva': "Dichiarazione IVA {anno}",
  'fisco.sc-forf-saldo-acconto': "Saldo e primo acconto dell'imposta sostitutiva",
  'fisco.sc-redditi-saldo-acconto': "Saldo e primo acconto delle imposte sui redditi",
  'fisco.sc-forf-acconto2': "Secondo acconto dell'imposta sostitutiva",
  'fisco.sc-redditi-acconto2': "Secondo acconto delle imposte sui redditi",
  'fisco.sc-dichiarazione-redditi': "Dichiarazione dei redditi {anno}",
  'fisco.sc-inps-fissi': "Contributi INPS fissi, rata {periodo}",
  'fisco.sc-inps-saldo-acconto': "Contributi INPS: saldo e acconto",
  'fisco.sc-inps-riduzione': "Domanda di riduzione INPS del 35%",
  'fisco.sc-bollo': "Bollo virtuale, {periodo}° trimestre {anno}",
  'fisco.sc-ritenute': "Ritenute del mese {periodo}",
  'fisco.sc-cu-consegna': "Certificazione Unica ai percipienti",
  'fisco.sc-cu-invio': "Certificazione Unica all'Agenzia (lavoro autonomo)",
  'fisco.sc-modello-770': "Modello 770",
  'fisco.sc-camerale': "Diritto camerale",
  'fisco.av-vicino-85': "Sei vicino alla soglia di 85.000 €: se la superi, dall'anno prossimo esci dal forfettario.",
  'fisco.av-oltre-85': "Hai superato 85.000 €: dall'anno prossimo esci dal forfettario. Parlane con un commercialista.",
  'fisco.av-oltre-100': "Hai superato 100.000 €: esci dal forfettario subito, con l'IVA dall'operazione che ha superato la soglia. Serve un commercialista.",
  'fisco.av-fuori-dal-regime': "L'anno scorso hai incassato più di 85.000 €: quest'anno non potresti essere nel forfettario. Verifica con un commercialista.",
  'fisco.av-contributi-stimati': "I contributi dedotti sono stimati: scrivi nelle impostazioni quelli versati davvero quest'anno.",
  'fisco.av-cassa-professionale': "Con una cassa professionale i contributi li calcola la cassa: Kubo non li conta.",
  'fisco.av-incassi-senza-data': "Alcune fatture pagate non hanno «Pagata il»: le conto alla data della fattura.",
  'fisco.av-visto-conformita': "Il credito IVA supera 5.000 €: per compensarlo in F24 serve il visto di conformità.",
  'fisco.av-forfettario-niente-iva': "Nel forfettario non c'è IVA da liquidare né LIPE: guarda il cruscotto del forfettario.",
  'fisco.av-redditi-professionista': "IRPEF, IRES e IRAP non sono qui: le calcola il commercialista o la precompilata.",
  'fisco.av-inps-cassetto': "Le rate fisse INPS sono una stima: l'F24 ufficiale è nel Cassetto previdenziale.",
  'fisco.av-cu-intermediario': "Con 20 o più CU non bastano le tue credenziali: serve Entratel o un intermediario.",
  'fisco.av-cu-fisconline': "Con meno di 20 CU puoi inviarle da solo con le tue credenziali.",
};
