// Personalizza, persone e permessi, lingua e valuta (web/personalizza.js, web/utenti.js, web/moduli/lingue.js).
export default {
  'gestione.tipo-testo': 'Testo',
  'gestione.tipo-testo_lungo': 'Testo lungo',
  'gestione.tipo-numero': 'Numero',
  'gestione.tipo-valuta': 'Importo ({simbolo})',
  'gestione.tipo-percentuale': 'Percentuale',
  'gestione.tipo-data': 'Data',
  'gestione.tipo-data_ora': 'Data e ora',
  'gestione.tipo-si_no': 'Sì / No',
  'gestione.tipo-scelta': 'Scelta',
  'gestione.tipo-scelta_multipla': 'Scelta multipla',
  'gestione.tipo-stato': 'Stato (flusso)',
  'gestione.tipo-relazione': 'Collegamento',
  'gestione.tipo-righe': 'Righe (sotto-tabella)',
  'gestione.tipo-calcolato': 'Calcolato (formula)',
  'gestione.tipo-contatore': 'Numerazione',
  'gestione.tipo-email': 'Email',
  'gestione.tipo-telefono': 'Telefono',
  'gestione.tipo-url': 'Sito web',
  'gestione.tipo-indirizzo': 'Indirizzo',
  'gestione.tipo-codice_a_barre': 'Codice a barre',
  'gestione.tipo-durata': 'Durata (minuti)',
  'gestione.tipo-immagine': 'Immagine',
  'gestione.tipo-file': 'File',
  'gestione.nome': 'Nome',
  'gestione.esempio-sezione': 'es. Noleggi',
  'gestione.archivia-campo': 'Archivia il campo (i valori restano)',
  'gestione.obbligatorio': 'Obbligatorio',
  'gestione.senza-doppioni': 'Senza doppioni',
  'gestione.prima-opzione': 'Prima opzione',
  'gestione.opzioni': 'Opzioni, una per riga (colori: {colori})',
  'gestione.righe-di': 'Righe di',
  'gestione.collegato-a': 'Collegato a',
  'gestione.piu-di-uno': 'Più di uno',
  'gestione.campo-punta': 'Campo che punta qui (nell\'altra entità)',
  'gestione.formula': 'Formula (es. quantita * prezzo · SOMMA(righe.totale) · SE(giacenza <= soglia; "sì"; "no"))',
  'gestione.mostra-come': 'Mostra come',
  'gestione.automatico': 'Automatico',
  'gestione.importo': 'Importo',
  'gestione.formato-contatore': 'Formato ({AAAA} anno, {N:4} numero a 4 cifre)',
  'gestione.salva-modifiche': 'Salva le modifiche',
  'gestione.dai-nome': 'Dai un nome',
  'gestione.piu-campo': '+ Campo',
  'gestione.personalizza-nome': 'Personalizza · {nome}',
  'gestione.icona': 'Icona',
  'gestione.nome-elemento': 'Nome di ogni elemento',
  'gestione.nota-dati': 'Rinominare e spostare non tocca i dati. Un campo tolto viene archiviato con i suoi valori e si può ripristinare. Se un cambio di tipo perderebbe dei valori, il salvataggio si ferma e ti dice quali.',
  'gestione.password-8': 'Password (8+)',
  'gestione.aggiungi': 'Aggiungi',
  'gestione.aggiunto': 'Aggiunto',
  'gestione.ruolo-cambiato': 'Ruolo cambiato',
  'gestione.disattiva': 'Disattiva',
  'gestione.riattiva': 'Riattiva',
  'gestione.ruolo': 'Ruolo',
  'gestione.nuova-persona': 'Nuova persona',
  'gestione.ruoli': 'Ruoli',
  'gestione.nota-ruoli': 'Il titolare può tutto. Per gli altri ruoli scegli, sezione per sezione, cosa possono fare.',
  'gestione.nuovo-ruolo': '+ Nuovo ruolo',
  'gestione.nome-ruolo': 'Nome del ruolo (es. Banco, Laboratorio)',
  'gestione.vede': 'Vede',
  'gestione.modifica': 'Modifica',
  'gestione.campi-nascosti-ruolo': 'Campi nascosti a questo ruolo',
  'gestione.salva-ruolo': 'Salva il ruolo',
  'gestione.ruolo-salvato': 'Ruolo salvato',
  'gestione.puo-personalizzare': 'Può personalizzare',
  'gestione.sezione': 'Sezione',
  'gestione.campi-nascosti': 'Campi nascosti (⌘/Ctrl per sceglierne più d\'uno)',
  'gestione.ruolo-titolare': 'Titolare',
  'gestione.ruolo-collaboratore': 'Collaboratore',
  'gestione.ruolo-lettura': 'Solo lettura',
  'gestione.lingua-valuta': 'Lingua e valuta',
  'gestione.tua-lingua': 'La tua lingua',
  'gestione.tua-lingua-nota': 'Vale solo per te, su ogni dispositivo.',
  'gestione.azienda': 'Per tutta l\'azienda',
  'gestione.lingua-modelli': 'Lingua dei modelli nuovi',
  'gestione.lingua-modelli-nota': 'I modelli che aggiungi da qui in poi arrivano con i nomi in questa lingua. Le sezioni che ci sono già non cambiano.',
  'gestione.valuta-nota': 'Gli importi si mostrano in questa valuta. I valori salvati non cambiano: cambiano solo il simbolo e il formato.',
  'gestione.esempio': 'Così: {numero} · {soldi} · {data}',
  'gestione.salvato-ricarico': 'Salvato: ricarico la pagina',
  'gestione.settimana-da': 'La settimana comincia di {giorno}.',
};
