// Il magazzino (web/moduli/magazzino.js): valore, inventario, movimenti.
export default {
  'magazzino.titolo': "Magazzino",
  'magazzino.scheda-valore': "Valore",
  'magazzino.scheda-inventario': "Inventario",
  'magazzino.scheda-movimenti': "Movimenti",
  'magazzino.sezione': "Sezione del magazzino",
  'magazzino.nessuna-sezione': "Nessuna sezione con la giacenza: aggiungi il campo «giacenza» agli articoli.",
  'magazzino.valore': "Valore",
  'magazzino.al-costo': "al costo degli articoli",
  'magazzino.pezzi': "Pezzi",
  'magazzino.articoli-n': {"one": "{n} articolo", "other": "{n} articoli"},
  'magazzino.sotto-scorta': "Sotto scorta",
  'magazzino.negativi': {"one": "{n} articolo con giacenza negativa: {nomi}", "other": "{n} articoli con giacenza negativa: {nomi}"},
  'magazzino.senza-costo': {"one": "{n} articolo in giacenza non ha il costo: non entra nel valore.", "other": "{n} articoli in giacenza non hanno il costo: non entrano nel valore."},
  'magazzino.per-categoria': "Per categoria",
  'magazzino.categoria': "Categoria",
  'magazzino.articoli': "Articoli",
  'magazzino.senza-categoria': "Senza categoria",
  'magazzino.per-articolo': "Per articolo",
  'magazzino.codice': "Codice",
  'magazzino.articolo': "Articolo",
  'magazzino.giacenza': "Giacenza",
  'magazzino.costo': "Costo",
  'magazzino.scarica-csv': "Scarica in CSV",
  'magazzino.nota-valore': "Il valore è giacenza × costo. Il costo lo aggiornano gli acquisti al costo medio ponderato. È il dato delle rimanenze per il commercialista.",
  'magazzino.inventario-nota': "Conta la merce sugli scaffali: le giacenze di adesso restano come riferimento, e alla chiusura ogni articolo contato si corregge della differenza. Le vendite fatte mentre conti restano giuste.",
  'magazzino.continua': "Continua «{nome}»",
  'magazzino.nuovo-inventario': "Inizia un inventario",
  'magazzino.inventari': "Inventari",
  'magazzino.nome': "Nome",
  'magazzino.iniziato': "Iniziato",
  'magazzino.contati': "Contati",
  'magazzino.stato': "Stato",
  'magazzino.chiuso-il': "Chiuso il {data}",
  'magazzino.aperto': "Aperto",
  'magazzino.leggi-codice': "Leggi un codice (lettore o tastiera, poi Invio)",
  'magazzino.letto': "{nome}: {n}",
  'magazzino.cerca': "Cerca articolo o codice",
  'magazzino.attesa': "Atteso",
  'magazzino.contata': "Contato",
  'magazzino.differenza': "Differenza",
  'magazzino.chiudi-conferma': {"one": "Chiudere l'inventario? Si corregge {n} giacenza.", "other": "Chiudere l'inventario? Si correggono {n} giacenze."},
  'magazzino.chiuso': {"one": "Inventario chiuso: {n} rettifica, {importo}", "other": "Inventario chiuso: {n} rettifiche, {importo}"},
  'magazzino.differenze': "Differenze",
  'magazzino.valore-differenze': "Valore delle differenze",
  'magazzino.chiudi': "Chiudi l'inventario",
  'magazzino.chiudi-nota': "Gli articoli non contati restano come sono.",
  'magazzino.quando': "Quando",
  'magazzino.movimento': "Movimento",
  'magazzino.origine': "Origine",
  'magazzino.chi': "Chi",
  'magazzino.origine-iniziale': "Giacenza iniziale",
  'magazzino.origine-modifica': "Modifica",
  'magazzino.origine-automazione': "Automatico (vendite, ordini, consumi)",
  'magazzino.origine-inventario': "Inventario",
  'magazzino.niente-movimenti': "Nessun movimento ancora.",
  'magazzino.nota-movimenti': "Ogni cambio di giacenza finisce qui da solo, da qualsiasi parte arrivi: schede, vendite, ordini arrivati, import, inventario.",
};
