// I moduli dell'interfaccia (web/moduli/*.js): Lumi, l'agenda e il cruscotto.
export default {
  'moduli.lumi-serve-chiave': "Per rispondere mi serve la chiave di Claude. Ti apro **Gestione → Lumi**: ci vuole un minuto.",
  'moduli.lumi-serve-chiave-spento': "Per rispondere mi serve la chiave di Claude e che tu mi riaccenda. Ti apro **Gestione → Lumi**: ci vuole un minuto.",
  'moduli.lumi-chiedi-titolare': "Per rispondere mi serve la chiave di Claude: chiedi al titolare di aggiungerla in **Gestione → Lumi**.",
  'moduli.lumi-spento': "Lumi è spento: si riaccende in Gestione → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi è quasi pronto: manca la chiave di Claude.",
  'moduli.lumi-apri': "Apri",
  'moduli.lumi-settimana': "Com'è la settimana",
  'moduli.lumi-settimana-domanda': "Com'è andata questa settimana? Dammi i numeri principali.",
  'moduli.lumi-accendi': "Accendi Lumi",
  'moduli.lumi-solo-titolare': "Le impostazioni di Lumi sono del titolare.",
  'moduli.lumi-gia-salvata': "•••••••• (già salvata)",
  'moduli.lumi-stato-spento': "Spento",
  'moduli.lumi-stato-acceso': "Acceso",
  'moduli.lumi-stato-manca': "Manca la chiave",
  'moduli.lumi-fonte-ambiente': "La chiave arriva dalla variabile ANTHROPIC_API_KEY del server.",
  'moduli.lumi-fonte-file': "Chiave salvata su questo computer.",
  'moduli.lumi-cos-e': "Lumi è l'assistente di Kubo. Gli parli o gli scrivi dalla pillola in alto: cerca, conta, prepara schede e cambia la forma del gestionale. Ogni modifica aspetta il tuo «Conferma», e ognuno vede solo quello che i suoi permessi gli lasciano vedere.",
  'moduli.lumi-chiave': "Chiave di Claude",
  'moduli.lumi-salva-chiave': "Salva la chiave",
  'moduli.lumi-incolla': "Incolla la chiave",
  'moduli.lumi-togliere': "Togliere la chiave? Lumi smette di rispondere.",
  'moduli.lumi-dove-chiave': "La crei su console.anthropic.com, alla voce API Keys. Resta su questo computer, in un file accanto ai dati che solo Kubo legge, e non arriva mai ai browser.",
  'moduli.lumi-acceso': "Lumi acceso",
  'moduli.lumi-limite': "Domande al minuto per persona",
  'moduli.lumi-da-provare': "Da provare",
  'moduli.lumi-esempio-1': "Quanto ho venduto questa settimana?",
  'moduli.lumi-esempio-2': "Cosa devo riordinare?",
  'moduli.lumi-esempio-3': "Aggiungi la taglia agli articoli con S, M, L e XL",
  'moduli.lumi-esempio-4': "Fammi una sezione per i noleggi con cliente, attrezzo, dal, al e stato",
  'moduli.lumi-esempio-5': "Quando un noleggio passa a restituito avvisami",
  'moduli.lumi-modello': "Modello: {modello}.",
  'moduli.lumi-voce-accesa': "Voce in tempo reale accesa.",
  'moduli.lumi-voce-browser': "Voce: quella del browser, dove c'è.",
};
