// I moduli dell'interfaccia (web/moduli/*.js): Lumi, l'agenda e il cruscotto.
export default {
  'moduli.lumi-serve-chiave': "Per rispondere mi serve la chiave di Claude. Ti apro **Gestione → Lumi**: ci vuole un minuto.",
  'moduli.lumi-serve-chiave-spento': "Per rispondere mi serve la chiave di Claude e che tu mi riaccenda. Ti apro **Gestione → Lumi**: ci vuole un minuto.",
  'moduli.lumi-chiedi-titolare': "Per rispondere mi serve la chiave di Claude: chiedi al titolare di aggiungerla in **Gestione → Lumi**.",
  'moduli.lumi-spento': "Lumi è spento: si riaccende in Gestione → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi è quasi pronto: manca la chiave di Claude.",
  'moduli.lumi-apri': "Apri",
  'moduli.lumi-settimana': "Com'è la settimana",
  'moduli.lumi-settimana-domanda': "Com'è andata questa settimana? Dammi i numeri principali.",
  'moduli.lumi-accendi': "Accendi Lumi",
  'moduli.lumi-solo-titolare': "Le impostazioni di Lumi sono del titolare.",
  'moduli.lumi-gia-salvata': "•••••••• (già salvata)",
  'moduli.lumi-stato-spento': "Spento",
  'moduli.lumi-stato-acceso': "Acceso",
  'moduli.lumi-stato-manca': "Manca la chiave",
  'moduli.lumi-fonte-ambiente': "La chiave arriva dalla variabile ANTHROPIC_API_KEY del server.",
  'moduli.lumi-fonte-file': "Chiave salvata su questo computer.",
  'moduli.lumi-cos-e': "Lumi è l'assistente di Kubo. Gli parli o gli scrivi dalla pillola in alto: cerca, conta, prepara schede e cambia la forma del gestionale. Ogni modifica aspetta il tuo «Conferma», e ognuno vede solo quello che i suoi permessi gli lasciano vedere.",
  'moduli.lumi-chiave': "Chiave di Claude",
  'moduli.lumi-salva-chiave': "Salva la chiave",
  'moduli.lumi-incolla': "Incolla la chiave",
  'moduli.lumi-togliere': "Togliere la chiave? Lumi smette di rispondere.",
  'moduli.lumi-dove-chiave': "La crei su console.anthropic.com, alla voce API Keys. Resta su questo computer, in un file accanto ai dati che solo Kubo legge, e non arriva mai ai browser.",
  'moduli.lumi-acceso': "Lumi acceso",
  'moduli.lumi-limite': "Domande al minuto per persona",
  'moduli.lumi-da-provare': "Da provare",
  'moduli.lumi-esempio-1': "Quanto ho venduto questa settimana?",
  'moduli.lumi-esempio-2': "Cosa devo riordinare?",
  'moduli.lumi-esempio-3': "Aggiungi la taglia agli articoli con S, M, L e XL",
  'moduli.lumi-esempio-4': "Fammi una sezione per i noleggi con cliente, attrezzo, dal, al e stato",
  'moduli.lumi-esempio-5': "Quando un noleggio passa a restituito avvisami",
  'moduli.lumi-modello': "Modello: {modello}.",
  'moduli.lumi-voce-accesa': "Voce in tempo reale accesa.",
  'moduli.lumi-voce-browser': "Voce: quella del browser, dove c'è.",
  'moduli.ag-adesso': "adesso",
  'moduli.ag-agenda': "Agenda",
  'moduli.ag-calendario': "Calendario",
  'moduli.ag-cruscotto': "Cruscotto",
  'moduli.ag-aggiungi-voce': "Aggiungi la voce",
  'moduli.ag-altri': {"one": "+{n} altro", "other": "+{n} altri"},
  'moduli.ag-e-altri': {"one": "e un altro", "other": "e altri {n}"},
  'moduli.ag-aria-grafico': "{titolo}: grafico",
  'moduli.ag-barre': "Barre",
  'moduli.ag-linea': "Linea",
  'moduli.ag-buongiorno': "Buongiorno",
  'moduli.ag-buon-pomeriggio': "Buon pomeriggio",
  'moduli.ag-buonasera': "Buonasera",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Cambia",
  'moduli.ag-cambia-widget': "Cambia il widget",
  'moduli.ag-nuovo-widget': "Nuovo widget",
  'moduli.ag-campo': "Campo",
  'moduli.ag-colonne-per': "Colonne: {nome}",
  'moduli.ag-una-colonna': "Una colonna",
  'moduli.ag-come-oggi': "come ieri",
  'moduli.ag-come-settimana': "come la settimana scorsa",
  'moduli.ag-come-mese': "come il mese scorso",
  'moduli.ag-come-anno': "come l'anno scorso",
  'moduli.ag-rispetto-oggi': "{diff} rispetto a ieri ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} rispetto alla settimana scorsa ({prima})",
  'moduli.ag-rispetto-mese': "{diff} rispetto al mese scorso ({prima})",
  'moduli.ag-rispetto-anno': "{diff} rispetto all'anno scorso ({prima})",
  'moduli.ag-data-rif': "Data di riferimento",
  'moduli.ag-prima': "Prima",
  'moduli.ag-dopo': "Dopo",
  'moduli.ag-fatto': "Fatto",
  'moduli.ag-forma': "Forma",
  'moduli.ag-ha-creato': "ha creato",
  'moduli.ag-ha-modificato': "ha modificato",
  'moduli.ag-ha-archiviato': "ha archiviato",
  'moduli.ag-ha-ripristinato': "ha ripristinato",
  'moduli.ag-in-sezione': "in {nome}",
  'moduli.ag-un-elemento': "un elemento",
  'moduli.ag-lista': "Lista",
  'moduli.ag-torna-lista': "Torna alla lista",
  'moduli.ag-media': "Media di…",
  'moduli.ag-somma': "Somma di…",
  'moduli.ag-quanti': "Quanti sono",
  'moduli.ag-misura': "Misura",
  'moduli.ag-modifica': "Modifica",
  'moduli.ag-nome-voce': "Nome della voce",
  'moduli.ag-nuova-voce': "Nuova voce",
  'moduli.ag-un-filtro': "Metti almeno un filtro alla voce",
  'moduli.ag-non-disegno': "Non riesco a disegnarlo",
  'moduli.ag-oggi': "Oggi",
  'moduli.ag-per': "Per",
  'moduli.ag-periodo': "Periodo",
  'moduli.ag-periodo-oggi': "Oggi",
  'moduli.ag-periodo-settimana': "Questa settimana",
  'moduli.ag-periodo-mese': "Questo mese",
  'moduli.ag-periodo-anno': "Quest'anno",
  'moduli.ag-periodo-ultimi_7': "Ultimi 7 giorni",
  'moduli.ag-periodo-ultimi_30': "Ultimi 30 giorni",
  'moduli.ag-periodo-ultimi_84': "Ultime 12 settimane",
  'moduli.ag-periodo-ultimi_365': "Ultimo anno",
  'moduli.ag-periodo-sempre': "Sempre",
  'moduli.ag-piede-grafico': "{periodo} · in tutto {totale}",
  'moduli.ag-piu-aggiungi': "+ Aggiungi",
  'moduli.ag-quale-data': "Quale data",
  'moduli.ag-senza-titolo': "Senza titolo",
  'moduli.ag-spostato': "Spostato",
  'moduli.ag-tipo': "Tipo",
  'moduli.ag-titolo': "Titolo",
  'moduli.ag-titolo-widget': "Dai un titolo al widget",
  'moduli.ag-tutti': "tutti",
  'moduli.ag-utente-non-attivo': "Utente non attivo",
  'moduli.ag-vedi-calendario': "Vedi sul calendario",
  'moduli.ag-vedi-elenco': "Vedi l'elenco",
  'moduli.ag-vedi-giorno': "Vedi il giorno",
  'moduli.ag-vista-giorno': "Giorno",
  'moduli.ag-vista-settimana': "Settimana",
  'moduli.ag-vista-mese': "Mese",
  'moduli.ag-w-numero': "Numero",
  'moduli.ag-w-grafico': "Grafico",
  'moduli.ag-w-attenzione': "Cosa richiede attenzione",
  'moduli.ag-w-ultime': "Ultime modifiche",
};
