// Area «sicurezza» (web/moduli/sicurezza.js): password, dispositivi collegati, impostazioni dell'azienda, poteri dei ruoli.
export default {
  'sicurezza.titolo': 'Sicurezza',
  'sicurezza.la-tua-password': 'La tua password',
  'sicurezza.dispositivi-collegati': 'Dispositivi collegati',
  'sicurezza.dispositivo': '{browser} su {sistema}',
  'sicurezza.dispositivo-sconosciuto': 'Dispositivo sconosciuto',
  'sicurezza.app-lumi': 'App Lumi',
  'sicurezza.iphone-ipad': 'iPhone o iPad',
  'sicurezza.password-diverse': 'Le due password nuove non sono uguali',
  'sicurezza.password-cambiata': 'Password cambiata. Gli altri dispositivi sono stati scollegati.',
  'sicurezza.password-attuale': 'Password attuale',
  'sicurezza.password-nuova': 'Nuova password',
  'sicurezza.password-regole': 'Almeno 8 caratteri; sotto i 12 mescola lettere con cifre o simboli.',
  'sicurezza.password-ripeti': 'Ripeti la nuova password',
  'sicurezza.cambia-password': 'Cambia password',
  'sicurezza.col-dispositivo': 'Dispositivo',
  'sicurezza.col-ultimo-uso': 'Ultimo uso',
  'sicurezza.col-indirizzo': 'Indirizzo',
  'sicurezza.questo': 'questo',
  'sicurezza.scollega': 'Scollega',
  'sicurezza.scollegati': { one: 'Scollegato {n} dispositivo', other: 'Scollegati {n} dispositivi' },
  'sicurezza.scollega-altri': 'Scollega tutti gli altri',
  'sicurezza.impostazioni': "Impostazioni dell'azienda",
  'sicurezza.inattivita': 'Chiudi le sessioni ferme da (minuti)',
  'sicurezza.allegati': 'Allegati: al massimo (MB)',
  'sicurezza.fuso': 'Fuso orario',
  'sicurezza.lumi-budget': 'Lumi: token al mese (0 = senza limite)',
  'sicurezza.lumi-usati': 'Usati questo mese: {usati}',
  'sicurezza.webhook-interni': 'Permetti i webhook verso la rete interna (127.0.0.1, 192.168…). Lascialo spento se non sai a cosa serve.',
  'sicurezza.salvate': 'Impostazioni salvate',
  'sicurezza.salva': 'Salva',
  'sicurezza.ruoli': 'Poteri dei ruoli',
  'sicurezza.ruoli-nota': "Esportare la fattura elettronica consuma un numero d'invio; Lumi usa i token dell'azienda.",
  'sicurezza.col-ruolo': 'Ruolo',
  'sicurezza.potere-fatturapa': 'Esporta FatturaPA',
  'sicurezza.potere-lumi': 'Usa Lumi',
  'sicurezza.potere-aria': '{potere} per {ruolo}',
  'sicurezza.salvato': 'Salvato',
  'sicurezza.persone': 'Persone',
  'sicurezza.col-nome': 'Nome',
  'sicurezza.obbliga-cambio': 'Obbliga a cambiare password',
  'sicurezza.obbligo-fatto': '{nome} cambierà la password al prossimo accesso',
  'sicurezza.scollega-ovunque': 'Scollega ovunque',
  'sicurezza.scollegato-ovunque': 'Sessioni di {nome} chiuse su tutti i dispositivi',
  'sicurezza.nessun-altro': "Nessun'altra persona.",
  'sicurezza.scegli-password': 'Scegli la tua password',
  'sicurezza.provvisoria': 'La password che ti hanno dato era provvisoria. Scegline una tua per continuare.',
};
