// La tesoreria (web/moduli/tesoreria.js): scadenzario, banca e riconciliazione, previsione di cassa, solleciti, distinte.
export default {
  'tesoreria.titolo': "Tesoreria",
  'tesoreria.scheda-scadenze': "Scadenzario",
  'tesoreria.scheda-banca': "Banca",
  'tesoreria.scheda-cassa': "Previsione di cassa",
  'tesoreria.scheda-solleciti': "Solleciti",
  'tesoreria.scheda-distinte': "Distinte",
  'tesoreria.scheda-impostazioni': "Impostazioni",
  'tesoreria.manca-fatture': "Lo scadenzario nasce dalle fatture: aggiungi il modello «Fatture e fattura elettronica» da Personalizza.",
  'tesoreria.da-incassare': "Da incassare",
  'tesoreria.da-pagare': "Da pagare",
  'tesoreria.di-cui-scaduto': "di cui scaduto {importo}",
  'tesoreria.saldo-netto': "Differenza",
  'tesoreria.verso-attiva': "Incassi dai clienti",
  'tesoreria.verso-passiva': "Pagamenti ai fornitori",
  'tesoreria.solo-scadute': "Solo scadute",
  'tesoreria.cerca': "Cerca cliente o documento",
  'tesoreria.scadenza': "Scadenza",
  'tesoreria.documento': "Documento",
  'tesoreria.cliente': "Cliente",
  'tesoreria.fornitore': "Fornitore",
  'tesoreria.importo': "Importo",
  'tesoreria.residuo': "Residuo",
  'tesoreria.stato': "Stato",
  'tesoreria.pagata': "Pagata",
  'tesoreria.in-distinta': "In distinta",
  'tesoreria.scaduta-da': { one: "Scaduta da {n} giorno", other: "Scaduta da {n} giorni" },
  'tesoreria.parziale': "Acconto",
  'tesoreria.aperta': "Aperta",
  'tesoreria.incassata': "Incassata",
  'tesoreria.pagata-btn': "Pagata",
  'tesoreria.acconto': "Acconto",
  'tesoreria.niente-scadenze': "Nessuna scadenza aperta.",
  'tesoreria.scegli-nota': "Spunta le scadenze per segnarle pagate o preparare il file per la banca.",
  'tesoreria.scelte': { one: "{n} scelta · {importo}", other: "{n} scelte · {importo}" },
  'tesoreria.segna-incassate': "Segna incassate",
  'tesoreria.segna-pagate': "Segna pagate",
  'tesoreria.distinta-riba': "Distinta Ri.Ba.",
  'tesoreria.distinta-sdd': "Addebito SDD",
  'tesoreria.distinta-sct': "Bonifici SEPA",
  'tesoreria.data-pagamento': "Data del pagamento (AAAA-MM-GG)",
  'tesoreria.data-esecuzione': "Data di esecuzione in banca (AAAA-MM-GG)",
  'tesoreria.data-accredito': "Data dell'accredito o del pagamento (AAAA-MM-GG)",
  'tesoreria.importo-acconto': "Importo incassato o pagato",
  'tesoreria.importo-non-valido': "Importo non valido",
  'tesoreria.incassi-registrati': { one: "Incasso registrato", other: "{n} incassi registrati" },
  'tesoreria.pagamenti-registrati': { one: "Pagamento registrato", other: "{n} pagamenti registrati" },
  'tesoreria.distinta-creata': "{nome} pronta: {importo}. Carica il file sull'home banking.",
  'tesoreria.nota-termini': "Le scadenze vengono dalle rate delle fatture, dalla data di scadenza o dai termini di pagamento del cliente o del fornitore (per esempio 30/60/90 DFFM).",
  'tesoreria.err-sia': "Manca il codice SIA dell'azienda (te lo dà la banca): scrivilo nelle impostazioni della tesoreria.",
  'tesoreria.err-iban-azienda': "Manca l'IBAN dell'azienda, o è sbagliato: Documenti → dati dell'azienda.",
  'tesoreria.err-banca-debitore': "{nome}: manca l'IBAN della banca d'appoggio nella scheda del cliente.",
  'tesoreria.err-cf-debitore': "{nome}: manca la partita IVA o il codice fiscale.",
  'tesoreria.err-importo': "{nome}: importo da incassare non valido.",
  'tesoreria.err-id-creditore': "Manca l'identificativo del creditore SEPA (lo rilascia la banca): impostazioni della tesoreria.",
  'tesoreria.err-iban-debitore': "{nome}: IBAN del cliente mancante o sbagliato.",
  'tesoreria.err-mandato': "{nome}: mancano codice e data del mandato SDD nella scheda del cliente.",
  'tesoreria.err-iban-beneficiario': "{nome}: IBAN del fornitore mancante o sbagliato.",
  'tesoreria.banca-titolo': "Estratto conto e riconciliazione",
  'tesoreria.manca-movimenti': "Per importare l'estratto conto serve la sezione «Movimenti di banca».",
  'tesoreria.prepara': "Prepara la tesoreria",
  'tesoreria.preparata': { one: "Aggiunta {n} cosa", other: "Aggiunte {n} cose" },
  'tesoreria.chiedi-titolare': "Chiedi a chi può personalizzare il gestionale.",
  'tesoreria.file-grande': "{nome} è troppo grande",
  'tesoreria.importati': "Importati {n} movimenti, {doppi} già presenti",
  'tesoreria.saldo-aggiornato': "Saldo della previsione aggiornato: {importo} al {data}",
  'tesoreria.carica-estratto': "Trascina qui l'estratto conto, o fai clic",
  'tesoreria.formati': "CAMT.053 (XML), CBI, CSV o Excel della banca",
  'tesoreria.abbinato': "Abbinato: scadenze segnate pagate",
  'tesoreria.abbinato-differenza': "Abbinato; avanzano {importo}",
  'tesoreria.abbina-a': "Abbina a…",
  'tesoreria.abbina': "Abbina",
  'tesoreria.ignora': "Ignora",
  'tesoreria.ignora-nota': "Spese, giroconti, stipendi: movimenti che non chiudono una fattura",
  'tesoreria.nessuna-proposta': "Nessuna proposta: scegli a mano qui sotto.",
  'tesoreria.da-abbinare': { one: "{n} movimento da abbinare", other: "{n} movimenti da abbinare" },
  'tesoreria.tutto-abbinato': "Tutto abbinato.",
  'tesoreria.abbinati-recenti': "Abbinati di recente",
  'tesoreria.data': "Data",
  'tesoreria.descrizione': "Descrizione",
  'tesoreria.mov-abbinato': "Abbinato",
  'tesoreria.mov-ignorato': "Ignorato",
  'tesoreria.mov-da_abbinare': "Da abbinare",
  'tesoreria.annulla': "Annulla",
  'tesoreria.nota-movimenti': "I movimenti stanno nella sezione «{sezione}»: la riempiono anche i collegamenti con la banca (open banking).",
  'tesoreria.perche-importo': "importo uguale",
  'tesoreria.perche-importo-vicino': "importo simile",
  'tesoreria.perche-acconto': "acconto",
  'tesoreria.perche-numero': "numero della fattura",
  'tesoreria.perche-iban': "stesso IBAN",
  'tesoreria.perche-nome': "nome",
  'tesoreria.perche-data': "data vicina",
  'tesoreria.perche-somma': "più fatture insieme",
  'tesoreria.perche-distinta': "accredito della distinta",
  'tesoreria.grafico': "Entrate, uscite e saldo previsto",
  'tesoreria.passo-settimana': "Settimane",
  'tesoreria.passo-mese': "Mesi",
  'tesoreria.senza-saldo': "Manca il saldo di partenza: scrivilo nelle impostazioni, o importa un estratto conto CAMT.053.",
  'tesoreria.apri-impostazioni': "Apri le impostazioni",
  'tesoreria.scoperto': "Attenzione: la cassa va sotto zero, fino a {importo} il {data}.",
  'tesoreria.saldo-oggi': "Saldo oggi",
  'tesoreria.saldo-dal': "dal saldo del {data} più i movimenti",
  'tesoreria.saldo-fine': "Saldo previsto",
  'tesoreria.punto-basso': "Punto più basso",
  'tesoreria.entrate': "Entrate",
  'tesoreria.uscite': "Uscite",
  'tesoreria.saldo': "Saldo",
  'tesoreria.periodi': "Per periodo",
  'tesoreria.periodo': "Periodo",
  'tesoreria.voci': "Da dove vengono i numeri",
  'tesoreria.tipo': "Tipo",
  'tesoreria.voce-incasso': "Incasso",
  'tesoreria.voce-pagamento': "Pagamento",
  'tesoreria.voce-previsione': "Previsione",
  'tesoreria.voce-contratto': "Contratto ricorrente",
  'tesoreria.voce-tasse': "Tasse",
  'tesoreria.ritardo-medio': { one: "il cliente paga in media {n} giorno dopo", other: "il cliente paga in media {n} giorni dopo" },
  'tesoreria.niente-voci': "Niente in vista nel periodo.",
  'tesoreria.aggiungi-previsione': "Aggiungi affitto, stipendi, mutui e altre previsioni",
  'tesoreria.sollecito-segnato': "Sollecito segnato",
  'tesoreria.livello-1': "Promemoria cortese",
  'tesoreria.livello-2': "Sollecito",
  'tesoreria.livello-3': "Diffida",
  'tesoreria.appena-sollecitato': "Sollecitato da poco",
  'tesoreria.ritardo-giorni': { one: "{n} giorno di ritardo", other: "{n} giorni di ritardo" },
  'tesoreria.ultimo-sollecito': "Ultimo sollecito il {data} (livello {livello})",
  'tesoreria.lettera': "Testo del sollecito",
  'tesoreria.copia': "Copia il testo",
  'tesoreria.copiato': "Copiato",
  'tesoreria.copia-no': "Non riesco a copiare: seleziona il testo a mano",
  'tesoreria.oggetto-sollecito': "Promemoria di pagamento",
  'tesoreria.scrivi-email': "Scrivi l'email",
  'tesoreria.segna-mandato': "Segna come mandato",
  'tesoreria.niente-solleciti': "Nessun cliente in ritardo.",
  'tesoreria.distinta-chiusa': "Distinta chiusa: scadenze segnate pagate",
  'tesoreria.distinta': "Distinta",
  'tesoreria.creata': "Creata",
  'tesoreria.quante': "Scadenze",
  'tesoreria.pagata-il': "Pagata il {data}",
  'tesoreria.accreditata-il': "Accreditata il {data}",
  'tesoreria.in-attesa': "In attesa",
  'tesoreria.scarica': "Scarica",
  'tesoreria.segna-pagati': "Segna pagati",
  'tesoreria.segna-accreditata': "Segna accreditata",
  'tesoreria.niente-distinte': "Ancora nessuna distinta: si preparano dallo scadenzario.",
  'tesoreria.nota-distinte': "Il file si carica sull'home banking (Ri.Ba. in formato CBI, SDD e bonifici in formato SEPA XML). Quando la banca accredita la distinta, la riconciliazione la propone da sola.",
  'tesoreria.salvate': "Impostazioni salvate",
  'tesoreria.sia': "Codice SIA",
  'tesoreria.bic': "BIC della tua banca (facoltativo)",
  'tesoreria.id-creditore': "Identificativo creditore SEPA (per gli SDD)",
  'tesoreria.saldo-banca': "Saldo del conto",
  'tesoreria.saldo-data': "Saldo al giorno",
  'tesoreria.sequenza-sdd': "Tipo di addebito SDD",
  'tesoreria.seq-rcur': "Ricorrente (RCUR)",
  'tesoreria.seq-frst': "Primo di una serie (FRST)",
  'tesoreria.seq-ooff': "Una tantum (OOFF)",
  'tesoreria.sezione-movimenti': "Sezione dei movimenti di banca",
  'tesoreria.ritardo-clienti': "Nella previsione sposta gli incassi del ritardo medio di ogni cliente",
  'tesoreria.salva': "Salva",
  'tesoreria.banca-azienda': "Il conto dell'azienda",
  'tesoreria.iban-azienda': "IBAN usato per Ri.Ba., SDD e bonifici: {iban}",
  'tesoreria.manca-iban': "Manca l'IBAN dell'azienda.",
  'tesoreria.dati-azienda': "Dati dell'azienda",
  'tesoreria.nota-sia': "Il codice SIA e l'identificativo del creditore li dà la banca quando attivi Ri.Ba. e SDD. L'identificativo proposto è calcolato dalla partita IVA: controllalo con la banca.",
  'tesoreria.sezioni': "Sezioni",
  'tesoreria.sezioni-mancano': "Mancano «Movimenti di banca» o «Previsioni di cassa», e i campi di pagamento di clienti e fornitori (termini, IBAN, mandato SDD).",
  'tesoreria.sezioni-ci-sono': "Ci sono tutte.",
  'tesoreria.termini': "Termini di pagamento",
  'tesoreria.termini-nota': "Si scrivono nella scheda del cliente o del fornitore. DF = data fattura, FM = fine mese, +10 = il 10 del mese dopo. 30, 60, 90 giorni contano come mesi.",
};
