// Lista, scheda, editor dei campi e filtri (web/viste.js, web/campi.js, web/filtri.js).
export default {
  'viste.cerca-in': 'Cerca in {nome}…',
  'viste.nuovo': '+ Nuovo',
  'viste.tabella': 'Tabella',
  'viste.kanban': 'Kanban',
  'viste.archiviati': 'Archiviati',
  'viste.viste-salvate': 'Viste salvate',
  'viste.colonne': 'Colonne',
  'viste.raggruppa': 'Raggruppa',
  'viste.senza-gruppi': 'Senza gruppi',
  'viste.gruppi-per': 'Gruppi: {nome}',
  'viste.salva-vista': 'Salva vista',
  'viste.tutti': 'Tutti',
  'viste.per-tutti': 'Per tutti',
  'viste.mie': 'Mie',
  'viste.filtri-tolti': 'Alcuni filtri di questa vista usano campi che non vedi: li ho tolti',
  'viste.salva-modifiche': 'Salva le modifiche…',
  'viste.esempio-vista': 'Es. Da consegnare questa settimana',
  'viste.nome-vista': 'Dai un nome alla vista',
  'viste.salvata-tutti': 'Vista salvata per tutti',
  'viste.salvata-te': 'Vista salvata per te',
  'viste.vista-nome': 'Vista «{nome}»',
  'viste.salva-questa': 'Salva questa vista',
  'viste.cosa-salva': 'Filtri, colonne, gruppi e ordine di adesso.',
  'viste.la-vedono-tutti': 'La vedono tutti',
  'viste.solo-tu': 'La vedrai solo tu.',
  'viste.elimina': 'Elimina',
  'viste.elimina-vista': 'Eliminare la vista «{nome}»?',
  'viste.vista-eliminata': 'Vista eliminata',
  'viste.salva-nuova': 'Salva come nuova',
  'viste.aggiorna': 'Aggiorna',
  'viste.salva': 'Salva',
  'viste.come-inizio': 'Come all\'inizio',
  'viste.nessuno': 'Nessuno',
  'viste.nessun-risultato': 'Nessun risultato.',
  'viste.niente-archivio': 'Niente in archivio.',
  'viste.ancora-nessuno': 'Ancora nessun elemento in {nome}.',
  'viste.crea-primo': '+ Crea il primo',
  'viste.totale': 'Totale ({n})',
  'viste.prime-di': 'Mostro le prime {k} di {n} (i totali contano tutte)',
  'viste.in-tutto': { one: '{n} in tutto', other: '{n} in tutto' },
  'viste.crea': 'Crea',
  'viste.creato': 'Creato',
  'viste.salvato': 'Salvato',
  'viste.nuovo-in': 'Nuovo in {nome}',
  'viste.archivia': 'Archivia',
  'viste.archiviare': 'Archiviare? Si può ripristinare dall\'archivio.',
  'viste.archiviato': 'Archiviato',
  'viste.ripristina': 'Ripristina',
  'viste.ripristinato': 'Ripristinato',
  'viste.storia': 'Storia',
  'viste.archiviato-min': 'archiviato',
  'viste.automazione': 'automazione',
  'viste.storia-creato': 'creato',
  'viste.storia-ripristinato': 'ripristinato',
  'viste.non-si-passa': 'Da «{da}» non si passa qui',
  'viste.al-salvataggio': 'al salvataggio',
  'viste.piu-immagine': '+ Immagine',
  'viste.piu-file': '+ File',
  'viste.non-immagine': '«{nome}» non è un\'immagine',
  'viste.o-trascina': 'o trascina qui',
  'viste.righe-non-trovata': 'Entità delle righe non trovata',
  'viste.aggiungi-riga': '+ Aggiungi riga',
  'viste.creato-il': 'Creato il',
  'viste.modificato-il': 'Modificato il',
  'viste.periodo-oggi': 'oggi',
  'viste.periodo-ieri': 'ieri',
  'viste.periodo-settimana': 'questa settimana',
  'viste.periodo-mese': 'questo mese',
  'viste.periodo-ultimi_7': 'ultimi 7 giorni',
  'viste.periodo-ultimi_30': 'ultimi 30 giorni',
  'viste.periodo-anno': 'quest\'anno',
  'viste.op-uguale': 'è',
  'viste.op-diverso': 'non è',
  'viste.op-tra': 'fra',
  'viste.op-contiene': 'contiene',
  'viste.op-inizia': 'inizia con',
  'viste.op-vuoto': 'è vuoto',
  'viste.op-nonvuoto': 'non è vuoto',
  'viste.op-in': 'è uno di',
  'viste.op-prima': 'prima del',
  'viste.op-dopo': 'dal',
  'viste.op-vero': 'è vero',
  'viste.op-falso': 'è falso',
  'viste.o': ' o ',
  'viste.tra-e': '{a} e {b}',
  'viste.io': 'io',
  'viste.me': 'me',
  'viste.io-maiuscolo': 'Io',
  'viste.piu-filtro': '+ Filtro',
  'viste.cambia-filtro': 'Cambia il filtro',
  'viste.togli-tutti': 'Togli tutti',
  'viste.scegli-campo': 'Scegli il campo…',
  'viste.nel-periodo': 'nel periodo',
  'viste.testo': 'testo',
  'viste.scegli-un-campo': 'Scegli un campo',
  'viste.manca-valore': 'Manca il valore',
  'viste.nuovo-filtro': 'Nuovo filtro',
  'viste.applica': 'Applica',
};
