// Il modulo WhatsApp dell'interfaccia (web/moduli/whatsapp.js): conversazioni, modelli, automazioni, impostazioni.
export default {
  'whatsapp.forse-stop': 'Sembra una richiesta di non ricevere più messaggi',
  'whatsapp.segna-stop': 'Segna STOP',
  'whatsapp.s-approvato': "Approvato",
  'whatsapp.s-in_attesa': "In attesa",
  'whatsapp.s-rifiutato': "Rifiutato",
  'whatsapp.s-in_pausa': "In pausa",
  'whatsapp.s-disattivato': "Disattivato",
  'whatsapp.s-inviato': "Inviato",
  'whatsapp.s-consegnato': "Consegnato",
  'whatsapp.s-letto': "Letto",
  'whatsapp.s-fallito': "Fallito",
  'whatsapp.s-bloccato': "Fermato",
  'whatsapp.s-coda': "In coda",
  'whatsapp.s-ricevuto': "Ricevuto",
  'whatsapp.finestra-aperta': "Finestra aperta fino alle {ora}",
  'whatsapp.finestra-chiusa': "Finestra chiusa: serve un modello",
  'whatsapp.attivo': "Attivo: {nome}",
  'whatsapp.nessuno': "Nessun servizio WhatsApp acceso.",
  'whatsapp.vai-connettori': "Collegalo dai connettori",
  'whatsapp.conversazioni': "Conversazioni",
  'whatsapp.modelli': "Modelli",
  'whatsapp.automazioni': "Automazioni WhatsApp",
  'whatsapp.impostazioni': "Impostazioni",
  'whatsapp.vuoto': "Ancora nessun messaggio.",
  'whatsapp.scegli': "Scegli una conversazione.",
  'whatsapp.c-servizio': "Servizio",
  'whatsapp.c-marketing': "Promozioni",
  'whatsapp.si-no-si': "sì",
  'whatsapp.si-no-no': "no",
  'whatsapp.fonte-chiedi': "Come hai raccolto la scelta? (es. modulo in negozio, sito, a voce)",
  'whatsapp.testo-chiedi': "Le parole esatte che il cliente ha accettato:",
  'whatsapp.testo-predefinito': "Acconsento a ricevere messaggi su WhatsApp da questa attività. Posso scrivere STOP in qualsiasi momento.",
  'whatsapp.ok-servizio': "Consenso servizio",
  'whatsapp.ok-marketing': "Consenso promozioni",
  'whatsapp.revoca': "Revoca",
  'whatsapp.sconosciuto': "Numero non in rubrica.",
  'whatsapp.crea-cliente': "Crea cliente",
  'whatsapp.crea-lead': "Crea contatto da qualificare",
  'whatsapp.scrivi': "Scrivi una risposta…",
  'whatsapp.serve-modello': "Fuori dalla finestra di 24 ore: scegli un modello approvato",
  'whatsapp.testo-libero': "Testo libero",
  'whatsapp.scegli-modello': "Scegli un modello",
  'whatsapp.k-servizio': "Servizio",
  'whatsapp.k-utility': "Utilità",
  'whatsapp.k-marketing': "Marketing",
  'whatsapp.k-authentication': "Autenticazione",
  'whatsapp.costo': "Costo stimato",
  'whatsapp.inviato': "Messaggio inviato",
  'whatsapp.invia': "Invia",
  'whatsapp.anteprima': "Anteprima",
  'whatsapp.sincronizzati': "Modelli aggiornati",
  'whatsapp.sincronizza': "Sincronizza i modelli",
  'whatsapp.salvato': "Salvato",
  'whatsapp.modelli-nota': "Ogni variabile {{n}} prende il valore da un campo: per esempio cliente.nome o riga.quando.",
  'whatsapp.nessun-modello': "Nessun modello: sincronizzali o creane uno.",
  'whatsapp.corpo-esempio': "Ciao {{1}}, il tuo ordine è pronto.",
  'whatsapp.esempi-esempio': "Mario; martedì alle 15",
  'whatsapp.nuovo-modello': "Nuovo modello",
  'whatsapp.nuovo-nota': "Meta lo controlla prima di approvarlo, di solito in pochi minuti. Per ogni variabile serve un esempio. I modelli con un PDF nell'intestazione si creano in WhatsApp Manager.",
  'whatsapp.nome': "Nome (minuscole, numeri, _)",
  'whatsapp.categoria': "Categoria",
  'whatsapp.lingua': "Lingua",
  'whatsapp.testo': "Testo",
  'whatsapp.esempi': "Esempi delle variabili, separati da ;",
  'whatsapp.mandato-a-meta': "Modello mandato in approvazione",
  'whatsapp.manda-approvazione': "Manda in approvazione",
  'whatsapp.automazioni-nota': "Accendi quelle che ti servono, scegli il modello e i tempi. Prima di ogni invio Kubo controlla consenso, STOP, ore di silenzio e limiti.",
  'whatsapp.o-ore': "Ore prima (es. 24, 2)",
  'whatsapp.o-giorni': "Dopo quanti giorni",
  'whatsapp.o-mesi': "Inattivo da mesi",
  'whatsapp.o-link': "Link per la recensione",
  'whatsapp.o-testo': "Testo della risposta",
  'whatsapp.esempio-da-approvare': "Esempio di modello: crealo e fallo approvare, poi sceglilo qui.",
  'whatsapp.mancano': "Variabili senza valore: {n}",
  'whatsapp.salva': "Salva",
  'whatsapp.r-promemoria': "Promemoria appuntamento",
  'whatsapp.r-conferma': "Conferma prenotazione",
  'whatsapp.r-pronto': "Ordine pronto o spedito",
  'whatsapp.r-documento': "Fattura o preventivo con PDF",
  'whatsapp.r-sollecito': "Sollecito di pagamento",
  'whatsapp.r-recensione': "Richiesta di recensione",
  'whatsapp.r-compleanno': "Auguri di compleanno",
  'whatsapp.r-riattivazione': "Cliente da riattivare",
  'whatsapp.r-fuori_orario': "Risposta fuori orario",
  'whatsapp.rd-promemoria': "Un messaggio prima dell'appuntamento (24 e 2 ore prima, o come vuoi).",
  'whatsapp.rd-conferma': "Appena nasce una prenotazione.",
  'whatsapp.rd-pronto': "Quando lo stato passa a pronto o spedito, con il numero di spedizione se c'è.",
  'whatsapp.rd-documento': "Quando la fattura è emessa o il preventivo inviato: il PDF va con un modello che ha il documento nell'intestazione.",
  'whatsapp.rd-sollecito': "Ogni mattina, per le fatture scadute da N giorni (una volta per fattura).",
  'whatsapp.rd-recensione': "N giorni dopo la vendita, con il link alla tua pagina delle recensioni.",
  'whatsapp.rd-compleanno': "La mattina del compleanno del cliente.",
  'whatsapp.rd-riattivazione': "A chi non torna da N mesi, una volta sola.",
  'whatsapp.rd-fuori_orario': "Quando un cliente scrive a negozio chiuso: testo libero, al massimo una volta ogni 12 ore.",
  'whatsapp.serve-marketing': "Promozionale: parte solo a chi ha dato il consenso alle promozioni, mai nelle ore di silenzio.",
  'whatsapp.non-possibile': "Il tuo gestionale non ha le sezioni o i campi che servono a questa automazione.",
  'whatsapp.modello': "Modello",
  'whatsapp.i-prefisso': "Prefisso predefinito",
  'whatsapp.i-silenzio-da': "Silenzio dalle",
  'whatsapp.i-silenzio-a': "alle",
  'whatsapp.i-silenzio-tutti': "Silenzio anche per i messaggi automatici di servizio",
  'whatsapp.i-limite-giorno': "Modelli al giorno, in tutto",
  'whatsapp.i-limite-cliente': "Modelli al giorno per cliente",
  'whatsapp.i-marketing-giorni': "Un promozionale ogni quanti giorni",
  'whatsapp.i-sconosciuti': "Chi scrive e non è in rubrica",
  'whatsapp.i-apre': "Apre alle",
  'whatsapp.i-chiude': "Chiude alle",
  'whatsapp.i-giorni': "Giorni aperti (0 = domenica)",
  'whatsapp.i-t-marketing': "Marketing, € a messaggio",
  'whatsapp.i-t-utility': "Utilità, € a messaggio",
  'whatsapp.i-t-authentication': "Autenticazione, € a messaggio",
  'whatsapp.i-t-servizio': "Servizio, € oltre la quota gratuita",
  'whatsapp.i-t-servizioGratisMese': "Messaggi di servizio gratis al mese (vuoto = tutti)",
  'whatsapp.i-t-twilio': "Sovrapprezzo Twilio, € a messaggio",
  'whatsapp.sc-chiedi': "Chiedimelo (resta un numero)",
  'whatsapp.sc-cliente': "Crea un cliente",
  'whatsapp.sc-lead': "Crea un contatto da qualificare",
  'whatsapp.webhook': "Indirizzo del webhook",
  'whatsapp.webhook-meta': "Incollalo in Meta (WhatsApp → Configurazione) con il token di verifica che trovi nella pagina del connettore, e iscriviti a messages e message_template_status_update. Deve essere raggiungibile da internet in https.",
  'whatsapp.webhook-360': "Kubo lo registra da solo su 360dialog quando c'è l'indirizzo pubblico nella pagina del connettore.",
  'whatsapp.webhook-twilio': "Incollalo nel mittente WhatsApp di Twilio come indirizzo dei messaggi in arrivo. L'indirizzo pubblico nella pagina del connettore deve essere lo stesso che vede Twilio.",
  'whatsapp.apri-connettore': "Apri il connettore",
  'whatsapp.costi-mese': "Questo mese",
  'whatsapp.nessun-costo': "Nessun messaggio a pagamento questo mese.",
  'whatsapp.costi-nota': "Stima con le tariffe di Meta per l'Italia ({data}): fa fede la fattura di Meta o del tuo fornitore.",
  'whatsapp.regole': "Regole di invio",
  'whatsapp.tariffe': "Tariffe",
  'whatsapp.tariffe-nota': "Meta aggiorna il listino ogni trimestre: correggi qui gli importi se cambiano.",
  'whatsapp.registro': "Messaggi fermati o falliti",
  'whatsapp.registro-vuoto': "Niente da segnalare.",
  'whatsapp.storia': "Storia WhatsApp",
  'whatsapp.senza-numero': "Il cliente non ha un numero di telefono.",
  'whatsapp.apri-chat': "Apri la conversazione",
};
