// Einkauf (web/moduli/acquisti.js): Nachbestellung, Bestellungen unterwegs, Wareneingang, Lieferantenrechnungen.
export default {
  'acquisti.titolo': "Einkauf",
  'acquisti.scheda-riordino': "Nachbestellen",
  'acquisti.scheda-arrivo': "Unterwegs",
  'acquisti.scheda-fatture': "Lieferantenrechnungen",
  'acquisti.stato-bozza': "Entwurf",
  'acquisti.stato-inviato': "Gesendet",
  'acquisti.stato-parziale': "Teilweise geliefert",
  'acquisti.stato-arrivato': "Geliefert",
  'acquisti.stato-annullato': "Storniert",
  'acquisti.serve-magazzino': "Der Einkauf braucht einen Bereich mit Lagerbestand (Artikel, Ersatzteile, Material…).",
  'acquisti.non-pronti': "Der Einkauf ist noch nicht eingerichtet.",
  'acquisti.chiedi-titolare': "Frag jemanden, der das System anpassen darf.",
  'acquisti.magazzino': "Lagerbereich",
  'acquisti.prepara-titolo': "Einkauf einrichten",
  'acquisti.prepara-nota': "Kubo nutzt die vorhandenen „Lieferantenbestellungen“ oder legt sie an und ergänzt die gelieferte Menge, den Status „teilweise geliefert“, den Lieferschein und die Lieferantenrechnung. Deine Daten bleiben unverändert.",
  'acquisti.prepara': "Einrichten",
  'acquisti.preparati': {"one": "{n} Element hinzugefügt", "other": "{n} Elemente hinzugefügt"},
  'acquisti.niente-riordino': "Nichts unter Mindestbestand: alles über der Schwelle oder schon bestellt.",
  'acquisti.fornitore': "Lieferant",
  'acquisti.scegli-fornitore': "Lieferant wählen…",
  'acquisti.da-ordinare': "Zu bestellen",
  'acquisti.senza-fornitore': "Ohne Lieferant",
  'acquisti.senza-fornitore-nota': "Diese Artikel haben keinen Lieferanten in ihrer Karte: Wähle ihn hier.",
  'acquisti.articolo': "Artikel",
  'acquisti.giacenza': "Bestand",
  'acquisti.soglia': "Mindestbestand",
  'acquisti.in-arrivo': "Unterwegs",
  'acquisti.costo': "Kosten",
  'acquisti.totale-stimato': "Geschätzte Summe: {importo}",
  'acquisti.niente-scelto': "Du hast nichts zum Bestellen gewählt",
  'acquisti.ordini-creati': {"one": "{n} Bestellung als Entwurf angelegt", "other": "{n} Bestellungen als Entwurf angelegt"},
  'acquisti.riordino-nota': "Unter Mindestbestand heißt: Bestand plus bereits Bestelltes liegt nicht über der Schwelle. Kubo schlägt vor, auf das Doppelte der Schwelle aufzufüllen: Passe die Mengen nach Belieben an.",
  'acquisti.crea-ordini': "Bestellungen anlegen",
  'acquisti.crea-nota': "Ein Entwurf pro Lieferant: prüfen und senden.",
  'acquisti.in-ritardo': "Verspätet: erwartet am {data}",
  'acquisti.previsto': "Erwartet am {data}",
  'acquisti.ricevi': "Ware annehmen",
  'acquisti.ricevute-di': "{ricevuta} von {quantita}",
  'acquisti.niente-arrivo': "Keine Bestellungen unterwegs.",
  'acquisti.ordine-chiuso': "Diese Bestellung ist schon abgeschlossen.",
  'acquisti.vedi-confronto': "Vergleich ansehen",
  'acquisti.ddt-segnaposto': "Nummer und Datum des Lieferscheins",
  'acquisti.ricevuto-tutto': "Ware angenommen: Bestellung vollständig",
  'acquisti.ricevuto-parte': "Ware angenommen: Die Bestellung bleibt für den Rest offen",
  'acquisti.ricevi-titolo': "Ware annehmen: {numero}, {fornitore}",
  'acquisti.ddt': "Lieferschein des Lieferanten",
  'acquisti.data': "Datum",
  'acquisti.ordinate': "Bestellt",
  'acquisti.gia-ricevute': "Schon geliefert",
  'acquisti.arrivate-ora': "Jetzt geliefert",
  'acquisti.ricevi-nota': "Gelieferte Mengen gehen sofort ins Lager, und die Artikelkosten werden zum gewichteten Durchschnitt. Was fehlt, bleibt unterwegs.",
  'acquisti.carica': "Einlagern",
  'acquisti.annulla': "Abbrechen",
  'acquisti.senza-fatture': "Zum Abgleich der Rechnungen braucht es die Vorlage „Rechnungen und E-Rechnung“.",
  'acquisti.ordine': "Bestellung",
  'acquisti.ricevuto': "Geliefert",
  'acquisti.fattura-proposta': "Vorgeschlagene Rechnung",
  'acquisti.candidata': "{numero}: {importo}",
  'acquisti.nessuna-fattura': "Keine Rechnung dieses Lieferanten",
  'acquisti.confronta': "Vergleichen",
  'acquisti.tutto-fatturato': "Jede Lieferung hat ihre Rechnung.",
  'acquisti.fatture-nota': "Kubo vergleicht den Wert der gelieferten Ware mit dem Nettobetrag der Lieferantenrechnungen. Es passt, wenn die Differenz höchstens 1 € oder 1 % beträgt.",
  'acquisti.abbinata': "Rechnung zugeordnet",
  'acquisti.tolta': "Rechnung entfernt",
  'acquisti.ordinato': "Bestellt",
  'acquisti.fatturato': "Berechnet",
  'acquisti.confronto-titolo': "{numero} · {fornitore}",
  'acquisti.torna': "Passt zur Rechnung {numero}.",
  'acquisti.non-torna': "Die Rechnung {numero} passt nicht: Differenz {importo}.",
  'acquisti.togli': "Entfernen",
  'acquisti.candidate': "Mögliche Rechnungen",
  'acquisti.fattura': "Rechnung",
  'acquisti.imponibile': "Nettobetrag",
  'acquisti.differenza': "Differenz",
  'acquisti.abbina': "Zuordnen",
  'acquisti.ricevimenti': "Wareneingänge",
  'acquisti.quantita': "Menge",
};
