// Area «avvio» (web/moduli/avvio.js) · Deutsch.
export default {
  'avvio.avanti': "Weiter",
  'avvio.indietro': "← Zurück",
  'avvio.azienda-es': "z. B. Werkstatt Ferri",
  'avvio.sottotitolo': "Zehn Fragen, und deine Unternehmenssoftware ist fertig, zugeschnitten auf deine Arbeit. Alles lässt sich später ändern.",
  'avvio.nome-attivita': "Wie heißt dein Betrieb?",
  'avvio.d-settore': "Was machst du beruflich?",
  'avvio.a-settore': "Wähl das, was am besten passt. Später lässt sich alles ändern.",
  'avvio.o-settore-negozio': "Laden und Geschäft",
  'avvio.sd-negozio': "Ich verkaufe an der Theke, mit Artikeln und Lager",
  'avvio.o-settore-ristorante': "Restaurant und Bar",
  'avvio.sd-ristorante': "Tische, Bestellungen, Speisekarte mit Allergenen, Reservierungen",
  'avvio.o-settore-laboratorio': "Handwerksbetrieb",
  'avvio.sd-laboratorio': "Angebote, Aufträge in Phasen, Material",
  'avvio.o-settore-officina': "Werkstatt und Service",
  'avvio.sd-officina': "Fahrzeuge oder Geräte, Einsätze, Ersatzteile, Garantien",
  'avvio.o-settore-studio': "Praxis und Dienstleistungen",
  'avvio.sd-studio': "Kalender, Kundenkarteien, Sitzungspakete",
  'avvio.o-settore-beauty': "Beauty und Kosmetik",
  'avvio.sd-beauty': "Kalender pro Kabine, Behandlungen, Pakete, Produkte",
  'avvio.o-settore-palestra': "Fitnessstudio und Verein",
  'avvio.sd-palestra': "Mitglieder, Abos und Verlängerungen, Kurse und Anwesenheit",
  'avvio.o-settore-professionista': "Freiberufler und Agentur",
  'avvio.sd-professionista': "Kunden, Projekte, Stunden, Fristen, Angebote",
  'avvio.o-settore-noleggio': "Vermietung",
  'avvio.sd-noleggio': "Mietobjekte, Verfügbarkeit, Verträge von/bis, Kautionen",
  'avvio.o-settore-altro': "Etwas anderes, bei null anfangen",
  'avvio.sd-altro': "Eine leere Software: Die Bereiche legst du selbst an",
  'avvio.d-offerta': "Verkaufst du Produkte, Dienstleistungen oder beides?",
  'avvio.o-offerta-prodotti': "Produkte",
  'avvio.o-offerta-servizi': "Dienstleistungen",
  'avvio.o-offerta-entrambi': "Beides",
  'avvio.d-magazzino': "Hast du ein Lager?",
  'avvio.a-magazzino': "Bestände, Mindestmengen, was nachbestellt werden muss.",
  'avvio.d-su_misura': "Arbeitest du auf Maß, mit Angeboten?",
  'avvio.a-su_misura': "Das Angebot mit seinen Positionen; nimmt der Kunde an, wird der Auftrag eröffnet.",
  'avvio.d-appuntamenti': "Vergibst du Termine oder nimmst du Reservierungen an?",
  'avvio.a-appuntamenti': "Ein Kalender pro Person oder pro Ressource.",
  'avvio.d-fornitori': "Kaufst du bei Lieferanten ein?",
  'avvio.a-fornitori': "Lieferantenverzeichnis und, wenn du ein Lager hast, Bestellungen mit Wareneingang.",
  'avvio.d-fatture': "Stellst du Rechnungen aus?",
  'avvio.a-fatture': "Pro Jahr nummeriert, mit MwSt., Fälligkeiten und der Datei der E-Rechnung.",
  'avvio.d-persone': "Wie viele Personen werden Kubo nutzen?",
  'avvio.o-persone-solo': "Nur ich",
  'avvio.o-persone-poche': "2 bis 5",
  'avvio.o-persone-molte': "Mehr als 5",
  'avvio.d-squadra': "Wer arbeitet mit dir?",
  'avvio.a-squadra': "Alle melden sich mit ihrer eigenen E-Mail an und sehen, was ihre Rolle braucht. Geht auch später.",
  'avvio.d-lumi': "Möchtest du Lumi, den Assistenten?",
  'avvio.a-lumi': "Du fragst einfach in Worten: „Wie viel habe ich diese Woche verkauft?“, „Füge den Artikeln die Größe hinzu“. Lumi schlägt vor, du bestätigst.",
  'avvio.d-esempi': "Möchtest du Kubo mit Beispieldaten sehen?",
  'avvio.a-esempi': "Erfundene, aber glaubwürdige Kunden, Verkäufe und Termine, um alles auszuprobieren. Mit einem Klick wieder weg.",
  'avvio.o-si': "Ja",
  'avvio.o-no': "Nein",
  'avvio.collaboratore': "Mitarbeiter (sieht und bearbeitet, löscht nicht)",
  'avvio.lettura': "Nur lesen",
  'avvio.nome': "Name",
  'avvio.ruolo': "Rolle",
  'avvio.togli': "Entfernen",
  'avvio.altra-persona': "+ Noch eine Person",
  'avvio.password-provvisoria': "Alle bekommen ein vorläufiges Passwort, das du am Ende siehst.",
  'avvio.sezioni': "Ich richte dir diese Bereiche ein",
  'avvio.nessuna-sezione': "Keine: Du fängst bei null an",
  'avvio.campi-spenti': { one: "{n} Feld, das du nicht brauchst, bleibt ausgeschaltet (wieder einschalten unter {personalizza})", other: "{n} Felder, die du nicht brauchst, bleiben ausgeschaltet (wieder einschalten unter {personalizza})" },
  'avvio.persone-ruolo': { one: "Eine Person mit ihrer Rolle", other: "{n} Personen, jede mit ihrer Rolle" },
  'avvio.lumi-acceso': "Lumi an",
  'avvio.lumi-spento': "Lumi aus (einschalten, wann du willst)",
  'avvio.con-esempi': "Mit Beispieldaten, mit einem Klick entfernbar",
  'avvio.senza-esempi': "Ohne Beispieldaten",
  'avvio.ci-siamo': "Fast geschafft",
  'avvio.chi-sei': "Noch eins: Wer bist du? Du wirst Inhaber, also derjenige, der alles darf.",
  'avvio.preparo': "Kubo wird eingerichtet…",
  'avvio.prepara': "Kubo einrichten",
  'avvio.pronto': "Kubo ist bereit",
  'avvio.consegna': "Gib allen ihr vorläufiges Passwort. Dieser Bildschirm erscheint nicht wieder: Kopiere sie jetzt.",
  'avvio.entra': "Kubo öffnen",
  'avvio.tappa-sezioni': "Deine Bereiche",
  'avvio.tappa-sezioni-testo': "Hier ist alles drin{esempi}. Jeder Bereich ist eine Liste, die du durchsuchen, filtern, sortieren und in Spalten ansehen kannst.",
  'avvio.tappa-personalizza-testo': "Fehlt ein Feld? Ist eins zu viel? Hier fügst du Felder hinzu, benennst sie um und verschiebst sie, ohne je Daten zu verlieren. Neue Bereiche legst du über „{nuova}“ an.",
  'avvio.tappa-lumi-testo': "Frag einfach in Worten: „Wie viel habe ich diese Woche verkauft?“, „Füge den Artikeln die Größe hinzu“. Lumi liest mit deinen Berechtigungen und schlägt vor; du entscheidest.",
  'avvio.tappa-cruscotto': "Das Dashboard",
  'avvio.tappa-cruscotto-testo': "Die wichtigen Zahlen und was Aufmerksamkeit braucht, aktuell, während du arbeitest. Ändern kannst du es oben mit „{modifica}“.",
  'avvio.n-di': "{n} von {tot}",
  'avvio.salta': "Überspringen",
  'avvio.capito': "Verstanden",
  'avvio.promemoria': "Du siehst Beispieldaten",
  'avvio.toglili': "Entfernen",
  'avvio.conferma-togli': "Alle Beispieldaten entfernen? Was du selbst eingetragen hast, bleibt.",
  'avvio.tolte': { one: "{n} Beispielzeile entfernt", other: "{n} Beispielzeilen entfernt" },
  'avvio.aggiunte': { one: "{n} Beispielzeile hinzugefügt", other: "{n} Beispielzeilen hinzugefügt" },
  'avvio.togli-esempi': "Beispieldaten entfernen",
  'avvio.rimetti-esempi': "Beispieldaten wieder einfügen",
  'avvio.pagina-titolo': "Beispieldaten und Rundgang",
  'avvio.ci-sono': { one: "Es gibt {n} Beispielzeile, damit du Kubo ohne Sorge ausprobieren kannst. Wenn du so weit bist, entferne sie: Sie verschwindet (auch wenn du sie bearbeitet hast), was du selbst eingetragen hast, bleibt, und wo noch nichts von dir ist, beginnt die Nummerierung wieder bei 1.", other: "Es gibt {n} Beispielzeilen: erfundene Kunden, Buchungen und Termine, damit du Kubo ohne Sorge ausprobieren kannst. Wenn du so weit bist, entferne sie: Sie verschwinden alle (auch die, die du bearbeitet hast), was du selbst eingetragen hast, bleibt, und wo noch nichts von dir ist, beginnt die Nummerierung wieder bei 1." },
  'avvio.solo-titolare': "Nur der Inhaber kann sie entfernen.",
  'avvio.nessun-esempio': "Es gibt keine Beispieldaten.",
  'avvio.rivedere': "Willst du nochmal sehen, wo alles ist?",
  'avvio.rifai-giro': "Rundgang wiederholen",
  'avvio.lato': "Beispieldaten und Rundgang",
  'avvio.lato-sezione': "Erste Schritte",
};
