export default {
  'comune.benvenuto': 'Willkommen bei Kubo',
  'comune.benvenuto-sotto': 'Die Unternehmenssoftware, die du dir selbst zusammenstellst. Starte mit einer Vorlage und ändere dann alles, was du willst.',
  'comune.nome-azienda': 'Name des Unternehmens',
  'comune.tuo-nome': 'Dein Name',
  'comune.email': 'E-Mail',
  'comune.password': 'Passwort',
  'comune.password-nuova': 'Passwort (mindestens 8 Zeichen)',
  'comune.valuta': 'Währung',
  'comune.da-dove': 'Womit fangen wir an? (Weitere kannst du später hinzufügen)',
  'comune.inizia': 'Loslegen',
  'comune.lingua': 'Sprache',
  'comune.accedi-per': 'Melde dich an, um fortzufahren.',
  'comune.accedi': 'Anmelden',
  'comune.gestione': 'Verwaltung',
  'comune.nuova-sezione': 'Neuer Bereich',
  'comune.persone-permessi': 'Personen und Rechte',
  'comune.esci': 'Abmelden',
  'comune.personalizza': 'Anpassen',
  'comune.personalizza-sezione': 'Diesen Bereich anpassen',
  'comune.nessuna-sezione': 'Noch keine Bereiche.',
  'comune.creane-una': 'Einen anlegen',
  'comune.chiedi-titolare': 'Bitte den Inhaber, einen anzulegen.',
  'comune.qualcosa-non-va': 'Etwas ist schiefgelaufen',
  'comune.errore-n': 'Fehler {stato}',
  'comune.percento': '{n} %',
  'comune.si': 'Ja',
  'comune.no': 'Nein',
  'comune.si-min': 'ja',
  'comune.no-min': 'nein',
  'comune.su': 'Nach oben',
  'comune.giu': 'Nach unten',
  'comune.togli': 'Entfernen',
  'comune.cerca': 'Suchen…',
  'comune.carico': 'Wird geladen…',
};
