export default {
  'connettori.titolo': "Connectoren",
  'connettori.spiega': "Verbinde Kubo mit den Diensten, die du schon nutzt: Zahlungen, Onlineshop, E-Rechnungen, E-Mail, Kalender. Die Schlüssel bleiben verschlüsselt in Kubo und gehen nie zurück an den Browser.",
  'connettori.terzi': "Ein Connector von Dritten wird in den Ordner „connettori“ neben den Daten kopiert: Du schaltest ihn hier ein, nachdem du seine Prüfsumme kontrolliert hast.",
  'connettori.ufficiale': "Offiziell",
  'connettori.locale': "Von Hand installiert",
  'connettori.rotto': "Der Connector lädt nicht: Prüfe die Datei connettore.js",
  'connettori.stato-acceso': "An",
  'connettori.stato-spento': "Aus",
  'connettori.stato-incompleto': "Zu vervollständigen",
  'connettori.stato-cambiato': "Geändert",
  'connettori.stato-rotto': "Defekt",
  'connettori.mancano': "Es fehlt noch: {cosa}",
  'connettori.cambiato': "Die Datei des Connectors hat sich nach dem Einschalten geändert: Er bleibt angehalten, bis du ihn mit Prüfung der Prüfsumme wieder einschaltest.",
  'connettori.accendi': "Einschalten",
  'connettori.spegni': "Ausschalten",
  'connettori.accendi-titolo': "{nome} einschalten?",
  'connettori.potra': "Er kann dann:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "lesen",
  'connettori.p-crea': "anlegen",
  'connettori.p-modifica': "bearbeiten",
  'connettori.p-elimina': "löschen",
  'connettori.somma': "Prüfsumme (SHA-256) der Datei: Vergleiche sie mit der vom Autor veröffentlichten.",
  'connettori.impostazioni': "Einstellungen",
  'connettori.salvato-segreto': "Gespeichert",
  'connettori.cambia': "Ändern",
  'connettori.togli': "Entfernen",
  'connettori.interni': "Adressen im internen Netz erlauben (ein Server im Laden, eine Kasse)",
  'connettori.salva': "Speichern",
  'connettori.salvato': "Gespeichert",
  'connettori.prova': "Verbindung testen",
  'connettori.provo': "Teste…",
  'connettori.prova-ok': "Verbindung funktioniert",
  'connettori.prova-no': "Funktioniert nicht: {motivo}",
  'connettori.collegamento': "Verbindung",
  'connettori.webhook': "Webhook-Adresse",
  'connettori.webhook-aiuto': "Füge sie in die Webhook-Einstellungen des Dienstes ein.",
  'connettori.indirizzo-segreto': "Geheime Adresse",
  'connettori.indirizzo-aiuto': "Wer diese Adresse hat, sieht die Daten: Gib sie nur an, wer sie braucht.",
  'connettori.account': "Konto",
  'connettori.collegato': "Verbunden",
  'connettori.scollegato': "Nicht verbunden",
  'connettori.scade': "Läuft ab {quando}",
  'connettori.collega': "Konto verbinden",
  'connettori.ricollega': "Neu verbinden",
  'connettori.oauth-ok': "Konto verbunden",
  'connettori.oauth-scaduto': "Die Verbindung ist abgelaufen: Versuche es erneut",
  'connettori.oauth-errore': "Die Verbindung ist fehlgeschlagen: Sieh im Protokoll nach",
  'connettori.abbinamenti': "Feldzuordnung",
  'connettori.abbinamenti-aiuto': "Die Felder des Connectors und die von Kubo: Wenn du ein Feld umbenennst, bleibt die Zuordnung.",
  'connettori.sezione-manca': "Der Bereich „{nome}“ fehlt",
  'connettori.facoltativo': "optional",
  'connettori.salva-abbinamenti': "Zuordnungen speichern",
  'connettori.sincronizzazioni': "Synchronisierungen",
  'connettori.ogni': "alle {ogni}",
  'connettori.alle': "um {alle}",
  'connettori.ultimo': "Letzter Lauf: {quando}",
  'connettori.prossimo': "nächster: {quando}",
  'connettori.sincronizza': "Jetzt synchronisieren",
  'connettori.giro-ok': "Erledigt",
  'connettori.coda': "In der Warteschlange: {attesa} · fehlgeschlagen: {fallite}",
  'connettori.riprova': "Fehlgeschlagene wiederholen",
  'connettori.registro': "Protokoll",
  'connettori.registro-vuoto': "Noch nichts: Hier siehst du, was ankommt und was rausgeht.",
  'connettori.col-quando': "Wann",
  'connettori.col-verso': "Richtung",
  'connettori.col-esito': "Ergebnis",
  'connettori.col-cosa': "Was",
  'connettori.verso-entrata': "eingehend",
  'connettori.verso-uscita': "ausgehend",
  'connettori.verso-giro': "geplanter Lauf",
  'connettori.verso-azione': "Aktion",
  'connettori.verso-prova': "Test",
  'connettori.verso-oauth': "Konto",
  'connettori.verso-sistema': "System",
  'connettori.copia': "Kopieren",
  'connettori.copiato': "Kopiert",
  'connettori.annulla': "Abbrechen",
  'connettori.conferma': "Bestätigen",
  'connettori.fatto': "Erledigt",
};
