export default {
  'connettori.terzi': "Ein Connector von Dritten wird in den Ordner „connettori“ neben den Daten kopiert: Du schaltest ihn hier ein, nachdem du seine Prüfsumme kontrolliert hast.",
  'connettori.locale': "Von Hand installiert",
  'connettori.rotto': "Der Connector lädt nicht: Prüfe die Datei connettore.js",
  'connettori.stato-acceso': "An",
  'connettori.stato-spento': "Aus",
  'connettori.stato-incompleto': "Zu vervollständigen",
  'connettori.stato-cambiato': "Geändert",
  'connettori.stato-rotto': "Defekt",
  'connettori.mancano': "Es fehlt noch: {cosa}",
  'connettori.cambiato': "Die Datei des Connectors hat sich nach dem Einschalten geändert: Er bleibt angehalten, bis du ihn mit Prüfung der Prüfsumme wieder einschaltest.",
  'connettori.accendi': "Einschalten",
  'connettori.spegni': "Ausschalten",
  'connettori.accendi-titolo': "{nome} einschalten?",
  'connettori.potra': "Er kann dann:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "lesen",
  'connettori.p-crea': "anlegen",
  'connettori.p-modifica': "bearbeiten",
  'connettori.p-elimina': "löschen",
  'connettori.somma': "Prüfsumme (SHA-256) der Datei: Vergleiche sie mit der vom Autor veröffentlichten.",
  'connettori.da-approvare': "Der Code dieses Connectors wurde noch nicht ausgeführt: Kubo lädt ihn erst, wenn du die Prüfsumme unten bestätigst. Danach siehst du die Bereiche, die er nutzen darf.",
  'connettori.impostazioni': "Einstellungen",
  'connettori.salvato-segreto': "Gespeichert",
  'connettori.cambia': "Ändern",
  'connettori.togli': "Entfernen",
  'connettori.interni': "Adressen im internen Netz erlauben (ein Server im Laden, eine Kasse)",
  'connettori.salva': "Speichern",
  'connettori.salvato': "Gespeichert",
  'connettori.prova': "Verbindung testen",
  'connettori.provo': "Teste…",
  'connettori.prova-ok': "Verbindung funktioniert",
  'connettori.prova-no': "Funktioniert nicht: {motivo}",
  'connettori.collegamento': "Verbindung",
  'connettori.webhook': "Webhook-Adresse",
  'connettori.webhook-aiuto': "Füge sie in die Webhook-Einstellungen des Dienstes ein.",
  'connettori.indirizzo-segreto': "Geheime Adresse",
  'connettori.indirizzo-aiuto': "Wer diese Adresse hat, sieht die Daten: Gib sie nur an, wer sie braucht.",
  'connettori.account': "Konto",
  'connettori.collegato': "Verbunden",
  'connettori.scollegato': "Nicht verbunden",
  'connettori.scade': "Läuft ab {quando}",
  'connettori.collega': "Konto verbinden",
  'connettori.ricollega': "Neu verbinden",
  'connettori.oauth-ok': "Konto verbunden",
  'connettori.oauth-scaduto': "Die Verbindung ist abgelaufen: Versuche es erneut",
  'connettori.oauth-errore': "Die Verbindung ist fehlgeschlagen: Sieh im Protokoll nach",
  'connettori.abbinamenti': "Feldzuordnung",
  'connettori.abbinamenti-aiuto': "Die Felder des Connectors und die von Kubo: Wenn du ein Feld umbenennst, bleibt die Zuordnung.",
  'connettori.sezione-manca': "Der Bereich „{nome}“ fehlt",
  'connettori.facoltativo': "optional",
  'connettori.salva-abbinamenti': "Zuordnungen speichern",
  'connettori.sincronizzazioni': "Synchronisierungen",
  'connettori.ogni': "alle {ogni}",
  'connettori.alle': "um {alle}",
  'connettori.ultimo': "Letzter Lauf: {quando}",
  'connettori.prossimo': "nächster: {quando}",
  'connettori.sincronizza': "Jetzt synchronisieren",
  'connettori.giro-ok': "Erledigt",
  'connettori.coda': "In der Warteschlange: {attesa} · fehlgeschlagen: {fallite}",
  'connettori.riprova': "Fehlgeschlagene wiederholen",
  'connettori.registro': "Protokoll",
  'connettori.registro-vuoto': "Noch nichts: Hier siehst du, was ankommt und was rausgeht.",
  'connettori.col-quando': "Wann",
  'connettori.col-verso': "Richtung",
  'connettori.col-esito': "Ergebnis",
  'connettori.col-cosa': "Was",
  'connettori.verso-entrata': "eingehend",
  'connettori.verso-uscita': "ausgehend",
  'connettori.verso-giro': "geplanter Lauf",
  'connettori.verso-azione': "Aktion",
  'connettori.verso-prova': "Test",
  'connettori.verso-oauth': "Konto",
  'connettori.verso-sistema': "System",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "Fehler",
  'connettori.esito-avviso': "Warnung",
  'connettori.esito-ignorato': "ignoriert",
  'connettori.copia': "Kopieren",
  'connettori.copiato': "Kopiert",
  'connettori.annulla': "Abbrechen",
  'connettori.conferma': "Bestätigen",
  'connettori.fatto': "Erledigt",
  // la libreria delle integrazioni e le ricette
  'connettori.libreria': "Integrationsbibliothek",
  'connettori.libreria-sotto': "{n} Integrationen · {accese} aktiv. Schlüssel bleiben in Kubo verschlüsselt und gehen nie zurück an den Browser.",
  'connettori.cerca': "Suchen: Stripe, Rechnung, WhatsApp, Versand…",
  'connettori.categorie': "Kategorien",
  'connettori.tutte': "Alle",
  'connettori.trovate': "{n} gefunden",
  'connettori.le-tue': "Aktiv",
  'connettori.nessuna': "Keine Integration gefunden.",
  'connettori.prova-http': "Nicht dabei? Verbinde es mit HTTP / REST-API",
  'connettori.smanettoni': "Für Bastler: Kubos API ist in OpenAPI 3.1 unter /api/openapi-3.1.json beschrieben, und ein neuer Konnektor ist ein Ordner mit einer Datei (docs/CONNETTORI.md).",
  'connettori.f-gratis': "Kostenlos",
  'connettori.f-facili': "Einfach",
  'connettori.f-italia': "Italien",
  'connettori.stato-da-approvare': "Zu bestätigen",
  'connettori.cat-pagamenti': "Zahlungen",
  'connettori.cat-cassa': "Kasse und POS",
  'connettori.cat-negozi-online': "Onlineshops",
  'connettori.cat-marketplace': "Marktplätze",
  'connettori.cat-fatturazione': "Rechnungsstellung",
  'connettori.cat-contabilita': "Buchhaltung",
  'connettori.cat-banche': "Banken",
  'connettori.cat-spedizioni': "Versand",
  'connettori.cat-whatsapp': "WhatsApp",
  'connettori.cat-messaggi': "Nachrichten",
  'connettori.cat-email': "E-Mail",
  'connettori.cat-sms': "SMS",
  'connettori.cat-calendario': "Kalender",
  'connettori.cat-prenotazioni': "Buchungen",
  'connettori.cat-archivio': "Speicher und Dateien",
  'connettori.cat-produttivita': "Produktivität",
  'connettori.cat-marketing': "Marketing",
  'connettori.cat-recensioni': "Bewertungen",
  'connettori.cat-firma': "Signatur",
  'connettori.cat-dati-aziende': "Firmendaten",
  'connettori.cat-automazione': "Automatisierung",
  'connettori.cat-ia': "KI",
  'connettori.cat-altro': "Sonstiges",
  'connettori.costo-gratis': "Kostenlos",
  'connettori.costo-a-consumo': "Nach Verbrauch",
  'connettori.costo-abbonamento': "Abonnement",
  'connettori.costo-contratto': "Mit Vertrag",
  'connettori.diff-facile': "Einfach",
  'connettori.diff-media': "Mittel",
  'connettori.diff-difficile': "Für Bastler",
  'connettori.zona-IT': "Italien",
  'connettori.zona-UE': "Europa",
  'connettori.zona-mondo': "Weltweit",
  'connettori.prova-finto': "Mit einem Testdienst geprüft",
  'connettori.prova-vero': "Mit dem echten Dienst geprüft",
  'connettori.prova-finto-aiuto': "Die automatischen Tests nutzen einen Testdienst, der wie der echte antwortet, laut der Dokumentation in den Quellen: probiere es im Testmodus, bevor du dich darauf verlässt.",
  'connettori.prova-vero-aiuto': "Dieser Konnektor wurde auch mit dem echten Dienst geprüft.",
  'connettori.sito': "Website des Dienstes",
  'connettori.apri': "Öffnen",
  'connettori.cosa-serve': "Was du brauchst",
  'connettori.passi': "Schritt für Schritt",
  'connettori.costo': "Kosten",
  'connettori.difficolta': "Schwierigkeit",
  'connettori.fonti': "Quellen ({n})",
  'connettori.permessi-titolo': "Worauf es zugreifen darf",
  'connettori.nessun-permesso': "Kein Kubo-Bereich: nur die Aufrufe, die du einrichtest.",
  'connettori.r-nessuna': "Noch keine Rezepte. Füge eins hinzu:",
  'connettori.r-tipo-uscita': "Ausgehend: wenn sich eine Zeile ändert",
  'connettori.r-tipo-azione': "Button im Datensatz und Lumi",
  'connettori.r-tipo-entrata': "Eingehend: der Dienst schreibt in Kubo",
  'connettori.r-nome': "Name des Rezepts",
  'connettori.r-attiva': "Aktiv",
  'connettori.r-sezione': "Bereich",
  'connettori.r-eventi': "Wenn die Zeile",
  'connettori.ev-crea': "angelegt wird",
  'connettori.ev-modifica': "geändert wird",
  'connettori.ev-elimina': "gelöscht wird",
  'connettori.ev-ripristina': "wiederhergestellt wird",
  'connettori.r-metodo': "Methode",
  'connettori.r-percorso': "Pfad (nach der Basisadresse) oder vollständige Adresse",
  'connettori.r-indirizzo': "Adresse, die dir die Plattform gibt (https://…)",
  'connettori.r-corpo': "Body (JSON mit Platzhaltern; leer = die ganze Zeile)",
  'connettori.r-segnaposto': "Platzhalter: {campi}",
  'connettori.r-scrive': "Vorschau zeigen und vor dem Senden bestätigen lassen",
  'connettori.r-modo': "Wenn die Zeile schon existiert",
  'connettori.modo-crea-o-aggiorna': "aktualisieren, sonst anlegen",
  'connettori.modo-crea': "immer eine neue Zeile anlegen",
  'connettori.modo-aggiorna': "nur aktualisieren",
  'connettori.r-chiave': "Schlüsselfeld (um die Zeile wiederzufinden)",
  'connettori.r-elenco': "Liste im JSON (optional, z. B. items)",
  'connettori.r-idevento': "Ereignis-ID im JSON (optional, gegen Duplikate)",
  'connettori.r-campi': "Zuordnungen (leer = JSON-Schlüssel mit denselben Namen wie die Felder)",
  'connettori.r-da': "Pfad im JSON (z. B. kunde.email)",
  'connettori.r-a': "Kubo-Feld",
  'connettori.r-aggiungi-campo': "Zuordnung hinzufügen",
  'connettori.r-indirizzo-entrata': "Adresse für den Dienst (JSON-POST)",
  'connettori.r-salva-prima': "Speichern und aktivieren, um die Adresse zu sehen.",
};
