// Area «desktop» (web/moduli/desktop.js): rete, backup e versioni nuove.
export default {
  'desktop.tipo-giornaliero': "Täglich",
  'desktop.tipo-modifica': "Vor einer Änderung",
  'desktop.tipo-manuale': "Manuell",
  'desktop.tipo-sicurezza': "Vor einer Wiederherstellung",
  'desktop.tipo-caricato': "Hochgeladen",
  'desktop.qr': "QR-Code mit der Adresse",
  'desktop.rete-titolo': "Weitere Geräte verbinden",
  'desktop.lato-rete': "Geräte verbinden",
  'desktop.un-momento': "Einen Moment…",
  'desktop.copiato': "Kopiert",
  'desktop.copia-fallita': "Kopieren fehlgeschlagen: Markiere es von Hand",
  'desktop.indirizzo': "Adresse",
  'desktop.altra-rete': "Oder in einem anderen Netz im Büro",
  'desktop.copia-indirizzo': "Adresse kopieren",
  'desktop.codice': "Code",
  'desktop.passo-telefono': "Handy oder Tablet:",
  'desktop.passo-telefono-testo': "richte die Kamera auf den Code und tippe auf den Link.",
  'desktop.passo-computer': "Ein anderer Computer:",
  'desktop.passo-computer-codice': "öffne den Browser und gib die Adresse ein. In der Kubo-App wählst du „Mit einem Kubo im Netz verbinden“ und gibst den Code ein.",
  'desktop.passo-computer-indirizzo': "öffne den Browser und gib die Adresse ein. In der Kubo-App wählst du „Mit einem Kubo im Netz verbinden“ und gibst die Adresse ein.",
  'desktop.solo-qui': "Im Moment antwortet Kubo nur diesem Computer.",
  'desktop.apri-rete': "Damit du es auch von anderen Geräten nutzen kannst, öffne in der Kubo-App das Menü in der oberen Leiste (oder im Infobereich) und schalte „Offen fürs lokale Netz“ ein.",
  'desktop.da-terminale': "Wenn du es im Terminal startest:",
  'desktop.non-in-rete': "Dieser Computer scheint mit keinem Netz verbunden zu sein. Verbinde ihn mit dem WLAN oder dem Kabel im Büro und lade die Seite neu.",
  'desktop.stessa-rete': "Die anderen Geräte müssen im selben Netz sein (dasselbe WLAN oder dasselbe Kabel). Wenn sie sich nicht verbinden, prüfe, ob die Firewall dieses Computers Kubo durchlässt.",
  'desktop.backup': "Backups",
  'desktop.fai-adesso': "Jetzt sichern",
  'desktop.copia-in-corso': "Wird kopiert…",
  'desktop.fatto': "Backup erstellt",
  'desktop.ultimo': "Letztes Backup",
  'desktop.nessuno-ancora': "Noch keins",
  'desktop.copie-tenute': "Aufbewahrte Kopien",
  'desktop.in-tutto': "{peso} insgesamt",
  'desktop.spiega-automatici': "Kubo kopiert die Datenbank jeden Tag von selbst, dazu vor jeder Änderung an der Struktur und vor jedem Import. Es behält {giornalieri} tägliche, {settimanali} wöchentliche und {mensili} monatliche Kopien; die von Hand erstellten bleiben, bis du sie löschst. Die Anhänge kommen in den Ordner „allegati“, wobei nur neue kopiert werden.",
  'desktop.spiega-spenti': "Die automatischen Backups sind aus (KUBO_BACKUP=0): Denk daran, sie von Hand oder mit deinen eigenen Werkzeugen zu machen.",
  'desktop.cartella-esempio': "Zum Beispiel {a} oder {b}",
  'desktop.cartella-nuova': "Ab jetzt landen die Backups dort",
  'desktop.cartella-tornata': "Die Backups liegen wieder neben den Daten",
  'desktop.scegli-cartella': "Ordner wählen…",
  'desktop.dove': "Wohin die Backups gehen",
  'desktop.in-memoria': "(Datenbank im Arbeitsspeicher: keine Backups)",
  'desktop.nota-esterna': "Ein Ordner, den du gewählt hast. Ist die Festplatte nicht angeschlossen, kommt die Tageskopie neben die Daten und hier erscheint ein Hinweis.",
  'desktop.nota-accanto': "Neben den Daten, auf diesem Computer. Besser ist eine zweite Kopie woanders: eine externe Festplatte oder ein synchronisierter Ordner (Dropbox, OneDrive, iCloud, Google Drive).",
  'desktop.usa-cartella': "Diesen Ordner verwenden",
  'desktop.torna-accanto': "Zurück neben die Daten",
  'desktop.vuoto': "Noch keine Backups. Das erste kommt in ein paar Minuten von selbst, oder du machst es jetzt.",
  'desktop.col-quando': "Wann",
  'desktop.col-tipo': "Art",
  'desktop.col-dimensione': "Größe",
  'desktop.accanto-ai-dati': "neben den Daten",
  'desktop.scarica': "Herunterladen",
  'desktop.ripristina': "Wiederherstellen",
  'desktop.elimina': "Dieses Backup löschen",
  'desktop.elimina-conferma': "Das Backup vom {quando} löschen? Es lässt sich dann nicht mehr wiederherstellen.",
  'desktop.eliminato': "Backup gelöscht",
  'desktop.ripristino-titolo': "Zu diesem Backup zurückkehren?",
  'desktop.ripristino-prima': "Alles wird wieder so, wie es am",
  'desktop.ripristino-dopo': " war. Alles, was danach gemacht wurde, verschwindet aus der Ansicht.",
  'desktop.ripristino-nota': "Vorher macht Kubo eine Kopie vom jetzigen Stand („{tipo}“): Wenn du es dir anders überlegst, stellst du die wieder her und verlierst nichts. Wer an anderen Geräten arbeitet, sieht die Seite neu laden.",
  'desktop.capito': "Verstanden, ich will zu diesem Zeitpunkt zurück",
  'desktop.annulla': "Abbrechen",
  'desktop.ripristino-in-corso': "Wird wiederhergestellt…",
  'desktop.ripristinato': "Wiederhergestellt",
  'desktop.ripristinato-altro': "Der Inhaber hat ein Backup wiederhergestellt: Seite wird neu geladen…",
  'desktop.caricato': "Backup hochgeladen: {azienda}, {persone}, {sezioni}. Du findest es oben in der Liste.",
  'desktop.persone': {"one": "{n} Person", "other": "{n} Personen"},
  'desktop.sezioni': {"one": "{n} Bereich", "other": "{n} Bereiche"},
  'desktop.carica': "Backup hochladen",
  'desktop.carica-nota': "Eine hier heruntergeladene .db-Datei, auch von einem anderen Computer. Kubo prüft sie und nimmt sie in die Liste auf: Dann entscheidest du, ob du sie wiederherstellst.",
  'desktop.scegli-file': "Datei wählen…",
  'desktop.uscita-versione': "Neue Version verfügbar:",
  'desktop.novita': "was ist neu",
  'desktop.aggiornato': "Du hast die neueste Version.",
  'desktop.versioni': "Neue Versionen",
  'desktop.stai-usando': "Du verwendest Kubo",
  'desktop.controlla-ogni-giorno': "Jeden Tag nach einer neuen Version suchen und mir Bescheid geben",
  'desktop.versioni-nota': "Kubo fragt bei GitHub nur die Nummer der neuesten veröffentlichten Version ab: Es sendet keine Firmendaten und installiert nichts von selbst. Du aktualisierst, wann du willst, nach einem Backup.",
  'desktop.controlla-adesso': "Jetzt prüfen",
  'desktop.avviso-versione': "Neue Kubo-Version:",
  'desktop.dettagli': "Details",
  'desktop.chiudi': "Schließen",
  'desktop.solo-titolare': "Backups verwaltet der Inhaber.",
};
