// E-invoices (web/moduli/fatture.js): received invoices, virtual stamp duty, numbering.
export default {
  'fatture.aggiorna-chiedi': "Lumis Rechnungen sind gewachsen: Preise mit bis zu 8 Nachkommastellen, Vorsorgekasse, öffentliche Verwaltung, erhaltene Rechnungen. Jetzt die neuen Felder hinzufügen? Es gehen keine Daten verloren.",
  'fatture.aggiornato': "Rechnungen aktualisiert",
  'fatture.bloccata': "Ausgestellt · gesperrt",
  'fatture.bloccata-nota': "Eine ausgestellte Rechnung lässt sich nicht mehr ändern: Korrigiere sie mit einer Gut- oder Lastschrift. Zahlungsstatus und interne Notizen kannst du ändern.",
  'fatture.bollo': "Virtuelle Stempelsteuer",
  'fatture.bollo-nota': "Die Stempelsteuer zahlst du mit dem F24 (Steuercodes 2521-2524) oder im geschützten Bereich der Agenzia delle Entrate, die den Betrag jedes Quartal berechnet. Es zählen die ausgestellten Rechnungen mit angehakter Stempelsteuer.",
  'fatture.chiudi': "Schließen",
  'fatture.codice-tributo': "Steuercode",
  'fatture.crea-integrazione': "Ergänzung erstellen",
  'fatture.da-integrare': "Zu ergänzen",
  'fatture.da-pagare': "Zu zahlen",
  'fatture.da-versare': "Abzuführen",
  'fatture.emesse': "Ausgestellt",
  'fatture.entro': "Bis",
  'fatture.fatture-con-bollo': "Rechnungen mit Stempelsteuer",
  'fatture.fornitore-nuovo': "neu",
  'fatture.gia-importata': "{numero} war schon da",
  'fatture.importa': "Rechnungen importieren",
  'fatture.importata': "{numero} vom {data} · {totale}",
  'fatture.integra-conferma': "Ergänzung (oder Eigenrechnung) für Rechnung {numero} erstellen? Sie entsteht als Entwurf: Du prüfst sie und stellst sie aus.",
  'fatture.integra-nota': "Erhaltene Rechnung mit Reverse Charge oder von einem ausländischen Lieferanten: Sie braucht die Ergänzung TD16-TD19.",
  'fatture.integrazione-creata': "Ergänzung {tipo} als Entwurf erstellt",
  'fatture.intestata-ad-altri': "ist nicht an deine USt-IdNr. adressiert",
  'fatture.leggo': "Wird gelesen…",
  'fatture.manca-modello': "Füge zuerst die Vorlage „Rechnungen und E-Rechnung“ hinzu.",
  'fatture.mancano': "Fehlende Nummern",
  'fatture.nessun-buco': "keine Lücken",
  'fatture.nessuna-emessa': "Dieses Jahr keine Rechnungen ausgestellt.",
  'fatture.niente-da-integrare': "Nichts zu ergänzen.",
  'fatture.niente-da-pagare': "Nichts zu zahlen.",
  'fatture.numerazione': "Nummerierung",
  'fatture.numerazione-nota': "Die Nummern laufen je Serie und Jahr ohne Lücken. Eine Lücke kommt meist von einer von Hand eingetragenen Rechnung: Prüfe das, bevor du die nächste ausstellst.",
  'fatture.ricevute': "Erhalten",
  'fatture.ricevute-nota': "Lade die Rechnungen aus dem Steuerpostfach oder der PEC herunter und zieh sie hierher: auch signierte .p7m und Dateien mit mehreren Rechnungen. Lumi legt den Lieferanten an und erfasst Kosten und Fälligkeit.",
  'fatture.serie': "Serie",
  'fatture.serie-principale': "Hauptserie",
  'fatture.solo-xml': "Nur .xml- oder .p7m-Dateien",
  'fatture.stampa': "Drucken",
  'fatture.titolo': "E-Rechnungen",
  'fatture.totale': "Gesamt",
  'fatture.trascina': "Erhaltene Rechnungen hierher ziehen",
  'fatture.trascina-nota': "oder tippen, um Dateien zu wählen (.xml, .xml.p7m)",
  'fatture.trimestre': "Quartal",
  'fatture.trimestre-n': "{n}. Quartal",
  'fatture.troppo-grande': "Datei zu groß (höchstens 3,5 MB)",
  'fatture.tutte-le-ricevute': "Alle erhaltenen Rechnungen →",
  'fatture.ultimo': "Letzte",
  'fatture.vedi': "Rechnung ansehen",
  'fatture.vista': "Erhaltene Rechnung",
};
