// Steuern (web/moduli/fisco.js).
export default {
  'fisco.titolo': "Steuern",
  'fisco.anno': "Jahr",
  'fisco.responsabilita': "Kubo rechnet und bereitet aus deinen Daten vor: prüfe vor dem Zahlen oder Einreichen. Die Verantwortung bleibt beim Steuerpflichtigen.",
  'fisco.scheda-riepilogo': "Zu zahlen",
  'fisco.scheda-iva': "MwSt.",
  'fisco.scheda-forfettario': "Pauschal",
  'fisco.scheda-f24': "F24",
  'fisco.scheda-ritenute': "Quellensteuer",
  'fisco.scheda-scadenze': "Fristen",
  'fisco.scheda-commercialista': "Für den Steuerberater",
  'fisco.scheda-impostazioni': "Einstellungen",
  'fisco.da-pagare-anno': "Dieses Jahr noch zu zahlen",
  'fisco.prossimo': "Nächste Zahlung",
  'fisco.niente': "Nichts in Sicht.",
  'fisco.regime': "Steuerregelung",
  'fisco.coeff': "Koeffizient {n} %",
  'fisco.regime-forfettario': "Pauschalregelung (forfettario)",
  'fisco.regime-semplificato': "Vereinfacht",
  'fisco.regime-ordinario': "Ordentlich",
  'fisco.periodicita-trimestrale': "MwSt. vierteljährlich",
  'fisco.periodicita-mensile': "MwSt. monatlich",
  'fisco.manca-ricevute': "Für die MwSt. auf Einkäufe und die Quellensteuer füge den Bereich „Eingangsrechnungen“ hinzu.",
  'fisco.apri-impostazioni': "Einstellungen öffnen",
  'fisco.prossimi-versamenti': "Nächste Zahlungen",
  'fisco.data': "Datum",
  'fisco.cosa': "Was",
  'fisco.codice': "Code",
  'fisco.anno-rif': "Bezugsjahr",
  'fisco.importo': "Betrag",
  'fisco.vedi-f24': "F24",
  'fisco.prossime-scadenze': "Nächste Fristen",
  'fisco.mese-n': "Monat {n}",
  'fisco.trimestre-n': "{n}. Quartal",
  'fisco.lipe-trimestre': "LIPE {n}. Quartal",
  'fisco.liquidazioni': "Periodische Abrechnungen",
  'fisco.periodo': "Zeitraum",
  'fisco.iva-vendite': "MwSt. Verkäufe",
  'fisco.iva-acquisti': "Abziehbare MwSt.",
  'fisco.riporti': "Vorträge",
  'fisco.interessi': "Zinsen 1 %",
  'fisco.da-versare': "Zu zahlen",
  'fisco.scadenza': "Fällig",
  'fisco.a-credito': "Guthaben {importo}",
  'fisco.riportato': "wird vorgetragen (bis 100 €)",
  'fisco.acconto-dicembre': "MwSt.-Vorauszahlung im Dezember",
  'fisco.acconto-dovuto': "Vorauszahlung von {importo} nach der Methode {metodo}: Code {codice}, bis {data}.",
  'fisco.acconto-no': "Keine Vorauszahlung fällig (unter 103,29 € oder Daten fehlen: trage sie in den Einstellungen ein).",
  'fisco.acconto-nota': "Historisch: 88 % dessen, was du für den letzten Zeitraum des Vorjahres gezahlt hast. Prognose: 88 % dessen, was du für den letzten Zeitraum dieses Jahres erwartest. Kubo nimmt den kleineren Wert.",
  'fisco.metodo-storico': "historisch",
  'fisco.metodo-previsionale': "Prognose",
  'fisco.lipe': "Meldung der periodischen Abrechnungen (LIPE)",
  'fisco.lipe-passo-1': "Lade oben die XML-Datei des Quartals herunter.",
  'fisco.lipe-passo-2': "Melde dich bei „Fatture e Corrispettivi“ auf der Website der Agenzia delle Entrate mit SPID, CIE oder CNS an.",
  'fisco.lipe-passo-3': "Öffne den Dienst für die periodischen MwSt.-Abrechnungen und wähle das Senden einer fertigen Datei.",
  'fisco.lipe-passo-4': "Lade die Datei hoch und bestätige: das System prüft sie sofort.",
  'fisco.lipe-passo-5': "Lade nach ein paar Minuten die Empfangsbestätigung herunter und bewahre sie auf.",
  'fisco.lipe-nota': "Fristen: 31. Mai, 30. September, 30. November und Ende Februar. Wenn etwas nicht passt, hilft die vorausgefüllte Meldung der Agentur beim Vergleichen.",
  'fisco.registri': "MwSt.-Register",
  'fisco.registri-nota': "Die Register für Verkäufe, Einkäufe und Tageseinnahmen sind im Paket für den Steuerberater, als CSV und Excel.",
  'fisco.debito-prec': "Vorschuld {importo}",
  'fisco.credito-prec': "Vorguthaben {importo}",
  'fisco.credito-anno': "Guthaben Vorjahr {importo}",
  'fisco.meno-acconto': "Vorauszahlung {importo}",
  'fisco.non-forfettario': "Das Unternehmen ist nicht in der Pauschalregelung: ändere es in den Einstellungen.",
  'fisco.sim-quanto': "Wenn ich noch einnehme (€)",
  'fisco.sim-esito': "Mit weiteren {piu} zahlst du etwa {tasse} mehr an Steuer und Beiträgen: dir bleiben {resta}.",
  'fisco.niente-acconti': "Keine Vorauszahlung fällig.",
  'fisco.incassato': "Eingenommen",
  'fisco.incassato-nota': "Rechnungen mit „Bezahlt am“ in diesem Jahr",
  'fisco.reddito': "Einkommen",
  'fisco.contributi': "INPS-Beiträge",
  'fisco.imposta': "Ersatzsteuer",
  'fisco.aliquota-n': "Satz {n} %",
  'fisco.soglia': "Grenze von 85.000 €",
  'fisco.soglia-nota': "Du hast {usato} % der Grenze genutzt: es bleiben {margine}. Über 100.000 € fällst du sofort aus der Regelung.",
  'fisco.simulazione': "Simulation",
  'fisco.simula': "Berechnen",
  'fisco.acconti-anno': "Vorauszahlungen {anno}",
  'fisco.acconti-base': "Berechnet auf die Steuer des Vorjahres: {importo}.",
  'fisco.saldo-stima': "Geschätzte Restzahlung im nächsten Jahr: {importo}.",
  'fisco.gestione-artigiani': "INPS Handwerker",
  'fisco.gestione-commercianti': "INPS Händler",
  'fisco.gestione-separata': "Gesonderte Verwaltung",
  'fisco.gestione-cassa': "Berufskasse",
  'fisco.gestione-nessuna': "Keine",
  'fisco.stampa-f24': "F24 drucken",
  'fisco.stampa': "Drucken oder als PDF speichern",
  'fisco.chiudi': "Schließen",
  'fisco.f24-del': "F24 vom {data}",
  'fisco.sezione': "Abschnitt",
  'fisco.rateazione': "Rate / Zeitraum",
  'fisco.sezione-erario': "Fiskus",
  'fisco.sezione-inps': "INPS",
  'fisco.sezione-locali': "Lokale Abgaben",
  'fisco.f24-come': "Übertrage die Zeilen in F24 web (Agenzia delle Entrate) oder ins Online-Banking. Wenn du ein Guthaben verrechnest oder der Saldo null ist, musst du die Dienste der Agentur nutzen.",
  'fisco.registro-ritenute': "Einbehaltene Quellensteuer",
  'fisco.pagata-il': "Bezahlt am",
  'fisco.percipiente': "Empfänger",
  'fisco.compenso': "Honorar",
  'fisco.ritenuta': "Einbehalt",
  'fisco.versare-entro': "Zahlen bis",
  'fisco.ritenute-vuoto': "Keine Quellensteuer: sie wird in den Eingangsrechnungen von Freiberuflern erfasst (Einbehalt und Zahlungsdatum).",
  'fisco.riepilogo-cu': "Übersicht für die CU und das 770",
  'fisco.cf': "Steuernummer",
  'fisco.causale': "Grund",
  'fisco.cu-nota': "Das sind die Daten zum Übertragen: die CU geht bis 16. März an die Empfänger und an die Agentur; das 770 bis 31. Oktober. Kubo reicht sie nicht ein.",
  'fisco.scadenze-anno': "Fristen {anno}",
  'fisco.scadenze-nota': "Nur die Fristen deiner Regelung. Daten an Samstagen oder Feiertagen sind schon auf den nächsten Werktag verschoben.",
  'fisco.dal': "Von",
  'fisco.al': "Bis",
  'fisco.scarica-pacchetto': "Zip herunterladen",
  'fisco.pacchetto': "Paket für den Steuerberater",
  'fisco.pacchetto-cosa': "Ein Zip mit XML-Kopien der ausgestellten Rechnungen, MwSt.-Registern, Abrechnungen, Kassenbuch und Quellensteuer als CSV und Excel und einer PDF-Übersicht.",
  'fisco.quando-professionista': "Wann du wirklich einen Profi brauchst",
  'fisco.pro-dichiarazioni': "Erklärungen (Einkommen, MwSt.-Jahreserklärung, 770) kannst du selbst mit SPID einreichen; soll sie jemand anderes einreichen, braucht es einen zugelassenen Vermittler.",
  'fisco.pro-visto': "Um im F24 ein MwSt.-Guthaben über 5.000 € zu verrechnen, braucht es den Konformitätsvermerk eines Profis.",
  'fisco.pro-consulenza': "Wahl der Regelung, INPS-Ermäßigung um 35 %, Ratenzahlungen, Prüfungen und Bescheide: das ist Beratung, frag einen Steuerberater.",
  'fisco.pro-redditi': "IRPEF, IRES und IRAP in der ordentlichen oder vereinfachten Regelung berechnet der Steuerberater oder die vorausgefüllte Erklärung, nicht Kubo.",
  'fisco.salva': "Speichern",
  'fisco.salvate': "Einstellungen gespeichert",
  'fisco.sezioni': "Bereiche für die Steuern",
  'fisco.sezioni-cosa': "Fügt „Eingangsrechnungen“ (Einkäufe und Quellensteuer) und, wenn du an der Theke verkaufst, „Tageseinnahmen“ hinzu.",
  'fisco.anche-corrispettivi': "Auch die Tageseinnahmen",
  'fisco.aggiungi-sezioni': "Bereiche hinzufügen",
  'fisco.sezioni-aggiunte': "Bereiche hinzugefügt",
  'fisco.manca-piva': "USt-IdNr. oder Steuernummer des Unternehmens fehlen.",
  'fisco.apri-documenti': "In Dokumente ergänzen",
  'fisco.gruppo-regime': "Regelung und Tätigkeit",
  'fisco.gruppo-inps': "INPS-Beiträge",
  'fisco.gruppo-forfettario': "Pauschal",
  'fisco.gruppo-iva': "MwSt.",
  'fisco.gruppo-altro': "Sonstiges",
  'fisco.promemoria': "Steuern: {cosa} am {data}",
  'fisco.imp-regime': "Steuerregelung",
  'fisco.impn-regime': "Wenn du es nicht weißt, frag deinen Steuerberater: diese Wahl ändert alles.",
  'fisco.imp-periodicita': "MwSt.-Abrechnung",
  'fisco.impn-periodicita': "Vierteljährlich mit 1 % Zinsen, wenn dein Umsatz es erlaubt.",
  'fisco.imp-ateco': "ATECO-Code",
  'fisco.impn-ateco': "Steht auf der Bescheinigung zur USt-IdNr.",
  'fisco.imp-coefficiente': "Rentabilitätskoeffizient %",
  'fisco.impn-coefficiente': "Leer: der aus der amtlichen Tabelle für deinen ATECO.",
  'fisco.imp-gestione': "Rentenversicherung",
  'fisco.impn-gestione': "Für Berufskassen berechnet Kubo keine Beiträge.",
  'fisco.imp-riduzione35': "Beitragsermäßigung um 35 %",
  'fisco.impn-riduzione35': "Nur pauschale Handwerker und Händler, die sie bei der INPS beantragt haben.",
  'fisco.imp-ante1996': "Beiträge vor 1996 gezahlt",
  'fisco.impn-ante1996': "Mit Beitragszeiten vor dem 31.12.1995 liegt die Obergrenze bei 93.707 € statt 122.295 €.",
  'fisco.imp-aliquotaridotta': "Satz von 5 % (erste fünf Jahre)",
  'fisco.impn-aliquotaridotta': "Für neue Tätigkeiten mit den gesetzlichen Voraussetzungen; sonst 15 %.",
  'fisco.imp-impostaannoprecedente': "Ersatzsteuer des Vorjahres (€)",
  'fisco.impn-impostaannoprecedente': "Grundlage der Vorauszahlungen. Leer: Kubo berechnet sie aus den Daten.",
  'fisco.imp-accontiversatiannoprecedente': "Im Vorjahr gezahlte Vorauszahlungen (€)",
  'fisco.impn-accontiversatiannoprecedente': "Für die Restzahlung im Juni.",
  'fisco.imp-contributiversati': "In diesem Jahr gezahlte Beiträge (€)",
  'fisco.impn-contributiversati': "Sie werden vom Einkommen abgezogen. Leer: es gilt die Schätzung.",
  'fisco.imp-sedeinps': "INPS-Dienststellencode",
  'fisco.impn-sedeinps': "Für den INPS-Abschnitt des F24.",
  'fisco.imp-matricolainps': "INPS-Nummer",
  'fisco.impn-matricolainps': "In der gesonderten Verwaltung ist es deine Steuernummer.",
  'fisco.imp-creditoannoprecedente': "MwSt.-Guthaben des Vorjahres (€)",
  'fisco.impn-creditoannoprecedente': "Wird in den Abrechnungen genutzt, solange es reicht.",
  'fisco.imp-accontoivastorico': "Für den letzten Zeitraum des Vorjahres gezahlt (€)",
  'fisco.impn-accontoivastorico': "Für die Vorauszahlung nach der historischen Methode.",
  'fisco.imp-accontoivaprevisto': "Erwartet für den letzten Zeitraum dieses Jahres (€)",
  'fisco.impn-accontoivaprevisto': "Für die Prognosemethode. Leer: nur die historische Methode, bis der letzte Zeitraum abgeschlossen ist.",
  'fisco.imp-camerale': "Jahresgebühr der Handelskammer (€)",
  'fisco.impn-camerale': "Den Betrag teilt dir deine Handelskammer mit.",
  'fisco.imp-provinciacciaa': "Provinz der Handelskammer",
  'fisco.impn-provinciacciaa': "Kürzel, zum Beispiel MI.",
  'fisco.imp-bollo': "Virtuelle Stempelsteuer auf Rechnungen",
  'fisco.impn-bollo': "In der Pauschalregelung immer aktiv.",
  'fisco.imp-sostituto': "Ich bin Steuereinbehalter",
  'fisco.impn-sostituto': "Du bezahlst Freiberufler und behältst die Steuer ein.",
  'fisco.v-iva': "MwSt. für Zeitraum {periodo}",
  'fisco.v-iva-saldo': "MwSt.-Jahresrestzahlung",
  'fisco.v-iva-acconto': "MwSt.-Vorauszahlung",
  'fisco.v-forf-saldo': "Restzahlung Ersatzsteuer {anno}",
  'fisco.v-forf-acconto': "Vorauszahlung Ersatzsteuer {anno}",
  'fisco.v-inps-acconto': "Vorauszahlung INPS-Beiträge {anno}",
  'fisco.v-inps-fissi': "Feste INPS-Beiträge",
  'fisco.v-iva-integrazioni': "MwSt. der Ergänzungen, Monat {periodo}",
  'fisco.v-bollo': "Virtuelle Stempelsteuer, {periodo}. Quartal",
  'fisco.v-ritenute': "Quellensteuer für Monat {periodo}",
  'fisco.v-camerale': "Handelskammergebühr {anno}",
  'fisco.sc-iva-mese': "MwSt.-Zahlung für Monat {periodo}",
  'fisco.sc-iva-trimestre': "MwSt.-Zahlung für das {periodo}. Quartal",
  'fisco.sc-iva-saldo': "MwSt.-Jahresrestzahlung",
  'fisco.sc-iva-acconto': "MwSt.-Vorauszahlung",
  'fisco.sc-lipe': "LIPE für das {periodo}. Quartal",
  'fisco.sc-dichiarazione-iva': "MwSt.-Erklärung {anno}",
  'fisco.sc-forf-saldo-acconto': "Restzahlung und erste Vorauszahlung der Ersatzsteuer",
  'fisco.sc-redditi-saldo-acconto': "Restzahlung und erste Vorauszahlung der Einkommensteuern",
  'fisco.sc-forf-acconto2': "Zweite Vorauszahlung der Ersatzsteuer",
  'fisco.sc-redditi-acconto2': "Zweite Vorauszahlung der Einkommensteuern",
  'fisco.sc-dichiarazione-redditi': "Einkommensteuererklärung {anno}",
  'fisco.sc-inps-fissi': "Feste INPS-Beiträge, Rate {periodo}",
  'fisco.sc-inps-saldo-acconto': "INPS-Beiträge: Restzahlung und Vorauszahlung",
  'fisco.sc-inps-riduzione': "Antrag auf INPS-Ermäßigung um 35 %",
  'fisco.sc-bollo': "Virtuelle Stempelsteuer, {periodo}. Quartal {anno}",
  'fisco.sc-ritenute': "Quellensteuer für Monat {periodo}",
  'fisco.sc-cu-consegna': "CU an die Empfänger",
  'fisco.sc-cu-invio': "CU an die Agentur (Selbstständige)",
  'fisco.sc-modello-770': "Modell 770",
  'fisco.sc-camerale': "Handelskammergebühr",
  'fisco.av-da-integrare': "Einige Eingangsrechnungen mit Reverse Charge oder aus dem Ausland müssen noch ergänzt werden: Bis du die Ergänzung ausstellst (TD16-TD19, unter E-Rechnungen), stehen sie nicht in den MwSt.-Registern.",
  'fisco.av-vicino-85': "Du bist nahe an der Grenze von 85.000 €: wenn du sie überschreitest, fällst du nächstes Jahr aus der Pauschalregelung.",
  'fisco.av-oltre-85': "Du hast 85.000 € überschritten: nächstes Jahr fällst du aus der Pauschalregelung. Sprich mit einem Steuerberater.",
  'fisco.av-oltre-100': "Du hast 100.000 € überschritten: du fällst sofort aus der Pauschalregelung, mit MwSt. ab dem Geschäft, das die Grenze überschritten hat. Du brauchst einen Steuerberater.",
  'fisco.av-fuori-dal-regime': "Im Vorjahr hast du mehr als 85.000 € eingenommen: dieses Jahr dürftest du nicht in der Pauschalregelung sein. Prüfe es mit einem Steuerberater.",
  'fisco.av-contributi-stimati': "Die abgezogenen Beiträge sind geschätzt: trage in den Einstellungen die tatsächlich gezahlten ein.",
  'fisco.av-cassa-professionale': "Bei einer Berufskasse berechnet die Kasse die Beiträge: Kubo zählt sie nicht.",
  'fisco.av-incassi-senza-data': "Einige bezahlte Rechnungen haben kein „Bezahlt am“: sie zählen zum Rechnungsdatum.",
  'fisco.av-visto-conformita': "Das MwSt.-Guthaben übersteigt 5.000 €: um es im F24 zu verrechnen, braucht es den Konformitätsvermerk.",
  'fisco.av-forfettario-niente-iva': "In der Pauschalregelung gibt es keine MwSt. abzurechnen und keine LIPE: sieh dir das Pauschal-Cockpit an.",
  'fisco.av-redditi-professionista': "IRPEF, IRES und IRAP sind nicht hier: sie berechnet der Steuerberater oder die vorausgefüllte Erklärung.",
  'fisco.av-inps-cassetto': "Die festen INPS-Raten sind eine Schätzung: das amtliche F24 liegt im Cassetto previdenziale.",
  'fisco.av-cu-intermediario': "Ab 20 CU reichen deine Zugangsdaten nicht: es braucht Entratel oder einen Vermittler.",
  'fisco.av-cu-fisconline': "Mit weniger als 20 CU kannst du sie selbst mit deinen Zugangsdaten einreichen.",
  'fisco.imp-anno-rif': "Die Werte „des Vorjahres“ gelten für die Zahlen von {anno}: aktualisiere sie zu Jahresbeginn. Für andere Jahre nutzt Kubo die Daten.",
};
