export default {
  'gestione.tipo-testo': 'Text',
  'gestione.tipo-testo_lungo': 'Langer Text',
  'gestione.tipo-numero': 'Zahl',
  'gestione.tipo-valuta': 'Betrag ({simbolo})',
  'gestione.tipo-percentuale': 'Prozent',
  'gestione.tipo-data': 'Datum',
  'gestione.tipo-data_ora': 'Datum und Uhrzeit',
  'gestione.tipo-si_no': 'Ja / Nein',
  'gestione.tipo-scelta': 'Auswahl',
  'gestione.tipo-scelta_multipla': 'Mehrfachauswahl',
  'gestione.tipo-stato': 'Status (Ablauf)',
  'gestione.tipo-relazione': 'Verknüpfung',
  'gestione.tipo-righe': 'Positionen (Untertabelle)',
  'gestione.tipo-calcolato': 'Berechnet (Formel)',
  'gestione.tipo-contatore': 'Nummerierung',
  'gestione.tipo-email': 'E-Mail',
  'gestione.tipo-telefono': 'Telefon',
  'gestione.tipo-url': 'Website',
  'gestione.tipo-indirizzo': 'Adresse',
  'gestione.tipo-codice_a_barre': 'Barcode',
  'gestione.tipo-durata': 'Dauer (Minuten)',
  'gestione.tipo-immagine': 'Bild',
  'gestione.tipo-file': 'Datei',
  'gestione.nome': 'Name',
  'gestione.esempio-sezione': 'z. B. Vermietungen',
  'gestione.archivia-campo': 'Feld archivieren (die Werte bleiben erhalten)',
  'gestione.obbligatorio': 'Pflichtfeld',
  'gestione.senza-doppioni': 'Keine Dubletten',
  'gestione.prima-opzione': 'Erste Option',
  'gestione.opzioni': 'Optionen, eine pro Zeile (Farben: {colori})',
  'gestione.righe-di': 'Positionen von',
  'gestione.collegato-a': 'Verknüpft mit',
  'gestione.piu-di-uno': 'Mehrere',
  'gestione.campo-punta': 'Feld, das hierher zeigt (in der anderen Entität)',
  'gestione.formula': 'Formel (z. B. menge * preis · SUMME(positionen.gesamt) · WENN(bestand <= mindestbestand; "ja"; "nein"))',
  'gestione.mostra-come': 'Anzeigen als',
  'gestione.automatico': 'Automatisch',
  'gestione.importo': 'Betrag',
  'gestione.formato-contatore': 'Format ({AAAA} Jahr, {N:4} vierstellige Nummer)',
  'gestione.salva-modifiche': 'Änderungen speichern',
  'gestione.dai-nome': 'Gib einen Namen ein',
  'gestione.piu-campo': '+ Feld',
  'gestione.personalizza-nome': 'Anpassen · {nome}',
  'gestione.icona': 'Symbol',
  'gestione.nome-elemento': 'Name jedes Eintrags',
  'gestione.nota-dati': 'Umbenennen und Verschieben ändern keine Daten. Ein entferntes Feld wird mit seinen Werten archiviert und lässt sich wiederherstellen. Würde eine Typänderung Werte verlieren, bricht das Speichern ab und zeigt dir, welche.',
  'gestione.password-8': 'Passwort (8+)',
  'gestione.aggiungi': 'Hinzufügen',
  'gestione.aggiunto': 'Hinzugefügt',
  'gestione.ruolo-cambiato': 'Rolle geändert',
  'gestione.disattiva': 'Deaktivieren',
  'gestione.riattiva': 'Reaktivieren',
  'gestione.ruolo': 'Rolle',
  'gestione.nuova-persona': 'Neue Person',
  'gestione.ruoli': 'Rollen',
  'gestione.nota-ruoli': 'Der Inhaber darf alles. Für die anderen Rollen legst du Bereich für Bereich fest, was sie dürfen.',
  'gestione.nuovo-ruolo': '+ Neue Rolle',
  'gestione.nome-ruolo': 'Name der Rolle (z. B. Theke, Werkstatt)',
  'gestione.vede': 'Sieht',
  'gestione.modifica': 'Bearbeitet',
  'gestione.campi-nascosti-ruolo': 'Für diese Rolle ausgeblendete Felder',
  'gestione.salva-ruolo': 'Rolle speichern',
  'gestione.ruolo-salvato': 'Rolle gespeichert',
  'gestione.puo-personalizzare': 'Darf anpassen',
  'gestione.sezione': 'Bereich',
  'gestione.campi-nascosti': 'Ausgeblendete Felder (⌘/Strg für mehrere)',
  'gestione.ruolo-titolare': 'Inhaber',
  'gestione.ruolo-collaboratore': 'Mitarbeiter',
  'gestione.ruolo-lettura': 'Nur lesen',
  'gestione.lingua-valuta': 'Sprache und Währung',
  'gestione.tua-lingua': 'Deine Sprache',
  'gestione.tua-lingua-nota': 'Gilt nur für dich, auf allen Geräten.',
  'gestione.azienda': 'Für das ganze Unternehmen',
  'gestione.lingua-modelli': 'Sprache neuer Vorlagen',
  'gestione.lingua-modelli-nota': 'Vorlagen, die du ab jetzt hinzufügst, kommen mit Namen in dieser Sprache. Bestehende Bereiche ändern sich nicht.',
  'gestione.valuta-nota': 'Beträge werden in dieser Währung angezeigt. Gespeicherte Werte ändern sich nicht: nur Symbol und Format.',
  'gestione.esempio': 'So sieht es aus: {numero} · {soldi} · {data}',
  'gestione.salvato-ricarico': 'Gespeichert: Die Seite wird neu geladen',
  'gestione.settimana-da': 'Die Woche beginnt am {giorno}.',
};
