// Lager (web/moduli/magazzino.js): Wert, Inventur, Bewegungen.
export default {
  'magazzino.titolo': "Lager",
  'magazzino.scheda-valore': "Wert",
  'magazzino.scheda-inventario': "Inventur",
  'magazzino.scheda-movimenti': "Bewegungen",
  'magazzino.sezione': "Lagerbereich",
  'magazzino.nessuna-sezione': "Kein Bereich mit Lagerbestand: Füge den Artikeln das Feld „giacenza“ hinzu.",
  'magazzino.valore': "Wert",
  'magazzino.al-costo': "zu Artikelkosten",
  'magazzino.pezzi': "Stück",
  'magazzino.articoli-n': {"one": "{n} Artikel", "other": "{n} Artikel"},
  'magazzino.sotto-scorta': "Unter Mindestbestand",
  'magazzino.negativi': {"one": "{n} Artikel mit negativem Bestand: {nomi}", "other": "{n} Artikel mit negativem Bestand: {nomi}"},
  'magazzino.senza-costo': {"one": "{n} Artikel im Bestand hat keine Kosten: Er fehlt im Wert.", "other": "{n} Artikel im Bestand haben keine Kosten: Sie fehlen im Wert."},
  'magazzino.per-categoria': "Nach Kategorie",
  'magazzino.categoria': "Kategorie",
  'magazzino.articoli': "Artikel",
  'magazzino.senza-categoria': "Ohne Kategorie",
  'magazzino.per-articolo': "Nach Artikel",
  'magazzino.codice': "Code",
  'magazzino.articolo': "Artikel",
  'magazzino.giacenza': "Bestand",
  'magazzino.costo': "Kosten",
  'magazzino.scarica-csv': "Als CSV herunterladen",
  'magazzino.nota-valore': "Der Wert ist Bestand × Kosten. Der Einkauf hält die Kosten auf dem gewichteten Durchschnitt. Das ist der Inventurwert für die Steuerberatung.",
  'magazzino.inventario-nota': "Zähle die Ware im Regal: Die aktuellen Bestände bleiben als Referenz, und beim Abschluss wird jeder gezählte Artikel um die Differenz korrigiert. Verkäufe während des Zählens bleiben richtig.",
  'magazzino.continua': "„{nome}“ fortsetzen",
  'magazzino.nuovo-inventario': "Inventur beginnen",
  'magazzino.inventari': "Inventuren",
  'magazzino.nome': "Name",
  'magazzino.iniziato': "Begonnen",
  'magazzino.contati': "Gezählt",
  'magazzino.stato': "Status",
  'magazzino.chiuso-il': "Abgeschlossen am {data}",
  'magazzino.aperto': "Offen",
  'magazzino.leggi-codice': "Code scannen (Scanner oder Tastatur, dann Enter)",
  'magazzino.letto': "{nome}: {n}",
  'magazzino.cerca': "Artikel oder Code suchen",
  'magazzino.attesa': "Erwartet",
  'magazzino.contata': "Gezählt",
  'magazzino.differenza': "Differenz",
  'magazzino.chiudi-conferma': {"one": "Inventur abschließen? {n} Bestand wird korrigiert.", "other": "Inventur abschließen? {n} Bestände werden korrigiert."},
  'magazzino.chiuso': {"one": "Inventur abgeschlossen: {n} Korrektur, {importo}", "other": "Inventur abgeschlossen: {n} Korrekturen, {importo}"},
  'magazzino.differenze': "Differenzen",
  'magazzino.valore-differenze': "Wert der Differenzen",
  'magazzino.chiudi': "Inventur abschließen",
  'magazzino.chiudi-nota': "Nicht gezählte Artikel bleiben, wie sie sind.",
  'magazzino.quando': "Wann",
  'magazzino.movimento': "Bewegung",
  'magazzino.origine': "Herkunft",
  'magazzino.chi': "Wer",
  'magazzino.origine-iniziale': "Anfangsbestand",
  'magazzino.origine-modifica': "Änderung",
  'magazzino.origine-automazione': "Automatisch (Verkäufe, Bestellungen, Verbrauch)",
  'magazzino.origine-inventario': "Inventur",
  'magazzino.niente-movimenti': "Noch keine Bewegungen.",
  'magazzino.nota-movimenti': "Jede Bestandsänderung landet von selbst hier, egal woher: Karten, Verkäufe, gelieferte Bestellungen, Importe, Inventuren.",
};
