export default {
  'moduli.lumi-serve-chiave': "Zum Antworten brauche ich den Claude-Schlüssel. Ich öffne dir **Verwaltung → Lumi**: Das dauert eine Minute.",
  'moduli.lumi-serve-chiave-spento': "Zum Antworten brauche ich den Claude-Schlüssel, und du musst mich wieder einschalten. Ich öffne dir **Verwaltung → Lumi**: Das dauert eine Minute.",
  'moduli.lumi-chiedi-titolare': "Zum Antworten brauche ich den Claude-Schlüssel: Bitte den Inhaber, ihn unter **Verwaltung → Lumi** einzutragen.",
  'moduli.lumi-spento': "Lumi ist aus: Unter Verwaltung → Lumi schaltest du es wieder ein.",
  'moduli.lumi-file-pronto': 'Datei bereit: {nome}',
  'moduli.lumi-quasi-pronto': "Lumi ist fast bereit: Der Claude-Schlüssel fehlt.",
  'moduli.lumi-apri': "Öffnen",
  'moduli.lumi-settimana': "Wie läuft die Woche",
  'moduli.lumi-settimana-domanda': "Wie lief diese Woche? Gib mir die wichtigsten Zahlen.",
  'moduli.lumi-accendi': "Lumi einschalten",
  'moduli.lumi-solo-titolare': "Die Einstellungen von Lumi sind Sache des Inhabers.",
  'moduli.lumi-gia-salvata': "•••••••• (bereits gespeichert)",
  'moduli.lumi-stato-spento': "Aus",
  'moduli.lumi-stato-acceso': "An",
  'moduli.lumi-stato-manca': "Schlüssel fehlt",
  'moduli.lumi-fonte-ambiente': "Der Schlüssel kommt aus der Variable ANTHROPIC_API_KEY des Servers.",
  'moduli.lumi-fonte-file': "Schlüssel auf diesem Computer gespeichert.",
  'moduli.lumi-cos-e': "Lumi ist der Assistent von Kubo. Du sprichst oder schreibst mit ihm über die Pille oben: Er sucht, zählt, legt Datensätze an und ändert die Form des Systems. Jede Änderung wartet auf dein „Bestätigen“, und jeder sieht nur, was seine Rechte erlauben.",
  'moduli.lumi-chiave': "Claude-Schlüssel",
  'moduli.lumi-salva-chiave': "Schlüssel speichern",
  'moduli.lumi-incolla': "Füge den Schlüssel ein",
  'moduli.lumi-togliere': "Schlüssel entfernen? Lumi antwortet dann nicht mehr.",
  'moduli.lumi-dove-chiave': "Du erstellst ihn auf console.anthropic.com unter API Keys. Er bleibt auf diesem Computer, in einer Datei neben den Daten, die nur Kubo liest, und erreicht nie die Browser.",
  'moduli.lumi-acceso': "Lumi an",
  'moduli.lumi-limite': "Fragen pro Minute und Person",
  'moduli.lumi-da-provare': "Zum Ausprobieren",
  'moduli.lumi-esempio-1': "Wie viel habe ich diese Woche verkauft?",
  'moduli.lumi-esempio-2': "Was muss ich nachbestellen?",
  'moduli.lumi-esempio-3': "Füge den Artikeln die Größe hinzu, mit S, M, L und XL",
  'moduli.lumi-esempio-4': "Leg mir einen Bereich für Vermietungen an, mit Kunde, Gerät, von, bis und Status",
  'moduli.lumi-esempio-5': "Wenn eine Vermietung auf zurückgegeben wechselt, sag mir Bescheid",
  'moduli.lumi-modello': "Modell: {modello}.",
  'moduli.lumi-voce-accesa': "Echtzeit-Sprache an.",
  'moduli.lumi-voce-browser': "Sprache: die des Browsers, wo vorhanden.",
  'moduli.lumi-voce-locale': "Lokale Spracherkennung: Parakeet versteht auf diesem Computer 25 europäische Sprachen, und das Audio verlässt das Unternehmen nicht.",
  'moduli.ag-adesso': "gerade eben",
  'moduli.ag-agenda': "Kalender",
  'moduli.ag-calendario': "Kalenderansicht",
  'moduli.ag-cruscotto': "Dashboard",
  'moduli.ag-aggiungi-voce': "Eintrag hinzufügen",
  'moduli.ag-altri': {"one": "+{n} weiterer", "other": "+{n} weitere"},
  'moduli.ag-e-altri': {"one": "und ein weiterer", "other": "und {n} weitere"},
  'moduli.ag-aria-grafico': "{titolo}: Diagramm",
  'moduli.ag-barre': "Balken",
  'moduli.ag-linea': "Linie",
  'moduli.ag-buongiorno': "Guten Morgen",
  'moduli.ag-buon-pomeriggio': "Guten Tag",
  'moduli.ag-buonasera': "Guten Abend",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Ändern",
  'moduli.ag-cambia-widget': "Widget ändern",
  'moduli.ag-nuovo-widget': "Neues Widget",
  'moduli.ag-campo': "Feld",
  'moduli.ag-colonne-per': "Spalten: {nome}",
  'moduli.ag-una-colonna': "Eine Spalte",
  'moduli.ag-come-oggi': "wie gestern",
  'moduli.ag-come-settimana': "wie letzte Woche",
  'moduli.ag-come-mese': "wie letzten Monat",
  'moduli.ag-come-anno': "wie letztes Jahr",
  'moduli.ag-rispetto-oggi': "{diff} gegenüber gestern ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} gegenüber letzter Woche ({prima})",
  'moduli.ag-rispetto-mese': "{diff} gegenüber letztem Monat ({prima})",
  'moduli.ag-rispetto-anno': "{diff} gegenüber letztem Jahr ({prima})",
  'moduli.ag-data-rif': "Bezugsdatum",
  'moduli.ag-prima': "Zurück",
  'moduli.ag-dopo': "Weiter",
  'moduli.ag-fatto': "Fertig",
  'moduli.ag-forma': "Darstellung",
  'moduli.ag-ha-creato': "hat angelegt:",
  'moduli.ag-ha-modificato': "hat bearbeitet:",
  'moduli.ag-ha-archiviato': "hat archiviert:",
  'moduli.ag-ha-ripristinato': "hat wiederhergestellt:",
  'moduli.ag-in-sezione': "in {nome}",
  'moduli.ag-un-elemento': "einen Eintrag",
  'moduli.ag-lista': "Liste",
  'moduli.ag-torna-lista': "Zurück zur Liste",
  'moduli.ag-media': "Durchschnitt von…",
  'moduli.ag-somma': "Summe von…",
  'moduli.ag-quanti': "Anzahl",
  'moduli.ag-misura': "Kennzahl",
  'moduli.ag-modifica': "Bearbeiten",
  'moduli.ag-nome-voce': "Name des Eintrags",
  'moduli.ag-nuova-voce': "Neuer Eintrag",
  'moduli.ag-un-filtro': "Gib dem Eintrag mindestens einen Filter",
  'moduli.ag-non-disegno': "Das lässt sich nicht darstellen",
  'moduli.ag-oggi': "Heute",
  'moduli.ag-per': "Nach",
  'moduli.ag-periodo': "Zeitraum",
  'moduli.ag-periodo-oggi': "Heute",
  'moduli.ag-periodo-settimana': "Diese Woche",
  'moduli.ag-periodo-mese': "Dieser Monat",
  'moduli.ag-periodo-anno': "Dieses Jahr",
  'moduli.ag-periodo-ultimi_7': "Letzte 7 Tage",
  'moduli.ag-periodo-ultimi_30': "Letzte 30 Tage",
  'moduli.ag-periodo-ultimi_84': "Letzte 12 Wochen",
  'moduli.ag-periodo-ultimi_365': "Letztes Jahr",
  'moduli.ag-periodo-sempre': "Gesamt",
  'moduli.ag-piede-grafico': "{periodo} · insgesamt {totale}",
  'moduli.ag-piu-aggiungi': "+ Hinzufügen",
  'moduli.ag-quale-data': "Welches Datum",
  'moduli.ag-senza-titolo': "Ohne Titel",
  'moduli.ag-spostato': "Verschoben",
  'moduli.ag-tipo': "Typ",
  'moduli.ag-titolo': "Titel",
  'moduli.ag-titolo-widget': "Gib dem Widget einen Titel",
  'moduli.ag-tutti': "alle",
  'moduli.ag-utente-non-attivo': "Inaktiver Benutzer",
  'moduli.ag-vedi-calendario': "Im Kalender ansehen",
  'moduli.ag-vedi-elenco': "Liste ansehen",
  'moduli.ag-vedi-giorno': "Tag ansehen",
  'moduli.ag-vista-giorno': "Tag",
  'moduli.ag-vista-settimana': "Woche",
  'moduli.ag-vista-mese': "Monat",
  'moduli.ag-w-numero': "Zahl",
  'moduli.ag-w-grafico': "Diagramm",
  'moduli.ag-w-attenzione': "Braucht Aufmerksamkeit",
  'moduli.ag-w-ultime': "Letzte Änderungen",
  'moduli.ag-def-incassato-oggi': "Heute eingenommen",
  'moduli.ag-def-incassato-mese': "Diesen Monat eingenommen",
  'moduli.ag-def-vendite-oggi': "Verkäufe heute",
  'moduli.ag-def-incassi-30': "Einnahmen der letzten 30 Tage",
  'moduli.ag-def-appuntamenti-oggi': "Termine heute",
  'moduli.ag-def-appuntamenti-settimana': "Termine pro Woche",
  'moduli.ag-def-preventivi-attesa': "Offene Angebote",
  'moduli.ag-def-commesse-aperte': "Offene Aufträge",
  'moduli.ag-def-accettato-mese': "Diesen Monat angenommen",
  'moduli.ag-def-preventivi-mese': "Angenommene Angebote pro Monat",
  'moduli.ag-def-articoli-riordinare': "Nachzubestellende Artikel",
  'moduli.ag-def-materiali-riordinare': "Nachzubestellendes Material",
  'moduli.ag-def-ordini-ritardo': "Verspätete Bestellungen",
  'moduli.ag-def-vendite-aperte': "Seit über 2 Tagen offene Verkäufe",
  'moduli.ag-def-commesse-ritardo': "Verspätete Aufträge",
  'moduli.ag-def-preventivi-senza-risposta': "Angebote seit 7 Tagen ohne Antwort",
  'moduli.ag-def-appuntamenti-chiudere': "Vergangene Termine zum Abschließen",
  'moduli.ag-def-pacchetti-scaduti': "Abgelaufene Pakete mit Sitzungen",
  'moduli.ag-def-attenzione': "Braucht Aufmerksamkeit",
  'moduli.ag-def-ultime': "Letzte Änderungen",
  'moduli.ag-def-nuovi-mese': "{nome}: neu diesen Monat",
  'moduli.ag-tutto-ok': "✓ Alles in Ordnung: nichts zu erledigen.",
  'moduli.ag-nessuna-modifica': "Noch keine Änderungen.",
  'moduli.ag-es-titolo': "Z. B. Heute eingenommen",
  'moduli.im-menu': "Aus einer Tabelle importieren oder die Liste mit den aktuellen Filtern exportieren",
  'moduli.im-importa-da': "Aus Excel oder CSV importieren…",
  'moduli.im-esporta-xlsx': "Nach Excel exportieren (.xlsx)",
  'moduli.im-esporta-csv': "Als CSV exportieren",
  'moduli.im-nuova-dal-foglio': "+ Ein neuer Bereich aus der Tabelle",
  'moduli.im-scegli-file': "Wähle eine Excel- (.xlsx) oder CSV-Datei",
  'moduli.im-trascina': "oder hierher ziehen. Die erste Zeile muss die Spaltennamen enthalten.",
  'moduli.im-esporta-tutto': "Alles exportieren",
  'moduli.im-backup': "Vollständige Sicherung",
  'moduli.im-backup-nota': "Ein Zip mit einer Kopie der Datenbank (konsistent, auch während gearbeitet wird) und den Anhängen. Bewahre es auf einer externen Festplatte oder in deiner eigenen Cloud auf.",
  'moduli.im-scarica-backup': "Sicherung herunterladen",
  'moduli.im-importa-esporta': "Import und Export",
  'moduli.im-api': "API und Integrationen",
  'moduli.im-dati': "Daten",
  'moduli.im-dove': "Wohin die Zeilen kommen",
  'moduli.im-non-importare': "— nicht importieren",
  'moduli.im-crea-campo': "+ Feld „{nome}“ anlegen ({tipo})",
  'moduli.im-non-controllare': "Nicht prüfen: jede Zeile ist neu",
  'moduli.im-stesso': "Gleiches Feld „{nome}“",
  'moduli.im-stesso-unico': "Gleiches Feld „{nome}“ (keine Dubletten)",
  'moduli.im-aggiorna': "die vorhandene aktualisieren",
  'moduli.im-salta': "in Ruhe lassen, Zeile überspringen",
  'moduli.im-controllo': "Wird geprüft…",
  'moduli.im-importo': "Wird importiert…",
  'moduli.im-importato': "Importiert",
  'moduli.im-prova': "Testen ohne Speichern",
  'moduli.im-importa-n': {"one": "{n} Zeile importieren", "other": "{n} Zeilen importieren"},
  'moduli.im-righe-in': {"one": "{n} Zeile in „{file}“", "other": "{n} Zeilen in „{file}“"},
  'moduli.im-riga': "Zeile",
  'moduli.im-errore': "Fehler",
  'moduli.im-file-errori': "zu korrigierende Zeilen.csv",
  'moduli.im-prova-esito': "Test: Nichts wurde gespeichert",
  'moduli.im-esito-create': {"one": "angelegt", "other": "angelegt"},
  'moduli.im-esito-aggiornate': {"one": "aktualisiert", "other": "aktualisiert"},
  'moduli.im-esito-saltate': {"one": "übersprungen", "other": "übersprungen"},
  'moduli.im-esito-errori': "mit Fehlern",
  'moduli.im-cosa-non-va': "Was nicht stimmt",
  'moduli.im-e-altre': {"one": "…und eine weitere.", "other": "…und {n} weitere."},
  'moduli.im-scarica-errori': "Fehlerhafte Zeilen herunterladen (.csv)",
  'moduli.im-correggi': "Korrigiere sie in der Datei und importiere sie erneut: Mit der Dublettenprüfung wird nichts doppelt angelegt.",
  'moduli.im-vai-a': "Zu {nome}",
  'moduli.im-abbina': "Ordne die Spalten den Feldern von {nome} zu. Die ersten Zeilen:",
  'moduli.im-ogni-colonna': "Jede Spalte wird zu einem Feld: Prüfe Namen und Typen.",
  'moduli.im-nome-sezione': "Name des neuen Bereichs",
  'moduli.im-gia-presenti': "Bereits vorhandene Zeilen",
  'moduli.im-se-trovo': "wenn ich sie finde:",
  'moduli.im-formati': "Zahlen wie „1.234,50“ oder „12 €“, Datumsangaben wie „31.12.2026“ und „1 / 0“ oder „yes / no“ werden akzeptiert. Leere Zellen löschen nichts.",
  'moduli.doc-campo-ragione_sociale': "Firmenbezeichnung",
  'moduli.doc-campo-piva': "USt-IdNr.",
  'moduli.doc-campo-codice_fiscale': "Steuernummer",
  'moduli.doc-campo-regime': "Steuerregelung",
  'moduli.doc-campo-via': "Adresse (Straße und Hausnummer)",
  'moduli.doc-campo-cap': "PLZ",
  'moduli.doc-campo-comune': "Ort",
  'moduli.doc-campo-provincia': "Provinz (Kürzel)",
  'moduli.doc-campo-telefono': "Telefon",
  'moduli.doc-campo-email': "E-Mail",
  'moduli.doc-campo-pec': "PEC",
  'moduli.doc-campo-codice_destinatario': "Dein Empfängercode",
  'moduli.doc-campo-iban': "IBAN",
  'moduli.doc-campo-banca': "Bank",
  'moduli.doc-campo-aliquota': "Standard-MwSt. %",
  'moduli.doc-campo-colore': "Farbe der Dokumente",
  'moduli.doc-chiudi': "Schließen (Esc)",
  'moduli.doc-anteprima': "Druckvorschau",
  'moduli.doc-stampa-pdf': "Drucken oder als PDF speichern",
  'moduli.doc-modifica-modello': "Vorlage bearbeiten",
  'moduli.doc-xml-manca': "Vor der XML-Datei fehlt noch etwas",
  'moduli.doc-sistema': "Behebe diese Punkte und versuche es erneut:",
  'moduli.doc-apri-dati': "Unternehmensdaten öffnen",
  'moduli.doc-scaricato': "{nome} heruntergeladen: Lade es jetzt im Portal deines Dienstleisters oder bei Fatture e Corrispettivi hoch",
  'moduli.doc-dati-azienda': "Unternehmensdaten",
  'moduli.doc-modelli-stampa': "Druckvorlagen",
  'moduli.doc-documenti': "Dokumente",
  'moduli.doc-dati-salvati': "Unternehmensdaten gespeichert",
  'moduli.doc-logo': "Logo",
  'moduli.doc-nessun-logo': "Kein Logo",
  'moduli.doc-logo-tipo': "Das Logo muss ein PNG oder JPEG sein",
  'moduli.doc-logo-grande': "Das Logo ist zu groß: höchstens 300 KB",
  'moduli.doc-logo-caricato': "Logo hochgeladen",
  'moduli.doc-carica-logo': "Logo hochladen",
  'moduli.doc-logo-nota': "PNG oder JPEG, höchstens 300 KB. Es steht oben auf jedem Dokument.",
  'moduli.doc-indirizzo-completo': "Vollständige Adresse",
  'moduli.doc-fattura-elettronica': "E-Rechnung (Italien)",
  'moduli.doc-fatturapa-nota': "Kubo erstellt die FatturaPA-Datei (XML). Um sie an das SDI zu senden, lade sie im Portal Fatture e Corrispettivi der Agenzia delle Entrate oder bei deinem Dienstleister hoch: Die Schritte stehen in docs/DOCUMENTI.md.",
  'moduli.doc-nessuna-stampa': "Kein Bereich mit Positionen zum Drucken. Füge eine Vorlage hinzu (Laden, Werkstatt, Rechnungen) oder einen Bereich mit Positionen.",
  'moduli.doc-elenco-nota': "Jeder Bereich mit Positionen hat sein A4-Dokument. Ändere Texte, Spalten und Fußzeile: Die Vorschau aktualisiert sich beim Tippen.",
  'moduli.doc-documento': "Dokument",
  'moduli.doc-modello': "Vorlage",
  'moduli.doc-personalizzato': "angepasst",
  'moduli.doc-predefinito': "Standard",
  'moduli.doc-sinistra': "links",
  'moduli.doc-destra': "rechts",
  'moduli.doc-salva-modello': "Vorlage speichern",
  'moduli.doc-modello-salvato': "Vorlage gespeichert",
  'moduli.doc-torna-predefinito': "Auf Standard zurücksetzen",
  'moduli.doc-torna-conferma': "Zur Standardvorlage zurück? Die Änderungen an dieser Vorlage gehen verloren.",
  'moduli.doc-modello-predefinito': "Standardvorlage",
  'moduli.doc-crea-uno': "Lege mindestens ein Dokument in {nome} an, um die Vorschau zu sehen.",
  'moduli.doc-segnaposto': "Platzhalter, die du verwenden kannst",
  'moduli.doc-seg-campi': "Felder des Dokuments: ",
  'moduli.doc-seg-collegati': "Verknüpft (jedes ihrer Felder): ",
  'moduli.doc-seg-azienda': "Dein Unternehmen: ",
  'moduli.doc-seg-colonne': "In den Spalten, jede Position: ",
  'moduli.doc-seg-campi-riga': " und die Felder der Position: ",
  'moduli.doc-seg-totali': "Summen: ",
  'moduli.doc-seg-oggi': " · heute: ",
  'moduli.doc-seg-se': "Ein Teil, der nur erscheint, wenn das Feld ausgefüllt ist: ",
  'moduli.doc-seg-se-manca': "; nur wenn es leer ist: ",
  'moduli.doc-ed-titolo': "Titel des Dokuments",
  'moduli.doc-ed-sopra-destinatario': "Über dem Empfänger",
  'moduli.doc-ed-destinatario': "Empfänger",
  'moduli.doc-ed-dettagli': "Details oben rechts",
  'moduli.doc-ed-colonne': "Spalten der Positionen",
  'moduli.doc-ed-riepilogo-iva': "MwSt.-Übersicht nach Satz",
  'moduli.doc-ed-prezzi-ivati': "Die Preise enthalten MwSt.",
  'moduli.doc-ed-note': "Notizen",
  'moduli.doc-ed-pagamento': "Zahlung",
  'moduli.doc-ed-piede': "Fußzeile",
  'moduli.doc-ed-colore-label': "Farbe",
  'moduli.doc-ed-colore-azienda': "die des Unternehmens",
  'moduli.doc-crea-fattura': "Rechnung erstellen",
  'moduli.doc-crea-fattura-nota': "Ein Rechnungsentwurf mit Kunde und Positionen dieses Dokuments",
  'moduli.doc-fattura-creata': "Rechnungsentwurf erstellt",
  'moduli.doc-nota-credito': "Gutschrift",
  'moduli.doc-nota-credito-nota': "Diese Rechnung mit einem Gutschriftentwurf stornieren",
  'moduli.doc-nota-conferma': "Eine Gutschrift erstellen, die Rechnung {numero} storniert?",
  'moduli.doc-nota-creata': "Gutschriftentwurf erstellt",
  'moduli.doc-fatturapa-titolo': "XML-Datei für das SDI prüfen und herunterladen",
  'moduli.doc-stampa-titolo': "Vorschau, Druck und PDF",
  'moduli.doc-stampa': "Drucken",
  'moduli.im-scarica-modello': "Vorlage zum Ausfüllen herunterladen",
  'moduli.api-f-valuta': "Zahl (19.9)",
  'moduli.api-f-data': "JJJJ-MM-TT",
  'moduli.api-f-uno-fra': "einer von: {fra}",
  'moduli.api-f-multipla': "Liste von Options-IDs",
  'moduli.api-f-rel-molti': "Liste von IDs aus {entita}",
  'moduli.api-f-rel': "ID aus {entita} (beim Lesen { id, titolo })",
  'moduli.api-f-righe': "Liste von Positionen aus {entita}",
  'moduli.api-f-lettura': "nur lesen",
  'moduli.api-f-contatore': "nur lesen, automatisch",
  'moduli.api-f-file': "Liste [{ id, nome }] der Uploads",
  'moduli.api-copia': "Kopieren",
  'moduli.api-copiato': "Kopiert",
  'moduli.api-copia-mano': "Markieren und von Hand kopieren",
  'moduli.api-inizia': "Beginnt mit",
  'moduli.api-creato': "Angelegt",
  'moduli.api-scade': "Läuft ab",
  'moduli.api-ultimo-uso': "Zuletzt genutzt",
  'moduli.api-mai': "nie",
  'moduli.api-revocato': "widerrufen",
  'moduli.api-revoca': "Widerrufen",
  'moduli.api-revocare': "„{nome}“ widerrufen? Wer es nutzt, kommt nicht mehr rein.",
  'moduli.api-nessun-token': "Noch keine Tokens.",
  'moduli.api-a-cosa': "Wofür es ist (z. B. Website, Buchhaltung)",
  'moduli.api-30': "30 Tage",
  'moduli.api-90': "90 Tage",
  'moduli.api-anno': "ein Jahr",
  'moduli.api-non-scade': "läuft nicht ab",
  'moduli.api-crea-token': "Token erstellen",
  'moduli.api-ecco': "Hier ist das Token. Kopiere es jetzt: Es wird nicht wieder angezeigt.",
  'moduli.api-valore': "Wert",
  'moduli.api-elenco': "Liste (q = Suche, f = JSON-Filter, o = sortieren feld:desc, p = Seite, n = pro Seite bis 500)",
  'moduli.api-una-riga': "Eine Zeile",
  'moduli.api-modifica': "Bearbeiten (nur die gesendeten Felder)",
  'moduli.api-esporta': "Nach Excel exportieren",
  'moduli.api-tutte': "Alle Bereiche",
  'moduli.api-ev-crea': "angelegt",
  'moduli.api-ev-modifica': "bearbeitet",
  'moduli.api-ev-elimina': "archiviert",
  'moduli.api-ev-ripristina': "wiederhergestellt",
  'moduli.api-consegnate': {"one": "{n} zugestellt", "other": "{n} zugestellt"},
  'moduli.api-fallite': {"one": "{n} fehlgeschlagen", "other": "{n} fehlgeschlagen"},
  'moduli.api-in-attesa': "{n} ausstehend",
  'moduli.api-segreto': "Geheimnis: ",
  'moduli.api-mostra': "Anzeigen",
  'moduli.api-prova': "Test senden",
  'moduli.api-prova-partenza': "Test wird gesendet",
  'moduli.api-registro': "Protokoll",
  'moduli.api-elimina-webhook': "Webhook „{nome}“ löschen?",
  'moduli.api-evento': "Ereignis",
  'moduli.api-stato': "Status",
  'moduli.api-tentativi': "Versuche",
  'moduli.api-risposta': "Antwort",
  'moduli.api-quando': "Wann",
  'moduli.api-st-ok': "zugestellt",
  'moduli.api-st-attesa': "ausstehend",
  'moduli.api-st-invio': "wird gesendet",
  'moduli.api-st-fallita': "fehlgeschlagen",
  'moduli.api-riprova': "Erneut versuchen",
  'moduli.api-nessuna-consegna': "Noch keine Zustellungen.",
  'moduli.api-nessun-webhook': "Noch keine Webhooks.",
  'moduli.api-nome-wh': "Name (z. B. Buchhaltung)",
  'moduli.api-url-wh': "https://… die empfangende Adresse",
  'moduli.api-aggiungi-wh': "Webhook hinzufügen",
  'moduli.api-wh-aggiunto': "Webhook hinzugefügt",
  'moduli.api-intro': "Verbinde Kubo mit deiner Website, der Buchhaltung oder einer Automatisierung. Jeder Aufruf hat dieselben Rechte wie deine Rolle.",
  'moduli.api-tuoi-token': "Deine Tokens",
  'moduli.api-documentazione': "Dokumentation",
  'moduli.api-doc-1': "Jede Anfrage trägt den Header ",
  'moduli.api-doc-2': ". Antworten sind JSON; Fehler haben ",
  'moduli.api-doc-3': " und den passenden HTTP-Code (401, 403, 404, 422).",
  'moduli.api-openapi-1': "Die OpenAPI-3-Beschreibung (für Postman, Swagger oder zum Erzeugen eines Clients) liegt unter ",
  'moduli.api-openapi-2': ", nur mit den Bereichen, die das Token sehen darf.",
  'moduli.api-allegati': "Anhänge werden zuerst in Teilen hochgeladen (POST /api/file/carica, dann /api/file/carica/<id> mit { da, pezzo in Base64 }) und dann als [{ \"id\": \"<id>\" }] ins Feld gesetzt.",
  'moduli.api-wh-intro': "Wenn sich etwas ändert, sendet Kubo einen signierten JSON-POST an die gewählte Adresse. Antwortet sie nicht, versucht es Kubo nach 30 Sekunden, 2, 10 und 30 Minuten und 2 Stunden erneut.",
  'moduli.api-sezioni': "Bereiche (keiner = alle)",
  'moduli.api-quando-riga': "Wenn eine Zeile",
  'moduli.api-firma': "So prüfst du die Signatur",
  'moduli.lumi-dv-ferme': "{sezione}: seit über einer Woche auf „{stato}“",
  'moduli.lumi-dv-oltre': "{sezione}: „{campo}“ überschritten",
  'moduli.ag-niente': "Nichts zu melden.",
  'moduli.doc-prepara-chiedi': "Für die E-Rechnung braucht „{nome}“ einige Felder: Empfängercode, PEC, Straße, PLZ, Ort und Provinz. Die bisherige Adresse wird auf diese Felder aufgeteilt; die alte bleibt archiviert. Jetzt hinzufügen?",
  'moduli.doc-prepara-fatto': "Kunden bereit für die E-Rechnung",
};
