export default {
  'moduli.lumi-serve-chiave': "Zum Antworten brauche ich den Claude-Schlüssel. Ich öffne dir **Verwaltung → Lumi**: Das dauert eine Minute.",
  'moduli.lumi-serve-chiave-spento': "Zum Antworten brauche ich den Claude-Schlüssel, und du musst mich wieder einschalten. Ich öffne dir **Verwaltung → Lumi**: Das dauert eine Minute.",
  'moduli.lumi-chiedi-titolare': "Zum Antworten brauche ich den Claude-Schlüssel: Bitte den Inhaber, ihn unter **Verwaltung → Lumi** einzutragen.",
  'moduli.lumi-spento': "Lumi ist aus: Unter Verwaltung → Lumi schaltest du es wieder ein.",
  'moduli.lumi-quasi-pronto': "Lumi ist fast bereit: Der Claude-Schlüssel fehlt.",
  'moduli.lumi-apri': "Öffnen",
  'moduli.lumi-settimana': "Wie läuft die Woche",
  'moduli.lumi-settimana-domanda': "Wie lief diese Woche? Gib mir die wichtigsten Zahlen.",
  'moduli.lumi-accendi': "Lumi einschalten",
  'moduli.lumi-solo-titolare': "Die Einstellungen von Lumi sind Sache des Inhabers.",
  'moduli.lumi-gia-salvata': "•••••••• (bereits gespeichert)",
  'moduli.lumi-stato-spento': "Aus",
  'moduli.lumi-stato-acceso': "An",
  'moduli.lumi-stato-manca': "Schlüssel fehlt",
  'moduli.lumi-fonte-ambiente': "Der Schlüssel kommt aus der Variable ANTHROPIC_API_KEY des Servers.",
  'moduli.lumi-fonte-file': "Schlüssel auf diesem Computer gespeichert.",
  'moduli.lumi-cos-e': "Lumi ist der Assistent von Kubo. Du sprichst oder schreibst mit ihm über die Pille oben: Er sucht, zählt, legt Datensätze an und ändert die Form des Systems. Jede Änderung wartet auf dein „Bestätigen“, und jeder sieht nur, was seine Rechte erlauben.",
  'moduli.lumi-chiave': "Claude-Schlüssel",
  'moduli.lumi-salva-chiave': "Schlüssel speichern",
  'moduli.lumi-incolla': "Füge den Schlüssel ein",
  'moduli.lumi-togliere': "Schlüssel entfernen? Lumi antwortet dann nicht mehr.",
  'moduli.lumi-dove-chiave': "Du erstellst ihn auf console.anthropic.com unter API Keys. Er bleibt auf diesem Computer, in einer Datei neben den Daten, die nur Kubo liest, und erreicht nie die Browser.",
  'moduli.lumi-acceso': "Lumi an",
  'moduli.lumi-limite': "Fragen pro Minute und Person",
  'moduli.lumi-da-provare': "Zum Ausprobieren",
  'moduli.lumi-esempio-1': "Wie viel habe ich diese Woche verkauft?",
  'moduli.lumi-esempio-2': "Was muss ich nachbestellen?",
  'moduli.lumi-esempio-3': "Füge den Artikeln die Größe hinzu, mit S, M, L und XL",
  'moduli.lumi-esempio-4': "Leg mir einen Bereich für Vermietungen an, mit Kunde, Gerät, von, bis und Status",
  'moduli.lumi-esempio-5': "Wenn eine Vermietung auf zurückgegeben wechselt, sag mir Bescheid",
  'moduli.lumi-modello': "Modell: {modello}.",
  'moduli.lumi-voce-accesa': "Echtzeit-Sprache an.",
  'moduli.lumi-voce-browser': "Sprache: die des Browsers, wo vorhanden.",
  'moduli.ag-adesso': "gerade eben",
  'moduli.ag-agenda': "Kalender",
  'moduli.ag-calendario': "Kalenderansicht",
  'moduli.ag-cruscotto': "Dashboard",
  'moduli.ag-aggiungi-voce': "Eintrag hinzufügen",
  'moduli.ag-altri': {"one": "+{n} weiterer", "other": "+{n} weitere"},
  'moduli.ag-e-altri': {"one": "und ein weiterer", "other": "und {n} weitere"},
  'moduli.ag-aria-grafico': "{titolo}: Diagramm",
  'moduli.ag-barre': "Balken",
  'moduli.ag-linea': "Linie",
  'moduli.ag-buongiorno': "Guten Morgen",
  'moduli.ag-buon-pomeriggio': "Guten Tag",
  'moduli.ag-buonasera': "Guten Abend",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Ändern",
  'moduli.ag-cambia-widget': "Widget ändern",
  'moduli.ag-nuovo-widget': "Neues Widget",
  'moduli.ag-campo': "Feld",
  'moduli.ag-colonne-per': "Spalten: {nome}",
  'moduli.ag-una-colonna': "Eine Spalte",
  'moduli.ag-come-oggi': "wie gestern",
  'moduli.ag-come-settimana': "wie letzte Woche",
  'moduli.ag-come-mese': "wie letzten Monat",
  'moduli.ag-come-anno': "wie letztes Jahr",
  'moduli.ag-rispetto-oggi': "{diff} gegenüber gestern ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} gegenüber letzter Woche ({prima})",
  'moduli.ag-rispetto-mese': "{diff} gegenüber letztem Monat ({prima})",
  'moduli.ag-rispetto-anno': "{diff} gegenüber letztem Jahr ({prima})",
  'moduli.ag-data-rif': "Bezugsdatum",
  'moduli.ag-prima': "Zurück",
  'moduli.ag-dopo': "Weiter",
  'moduli.ag-fatto': "Fertig",
  'moduli.ag-forma': "Darstellung",
  'moduli.ag-ha-creato': "hat angelegt:",
  'moduli.ag-ha-modificato': "hat bearbeitet:",
  'moduli.ag-ha-archiviato': "hat archiviert:",
  'moduli.ag-ha-ripristinato': "hat wiederhergestellt:",
  'moduli.ag-in-sezione': "in {nome}",
  'moduli.ag-un-elemento': "einen Eintrag",
  'moduli.ag-lista': "Liste",
  'moduli.ag-torna-lista': "Zurück zur Liste",
  'moduli.ag-media': "Durchschnitt von…",
  'moduli.ag-somma': "Summe von…",
  'moduli.ag-quanti': "Anzahl",
  'moduli.ag-misura': "Kennzahl",
  'moduli.ag-modifica': "Bearbeiten",
  'moduli.ag-nome-voce': "Name des Eintrags",
  'moduli.ag-nuova-voce': "Neuer Eintrag",
  'moduli.ag-un-filtro': "Gib dem Eintrag mindestens einen Filter",
  'moduli.ag-non-disegno': "Das lässt sich nicht darstellen",
  'moduli.ag-oggi': "Heute",
  'moduli.ag-per': "Nach",
  'moduli.ag-periodo': "Zeitraum",
  'moduli.ag-periodo-oggi': "Heute",
  'moduli.ag-periodo-settimana': "Diese Woche",
  'moduli.ag-periodo-mese': "Dieser Monat",
  'moduli.ag-periodo-anno': "Dieses Jahr",
  'moduli.ag-periodo-ultimi_7': "Letzte 7 Tage",
  'moduli.ag-periodo-ultimi_30': "Letzte 30 Tage",
  'moduli.ag-periodo-ultimi_84': "Letzte 12 Wochen",
  'moduli.ag-periodo-ultimi_365': "Letztes Jahr",
  'moduli.ag-periodo-sempre': "Gesamt",
  'moduli.ag-piede-grafico': "{periodo} · insgesamt {totale}",
  'moduli.ag-piu-aggiungi': "+ Hinzufügen",
  'moduli.ag-quale-data': "Welches Datum",
  'moduli.ag-senza-titolo': "Ohne Titel",
  'moduli.ag-spostato': "Verschoben",
  'moduli.ag-tipo': "Typ",
  'moduli.ag-titolo': "Titel",
  'moduli.ag-titolo-widget': "Gib dem Widget einen Titel",
  'moduli.ag-tutti': "alle",
  'moduli.ag-utente-non-attivo': "Inaktiver Benutzer",
  'moduli.ag-vedi-calendario': "Im Kalender ansehen",
  'moduli.ag-vedi-elenco': "Liste ansehen",
  'moduli.ag-vedi-giorno': "Tag ansehen",
  'moduli.ag-vista-giorno': "Tag",
  'moduli.ag-vista-settimana': "Woche",
  'moduli.ag-vista-mese': "Monat",
  'moduli.ag-w-numero': "Zahl",
  'moduli.ag-w-grafico': "Diagramm",
  'moduli.ag-w-attenzione': "Braucht Aufmerksamkeit",
  'moduli.ag-w-ultime': "Letzte Änderungen",
  'moduli.ag-def-incassato-oggi': "Heute eingenommen",
  'moduli.ag-def-incassato-mese': "Diesen Monat eingenommen",
  'moduli.ag-def-vendite-oggi': "Verkäufe heute",
  'moduli.ag-def-incassi-30': "Einnahmen der letzten 30 Tage",
  'moduli.ag-def-appuntamenti-oggi': "Termine heute",
  'moduli.ag-def-appuntamenti-settimana': "Termine pro Woche",
  'moduli.ag-def-preventivi-attesa': "Offene Angebote",
  'moduli.ag-def-commesse-aperte': "Offene Aufträge",
  'moduli.ag-def-accettato-mese': "Diesen Monat angenommen",
  'moduli.ag-def-preventivi-mese': "Angenommene Angebote pro Monat",
  'moduli.ag-def-articoli-riordinare': "Nachzubestellende Artikel",
  'moduli.ag-def-materiali-riordinare': "Nachzubestellendes Material",
  'moduli.ag-def-ordini-ritardo': "Verspätete Bestellungen",
  'moduli.ag-def-vendite-aperte': "Seit über 2 Tagen offene Verkäufe",
  'moduli.ag-def-commesse-ritardo': "Verspätete Aufträge",
  'moduli.ag-def-preventivi-senza-risposta': "Angebote seit 7 Tagen ohne Antwort",
  'moduli.ag-def-appuntamenti-chiudere': "Vergangene Termine zum Abschließen",
  'moduli.ag-def-pacchetti-scaduti': "Abgelaufene Pakete mit Sitzungen",
  'moduli.ag-def-attenzione': "Braucht Aufmerksamkeit",
  'moduli.ag-def-ultime': "Letzte Änderungen",
  'moduli.ag-def-nuovi-mese': "{nome}: neu diesen Monat",
  'moduli.ag-tutto-ok': "✓ Alles in Ordnung: nichts zu erledigen.",
  'moduli.ag-nessuna-modifica': "Noch keine Änderungen.",
  'moduli.ag-es-titolo': "Z. B. Heute eingenommen",
};
