export default {
  'moduli.lumi-serve-chiave': "Zum Antworten brauche ich den Claude-Schlüssel. Ich öffne dir **Verwaltung → Lumi**: Das dauert eine Minute.",
  'moduli.lumi-serve-chiave-spento': "Zum Antworten brauche ich den Claude-Schlüssel, und du musst mich wieder einschalten. Ich öffne dir **Verwaltung → Lumi**: Das dauert eine Minute.",
  'moduli.lumi-chiedi-titolare': "Zum Antworten brauche ich den Claude-Schlüssel: Bitte den Inhaber, ihn unter **Verwaltung → Lumi** einzutragen.",
  'moduli.lumi-spento': "Lumi ist aus: Unter Verwaltung → Lumi schaltest du es wieder ein.",
  'moduli.lumi-quasi-pronto': "Lumi ist fast bereit: Der Claude-Schlüssel fehlt.",
  'moduli.lumi-apri': "Öffnen",
  'moduli.lumi-settimana': "Wie läuft die Woche",
  'moduli.lumi-settimana-domanda': "Wie lief diese Woche? Gib mir die wichtigsten Zahlen.",
  'moduli.lumi-accendi': "Lumi einschalten",
  'moduli.lumi-solo-titolare': "Die Einstellungen von Lumi sind Sache des Inhabers.",
  'moduli.lumi-gia-salvata': "•••••••• (bereits gespeichert)",
  'moduli.lumi-stato-spento': "Aus",
  'moduli.lumi-stato-acceso': "An",
  'moduli.lumi-stato-manca': "Schlüssel fehlt",
  'moduli.lumi-fonte-ambiente': "Der Schlüssel kommt aus der Variable ANTHROPIC_API_KEY des Servers.",
  'moduli.lumi-fonte-file': "Schlüssel auf diesem Computer gespeichert.",
  'moduli.lumi-cos-e': "Lumi ist der Assistent von Kubo. Du sprichst oder schreibst mit ihm über die Pille oben: Er sucht, zählt, legt Datensätze an und ändert die Form des Systems. Jede Änderung wartet auf dein „Bestätigen“, und jeder sieht nur, was seine Rechte erlauben.",
  'moduli.lumi-chiave': "Claude-Schlüssel",
  'moduli.lumi-salva-chiave': "Schlüssel speichern",
  'moduli.lumi-incolla': "Füge den Schlüssel ein",
  'moduli.lumi-togliere': "Schlüssel entfernen? Lumi antwortet dann nicht mehr.",
  'moduli.lumi-dove-chiave': "Du erstellst ihn auf console.anthropic.com unter API Keys. Er bleibt auf diesem Computer, in einer Datei neben den Daten, die nur Kubo liest, und erreicht nie die Browser.",
  'moduli.lumi-acceso': "Lumi an",
  'moduli.lumi-limite': "Fragen pro Minute und Person",
  'moduli.lumi-da-provare': "Zum Ausprobieren",
  'moduli.lumi-esempio-1': "Wie viel habe ich diese Woche verkauft?",
  'moduli.lumi-esempio-2': "Was muss ich nachbestellen?",
  'moduli.lumi-esempio-3': "Füge den Artikeln die Größe hinzu, mit S, M, L und XL",
  'moduli.lumi-esempio-4': "Leg mir einen Bereich für Vermietungen an, mit Kunde, Gerät, von, bis und Status",
  'moduli.lumi-esempio-5': "Wenn eine Vermietung auf zurückgegeben wechselt, sag mir Bescheid",
  'moduli.lumi-modello': "Modell: {modello}.",
  'moduli.lumi-voce-accesa': "Echtzeit-Sprache an.",
  'moduli.lumi-voce-browser': "Sprache: die des Browsers, wo vorhanden.",
};
