// Area «sicurezza» (web/moduli/sicurezza.js): password, dispositivi collegati, impostazioni dell'azienda, poteri dei ruoli.
export default {
  'sicurezza.titolo': 'Sicherheit',
  'sicurezza.la-tua-password': 'Dein Passwort',
  'sicurezza.dispositivi-collegati': 'Angemeldete Geräte',
  'sicurezza.dispositivo': '{browser} auf {sistema}',
  'sicurezza.dispositivo-sconosciuto': 'Unbekanntes Gerät',
  'sicurezza.app-lumi': 'Lumi-App',
  'sicurezza.iphone-ipad': 'iPhone oder iPad',
  'sicurezza.password-diverse': 'Die beiden neuen Passwörter stimmen nicht überein',
  'sicurezza.password-cambiata': 'Passwort geändert. Die anderen Geräte wurden abgemeldet.',
  'sicurezza.password-attuale': 'Aktuelles Passwort',
  'sicurezza.password-nuova': 'Neues Passwort',
  'sicurezza.password-regole': 'Mindestens 8 Zeichen; unter 12 mische Buchstaben mit Ziffern oder Sonderzeichen.',
  'sicurezza.password-ripeti': 'Neues Passwort wiederholen',
  'sicurezza.cambia-password': 'Passwort ändern',
  'sicurezza.col-dispositivo': 'Gerät',
  'sicurezza.col-ultimo-uso': 'Zuletzt benutzt',
  'sicurezza.col-indirizzo': 'Adresse',
  'sicurezza.questo': 'dieses',
  'sicurezza.scollega': 'Abmelden',
  'sicurezza.scollegati': { one: '{n} Gerät abgemeldet', other: '{n} Geräte abgemeldet' },
  'sicurezza.scollega-altri': 'Alle anderen abmelden',
  'sicurezza.impostazioni': 'Firmeneinstellungen',
  'sicurezza.inattivita': 'Sitzungen schließen nach Inaktivität von (Minuten)',
  'sicurezza.allegati': 'Anhänge: höchstens (MB)',
  'sicurezza.fuso': 'Zeitzone',
  'sicurezza.lumi-budget': 'Lumi: Tokens pro Monat (0 = unbegrenzt)',
  'sicurezza.lumi-usati': 'Diesen Monat verbraucht: {usati}',
  'sicurezza.webhook-interni': 'Webhooks ins interne Netz erlauben (127.0.0.1, 192.168…). Lass es aus, wenn du nicht weißt, wofür es gut ist.',
  'sicurezza.salvate': 'Einstellungen gespeichert',
  'sicurezza.salva': 'Speichern',
  'sicurezza.ruoli': 'Rechte der Rollen',
  'sicurezza.ruoli-nota': 'Der Export der E-Rechnung verbraucht eine Versandnummer; Lumi nutzt die Tokens der Firma.',
  'sicurezza.col-ruolo': 'Rolle',
  'sicurezza.potere-fatturapa': 'FatturaPA exportieren',
  'sicurezza.potere-lumi': 'Lumi nutzen',
  'sicurezza.potere-aria': '{potere} für {ruolo}',
  'sicurezza.salvato': 'Gespeichert',
  'sicurezza.persone': 'Personen',
  'sicurezza.col-nome': 'Name',
  'sicurezza.obbliga-cambio': 'Passwortänderung erzwingen',
  'sicurezza.obbligo-fatto': '{nome} ändert das Passwort bei der nächsten Anmeldung',
  'sicurezza.scollega-ovunque': 'Überall abmelden',
  'sicurezza.scollegato-ovunque': 'Sitzungen von {nome} auf allen Geräten beendet',
  'sicurezza.nessun-altro': 'Sonst niemand.',
  'sicurezza.scegli-password': 'Wähle dein Passwort',
  'sicurezza.provvisoria': 'Das Passwort, das du bekommen hast, war vorläufig. Wähle ein eigenes, um weiterzumachen.',
};
