// Finanzen (web/moduli/tesoreria.js): Fälligkeiten, Bankabgleich, Liquiditätsvorschau, Mahnungen, Sammelaufträge.
export default {
  'tesoreria.titolo': "Finanzen",
  'tesoreria.scheda-scadenze': "Fälligkeiten",
  'tesoreria.scheda-banca': "Bank",
  'tesoreria.scheda-cassa': "Liquiditätsvorschau",
  'tesoreria.scheda-solleciti': "Mahnungen",
  'tesoreria.scheda-distinte': "Sammelaufträge",
  'tesoreria.scheda-impostazioni': "Einstellungen",
  'tesoreria.manca-fatture': "Fälligkeiten entstehen aus Rechnungen: Füge unter Anpassen die Vorlage „Rechnungen und E-Rechnung“ hinzu.",
  'tesoreria.da-incassare': "Offene Forderungen",
  'tesoreria.da-pagare': "Offene Verbindlichkeiten",
  'tesoreria.di-cui-scaduto': "davon überfällig {importo}",
  'tesoreria.saldo-netto': "Differenz",
  'tesoreria.verso-attiva': "Zahlungseingänge von Kunden",
  'tesoreria.verso-passiva': "Zahlungen an Lieferanten",
  'tesoreria.solo-scadute': "Nur überfällige",
  'tesoreria.cerca': "Kunde oder Beleg suchen",
  'tesoreria.scadenza': "Fällig am",
  'tesoreria.documento': "Beleg",
  'tesoreria.cliente': "Kunde",
  'tesoreria.fornitore': "Lieferant",
  'tesoreria.importo': "Betrag",
  'tesoreria.residuo': "Offen",
  'tesoreria.stato': "Status",
  'tesoreria.pagata': "Bezahlt",
  'tesoreria.in-distinta': "Im Sammelauftrag",
  'tesoreria.scaduta-da': { one: "Seit {n} Tag überfällig", other: "Seit {n} Tagen überfällig" },
  'tesoreria.parziale': "Teilzahlung",
  'tesoreria.aperta': "Offen",
  'tesoreria.incassata': "Eingegangen",
  'tesoreria.pagata-btn': "Bezahlt",
  'tesoreria.acconto': "Teilzahlung",
  'tesoreria.niente-scadenze': "Keine offenen Fälligkeiten.",
  'tesoreria.scegli-nota': "Fälligkeiten ankreuzen, um sie als bezahlt zu markieren oder die Datei für die Bank zu erstellen.",
  'tesoreria.scelte': { one: "{n} ausgewählt · {importo}", other: "{n} ausgewählt · {importo}" },
  'tesoreria.segna-incassate': "Als eingegangen markieren",
  'tesoreria.segna-pagate': "Als bezahlt markieren",
  'tesoreria.distinta-riba': "Ri.Ba.-Sammelauftrag",
  'tesoreria.distinta-sdd': "SDD-Lastschrift",
  'tesoreria.distinta-sct': "SEPA-Überweisungen",
  'tesoreria.data-pagamento': "Zahlungsdatum (JJJJ-MM-TT)",
  'tesoreria.data-esecuzione': "Ausführungsdatum bei der Bank (JJJJ-MM-TT)",
  'tesoreria.data-accredito': "Datum der Gutschrift oder Zahlung (JJJJ-MM-TT)",
  'tesoreria.importo-acconto': "Eingegangener oder bezahlter Betrag",
  'tesoreria.importo-non-valido': "Ungültiger Betrag",
  'tesoreria.incassi-registrati': { one: "Zahlungseingang erfasst", other: "{n} Zahlungseingänge erfasst" },
  'tesoreria.pagamenti-registrati': { one: "Zahlung erfasst", other: "{n} Zahlungen erfasst" },
  'tesoreria.distinta-creata': "{nome} bereit: {importo}. Lade die Datei ins Online-Banking hoch.",
  'tesoreria.nota-termini': "Fälligkeiten kommen aus den Raten der Rechnung, ihrem Fälligkeitsdatum oder den Zahlungsbedingungen des Kunden oder Lieferanten (zum Beispiel 30/60/90 DFFM).",
  'tesoreria.err-sia': "Der SIA-Code des Unternehmens fehlt (du erhältst ihn von der Bank): Trage ihn in den Finanzeinstellungen ein.",
  'tesoreria.err-iban-azienda': "Die IBAN des Unternehmens fehlt oder ist falsch: Dokumente → Firmendaten.",
  'tesoreria.err-banca-debitore': "{nome}: In der Kundenkarte fehlt die IBAN der Hausbank.",
  'tesoreria.err-cf-debitore': "{nome}: Umsatzsteuer-ID oder Steuernummer fehlt.",
  'tesoreria.err-importo': "{nome}: ungültiger Einzugsbetrag.",
  'tesoreria.err-id-creditore': "Die SEPA-Gläubiger-ID fehlt (die Bank vergibt sie): Finanzeinstellungen.",
  'tesoreria.err-iban-debitore': "{nome}: IBAN des Kunden fehlt oder ist falsch.",
  'tesoreria.err-mandato-id': "{nome}: Die SDD-Mandatsreferenz enthält unzulässige Zeichen oder ist länger als 35: in der Kundenkarte korrigieren (muss dem unterschriebenen Mandat genau entsprechen).",
  'tesoreria.err-mandato': "{nome}: In der Kundenkarte fehlen Mandatsreferenz und -datum für SDD.",
  'tesoreria.err-iban-beneficiario': "{nome}: IBAN des Lieferanten fehlt oder ist falsch.",
  'tesoreria.banca-titolo': "Kontoauszug und Abgleich",
  'tesoreria.manca-movimenti': "Für den Import eines Kontoauszugs braucht es den Bereich „Bankbewegungen“.",
  'tesoreria.prepara': "Finanzen einrichten",
  'tesoreria.preparata': { one: "{n} Element hinzugefügt", other: "{n} Elemente hinzugefügt" },
  'tesoreria.chiedi-titolare': "Frag jemanden, der das System anpassen darf.",
  'tesoreria.file-grande': "{nome} ist zu groß",
  'tesoreria.importati': "{n} Bewegungen importiert, {doppi} schon vorhanden",
  'tesoreria.saldo-aggiornato': "Saldo der Vorschau aktualisiert: {importo} am {data}",
  'tesoreria.carica-estratto': "Kontoauszug hierher ziehen oder klicken",
  'tesoreria.formati': "CAMT.053 (XML), CBI, CSV oder Excel der Bank",
  'tesoreria.abbinato': "Abgeglichen: Fälligkeiten als bezahlt markiert",
  'tesoreria.abbinato-differenza': "Abgeglichen; {importo} bleiben übrig",
  'tesoreria.abbina-a': "Zuordnen zu…",
  'tesoreria.abbina': "Zuordnen",
  'tesoreria.ignora': "Ignorieren",
  'tesoreria.ignora-nota': "Gebühren, Umbuchungen, Gehälter: Bewegungen, die keine Rechnung ausgleichen",
  'tesoreria.nessuna-proposta': "Kein Vorschlag: unten von Hand auswählen.",
  'tesoreria.da-abbinare': { one: "{n} Bewegung zuzuordnen", other: "{n} Bewegungen zuzuordnen" },
  'tesoreria.tutto-abbinato': "Alles zugeordnet.",
  'tesoreria.abbinati-recenti': "Kürzlich zugeordnet",
  'tesoreria.data': "Datum",
  'tesoreria.descrizione': "Beschreibung",
  'tesoreria.mov-abbinato': "Zugeordnet",
  'tesoreria.mov-ignorato': "Ignoriert",
  'tesoreria.mov-da_abbinare': "Zuzuordnen",
  'tesoreria.annulla': "Rückgängig",
  'tesoreria.nota-movimenti': "Die Bewegungen stehen im Bereich „{sezione}“: Auch die Bankverbindungen (Open Banking) füllen ihn.",
  'tesoreria.perche-importo': "gleicher Betrag",
  'tesoreria.perche-importo-vicino': "ähnlicher Betrag",
  'tesoreria.perche-acconto': "Teilzahlung",
  'tesoreria.perche-numero': "Rechnungsnummer",
  'tesoreria.perche-iban': "gleiche IBAN",
  'tesoreria.perche-nome': "Name",
  'tesoreria.perche-data': "nahes Datum",
  'tesoreria.perche-somma': "mehrere Rechnungen zusammen",
  'tesoreria.perche-distinta': "Gutschrift des Sammelauftrags",
  'tesoreria.grafico': "Erwartete Einnahmen, Ausgaben und Saldo",
  'tesoreria.passo-settimana': "Wochen",
  'tesoreria.passo-mese': "Monate",
  'tesoreria.senza-saldo': "Der Anfangssaldo fehlt: Trage ihn in den Einstellungen ein oder importiere einen CAMT.053-Kontoauszug.",
  'tesoreria.apri-impostazioni': "Einstellungen öffnen",
  'tesoreria.scoperto': "Achtung: Die Liquidität fällt unter null, bis auf {importo} am {data}.",
  'tesoreria.saldo-oggi': "Saldo heute",
  'tesoreria.saldo-dal': "vom Saldo am {data} plus Bewegungen",
  'tesoreria.saldo-fine': "Erwarteter Saldo",
  'tesoreria.punto-basso': "Tiefster Stand",
  'tesoreria.entrate': "Einnahmen",
  'tesoreria.uscite': "Ausgaben",
  'tesoreria.saldo': "Saldo",
  'tesoreria.periodi': "Nach Zeitraum",
  'tesoreria.periodo': "Zeitraum",
  'tesoreria.voci': "Woher die Zahlen kommen",
  'tesoreria.tipo': "Art",
  'tesoreria.voce-incasso': "Zahlungseingang",
  'tesoreria.voce-pagamento': "Zahlung",
  'tesoreria.voce-previsione': "Planwert",
  'tesoreria.voce-contratto': "Wiederkehrender Vertrag",
  'tesoreria.voce-tasse': "Steuern",
  'tesoreria.ritardo-medio': { one: "der Kunde zahlt im Schnitt {n} Tag zu spät", other: "der Kunde zahlt im Schnitt {n} Tage zu spät" },
  'tesoreria.niente-voci': "Nichts in Sicht in diesem Zeitraum.",
  'tesoreria.aggiungi-previsione': "Miete, Gehälter, Kredite und andere Planwerte hinzufügen",
  'tesoreria.sollecito-segnato': "Mahnung erfasst",
  'tesoreria.livello-1': "Freundliche Erinnerung",
  'tesoreria.livello-2': "Mahnung",
  'tesoreria.livello-3': "Letzte Mahnung",
  'tesoreria.appena-sollecitato': "Kürzlich gemahnt",
  'tesoreria.ritardo-giorni': { one: "{n} Tag Verzug", other: "{n} Tage Verzug" },
  'tesoreria.ultimo-sollecito': "Letzte Mahnung am {data} (Stufe {livello})",
  'tesoreria.lettera': "Text der Mahnung",
  'tesoreria.copia': "Text kopieren",
  'tesoreria.copiato': "Kopiert",
  'tesoreria.copia-no': "Kopieren nicht möglich: Text von Hand markieren",
  'tesoreria.oggetto-sollecito': "Zahlungserinnerung",
  'tesoreria.scrivi-email': "E-Mail schreiben",
  'tesoreria.segna-mandato': "Als gesendet markieren",
  'tesoreria.niente-solleciti': "Kein Kunde im Verzug.",
  'tesoreria.distinta-chiusa': "Sammelauftrag abgeschlossen: Fälligkeiten als bezahlt markiert",
  'tesoreria.distinta': "Sammelauftrag",
  'tesoreria.creata': "Erstellt",
  'tesoreria.quante': "Fälligkeiten",
  'tesoreria.pagata-il': "Bezahlt am {data}",
  'tesoreria.accreditata-il': "Gutgeschrieben am {data}",
  'tesoreria.in-attesa': "Ausstehend",
  'tesoreria.scarica': "Herunterladen",
  'tesoreria.segna-pagati': "Als bezahlt markieren",
  'tesoreria.segna-accreditata': "Als gutgeschrieben markieren",
  'tesoreria.niente-distinte': "Noch keine Sammelaufträge: Sie entstehen aus den Fälligkeiten.",
  'tesoreria.nota-distinte': "Die Datei wird ins Online-Banking hochgeladen (Ri.Ba. im CBI-Format, SDD und Überweisungen als SEPA-XML). Schreibt die Bank den Sammelauftrag gut, schlägt der Abgleich ihn von selbst vor.",
  'tesoreria.salvate': "Einstellungen gespeichert",
  'tesoreria.sia': "SIA-Code",
  'tesoreria.bic': "BIC deiner Bank (optional)",
  'tesoreria.id-creditore': "SEPA-Gläubiger-ID (für SDD)",
  'tesoreria.saldo-banca': "Kontostand",
  'tesoreria.saldo-data': "Kontostand am",
  'tesoreria.sequenza-sdd': "Art der SDD-Lastschrift",
  'tesoreria.seq-rcur': "Wiederkehrend (RCUR)",
  'tesoreria.seq-frst': "Erste einer Serie (FRST)",
  'tesoreria.seq-ooff': "Einmalig (OOFF)",
  'tesoreria.sezione-movimenti': "Bereich der Bankbewegungen",
  'tesoreria.ritardo-clienti': "In der Vorschau Zahlungseingänge um den durchschnittlichen Verzug jedes Kunden verschieben",
  'tesoreria.salva': "Speichern",
  'tesoreria.banca-azienda': "Das Firmenkonto",
  'tesoreria.iban-azienda': "IBAN für Ri.Ba., SDD und Überweisungen: {iban}",
  'tesoreria.manca-iban': "Die IBAN des Unternehmens fehlt.",
  'tesoreria.dati-azienda': "Firmendaten",
  'tesoreria.nota-sia': "SIA-Code und Gläubiger-ID erhältst du von der Bank, wenn du Ri.Ba. und SDD aktivierst. Die vorgeschlagene ID wird aus der Umsatzsteuer-ID berechnet: Prüfe sie mit der Bank.",
  'tesoreria.sezioni': "Bereiche",
  'tesoreria.sezioni-mancano': "Es fehlen „Bankbewegungen“ oder „Liquiditätsplanung“ sowie die Zahlungsfelder von Kunden und Lieferanten (Bedingungen, IBAN, SDD-Mandat).",
  'tesoreria.sezioni-ci-sono': "Alle vorhanden.",
  'tesoreria.termini': "Zahlungsbedingungen",
  'tesoreria.termini-nota': "Sie stehen in der Karte des Kunden oder Lieferanten. DF = Rechnungsdatum, FM = Monatsende, +10 = der 10. des Folgemonats. 30, 60 und 90 Tage zählen als Monate.",
};
