export default {
  'viste.cerca-in': 'In {nome} suchen…',
  'viste.nuovo': '+ Neu',
  'viste.tabella': 'Tabelle',
  'viste.kanban': 'Kanban',
  'viste.archiviati': 'Archiviert',
  'viste.viste-salvate': 'Gespeicherte Ansichten',
  'viste.colonne': 'Spalten',
  'viste.raggruppa': 'Gruppieren',
  'viste.senza-gruppi': 'Ohne Gruppen',
  'viste.gruppi-per': 'Gruppen: {nome}',
  'viste.salva-vista': 'Ansicht speichern',
  'viste.tutti': 'Alle',
  'viste.per-tutti': 'Für alle',
  'viste.mie': 'Meine',
  'viste.filtri-tolti': 'Einige Filter dieser Ansicht nutzen Felder, die du nicht siehst: Ich habe sie entfernt',
  'viste.salva-modifiche': 'Änderungen speichern…',
  'viste.esempio-vista': 'Z. B. Diese Woche liefern',
  'viste.nome-vista': 'Gib der Ansicht einen Namen',
  'viste.salvata-tutti': 'Ansicht für alle gespeichert',
  'viste.salvata-te': 'Ansicht für dich gespeichert',
  'viste.vista-nome': 'Ansicht „{nome}“',
  'viste.salva-questa': 'Diese Ansicht speichern',
  'viste.cosa-salva': 'Aktuelle Filter, Spalten, Gruppen und Sortierung.',
  'viste.la-vedono-tutti': 'Alle sehen sie',
  'viste.solo-tu': 'Nur du siehst sie.',
  'viste.elimina': 'Löschen',
  'viste.elimina-vista': 'Ansicht „{nome}“ löschen?',
  'viste.vista-eliminata': 'Ansicht gelöscht',
  'viste.salva-nuova': 'Als neue speichern',
  'viste.aggiorna': 'Aktualisieren',
  'viste.salva': 'Speichern',
  'viste.come-inizio': 'Zurücksetzen',
  'viste.nessuno': 'Keine Angabe',
  'viste.nessun-risultato': 'Keine Ergebnisse.',
  'viste.niente-archivio': 'Nichts im Archiv.',
  'viste.ancora-nessuno': 'Noch nichts in {nome}.',
  'viste.crea-primo': '+ Den ersten anlegen',
  'viste.totale': 'Summe ({n})',
  'viste.prime-di': 'Ich zeige die ersten {k} von {n} (die Summen zählen alle)',
  'viste.in-tutto': { one: '{n} insgesamt', other: '{n} insgesamt' },
  'viste.crea': 'Anlegen',
  'viste.creato': 'Angelegt',
  'viste.salvato': 'Gespeichert',
  'viste.nuovo-in': 'Neu in {nome}',
  'viste.archivia': 'Archivieren',
  'viste.archiviare': 'Archivieren? Du kannst es aus dem Archiv wiederherstellen.',
  'viste.archiviato': 'Archiviert',
  'viste.ripristina': 'Wiederherstellen',
  'viste.ripristinato': 'Wiederhergestellt',
  'viste.storia': 'Verlauf',
  'viste.archiviato-min': 'archiviert',
  'viste.automazione': 'Automatisierung',
  'viste.storia-creato': 'angelegt',
  'viste.storia-ripristinato': 'wiederhergestellt',
  'viste.non-si-passa': 'Von „{da}“ geht es nicht hierher',
  'viste.al-salvataggio': 'beim Speichern',
  'viste.piu-immagine': '+ Bild',
  'viste.piu-file': '+ Datei',
  'viste.non-immagine': '„{nome}“ ist kein Bild',
  'viste.o-trascina': 'oder hierher ziehen',
  'viste.righe-non-trovata': 'Entität der Positionen nicht gefunden',
  'viste.aggiungi-riga': '+ Position hinzufügen',
  'viste.creato-il': 'Angelegt am',
  'viste.modificato-il': 'Geändert am',
  'viste.periodo-oggi': 'heute',
  'viste.periodo-ieri': 'gestern',
  'viste.periodo-settimana': 'diese Woche',
  'viste.periodo-mese': 'diesen Monat',
  'viste.periodo-ultimi_7': 'letzte 7 Tage',
  'viste.periodo-ultimi_30': 'letzte 30 Tage',
  'viste.periodo-anno': 'dieses Jahr',
  'viste.op-uguale': 'ist',
  'viste.op-diverso': 'ist nicht',
  'viste.op-tra': 'zwischen',
  'viste.op-contiene': 'enthält',
  'viste.op-inizia': 'beginnt mit',
  'viste.op-vuoto': 'ist leer',
  'viste.op-nonvuoto': 'ist nicht leer',
  'viste.op-in': 'ist einer von',
  'viste.op-prima': 'vor dem',
  'viste.op-dopo': 'ab dem',
  'viste.op-vero': 'ist wahr',
  'viste.op-falso': 'ist falsch',
  'viste.o': ' oder ',
  'viste.tra-e': '{a} und {b}',
  'viste.io': 'ich',
  'viste.me': 'mir',
  'viste.io-maiuscolo': 'Ich',
  'viste.piu-filtro': '+ Filter',
  'viste.cambia-filtro': 'Filter ändern',
  'viste.togli-tutti': 'Alle entfernen',
  'viste.scegli-campo': 'Feld wählen…',
  'viste.nel-periodo': 'im Zeitraum',
  'viste.testo': 'Text',
  'viste.scegli-un-campo': 'Wähle ein Feld',
  'viste.manca-valore': 'Der Wert fehlt',
  'viste.nuovo-filtro': 'Neuer Filter',
  'viste.applica': 'Anwenden',
};
