// Il modulo WhatsApp dell'interfaccia (web/moduli/whatsapp.js): conversazioni, modelli, automazioni, impostazioni.
export default {
  'whatsapp.forse-stop': 'Klingt nach dem Wunsch, keine Nachrichten mehr zu erhalten',
  'whatsapp.segna-stop': 'Als STOP markieren',
  'whatsapp.s-approvato': "Genehmigt",
  'whatsapp.s-in_attesa': "Ausstehend",
  'whatsapp.s-rifiutato': "Abgelehnt",
  'whatsapp.s-in_pausa': "Pausiert",
  'whatsapp.s-disattivato': "Deaktiviert",
  'whatsapp.s-inviato': "Gesendet",
  'whatsapp.s-consegnato': "Zugestellt",
  'whatsapp.s-letto': "Gelesen",
  'whatsapp.s-fallito': "Fehlgeschlagen",
  'whatsapp.s-bloccato': "Gestoppt",
  'whatsapp.s-coda': "In Warteschlange",
  'whatsapp.s-ricevuto': "Empfangen",
  'whatsapp.finestra-aperta': "Fenster offen bis {ora}",
  'whatsapp.finestra-chiusa': "Fenster geschlossen: eine Vorlage ist nötig",
  'whatsapp.attivo': "Aktiv: {nome}",
  'whatsapp.nessuno': "Kein WhatsApp-Dienst eingeschaltet.",
  'whatsapp.vai-connettori': "In den Connectoren verbinden",
  'whatsapp.conversazioni': "Unterhaltungen",
  'whatsapp.modelli': "Vorlagen",
  'whatsapp.automazioni': "WhatsApp-Automationen",
  'whatsapp.impostazioni': "Einstellungen",
  'whatsapp.vuoto': "Noch keine Nachrichten.",
  'whatsapp.scegli': "Wähle eine Unterhaltung.",
  'whatsapp.c-servizio': "Service",
  'whatsapp.c-marketing': "Werbung",
  'whatsapp.si-no-si': "ja",
  'whatsapp.si-no-no': "nein",
  'whatsapp.fonte-chiedi': "Wie hast du die Entscheidung erfasst? (z. B. Formular im Laden, Website, mündlich)",
  'whatsapp.testo-chiedi': "Der genaue Wortlaut, dem der Kunde zugestimmt hat:",
  'whatsapp.testo-predefinito': "Ich bin einverstanden, WhatsApp-Nachrichten von diesem Geschäft zu erhalten. Ich kann jederzeit STOP antworten.",
  'whatsapp.ok-servizio': "Einwilligung Service",
  'whatsapp.ok-marketing': "Einwilligung Werbung",
  'whatsapp.revoca': "Widerrufen",
  'whatsapp.sconosciuto': "Nummer nicht im Kundenstamm.",
  'whatsapp.crea-cliente': "Kunden anlegen",
  'whatsapp.crea-lead': "Lead anlegen",
  'whatsapp.scrivi': "Antwort schreiben…",
  'whatsapp.serve-modello': "Außerhalb des 24-Stunden-Fensters: wähle eine genehmigte Vorlage",
  'whatsapp.testo-libero': "Freier Text",
  'whatsapp.scegli-modello': "Vorlage wählen",
  'whatsapp.k-servizio': "Service",
  'whatsapp.k-utility': "Service-Info",
  'whatsapp.k-marketing': "Marketing",
  'whatsapp.k-authentication': "Authentifizierung",
  'whatsapp.costo': "Geschätzte Kosten",
  'whatsapp.inviato': "Nachricht gesendet",
  'whatsapp.invia': "Senden",
  'whatsapp.anteprima': "Vorschau",
  'whatsapp.sincronizzati': "Vorlagen aktualisiert",
  'whatsapp.sincronizza': "Vorlagen synchronisieren",
  'whatsapp.salvato': "Gespeichert",
  'whatsapp.modelli-nota': "Jede Variable {{n}} nimmt den Wert eines Felds: zum Beispiel cliente.nome oder riga.quando.",
  'whatsapp.nessun-modello': "Keine Vorlagen: synchronisiere oder erstelle eine.",
  'whatsapp.corpo-esempio': "Hallo {{1}}, deine Bestellung ist fertig.",
  'whatsapp.esempi-esempio': "Mario; Dienstag um 15 Uhr",
  'whatsapp.nuovo-modello': "Neue Vorlage",
  'whatsapp.nuovo-nota': "Meta prüft sie vor der Genehmigung, meist in wenigen Minuten. Jede Variable braucht ein Beispiel. Vorlagen mit PDF-Kopfzeile erstellst du im WhatsApp Manager.",
  'whatsapp.nome': "Name (Kleinbuchstaben, Ziffern, _)",
  'whatsapp.categoria': "Kategorie",
  'whatsapp.lingua': "Sprache",
  'whatsapp.testo': "Text",
  'whatsapp.esempi': "Beispiele der Variablen, getrennt durch ;",
  'whatsapp.mandato-a-meta': "Vorlage zur Genehmigung gesendet",
  'whatsapp.manda-approvazione': "Zur Genehmigung senden",
  'whatsapp.automazioni-nota': "Schalte die ein, die du brauchst, wähle Vorlage und Zeitpunkt. Vor jedem Versand prüft Kubo Einwilligung, STOP, Ruhezeiten und Limits.",
  'whatsapp.o-ore': "Stunden vorher (z. B. 24, 2)",
  'whatsapp.o-giorni': "Nach wie vielen Tagen",
  'whatsapp.o-mesi': "Inaktiv seit Monaten",
  'whatsapp.o-link': "Link zur Bewertung",
  'whatsapp.o-testo': "Antworttext",
  'whatsapp.esempio-da-approvare': "Vorlagenbeispiel: erstelle sie, lass sie genehmigen und wähle sie dann hier.",
  'whatsapp.mancano': "Variablen ohne Wert: {n}",
  'whatsapp.salva': "Speichern",
  'whatsapp.r-promemoria': "Terminerinnerung",
  'whatsapp.r-conferma': "Buchungsbestätigung",
  'whatsapp.r-pronto': "Bestellung fertig oder versandt",
  'whatsapp.r-documento': "Rechnung oder Angebot mit PDF",
  'whatsapp.r-sollecito': "Zahlungserinnerung",
  'whatsapp.r-recensione': "Bewertungsanfrage",
  'whatsapp.r-compleanno': "Geburtstagsgrüße",
  'whatsapp.r-riattivazione': "Inaktive Kunden zurückgewinnen",
  'whatsapp.r-fuori_orario': "Antwort außerhalb der Öffnungszeiten",
  'whatsapp.rd-promemoria': "Eine Nachricht vor dem Termin (24 und 2 Stunden vorher, oder wie du willst).",
  'whatsapp.rd-conferma': "Sobald eine Buchung angelegt wird.",
  'whatsapp.rd-pronto': "Wenn der Status auf fertig oder versandt wechselt, mit Sendungsnummer, falls vorhanden.",
  'whatsapp.rd-documento': "Wenn die Rechnung ausgestellt oder das Angebot gesendet ist: das PDF geht mit einer Vorlage mit Dokument-Kopfzeile.",
  'whatsapp.rd-sollecito': "Jeden Morgen für Rechnungen, die seit N Tagen fällig sind (einmal pro Rechnung).",
  'whatsapp.rd-recensione': "N Tage nach dem Verkauf, mit dem Link zu deiner Bewertungsseite.",
  'whatsapp.rd-compleanno': "Am Morgen des Kundengeburtstags.",
  'whatsapp.rd-riattivazione': "An Kunden, die seit N Monaten nicht wiederkamen, einmalig.",
  'whatsapp.rd-fuori_orario': "Wenn ein Kunde außerhalb der Öffnungszeiten schreibt: freier Text, höchstens alle 12 Stunden.",
  'whatsapp.serve-marketing': "Werbung: nur an Kunden mit Werbe-Einwilligung, nie in der Ruhezeit.",
  'whatsapp.non-possibile': "Deiner Verwaltung fehlen die Bereiche oder Felder für diese Automation.",
  'whatsapp.modello': "Vorlage",
  'whatsapp.i-prefisso': "Standard-Ländervorwahl",
  'whatsapp.i-silenzio-da': "Ruhe ab",
  'whatsapp.i-silenzio-a': "bis",
  'whatsapp.i-silenzio-tutti': "Ruhezeit auch für automatische Servicenachrichten",
  'whatsapp.i-limite-giorno': "Vorlagen pro Tag, insgesamt",
  'whatsapp.i-limite-cliente': "Vorlagen pro Tag und Kunde",
  'whatsapp.i-marketing-giorni': "Eine Werbenachricht alle wie viele Tage",
  'whatsapp.i-sconosciuti': "Absender nicht im Kundenstamm",
  'whatsapp.i-apre': "Öffnet um",
  'whatsapp.i-chiude': "Schließt um",
  'whatsapp.i-giorni': "Öffnungstage (0 = Sonntag)",
  'whatsapp.i-t-marketing': "Marketing, € pro Nachricht",
  'whatsapp.i-t-utility': "Service-Info, € pro Nachricht",
  'whatsapp.i-t-authentication': "Authentifizierung, € pro Nachricht",
  'whatsapp.i-t-servizio': "Service, € über dem Freikontingent",
  'whatsapp.i-t-servizioGratisMese': "Kostenlose Servicenachrichten pro Monat (leer = alle)",
  'whatsapp.i-t-twilio': "Twilio-Aufschlag, € pro Nachricht",
  'whatsapp.sc-chiedi': "Mich fragen (bleibt eine Nummer)",
  'whatsapp.sc-cliente': "Kunden anlegen",
  'whatsapp.sc-lead': "Lead anlegen",
  'whatsapp.webhook': "Webhook-Adresse",
  'whatsapp.webhook-meta': "Füge sie bei Meta ein (WhatsApp → Konfiguration) mit dem Verifizierungstoken von der Connector-Seite und abonniere messages und message_template_status_update. Sie muss aus dem Internet per https erreichbar sein.",
  'whatsapp.webhook-360': "Kubo registriert ihn selbst bei 360dialog, sobald die öffentliche Adresse auf der Connector-Seite steht.",
  'whatsapp.webhook-twilio': "Füge sie beim WhatsApp-Absender von Twilio als Adresse für eingehende Nachrichten ein. Die öffentliche Adresse des Connectors muss der entsprechen, die Twilio sieht.",
  'whatsapp.apri-connettore': "Connector öffnen",
  'whatsapp.costi-mese': "Diesen Monat",
  'whatsapp.nessun-costo': "Diesen Monat keine kostenpflichtigen Nachrichten.",
  'whatsapp.costi-nota': "Schätzung mit Metas Preisen für Italien ({data}): maßgeblich ist die Rechnung von Meta oder deinem Anbieter.",
  'whatsapp.regole': "Versandregeln",
  'whatsapp.tariffe': "Preise",
  'whatsapp.tariffe-nota': "Meta aktualisiert die Preisliste jedes Quartal: korrigiere die Beträge hier, wenn sie sich ändern.",
  'whatsapp.registro': "Gestoppte oder fehlgeschlagene Nachrichten",
  'whatsapp.registro-vuoto': "Nichts zu melden.",
  'whatsapp.storia': "WhatsApp-Verlauf",
  'whatsapp.senza-numero': "Der Kunde hat keine Telefonnummer.",
  'whatsapp.apri-chat': "Unterhaltung öffnen",
};
