// I messaggi del nucleo dei connettori nelle sei lingue. Il nucleo lancia gli errori con una chiave (errore(stato, chiave, p))
// e li riscrive nella lingua di chi chiede prima che la risposta parta (suErrore in connettori.js): così il catalogo comune
// del server (server/moduli/lingue/) non cambia. test/connettori.test.mjs controlla che le sei lingue abbiano le stesse chiavi.
export const TESTI = {
  it: {
    sconosciuto: 'Connettore sconosciuto', spento: 'Connettore spento o inesistente', 'giro-sconosciuto': 'Giro pianificato sconosciuto',
    'azione-sconosciuta': 'Azione sconosciuta', 'solo-titolare': 'Solo il titolare gestisce i connettori, e solo dall\'interfaccia',
    'impostazione-sconosciuta': 'Impostazione sconosciuta: {nome}', 'mappa-non-valida': 'Abbinamento non valido: {nome}', 'valore-non-valido': 'Valore non valido: {nome}',
    'indirizzo-non-valido': 'Indirizzo non valido o nella rete interna: {nome}', 'somma-diversa': 'La somma di controllo non corrisponde: il file del connettore è cambiato, ricontrollalo',
    'oauth-rifiutato': 'Il servizio non ha dato l\'accesso (risposta {stato})', 'oauth-scollegato': 'Account non collegato: collegalo dalla pagina del connettore',
    'oauth-no': 'Questo connettore non usa questo tipo di collegamento', troppe: 'Troppe richieste: riprova fra un minuto', 'troppo-grande': 'Richiesta troppo grande',
    'non-configurato': 'Connettore non ancora configurato', firma: 'Firma non valida', corpo: 'Corpo della richiesta non leggibile',
    'servizio': 'Il servizio non ha completato l\'operazione: {dettaglio}',
    'ricette-elenco': "Le ricette sono un elenco",
    'ricette-troppe': "Al massimo 100 ricette",
    'ricetta-id': "Ricetta {n}: id «{id}» non valido o doppio",
    'ricetta-tipo': "Ricetta {n}: tipo «{tipo}» non valido ({tipi})",
    'ricetta-sezione': "Ricetta {n}: la sezione «{sezione}» non c'è",
    'ricetta-campo': "Ricetta {n}: il campo «{campo}» non c'è nella sezione",
    'ricetta-serve-chiave': "Ricetta {n}: per aggiornare serve un campo chiave (es. l'email)",
    'ricetta-percorso-json': "Ricetta {n}: il percorso «{percorso}» non è valido (es. data.email)",
    'ricetta-manca-percorso': "Ricetta {n}: manca il percorso o l'indirizzo",
    'ricetta-http': "Ricetta {n}: l'indirizzo deve iniziare con http:// o https://",
    'ricetta-rete': "Ricetta {n}: indirizzo non valido o nella rete interna (permettila nella pagina, se serve)",
    'ricetta-assoluto': "Ricetta {n}: serve l'indirizzo completo che ti dà la piattaforma (https://…)",
    'ricetta-barra': "Ricetta {n}: il percorso inizia con «/» (o è un indirizzo completo)",
    'ricette-base': "Manca l'indirizzo base del servizio",
    'ricette-intestazioni': "Le intestazioni sono un oggetto JSON con nomi semplici (lettere, numeri, trattini)",
    'ricette-righe': "Al massimo 500 righe per richiesta",
    'ricette-risposta': "Il servizio ha risposto {stato} ({dettaglio})",
    'copia-no': "Di questo connettore non si fanno copie",
    'copia-nome': "Dai un nome al servizio (lettere o cifre)",
    'copia-doppia': "C'è già un connettore «{nome}»",
    'copia-accesa': "Spegnilo prima di toglierlo",
  },
  en: {
    sconosciuto: 'Unknown connector', spento: 'Connector off or missing', 'giro-sconosciuto': 'Unknown scheduled run',
    'azione-sconosciuta': 'Unknown action', 'solo-titolare': 'Only the owner manages connectors, and only from the interface',
    'impostazione-sconosciuta': 'Unknown setting: {nome}', 'mappa-non-valida': 'Invalid field match: {nome}', 'valore-non-valido': 'Invalid value: {nome}',
    'indirizzo-non-valido': 'Invalid address, or on the internal network: {nome}', 'somma-diversa': 'The checksum does not match: the connector file changed, check it again',
    'oauth-rifiutato': 'The service did not grant access (response {stato})', 'oauth-scollegato': 'Account not connected: connect it from the connector page',
    'oauth-no': 'This connector does not use this kind of connection', troppe: 'Too many requests: try again in a minute', 'troppo-grande': 'Request too large',
    'non-configurato': 'Connector not configured yet', firma: 'Invalid signature', corpo: 'Unreadable request body',
    'servizio': 'The service did not complete the operation: {dettaglio}',
    'ricette-elenco': "Recipes must be a list",
    'ricette-troppe': "At most 100 recipes",
    'ricetta-id': "Recipe {n}: id «{id}» invalid or duplicated",
    'ricetta-tipo': "Recipe {n}: invalid type «{tipo}» ({tipi})",
    'ricetta-sezione': "Recipe {n}: section «{sezione}» does not exist",
    'ricetta-campo': "Recipe {n}: field «{campo}» is not in the section",
    'ricetta-serve-chiave': "Recipe {n}: updating needs a key field (e.g. the email)",
    'ricetta-percorso-json': "Recipe {n}: path «{percorso}» is not valid (e.g. data.email)",
    'ricetta-manca-percorso': "Recipe {n}: the path or address is missing",
    'ricetta-http': "Recipe {n}: the address must start with http:// or https://",
    'ricetta-rete': "Recipe {n}: invalid address, or on the internal network (allow it on the page if needed)",
    'ricetta-assoluto': "Recipe {n}: it needs the full address the platform gives you (https://…)",
    'ricetta-barra': "Recipe {n}: the path starts with «/» (or is a full address)",
    'ricette-base': "The service base address is missing",
    'ricette-intestazioni': "Headers are a JSON object with simple names (letters, digits, dashes)",
    'ricette-righe': "At most 500 rows per request",
    'ricette-risposta': "The service answered {stato} ({dettaglio})",
    'copia-no': "This connector cannot be copied",
    'copia-nome': "Give the service a name (letters or digits)",
    'copia-doppia': "There is already a connector «{nome}»",
    'copia-accesa': "Switch it off before removing it",
  },
  es: {
    sconosciuto: 'Conector desconocido', spento: 'Conector apagado o inexistente', 'giro-sconosciuto': 'Tarea programada desconocida',
    'azione-sconosciuta': 'Acción desconocida', 'solo-titolare': 'Solo el titular gestiona los conectores, y solo desde la interfaz',
    'impostazione-sconosciuta': 'Ajuste desconocido: {nome}', 'mappa-non-valida': 'Correspondencia no válida: {nome}', 'valore-non-valido': 'Valor no válido: {nome}',
    'indirizzo-non-valido': 'Dirección no válida o en la red interna: {nome}', 'somma-diversa': 'La suma de control no coincide: el archivo del conector cambió, revísalo',
    'oauth-rifiutato': 'El servicio no dio acceso (respuesta {stato})', 'oauth-scollegato': 'Cuenta no conectada: conéctala desde la página del conector',
    'oauth-no': 'Este conector no usa este tipo de conexión', troppe: 'Demasiadas solicitudes: inténtalo en un minuto', 'troppo-grande': 'Solicitud demasiado grande',
    'non-configurato': 'Conector aún no configurado', firma: 'Firma no válida', corpo: 'Cuerpo de la solicitud ilegible',
    'servizio': 'El servicio no completó la operación: {dettaglio}',
    'ricette-elenco': "Las recetas son una lista",
    'ricette-troppe': "Como máximo 100 recetas",
    'ricetta-id': "Receta {n}: id «{id}» no válido o duplicado",
    'ricetta-tipo': "Receta {n}: tipo «{tipo}» no válido ({tipi})",
    'ricetta-sezione': "Receta {n}: la sección «{sezione}» no existe",
    'ricetta-campo': "Receta {n}: el campo «{campo}» no está en la sección",
    'ricetta-serve-chiave': "Receta {n}: para actualizar hace falta un campo clave (p. ej. el email)",
    'ricetta-percorso-json': "Receta {n}: la ruta «{percorso}» no es válida (p. ej. data.email)",
    'ricetta-manca-percorso': "Receta {n}: falta la ruta o la dirección",
    'ricetta-http': "Receta {n}: la dirección debe empezar por http:// o https://",
    'ricetta-rete': "Receta {n}: dirección no válida o en la red interna (permítela en la página si hace falta)",
    'ricetta-assoluto': "Receta {n}: hace falta la dirección completa que te da la plataforma (https://…)",
    'ricetta-barra': "Receta {n}: la ruta empieza por «/» (o es una dirección completa)",
    'ricette-base': "Falta la dirección base del servicio",
    'ricette-intestazioni': "Las cabeceras son un objeto JSON con nombres simples (letras, números, guiones)",
    'ricette-righe': "Como máximo 500 filas por petición",
    'ricette-risposta': "El servicio respondió {stato} ({dettaglio})",
    'copia-no': "De este conector no se hacen copias",
    'copia-nome': "Ponle un nombre al servicio (letras o cifras)",
    'copia-doppia': "Ya existe un conector «{nome}»",
    'copia-accesa': "Apágalo antes de quitarlo",
  },
  fr: {
    sconosciuto: 'Connecteur inconnu', spento: 'Connecteur éteint ou inexistant', 'giro-sconosciuto': 'Tâche planifiée inconnue',
    'azione-sconosciuta': 'Action inconnue', 'solo-titolare': 'Seul le titulaire gère les connecteurs, et seulement depuis l\'interface',
    'impostazione-sconosciuta': 'Réglage inconnu : {nome}', 'mappa-non-valida': 'Correspondance non valide : {nome}', 'valore-non-valido': 'Valeur non valide : {nome}',
    'indirizzo-non-valido': 'Adresse non valide ou sur le réseau interne : {nome}', 'somma-diversa': 'La somme de contrôle ne correspond pas : le fichier du connecteur a changé, vérifiez-le',
    'oauth-rifiutato': 'Le service n\'a pas donné l\'accès (réponse {stato})', 'oauth-scollegato': 'Compte non connecté : connectez-le depuis la page du connecteur',
    'oauth-no': 'Ce connecteur n\'utilise pas ce type de connexion', troppe: 'Trop de requêtes : réessayez dans une minute', 'troppo-grande': 'Requête trop volumineuse',
    'non-configurato': 'Connecteur pas encore configuré', firma: 'Signature non valide', corpo: 'Corps de la requête illisible',
    'servizio': 'Le service n\'a pas terminé l\'opération : {dettaglio}',
    'ricette-elenco': "Les recettes sont une liste",
    'ricette-troppe': "100 recettes au maximum",
    'ricetta-id': "Recette {n} : id « {id} » non valide ou en double",
    'ricetta-tipo': "Recette {n} : type « {tipo} » non valide ({tipi})",
    'ricetta-sezione': "Recette {n} : la section « {sezione} » n'existe pas",
    'ricetta-campo': "Recette {n} : le champ « {campo} » n'est pas dans la section",
    'ricetta-serve-chiave': "Recette {n} : pour mettre à jour il faut un champ clé (ex. l'e-mail)",
    'ricetta-percorso-json': "Recette {n} : le chemin « {percorso} » n'est pas valide (ex. data.email)",
    'ricetta-manca-percorso': "Recette {n} : il manque le chemin ou l'adresse",
    'ricetta-http': "Recette {n} : l'adresse doit commencer par http:// ou https://",
    'ricetta-rete': "Recette {n} : adresse non valide ou sur le réseau interne (autorisez-le sur la page si besoin)",
    'ricetta-assoluto': "Recette {n} : il faut l'adresse complète fournie par la plateforme (https://…)",
    'ricetta-barra': "Recette {n} : le chemin commence par « / » (ou est une adresse complète)",
    'ricette-base': "Il manque l'adresse de base du service",
    'ricette-intestazioni': "Les en-têtes sont un objet JSON aux noms simples (lettres, chiffres, tirets)",
    'ricette-righe': "500 lignes par requête au maximum",
    'ricette-risposta': "Le service a répondu {stato} ({dettaglio})",
    'copia-no': "Ce connecteur ne peut pas être copié",
    'copia-nome': "Donnez un nom au service (lettres ou chiffres)",
    'copia-doppia': "Il existe déjà un connecteur « {nome} »",
    'copia-accesa': "Désactivez-le avant de le retirer",
  },
  de: {
    sconosciuto: 'Unbekannter Connector', spento: 'Connector aus oder nicht vorhanden', 'giro-sconosciuto': 'Unbekannter geplanter Lauf',
    'azione-sconosciuta': 'Unbekannte Aktion', 'solo-titolare': 'Nur der Inhaber verwaltet Connectoren, und nur über die Oberfläche',
    'impostazione-sconosciuta': 'Unbekannte Einstellung: {nome}', 'mappa-non-valida': 'Ungültige Zuordnung: {nome}', 'valore-non-valido': 'Ungültiger Wert: {nome}',
    'indirizzo-non-valido': 'Ungültige Adresse oder im internen Netz: {nome}', 'somma-diversa': 'Die Prüfsumme stimmt nicht: Die Datei des Connectors hat sich geändert, prüfe sie erneut',
    'oauth-rifiutato': 'Der Dienst hat den Zugriff verweigert (Antwort {stato})', 'oauth-scollegato': 'Konto nicht verbunden: Verbinde es auf der Seite des Connectors',
    'oauth-no': 'Dieser Connector nutzt diese Verbindungsart nicht', troppe: 'Zu viele Anfragen: Versuche es in einer Minute erneut', 'troppo-grande': 'Anfrage zu groß',
    'non-configurato': 'Connector noch nicht eingerichtet', firma: 'Ungültige Signatur', corpo: 'Anfrageinhalt nicht lesbar',
    'servizio': 'Der Dienst hat den Vorgang nicht abgeschlossen: {dettaglio}',
    'ricette-elenco': "Rezepte sind eine Liste",
    'ricette-troppe': "Höchstens 100 Rezepte",
    'ricetta-id': "Rezept {n}: ID „{id}“ ungültig oder doppelt",
    'ricetta-tipo': "Rezept {n}: ungültiger Typ „{tipo}“ ({tipi})",
    'ricetta-sezione': "Rezept {n}: Bereich „{sezione}“ existiert nicht",
    'ricetta-campo': "Rezept {n}: Feld „{campo}“ ist nicht im Bereich",
    'ricetta-serve-chiave': "Rezept {n}: zum Aktualisieren braucht es ein Schlüsselfeld (z. B. die E-Mail)",
    'ricetta-percorso-json': "Rezept {n}: Pfad „{percorso}“ ist ungültig (z. B. data.email)",
    'ricetta-manca-percorso': "Rezept {n}: Pfad oder Adresse fehlt",
    'ricetta-http': "Rezept {n}: die Adresse muss mit http:// oder https:// beginnen",
    'ricetta-rete': "Rezept {n}: ungültige Adresse oder im internen Netz (bei Bedarf auf der Seite erlauben)",
    'ricetta-assoluto': "Rezept {n}: es braucht die vollständige Adresse der Plattform (https://…)",
    'ricetta-barra': "Rezept {n}: der Pfad beginnt mit „/“ (oder ist eine vollständige Adresse)",
    'ricette-base': "Die Basisadresse des Dienstes fehlt",
    'ricette-intestazioni': "Header sind ein JSON-Objekt mit einfachen Namen (Buchstaben, Ziffern, Bindestriche)",
    'ricette-righe': "Höchstens 500 Zeilen pro Anfrage",
    'ricette-risposta': "Der Dienst antwortete {stato} ({dettaglio})",
    'copia-no': "Dieser Konnektor kann nicht kopiert werden",
    'copia-nome': "Gib dem Dienst einen Namen (Buchstaben oder Ziffern)",
    'copia-doppia': "Es gibt schon einen Konnektor „{nome}“",
    'copia-accesa': "Schalte ihn aus, bevor du ihn entfernst",
  },
  pt: {
    sconosciuto: 'Conector desconhecido', spento: 'Conector desligado ou inexistente', 'giro-sconosciuto': 'Execução agendada desconhecida',
    'azione-sconosciuta': 'Ação desconhecida', 'solo-titolare': 'Só o titular gerencia os conectores, e só pela interface',
    'impostazione-sconosciuta': 'Configuração desconhecida: {nome}', 'mappa-non-valida': 'Correspondência inválida: {nome}', 'valore-non-valido': 'Valor inválido: {nome}',
    'indirizzo-non-valido': 'Endereço inválido ou na rede interna: {nome}', 'somma-diversa': 'A soma de verificação não confere: o arquivo do conector mudou, verifique-o',
    'oauth-rifiutato': 'O serviço não deu acesso (resposta {stato})', 'oauth-scollegato': 'Conta não conectada: conecte-a pela página do conector',
    'oauth-no': 'Este conector não usa este tipo de conexão', troppe: 'Solicitações demais: tente de novo em um minuto', 'troppo-grande': 'Solicitação grande demais',
    'non-configurato': 'Conector ainda não configurado', firma: 'Assinatura inválida', corpo: 'Corpo da solicitação ilegível',
    'servizio': 'O serviço não concluiu a operação: {dettaglio}',
    'ricette-elenco': "As receitas são uma lista",
    'ricette-troppe': "No máximo 100 receitas",
    'ricetta-id': "Receita {n}: id «{id}» inválido ou duplicado",
    'ricetta-tipo': "Receita {n}: tipo «{tipo}» inválido ({tipi})",
    'ricetta-sezione': "Receita {n}: a seção «{sezione}» não existe",
    'ricetta-campo': "Receita {n}: o campo «{campo}» não está na seção",
    'ricetta-serve-chiave': "Receita {n}: para atualizar é preciso um campo chave (ex. o email)",
    'ricetta-percorso-json': "Receita {n}: o caminho «{percorso}» não é válido (ex. data.email)",
    'ricetta-manca-percorso': "Receita {n}: falta o caminho ou o endereço",
    'ricetta-http': "Receita {n}: o endereço deve começar com http:// ou https://",
    'ricetta-rete': "Receita {n}: endereço inválido ou na rede interna (permita na página, se precisar)",
    'ricetta-assoluto': "Receita {n}: é preciso o endereço completo que a plataforma lhe dá (https://…)",
    'ricetta-barra': "Receita {n}: o caminho começa com «/» (ou é um endereço completo)",
    'ricette-base': "Falta o endereço base do serviço",
    'ricette-intestazioni': "Os cabeçalhos são um objeto JSON com nomes simples (letras, números, hífens)",
    'ricette-righe': "No máximo 500 linhas por requisição",
    'ricette-risposta': "O serviço respondeu {stato} ({dettaglio})",
    'copia-no': "Este conector não pode ser copiado",
    'copia-nome': "Dê um nome ao serviço (letras ou números)",
    'copia-doppia': "Já existe um conector «{nome}»",
    'copia-accesa': "Desative antes de remover",
  },
};
export const testo = (l, chiave, p = {}) => String(TESTI[l]?.[chiave] ?? TESTI.it[chiave] ?? chiave).replace(/\{(\w+)\}/g, (x, k) => (k in p ? String(p[k]) : x));
