// I messaggi del modulo WhatsApp nelle sei lingue: gli errori e i motivi per cui un messaggio non parte.
// Il modulo li lancia con una chiave (errore(stato, chiave, p)) e li riscrive nella lingua di chi chiede (suErrore in
// whatsapp.js), come fa il nucleo dei connettori. test/whatsapp.test.mjs controlla che le lingue abbiano le stesse chiavi.
export const TESTI = {
  it: {
    'cambiato': 'Nel frattempo è cambiato qualcosa (la finestra di 24 ore o il modello): rifai l\'anteprima',
    'lumi.titolo': 'Messaggio WhatsApp', 'lumi.a': 'A', 'lumi.finestra': 'Finestra di 24 ore', 'lumi.aperta': 'aperta fino a {ora}', 'lumi.chiusa': 'chiusa: si usa un modello approvato', 'lumi.modello': 'Modello', 'lumi.messaggio': 'Messaggio', 'lumi.costo': 'Costo stimato',
    'nessun-provider': 'WhatsApp non è collegato: accendi un connettore WhatsApp (Meta, Twilio o 360dialog)',
    'un-provider': 'È già acceso {attivo}: spegnilo prima di accendere un altro servizio WhatsApp',
    numero: 'Numero di telefono non valido: {numero}', 'senza-numero': 'Il cliente non ha un numero di telefono',
    stop: 'Il cliente ha chiesto di non ricevere più messaggi (STOP il {quando})',
    'consenso-servizio': 'Manca il consenso del cliente a ricevere messaggi WhatsApp di servizio',
    'consenso-marketing': 'Manca il consenso del cliente ai messaggi promozionali su WhatsApp',
    'finestra-chiusa': 'La finestra di 24 ore è chiusa: serve un modello approvato',
    silenzio: 'Ore di silenzio ({da}–{a}): niente messaggi promozionali adesso',
    'limite-giorno': 'Raggiunto il limite di {n} messaggi al giorno', 'limite-cliente': 'Raggiunto il limite di {n} messaggi al giorno per questo cliente',
    'limite-marketing': 'Questo cliente ha già ricevuto un messaggio promozionale negli ultimi {giorni} giorni',
    'modello-sconosciuto': 'Modello sconosciuto o non approvato: {nome}', variabili: 'Mancano i valori delle variabili {n} del modello',
    vuoto: 'Il messaggio è vuoto', 'cliente-sconosciuto': 'Cliente non trovato: {nome}', 'clienti-ambigui': 'Più clienti si chiamano così: {nomi}. Quale?',
    'non-supportato': 'Il servizio WhatsApp attivo non permette questa operazione', 'solo-titolare': 'Solo il titolare cambia le impostazioni di WhatsApp',
    'ricetta-sconosciuta': 'Automazione WhatsApp sconosciuta', 'invio-fallito': 'Il servizio WhatsApp ha rifiutato il messaggio: {dettaglio}',
    'modello-nome': 'Nome del modello non valido: solo lettere minuscole, numeri e trattini bassi', documento: 'Documento non trovato',
    indirizzo: 'Per mandare un file con Twilio serve l\'indirizzo pubblico di Kubo nella pagina del connettore',
    'nessun-modello': 'Nessun modello approvato adatto: creane uno o sincronizza i modelli', 'senza-rubrica': 'Non c\'è una sezione clienti con il telefono',
  },
  en: {
    'cambiato': 'Something changed in the meantime (the 24-hour window or the template): preview it again',
    'lumi.titolo': 'WhatsApp message', 'lumi.a': 'To', 'lumi.finestra': '24-hour window', 'lumi.aperta': 'open until {ora}', 'lumi.chiusa': 'closed: an approved template is used', 'lumi.modello': 'Template', 'lumi.messaggio': 'Message', 'lumi.costo': 'Estimated cost',
    'nessun-provider': 'WhatsApp is not connected: turn on a WhatsApp connector (Meta, Twilio or 360dialog)',
    'un-provider': '{attivo} is already on: turn it off before turning on another WhatsApp service',
    numero: 'Invalid phone number: {numero}', 'senza-numero': 'The customer has no phone number',
    stop: 'The customer asked to stop receiving messages (STOP on {quando})',
    'consenso-servizio': 'The customer has not agreed to receive WhatsApp service messages',
    'consenso-marketing': 'The customer has not agreed to promotional WhatsApp messages',
    'finestra-chiusa': 'The 24-hour window is closed: an approved template is needed',
    silenzio: 'Quiet hours ({da}–{a}): no promotional messages now',
    'limite-giorno': 'Daily limit of {n} messages reached', 'limite-cliente': 'Limit of {n} messages a day for this customer reached',
    'limite-marketing': 'This customer already got a promotional message in the last {giorni} days',
    'modello-sconosciuto': 'Unknown or unapproved template: {nome}', variabili: 'Template variables {n} have no value',
    vuoto: 'The message is empty', 'cliente-sconosciuto': 'Customer not found: {nome}', 'clienti-ambigui': 'Several customers have this name: {nomi}. Which one?',
    'non-supportato': 'The active WhatsApp service does not allow this', 'solo-titolare': 'Only the owner changes the WhatsApp settings',
    'ricetta-sconosciuta': 'Unknown WhatsApp automation', 'invio-fallito': 'The WhatsApp service rejected the message: {dettaglio}',
    'modello-nome': 'Invalid template name: lowercase letters, numbers and underscores only', documento: 'Document not found',
    indirizzo: 'To send a file with Twilio, set Kubo\'s public address on the connector page',
    'nessun-modello': 'No suitable approved template: create one or sync the templates', 'senza-rubrica': 'There is no customer section with a phone field',
  },
  es: {
    'cambiato': 'Algo ha cambiado mientras tanto (la ventana de 24 horas o la plantilla): vuelve a ver la vista previa',
    'lumi.titolo': 'Mensaje de WhatsApp', 'lumi.a': 'Para', 'lumi.finestra': 'Ventana de 24 horas', 'lumi.aperta': 'abierta hasta {ora}', 'lumi.chiusa': 'cerrada: se usa una plantilla aprobada', 'lumi.modello': 'Plantilla', 'lumi.messaggio': 'Mensaje', 'lumi.costo': 'Coste estimado',
    'nessun-provider': 'WhatsApp no está conectado: activa un conector de WhatsApp (Meta, Twilio o 360dialog)',
    'un-provider': '{attivo} ya está activo: apágalo antes de activar otro servicio de WhatsApp',
    numero: 'Número de teléfono no válido: {numero}', 'senza-numero': 'El cliente no tiene número de teléfono',
    stop: 'El cliente pidió no recibir más mensajes (STOP el {quando})',
    'consenso-servizio': 'Falta el consentimiento del cliente para recibir mensajes de servicio por WhatsApp',
    'consenso-marketing': 'Falta el consentimiento del cliente para mensajes promocionales por WhatsApp',
    'finestra-chiusa': 'La ventana de 24 horas está cerrada: hace falta una plantilla aprobada',
    silenzio: 'Horas de silencio ({da}–{a}): ahora no se envían mensajes promocionales',
    'limite-giorno': 'Alcanzado el límite de {n} mensajes al día', 'limite-cliente': 'Alcanzado el límite de {n} mensajes al día para este cliente',
    'limite-marketing': 'Este cliente ya recibió un mensaje promocional en los últimos {giorni} días',
    'modello-sconosciuto': 'Plantilla desconocida o no aprobada: {nome}', variabili: 'Faltan los valores de las variables {n} de la plantilla',
    vuoto: 'El mensaje está vacío', 'cliente-sconosciuto': 'Cliente no encontrado: {nome}', 'clienti-ambigui': 'Varios clientes se llaman así: {nomi}. ¿Cuál?',
    'non-supportato': 'El servicio de WhatsApp activo no permite esta operación', 'solo-titolare': 'Solo el titular cambia los ajustes de WhatsApp',
    'ricetta-sconosciuta': 'Automatización de WhatsApp desconocida', 'invio-fallito': 'El servicio de WhatsApp rechazó el mensaje: {dettaglio}',
    'modello-nome': 'Nombre de plantilla no válido: solo minúsculas, números y guiones bajos', documento: 'Documento no encontrado',
    indirizzo: 'Para enviar un archivo con Twilio indica la dirección pública de Kubo en la página del conector',
    'nessun-modello': 'Ninguna plantilla aprobada adecuada: crea una o sincroniza las plantillas', 'senza-rubrica': 'No hay una sección de clientes con teléfono',
  },
  fr: {
    'cambiato': 'Quelque chose a changé entre-temps (la fenêtre de 24 heures ou le modèle) : refais l\'aperçu',
    'lumi.titolo': 'Message WhatsApp', 'lumi.a': 'À', 'lumi.finestra': 'Fenêtre de 24 heures', 'lumi.aperta': 'ouverte jusqu\'à {ora}', 'lumi.chiusa': 'fermée : un modèle approuvé est utilisé', 'lumi.modello': 'Modèle', 'lumi.messaggio': 'Message', 'lumi.costo': 'Coût estimé',
    'nessun-provider': 'WhatsApp n\'est pas connecté : activez un connecteur WhatsApp (Meta, Twilio ou 360dialog)',
    'un-provider': '{attivo} est déjà actif : désactivez-le avant d\'activer un autre service WhatsApp',
    numero: 'Numéro de téléphone non valide : {numero}', 'senza-numero': 'Le client n\'a pas de numéro de téléphone',
    stop: 'Le client a demandé à ne plus recevoir de messages (STOP le {quando})',
    'consenso-servizio': 'Le client n\'a pas consenti aux messages de service WhatsApp',
    'consenso-marketing': 'Le client n\'a pas consenti aux messages promotionnels WhatsApp',
    'finestra-chiusa': 'La fenêtre de 24 heures est fermée : il faut un modèle approuvé',
    silenzio: 'Heures de silence ({da}–{a}) : pas de messages promotionnels maintenant',
    'limite-giorno': 'Limite de {n} messages par jour atteinte', 'limite-cliente': 'Limite de {n} messages par jour atteinte pour ce client',
    'limite-marketing': 'Ce client a déjà reçu un message promotionnel ces {giorni} derniers jours',
    'modello-sconosciuto': 'Modèle inconnu ou non approuvé : {nome}', variabili: 'Les variables {n} du modèle n\'ont pas de valeur',
    vuoto: 'Le message est vide', 'cliente-sconosciuto': 'Client introuvable : {nome}', 'clienti-ambigui': 'Plusieurs clients portent ce nom : {nomi}. Lequel ?',
    'non-supportato': 'Le service WhatsApp actif ne permet pas cette opération', 'solo-titolare': 'Seul le titulaire modifie les réglages WhatsApp',
    'ricetta-sconosciuta': 'Automatisation WhatsApp inconnue', 'invio-fallito': 'Le service WhatsApp a refusé le message : {dettaglio}',
    'modello-nome': 'Nom de modèle non valide : minuscules, chiffres et tirets bas uniquement', documento: 'Document introuvable',
    indirizzo: 'Pour envoyer un fichier avec Twilio, indiquez l\'adresse publique de Kubo sur la page du connecteur',
    'nessun-modello': 'Aucun modèle approuvé adapté : créez-en un ou synchronisez les modèles', 'senza-rubrica': 'Aucune section clients avec un téléphone',
  },
  de: {
    'cambiato': 'Inzwischen hat sich etwas geändert (das 24-Stunden-Fenster oder die Vorlage): Vorschau erneut anzeigen',
    'lumi.titolo': 'WhatsApp-Nachricht', 'lumi.a': 'An', 'lumi.finestra': '24-Stunden-Fenster', 'lumi.aperta': 'offen bis {ora}', 'lumi.chiusa': 'geschlossen: eine genehmigte Vorlage wird verwendet', 'lumi.modello': 'Vorlage', 'lumi.messaggio': 'Nachricht', 'lumi.costo': 'Geschätzte Kosten',
    'nessun-provider': 'WhatsApp ist nicht verbunden: schalte einen WhatsApp-Connector ein (Meta, Twilio oder 360dialog)',
    'un-provider': '{attivo} ist bereits an: schalte ihn aus, bevor du einen anderen WhatsApp-Dienst einschaltest',
    numero: 'Ungültige Telefonnummer: {numero}', 'senza-numero': 'Der Kunde hat keine Telefonnummer',
    stop: 'Der Kunde möchte keine Nachrichten mehr erhalten (STOP am {quando})',
    'consenso-servizio': 'Die Einwilligung des Kunden für WhatsApp-Servicenachrichten fehlt',
    'consenso-marketing': 'Die Einwilligung des Kunden für WhatsApp-Werbenachrichten fehlt',
    'finestra-chiusa': 'Das 24-Stunden-Fenster ist geschlossen: eine genehmigte Vorlage ist nötig',
    silenzio: 'Ruhezeit ({da}–{a}): jetzt keine Werbenachrichten',
    'limite-giorno': 'Tageslimit von {n} Nachrichten erreicht', 'limite-cliente': 'Limit von {n} Nachrichten pro Tag für diesen Kunden erreicht',
    'limite-marketing': 'Dieser Kunde hat in den letzten {giorni} Tagen schon eine Werbenachricht erhalten',
    'modello-sconosciuto': 'Unbekannte oder nicht genehmigte Vorlage: {nome}', variabili: 'Den Variablen {n} der Vorlage fehlen Werte',
    vuoto: 'Die Nachricht ist leer', 'cliente-sconosciuto': 'Kunde nicht gefunden: {nome}', 'clienti-ambigui': 'Mehrere Kunden heißen so: {nomi}. Welcher?',
    'non-supportato': 'Der aktive WhatsApp-Dienst erlaubt das nicht', 'solo-titolare': 'Nur der Inhaber ändert die WhatsApp-Einstellungen',
    'ricetta-sconosciuta': 'Unbekannte WhatsApp-Automation', 'invio-fallito': 'Der WhatsApp-Dienst hat die Nachricht abgelehnt: {dettaglio}',
    'modello-nome': 'Ungültiger Vorlagenname: nur Kleinbuchstaben, Ziffern und Unterstriche', documento: 'Dokument nicht gefunden',
    indirizzo: 'Um mit Twilio eine Datei zu senden, trage die öffentliche Adresse von Kubo auf der Connector-Seite ein',
    'nessun-modello': 'Keine passende genehmigte Vorlage: erstelle eine oder synchronisiere die Vorlagen', 'senza-rubrica': 'Es gibt keinen Kundenbereich mit Telefon',
  },
  pt: {
    'cambiato': 'Algo mudou entretanto (a janela de 24 horas ou o modelo): refaz a pré-visualização',
    'lumi.titolo': 'Mensagem de WhatsApp', 'lumi.a': 'Para', 'lumi.finestra': 'Janela de 24 horas', 'lumi.aperta': 'aberta até {ora}', 'lumi.chiusa': 'fechada: usa-se um modelo aprovado', 'lumi.modello': 'Modelo', 'lumi.messaggio': 'Mensagem', 'lumi.costo': 'Custo estimado',
    'nessun-provider': 'O WhatsApp não está conectado: ative um conector WhatsApp (Meta, Twilio ou 360dialog)',
    'un-provider': '{attivo} já está ativo: desative-o antes de ativar outro serviço WhatsApp',
    numero: 'Número de telefone inválido: {numero}', 'senza-numero': 'O cliente não tem número de telefone',
    stop: 'O cliente pediu para não receber mais mensagens (STOP em {quando})',
    'consenso-servizio': 'Falta o consentimento do cliente para mensagens de serviço no WhatsApp',
    'consenso-marketing': 'Falta o consentimento do cliente para mensagens promocionais no WhatsApp',
    'finestra-chiusa': 'A janela de 24 horas está fechada: é preciso um modelo aprovado',
    silenzio: 'Horas de silêncio ({da}–{a}): nada de mensagens promocionais agora',
    'limite-giorno': 'Limite de {n} mensagens por dia atingido', 'limite-cliente': 'Limite de {n} mensagens por dia atingido para este cliente',
    'limite-marketing': 'Este cliente já recebeu uma mensagem promocional nos últimos {giorni} dias',
    'modello-sconosciuto': 'Modelo desconhecido ou não aprovado: {nome}', variabili: 'Faltam os valores das variáveis {n} do modelo',
    vuoto: 'A mensagem está vazia', 'cliente-sconosciuto': 'Cliente não encontrado: {nome}', 'clienti-ambigui': 'Vários clientes têm este nome: {nomi}. Qual?',
    'non-supportato': 'O serviço WhatsApp ativo não permite esta operação', 'solo-titolare': 'Só o titular altera as configurações do WhatsApp',
    'ricetta-sconosciuta': 'Automação de WhatsApp desconhecida', 'invio-fallito': 'O serviço WhatsApp recusou a mensagem: {dettaglio}',
    'modello-nome': 'Nome de modelo inválido: só minúsculas, números e sublinhados', documento: 'Documento não encontrado',
    indirizzo: 'Para enviar um arquivo com o Twilio, informe o endereço público do Kubo na página do conector',
    'nessun-modello': 'Nenhum modelo aprovado adequado: crie um ou sincronize os modelos', 'senza-rubrica': 'Não há uma seção de clientes com telefone',
  },
};
export const testo = (l, chiave, p = {}) => String((TESTI[l] || TESTI.it)[chiave] ?? TESTI.it[chiave] ?? chiave).replace(/\{(\w+)\}/g, (x, k) => (k in p ? String(p[k]) : x));
