// Compras (web/moduli/acquisti.js): reposição, pedidos a caminho, recebimentos, faturas de fornecedores.
export default {
  'acquisti.titolo': "Compras",
  'acquisti.scheda-riordino': "Para repor",
  'acquisti.scheda-arrivo': "A caminho",
  'acquisti.scheda-fatture': "Faturas de fornecedores",
  'acquisti.stato-bozza': "Rascunho",
  'acquisti.stato-inviato': "Enviado",
  'acquisti.stato-parziale': "Recebido em parte",
  'acquisti.stato-arrivato': "Recebido",
  'acquisti.stato-annullato': "Cancelado",
  'acquisti.serve-magazzino': "As compras precisam de uma seção com estoque (artigos, peças, materiais…).",
  'acquisti.non-pronti': "As compras ainda não estão prontas.",
  'acquisti.chiedi-titolare': "Peça a quem pode personalizar o sistema.",
  'acquisti.magazzino': "Seção do estoque",
  'acquisti.prepara-titolo': "Preparar as compras",
  'acquisti.prepara-nota': "O Lumi usa os «Pedidos a fornecedores» que já existem, ou os cria, e adiciona a quantidade recebida, a situação «recebido em parte», a nota de entrega e a fatura do fornecedor. Seus dados não mudam.",
  'acquisti.prepara': "Preparar",
  'acquisti.preparati': {"one": "{n} item adicionado", "other": "{n} itens adicionados"},
  'acquisti.niente-riordino': "Nada abaixo do mínimo: tudo acima do limite, ou já pedido.",
  'acquisti.fornitore': "Fornecedor",
  'acquisti.scegli-fornitore': "Escolha o fornecedor…",
  'acquisti.da-ordinare': "A pedir",
  'acquisti.senza-fornitore': "Sem fornecedor",
  'acquisti.senza-fornitore-nota': "Estes artigos não têm fornecedor na ficha: escolha aqui.",
  'acquisti.articolo': "Artigo",
  'acquisti.giacenza': "Estoque",
  'acquisti.soglia': "Mínimo",
  'acquisti.in-arrivo': "A caminho",
  'acquisti.costo': "Custo",
  'acquisti.totale-stimato': "Total estimado: {importo}",
  'acquisti.niente-scelto': "Você não escolheu nada para pedir",
  'acquisti.ordini-creati': {"one": "{n} pedido criado em rascunho", "other": "{n} pedidos criados em rascunho"},
  'acquisti.riordino-nota': "Abaixo do mínimo quer dizer estoque mais o que já foi pedido sem passar do limite. O Lumi sugere voltar ao dobro do limite: ajuste as quantidades como quiser.",
  'acquisti.crea-ordini': "Criar os pedidos",
  'acquisti.crea-nota': "Um pedido em rascunho por fornecedor: confira e envie.",
  'acquisti.in-ritardo': "Atrasado: previsto para {data}",
  'acquisti.previsto': "Previsto para {data}",
  'acquisti.ricevi': "Receber mercadoria",
  'acquisti.ricevute-di': "{ricevuta} de {quantita}",
  'acquisti.niente-arrivo': "Nenhum pedido a caminho.",
  'acquisti.ordine-chiuso': "Este pedido já está fechado.",
  'acquisti.vedi-confronto': "Ver a comparação",
  'acquisti.ddt-segnaposto': "Número e data da nota de entrega",
  'acquisti.ricevuto-tutto': "Mercadoria recebida: pedido completo",
  'acquisti.ricevuto-parte': "Mercadoria recebida: o pedido continua aberto para o resto",
  'acquisti.ricevi-titolo': "Receber mercadoria: {numero}, {fornitore}",
  'acquisti.ddt': "Nota de entrega do fornecedor",
  'acquisti.data': "Data",
  'acquisti.ordinate': "Pedidas",
  'acquisti.gia-ricevute': "Já recebidas",
  'acquisti.arrivate-ora': "Chegaram agora",
  'acquisti.ricevi-nota': "As quantidades que chegaram entram logo no estoque e o custo do artigo passa a ser o custo médio ponderado. O que falta continua a caminho.",
  'acquisti.carica': "Dar entrada no estoque",
  'acquisti.annulla': "Cancelar",
  'acquisti.senza-fatture': "Para associar faturas é preciso o modelo «Faturas e nota fiscal eletrônica».",
  'acquisti.ordine': "Pedido",
  'acquisti.ricevuto': "Recebido",
  'acquisti.fattura-proposta': "Fatura sugerida",
  'acquisti.candidata': "{numero}: {importo}",
  'acquisti.nessuna-fattura': "Nenhuma fatura deste fornecedor",
  'acquisti.confronta': "Comparar",
  'acquisti.tutto-fatturato': "Cada mercadoria recebida tem sua fatura.",
  'acquisti.fatture-nota': "O Lumi compara o valor da mercadoria recebida com a base de cálculo das faturas do fornecedor. Bate se a diferença for de até R$ 1 ou 1%.",
  'acquisti.abbinata': "Fatura associada",
  'acquisti.tolta': "Fatura removida",
  'acquisti.ordinato': "Pedido",
  'acquisti.fatturato': "Faturado",
  'acquisti.confronto-titolo': "{numero} · {fornitore}",
  'acquisti.torna': "Bate com a fatura {numero}.",
  'acquisti.non-torna': "A fatura {numero} não bate: diferença {importo}.",
  'acquisti.togli': "Remover",
  'acquisti.candidate': "Faturas candidatas",
  'acquisti.fattura': "Fatura",
  'acquisti.imponibile': "Base de cálculo",
  'acquisti.differenza': "Diferença",
  'acquisti.abbina': "Associar",
  'acquisti.ricevimenti': "Recebimentos",
  'acquisti.quantita': "Quantidade",
};
