// Area «avvio» (web/moduli/avvio.js) · Português (Brasil).
export default {
  'avvio.avanti': "Avançar",
  'avvio.indietro': "← Voltar",
  'avvio.azienda-es': "ex.: Ateliê Ferri",
  'avvio.sottotitolo': "Dez perguntas e o seu sistema de gestão fica pronto, sob medida para o seu trabalho. Dá para mudar tudo depois.",
  'avvio.nome-attivita': "Qual é o nome do seu negócio?",
  'avvio.d-settore': "Com o que você trabalha?",
  'avvio.a-settore': "Escolha o mais parecido. Depois dá para mudar tudo.",
  'avvio.o-settore-negozio': "Loja e comércio",
  'avvio.sd-negozio': "Vendo no balcão, com produtos e estoque",
  'avvio.o-settore-ristorante': "Restaurante e bar",
  'avvio.sd-ristorante': "Mesas, comandas, cardápio com alérgenos, reservas",
  'avvio.o-settore-laboratorio': "Ateliê e artesanato",
  'avvio.sd-laboratorio': "Orçamentos, pedidos em etapas, materiais",
  'avvio.o-settore-officina': "Oficina e assistência técnica",
  'avvio.sd-officina': "Veículos ou aparelhos, serviços, peças, garantias",
  'avvio.o-settore-studio': "Consultório e serviços",
  'avvio.sd-studio': "Agenda, fichas de clientes, pacotes de sessões",
  'avvio.o-settore-beauty': "Beleza e estética",
  'avvio.sd-beauty': "Agenda por sala, tratamentos, pacotes, produtos",
  'avvio.o-settore-palestra': "Academia e associação",
  'avvio.sd-palestra': "Membros, planos e renovações, aulas e presenças",
  'avvio.o-settore-professionista': "Profissional liberal e agência",
  'avvio.sd-professionista': "Clientes, projetos, horas, prazos, orçamentos",
  'avvio.o-settore-noleggio': "Aluguel",
  'avvio.sd-noleggio': "Bens, disponibilidade, contratos de/até, cauções",
  'avvio.o-settore-altro': "Outro, começo do zero",
  'avvio.sd-altro': "Um sistema vazio: você cria as seções",
  'avvio.d-offerta': "Você vende produtos, serviços ou os dois?",
  'avvio.o-offerta-prodotti': "Produtos",
  'avvio.o-offerta-servizi': "Serviços",
  'avvio.o-offerta-entrambi': "Os dois",
  'avvio.d-magazzino': "Você tem estoque?",
  'avvio.a-magazzino': "Saldos, estoque mínimo, o que repor.",
  'avvio.d-su_misura': "Você faz trabalhos sob medida, com orçamentos?",
  'avvio.a-su_misura': "O orçamento com os itens; quando o cliente aceita, o trabalho é aberto.",
  'avvio.d-appuntamenti': "Você marca horários ou recebe reservas?",
  'avvio.a-appuntamenti': "Uma agenda por pessoa ou por recurso.",
  'avvio.d-fornitori': "Você compra de fornecedores?",
  'avvio.a-fornitori': "Cadastro de fornecedores e, se você tem estoque, os pedidos com a entrada de mercadoria.",
  'avvio.d-fatture': "Você emite notas fiscais?",
  'avvio.a-fatture': "Numeradas por ano, com impostos, vencimentos e o arquivo da nota fiscal eletrônica.",
  'avvio.d-persone': "Quantas pessoas vão usar o Lumi?",
  'avvio.o-persone-solo': "Só eu",
  'avvio.o-persone-poche': "De 2 a 5",
  'avvio.o-persone-molte': "Mais de 5",
  'avvio.d-squadra': "Quem trabalha com você?",
  'avvio.a-squadra': "Cada um entra com o próprio e-mail e vê o que o seu papel precisa. Dá para fazer depois também.",
  'avvio.d-lumi': "Quer o Lumi, o assistente?",
  'avvio.a-lumi': "Você pede as coisas com palavras: “quanto vendi esta semana?”, “adicione o tamanho aos produtos”. Ele propõe, você confirma.",
  'avvio.d-esempi': "Quer ver o sistema com dados de exemplo?",
  'avvio.a-esempi': "Clientes, vendas e agendamentos fictícios, mas realistas, para testar tudo. Somem com um clique.",
  'avvio.o-si': "Sim",
  'avvio.o-no': "Não",
  'avvio.collaboratore': "Colaborador (vê e edita, não exclui)",
  'avvio.lettura': "Somente leitura",
  'avvio.nome': "Nome",
  'avvio.ruolo': "Papel",
  'avvio.togli': "Remover",
  'avvio.altra-persona': "+ Outra pessoa",
  'avvio.password-provvisoria': "Cada um recebe uma senha provisória, que você vai ver no final.",
  'avvio.sezioni': "Vou preparar estas seções para você",
  'avvio.nessuna-sezione': "Nenhuma: você começa do zero",
  'avvio.campi-spenti': { one: "{n} campo de que você não precisa fica desativado (dá para reativar em {personalizza})", other: "{n} campos de que você não precisa ficam desativados (dá para reativar em {personalizza})" },
  'avvio.persone-ruolo': { one: "Uma pessoa com o seu papel", other: "{n} pessoas, cada uma com o seu papel" },
  'avvio.lumi-acceso': "Lumi ligado",
  'avvio.lumi-spento': "Lumi desligado (você liga quando quiser)",
  'avvio.con-esempi': "Com dados de exemplo, que saem com um clique",
  'avvio.senza-esempi': "Sem dados de exemplo",
  'avvio.ci-siamo': "Quase lá",
  'avvio.chi-sei': "Última coisa: quem é você? Você será o proprietário, quem pode tudo.",
  'avvio.preparo': "Preparando o Lumi…",
  'avvio.prepara': "Preparar o Lumi",
  'avvio.pronto': "O Lumi está pronto",
  'avvio.consegna': "Entregue a cada um a sua senha provisória. Esta tela não aparece de novo: copie as senhas agora.",
  'avvio.entra': "Entrar no Lumi",
  'avvio.tappa-sezioni': "Suas seções",
  'avvio.tappa-sezioni-testo': "Aqui está todo o sistema{esempi}. Cada seção é uma lista que você pode pesquisar, filtrar, ordenar e ver em colunas.",
  'avvio.tappa-personalizza-testo': "Falta um campo? Sobra algum? Daqui você adiciona, renomeia e move campos sem nunca perder dados. Seções novas você cria em “{nuova}”.",
  'avvio.tappa-lumi-testo': "Peça com palavras: “quanto vendi esta semana?”, “adicione o tamanho aos produtos”. O Lumi lê com as suas permissões e propõe; você decide.",
  'avvio.tappa-cruscotto': "O painel",
  'avvio.tappa-cruscotto-testo': "Os números que importam e o que pede atenção, atualizados enquanto você trabalha. Dá para mudar em “{modifica}”, no alto.",
  'avvio.n-di': "{n} de {tot}",
  'avvio.salta': "Pular",
  'avvio.capito': "Entendi",
  'avvio.promemoria': "Você está vendo dados de exemplo",
  'avvio.toglili': "Remover",
  'avvio.conferma-togli': "Remover todos os dados de exemplo? O que você adicionou continua lá.",
  'avvio.tolte': { one: "{n} linha de exemplo removida", other: "{n} linhas de exemplo removidas" },
  'avvio.aggiunte': { one: "{n} linha de exemplo adicionada", other: "{n} linhas de exemplo adicionadas" },
  'avvio.togli-esempi': "Remover os dados de exemplo",
  'avvio.rimetti-esempi': "Colocar os dados de exemplo de volta",
  'avvio.pagina-titolo': "Dados de exemplo e tour guiado",
  'avvio.ci-sono': { one: "Há {n} linha de exemplo, para testar o Lumi sem medo. Quando estiver pronto, remova-a: ela some (mesmo se você a editou), o que você cadastrou continua e, onde ainda não há nada seu, a numeração recomeça do 1.", other: "Há {n} linhas de exemplo: clientes, movimentações e agendamentos fictícios, para testar o Lumi sem medo. Quando estiver pronto, remova-as: somem todas (até as que você editou), o que você cadastrou continua e, onde ainda não há nada seu, a numeração recomeça do 1." },
  'avvio.solo-titolare': "Só o proprietário pode removê-los.",
  'avvio.nessun-esempio': "Não há dados de exemplo.",
  'avvio.rivedere': "Quer rever onde fica cada coisa?",
  'avvio.rifai-giro': "Refazer o tour guiado",
  'avvio.lato': "Dados de exemplo e tour",
  'avvio.lato-sezione': "Primeiros passos",
};
