export default {
  'comune.benvenuto': 'Boas-vindas ao Kubo',
  'comune.benvenuto-sotto': 'O sistema de gestão que você monta do seu jeito. Comece com um modelo e depois mude tudo o que quiser.',
  'comune.nome-azienda': 'Nome da empresa',
  'comune.tuo-nome': 'Seu nome',
  'comune.email': 'E-mail',
  'comune.password': 'Senha',
  'comune.password-nuova': 'Senha (pelo menos 8 caracteres)',
  'comune.valuta': 'Moeda',
  'comune.da-dove': 'Por onde começamos? (dá para adicionar outros depois)',
  'comune.codice-avvio': "Código de início (aparece no terminal ou no log onde o Kubo roda)",
  'comune.codice-avvio-es': "ex.: 3FA9C2D1",
  'comune.inizia': 'Começar',
  'comune.lingua': 'Idioma',
  'comune.accedi-per': 'Entre para continuar.',
  'comune.accedi': 'Entrar',
  'comune.gestione': 'Gestão',
  'comune.nuova-sezione': 'Nova seção',
  'comune.persone-permessi': 'Pessoas e permissões',
  'comune.esci': 'Sair',
  'comune.personalizza': 'Personalizar',
  'comune.personalizza-sezione': 'Personalizar esta seção',
  'comune.nessuna-sezione': 'Ainda não há seções.',
  'comune.creane-una': 'Criar uma',
  'comune.chiedi-titolare': 'Peça ao proprietário para criar uma.',
  'comune.qualcosa-non-va': 'Algo deu errado',
  'comune.errore-n': 'Erro {stato}',
  'comune.percento': '{n}%',
  'comune.si': 'Sim',
  'comune.no': 'Não',
  'comune.si-min': 'sim',
  'comune.no-min': 'não',
  'comune.su': 'Subir',
  'comune.giu': 'Descer',
  'comune.togli': 'Remover',
  'comune.cerca': 'Buscar…',
  'comune.carico': 'Carregando…',
  'comune.avviso-esempi-aggiunti': "Dados de exemplo adicionados",
  'comune.avviso-esempi-tolti': "Dados de exemplo removidos",
};
