export default {
  'connettori.terzi': "Um conector de terceiros é copiado na pasta «connettori» ao lado dos dados: você o liga aqui depois de conferir a soma.",
  'connettori.locale': "Instalado à mão",
  'connettori.rotto': "O conector não carrega: confira o arquivo connettore.js",
  'connettori.stato-acceso': "Ligado",
  'connettori.stato-spento': "Desligado",
  'connettori.stato-incompleto': "A completar",
  'connettori.stato-cambiato': "Alterado",
  'connettori.stato-rotto': "Quebrado",
  'connettori.mancano': "Ainda falta: {cosa}",
  'connettori.cambiato': "O arquivo do conector mudou depois de ligado: fica parado até você ligá-lo de novo conferindo a soma.",
  'connettori.accendi': "Ligar",
  'connettori.spegni': "Desligar",
  'connettori.accendi-titolo': "Ligar {nome}?",
  'connettori.potra': "Ele poderá:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "ler",
  'connettori.p-crea': "criar",
  'connettori.p-modifica': "editar",
  'connettori.p-elimina': "excluir",
  'connettori.somma': "Soma de verificação (SHA-256) do arquivo: compare com a publicada pelo autor.",
  'connettori.da-approvare': "O código deste conector ainda não foi executado: o Lumi só o carrega depois que você confirmar a soma abaixo. Depois você verá as seções que ele pode usar.",
  'connettori.impostazioni': "Configurações",
  'connettori.salvato-segreto': "Salvo",
  'connettori.cambia': "Trocar",
  'connettori.togli': "Remover",
  'connettori.interni': "Permitir endereços da rede interna (um servidor na loja, um caixa)",
  'connettori.salva': "Salvar",
  'connettori.salvato': "Salvo",
  'connettori.prova': "Testar a conexão",
  'connettori.provo': "Testando…",
  'connettori.prova-ok': "Conexão funcionando",
  'connettori.prova-no': "Não funciona: {motivo}",
  'connettori.collegamento': "Conexão",
  'connettori.webhook': "Endereço do webhook",
  'connettori.webhook-aiuto': "Cole nas configurações de webhooks do serviço.",
  'connettori.indirizzo-segreto': "Endereço secreto",
  'connettori.indirizzo-aiuto': "Quem tem este endereço vê os dados: passe só para quem precisa.",
  'connettori.account': "Conta",
  'connettori.collegato': "Conectada",
  'connettori.scollegato': "Não conectada",
  'connettori.scade': "Expira {quando}",
  'connettori.collega': "Conectar a conta",
  'connettori.ricollega': "Reconectar",
  'connettori.oauth-ok': "Conta conectada",
  'connettori.oauth-scaduto': "A conexão expirou: tente de novo",
  'connettori.oauth-errore': "A conexão falhou: veja o registro",
  'connettori.abbinamenti': "Correspondência dos campos",
  'connettori.abbinamenti-aiuto': "Os campos do conector e os do Lumi: se você renomear um campo, a correspondência continua.",
  'connettori.sezione-manca': "Falta a seção «{nome}»",
  'connettori.facoltativo': "opcional",
  'connettori.salva-abbinamenti': "Salvar as correspondências",
  'connettori.sincronizzazioni': "Sincronizações",
  'connettori.ogni': "a cada {ogni}",
  'connettori.alle': "às {alle}",
  'connettori.ultimo': "Última execução: {quando}",
  'connettori.prossimo': "próxima: {quando}",
  'connettori.sincronizza': "Sincronizar agora",
  'connettori.giro-ok': "Feito",
  'connettori.coda': "Na fila: {attesa} · falharam: {fallite}",
  'connettori.riprova': "Tentar de novo as que falharam",
  'connettori.registro': "Registro",
  'connettori.registro-vuoto': "Nada ainda: aqui você vê o que chega e o que sai.",
  'connettori.col-quando': "Quando",
  'connettori.col-verso': "Sentido",
  'connettori.col-esito': "Resultado",
  'connettori.col-cosa': "O quê",
  'connettori.verso-entrata': "entrada",
  'connettori.verso-uscita': "saída",
  'connettori.verso-giro': "execução agendada",
  'connettori.verso-azione': "ação",
  'connettori.verso-prova': "teste",
  'connettori.verso-oauth': "conta",
  'connettori.verso-sistema': "sistema",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "erro",
  'connettori.esito-avviso': "aviso",
  'connettori.esito-ignorato': "ignorado",
  'connettori.copia': "Copiar",
  'connettori.copiato': "Copiado",
  'connettori.annulla': "Cancelar",
  'connettori.conferma': "Confirmar",
  'connettori.fatto': "Feito",
  // la libreria delle integrazioni e le ricette
  'connettori.libreria': "Biblioteca de integrações",
  'connettori.libreria-sotto': "{n} integrações · {accese} ativas. As chaves ficam criptografadas no Lumi e nunca voltam ao navegador.",
  'connettori.cerca': "Buscar: Stripe, fatura, WhatsApp, envios…",
  'connettori.categorie': "Categorias",
  'connettori.tutte': "Todas",
  'connettori.trovate': "{n} encontradas",
  'connettori.le-tue': "Ativas",
  'connettori.nessuna': "Nenhuma integração encontrada.",
  'connettori.prova-http': "Não está? Conecte com HTTP / API REST",
  'connettori.smanettoni': "Para quem gosta de mexer: a API do Lumi está descrita em OpenAPI 3.1 em /api/openapi-3.1.json, e um conector novo é uma pasta com um arquivo (docs/CONNETTORI.md).",
  'connettori.f-gratis': "Grátis",
  'connettori.f-facili': "Fáceis",
  'connettori.f-italia': "Itália",
  'connettori.stato-da-approvare': "A aprovar",
  'connettori.cat-pagamenti': "Pagamentos",
  'connettori.cat-cassa': "Caixa e POS",
  'connettori.cat-negozi-online': "Lojas online",
  'connettori.cat-marketplace': "Marketplaces",
  'connettori.cat-fatturazione': "Faturação",
  'connettori.cat-contabilita': "Contabilidade",
  'connettori.cat-banche': "Bancos",
  'connettori.cat-spedizioni': "Envios",
  'connettori.cat-whatsapp': "WhatsApp",
  'connettori.cat-messaggi': "Mensagens",
  'connettori.cat-email': "Email",
  'connettori.cat-sms': "SMS",
  'connettori.cat-calendario': "Calendário",
  'connettori.cat-prenotazioni': "Reservas",
  'connettori.cat-archivio': "Arquivo e ficheiros",
  'connettori.cat-produttivita': "Produtividade",
  'connettori.cat-marketing': "Marketing",
  'connettori.cat-recensioni': "Avaliações",
  'connettori.cat-firma': "Assinatura",
  'connettori.cat-dati-aziende': "Dados de empresas",
  'connettori.cat-automazione': "Automação",
  'connettori.cat-ia': "Inteligência artificial",
  'connettori.cat-altro': "Outros",
  'connettori.costo-gratis': "Grátis",
  'connettori.costo-a-consumo': "Por uso",
  'connettori.costo-abbonamento': "Assinatura",
  'connettori.costo-contratto': "Com contrato",
  'connettori.diff-facile': "Fácil",
  'connettori.diff-media': "Média",
  'connettori.diff-difficile': "Para entendidos",
  'connettori.zona-IT': "Itália",
  'connettori.zona-UE': "Europa",
  'connettori.zona-mondo': "Mundo",
  'connettori.prova-finto': "Testado com um serviço simulado",
  'connettori.prova-vero': "Testado com o serviço real",
  'connettori.prova-finto-aiuto': "Os testes automáticos usam um serviço simulado que responde como o real, segundo a documentação das fontes: antes de confiar, teste em modo de teste.",
  'connettori.prova-vero-aiuto': "Este conector também foi testado com o serviço real.",
  'connettori.sito': "Site do serviço",
  'connettori.apri': "Abrir",
  'connettori.cosa-serve': "O que você precisa",
  'connettori.passi': "Passo a passo",
  'connettori.costo': "Custo",
  'connettori.difficolta': "Dificuldade",
  'connettori.fonti': "Fontes ({n})",
  'connettori.permessi-titolo': "O que poderá tocar",
  'connettori.nessun-permesso': "Nenhuma seção do Lumi: só as chamadas que você configurar.",
  'connettori.r-nessuna': "Ainda não há receitas. Adicione uma:",
  'connettori.r-tipo-uscita': "De saída: quando uma linha muda",
  'connettori.r-tipo-azione': "Botão na ficha e Lumi",
  'connettori.r-tipo-entrata': "De entrada: o serviço escreve no Lumi",
  'connettori.r-nome': "Nome da receita",
  'connettori.r-attiva': "Ativa",
  'connettori.r-sezione': "Seção",
  'connettori.r-eventi': "Quando a linha é",
  'connettori.ev-crea': "criada",
  'connettori.ev-modifica': "alterada",
  'connettori.ev-elimina': "eliminada",
  'connettori.ev-ripristina': "restaurada",
  'connettori.r-metodo': "Método",
  'connettori.r-percorso': "Caminho (após o endereço base) ou endereço completo",
  'connettori.r-indirizzo': "Endereço que a plataforma lhe dá (https://…)",
  'connettori.r-corpo': "Corpo (JSON com marcadores; vazio = a linha inteira)",
  'connettori.r-segnaposto': "Marcadores: {campi}",
  'connettori.r-scrive': "Mostra a pré-visualização e pede confirmação antes de enviar",
  'connettori.r-modo': "Se a linha já existe",
  'connettori.modo-crea-o-aggiorna': "atualize, senão crie",
  'connettori.modo-crea': "crie sempre uma linha nova",
  'connettori.modo-aggiorna': "só atualizar",
  'connettori.r-chiave': "Campo chave (para encontrar a linha)",
  'connettori.r-elenco': "Lista no JSON (opcional, ex. items)",
  'connettori.r-idevento': "Id do evento no JSON (opcional, contra duplicados)",
  'connettori.r-campi': "Correspondências (vazio = as chaves do JSON com os mesmos nomes dos campos)",
  'connettori.r-da': "Caminho no JSON (ex. cliente.email)",
  'connettori.r-a': "Campo do Lumi",
  'connettori.r-aggiungi-campo': "Adicionar uma correspondência",
  'connettori.r-indirizzo-entrata': "Endereço para o serviço (POST JSON)",
  'connettori.r-salva-prima': "Salve e ative para ver o endereço.",
  'connettori.copia': "Conectar outro serviço assim",
  'connettori.copia-aiuto': "Um segundo serviço com o seu endereço, a sua autenticação e as suas receitas.",
  'connettori.copia-nome': "Nome do serviço (ex. CRM)",
  'connettori.copia-crea': "Criar",
  'connettori.copia-di': "Cópia de «{nome}»",
  'connettori.togli-copia': "Remover este serviço",
  'connettori.togli-copia-conferma': "Remover «{nome}» com as suas configurações, segredos e registro?",
  'connettori.tutte-lettura': "Todas as secções (só leitura)",
  'connettori.tutte-sezioni': "Todas as secções",
  'connettori.dispositivo': "Ligar com um código",
  'connettori.dispositivo-titolo': "Ligar {nome} com um código",
  'connettori.dispositivo-passi': "Abra o endereço abaixo (também no telemóvel), entre no serviço e escreva este código. O Lumi verifica sozinho a cada poucos segundos: pode deixar esta janela aberta.",
  'connettori.dispositivo-attesa': "À espera da confirmação…",
  'connettori.dispositivo-scaduto': "O código expirou ou a janela foi fechada: prima de novo «Ligar com um código».",
  'connettori.dispositivo-chiudi': "Fechar",
  'connettori.ritorno': "Endereço de retorno (registe-o no serviço)",
  'connettori.pubblico-titolo': "Endereço público do Lumi",
  'connettori.pubblico-aiuto': "O endereço com que os serviços chegam ao Lumi pela internet (ex.: https://lumi.loja.pt). Usam-no os webhooks e os retornos de todos os conectores; vazio = o do navegador.",
  'connettori.pubblico-salvato': "Endereço guardado",
  'connettori.r-con-accesso': "Enviar a chave ou o token mesmo que o endereço esteja noutro site",
};
