export default {
  'connettori.titolo': "Conectores",
  'connettori.spiega': "Conecte o Kubo aos serviços que você já usa: pagamentos, loja online, nota fiscal eletrônica, email, calendário. As chaves ficam criptografadas no Kubo e nunca voltam ao navegador.",
  'connettori.terzi': "Um conector de terceiros é copiado na pasta «connettori» ao lado dos dados: você o liga aqui depois de conferir a soma.",
  'connettori.ufficiale': "Oficial",
  'connettori.locale': "Instalado à mão",
  'connettori.rotto': "O conector não carrega: confira o arquivo connettore.js",
  'connettori.stato-acceso': "Ligado",
  'connettori.stato-spento': "Desligado",
  'connettori.stato-incompleto': "A completar",
  'connettori.stato-cambiato': "Alterado",
  'connettori.stato-rotto': "Quebrado",
  'connettori.mancano': "Ainda falta: {cosa}",
  'connettori.cambiato': "O arquivo do conector mudou depois de ligado: fica parado até você ligá-lo de novo conferindo a soma.",
  'connettori.accendi': "Ligar",
  'connettori.spegni': "Desligar",
  'connettori.accendi-titolo': "Ligar {nome}?",
  'connettori.potra': "Ele poderá:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "ler",
  'connettori.p-crea': "criar",
  'connettori.p-modifica': "editar",
  'connettori.p-elimina': "excluir",
  'connettori.somma': "Soma de verificação (SHA-256) do arquivo: compare com a publicada pelo autor.",
  'connettori.impostazioni': "Configurações",
  'connettori.salvato-segreto': "Salvo",
  'connettori.cambia': "Trocar",
  'connettori.togli': "Remover",
  'connettori.interni': "Permitir endereços da rede interna (um servidor na loja, um caixa)",
  'connettori.salva': "Salvar",
  'connettori.salvato': "Salvo",
  'connettori.prova': "Testar a conexão",
  'connettori.provo': "Testando…",
  'connettori.prova-ok': "Conexão funcionando",
  'connettori.prova-no': "Não funciona: {motivo}",
  'connettori.collegamento': "Conexão",
  'connettori.webhook': "Endereço do webhook",
  'connettori.webhook-aiuto': "Cole nas configurações de webhooks do serviço.",
  'connettori.indirizzo-segreto': "Endereço secreto",
  'connettori.indirizzo-aiuto': "Quem tem este endereço vê os dados: passe só para quem precisa.",
  'connettori.account': "Conta",
  'connettori.collegato': "Conectada",
  'connettori.scollegato': "Não conectada",
  'connettori.scade': "Expira {quando}",
  'connettori.collega': "Conectar a conta",
  'connettori.ricollega': "Reconectar",
  'connettori.oauth-ok': "Conta conectada",
  'connettori.oauth-scaduto': "A conexão expirou: tente de novo",
  'connettori.oauth-errore': "A conexão falhou: veja o registro",
  'connettori.abbinamenti': "Correspondência dos campos",
  'connettori.abbinamenti-aiuto': "Os campos do conector e os do Kubo: se você renomear um campo, a correspondência continua.",
  'connettori.sezione-manca': "Falta a seção «{nome}»",
  'connettori.facoltativo': "opcional",
  'connettori.salva-abbinamenti': "Salvar as correspondências",
  'connettori.sincronizzazioni': "Sincronizações",
  'connettori.ogni': "a cada {ogni}",
  'connettori.alle': "às {alle}",
  'connettori.ultimo': "Última execução: {quando}",
  'connettori.prossimo': "próxima: {quando}",
  'connettori.sincronizza': "Sincronizar agora",
  'connettori.giro-ok': "Feito",
  'connettori.coda': "Na fila: {attesa} · falharam: {fallite}",
  'connettori.riprova': "Tentar de novo as que falharam",
  'connettori.registro': "Registro",
  'connettori.registro-vuoto': "Nada ainda: aqui você vê o que chega e o que sai.",
  'connettori.col-quando': "Quando",
  'connettori.col-verso': "Sentido",
  'connettori.col-esito': "Resultado",
  'connettori.col-cosa': "O quê",
  'connettori.verso-entrata': "entrada",
  'connettori.verso-uscita': "saída",
  'connettori.verso-giro': "execução agendada",
  'connettori.verso-azione': "ação",
  'connettori.verso-prova': "teste",
  'connettori.verso-oauth': "conta",
  'connettori.verso-sistema': "sistema",
  'connettori.copia': "Copiar",
  'connettori.copiato': "Copiado",
  'connettori.annulla': "Cancelar",
  'connettori.conferma': "Confirmar",
  'connettori.fatto': "Feito",
};
