// Area «desktop» (web/moduli/desktop.js): rete, backup e versioni nuove.
export default {
  'desktop.tipo-giornaliero': "Diário",
  'desktop.tipo-modifica': "Antes de uma alteração",
  'desktop.tipo-manuale': "Manual",
  'desktop.tipo-sicurezza': "Antes de uma restauração",
  'desktop.tipo-caricato': "Enviado de fora",
  'desktop.qr': "QR code com o endereço",
  'desktop.rete-titolo': "Conectar outros dispositivos",
  'desktop.lato-rete': "Conectar dispositivos",
  'desktop.un-momento': "Um momento…",
  'desktop.copiato': "Copiado",
  'desktop.copia-fallita': "Não foi possível copiar: selecione à mão",
  'desktop.indirizzo': "Endereço",
  'desktop.altra-rete': "Ou, em outra rede do escritório",
  'desktop.copia-indirizzo': "Copiar o endereço",
  'desktop.codice': "Código",
  'desktop.passo-telefono': "Celular ou tablet:",
  'desktop.passo-telefono-testo': "aponte a câmera para o código e toque no link.",
  'desktop.passo-computer': "Outro computador:",
  'desktop.passo-computer-codice': "abra o navegador e digite o endereço. No app Lumi, escolha “Conectar ao Lumi na rede” e digite o código.",
  'desktop.passo-computer-indirizzo': "abra o navegador e digite o endereço. No app Lumi, escolha “Conectar ao Lumi na rede” e digite o endereço.",
  'desktop.solo-qui': "Agora o Lumi só responde a este computador.",
  'desktop.apri-rete': "Para usar também nos outros dispositivos, no app Lumi abra o menu na barra superior (ou na área de notificação) e ative “Aberto à rede local”.",
  'desktop.da-terminale': "Se você o inicia pelo terminal:",
  'desktop.non-in-rete': "Este computador não parece conectado a uma rede. Conecte-o ao Wi-Fi ou ao cabo do escritório e recarregue a página.",
  'desktop.stessa-rete': "Os outros dispositivos precisam estar na mesma rede (o mesmo Wi-Fi ou o mesmo cabo). Se não conectarem, verifique se o firewall deste computador deixa o Lumi passar.",
  'desktop.backup': "Backups",
  'desktop.fai-adesso': "Fazer backup agora",
  'desktop.copia-in-corso': "Copiando…",
  'desktop.fatto': "Backup feito",
  'desktop.ultimo': "Último backup",
  'desktop.nessuno-ancora': "Nenhum ainda",
  'desktop.copie-tenute': "Cópias guardadas",
  'desktop.in-tutto': "{peso} no total",
  'desktop.spiega-automatici': "Todo dia o Lumi faz sozinho uma cópia do banco de dados, e outra antes de cada alteração na estrutura ou de cada importação. Guarda {giornalieri} cópias diárias, {settimanali} semanais e {mensili} mensais; as feitas à mão ficam até você excluí-las. Os anexos vão para a pasta “allegati”, copiando só os novos.",
  'desktop.spiega-spenti': "Os backups automáticos estão desligados (LUMI_BACKUP=0): lembre-se de fazê-los à mão ou com suas próprias ferramentas.",
  'desktop.cartella-esempio': "Por exemplo {a} ou {b}",
  'desktop.cartella-nuova': "A partir de agora os backups vão para lá",
  'desktop.cartella-tornata': "Os backups voltam para junto dos dados",
  'desktop.scegli-cartella': "Escolher uma pasta…",
  'desktop.dove': "Para onde vão os backups",
  'desktop.in-memoria': "(banco de dados em memória: sem backups)",
  'desktop.nota-esterna': "Uma pasta escolhida por você. Se o disco não estiver conectado, a cópia do dia vai para junto dos dados e aparece um aviso aqui.",
  'desktop.nota-accanto': "Junto dos dados, neste computador. Melhor ter uma segunda cópia em outro lugar: um disco externo ou uma pasta sincronizada (Dropbox, OneDrive, iCloud, Google Drive).",
  'desktop.usa-cartella': "Usar esta pasta",
  'desktop.torna-accanto': "Voltar para junto dos dados",
  'desktop.vuoto': "Nenhum backup ainda. O primeiro chega sozinho em poucos minutos, ou faça agora.",
  'desktop.col-quando': "Quando",
  'desktop.col-tipo': "Tipo",
  'desktop.col-dimensione': "Tamanho",
  'desktop.accanto-ai-dati': "junto dos dados",
  'desktop.scarica': "Baixar",
  'desktop.ripristina': "Restaurar",
  'desktop.elimina': "Excluir este backup",
  'desktop.elimina-conferma': "Excluir o backup de {quando}? Não será mais possível restaurá-lo.",
  'desktop.eliminato': "Backup excluído",
  'desktop.ripristino-titolo': "Voltar para este backup?",
  'desktop.ripristino-prima': "Tudo voltará a ser como era em",
  'desktop.ripristino-dopo': ". Tudo o que foi feito depois some da vista.",
  'desktop.ripristino-nota': "Antes, o Lumi faz uma cópia de como está agora (“{tipo}”): se mudar de ideia, restaure essa e não perde nada. Quem estiver trabalhando em outros dispositivos verá a página recarregar.",
  'desktop.capito': "Entendi, quero voltar para aquele momento",
  'desktop.annulla': "Cancelar",
  'desktop.ripristino-in-corso': "Restaurando…",
  'desktop.ripristinato': "Restaurado",
  'desktop.ripristinato-altro': "O proprietário restaurou um backup: recarregando…",
  'desktop.caricato': "Backup enviado: {azienda}, {persone}, {sezioni}. Ele está no topo da lista.",
  'desktop.persone': {"one": "{n} pessoa", "other": "{n} pessoas"},
  'desktop.sezioni': {"one": "{n} seção", "other": "{n} seções"},
  'desktop.carica': "Enviar um backup",
  'desktop.carica-nota': "Um arquivo .db baixado daqui, mesmo de outro computador. O Lumi o verifica e coloca na lista: depois você decide se quer restaurá-lo.",
  'desktop.scegli-file': "Escolher o arquivo…",
  'desktop.uscita-versione': "Nova versão disponível:",
  'desktop.novita': "novidades",
  'desktop.aggiornato': "Você está na versão mais recente.",
  'desktop.versioni': "Novas versões",
  'desktop.stai-usando': "Você está usando o Lumi",
  'desktop.controlla-ogni-giorno': "Verificar todo dia se saiu uma versão nova e me avisar",
  'desktop.versioni-nota': "O Lumi só pergunta ao GitHub o número da última versão publicada: não envia dados da empresa e não instala nada sozinho. Você atualiza quando quiser, depois de um backup.",
  'desktop.controlla-adesso': "Verificar agora",
  'desktop.avviso-versione': "Nova versão do Lumi:",
  'desktop.dettagli': "Detalhes",
  'desktop.chiudi': "Fechar",
  'desktop.solo-titolare': "Os backups são gerenciados pelo proprietário.",
};
