// E-invoices (web/moduli/fatture.js): received invoices, virtual stamp duty, numbering.
export default {
  'fatture.aggiorna-chiedi': "As faturas do Lumi cresceram: preços com até 8 casas decimais, caixa previdenciária, Administração Pública, faturas recebidas. Adiciono os campos novos agora? Nenhum dado se perde.",
  'fatture.aggiornato': "Faturas atualizadas",
  'fatture.bloccata': "Emitida · bloqueada",
  'fatture.bloccata-nota': "Uma fatura emitida não pode mais ser alterada: corrija com uma nota de crédito ou de débito. Você pode mudar o status do pagamento e as notas internas.",
  'fatture.bollo': "Selo virtual",
  'fatture.bollo-nota': "O selo é pago com o F24 (códigos 2521-2524) ou na área reservada da Agência da Receita, que calcula o valor a cada trimestre. Contam as faturas emitidas com o selo marcado.",
  'fatture.chiudi': "Fechar",
  'fatture.codice-tributo': "Código do tributo",
  'fatture.crea-integrazione': "Criar integração",
  'fatture.da-integrare': "A integrar",
  'fatture.da-pagare': "A pagar",
  'fatture.da-versare': "A recolher",
  'fatture.emesse': "Emitidas",
  'fatture.entro': "Até",
  'fatture.fatture-con-bollo': "Faturas com selo",
  'fatture.fornitore-nuovo': "novo",
  'fatture.gia-importata': "{numero} já estava lá",
  'fatture.importa': "Importar faturas",
  'fatture.importata': "{numero} de {data} · {totale}",
  'fatture.integra-conferma': "Criar a integração (ou autofatura) da fatura {numero}? Ela nasce como rascunho: você confere e emite.",
  'fatture.integra-nota': "Fatura recebida com reverse charge ou de um fornecedor estrangeiro: precisa da integração TD16-TD19.",
  'fatture.integrazione-creata': "Integração {tipo} criada como rascunho",
  'fatture.intestata-ad-altri': "não está no nome do seu número de IVA",
  'fatture.leggo': "Lendo…",
  'fatture.manca-modello': "Adicione antes o modelo «Faturas e fatura eletrônica».",
  'fatture.mancano': "Números faltando",
  'fatture.nessun-buco': "sem buracos",
  'fatture.nessuna-emessa': "Nenhuma fatura emitida neste ano.",
  'fatture.niente-da-integrare': "Nada a integrar.",
  'fatture.niente-da-pagare': "Nada a pagar.",
  'fatture.numerazione': "Numeração",
  'fatture.numerazione-nota': "Os números seguem em ordem por série e ano, sem buracos. Um buraco costuma vir de uma fatura lançada à mão: confira antes de emitir a próxima.",
  'fatture.ricevute': "Recebidas",
  'fatture.ricevute-nota': "Baixe as faturas da caixa fiscal ou da PEC e arraste para cá: também os .p7m assinados e os arquivos com várias faturas. O Lumi cria o fornecedor e registra o custo e o vencimento.",
  'fatture.serie': "Série",
  'fatture.serie-principale': "principal",
  'fatture.solo-xml': "Somente arquivos .xml ou .p7m",
  'fatture.stampa': "Imprimir",
  'fatture.titolo': "Faturas eletrônicas",
  'fatture.totale': "Total",
  'fatture.trascina': "Arraste aqui as faturas recebidas",
  'fatture.trascina-nota': "ou toque para escolher os arquivos (.xml, .xml.p7m)",
  'fatture.trimestre': "Trimestre",
  'fatture.trimestre-n': "{n}º trimestre",
  'fatture.troppo-grande': "Arquivo grande demais (no máximo 3,5 MB)",
  'fatture.tutte-le-ricevute': "Todas as faturas recebidas →",
  'fatture.ultimo': "Último",
  'fatture.vedi': "Ver a fatura",
  'fatture.vista': "Fatura recebida",
};
