// Impostos (web/moduli/fisco.js).
export default {
  'fisco.titolo': "Impostos",
  'fisco.anno': "Ano",
  'fisco.responsabilita': "O Kubo calcula e prepara a partir dos seus dados: confira antes de pagar ou enviar. A responsabilidade continua sendo do contribuinte.",
  'fisco.scheda-riepilogo': "A pagar",
  'fisco.scheda-iva': "IVA",
  'fisco.scheda-forfettario': "Forfetário",
  'fisco.scheda-f24': "F24",
  'fisco.scheda-ritenute': "Retenções",
  'fisco.scheda-scadenze': "Prazos",
  'fisco.scheda-commercialista': "Para o contador",
  'fisco.scheda-impostazioni': "Configurações",
  'fisco.da-pagare-anno': "Ainda a pagar este ano",
  'fisco.prossimo': "Próximo pagamento",
  'fisco.niente': "Nada à vista.",
  'fisco.regime': "Regime",
  'fisco.coeff': "coeficiente {n}%",
  'fisco.regime-forfettario': "Forfetário (forfettario)",
  'fisco.regime-semplificato': "Simplificado",
  'fisco.regime-ordinario': "Ordinário",
  'fisco.periodicita-trimestrale': "IVA trimestral",
  'fisco.periodicita-mensile': "IVA mensal",
  'fisco.manca-ricevute': "Para o IVA das compras e as retenções, adicione a seção «Faturas recebidas».",
  'fisco.apri-impostazioni': "Abrir as configurações",
  'fisco.prossimi-versamenti': "Próximos pagamentos",
  'fisco.data': "Data",
  'fisco.cosa': "O quê",
  'fisco.codice': "Código",
  'fisco.anno-rif': "Ano ref.",
  'fisco.importo': "Valor",
  'fisco.vedi-f24': "F24",
  'fisco.prossime-scadenze': "Próximos prazos",
  'fisco.mese-n': "Mês {n}",
  'fisco.trimestre-n': "{n}º trimestre",
  'fisco.lipe-trimestre': "LIPE {n}º trimestre",
  'fisco.liquidazioni': "Apurações periódicas",
  'fisco.periodo': "Período",
  'fisco.iva-vendite': "IVA vendas",
  'fisco.iva-acquisti': "IVA dedutível",
  'fisco.riporti': "Transportes",
  'fisco.interessi': "Juros 1%",
  'fisco.da-versare': "A pagar",
  'fisco.scadenza': "Vence",
  'fisco.a-credito': "crédito {importo}",
  'fisco.riportato': "transportado (até 100 €)",
  'fisco.acconto-dicembre': "Antecipação de IVA de dezembro",
  'fisco.acconto-dovuto': "Antecipação de {importo} pelo método {metodo}: código {codice}, até {data}.",
  'fisco.acconto-no': "Antecipação não devida (abaixo de 103,29 € ou faltam dados: informe-os nas configurações).",
  'fisco.acconto-nota': "Histórico: 88% do que você pagou pelo último período do ano passado. Previsional: 88% do que você prevê para o último período deste ano. O Kubo escolhe o menor.",
  'fisco.metodo-storico': "histórico",
  'fisco.metodo-previsionale': "previsional",
  'fisco.lipe': "Comunicação das apurações periódicas (LIPE)",
  'fisco.lipe-passo-1': "Baixe acima o arquivo XML do trimestre.",
  'fisco.lipe-passo-2': "Entre em «Fatture e Corrispettivi» no site da Agenzia delle Entrate com SPID, CIE ou CNS.",
  'fisco.lipe-passo-3': "Abra o serviço das apurações periódicas de IVA e escolha enviar um arquivo já pronto.",
  'fisco.lipe-passo-4': "Envie o arquivo e confirme: o sistema o verifica na hora.",
  'fisco.lipe-passo-5': "Baixe o recibo depois de alguns minutos e guarde-o.",
  'fisco.lipe-nota': "Prazos: 31 de maio, 30 de setembro, 30 de novembro e fim de fevereiro. Se algo não bater, a pré-preenchida da Agência ajuda a comparar.",
  'fisco.registri': "Livros de IVA",
  'fisco.registri-nota': "Os livros de vendas, compras e caixa diário estão no pacote para o contador, em CSV e Excel.",
  'fisco.debito-prec': "débito ant. {importo}",
  'fisco.credito-prec': "crédito ant. {importo}",
  'fisco.credito-anno': "crédito ano ant. {importo}",
  'fisco.meno-acconto': "antecipação {importo}",
  'fisco.non-forfettario': "A empresa não está no regime forfetário: altere isso nas configurações.",
  'fisco.sim-quanto': "Se eu receber mais (€)",
  'fisco.sim-esito': "Recebendo mais {piu}, você paga cerca de {tasse} a mais entre imposto e contribuições: sobram {resta}.",
  'fisco.niente-acconti': "Nenhuma antecipação devida.",
  'fisco.incassato': "Recebido",
  'fisco.incassato-nota': "faturas com «Paga em» neste ano",
  'fisco.reddito': "Renda",
  'fisco.contributi': "Contribuições INPS",
  'fisco.imposta': "Imposto substitutivo",
  'fisco.aliquota-n': "alíquota {n}%",
  'fisco.soglia': "Limite de 85.000 €",
  'fisco.soglia-nota': "Você usou {usato}% do limite: restam {margine}. Acima de 100.000 € você sai do regime na hora.",
  'fisco.simulazione': "Simulação",
  'fisco.simula': "Calcular",
  'fisco.acconti-anno': "Antecipações {anno}",
  'fisco.acconti-base': "Calculadas sobre o imposto do ano anterior: {importo}.",
  'fisco.saldo-stima': "Saldo estimado a pagar no ano que vem: {importo}.",
  'fisco.gestione-artigiani': "INPS artesãos",
  'fisco.gestione-commercianti': "INPS comerciantes",
  'fisco.gestione-separata': "Gestão separada",
  'fisco.gestione-cassa': "Caixa profissional",
  'fisco.gestione-nessuna': "Nenhuma",
  'fisco.stampa-f24': "Imprimir F24",
  'fisco.stampa': "Imprimir ou salvar PDF",
  'fisco.chiudi': "Fechar",
  'fisco.f24-del': "F24 de {data}",
  'fisco.sezione': "Seção",
  'fisco.rateazione': "Parcela / período",
  'fisco.sezione-erario': "Tesouro",
  'fisco.sezione-inps': "INPS",
  'fisco.sezione-locali': "Tributos locais",
  'fisco.f24-come': "Copie as linhas no F24 web (Agenzia delle Entrate) ou no internet banking. Se você compensar um crédito, ou o saldo for zero, precisa usar os serviços da Agência.",
  'fisco.registro-ritenute': "Retenções efetuadas",
  'fisco.pagata-il': "Paga em",
  'fisco.percipiente': "Beneficiário",
  'fisco.compenso': "Honorário",
  'fisco.ritenuta': "Retenção",
  'fisco.versare-entro': "Pagar até",
  'fisco.ritenute-vuoto': "Nenhuma retenção: elas são registradas nas faturas recebidas de profissionais (retenção e data de pagamento).",
  'fisco.riepilogo-cu': "Resumo para a CU e o 770",
  'fisco.cf': "Código fiscal",
  'fisco.causale': "Causa",
  'fisco.cu-nota': "São os dados a informar: a CU é entregue até 16 de março e enviada à Agência; o 770 até 31 de outubro. O Kubo não os envia.",
  'fisco.scadenze-anno': "Prazos {anno}",
  'fisco.scadenze-nota': "Só os prazos do seu regime. Datas em sábado ou feriado já passam para o próximo dia útil.",
  'fisco.dal': "De",
  'fisco.al': "Até",
  'fisco.scarica-pacchetto': "Baixar o zip",
  'fisco.pacchetto': "Pacote para o contador",
  'fisco.pacchetto-cosa': "Um zip com cópias XML das faturas emitidas, livros de IVA, apurações, livro-caixa e retenções em CSV e Excel, e um resumo em PDF.",
  'fisco.quando-professionista': "Quando você precisa mesmo de um profissional",
  'fisco.pro-dichiarazioni': "As declarações (renda, IVA anual, 770) você pode enviar sozinho com SPID; para alguém enviá-las por você é preciso um intermediário habilitado.",
  'fisco.pro-visto': "Para compensar no F24 um crédito de IVA acima de 5.000 € é preciso o visto de conformidade de um profissional.",
  'fisco.pro-consulenza': "Escolha do regime, redução INPS de 35%, parcelamentos, fiscalizações e avisos: é consultoria, pergunte a um contador.",
  'fisco.pro-redditi': "IRPEF, IRES e IRAP do regime ordinário ou simplificado são calculados pelo contador ou pela pré-preenchida, não pelo Kubo.",
  'fisco.salva': "Salvar",
  'fisco.salvate': "Configurações salvas",
  'fisco.sezioni': "Seções para impostos",
  'fisco.sezioni-cosa': "Adiciona «Faturas recebidas» (compras e retenções) e, se você vende no balcão, «Caixa diário».",
  'fisco.anche-corrispettivi': "Também o caixa diário",
  'fisco.aggiungi-sezioni': "Adicionar as seções",
  'fisco.sezioni-aggiunte': "Seções adicionadas",
  'fisco.manca-piva': "Faltam o número de IVA ou o código fiscal da empresa.",
  'fisco.apri-documenti': "Informe-os em Documentos",
  'fisco.gruppo-regime': "Regime e atividade",
  'fisco.gruppo-inps': "Contribuições INPS",
  'fisco.gruppo-forfettario': "Forfetário",
  'fisco.gruppo-iva': "IVA",
  'fisco.gruppo-altro': "Outros",
  'fisco.promemoria': "Impostos: {cosa} em {data}",
  'fisco.imp-regime': "Regime fiscal",
  'fisco.impn-regime': "Se você não sabe, pergunte ao seu contador: essa escolha muda tudo.",
  'fisco.imp-periodicita': "Apuração de IVA",
  'fisco.impn-periodicita': "Trimestral com 1% de juros, se o seu volume de negócios permitir.",
  'fisco.imp-ateco': "Código ATECO",
  'fisco.impn-ateco': "Está no certificado de atribuição do número de IVA.",
  'fisco.imp-coefficiente': "Coeficiente de rentabilidade %",
  'fisco.impn-coefficiente': "Vazio: o da tabela oficial para o seu ATECO.",
  'fisco.imp-gestione': "Regime previdenciário",
  'fisco.impn-gestione': "Para as caixas profissionais o Kubo não calcula as contribuições.",
  'fisco.imp-riduzione35': "Redução de 35% das contribuições",
  'fisco.impn-riduzione35': "Só artesãos e comerciantes forfetários que a pediram ao INPS.",
  'fisco.imp-aliquotaridotta': "Alíquota de 5% (primeiros cinco anos)",
  'fisco.impn-aliquotaridotta': "Para atividades novas que cumprem os requisitos; senão 15%.",
  'fisco.imp-impostaannoprecedente': "Imposto substitutivo do ano passado (€)",
  'fisco.impn-impostaannoprecedente': "Base das antecipações. Vazio: o Kubo calcula a partir dos dados.",
  'fisco.imp-accontiversatiannoprecedente': "Antecipações pagas no ano passado (€)",
  'fisco.impn-accontiversatiannoprecedente': "Para calcular o saldo de junho.",
  'fisco.imp-contributiversati': "Contribuições pagas neste ano (€)",
  'fisco.impn-contributiversati': "São deduzidas da renda. Vazio: usa-se a estimativa.",
  'fisco.imp-sedeinps': "Código da sede INPS",
  'fisco.impn-sedeinps': "Para a seção INPS do F24.",
  'fisco.imp-matricolainps': "Matrícula ou código INPS",
  'fisco.impn-matricolainps': "Na gestão separada é o seu código fiscal.",
  'fisco.imp-creditoannoprecedente': "Crédito de IVA do ano passado (€)",
  'fisco.impn-creditoannoprecedente': "Usado nas apurações enquanto houver.",
  'fisco.imp-accontoivastorico': "Pago pelo último período do ano passado (€)",
  'fisco.impn-accontoivastorico': "Para a antecipação pelo método histórico.",
  'fisco.imp-accontoivaprevisto': "Previsto para o último período deste ano (€)",
  'fisco.impn-accontoivaprevisto': "Para o método previsional. Vazio: a estimativa do Kubo.",
  'fisco.imp-camerale': "Taxa anual da Câmara de Comércio (€)",
  'fisco.impn-camerale': "O valor é informado pela sua Câmara de Comércio.",
  'fisco.imp-provinciacciaa': "Província da Câmara de Comércio",
  'fisco.impn-provinciacciaa': "Sigla, por exemplo MI.",
  'fisco.imp-bollo': "Selo virtual nas faturas",
  'fisco.impn-bollo': "No regime forfetário está sempre ativo.",
  'fisco.imp-sostituto': "Sou agente de retenção",
  'fisco.impn-sostituto': "Você paga profissionais retendo o imposto.",
  'fisco.v-iva': "IVA do período {periodo}",
  'fisco.v-iva-saldo': "Saldo anual de IVA",
  'fisco.v-iva-acconto': "Antecipação de IVA",
  'fisco.v-forf-saldo': "Saldo do imposto substitutivo {anno}",
  'fisco.v-forf-acconto': "Antecipação do imposto substitutivo {anno}",
  'fisco.v-inps-acconto': "Antecipação das contribuições INPS {anno}",
  'fisco.v-inps-fissi': "Contribuições INPS fixas",
  'fisco.v-bollo': "Selo virtual, {periodo}º trimestre",
  'fisco.v-ritenute': "Retenções do mês {periodo}",
  'fisco.v-camerale': "Taxa da Câmara de Comércio {anno}",
  'fisco.sc-iva-mese': "Pagamento de IVA do mês {periodo}",
  'fisco.sc-iva-trimestre': "Pagamento de IVA do {periodo}º trimestre",
  'fisco.sc-iva-saldo': "Saldo anual de IVA",
  'fisco.sc-iva-acconto': "Antecipação de IVA",
  'fisco.sc-lipe': "LIPE do {periodo}º trimestre",
  'fisco.sc-dichiarazione-iva': "Declaração de IVA {anno}",
  'fisco.sc-forf-saldo-acconto': "Saldo e primeira antecipação do imposto substitutivo",
  'fisco.sc-redditi-saldo-acconto': "Saldo e primeira antecipação dos impostos sobre a renda",
  'fisco.sc-forf-acconto2': "Segunda antecipação do imposto substitutivo",
  'fisco.sc-redditi-acconto2': "Segunda antecipação dos impostos sobre a renda",
  'fisco.sc-dichiarazione-redditi': "Declaração de renda {anno}",
  'fisco.sc-inps-fissi': "Contribuições INPS fixas, parcela {periodo}",
  'fisco.sc-inps-saldo-acconto': "Contribuições INPS: saldo e antecipação",
  'fisco.sc-inps-riduzione': "Pedido de redução INPS de 35%",
  'fisco.sc-bollo': "Selo virtual, {periodo}º trimestre {anno}",
  'fisco.sc-ritenute': "Retenções do mês {periodo}",
  'fisco.sc-cu-consegna': "CU aos beneficiários",
  'fisco.sc-cu-invio': "CU à Agência (trabalho autônomo)",
  'fisco.sc-modello-770': "Modelo 770",
  'fisco.sc-camerale': "Taxa da Câmara de Comércio",
  'fisco.av-vicino-85': "Você está perto do limite de 85.000 €: se passar dele, no ano que vem sai do regime forfetário.",
  'fisco.av-oltre-85': "Você passou de 85.000 €: no ano que vem sai do regime forfetário. Converse com um contador.",
  'fisco.av-oltre-100': "Você passou de 100.000 €: sai do regime forfetário na hora, com IVA a partir da operação que ultrapassou o limite. Você precisa de um contador.",
  'fisco.av-fuori-dal-regime': "No ano passado você recebeu mais de 85.000 €: este ano não poderia estar no regime forfetário. Confira com um contador.",
  'fisco.av-contributi-stimati': "As contribuições deduzidas são estimadas: informe nas configurações as realmente pagas neste ano.",
  'fisco.av-cassa-professionale': "Com uma caixa profissional, quem calcula as contribuições é a caixa: o Kubo não as conta.",
  'fisco.av-incassi-senza-data': "Algumas faturas pagas não têm «Paga em»: contam na data da fatura.",
  'fisco.av-visto-conformita': "O crédito de IVA passa de 5.000 €: para compensá-lo no F24 é preciso o visto de conformidade.",
  'fisco.av-forfettario-niente-iva': "No regime forfetário não há IVA a apurar nem LIPE: veja o painel do forfetário.",
  'fisco.av-redditi-professionista': "IRPEF, IRES e IRAP não estão aqui: quem calcula é o contador ou a pré-preenchida.",
  'fisco.av-inps-cassetto': "As parcelas fixas do INPS são uma estimativa: o F24 oficial está no Cassetto previdenziale.",
  'fisco.av-cu-intermediario': "Com 20 CU ou mais suas credenciais não bastam: é preciso Entratel ou um intermediário.",
  'fisco.av-cu-fisconline': "Com menos de 20 CU você pode enviá-las sozinho com suas credenciais.",
};
