export default {
  'gestione.tipo-testo': 'Texto',
  'gestione.tipo-testo_lungo': 'Texto longo',
  'gestione.tipo-numero': 'Número',
  'gestione.tipo-valuta': 'Valor ({simbolo})',
  'gestione.tipo-percentuale': 'Porcentagem',
  'gestione.tipo-data': 'Data',
  'gestione.tipo-data_ora': 'Data e hora',
  'gestione.tipo-si_no': 'Sim / Não',
  'gestione.tipo-scelta': 'Opção',
  'gestione.tipo-scelta_multipla': 'Múltipla escolha',
  'gestione.tipo-stato': 'Status (fluxo)',
  'gestione.tipo-relazione': 'Vínculo',
  'gestione.tipo-righe': 'Itens (subtabela)',
  'gestione.tipo-calcolato': 'Calculado (fórmula)',
  'gestione.tipo-contatore': 'Numeração',
  'gestione.tipo-email': 'E-mail',
  'gestione.tipo-telefono': 'Telefone',
  'gestione.tipo-url': 'Site',
  'gestione.tipo-indirizzo': 'Endereço',
  'gestione.tipo-codice_a_barre': 'Código de barras',
  'gestione.tipo-durata': 'Duração (minutos)',
  'gestione.tipo-immagine': 'Imagem',
  'gestione.tipo-file': 'Arquivo',
  'gestione.nome': 'Nome',
  'gestione.esempio-sezione': 'ex.: Aluguéis',
  'gestione.archivia-campo': 'Arquivar o campo (os valores ficam)',
  'gestione.obbligatorio': 'Obrigatório',
  'gestione.senza-doppioni': 'Sem duplicados',
  'gestione.prima-opzione': 'Primeira opção',
  'gestione.opzioni': 'Opções, uma por linha (cores: {colori})',
  'gestione.righe-di': 'Itens de',
  'gestione.collegato-a': 'Vinculado a',
  'gestione.piu-di-uno': 'Mais de um',
  'gestione.campo-punta': 'Campo que aponta para cá (na outra entidade)',
  'gestione.formula': 'Fórmula (ex.: quantidade * preco · SOMA(itens.total) · SE(estoque <= minimo; "sim"; "não"))',
  'gestione.mostra-come': 'Mostrar como',
  'gestione.automatico': 'Automático',
  'gestione.importo': 'Valor',
  'gestione.formato-contatore': 'Formato ({AAAA} ano, {N:4} número de 4 dígitos)',
  'gestione.salva-modifiche': 'Salvar alterações',
  'gestione.dai-nome': 'Dê um nome',
  'gestione.piu-campo': '+ Campo',
  'gestione.personalizza-nome': 'Personalizar · {nome}',
  'gestione.icona': 'Ícone',
  'gestione.nome-elemento': 'Nome de cada item',
  'gestione.nota-dati': 'Renomear e mover não mexe nos dados. Um campo removido é arquivado com seus valores e pode ser restaurado. Se uma mudança de tipo perder valores, o salvamento para e mostra quais.',
  'gestione.password-8': 'Senha (8+)',
  'gestione.aggiungi': 'Adicionar',
  'gestione.aggiunto': 'Adicionado',
  'gestione.ruolo-cambiato': 'Papel alterado',
  'gestione.disattiva': 'Desativar',
  'gestione.riattiva': 'Reativar',
  'gestione.ruolo': 'Papel',
  'gestione.nuova-persona': 'Nova pessoa',
  'gestione.ruoli': 'Papéis',
  'gestione.nota-ruoli': 'O proprietário pode tudo. Para os outros papéis, escolha seção por seção o que podem fazer.',
  'gestione.nuovo-ruolo': '+ Novo papel',
  'gestione.nome-ruolo': 'Nome do papel (ex.: Balcão, Oficina)',
  'gestione.vede': 'Vê',
  'gestione.modifica': 'Edita',
  'gestione.campi-nascosti-ruolo': 'Campos ocultos para este papel',
  'gestione.salva-ruolo': 'Salvar o papel',
  'gestione.ruolo-salvato': 'Papel salvo',
  'gestione.puo-personalizzare': 'Pode personalizar',
  'gestione.sezione': 'Seção',
  'gestione.campi-nascosti': 'Campos ocultos (⌘/Ctrl para escolher vários)',
  'gestione.ruolo-titolare': 'Proprietário',
  'gestione.ruolo-collaboratore': 'Colaborador',
  'gestione.ruolo-lettura': 'Somente leitura',
  'gestione.lingua-valuta': 'Idioma e moeda',
  'gestione.tua-lingua': 'Seu idioma',
  'gestione.tua-lingua-nota': 'Vale só para você, em todos os dispositivos.',
  'gestione.azienda': 'Para toda a empresa',
  'gestione.lingua-modelli': 'Idioma dos novos modelos',
  'gestione.lingua-modelli-nota': 'Os modelos que você adicionar daqui em diante chegam com os nomes neste idioma. As seções que já existem não mudam.',
  'gestione.valuta-nota': 'Os valores aparecem nesta moeda. Os valores salvos não mudam: só o símbolo e o formato.',
  'gestione.esempio': 'Fica assim: {numero} · {soldi} · {data}',
  'gestione.salvato-ricarico': 'Salvo: recarregando a página',
  'gestione.settimana-da': 'Primeiro dia da semana: {giorno}.',
};
