// Estoque (web/moduli/magazzino.js): valor, inventário, movimentos.
export default {
  'magazzino.titolo': "Estoque",
  'magazzino.scheda-valore': "Valor",
  'magazzino.scheda-inventario': "Inventário",
  'magazzino.scheda-movimenti': "Movimentos",
  'magazzino.sezione': "Seção do estoque",
  'magazzino.nessuna-sezione': "Nenhuma seção com estoque: adicione o campo «giacenza» aos artigos.",
  'magazzino.valore': "Valor",
  'magazzino.al-costo': "ao custo dos artigos",
  'magazzino.pezzi': "Peças",
  'magazzino.articoli-n': {"one": "{n} artigo", "other": "{n} artigos"},
  'magazzino.sotto-scorta': "Abaixo do mínimo",
  'magazzino.negativi': {"one": "{n} artigo com estoque negativo: {nomi}", "other": "{n} artigos com estoque negativo: {nomi}"},
  'magazzino.senza-costo': {"one": "{n} artigo em estoque não tem custo: fica fora do valor.", "other": "{n} artigos em estoque não têm custo: ficam fora do valor."},
  'magazzino.per-categoria': "Por categoria",
  'magazzino.categoria': "Categoria",
  'magazzino.articoli': "Artigos",
  'magazzino.senza-categoria': "Sem categoria",
  'magazzino.per-articolo': "Por artigo",
  'magazzino.codice': "Código",
  'magazzino.articolo': "Artigo",
  'magazzino.giacenza': "Estoque",
  'magazzino.costo': "Custo",
  'magazzino.scarica-csv': "Baixar CSV",
  'magazzino.nota-valore': "O valor é estoque × custo. As compras mantêm o custo médio ponderado. É o dado do estoque final para o contador.",
  'magazzino.inventario-nota': "Conte a mercadoria nas prateleiras: os estoques de agora ficam como referência e, ao fechar, cada artigo contado é corrigido pela diferença. As vendas feitas durante a contagem continuam certas.",
  'magazzino.continua': "Continuar «{nome}»",
  'magazzino.nuovo-inventario': "Começar um inventário",
  'magazzino.inventari': "Inventários",
  'magazzino.nome': "Nome",
  'magazzino.iniziato': "Começado",
  'magazzino.contati': "Contados",
  'magazzino.stato': "Situação",
  'magazzino.chiuso-il': "Fechado em {data}",
  'magazzino.aperto': "Aberto",
  'magazzino.leggi-codice': "Leia um código (leitor ou teclado, depois Enter)",
  'magazzino.letto': "{nome}: {n}",
  'magazzino.cerca': "Buscar artigo ou código",
  'magazzino.attesa': "Esperado",
  'magazzino.contata': "Contado",
  'magazzino.differenza': "Diferença",
  'magazzino.chiudi-conferma': {"one": "Fechar o inventário? {n} estoque será corrigido.", "other": "Fechar o inventário? {n} estoques serão corrigidos."},
  'magazzino.chiuso': {"one": "Inventário fechado: {n} ajuste, {importo}", "other": "Inventário fechado: {n} ajustes, {importo}"},
  'magazzino.differenze': "Diferenças",
  'magazzino.valore-differenze': "Valor das diferenças",
  'magazzino.chiudi': "Fechar o inventário",
  'magazzino.chiudi-nota': "Os artigos não contados ficam como estão.",
  'magazzino.quando': "Quando",
  'magazzino.movimento': "Movimento",
  'magazzino.origine': "Origem",
  'magazzino.chi': "Quem",
  'magazzino.origine-iniziale': "Estoque inicial",
  'magazzino.origine-modifica': "Alteração",
  'magazzino.origine-automazione': "Automático (vendas, pedidos, consumos)",
  'magazzino.origine-inventario': "Inventário",
  'magazzino.niente-movimenti': "Nenhum movimento ainda.",
  'magazzino.nota-movimenti': "Cada mudança de estoque chega aqui sozinha, venha de onde vier: fichas, vendas, pedidos recebidos, importações, inventários.",
};
