export default {
  'moduli.lumi-serve-chiave': "Para responder preciso da chave do Claude. Vou abrir **Gestão → Lumi**: leva um minuto.",
  'moduli.lumi-serve-chiave-spento': "Para responder preciso da chave do Claude e que você me ligue de novo. Vou abrir **Gestão → Lumi**: leva um minuto.",
  'moduli.lumi-chiedi-titolare': "Para responder preciso da chave do Claude: peça ao proprietário para adicioná-la em **Gestão → Lumi**.",
  'moduli.lumi-spento': "O Lumi está desligado: dá para ligar de novo em Gestão → Lumi.",
  'moduli.lumi-quasi-pronto': "O Lumi está quase pronto: falta a chave do Claude.",
  'moduli.lumi-apri': "Abrir",
  'moduli.lumi-settimana': "Como está a semana",
  'moduli.lumi-settimana-domanda': "Como foi esta semana? Me dê os números principais.",
  'moduli.lumi-accendi': "Ligar o Lumi",
  'moduli.lumi-solo-titolare': "As configurações do Lumi são do proprietário.",
  'moduli.lumi-gia-salvata': "•••••••• (já salva)",
  'moduli.lumi-stato-spento': "Desligado",
  'moduli.lumi-stato-acceso': "Ligado",
  'moduli.lumi-stato-manca': "Falta a chave",
  'moduli.lumi-fonte-ambiente': "A chave vem da variável ANTHROPIC_API_KEY do servidor.",
  'moduli.lumi-fonte-file': "Chave salva neste computador.",
  'moduli.lumi-cos-e': "O Lumi é o assistente do Kubo. Você fala ou escreve para ele na pílula lá em cima: ele busca, conta, prepara fichas e muda a forma do sistema. Cada alteração espera o seu «Confirmar», e cada pessoa só vê o que as permissões dela deixam.",
  'moduli.lumi-chiave': "Chave do Claude",
  'moduli.lumi-salva-chiave': "Salvar a chave",
  'moduli.lumi-incolla': "Cole a chave",
  'moduli.lumi-togliere': "Remover a chave? O Lumi para de responder.",
  'moduli.lumi-dove-chiave': "Você cria em console.anthropic.com, em API Keys. Ela fica neste computador, num arquivo ao lado dos dados que só o Kubo lê, e nunca chega aos navegadores.",
  'moduli.lumi-acceso': "Lumi ligado",
  'moduli.lumi-limite': "Perguntas por minuto por pessoa",
  'moduli.lumi-da-provare': "Para experimentar",
  'moduli.lumi-esempio-1': "Quanto vendi esta semana?",
  'moduli.lumi-esempio-2': "O que preciso repor?",
  'moduli.lumi-esempio-3': "Adicione o tamanho aos produtos com P, M, G e GG",
  'moduli.lumi-esempio-4': "Crie uma seção de aluguéis com cliente, ferramenta, de, até e status",
  'moduli.lumi-esempio-5': "Quando um aluguel passar para devolvido, me avise",
  'moduli.lumi-modello': "Modelo: {modello}.",
  'moduli.lumi-voce-accesa': "Voz em tempo real ligada.",
  'moduli.lumi-voce-browser': "Voz: a do navegador, onde houver.",
  'moduli.ag-adesso': "agora",
  'moduli.ag-agenda': "Agenda",
  'moduli.ag-calendario': "Calendário",
  'moduli.ag-cruscotto': "Painel",
  'moduli.ag-aggiungi-voce': "Adicionar o item",
  'moduli.ag-altri': {"one": "+{n} outro", "other": "+{n} outros"},
  'moduli.ag-e-altri': {"one": "e mais um", "other": "e mais {n}"},
  'moduli.ag-aria-grafico': "{titolo}: gráfico",
  'moduli.ag-barre': "Barras",
  'moduli.ag-linea': "Linha",
  'moduli.ag-buongiorno': "Bom dia",
  'moduli.ag-buon-pomeriggio': "Boa tarde",
  'moduli.ag-buonasera': "Boa noite",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Alterar",
  'moduli.ag-cambia-widget': "Alterar o widget",
  'moduli.ag-nuovo-widget': "Novo widget",
  'moduli.ag-campo': "Campo",
  'moduli.ag-colonne-per': "Colunas: {nome}",
  'moduli.ag-una-colonna': "Uma coluna",
  'moduli.ag-come-oggi': "igual a ontem",
  'moduli.ag-come-settimana': "igual à semana passada",
  'moduli.ag-come-mese': "igual ao mês passado",
  'moduli.ag-come-anno': "igual ao ano passado",
  'moduli.ag-rispetto-oggi': "{diff} em relação a ontem ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} em relação à semana passada ({prima})",
  'moduli.ag-rispetto-mese': "{diff} em relação ao mês passado ({prima})",
  'moduli.ag-rispetto-anno': "{diff} em relação ao ano passado ({prima})",
  'moduli.ag-data-rif': "Data de referência",
  'moduli.ag-prima': "Anterior",
  'moduli.ag-dopo': "Próximo",
  'moduli.ag-fatto': "Pronto",
  'moduli.ag-forma': "Formato",
  'moduli.ag-ha-creato': "criou",
  'moduli.ag-ha-modificato': "alterou",
  'moduli.ag-ha-archiviato': "arquivou",
  'moduli.ag-ha-ripristinato': "restaurou",
  'moduli.ag-in-sezione': "em {nome}",
  'moduli.ag-un-elemento': "um item",
  'moduli.ag-lista': "Lista",
  'moduli.ag-torna-lista': "Voltar à lista",
  'moduli.ag-media': "Média de…",
  'moduli.ag-somma': "Soma de…",
  'moduli.ag-quanti': "Quantos são",
  'moduli.ag-misura': "Medida",
  'moduli.ag-modifica': "Editar",
  'moduli.ag-nome-voce': "Nome do item",
  'moduli.ag-nuova-voce': "Novo item",
  'moduli.ag-un-filtro': "Coloque pelo menos um filtro no item",
  'moduli.ag-non-disegno': "Não consigo desenhar",
  'moduli.ag-oggi': "Hoje",
  'moduli.ag-per': "Por",
  'moduli.ag-periodo': "Período",
  'moduli.ag-periodo-oggi': "Hoje",
  'moduli.ag-periodo-settimana': "Esta semana",
  'moduli.ag-periodo-mese': "Este mês",
  'moduli.ag-periodo-anno': "Este ano",
  'moduli.ag-periodo-ultimi_7': "Últimos 7 dias",
  'moduli.ag-periodo-ultimi_30': "Últimos 30 dias",
  'moduli.ag-periodo-ultimi_84': "Últimas 12 semanas",
  'moduli.ag-periodo-ultimi_365': "Último ano",
  'moduli.ag-periodo-sempre': "Sempre",
  'moduli.ag-piede-grafico': "{periodo} · {totale} no total",
  'moduli.ag-piu-aggiungi': "+ Adicionar",
  'moduli.ag-quale-data': "Qual data",
  'moduli.ag-senza-titolo': "Sem título",
  'moduli.ag-spostato': "Movido",
  'moduli.ag-tipo': "Tipo",
  'moduli.ag-titolo': "Título",
  'moduli.ag-titolo-widget': "Dê um título ao widget",
  'moduli.ag-tutti': "todos",
  'moduli.ag-utente-non-attivo': "Usuário inativo",
  'moduli.ag-vedi-calendario': "Ver no calendário",
  'moduli.ag-vedi-elenco': "Ver a lista",
  'moduli.ag-vedi-giorno': "Ver o dia",
  'moduli.ag-vista-giorno': "Dia",
  'moduli.ag-vista-settimana': "Semana",
  'moduli.ag-vista-mese': "Mês",
  'moduli.ag-w-numero': "Número",
  'moduli.ag-w-grafico': "Gráfico",
  'moduli.ag-w-attenzione': "Precisa de atenção",
  'moduli.ag-w-ultime': "Últimas alterações",
  'moduli.ag-def-incassato-oggi': "Recebido hoje",
  'moduli.ag-def-incassato-mese': "Recebido este mês",
  'moduli.ag-def-vendite-oggi': "Vendas hoje",
  'moduli.ag-def-incassi-30': "Recebimentos dos últimos 30 dias",
  'moduli.ag-def-appuntamenti-oggi': "Agendamentos hoje",
  'moduli.ag-def-appuntamenti-settimana': "Agendamentos por semana",
  'moduli.ag-def-preventivi-attesa': "Orçamentos aguardando",
  'moduli.ag-def-commesse-aperte': "Pedidos em aberto",
  'moduli.ag-def-accettato-mese': "Aprovado este mês",
  'moduli.ag-def-preventivi-mese': "Orçamentos aprovados por mês",
  'moduli.ag-def-articoli-riordinare': "Produtos para repor",
  'moduli.ag-def-materiali-riordinare': "Materiais para repor",
  'moduli.ag-def-ordini-ritardo': "Pedidos atrasados",
  'moduli.ag-def-vendite-aperte': "Vendas abertas há mais de 2 dias",
  'moduli.ag-def-commesse-ritardo': "Pedidos atrasados",
  'moduli.ag-def-preventivi-senza-risposta': "Orçamentos sem resposta há 7 dias",
  'moduli.ag-def-appuntamenti-chiudere': "Agendamentos passados para fechar",
  'moduli.ag-def-pacchetti-scaduti': "Pacotes vencidos com sessões",
  'moduli.ag-def-attenzione': "Precisa de atenção",
  'moduli.ag-def-ultime': "Últimas alterações",
  'moduli.ag-def-nuovi-mese': "{nome}: novos este mês",
  'moduli.ag-tutto-ok': "✓ Tudo em ordem: nada para resolver.",
  'moduli.ag-nessuna-modifica': "Nenhuma alteração ainda.",
  'moduli.ag-es-titolo': "Ex.: Recebido hoje",
  'moduli.im-menu': "Importe de uma planilha ou exporte a lista com os filtros atuais",
  'moduli.im-importa-da': "Importar do Excel ou CSV…",
  'moduli.im-esporta-xlsx': "Exportar para Excel (.xlsx)",
  'moduli.im-esporta-csv': "Exportar em CSV",
  'moduli.im-nuova-dal-foglio': "+ Uma nova seção a partir da planilha",
  'moduli.im-scegli-file': "Escolha um arquivo Excel (.xlsx) ou CSV",
  'moduli.im-trascina': "ou arraste para cá. A primeira linha precisa ter os nomes das colunas.",
  'moduli.im-esporta-tutto': "Exportar tudo",
  'moduli.im-backup': "Backup completo",
  'moduli.im-backup-nota': "Um zip com a cópia do banco de dados (consistente mesmo enquanto se trabalha) e os anexos. Guarde num disco externo ou numa nuvem sua.",
  'moduli.im-scarica-backup': "Baixar o backup",
  'moduli.im-importa-esporta': "Importar e exportar",
  'moduli.im-api': "API e integrações",
  'moduli.im-dati': "Dados",
  'moduli.im-dove': "Para onde vão as linhas",
  'moduli.im-non-importare': "— não importar",
  'moduli.im-crea-campo': "+ Criar o campo «{nome}» ({tipo})",
  'moduli.im-non-controllare': "Não verificar: cada linha é nova",
  'moduli.im-stesso': "Mesmo «{nome}»",
  'moduli.im-stesso-unico': "Mesmo «{nome}» (sem duplicados)",
  'moduli.im-aggiorna': "atualize a que já existe",
  'moduli.im-salta': "deixe como está, pule a linha",
  'moduli.im-controllo': "Verificando…",
  'moduli.im-importo': "Importando…",
  'moduli.im-importato': "Importado",
  'moduli.im-prova': "Testar sem salvar",
  'moduli.im-importa-n': {"one": "Importar {n} linha", "other": "Importar {n} linhas"},
  'moduli.im-righe-in': {"one": "{n} linha em «{file}»", "other": "{n} linhas em «{file}»"},
  'moduli.im-riga': "Linha",
  'moduli.im-errore': "Erro",
  'moduli.im-file-errori': "linhas para corrigir.csv",
  'moduli.im-prova-esito': "Teste: nada foi salvo",
  'moduli.im-esito-create': {"one": "criada", "other": "criadas"},
  'moduli.im-esito-aggiornate': {"one": "atualizada", "other": "atualizadas"},
  'moduli.im-esito-saltate': {"one": "pulada", "other": "puladas"},
  'moduli.im-esito-errori': "com erros",
  'moduli.im-cosa-non-va': "O que está errado",
  'moduli.im-e-altre': {"one": "…e mais uma.", "other": "…e mais {n}."},
  'moduli.im-scarica-errori': "Baixar as linhas com erro (.csv)",
  'moduli.im-correggi': "Corrija no arquivo e importe de novo: com a verificação de duplicados nada se repete.",
  'moduli.im-vai-a': "Ir para {nome}",
  'moduli.im-abbina': "Ligue as colunas aos campos de {nome}. As primeiras linhas:",
  'moduli.im-ogni-colonna': "Cada coluna vira um campo: confira nomes e tipos.",
  'moduli.im-nome-sezione': "Nome da nova seção",
  'moduli.im-gia-presenti': "Linhas já existentes",
  'moduli.im-se-trovo': "se eu encontrar:",
  'moduli.im-formati': "São aceitos números como «1.234,50» ou «1234.50», datas como «31/12/2026» e «1 / 0» ou «yes / no». Células vazias não apagam nada.",
  'moduli.doc-campo-ragione_sociale': "Razão social",
  'moduli.doc-campo-piva': "Número de IVA",
  'moduli.doc-campo-codice_fiscale': "Código fiscal",
  'moduli.doc-campo-regime': "Regime fiscal",
  'moduli.doc-campo-via': "Endereço (rua e número)",
  'moduli.doc-campo-cap': "CEP",
  'moduli.doc-campo-comune': "Município",
  'moduli.doc-campo-provincia': "Província (sigla)",
  'moduli.doc-campo-telefono': "Telefone",
  'moduli.doc-campo-email': "E-mail",
  'moduli.doc-campo-pec': "PEC",
  'moduli.doc-campo-codice_destinatario': "Seu código de destinatário",
  'moduli.doc-campo-iban': "IBAN",
  'moduli.doc-campo-banca': "Banco",
  'moduli.doc-campo-aliquota': "IVA padrão %",
  'moduli.doc-campo-colore': "Cor dos documentos",
  'moduli.doc-chiudi': "Fechar (Esc)",
  'moduli.doc-anteprima': "Pré-visualização de impressão",
  'moduli.doc-stampa-pdf': "Imprimir ou salvar em PDF",
  'moduli.doc-modifica-modello': "Editar o modelo",
  'moduli.doc-xml-manca': "Falta algo antes do arquivo XML",
  'moduli.doc-sistema': "Corrija estes pontos e tente de novo:",
  'moduli.doc-apri-dati': "Abrir os dados da empresa",
  'moduli.doc-scaricato': "{nome} baixado: agora envie ao portal do seu intermediário ou ao Fatture e Corrispettivi",
  'moduli.doc-dati-azienda': "Dados da empresa",
  'moduli.doc-modelli-stampa': "Modelos de impressão",
  'moduli.doc-documenti': "Documentos",
  'moduli.doc-dati-salvati': "Dados da empresa salvos",
  'moduli.doc-logo': "Logo",
  'moduli.doc-nessun-logo': "Sem logo",
  'moduli.doc-logo-tipo': "O logo precisa ser PNG ou JPEG",
  'moduli.doc-logo-grande': "O logo é grande demais: no máximo 300 KB",
  'moduli.doc-logo-caricato': "Logo enviado",
  'moduli.doc-carica-logo': "Enviar o logo",
  'moduli.doc-logo-nota': "PNG ou JPEG, no máximo 300 KB. Vai no topo de cada documento.",
  'moduli.doc-indirizzo-completo': "Endereço completo",
  'moduli.doc-fattura-elettronica': "Fatura eletrônica (Itália)",
  'moduli.doc-fatturapa-nota': "O Kubo prepara o arquivo FatturaPA (XML). Para enviar ao SDI, envie no portal Fatture e Corrispettivi da Agenzia delle Entrate ou ao seu intermediário: os passos estão em docs/DOCUMENTI.md.",
  'moduli.doc-nessuna-stampa': "Nenhuma seção com itens para imprimir. Adicione um modelo (loja, oficina, faturas) ou uma seção com itens.",
  'moduli.doc-elenco-nota': "Cada seção com itens tem seu documento A4. Mude textos, colunas e rodapé: a pré-visualização se atualiza enquanto você escreve.",
  'moduli.doc-documento': "Documento",
  'moduli.doc-modello': "Modelo",
  'moduli.doc-personalizzato': "personalizado",
  'moduli.doc-predefinito': "padrão",
  'moduli.doc-sinistra': "à esquerda",
  'moduli.doc-destra': "à direita",
  'moduli.doc-salva-modello': "Salvar o modelo",
  'moduli.doc-modello-salvato': "Modelo salvo",
  'moduli.doc-torna-predefinito': "Voltar ao padrão",
  'moduli.doc-torna-conferma': "Voltar ao modelo padrão? As alterações deste modelo se perdem.",
  'moduli.doc-modello-predefinito': "Modelo padrão",
  'moduli.doc-crea-uno': "Crie pelo menos um documento em {nome} para ver a pré-visualização.",
  'moduli.doc-segnaposto': "Marcadores que você pode usar",
  'moduli.doc-seg-campi': "Campos do documento: ",
  'moduli.doc-seg-collegati': "Vinculados (qualquer campo deles): ",
  'moduli.doc-seg-azienda': "Sua empresa: ",
  'moduli.doc-seg-colonne': "Nas colunas, cada item: ",
  'moduli.doc-seg-campi-riga': " e os campos do item: ",
  'moduli.doc-seg-totali': "Totais: ",
  'moduli.doc-seg-oggi': " · hoje: ",
  'moduli.doc-seg-se': "Um trecho que só aparece se o campo estiver preenchido: ",
  'moduli.doc-seg-se-manca': "; só se estiver vazio: ",
  'moduli.doc-ed-titolo': "Título do documento",
  'moduli.doc-ed-sopra-destinatario': "Acima do destinatário",
  'moduli.doc-ed-destinatario': "Destinatário",
  'moduli.doc-ed-dettagli': "Detalhes no canto superior direito",
  'moduli.doc-ed-colonne': "Colunas dos itens",
  'moduli.doc-ed-riepilogo-iva': "Resumo de IVA por alíquota",
  'moduli.doc-ed-prezzi-ivati': "Os preços incluem IVA",
  'moduli.doc-ed-note': "Observações",
  'moduli.doc-ed-pagamento': "Pagamento",
  'moduli.doc-ed-piede': "Rodapé",
  'moduli.doc-ed-colore-label': "Cor",
  'moduli.doc-ed-colore-azienda': "o da empresa",
  'moduli.doc-crea-fattura': "Criar fatura",
  'moduli.doc-crea-fattura-nota': "Uma fatura em rascunho com o cliente e os itens deste documento",
  'moduli.doc-fattura-creata': "Fatura em rascunho criada",
  'moduli.doc-nota-credito': "Nota de crédito",
  'moduli.doc-nota-credito-nota': "Estorne esta fatura com uma nota de crédito em rascunho",
  'moduli.doc-nota-conferma': "Criar uma nota de crédito que estorna a fatura {numero}?",
  'moduli.doc-nota-creata': "Nota de crédito em rascunho criada",
  'moduli.doc-fatturapa-titolo': "Verifique e baixe o arquivo XML para o SDI",
  'moduli.doc-stampa-titolo': "Pré-visualização, impressão e PDF",
  'moduli.doc-stampa': "Imprimir",
  'moduli.im-scarica-modello': "Baixar o modelo para preencher",
};
