export default {
  'moduli.lumi-serve-chiave': "Para responder preciso da chave do Claude. Vou abrir **Gestão → Lumi**: leva um minuto.",
  'moduli.lumi-serve-chiave-spento': "Para responder preciso da chave do Claude e que você me ligue de novo. Vou abrir **Gestão → Lumi**: leva um minuto.",
  'moduli.lumi-chiedi-titolare': "Para responder preciso da chave do Claude: peça ao proprietário para adicioná-la em **Gestão → Lumi**.",
  'moduli.lumi-spento': "O Lumi está desligado: dá para ligar de novo em Gestão → Lumi.",
  'moduli.lumi-quasi-pronto': "O Lumi está quase pronto: falta a chave do Claude.",
  'moduli.lumi-apri': "Abrir",
  'moduli.lumi-settimana': "Como está a semana",
  'moduli.lumi-settimana-domanda': "Como foi esta semana? Me dê os números principais.",
  'moduli.lumi-accendi': "Ligar o Lumi",
  'moduli.lumi-solo-titolare': "As configurações do Lumi são do proprietário.",
  'moduli.lumi-gia-salvata': "•••••••• (já salva)",
  'moduli.lumi-stato-spento': "Desligado",
  'moduli.lumi-stato-acceso': "Ligado",
  'moduli.lumi-stato-manca': "Falta a chave",
  'moduli.lumi-fonte-ambiente': "A chave vem da variável ANTHROPIC_API_KEY do servidor.",
  'moduli.lumi-fonte-file': "Chave salva neste computador.",
  'moduli.lumi-cos-e': "O Lumi é o assistente do Kubo. Você fala ou escreve para ele na pílula lá em cima: ele busca, conta, prepara fichas e muda a forma do sistema. Cada alteração espera o seu «Confirmar», e cada pessoa só vê o que as permissões dela deixam.",
  'moduli.lumi-chiave': "Chave do Claude",
  'moduli.lumi-salva-chiave': "Salvar a chave",
  'moduli.lumi-incolla': "Cole a chave",
  'moduli.lumi-togliere': "Remover a chave? O Lumi para de responder.",
  'moduli.lumi-dove-chiave': "Você cria em console.anthropic.com, em API Keys. Ela fica neste computador, num arquivo ao lado dos dados que só o Kubo lê, e nunca chega aos navegadores.",
  'moduli.lumi-acceso': "Lumi ligado",
  'moduli.lumi-limite': "Perguntas por minuto por pessoa",
  'moduli.lumi-da-provare': "Para experimentar",
  'moduli.lumi-esempio-1': "Quanto vendi esta semana?",
  'moduli.lumi-esempio-2': "O que preciso repor?",
  'moduli.lumi-esempio-3': "Adicione o tamanho aos produtos com P, M, G e GG",
  'moduli.lumi-esempio-4': "Crie uma seção de aluguéis com cliente, ferramenta, de, até e status",
  'moduli.lumi-esempio-5': "Quando um aluguel passar para devolvido, me avise",
  'moduli.lumi-modello': "Modelo: {modello}.",
  'moduli.lumi-voce-accesa': "Voz em tempo real ligada.",
  'moduli.lumi-voce-browser': "Voz: a do navegador, onde houver.",
  'moduli.ag-adesso': "agora",
  'moduli.ag-agenda': "Agenda",
  'moduli.ag-calendario': "Calendário",
  'moduli.ag-cruscotto': "Painel",
  'moduli.ag-aggiungi-voce': "Adicionar o item",
  'moduli.ag-altri': {"one": "+{n} outro", "other": "+{n} outros"},
  'moduli.ag-e-altri': {"one": "e mais um", "other": "e mais {n}"},
  'moduli.ag-aria-grafico': "{titolo}: gráfico",
  'moduli.ag-barre': "Barras",
  'moduli.ag-linea': "Linha",
  'moduli.ag-buongiorno': "Bom dia",
  'moduli.ag-buon-pomeriggio': "Boa tarde",
  'moduli.ag-buonasera': "Boa noite",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Alterar",
  'moduli.ag-cambia-widget': "Alterar o widget",
  'moduli.ag-nuovo-widget': "Novo widget",
  'moduli.ag-campo': "Campo",
  'moduli.ag-colonne-per': "Colunas: {nome}",
  'moduli.ag-una-colonna': "Uma coluna",
  'moduli.ag-come-oggi': "igual a ontem",
  'moduli.ag-come-settimana': "igual à semana passada",
  'moduli.ag-come-mese': "igual ao mês passado",
  'moduli.ag-come-anno': "igual ao ano passado",
  'moduli.ag-rispetto-oggi': "{diff} em relação a ontem ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} em relação à semana passada ({prima})",
  'moduli.ag-rispetto-mese': "{diff} em relação ao mês passado ({prima})",
  'moduli.ag-rispetto-anno': "{diff} em relação ao ano passado ({prima})",
  'moduli.ag-data-rif': "Data de referência",
  'moduli.ag-prima': "Anterior",
  'moduli.ag-dopo': "Próximo",
  'moduli.ag-fatto': "Pronto",
  'moduli.ag-forma': "Formato",
  'moduli.ag-ha-creato': "criou",
  'moduli.ag-ha-modificato': "alterou",
  'moduli.ag-ha-archiviato': "arquivou",
  'moduli.ag-ha-ripristinato': "restaurou",
  'moduli.ag-in-sezione': "em {nome}",
  'moduli.ag-un-elemento': "um item",
  'moduli.ag-lista': "Lista",
  'moduli.ag-torna-lista': "Voltar à lista",
  'moduli.ag-media': "Média de…",
  'moduli.ag-somma': "Soma de…",
  'moduli.ag-quanti': "Quantos são",
  'moduli.ag-misura': "Medida",
  'moduli.ag-modifica': "Editar",
  'moduli.ag-nome-voce': "Nome do item",
  'moduli.ag-nuova-voce': "Novo item",
  'moduli.ag-un-filtro': "Coloque pelo menos um filtro no item",
  'moduli.ag-non-disegno': "Não consigo desenhar",
  'moduli.ag-oggi': "Hoje",
  'moduli.ag-per': "Por",
  'moduli.ag-periodo': "Período",
  'moduli.ag-periodo-oggi': "Hoje",
  'moduli.ag-periodo-settimana': "Esta semana",
  'moduli.ag-periodo-mese': "Este mês",
  'moduli.ag-periodo-anno': "Este ano",
  'moduli.ag-periodo-ultimi_7': "Últimos 7 dias",
  'moduli.ag-periodo-ultimi_30': "Últimos 30 dias",
  'moduli.ag-periodo-ultimi_84': "Últimas 12 semanas",
  'moduli.ag-periodo-ultimi_365': "Último ano",
  'moduli.ag-periodo-sempre': "Sempre",
  'moduli.ag-piede-grafico': "{periodo} · {totale} no total",
  'moduli.ag-piu-aggiungi': "+ Adicionar",
  'moduli.ag-quale-data': "Qual data",
  'moduli.ag-senza-titolo': "Sem título",
  'moduli.ag-spostato': "Movido",
  'moduli.ag-tipo': "Tipo",
  'moduli.ag-titolo': "Título",
  'moduli.ag-titolo-widget': "Dê um título ao widget",
  'moduli.ag-tutti': "todos",
  'moduli.ag-utente-non-attivo': "Usuário inativo",
  'moduli.ag-vedi-calendario': "Ver no calendário",
  'moduli.ag-vedi-elenco': "Ver a lista",
  'moduli.ag-vedi-giorno': "Ver o dia",
  'moduli.ag-vista-giorno': "Dia",
  'moduli.ag-vista-settimana': "Semana",
  'moduli.ag-vista-mese': "Mês",
  'moduli.ag-w-numero': "Número",
  'moduli.ag-w-grafico': "Gráfico",
  'moduli.ag-w-attenzione': "Precisa de atenção",
  'moduli.ag-w-ultime': "Últimas alterações",
  'moduli.ag-def-incassato-oggi': "Recebido hoje",
  'moduli.ag-def-incassato-mese': "Recebido este mês",
  'moduli.ag-def-vendite-oggi': "Vendas hoje",
  'moduli.ag-def-incassi-30': "Recebimentos dos últimos 30 dias",
  'moduli.ag-def-appuntamenti-oggi': "Agendamentos hoje",
  'moduli.ag-def-appuntamenti-settimana': "Agendamentos por semana",
  'moduli.ag-def-preventivi-attesa': "Orçamentos aguardando",
  'moduli.ag-def-commesse-aperte': "Pedidos em aberto",
  'moduli.ag-def-accettato-mese': "Aprovado este mês",
  'moduli.ag-def-preventivi-mese': "Orçamentos aprovados por mês",
  'moduli.ag-def-articoli-riordinare': "Produtos para repor",
  'moduli.ag-def-materiali-riordinare': "Materiais para repor",
  'moduli.ag-def-ordini-ritardo': "Pedidos atrasados",
  'moduli.ag-def-vendite-aperte': "Vendas abertas há mais de 2 dias",
  'moduli.ag-def-commesse-ritardo': "Pedidos atrasados",
  'moduli.ag-def-preventivi-senza-risposta': "Orçamentos sem resposta há 7 dias",
  'moduli.ag-def-appuntamenti-chiudere': "Agendamentos passados para fechar",
  'moduli.ag-def-pacchetti-scaduti': "Pacotes vencidos com sessões",
  'moduli.ag-def-attenzione': "Precisa de atenção",
  'moduli.ag-def-ultime': "Últimas alterações",
  'moduli.ag-def-nuovi-mese': "{nome}: novos este mês",
  'moduli.ag-tutto-ok': "✓ Tudo em ordem: nada para resolver.",
  'moduli.ag-nessuna-modifica': "Nenhuma alteração ainda.",
  'moduli.ag-es-titolo': "Ex.: Recebido hoje",
};
