// Area «sicurezza» (web/moduli/sicurezza.js): password, dispositivi collegati, impostazioni dell'azienda, poteri dei ruoli.
export default {
  'sicurezza.titolo': 'Segurança',
  'sicurezza.la-tua-password': 'Sua senha',
  'sicurezza.dispositivi-collegati': 'Dispositivos conectados',
  'sicurezza.dispositivo': '{browser} no {sistema}',
  'sicurezza.dispositivo-sconosciuto': 'Dispositivo desconhecido',
  'sicurezza.app-kubo': 'App Kubo',
  'sicurezza.iphone-ipad': 'iPhone ou iPad',
  'sicurezza.password-diverse': 'As duas senhas novas não são iguais',
  'sicurezza.password-cambiata': 'Senha alterada. Os outros dispositivos foram desconectados.',
  'sicurezza.password-attuale': 'Senha atual',
  'sicurezza.password-nuova': 'Nova senha',
  'sicurezza.password-regole': 'Pelo menos 8 caracteres; com menos de 12, misture letras com números ou símbolos.',
  'sicurezza.password-ripeti': 'Repita a nova senha',
  'sicurezza.cambia-password': 'Alterar senha',
  'sicurezza.col-dispositivo': 'Dispositivo',
  'sicurezza.col-ultimo-uso': 'Último uso',
  'sicurezza.col-indirizzo': 'Endereço',
  'sicurezza.questo': 'este',
  'sicurezza.scollega': 'Desconectar',
  'sicurezza.scollegati': { one: '{n} dispositivo desconectado', other: '{n} dispositivos desconectados' },
  'sicurezza.scollega-altri': 'Desconectar todos os outros',
  'sicurezza.impostazioni': 'Configurações da empresa',
  'sicurezza.inattivita': 'Encerrar sessões paradas há (minutos)',
  'sicurezza.allegati': 'Anexos: no máximo (MB)',
  'sicurezza.fuso': 'Fuso horário',
  'sicurezza.lumi-budget': 'Lumi: tokens por mês (0 = sem limite)',
  'sicurezza.lumi-usati': 'Usados este mês: {usati}',
  'sicurezza.webhook-interni': 'Permitir webhooks para a rede interna (127.0.0.1, 192.168…). Deixe desligado se não souber para que serve.',
  'sicurezza.salvate': 'Configurações salvas',
  'sicurezza.salva': 'Salvar',
  'sicurezza.ruoli': 'Permissões dos papéis',
  'sicurezza.ruoli-nota': 'Exportar a nota fiscal eletrônica consome um número de envio; o Lumi usa os tokens da empresa.',
  'sicurezza.col-ruolo': 'Papel',
  'sicurezza.potere-fatturapa': 'Exportar FatturaPA',
  'sicurezza.potere-lumi': 'Usar o Lumi',
  'sicurezza.potere-aria': '{potere} para {ruolo}',
  'sicurezza.salvato': 'Salvo',
  'sicurezza.persone': 'Pessoas',
  'sicurezza.col-nome': 'Nome',
  'sicurezza.obbliga-cambio': 'Obrigar a trocar a senha',
  'sicurezza.obbligo-fatto': '{nome} vai trocar a senha no próximo acesso',
  'sicurezza.scollega-ovunque': 'Desconectar de todos',
  'sicurezza.scollegato-ovunque': 'Sessões de {nome} encerradas em todos os dispositivos',
  'sicurezza.nessun-altro': 'Mais ninguém.',
  'sicurezza.scegli-password': 'Escolha sua senha',
  'sicurezza.provvisoria': 'A senha que você recebeu era provisória. Escolha uma sua para continuar.',
};
