// Tesouraria (web/moduli/tesoreria.js): vencimentos, conciliação bancária, previsão de caixa, cobranças, remessas.
export default {
  'tesoreria.titolo': "Tesouraria",
  'tesoreria.scheda-scadenze': "Vencimentos",
  'tesoreria.scheda-banca': "Banco",
  'tesoreria.scheda-cassa': "Previsão de caixa",
  'tesoreria.scheda-solleciti': "Cobranças",
  'tesoreria.scheda-distinte': "Remessas",
  'tesoreria.scheda-impostazioni': "Configurações",
  'tesoreria.manca-fatture': "Os vencimentos vêm das faturas: adicione o modelo «Faturas e nota fiscal eletrônica» em Personalizar.",
  'tesoreria.da-incassare': "A receber",
  'tesoreria.da-pagare': "A pagar",
  'tesoreria.di-cui-scaduto': "dos quais vencido {importo}",
  'tesoreria.saldo-netto': "Diferença",
  'tesoreria.verso-attiva': "Recebimentos de clientes",
  'tesoreria.verso-passiva': "Pagamentos a fornecedores",
  'tesoreria.solo-scadute': "Só vencidos",
  'tesoreria.cerca': "Buscar cliente ou documento",
  'tesoreria.scadenza': "Vencimento",
  'tesoreria.documento': "Documento",
  'tesoreria.cliente': "Cliente",
  'tesoreria.fornitore': "Fornecedor",
  'tesoreria.importo': "Valor",
  'tesoreria.residuo': "Em aberto",
  'tesoreria.stato': "Situação",
  'tesoreria.pagata': "Paga",
  'tesoreria.in-distinta': "Em remessa",
  'tesoreria.scaduta-da': { one: "Vencida há {n} dia", other: "Vencida há {n} dias" },
  'tesoreria.parziale': "Pagamento parcial",
  'tesoreria.aperta': "Aberta",
  'tesoreria.incassata': "Recebida",
  'tesoreria.pagata-btn': "Paga",
  'tesoreria.acconto': "Pagamento parcial",
  'tesoreria.niente-scadenze': "Nenhum vencimento em aberto.",
  'tesoreria.scegli-nota': "Marque os vencimentos para dá-los como pagos ou preparar o arquivo para o banco.",
  'tesoreria.scelte': { one: "{n} escolhido · {importo}", other: "{n} escolhidos · {importo}" },
  'tesoreria.segna-incassate': "Marcar como recebidos",
  'tesoreria.segna-pagate': "Marcar como pagos",
  'tesoreria.distinta-riba': "Remessa Ri.Ba.",
  'tesoreria.distinta-sdd': "Débito SDD",
  'tesoreria.distinta-sct': "Transferências SEPA",
  'tesoreria.data-pagamento': "Data do pagamento (AAAA-MM-DD)",
  'tesoreria.data-esecuzione': "Data de execução no banco (AAAA-MM-DD)",
  'tesoreria.data-accredito': "Data do crédito ou do pagamento (AAAA-MM-DD)",
  'tesoreria.importo-acconto': "Valor recebido ou pago",
  'tesoreria.importo-non-valido': "Valor inválido",
  'tesoreria.incassi-registrati': { one: "Recebimento registrado", other: "{n} recebimentos registrados" },
  'tesoreria.pagamenti-registrati': { one: "Pagamento registrado", other: "{n} pagamentos registrados" },
  'tesoreria.distinta-creata': "{nome} pronta: {importo}. Envie o arquivo pelo internet banking.",
  'tesoreria.nota-termini': "Os vencimentos vêm das parcelas da fatura, da data de vencimento ou das condições de pagamento do cliente ou do fornecedor (por exemplo 30/60/90 DFFM).",
  'tesoreria.err-sia': "Falta o código SIA da empresa (o banco fornece): escreva-o nas configurações da tesouraria.",
  'tesoreria.err-iban-azienda': "Falta o IBAN da empresa, ou está errado: Documentos → dados da empresa.",
  'tesoreria.err-banca-debitore': "{nome}: falta o IBAN do banco do cliente na ficha dele.",
  'tesoreria.err-cf-debitore': "{nome}: falta o número de IVA ou o código fiscal.",
  'tesoreria.err-importo': "{nome}: valor a receber inválido.",
  'tesoreria.err-id-creditore': "Falta o identificador de credor SEPA (o banco emite): configurações da tesouraria.",
  'tesoreria.err-iban-debitore': "{nome}: IBAN do cliente ausente ou errado.",
  'tesoreria.err-mandato': "{nome}: faltam a referência e a data do mandato SDD na ficha do cliente.",
  'tesoreria.err-iban-beneficiario': "{nome}: IBAN do fornecedor ausente ou errado.",
  'tesoreria.banca-titolo': "Extrato e conciliação",
  'tesoreria.manca-movimenti': "Para importar o extrato é preciso a seção «Movimentos bancários».",
  'tesoreria.prepara': "Preparar a tesouraria",
  'tesoreria.preparata': { one: "{n} item adicionado", other: "{n} itens adicionados" },
  'tesoreria.chiedi-titolare': "Peça a quem pode personalizar o sistema.",
  'tesoreria.file-grande': "{nome} é grande demais",
  'tesoreria.importati': "{n} movimentos importados, {doppi} já existiam",
  'tesoreria.saldo-aggiornato': "Saldo da previsão atualizado: {importo} em {data}",
  'tesoreria.carica-estratto': "Arraste o extrato aqui, ou clique",
  'tesoreria.formati': "CAMT.053 (XML), CBI, CSV ou Excel do banco",
  'tesoreria.abbinato': "Conciliado: vencimentos marcados como pagos",
  'tesoreria.abbinato-differenza': "Conciliado; sobram {importo}",
  'tesoreria.abbina-a': "Conciliar com…",
  'tesoreria.abbina': "Conciliar",
  'tesoreria.ignora': "Ignorar",
  'tesoreria.ignora-nota': "Tarifas, transferências internas, salários: movimentos que não quitam uma fatura",
  'tesoreria.nessuna-proposta': "Nenhuma sugestão: escolha à mão aqui embaixo.",
  'tesoreria.da-abbinare': { one: "{n} movimento para conciliar", other: "{n} movimentos para conciliar" },
  'tesoreria.tutto-abbinato': "Tudo conciliado.",
  'tesoreria.abbinati-recenti': "Conciliados recentemente",
  'tesoreria.data': "Data",
  'tesoreria.descrizione': "Descrição",
  'tesoreria.mov-abbinato': "Conciliado",
  'tesoreria.mov-ignorato': "Ignorado",
  'tesoreria.mov-da_abbinare': "Para conciliar",
  'tesoreria.annulla': "Desfazer",
  'tesoreria.nota-movimenti': "Os movimentos ficam na seção «{sezione}»: as conexões com o banco (open banking) também a preenchem.",
  'tesoreria.perche-importo': "mesmo valor",
  'tesoreria.perche-importo-vicino': "valor parecido",
  'tesoreria.perche-acconto': "pagamento parcial",
  'tesoreria.perche-numero': "número da fatura",
  'tesoreria.perche-iban': "mesmo IBAN",
  'tesoreria.perche-nome': "nome",
  'tesoreria.perche-data': "data próxima",
  'tesoreria.perche-somma': "várias faturas juntas",
  'tesoreria.perche-distinta': "crédito da remessa",
  'tesoreria.grafico': "Entradas, saídas e saldo previstos",
  'tesoreria.passo-settimana': "Semanas",
  'tesoreria.passo-mese': "Meses",
  'tesoreria.senza-saldo': "Falta o saldo inicial: escreva-o nas configurações ou importe um extrato CAMT.053.",
  'tesoreria.apri-impostazioni': "Abrir as configurações",
  'tesoreria.scoperto': "Atenção: o caixa fica negativo, até {importo} em {data}.",
  'tesoreria.saldo-oggi': "Saldo hoje",
  'tesoreria.saldo-dal': "a partir do saldo de {data} mais os movimentos",
  'tesoreria.saldo-fine': "Saldo previsto",
  'tesoreria.punto-basso': "Ponto mais baixo",
  'tesoreria.entrate': "Entradas",
  'tesoreria.uscite': "Saídas",
  'tesoreria.saldo': "Saldo",
  'tesoreria.periodi': "Por período",
  'tesoreria.periodo': "Período",
  'tesoreria.voci': "De onde vêm os números",
  'tesoreria.tipo': "Tipo",
  'tesoreria.voce-incasso': "Recebimento",
  'tesoreria.voce-pagamento': "Pagamento",
  'tesoreria.voce-previsione': "Previsão",
  'tesoreria.voce-contratto': "Contrato recorrente",
  'tesoreria.voce-tasse': "Impostos",
  'tesoreria.ritardo-medio': { one: "o cliente paga em média {n} dia atrasado", other: "o cliente paga em média {n} dias atrasado" },
  'tesoreria.niente-voci': "Nada previsto no período.",
  'tesoreria.aggiungi-previsione': "Adicione aluguel, salários, empréstimos e outras previsões",
  'tesoreria.sollecito-segnato': "Cobrança registrada",
  'tesoreria.livello-1': "Lembrete gentil",
  'tesoreria.livello-2': "Cobrança",
  'tesoreria.livello-3': "Notificação formal",
  'tesoreria.appena-sollecitato': "Cobrado recentemente",
  'tesoreria.ritardo-giorni': { one: "{n} dia de atraso", other: "{n} dias de atraso" },
  'tesoreria.ultimo-sollecito': "Última cobrança em {data} (nível {livello})",
  'tesoreria.lettera': "Texto da cobrança",
  'tesoreria.copia': "Copiar o texto",
  'tesoreria.copiato': "Copiado",
  'tesoreria.copia-no': "Não foi possível copiar: selecione o texto à mão",
  'tesoreria.oggetto-sollecito': "Lembrete de pagamento",
  'tesoreria.scrivi-email': "Escrever o e-mail",
  'tesoreria.segna-mandato': "Marcar como enviado",
  'tesoreria.niente-solleciti': "Nenhum cliente em atraso.",
  'tesoreria.distinta-chiusa': "Remessa fechada: vencimentos marcados como pagos",
  'tesoreria.distinta': "Remessa",
  'tesoreria.creata': "Criada",
  'tesoreria.quante': "Vencimentos",
  'tesoreria.pagata-il': "Paga em {data}",
  'tesoreria.accreditata-il': "Creditada em {data}",
  'tesoreria.in-attesa': "Pendente",
  'tesoreria.scarica': "Baixar",
  'tesoreria.segna-pagati': "Marcar como pagos",
  'tesoreria.segna-accreditata': "Marcar como creditada",
  'tesoreria.niente-distinte': "Ainda nenhuma remessa: elas se preparam a partir dos vencimentos.",
  'tesoreria.nota-distinte': "O arquivo é enviado pelo internet banking (Ri.Ba. no formato CBI, SDD e transferências em SEPA XML). Quando o banco credita a remessa, a conciliação a sugere sozinha.",
  'tesoreria.salvate': "Configurações salvas",
  'tesoreria.sia': "Código SIA",
  'tesoreria.bic': "BIC do seu banco (opcional)",
  'tesoreria.id-creditore': "Identificador de credor SEPA (para SDD)",
  'tesoreria.saldo-banca': "Saldo da conta",
  'tesoreria.saldo-data': "Saldo em",
  'tesoreria.sequenza-sdd': "Tipo de débito SDD",
  'tesoreria.seq-rcur': "Recorrente (RCUR)",
  'tesoreria.seq-frst': "Primeiro de uma série (FRST)",
  'tesoreria.seq-ooff': "Avulso (OOFF)",
  'tesoreria.sezione-movimenti': "Seção dos movimentos bancários",
  'tesoreria.ritardo-clienti': "Na previsão, deslocar os recebimentos pelo atraso médio de cada cliente",
  'tesoreria.salva': "Salvar",
  'tesoreria.banca-azienda': "A conta da empresa",
  'tesoreria.iban-azienda': "IBAN usado para Ri.Ba., SDD e transferências: {iban}",
  'tesoreria.manca-iban': "Falta o IBAN da empresa.",
  'tesoreria.dati-azienda': "Dados da empresa",
  'tesoreria.nota-sia': "O código SIA e o identificador de credor são fornecidos pelo banco quando você ativa Ri.Ba. e SDD. O identificador sugerido é calculado a partir do número de IVA: confira com o banco.",
  'tesoreria.sezioni': "Seções",
  'tesoreria.sezioni-mancano': "Faltam «Movimentos bancários» ou «Previsões de caixa», e os campos de pagamento de clientes e fornecedores (condições, IBAN, mandato SDD).",
  'tesoreria.sezioni-ci-sono': "Estão todas.",
  'tesoreria.termini': "Condições de pagamento",
  'tesoreria.termini-nota': "São escritas na ficha do cliente ou do fornecedor. DF = data da fatura, FM = fim do mês, +10 = dia 10 do mês seguinte. 30, 60 e 90 dias contam como meses.",
};
