export default {
  'viste.cerca-in': 'Buscar em {nome}…',
  'viste.nuovo': '+ Novo',
  'viste.tabella': 'Tabela',
  'viste.kanban': 'Kanban',
  'viste.archiviati': 'Arquivados',
  'viste.viste-salvate': 'Visualizações salvas',
  'viste.colonne': 'Colunas',
  'viste.raggruppa': 'Agrupar',
  'viste.senza-gruppi': 'Sem grupos',
  'viste.gruppi-per': 'Grupos: {nome}',
  'viste.salva-vista': 'Salvar visualização',
  'viste.tutti': 'Todos',
  'viste.per-tutti': 'Para todos',
  'viste.mie': 'Minhas',
  'viste.filtri-tolti': 'Alguns filtros desta visualização usam campos que você não vê: eu os removi',
  'viste.salva-modifiche': 'Salvar alterações…',
  'viste.esempio-vista': 'Ex.: Para entregar esta semana',
  'viste.nome-vista': 'Dê um nome à visualização',
  'viste.salvata-tutti': 'Visualização salva para todos',
  'viste.salvata-te': 'Visualização salva para você',
  'viste.vista-nome': 'Visualização «{nome}»',
  'viste.salva-questa': 'Salvar esta visualização',
  'viste.cosa-salva': 'Filtros, colunas, grupos e ordem atuais.',
  'viste.la-vedono-tutti': 'Todos podem ver',
  'viste.solo-tu': 'Só você vai ver.',
  'viste.elimina': 'Excluir',
  'viste.elimina-vista': 'Excluir a visualização «{nome}»?',
  'viste.vista-eliminata': 'Visualização excluída',
  'viste.salva-nuova': 'Salvar como nova',
  'viste.aggiorna': 'Atualizar',
  'viste.salva': 'Salvar',
  'viste.come-inizio': 'Como no início',
  'viste.nessuno': 'Nenhum',
  'viste.nessun-risultato': 'Nenhum resultado.',
  'viste.niente-archivio': 'Nada no arquivo.',
  'viste.ancora-nessuno': 'Ainda não há nada em {nome}.',
  'viste.crea-primo': '+ Criar o primeiro',
  'viste.totale': 'Total ({n})',
  'viste.prime-di': 'Mostrando os primeiros {k} de {n} (os totais contam todos)',
  'viste.in-tutto': { one: '{n} no total', other: '{n} no total' },
  'viste.crea': 'Criar',
  'viste.creato': 'Criado',
  'viste.salvato': 'Salvo',
  'viste.nuovo-in': 'Novo em {nome}',
  'viste.archivia': 'Arquivar',
  'viste.archiviare': 'Arquivar? Dá para restaurar pelo arquivo.',
  'viste.archiviato': 'Arquivado',
  'viste.ripristina': 'Restaurar',
  'viste.ripristinato': 'Restaurado',
  'viste.storia': 'Histórico',
  'viste.archiviato-min': 'arquivado',
  'viste.automazione': 'automação',
  'viste.storia-creato': 'criado',
  'viste.storia-ripristinato': 'restaurado',
  'viste.non-si-passa': 'De «{da}» não dá para vir para cá',
  'viste.al-salvataggio': 'ao salvar',
  'viste.piu-immagine': '+ Imagem',
  'viste.piu-file': '+ Arquivo',
  'viste.non-immagine': '«{nome}» não é uma imagem',
  'viste.o-trascina': 'ou arraste para cá',
  'viste.righe-non-trovata': 'Entidade dos itens não encontrada',
  'viste.aggiungi-riga': '+ Adicionar item',
  'viste.creato-il': 'Criado em',
  'viste.modificato-il': 'Alterado em',
  'viste.periodo-oggi': 'hoje',
  'viste.periodo-ieri': 'ontem',
  'viste.periodo-settimana': 'esta semana',
  'viste.periodo-mese': 'este mês',
  'viste.periodo-ultimi_7': 'últimos 7 dias',
  'viste.periodo-ultimi_30': 'últimos 30 dias',
  'viste.periodo-anno': 'este ano',
  'viste.op-uguale': 'é',
  'viste.op-diverso': 'não é',
  'viste.op-tra': 'entre',
  'viste.op-contiene': 'contém',
  'viste.op-inizia': 'começa com',
  'viste.op-vuoto': 'está vazio',
  'viste.op-nonvuoto': 'não está vazio',
  'viste.op-in': 'é um de',
  'viste.op-prima': 'antes de',
  'viste.op-dopo': 'a partir de',
  'viste.op-vero': 'é verdadeiro',
  'viste.op-falso': 'é falso',
  'viste.o': ' ou ',
  'viste.tra-e': '{a} e {b}',
  'viste.io': 'eu',
  'viste.me': 'mim',
  'viste.io-maiuscolo': 'Eu',
  'viste.piu-filtro': '+ Filtro',
  'viste.cambia-filtro': 'Mudar o filtro',
  'viste.togli-tutti': 'Remover todos',
  'viste.scegli-campo': 'Escolha o campo…',
  'viste.nel-periodo': 'no período',
  'viste.testo': 'texto',
  'viste.scegli-un-campo': 'Escolha um campo',
  'viste.manca-valore': 'Falta o valor',
  'viste.nuovo-filtro': 'Novo filtro',
  'viste.applica': 'Aplicar',
};
