// Il modulo WhatsApp dell'interfaccia (web/moduli/whatsapp.js): conversazioni, modelli, automazioni, impostazioni.
export default {
  'whatsapp.forse-stop': 'Parece um pedido para não receber mais mensagens',
  'whatsapp.segna-stop': 'Marcar STOP',
  'whatsapp.s-approvato': "Aprovado",
  'whatsapp.s-in_attesa': "Pendente",
  'whatsapp.s-rifiutato': "Rejeitado",
  'whatsapp.s-in_pausa': "Pausado",
  'whatsapp.s-disattivato': "Desativado",
  'whatsapp.s-inviato': "Enviado",
  'whatsapp.s-consegnato': "Entregue",
  'whatsapp.s-letto': "Lido",
  'whatsapp.s-fallito': "Falhou",
  'whatsapp.s-bloccato': "Bloqueado",
  'whatsapp.s-coda': "Na fila",
  'whatsapp.s-ricevuto': "Recebido",
  'whatsapp.finestra-aperta': "Janela aberta até {ora}",
  'whatsapp.finestra-chiusa': "Janela fechada: é preciso um modelo",
  'whatsapp.attivo': "Ativo: {nome}",
  'whatsapp.nessuno': "Nenhum serviço WhatsApp ativo.",
  'whatsapp.vai-connettori': "Conecte pelos conectores",
  'whatsapp.conversazioni': "Conversas",
  'whatsapp.modelli': "Modelos",
  'whatsapp.automazioni': "Automações de WhatsApp",
  'whatsapp.impostazioni': "Configurações",
  'whatsapp.vuoto': "Ainda não há mensagens.",
  'whatsapp.scegli': "Escolha uma conversa.",
  'whatsapp.c-servizio': "Serviço",
  'whatsapp.c-marketing': "Promoções",
  'whatsapp.si-no-si': "sim",
  'whatsapp.si-no-no': "não",
  'whatsapp.fonte-chiedi': "Como você registrou a escolha? (ex. formulário na loja, site, pessoalmente)",
  'whatsapp.testo-chiedi': "As palavras exatas que o cliente aceitou:",
  'whatsapp.testo-predefinito': "Aceito receber mensagens de WhatsApp desta empresa. Posso responder STOP a qualquer momento.",
  'whatsapp.ok-servizio': "Consentimento de serviço",
  'whatsapp.ok-marketing': "Consentimento de promoções",
  'whatsapp.revoca': "Revogar",
  'whatsapp.sconosciuto': "Número fora da agenda.",
  'whatsapp.crea-cliente': "Criar cliente",
  'whatsapp.crea-lead': "Criar lead",
  'whatsapp.scrivi': "Escreva uma resposta…",
  'whatsapp.serve-modello': "Fora da janela de 24 horas: escolha um modelo aprovado",
  'whatsapp.testo-libero': "Texto livre",
  'whatsapp.scegli-modello': "Escolha um modelo",
  'whatsapp.k-servizio': "Serviço",
  'whatsapp.k-utility': "Utilidade",
  'whatsapp.k-marketing': "Marketing",
  'whatsapp.k-authentication': "Autenticação",
  'whatsapp.costo': "Custo estimado",
  'whatsapp.inviato': "Mensagem enviada",
  'whatsapp.invia': "Enviar",
  'whatsapp.anteprima': "Pré-visualizar",
  'whatsapp.sincronizzati': "Modelos atualizados",
  'whatsapp.sincronizza': "Sincronizar modelos",
  'whatsapp.salvato': "Salvo",
  'whatsapp.modelli-nota': "Cada variável {{n}} recebe o valor de um campo: por exemplo cliente.nome ou riga.quando.",
  'whatsapp.nessun-modello': "Nenhum modelo: sincronize ou crie um.",
  'whatsapp.corpo-esempio': "Olá {{1}}, seu pedido está pronto.",
  'whatsapp.esempi-esempio': "Mario; terça às 15h",
  'whatsapp.nuovo-modello': "Novo modelo",
  'whatsapp.nuovo-nota': "A Meta revisa antes de aprovar, geralmente em poucos minutos. Cada variável precisa de um exemplo. Modelos com PDF no cabeçalho são criados no WhatsApp Manager.",
  'whatsapp.nome': "Nome (minúsculas, números, _)",
  'whatsapp.categoria': "Categoria",
  'whatsapp.lingua': "Idioma",
  'whatsapp.testo': "Texto",
  'whatsapp.esempi': "Exemplos das variáveis, separados por ;",
  'whatsapp.mandato-a-meta': "Modelo enviado para aprovação",
  'whatsapp.manda-approvazione': "Enviar para aprovação",
  'whatsapp.automazioni-nota': "Ative as que precisar, escolha o modelo e o momento. Antes de cada envio o Lumi verifica consentimento, STOP, horas de silêncio e limites.",
  'whatsapp.o-ore': "Horas antes (ex. 24, 2)",
  'whatsapp.o-giorni': "Depois de quantos dias",
  'whatsapp.o-mesi': "Inativo há meses",
  'whatsapp.o-link': "Link para a avaliação",
  'whatsapp.o-testo': "Texto da resposta",
  'whatsapp.esempio-da-approvare': "Exemplo de modelo: crie, peça aprovação e depois escolha aqui.",
  'whatsapp.mancano': "Variáveis sem valor: {n}",
  'whatsapp.salva': "Salvar",
  'whatsapp.r-promemoria': "Lembrete de compromisso",
  'whatsapp.r-conferma': "Confirmação de reserva",
  'whatsapp.r-pronto': "Pedido pronto ou enviado",
  'whatsapp.r-documento': "Fatura ou orçamento com PDF",
  'whatsapp.r-sollecito': "Lembrete de pagamento",
  'whatsapp.r-recensione': "Pedido de avaliação",
  'whatsapp.r-compleanno': "Felicitações de aniversário",
  'whatsapp.r-riattivazione': "Reativar clientes inativos",
  'whatsapp.r-fuori_orario': "Resposta fora do horário",
  'whatsapp.rd-promemoria': "Uma mensagem antes do compromisso (24 e 2 horas antes, ou como quiser).",
  'whatsapp.rd-conferma': "Assim que uma reserva é criada.",
  'whatsapp.rd-pronto': "Quando o status muda para pronto ou enviado, com o código de rastreio se houver.",
  'whatsapp.rd-documento': "Quando a fatura é emitida ou o orçamento enviado: o PDF vai com um modelo com documento no cabeçalho.",
  'whatsapp.rd-sollecito': "Toda manhã, para faturas vencidas há N dias (uma vez por fatura).",
  'whatsapp.rd-recensione': "N dias após a venda, com o link para sua página de avaliações.",
  'whatsapp.rd-compleanno': "Na manhã do aniversário do cliente.",
  'whatsapp.rd-riattivazione': "A quem não volta há N meses, uma única vez.",
  'whatsapp.rd-fuori_orario': "Quando um cliente escreve com a loja fechada: texto livre, no máximo uma vez a cada 12 horas.",
  'whatsapp.serve-marketing': "Promocional: só para quem aceitou promoções, nunca nas horas de silêncio.",
  'whatsapp.non-possibile': "Sua gestão não tem as seções ou campos que esta automação precisa.",
  'whatsapp.modello': "Modelo",
  'whatsapp.i-prefisso': "Código do país padrão",
  'whatsapp.i-silenzio-da': "Silêncio a partir das",
  'whatsapp.i-silenzio-a': "até",
  'whatsapp.i-silenzio-tutti': "Silêncio também para mensagens automáticas de serviço",
  'whatsapp.i-limite-giorno': "Modelos por dia, no total",
  'whatsapp.i-limite-cliente': "Modelos por dia por cliente",
  'whatsapp.i-marketing-giorni': "Uma promoção a cada quantos dias",
  'whatsapp.i-sconosciuti': "Quem escreve e não está na agenda",
  'whatsapp.i-apre': "Abre às",
  'whatsapp.i-chiude': "Fecha às",
  'whatsapp.i-giorni': "Dias abertos (0 = domingo)",
  'whatsapp.i-t-marketing': "Marketing, € por mensagem",
  'whatsapp.i-t-utility': "Utilidade, € por mensagem",
  'whatsapp.i-t-authentication': "Autenticação, € por mensagem",
  'whatsapp.i-t-servizio': "Serviço, € além da cota gratuita",
  'whatsapp.i-t-servizioGratisMese': "Mensagens de serviço grátis por mês (vazio = todas)",
  'whatsapp.i-t-twilio': "Taxa da Twilio, € por mensagem",
  'whatsapp.sc-chiedi': "Perguntar (fica como número)",
  'whatsapp.sc-cliente': "Criar um cliente",
  'whatsapp.sc-lead': "Criar um lead",
  'whatsapp.webhook': "Endereço do webhook",
  'whatsapp.webhook-meta': "Cole na Meta (WhatsApp → Configuração) com o token de verificação da página do conector e assine messages e message_template_status_update. Precisa ser acessível pela internet em https.",
  'whatsapp.webhook-360': "O Lumi registra sozinho na 360dialog quando o endereço público está na página do conector.",
  'whatsapp.webhook-twilio': "Cole no remetente WhatsApp da Twilio como endereço das mensagens recebidas. O endereço público do conector deve ser o que a Twilio vê.",
  'whatsapp.apri-connettore': "Abrir o conector",
  'whatsapp.costi-mese': "Este mês",
  'whatsapp.nessun-costo': "Nenhuma mensagem paga este mês.",
  'whatsapp.costi-nota': "Estimativa com as tarifas da Meta para a Itália ({data}): vale a fatura da Meta ou do seu fornecedor.",
  'whatsapp.regole': "Regras de envio",
  'whatsapp.tariffe': "Tarifas",
  'whatsapp.tariffe-nota': "A Meta atualiza a tabela a cada trimestre: corrija aqui os valores se mudarem.",
  'whatsapp.registro': "Mensagens bloqueadas ou com falha",
  'whatsapp.registro-vuoto': "Nada a relatar.",
  'whatsapp.storia': "Histórico do WhatsApp",
  'whatsapp.senza-numero': "O cliente não tem número de telefone.",
  'whatsapp.apri-chat': "Abrir a conversa",
};
