// Purchasing (web/moduli/acquisti.js): reorder, incoming orders, receipts, supplier invoices.
export default {
  'acquisti.titolo': "Purchasing",
  'acquisti.scheda-riordino': "To reorder",
  'acquisti.scheda-arrivo': "Incoming",
  'acquisti.scheda-fatture': "Supplier invoices",
  'acquisti.stato-bozza': "Draft",
  'acquisti.stato-inviato': "Sent",
  'acquisti.stato-parziale': "Partly received",
  'acquisti.stato-arrivato': "Received",
  'acquisti.stato-annullato': "Cancelled",
  'acquisti.serve-magazzino': "Purchasing needs a section with stock levels (items, spare parts, materials…).",
  'acquisti.non-pronti': "Purchasing isn't set up yet.",
  'acquisti.chiedi-titolare': "Ask someone who can customise the system.",
  'acquisti.magazzino': "Stock section",
  'acquisti.prepara-titolo': "Set up purchasing",
  'acquisti.prepara-nota': "Kubo uses the existing «Supplier orders», or creates them, and adds the received quantity, the «partly received» status, the delivery note and the supplier invoice. Your data doesn't change.",
  'acquisti.prepara': "Set up",
  'acquisti.preparati': {"one": "Added {n} item", "other": "Added {n} items"},
  'acquisti.niente-riordino': "Nothing below minimum: everything is above the threshold, or already ordered.",
  'acquisti.fornitore': "Supplier",
  'acquisti.scegli-fornitore': "Choose the supplier…",
  'acquisti.da-ordinare': "To order",
  'acquisti.senza-fornitore': "No supplier",
  'acquisti.senza-fornitore-nota': "These items have no supplier on their record: choose one here.",
  'acquisti.articolo': "Item",
  'acquisti.giacenza': "Stock",
  'acquisti.soglia': "Minimum",
  'acquisti.in-arrivo': "Incoming",
  'acquisti.costo': "Cost",
  'acquisti.totale-stimato': "Estimated total: {importo}",
  'acquisti.niente-scelto': "You haven't chosen anything to order",
  'acquisti.ordini-creati': {"one": "Created {n} draft order", "other": "Created {n} draft orders"},
  'acquisti.riordino-nota': "Below minimum means stock plus what's already ordered is no more than the threshold. Kubo suggests getting back to twice the threshold: adjust the quantities as you like.",
  'acquisti.crea-ordini': "Create orders",
  'acquisti.crea-nota': "One draft order per supplier: check it and send it.",
  'acquisti.in-ritardo': "Late: expected on {data}",
  'acquisti.previsto': "Expected on {data}",
  'acquisti.ricevi': "Receive goods",
  'acquisti.ricevute-di': "{ricevuta} of {quantita}",
  'acquisti.niente-arrivo': "No incoming orders.",
  'acquisti.ordine-chiuso': "This order is already closed.",
  'acquisti.vedi-confronto': "See the comparison",
  'acquisti.ddt-segnaposto': "Delivery note number and date",
  'acquisti.ricevuto-tutto': "Goods received: order complete",
  'acquisti.ricevuto-parte': "Goods received: the order stays open for the rest",
  'acquisti.ricevi-titolo': "Receive goods: {numero}, {fornitore}",
  'acquisti.ddt': "Supplier delivery note",
  'acquisti.data': "Date",
  'acquisti.ordinate': "Ordered",
  'acquisti.gia-ricevute': "Already received",
  'acquisti.arrivate-ora': "Arrived now",
  'acquisti.ricevi-nota': "Arrived quantities go into stock straight away, and the item cost becomes the weighted average cost. Whatever is missing stays incoming.",
  'acquisti.carica': "Add to stock",
  'acquisti.annulla': "Cancel",
  'acquisti.senza-fatture': "Matching invoices needs the «Invoices and e-invoicing» template.",
  'acquisti.ordine': "Order",
  'acquisti.ricevuto': "Received",
  'acquisti.fattura-proposta': "Suggested invoice",
  'acquisti.candidata': "{numero}: {importo}",
  'acquisti.nessuna-fattura': "No invoice from this supplier",
  'acquisti.confronta': "Compare",
  'acquisti.tutto-fatturato': "Every received delivery has its invoice.",
  'acquisti.fatture-nota': "Kubo compares the value of the goods received with the taxable amount of the supplier's invoices. It matches if the difference is within €1 or 1%.",
  'acquisti.abbinata': "Invoice matched",
  'acquisti.tolta': "Invoice removed",
  'acquisti.ordinato': "Ordered",
  'acquisti.fatturato': "Invoiced",
  'acquisti.confronto-titolo': "{numero} · {fornitore}",
  'acquisti.torna': "Matches invoice {numero}.",
  'acquisti.non-torna': "Invoice {numero} doesn't match: difference {importo}.",
  'acquisti.togli': "Remove",
  'acquisti.candidate': "Candidate invoices",
  'acquisti.fattura': "Invoice",
  'acquisti.imponibile': "Taxable amount",
  'acquisti.differenza': "Difference",
  'acquisti.abbina': "Match",
  'acquisti.ricevimenti': "Receipts",
  'acquisti.quantita': "Quantity",
};
