// Area «avvio» (web/moduli/avvio.js) · English.
export default {
  'avvio.avanti': "Next",
  'avvio.indietro': "← Back",
  'avvio.azienda-es': "e.g. Ferri Workshop",
  'avvio.sottotitolo': "Ten questions and your business software is ready, tailored to your work. You can change everything later.",
  'avvio.nome-attivita': "What's your business called?",
  'avvio.d-settore': "What do you do?",
  'avvio.a-settore': "Pick the closest one. You can change everything later.",
  'avvio.o-settore-negozio': "Shop and store",
  'avvio.sd-negozio': "I sell over the counter, with products and stock",
  'avvio.o-settore-ristorante': "Restaurant and bar",
  'avvio.sd-ristorante': "Tables, orders, menus with allergens, bookings",
  'avvio.o-settore-laboratorio': "Workshop and crafts",
  'avvio.sd-laboratorio': "Quotes, jobs in stages, materials",
  'avvio.o-settore-officina': "Repairs and servicing",
  'avvio.sd-officina': "Vehicles or appliances, jobs, spare parts, warranties",
  'avvio.o-settore-studio': "Practice and services",
  'avvio.sd-studio': "Calendar, client records, session packages",
  'avvio.o-settore-beauty': "Beauty and wellness",
  'avvio.sd-beauty': "Calendar per room, treatments, packages, products",
  'avvio.o-settore-palestra': "Gym and club",
  'avvio.sd-palestra': "Members, memberships and renewals, classes and attendance",
  'avvio.o-settore-professionista': "Freelancer and agency",
  'avvio.sd-professionista': "Clients, projects, hours, deadlines, quotes",
  'avvio.o-settore-noleggio': "Rentals",
  'avvio.sd-noleggio': "Items, availability, from/to contracts, deposits",
  'avvio.o-settore-altro': "Something else, start from scratch",
  'avvio.sd-altro': "Empty software: you create the sections",
  'avvio.d-offerta': "Do you sell products, services or both?",
  'avvio.o-offerta-prodotti': "Products",
  'avvio.o-offerta-servizi': "Services",
  'avvio.o-offerta-entrambi': "Both",
  'avvio.d-magazzino': "Do you keep stock?",
  'avvio.a-magazzino': "Stock levels, minimum stock, what to reorder.",
  'avvio.d-su_misura': "Do you do custom work, with quotes?",
  'avvio.a-su_misura': "Quotes with line items; when the customer accepts, the job opens.",
  'avvio.d-appuntamenti': "Do you take appointments or bookings?",
  'avvio.a-appuntamenti': "A calendar per person or per resource.",
  'avvio.d-fornitori': "Do you buy from suppliers?",
  'avvio.a-fornitori': "A supplier list and, if you keep stock, purchase orders that update it when goods arrive.",
  'avvio.d-fatture': "Do you issue invoices?",
  'avvio.a-fatture': "Numbered by year, with VAT, due dates and the e-invoice file.",
  'avvio.d-persone': "How many people will use Lumi?",
  'avvio.o-persone-solo': "Just me",
  'avvio.o-persone-poche': "2 to 5",
  'avvio.o-persone-molte': "More than 5",
  'avvio.d-squadra': "Who works with you?",
  'avvio.a-squadra': "Everyone signs in with their own email and sees what their role needs. You can also do this later.",
  'avvio.d-lumi': "Would you like Lumi, the assistant?",
  'avvio.a-lumi': "Just ask in plain words: \"how much did I sell this week?\", \"add a size to products\". Lumi suggests, you confirm.",
  'avvio.d-esempi': "Would you like to see the app with some sample data?",
  'avvio.a-esempi': "Fake but believable customers, sales and appointments, to try everything out. They're gone in one click.",
  'avvio.o-si': "Yes",
  'avvio.o-no': "No",
  'avvio.collaboratore': "Staff (views and edits, can't delete)",
  'avvio.lettura': "Read only",
  'avvio.nome': "Name",
  'avvio.ruolo': "Role",
  'avvio.togli': "Remove",
  'avvio.altra-persona': "+ Another person",
  'avvio.password-provvisoria': "Everyone gets a temporary password, which you'll see at the end.",
  'avvio.sezioni': "I'll set up these sections for you",
  'avvio.nessuna-sezione': "None: you start from scratch",
  'avvio.campi-spenti': { one: "{n} field you don't need stays off (turn it back on in {personalizza})", other: "{n} fields you don't need stay off (turn them back on in {personalizza})" },
  'avvio.persone-ruolo': { one: "One person with their role", other: "{n} people, each with their role" },
  'avvio.lumi-acceso': "Lumi on",
  'avvio.lumi-spento': "Lumi off (turn it on whenever you like)",
  'avvio.con-esempi': "With sample data, removable in one click",
  'avvio.senza-esempi': "No sample data",
  'avvio.ci-siamo': "Almost there",
  'avvio.chi-sei': "One last thing: who are you? You'll be the owner, the one who can do everything.",
  'avvio.preparo': "Setting up Lumi…",
  'avvio.prepara': "Set up Lumi",
  'avvio.pronto': "Lumi is ready",
  'avvio.consegna': "Give everyone their temporary password. You won't see this screen again: copy them now.",
  'avvio.entra': "Open Lumi",
  'avvio.tappa-sezioni': "Your sections",
  'avvio.tappa-sezioni-testo': "Everything is here{esempi}. Each section is a list you can search, filter, sort and view in columns.",
  'avvio.tappa-personalizza-testo': "Missing a field? Got one too many? From here you add, rename and move fields without ever losing data. New sections are created from \"{nuova}\".",
  'avvio.tappa-lumi-testo': "Ask in plain words: \"how much did I sell this week?\", \"add a size to products\". Lumi reads with your permissions and suggests; you decide.",
  'avvio.tappa-cruscotto': "The dashboard",
  'avvio.tappa-cruscotto-testo': "The numbers that matter and what needs attention, updated as you work. Change it with \"{modifica}\" at the top.",
  'avvio.n-di': "{n} of {tot}",
  'avvio.salta': "Skip",
  'avvio.capito': "Got it",
  'avvio.promemoria': "You're looking at sample data",
  'avvio.toglili': "Remove them",
  'avvio.conferma-togli': "Remove all sample data? Anything you added yourself stays.",
  'avvio.tolte': { one: "{n} sample row removed", other: "{n} sample rows removed" },
  'avvio.aggiunte': { one: "{n} sample row added", other: "{n} sample rows added" },
  'avvio.togli-esempi': "Remove sample data",
  'avvio.rimetti-esempi': "Add sample data back",
  'avvio.pagina-titolo': "Sample data and guided tour",
  'avvio.ci-sono': { one: "There's {n} sample row, so you can try Lumi without worry. When you're ready, remove it: it goes (even if you've edited it), whatever you entered yourself stays and, where there's nothing of yours yet, numbering starts again from 1.", other: "There are {n} sample rows: fake customers, transactions and appointments, so you can try Lumi without worry. When you're ready, remove them: they all go (even the ones you've edited), whatever you entered yourself stays and, where there's nothing of yours yet, numbering starts again from 1." },
  'avvio.solo-titolare': "Only the owner can remove them.",
  'avvio.nessun-esempio': "There's no sample data.",
  'avvio.rivedere': "Want a refresher on where things are?",
  'avvio.rifai-giro': "Take the tour again",
  'avvio.lato': "Sample data and tour",
  'avvio.lato-sezione': "Getting started",
};
