export default {
  'comune.benvenuto': 'Welcome to Kubo',
  'comune.benvenuto-sotto': 'The business software you put together your way. Start from a template, then change whatever you like.',
  'comune.nome-azienda': 'Company name',
  'comune.tuo-nome': 'Your name',
  'comune.email': 'Email',
  'comune.password': 'Password',
  'comune.password-nuova': 'Password (at least 8 characters)',
  'comune.valuta': 'Currency',
  'comune.da-dove': 'Where do we start? (you can add more later)',
  'comune.codice-avvio': "Setup code (shown in the terminal or log where Kubo runs)",
  'comune.codice-avvio-es': "e.g. 3FA9C2D1",
  'comune.inizia': 'Get started',
  'comune.lingua': 'Language',
  'comune.accedi-per': 'Sign in to continue.',
  'comune.accedi': 'Sign in',
  'comune.gestione': 'Admin',
  'comune.nuova-sezione': 'New section',
  'comune.persone-permessi': 'People and permissions',
  'comune.esci': 'Sign out',
  'comune.personalizza': 'Customise',
  'comune.personalizza-sezione': 'Customise this section',
  'comune.nessuna-sezione': 'No sections yet.',
  'comune.creane-una': 'Create one',
  'comune.chiedi-titolare': 'Ask the owner to create one.',
  'comune.qualcosa-non-va': 'Something went wrong',
  'comune.errore-n': 'Error {stato}',
  'comune.percento': '{n}%',
  'comune.si': 'Yes',
  'comune.no': 'No',
  'comune.si-min': 'yes',
  'comune.no-min': 'no',
  'comune.su': 'Up',
  'comune.giu': 'Down',
  'comune.togli': 'Remove',
  'comune.cerca': 'Search…',
  'comune.carico': 'Loading…',
  'comune.avviso-esempi-aggiunti': "Sample data added",
  'comune.avviso-esempi-tolti': "Sample data removed",
};
