export default {
  'connettori.terzi': "A third-party connector is copied into the “connettori” folder next to the data: you switch it on here after checking its checksum.",
  'connettori.locale': "Installed by hand",
  'connettori.rotto': "The connector does not load: check its connettore.js file",
  'connettori.stato-acceso': "On",
  'connettori.stato-spento': "Off",
  'connettori.stato-incompleto': "To complete",
  'connettori.stato-cambiato': "Changed",
  'connettori.stato-rotto': "Broken",
  'connettori.mancano': "Still missing: {cosa}",
  'connettori.cambiato': "The connector file changed after it was switched on: it stays stopped until you switch it on again and check the checksum.",
  'connettori.accendi': "Switch on",
  'connettori.spegni': "Switch off",
  'connettori.accendi-titolo': "Switch on {nome}?",
  'connettori.potra': "It will be able to:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "read",
  'connettori.p-crea': "create",
  'connettori.p-modifica': "edit",
  'connettori.p-elimina': "delete",
  'connettori.somma': "Checksum (SHA-256) of the file: compare it with the one published by its author.",
  'connettori.da-approvare': "This connector's code has not run yet: Kubo loads it only after you confirm the checksum below. Then you will see the sections it can use.",
  'connettori.impostazioni': "Settings",
  'connettori.salvato-segreto': "Saved",
  'connettori.cambia': "Change",
  'connettori.togli': "Remove",
  'connettori.interni': "Allow internal network addresses (a server in the shop, a cash register)",
  'connettori.salva': "Save",
  'connettori.salvato': "Saved",
  'connettori.prova': "Test the connection",
  'connettori.provo': "Testing…",
  'connettori.prova-ok': "Connection works",
  'connettori.prova-no': "It does not work: {motivo}",
  'connettori.collegamento': "Connection",
  'connettori.webhook': "Webhook address",
  'connettori.webhook-aiuto': "Paste it into the service's webhook settings.",
  'connettori.indirizzo-segreto': "Secret address",
  'connettori.indirizzo-aiuto': "Anyone with this address sees the data: give it only to those who need it.",
  'connettori.account': "Account",
  'connettori.collegato': "Connected",
  'connettori.scollegato': "Not connected",
  'connettori.scade': "Expires {quando}",
  'connettori.collega': "Connect the account",
  'connettori.ricollega': "Reconnect",
  'connettori.oauth-ok': "Account connected",
  'connettori.oauth-scaduto': "The connection expired: try again",
  'connettori.oauth-errore': "The connection failed: check the log",
  'connettori.abbinamenti': "Field matching",
  'connettori.abbinamenti-aiuto': "The connector's fields and Kubo's: if you rename a field the match stays.",
  'connettori.sezione-manca': "The «{nome}» section is missing",
  'connettori.facoltativo': "optional",
  'connettori.salva-abbinamenti': "Save the matching",
  'connettori.sincronizzazioni': "Syncs",
  'connettori.ogni': "every {ogni}",
  'connettori.alle': "at {alle}",
  'connettori.ultimo': "Last run: {quando}",
  'connettori.prossimo': "next: {quando}",
  'connettori.sincronizza': "Sync now",
  'connettori.giro-ok': "Done",
  'connettori.coda': "Queued: {attesa} · failed: {fallite}",
  'connettori.riprova': "Retry the failed ones",
  'connettori.registro': "Log",
  'connettori.registro-vuoto': "Nothing yet: here you see what comes in and what goes out.",
  'connettori.col-quando': "When",
  'connettori.col-verso': "Direction",
  'connettori.col-esito': "Result",
  'connettori.col-cosa': "What",
  'connettori.verso-entrata': "incoming",
  'connettori.verso-uscita': "outgoing",
  'connettori.verso-giro': "scheduled run",
  'connettori.verso-azione': "action",
  'connettori.verso-prova': "test",
  'connettori.verso-oauth': "account",
  'connettori.verso-sistema': "system",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "error",
  'connettori.esito-avviso': "warning",
  'connettori.esito-ignorato': "ignored",
  'connettori.copia': "Copy",
  'connettori.copiato': "Copied",
  'connettori.annulla': "Cancel",
  'connettori.conferma': "Confirm",
  'connettori.fatto': "Done",
  // la libreria delle integrazioni e le ricette
  'connettori.libreria': "Integrations library",
  'connettori.libreria-sotto': "{n} integrations · {accese} on. Keys stay encrypted in Kubo and never go back to the browser.",
  'connettori.cerca': "Search: Stripe, invoice, WhatsApp, shipping…",
  'connettori.categorie': "Categories",
  'connettori.tutte': "All",
  'connettori.trovate': "{n} found",
  'connettori.le-tue': "Switched on",
  'connettori.nessuna': "No integration found.",
  'connettori.prova-http': "Not there? Connect it with HTTP / REST API",
  'connettori.smanettoni': "For tinkerers: Kubo's API is described in OpenAPI 3.1 at /api/openapi-3.1.json, and a new connector is a folder with one file (docs/CONNETTORI.md).",
  'connettori.f-gratis': "Free",
  'connettori.f-facili': "Easy",
  'connettori.f-italia': "Italy",
  'connettori.stato-da-approvare': "To approve",
  'connettori.cat-pagamenti': "Payments",
  'connettori.cat-cassa': "Till and POS",
  'connettori.cat-negozi-online': "Online shops",
  'connettori.cat-marketplace': "Marketplaces",
  'connettori.cat-fatturazione': "Invoicing",
  'connettori.cat-contabilita': "Accounting",
  'connettori.cat-banche': "Banks",
  'connettori.cat-spedizioni': "Shipping",
  'connettori.cat-whatsapp': "WhatsApp",
  'connettori.cat-messaggi': "Messaging",
  'connettori.cat-email': "Email",
  'connettori.cat-sms': "SMS",
  'connettori.cat-calendario': "Calendar",
  'connettori.cat-prenotazioni': "Bookings",
  'connettori.cat-archivio': "Storage and files",
  'connettori.cat-produttivita': "Productivity",
  'connettori.cat-marketing': "Marketing",
  'connettori.cat-recensioni': "Reviews",
  'connettori.cat-firma': "E-signature",
  'connettori.cat-dati-aziende': "Company data",
  'connettori.cat-automazione': "Automation",
  'connettori.cat-ia': "AI",
  'connettori.cat-altro': "Other",
  'connettori.costo-gratis': "Free",
  'connettori.costo-a-consumo': "Pay as you go",
  'connettori.costo-abbonamento': "Subscription",
  'connettori.costo-contratto': "Contract",
  'connettori.diff-facile': "Easy",
  'connettori.diff-media': "Medium",
  'connettori.diff-difficile': "For tinkerers",
  'connettori.zona-IT': "Italy",
  'connettori.zona-UE': "Europe",
  'connettori.zona-mondo': "Worldwide",
  'connettori.prova-finto': "Tested with a fake service",
  'connettori.prova-vero': "Tested with the real service",
  'connettori.prova-finto-aiuto': "The automatic tests use a fake service that answers like the real one, following the documentation in the sources: before relying on it, try it in test mode.",
  'connettori.prova-vero-aiuto': "This connector was also tested with the real service.",
  'connettori.sito': "Service website",
  'connettori.apri': "Open",
  'connettori.cosa-serve': "What you need",
  'connettori.passi': "Step by step",
  'connettori.costo': "Cost",
  'connettori.difficolta': "Difficulty",
  'connettori.fonti': "Sources ({n})",
  'connettori.permessi-titolo': "What it can touch",
  'connettori.nessun-permesso': "No Kubo section: only the calls you set up.",
  'connettori.r-nessuna': "No recipes yet. Add one:",
  'connettori.r-tipo-uscita': "Outgoing: when a row changes",
  'connettori.r-tipo-azione': "Button on the record and Lumi",
  'connettori.r-tipo-entrata': "Incoming: the service writes into Kubo",
  'connettori.r-nome': "Recipe name",
  'connettori.r-attiva': "Active",
  'connettori.r-sezione': "Section",
  'connettori.r-eventi': "When the row is",
  'connettori.ev-crea': "created",
  'connettori.ev-modifica': "changed",
  'connettori.ev-elimina': "deleted",
  'connettori.ev-ripristina': "restored",
  'connettori.r-metodo': "Method",
  'connettori.r-percorso': "Path (after the base address) or full address",
  'connettori.r-indirizzo': "Address the platform gives you (https://…)",
  'connettori.r-corpo': "Body (JSON with placeholders; empty = the whole row)",
  'connettori.r-segnaposto': "Placeholders: {campi}",
  'connettori.r-scrive': "Show a preview and ask for confirmation before sending",
  'connettori.r-modo': "If the row already exists",
  'connettori.modo-crea-o-aggiorna': "update it, otherwise create it",
  'connettori.modo-crea': "always create a new row",
  'connettori.modo-aggiorna': "only update",
  'connettori.r-chiave': "Key field (to find the row again)",
  'connettori.r-elenco': "List in the JSON (optional, e.g. items)",
  'connettori.r-idevento': "Event id in the JSON (optional, against duplicates)",
  'connettori.r-campi': "Field matches (empty = JSON keys with the same names as the fields)",
  'connettori.r-da': "Path in the JSON (e.g. customer.email)",
  'connettori.r-a': "Kubo field",
  'connettori.r-aggiungi-campo': "Add a match",
  'connettori.r-indirizzo-entrata': "Address to give the service (JSON POST)",
  'connettori.r-salva-prima': "Save and switch on to see the address.",
  'connettori.copia': "Connect another service like this",
  'connettori.copia-aiuto': "A second service with its own address, authentication and recipes.",
  'connettori.copia-nome': "Service name (e.g. CRM)",
  'connettori.copia-crea': "Create",
  'connettori.copia-di': "Copy of «{nome}»",
  'connettori.togli-copia': "Remove this service",
  'connettori.togli-copia-conferma': "Remove «{nome}» with its settings, secrets and log?",
  'connettori.tutte-lettura': "All sections (read only)",
  'connettori.tutte-sezioni': "All sections",
  'connettori.dispositivo': "Connect with a code",
  'connettori.dispositivo-titolo': "Connect {nome} with a code",
  'connettori.dispositivo-passi': "Open the address below (from your phone too), sign in to the service and type this code. Kubo checks by itself every few seconds: you can leave this window open.",
  'connettori.dispositivo-attesa': "Waiting for confirmation…",
  'connettori.dispositivo-scaduto': "The code expired or the window was closed: press «Connect with a code» again.",
  'connettori.dispositivo-chiudi': "Close",
  'connettori.ritorno': "Return address (register it in the service)",
  'connettori.pubblico-titolo': "Kubo's public address",
  'connettori.pubblico-aiuto': "The address services use to reach Kubo from the internet (e.g. https://kubo.shop.com). Webhook and return addresses of every connector use it; empty = the browser's.",
  'connettori.pubblico-salvato': "Address saved",
  'connettori.r-con-accesso': "Send the key or token even when the address is on another site",
};
