export default {
  'connettori.titolo': "Connectors",
  'connettori.spiega': "Connect Kubo to the services you already use: payments, online shop, e-invoicing, email, calendar. Keys stay encrypted in Kubo and never go back to the browser.",
  'connettori.terzi': "A third-party connector is copied into the “connettori” folder next to the data: you switch it on here after checking its checksum.",
  'connettori.ufficiale': "Official",
  'connettori.locale': "Installed by hand",
  'connettori.rotto': "The connector does not load: check its connettore.js file",
  'connettori.stato-acceso': "On",
  'connettori.stato-spento': "Off",
  'connettori.stato-incompleto': "To complete",
  'connettori.stato-cambiato': "Changed",
  'connettori.stato-rotto': "Broken",
  'connettori.mancano': "Still missing: {cosa}",
  'connettori.cambiato': "The connector file changed after it was switched on: it stays stopped until you switch it on again and check the checksum.",
  'connettori.accendi': "Switch on",
  'connettori.spegni': "Switch off",
  'connettori.accendi-titolo': "Switch on {nome}?",
  'connettori.potra': "It will be able to:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "read",
  'connettori.p-crea': "create",
  'connettori.p-modifica': "edit",
  'connettori.p-elimina': "delete",
  'connettori.somma': "Checksum (SHA-256) of the file: compare it with the one published by its author.",
  'connettori.da-approvare': "This connector's code has not run yet: Kubo loads it only after you confirm the checksum below. Then you will see the sections it can use.",
  'connettori.impostazioni': "Settings",
  'connettori.salvato-segreto': "Saved",
  'connettori.cambia': "Change",
  'connettori.togli': "Remove",
  'connettori.interni': "Allow internal network addresses (a server in the shop, a cash register)",
  'connettori.salva': "Save",
  'connettori.salvato': "Saved",
  'connettori.prova': "Test the connection",
  'connettori.provo': "Testing…",
  'connettori.prova-ok': "Connection works",
  'connettori.prova-no': "It does not work: {motivo}",
  'connettori.collegamento': "Connection",
  'connettori.webhook': "Webhook address",
  'connettori.webhook-aiuto': "Paste it into the service's webhook settings.",
  'connettori.indirizzo-segreto': "Secret address",
  'connettori.indirizzo-aiuto': "Anyone with this address sees the data: give it only to those who need it.",
  'connettori.account': "Account",
  'connettori.collegato': "Connected",
  'connettori.scollegato': "Not connected",
  'connettori.scade': "Expires {quando}",
  'connettori.collega': "Connect the account",
  'connettori.ricollega': "Reconnect",
  'connettori.oauth-ok': "Account connected",
  'connettori.oauth-scaduto': "The connection expired: try again",
  'connettori.oauth-errore': "The connection failed: check the log",
  'connettori.abbinamenti': "Field matching",
  'connettori.abbinamenti-aiuto': "The connector's fields and Kubo's: if you rename a field the match stays.",
  'connettori.sezione-manca': "The «{nome}» section is missing",
  'connettori.facoltativo': "optional",
  'connettori.salva-abbinamenti': "Save the matching",
  'connettori.sincronizzazioni': "Syncs",
  'connettori.ogni': "every {ogni}",
  'connettori.alle': "at {alle}",
  'connettori.ultimo': "Last run: {quando}",
  'connettori.prossimo': "next: {quando}",
  'connettori.sincronizza': "Sync now",
  'connettori.giro-ok': "Done",
  'connettori.coda': "Queued: {attesa} · failed: {fallite}",
  'connettori.riprova': "Retry the failed ones",
  'connettori.registro': "Log",
  'connettori.registro-vuoto': "Nothing yet: here you see what comes in and what goes out.",
  'connettori.col-quando': "When",
  'connettori.col-verso': "Direction",
  'connettori.col-esito': "Result",
  'connettori.col-cosa': "What",
  'connettori.verso-entrata': "incoming",
  'connettori.verso-uscita': "outgoing",
  'connettori.verso-giro': "scheduled run",
  'connettori.verso-azione': "action",
  'connettori.verso-prova': "test",
  'connettori.verso-oauth': "account",
  'connettori.verso-sistema': "system",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "error",
  'connettori.esito-avviso': "warning",
  'connettori.esito-ignorato': "ignored",
  'connettori.copia': "Copy",
  'connettori.copiato': "Copied",
  'connettori.annulla': "Cancel",
  'connettori.conferma': "Confirm",
  'connettori.fatto': "Done",
};
