// Area «desktop» (web/moduli/desktop.js): rete, backup e versioni nuove.
export default {
  'desktop.tipo-giornaliero': "Daily",
  'desktop.tipo-modifica': "Before a change",
  'desktop.tipo-manuale': "Manual",
  'desktop.tipo-sicurezza': "Before a restore",
  'desktop.tipo-caricato': "Uploaded",
  'desktop.qr': "QR code with the address",
  'desktop.rete-titolo': "Connect other devices",
  'desktop.lato-rete': "Connect devices",
  'desktop.un-momento': "One moment…",
  'desktop.copiato': "Copied",
  'desktop.copia-fallita': "Couldn't copy: select it by hand",
  'desktop.indirizzo': "Address",
  'desktop.altra-rete': "Or, on another office network",
  'desktop.copia-indirizzo': "Copy the address",
  'desktop.codice': "Code",
  'desktop.passo-telefono': "Phone or tablet:",
  'desktop.passo-telefono-testo': "point the camera at the code and tap the link.",
  'desktop.passo-computer': "Another computer:",
  'desktop.passo-computer-codice': "open the browser and type the address. With the Lumi app, choose “Connect to Lumi on the network” and type the code.",
  'desktop.passo-computer-indirizzo': "open the browser and type the address. With the Lumi app, choose “Connect to Lumi on the network” and type the address.",
  'desktop.solo-qui': "Right now Lumi only answers this computer.",
  'desktop.apri-rete': "To use it from other devices too, open the menu in the Lumi app’s top bar (or in the notification area) and turn on “Open to the local network”.",
  'desktop.da-terminale': "If you start it from a terminal:",
  'desktop.non-in-rete': "This computer doesn't seem to be on a network. Connect it to the office Wi-Fi or cable and reload the page.",
  'desktop.stessa-rete': "The other devices must be on the same network (the same Wi-Fi or the same cable). If they can't connect, check that this computer's firewall lets Lumi through.",
  'desktop.backup': "Backups",
  'desktop.fai-adesso': "Back up now",
  'desktop.copia-in-corso': "Copying…",
  'desktop.fatto': "Backup done",
  'desktop.ultimo': "Last backup",
  'desktop.nessuno-ancora': "None yet",
  'desktop.copie-tenute': "Copies kept",
  'desktop.in-tutto': "{peso} in total",
  'desktop.spiega-automatici': "Every day Lumi makes a copy of the database on its own, plus one before every change to the structure or every import. It keeps {giornalieri} daily, {settimanali} weekly and {mensili} monthly copies; the ones you make by hand stay until you delete them. Attachments go in the “allegati” folder, copying only the new ones.",
  'desktop.spiega-spenti': "Automatic backups are off (LUMI_BACKUP=0): remember to make them by hand or with your own tools.",
  'desktop.cartella-esempio': "For example {a} or {b}",
  'desktop.cartella-nuova': "From now on backups go there",
  'desktop.cartella-tornata': "Backups go back next to the data",
  'desktop.scegli-cartella': "Choose a folder…",
  'desktop.dove': "Where backups go",
  'desktop.in-memoria': "(in-memory database: no backups)",
  'desktop.nota-esterna': "A folder you chose. If the drive isn't connected, the day's copy goes next to the data and a warning shows up here.",
  'desktop.nota-accanto': "Next to the data, on this computer. Better to keep a second copy elsewhere: an external drive, or a synced folder (Dropbox, OneDrive, iCloud, Google Drive).",
  'desktop.usa-cartella': "Use this folder",
  'desktop.torna-accanto': "Back next to the data",
  'desktop.vuoto': "No backups yet. The first one arrives on its own within a few minutes, or make it now.",
  'desktop.col-quando': "When",
  'desktop.col-tipo': "Type",
  'desktop.col-dimensione': "Size",
  'desktop.accanto-ai-dati': "next to the data",
  'desktop.scarica': "Download",
  'desktop.ripristina': "Restore",
  'desktop.elimina': "Delete this backup",
  'desktop.elimina-conferma': "Delete the backup from {quando}? It can no longer be restored.",
  'desktop.eliminato': "Backup deleted",
  'desktop.ripristino-titolo': "Go back to this backup?",
  'desktop.ripristino-prima': "Everything will go back to how it was on",
  'desktop.ripristino-dopo': ". Anything done after that disappears from view.",
  'desktop.ripristino-nota': "First Lumi makes a copy of how things are now (“{tipo}”): if you change your mind, restore that one and you lose nothing. Anyone working on other devices will see the page reload.",
  'desktop.capito': "I understand, I want to go back to that moment",
  'desktop.annulla': "Cancel",
  'desktop.ripristino-in-corso': "Restoring…",
  'desktop.ripristinato': "Restored",
  'desktop.ripristinato-altro': "The owner restored a backup: reloading…",
  'desktop.caricato': "Backup uploaded: {azienda}, {persone}, {sezioni}. You'll find it at the top of the list.",
  'desktop.persone': {"one": "{n} person", "other": "{n} people"},
  'desktop.sezioni': {"one": "{n} section", "other": "{n} sections"},
  'desktop.carica': "Upload a backup",
  'desktop.carica-nota': "A .db file downloaded from here, even from another computer. Lumi checks it and adds it to the list: then you decide whether to restore it.",
  'desktop.scegli-file': "Choose the file…",
  'desktop.uscita-versione': "New version available:",
  'desktop.novita': "what's new",
  'desktop.aggiornato': "You're on the latest version.",
  'desktop.versioni': "New versions",
  'desktop.stai-usando': "You're using Lumi",
  'desktop.controlla-ogni-giorno': "Check every day for a new version and let me know",
  'desktop.versioni-nota': "Lumi only asks GitHub for the number of the latest published version: it sends no company data and installs nothing on its own. You update when you want, after a backup.",
  'desktop.controlla-adesso': "Check now",
  'desktop.avviso-versione': "New Lumi version:",
  'desktop.dettagli': "Details",
  'desktop.chiudi': "Close",
  'desktop.solo-titolare': "Backups are managed by the owner.",
};
