// E-invoices (web/moduli/fatture.js): received invoices, virtual stamp duty, numbering.
export default {
  'fatture.aggiorna-chiedi': "Lumi's invoices have grown: prices up to 8 decimals, pension fund, Public Administration, received invoices. Add the new fields now? No data is lost.",
  'fatture.aggiornato': "Invoices updated",
  'fatture.bloccata': "Issued · locked",
  'fatture.bloccata-nota': "An issued invoice can no longer be changed: correct it with a credit or debit note. You can change the payment status and the internal notes.",
  'fatture.bollo': "Virtual stamp duty",
  'fatture.bollo-nota': "Stamp duty is paid with the F24 form (tax codes 2521-2524) or from the Revenue Agency's reserved area, which works out the amount every quarter. Issued invoices with stamp duty ticked count.",
  'fatture.chiudi': "Close",
  'fatture.codice-tributo': "Tax code",
  'fatture.crea-integrazione': "Create integration",
  'fatture.da-integrare': "To integrate",
  'fatture.da-pagare': "To pay",
  'fatture.da-versare': "To pay over",
  'fatture.emesse': "Issued",
  'fatture.entro': "By",
  'fatture.fatture-con-bollo': "Invoices with stamp duty",
  'fatture.fornitore-nuovo': "new",
  'fatture.gia-importata': "{numero} was already there",
  'fatture.importa': "Import invoices",
  'fatture.importata': "{numero} of {data} · {totale}",
  'fatture.integra-conferma': "Create the integration (or self-billed invoice) for invoice {numero}? It starts as a draft: you check it and issue it.",
  'fatture.integra-nota': "Received invoice under reverse charge or from a foreign supplier: it needs a TD16-TD19 integration.",
  'fatture.integrazione-creata': "{tipo} integration created as a draft",
  'fatture.intestata-ad-altri': "is not addressed to your VAT number",
  'fatture.leggo': "Reading…",
  'fatture.manca-modello': "Add the “Invoices and e-invoicing” template first.",
  'fatture.mancano': "Missing numbers",
  'fatture.nessun-buco': "no gaps",
  'fatture.nessuna-emessa': "No invoices issued this year.",
  'fatture.niente-da-integrare': "Nothing to integrate.",
  'fatture.niente-da-pagare': "Nothing to pay.",
  'fatture.numerazione': "Numbering",
  'fatture.numerazione-nota': "Numbers run in order by series and year, with no gaps. A gap usually comes from an invoice entered by hand: check before issuing the next one.",
  'fatture.ricevute': "Received",
  'fatture.ricevute-nota': "Download invoices from the tax drawer or your PEC and drop them here: signed .p7m files and files with several invoices too. Lumi creates the supplier and records the cost and due date.",
  'fatture.serie': "Series",
  'fatture.serie-principale': "main",
  'fatture.solo-xml': "Only .xml or .p7m files",
  'fatture.stampa': "Print",
  'fatture.titolo': "E-invoices",
  'fatture.totale': "Total",
  'fatture.trascina': "Drop received invoices here",
  'fatture.trascina-nota': "or tap to choose files (.xml, .xml.p7m)",
  'fatture.trimestre': "Quarter",
  'fatture.trimestre-n': "Q{n}",
  'fatture.troppo-grande': "File too large (3.5 MB at most)",
  'fatture.tutte-le-ricevute': "All received invoices →",
  'fatture.ultimo': "Last",
  'fatture.vedi': "View invoice",
  'fatture.vista': "Received invoice",
};
