// Taxes (web/moduli/fisco.js).
export default {
  'fisco.titolo': "Taxes",
  'fisco.anno': "Year",
  'fisco.responsabilita': "Kubo calculates and prepares from your data: check before paying or filing. The responsibility stays with the taxpayer.",
  'fisco.scheda-riepilogo': "To pay",
  'fisco.scheda-iva': "VAT",
  'fisco.scheda-forfettario': "Flat-rate",
  'fisco.scheda-f24': "F24",
  'fisco.scheda-ritenute': "Withholding",
  'fisco.scheda-scadenze': "Deadlines",
  'fisco.scheda-commercialista': "For the accountant",
  'fisco.scheda-impostazioni': "Settings",
  'fisco.da-pagare-anno': "Still to pay this year",
  'fisco.prossimo': "Next payment",
  'fisco.niente': "Nothing coming up.",
  'fisco.regime': "Tax scheme",
  'fisco.coeff': "coefficient {n}%",
  'fisco.regime-forfettario': "Flat-rate (forfettario)",
  'fisco.regime-semplificato': "Simplified",
  'fisco.regime-ordinario': "Ordinary",
  'fisco.periodicita-trimestrale': "Quarterly VAT",
  'fisco.periodicita-mensile': "Monthly VAT",
  'fisco.manca-ricevute': "For VAT on purchases and withholding, add the “Received invoices” section.",
  'fisco.apri-impostazioni': "Open settings",
  'fisco.prossimi-versamenti': "Upcoming payments",
  'fisco.data': "Date",
  'fisco.cosa': "What",
  'fisco.codice': "Code",
  'fisco.anno-rif': "Ref. year",
  'fisco.importo': "Amount",
  'fisco.vedi-f24': "F24",
  'fisco.prossime-scadenze': "Upcoming deadlines",
  'fisco.mese-n': "Month {n}",
  'fisco.trimestre-n': "Q{n}",
  'fisco.lipe-trimestre': "LIPE Q{n}",
  'fisco.liquidazioni': "Periodic VAT settlements",
  'fisco.periodo': "Period",
  'fisco.iva-vendite': "VAT on sales",
  'fisco.iva-acquisti': "Deductible VAT",
  'fisco.riporti': "Carried over",
  'fisco.interessi': "1% interest",
  'fisco.da-versare': "To pay",
  'fisco.scadenza': "Due",
  'fisco.a-credito': "credit {importo}",
  'fisco.riportato': "carried over (up to €100)",
  'fisco.acconto-dicembre': "December VAT advance",
  'fisco.acconto-dovuto': "Advance of {importo} with the {metodo} method: code {codice}, by {data}.",
  'fisco.acconto-no': "No advance due (under €103.29 or data missing: add it in the settings).",
  'fisco.acconto-nota': "Historical: 88% of what you paid for last year's final period. Forecast: 88% of what you expect for this year's final period. Kubo picks the lower one.",
  'fisco.metodo-storico': "historical",
  'fisco.metodo-previsionale': "forecast",
  'fisco.lipe': "Periodic VAT settlement return (LIPE)",
  'fisco.lipe-passo-1': "Download the quarter's XML file above.",
  'fisco.lipe-passo-2': "Sign in to “Fatture e Corrispettivi” on the Agenzia delle Entrate website with SPID, CIE or CNS.",
  'fisco.lipe-passo-3': "Go to “Comunicazioni” → “Liquidazioni periodiche IVA” → “Invio file”.",
  'fisco.lipe-passo-4': "Upload the file and confirm: the system checks it right away.",
  'fisco.lipe-passo-5': "Download the receipt after a few minutes and keep it.",
  'fisco.lipe-nota': "Deadlines: 31 May, 30 September, 30 November and end of February. If something doesn't match, the Agency's pre-filled return helps you compare.",
  'fisco.registri': "VAT registers",
  'fisco.registri-nota': "The sales, purchase and daily-takings registers are in the accountant package, as CSV and Excel.",
  'fisco.debito-prec': "prev. debt {importo}",
  'fisco.credito-prec': "prev. credit {importo}",
  'fisco.credito-anno': "last year's credit {importo}",
  'fisco.meno-acconto': "advance {importo}",
  'fisco.non-forfettario': "The company is not under the flat-rate scheme: change it in the settings.",
  'fisco.sim-quanto': "If I collect another (€)",
  'fisco.sim-esito': "Collecting another {piu}, you pay about {tasse} more in tax and contributions: you keep {resta}.",
  'fisco.niente-acconti': "No advance due.",
  'fisco.incassato': "Collected",
  'fisco.incassato-nota': "invoices with “Paid on” this year",
  'fisco.reddito': "Income",
  'fisco.contributi': "INPS contributions",
  'fisco.imposta': "Substitute tax",
  'fisco.aliquota-n': "rate {n}%",
  'fisco.soglia': "€85,000 threshold",
  'fisco.soglia-nota': "You have used {usato}% of the threshold: {margine} left. Above €100,000 you leave the scheme immediately.",
  'fisco.simulazione': "Simulation",
  'fisco.simula': "Calculate",
  'fisco.acconti-anno': "Advances {anno}",
  'fisco.acconti-base': "Based on the previous year's tax: {importo}.",
  'fisco.saldo-stima': "Estimated balance to pay next year: {importo}.",
  'fisco.gestione-artigiani': "INPS craftsmen",
  'fisco.gestione-commercianti': "INPS traders",
  'fisco.gestione-separata': "Separate scheme (gestione separata)",
  'fisco.gestione-cassa': "Professional fund",
  'fisco.gestione-nessuna': "None",
  'fisco.stampa-f24': "Print F24",
  'fisco.stampa': "Print or save PDF",
  'fisco.chiudi': "Close",
  'fisco.f24-del': "F24 of {data}",
  'fisco.sezione': "Section",
  'fisco.rateazione': "Instalment / period",
  'fisco.sezione-erario': "Treasury",
  'fisco.sezione-inps': "INPS",
  'fisco.sezione-locali': "Local taxes",
  'fisco.f24-come': "Copy the lines into F24 web (Agenzia delle Entrate) or your home banking. If you offset a credit, or the balance is zero, you must use the Agency's services.",
  'fisco.registro-ritenute': "Withholding applied",
  'fisco.pagata-il': "Paid on",
  'fisco.percipiente': "Payee",
  'fisco.compenso': "Fee",
  'fisco.ritenuta': "Withholding",
  'fisco.versare-entro': "Pay by",
  'fisco.ritenute-vuoto': "No withholding: record it on the invoices received from professionals (withholding and payment date).",
  'fisco.riepilogo-cu': "Summary for the CU and the 770",
  'fisco.cf': "Tax code",
  'fisco.causale': "Reason code",
  'fisco.cu-nota': "This is the data to report: the CU goes to payees by 16 March and to the Agency; the 770 by 31 October. Kubo does not file them.",
  'fisco.scadenze-anno': "Deadlines {anno}",
  'fisco.scadenze-nota': "Only the deadlines for your scheme. Dates falling on a Saturday or holiday are already moved to the next working day.",
  'fisco.dal': "From",
  'fisco.al': "To",
  'fisco.scarica-pacchetto': "Download the zip",
  'fisco.pacchetto': "Package for the accountant",
  'fisco.pacchetto-cosa': "A zip with XML copies of the issued invoices, VAT registers, settlements, cash book and withholding as CSV and Excel, and a PDF summary.",
  'fisco.quando-professionista': "When you really need a professional",
  'fisco.pro-dichiarazioni': "You can file returns (income, annual VAT, 770) yourself with SPID; to have someone else file them you need an authorised intermediary.",
  'fisco.pro-visto': "To offset a VAT credit over €5,000 in the F24 you need a professional's compliance stamp (visto di conformità).",
  'fisco.pro-consulenza': "Choosing the scheme, the 35% INPS reduction, instalments, audits and notices: that is advice, ask an accountant.",
  'fisco.pro-redditi': "IRPEF, IRES and IRAP under the ordinary or simplified scheme are calculated by the accountant or the pre-filled return, not by Kubo.",
  'fisco.salva': "Save",
  'fisco.salvate': "Settings saved",
  'fisco.sezioni': "Sections for taxes",
  'fisco.sezioni-cosa': "Adds “Received invoices” (purchases and withholding) and, if you sell over the counter, “Daily takings”.",
  'fisco.anche-corrispettivi': "Daily takings too",
  'fisco.aggiungi-sezioni': "Add the sections",
  'fisco.sezioni-aggiunte': "Sections added",
  'fisco.manca-piva': "The company's VAT number or tax code is missing.",
  'fisco.apri-documenti': "Add them in Documents",
  'fisco.gruppo-regime': "Scheme and business",
  'fisco.gruppo-inps': "INPS contributions",
  'fisco.gruppo-forfettario': "Flat-rate",
  'fisco.gruppo-iva': "VAT",
  'fisco.gruppo-altro': "Other",
  'fisco.promemoria': "Taxes: {cosa} on {data}",
  'fisco.imp-regime': "Tax scheme",
  'fisco.impn-regime': "If you don't know, ask your accountant: this choice changes everything.",
  'fisco.imp-periodicita': "VAT settlement",
  'fisco.impn-periodicita': "Quarterly with 1% interest, if your turnover allows it.",
  'fisco.imp-ateco': "ATECO code",
  'fisco.impn-ateco': "You find it on your VAT number certificate.",
  'fisco.imp-coefficiente': "Profitability coefficient %",
  'fisco.impn-coefficiente': "Empty: the one from the official table for your ATECO.",
  'fisco.imp-gestione': "Pension scheme",
  'fisco.impn-gestione': "Kubo does not calculate contributions for professional funds.",
  'fisco.imp-riduzione35': "35% contribution reduction",
  'fisco.impn-riduzione35': "Only flat-rate craftsmen and traders who requested it from INPS.",
  'fisco.imp-aliquotaridotta': "5% rate (first five years)",
  'fisco.impn-aliquotaridotta': "For new businesses that meet the legal requirements; otherwise 15%.",
  'fisco.imp-impostaannoprecedente': "Last year's substitute tax (€)",
  'fisco.impn-impostaannoprecedente': "Basis for the advances. Empty: Kubo calculates it from the data.",
  'fisco.imp-accontiversatiannoprecedente': "Advances paid last year (€)",
  'fisco.impn-accontiversatiannoprecedente': "To calculate the June balance.",
  'fisco.imp-contributiversati': "Contributions paid this year (€)",
  'fisco.impn-contributiversati': "They are deducted from income. Empty: the estimate is used.",
  'fisco.imp-sedeinps': "INPS office code",
  'fisco.impn-sedeinps': "For the INPS section of the F24.",
  'fisco.imp-matricolainps': "INPS registration number",
  'fisco.impn-matricolainps': "In the separate scheme it is your tax code.",
  'fisco.imp-creditoannoprecedente': "Last year's VAT credit (€)",
  'fisco.impn-creditoannoprecedente': "Used in the settlements while it lasts.",
  'fisco.imp-accontoivastorico': "Paid for last year's final period (€)",
  'fisco.impn-accontoivastorico': "For the advance with the historical method.",
  'fisco.imp-accontoivaprevisto': "Expected for this year's final period (€)",
  'fisco.impn-accontoivaprevisto': "For the forecast method. Empty: Kubo's estimate.",
  'fisco.imp-camerale': "Annual chamber of commerce fee (€)",
  'fisco.impn-camerale': "Your Chamber of Commerce tells you the amount.",
  'fisco.imp-provinciacciaa': "Chamber of Commerce province",
  'fisco.impn-provinciacciaa': "Code, for example MI.",
  'fisco.imp-bollo': "Virtual stamp duty on invoices",
  'fisco.impn-bollo': "Always on under the flat-rate scheme.",
  'fisco.imp-sostituto': "I am a withholding agent",
  'fisco.impn-sostituto': "You pay professionals and withhold tax.",
  'fisco.v-iva': "VAT for period {periodo}",
  'fisco.v-iva-saldo': "Annual VAT balance",
  'fisco.v-iva-acconto': "VAT advance",
  'fisco.v-forf-saldo': "Substitute tax balance {anno}",
  'fisco.v-forf-acconto': "Substitute tax advance {anno}",
  'fisco.v-inps-acconto': "INPS contributions advance {anno}",
  'fisco.v-inps-fissi': "Fixed INPS contributions",
  'fisco.v-bollo': "Virtual stamp duty, Q{periodo}",
  'fisco.v-ritenute': "Withholding for month {periodo}",
  'fisco.v-camerale': "Chamber of commerce fee {anno}",
  'fisco.sc-iva-mese': "VAT payment for month {periodo}",
  'fisco.sc-iva-trimestre': "VAT payment for Q{periodo}",
  'fisco.sc-iva-saldo': "Annual VAT balance",
  'fisco.sc-iva-acconto': "VAT advance",
  'fisco.sc-lipe': "LIPE for Q{periodo}",
  'fisco.sc-dichiarazione-iva': "VAT return {anno}",
  'fisco.sc-forf-saldo-acconto': "Substitute tax balance and first advance",
  'fisco.sc-redditi-saldo-acconto': "Income tax balance and first advance",
  'fisco.sc-forf-acconto2': "Substitute tax second advance",
  'fisco.sc-redditi-acconto2': "Income tax second advance",
  'fisco.sc-dichiarazione-redditi': "Income tax return {anno}",
  'fisco.sc-inps-fissi': "Fixed INPS contributions, instalment {periodo}",
  'fisco.sc-inps-saldo-acconto': "INPS contributions: balance and advance",
  'fisco.sc-inps-riduzione': "Request for the 35% INPS reduction",
  'fisco.sc-bollo': "Virtual stamp duty, Q{periodo} {anno}",
  'fisco.sc-ritenute': "Withholding for month {periodo}",
  'fisco.sc-cu-consegna': "CU to payees",
  'fisco.sc-cu-invio': "CU to the Agency (self-employment)",
  'fisco.sc-modello-770': "770 return",
  'fisco.sc-camerale': "Chamber of commerce fee",
  'fisco.av-vicino-85': "You are close to the €85,000 threshold: if you exceed it, you leave the flat-rate scheme next year.",
  'fisco.av-oltre-85': "You exceeded €85,000: you leave the flat-rate scheme next year. Talk to an accountant.",
  'fisco.av-oltre-100': "You exceeded €100,000: you leave the flat-rate scheme immediately, with VAT from the transaction that crossed the threshold. You need an accountant.",
  'fisco.av-fuori-dal-regime': "Last year you collected more than €85,000: this year you could not be under the flat-rate scheme. Check with an accountant.",
  'fisco.av-contributi-stimati': "Deducted contributions are estimated: enter the ones actually paid this year in the settings.",
  'fisco.av-cassa-professionale': "With a professional fund the fund calculates contributions: Kubo does not count them.",
  'fisco.av-incassi-senza-data': "Some paid invoices have no “Paid on”: they count at the invoice date.",
  'fisco.av-visto-conformita': "The VAT credit is over €5,000: to offset it in the F24 you need the compliance stamp.",
  'fisco.av-forfettario-niente-iva': "Under the flat-rate scheme there is no VAT to settle and no LIPE: see the flat-rate dashboard.",
  'fisco.av-redditi-professionista': "IRPEF, IRES and IRAP are not here: the accountant or the pre-filled return calculates them.",
  'fisco.av-inps-cassetto': "Fixed INPS instalments are an estimate: the official F24 is in the Cassetto previdenziale.",
  'fisco.av-cu-intermediario': "With 20 or more CUs your own credentials are not enough: you need Entratel or an intermediary.",
  'fisco.av-cu-fisconline': "With fewer than 20 CUs you can file them yourself with your credentials.",
};
