export default {
  'gestione.tipo-testo': 'Text',
  'gestione.tipo-testo_lungo': 'Long text',
  'gestione.tipo-numero': 'Number',
  'gestione.tipo-valuta': 'Amount ({simbolo})',
  'gestione.tipo-percentuale': 'Percentage',
  'gestione.tipo-data': 'Date',
  'gestione.tipo-data_ora': 'Date and time',
  'gestione.tipo-si_no': 'Yes / No',
  'gestione.tipo-scelta': 'Choice',
  'gestione.tipo-scelta_multipla': 'Multiple choice',
  'gestione.tipo-stato': 'Status (workflow)',
  'gestione.tipo-relazione': 'Link',
  'gestione.tipo-righe': 'Lines (sub-table)',
  'gestione.tipo-calcolato': 'Calculated (formula)',
  'gestione.tipo-contatore': 'Numbering',
  'gestione.tipo-email': 'Email',
  'gestione.tipo-telefono': 'Phone',
  'gestione.tipo-url': 'Website',
  'gestione.tipo-indirizzo': 'Address',
  'gestione.tipo-codice_a_barre': 'Barcode',
  'gestione.tipo-durata': 'Duration (minutes)',
  'gestione.tipo-immagine': 'Image',
  'gestione.tipo-file': 'File',
  'gestione.nome': 'Name',
  'gestione.esempio-sezione': 'e.g. Rentals',
  'gestione.archivia-campo': 'Archive the field (values are kept)',
  'gestione.obbligatorio': 'Required',
  'gestione.senza-doppioni': 'No duplicates',
  'gestione.prima-opzione': 'First option',
  'gestione.opzioni': 'Options, one per line (colours: {colori})',
  'gestione.righe-di': 'Lines of',
  'gestione.collegato-a': 'Linked to',
  'gestione.piu-di-uno': 'More than one',
  'gestione.campo-punta': 'Field pointing here (in the other entity)',
  'gestione.formula': 'Formula (e.g. quantity * price · SUM(lines.total) · IF(stock <= threshold, "yes", "no"))',
  'gestione.mostra-come': 'Show as',
  'gestione.automatico': 'Automatic',
  'gestione.importo': 'Amount',
  'gestione.formato-contatore': 'Format ({AAAA} year, {N:4} 4-digit number)',
  'gestione.salva-modifiche': 'Save changes',
  'gestione.dai-nome': 'Give it a name',
  'gestione.piu-campo': '+ Field',
  'gestione.personalizza-nome': 'Customise · {nome}',
  'gestione.icona': 'Icon',
  'gestione.nome-elemento': 'Name of each item',
  'gestione.nota-dati': 'Renaming and moving never touch the data. A removed field is archived with its values and can be restored. If a type change would lose values, saving stops and tells you which.',
  'gestione.password-8': 'Password (8+)',
  'gestione.aggiungi': 'Add',
  'gestione.aggiunto': 'Added',
  'gestione.ruolo-cambiato': 'Role changed',
  'gestione.disattiva': 'Deactivate',
  'gestione.riattiva': 'Reactivate',
  'gestione.ruolo': 'Role',
  'gestione.nuova-persona': 'New person',
  'gestione.ruoli': 'Roles',
  'gestione.nota-ruoli': 'The owner can do everything. For the other roles, choose what they can do, section by section.',
  'gestione.nuovo-ruolo': '+ New role',
  'gestione.nome-ruolo': 'Role name (e.g. Counter, Workshop)',
  'gestione.vede': 'View',
  'gestione.modifica': 'Edit',
  'gestione.campi-nascosti-ruolo': 'Fields hidden from this role',
  'gestione.salva-ruolo': 'Save role',
  'gestione.ruolo-salvato': 'Role saved',
  'gestione.puo-personalizzare': 'Can customise',
  'gestione.sezione': 'Section',
  'gestione.campi-nascosti': 'Hidden fields (⌘/Ctrl to pick more than one)',
  'gestione.ruolo-titolare': 'Owner',
  'gestione.ruolo-collaboratore': 'Staff',
  'gestione.ruolo-lettura': 'Read only',
  'gestione.lingua-valuta': 'Language and currency',
  'gestione.tua-lingua': 'Your language',
  'gestione.tua-lingua-nota': 'Applies only to you, on every device.',
  'gestione.azienda': 'For the whole company',
  'gestione.lingua-modelli': 'Language for new templates',
  'gestione.lingua-modelli-nota': 'Templates you add from now on come with names in this language. Existing sections don\'t change.',
  'gestione.valuta-nota': 'Amounts are shown in this currency. Saved values don\'t change: only the symbol and format do.',
  'gestione.esempio': 'Looks like: {numero} · {soldi} · {data}',
  'gestione.salvato-ricarico': 'Saved: reloading the page',
  'gestione.settimana-da': 'The week starts on {giorno}.',
};
