// Stock (web/moduli/magazzino.js): value, stocktake, movements.
export default {
  'magazzino.titolo': "Stock",
  'magazzino.scheda-valore': "Value",
  'magazzino.scheda-inventario': "Stocktake",
  'magazzino.scheda-movimenti': "Movements",
  'magazzino.sezione': "Stock section",
  'magazzino.nessuna-sezione': "No section with stock levels: add the «giacenza» field to your items.",
  'magazzino.valore': "Value",
  'magazzino.al-costo': "at item cost",
  'magazzino.pezzi': "Pieces",
  'magazzino.articoli-n': {"one": "{n} item", "other": "{n} items"},
  'magazzino.sotto-scorta': "Below minimum",
  'magazzino.negativi': {"one": "{n} item with negative stock: {nomi}", "other": "{n} items with negative stock: {nomi}"},
  'magazzino.senza-costo': {"one": "{n} item in stock has no cost: it's left out of the value.", "other": "{n} items in stock have no cost: they're left out of the value."},
  'magazzino.per-categoria': "By category",
  'magazzino.categoria': "Category",
  'magazzino.articoli': "Items",
  'magazzino.senza-categoria': "No category",
  'magazzino.per-articolo': "By item",
  'magazzino.codice': "Code",
  'magazzino.articolo': "Item",
  'magazzino.giacenza': "Stock",
  'magazzino.costo': "Cost",
  'magazzino.scarica-csv': "Download CSV",
  'magazzino.nota-valore': "Value is stock × cost. Purchasing keeps the cost at weighted average. It's the closing inventory figure for your accountant.",
  'magazzino.inventario-nota': "Count the goods on the shelves: current stock levels are kept as the reference, and on closing every counted item is corrected by the difference. Sales made while you count stay right.",
  'magazzino.continua': "Continue «{nome}»",
  'magazzino.nuovo-inventario': "Start a stocktake",
  'magazzino.inventari': "Stocktakes",
  'magazzino.nome': "Name",
  'magazzino.iniziato': "Started",
  'magazzino.contati': "Counted",
  'magazzino.stato': "Status",
  'magazzino.chiuso-il': "Closed on {data}",
  'magazzino.aperto': "Open",
  'magazzino.leggi-codice': "Scan a code (scanner or keyboard, then Enter)",
  'magazzino.letto': "{nome}: {n}",
  'magazzino.cerca': "Search item or code",
  'magazzino.attesa': "Expected",
  'magazzino.contata': "Counted",
  'magazzino.differenza': "Difference",
  'magazzino.chiudi-conferma': {"one": "Close the stocktake? {n} stock level will be corrected.", "other": "Close the stocktake? {n} stock levels will be corrected."},
  'magazzino.chiuso': {"one": "Stocktake closed: {n} adjustment, {importo}", "other": "Stocktake closed: {n} adjustments, {importo}"},
  'magazzino.differenze': "Differences",
  'magazzino.valore-differenze': "Value of differences",
  'magazzino.chiudi': "Close the stocktake",
  'magazzino.chiudi-nota': "Items not counted stay as they are.",
  'magazzino.quando': "When",
  'magazzino.movimento': "Movement",
  'magazzino.origine': "Source",
  'magazzino.chi': "Who",
  'magazzino.origine-iniziale': "Opening stock",
  'magazzino.origine-modifica': "Edit",
  'magazzino.origine-automazione': "Automatic (sales, orders, usage)",
  'magazzino.origine-inventario': "Stocktake",
  'magazzino.niente-movimenti': "No movements yet.",
  'magazzino.nota-movimenti': "Every stock change lands here by itself, wherever it comes from: records, sales, received orders, imports, stocktakes.",
};
