export default {
  'moduli.lumi-serve-chiave': "To answer I need the Claude key. I'll open **Admin → Lumi** for you: it takes a minute.",
  'moduli.lumi-serve-chiave-spento': "To answer I need the Claude key and to be switched back on. I'll open **Admin → Lumi** for you: it takes a minute.",
  'moduli.lumi-chiedi-titolare': "To answer I need the Claude key: ask the owner to add it in **Admin → Lumi**.",
  'moduli.lumi-spento': "Lumi is off: switch it back on in Admin → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi is almost ready: the Claude key is missing.",
  'moduli.lumi-apri': "Open",
  'moduli.lumi-settimana': "How's the week",
  'moduli.lumi-settimana-domanda': "How did this week go? Give me the main figures.",
  'moduli.lumi-accendi': "Turn on Lumi",
  'moduli.lumi-solo-titolare': "Lumi's settings belong to the owner.",
  'moduli.lumi-gia-salvata': "•••••••• (already saved)",
  'moduli.lumi-stato-spento': "Off",
  'moduli.lumi-stato-acceso': "On",
  'moduli.lumi-stato-manca': "Key missing",
  'moduli.lumi-fonte-ambiente': "The key comes from the server's ANTHROPIC_API_KEY variable.",
  'moduli.lumi-fonte-file': "Key saved on this computer.",
  'moduli.lumi-cos-e': "Lumi is Kubo's assistant. You talk or write to it from the pill at the top: it searches, counts, prepares records and reshapes the system. Every change waits for your “Confirm”, and everyone sees only what their permissions allow.",
  'moduli.lumi-chiave': "Claude key",
  'moduli.lumi-salva-chiave': "Save the key",
  'moduli.lumi-incolla': "Paste the key",
  'moduli.lumi-togliere': "Remove the key? Lumi will stop answering.",
  'moduli.lumi-dove-chiave': "Create it at console.anthropic.com, under API Keys. It stays on this computer, in a file next to the data that only Kubo reads, and never reaches the browsers.",
  'moduli.lumi-acceso': "Lumi on",
  'moduli.lumi-limite': "Questions per minute per person",
  'moduli.lumi-da-provare': "Things to try",
  'moduli.lumi-esempio-1': "How much did I sell this week?",
  'moduli.lumi-esempio-2': "What do I need to reorder?",
  'moduli.lumi-esempio-3': "Add a size to products with S, M, L and XL",
  'moduli.lumi-esempio-4': "Make me a rentals section with customer, tool, from, to and status",
  'moduli.lumi-esempio-5': "When a rental is marked returned, let me know",
  'moduli.lumi-modello': "Model: {modello}.",
  'moduli.lumi-voce-accesa': "Real-time voice on.",
  'moduli.lumi-voce-browser': "Voice: the browser's own, where available.",
};
