export default {
  'moduli.lumi-serve-chiave': "To answer I need the Claude key. I'll open **Admin → Lumi** for you: it takes a minute.",
  'moduli.lumi-serve-chiave-spento': "To answer I need the Claude key and to be switched back on. I'll open **Admin → Lumi** for you: it takes a minute.",
  'moduli.lumi-chiedi-titolare': "To answer I need the Claude key: ask the owner to add it in **Admin → Lumi**.",
  'moduli.lumi-spento': "Lumi is off: switch it back on in Admin → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi is almost ready: the Claude key is missing.",
  'moduli.lumi-apri': "Open",
  'moduli.lumi-settimana': "How's the week",
  'moduli.lumi-settimana-domanda': "How did this week go? Give me the main figures.",
  'moduli.lumi-accendi': "Turn on Lumi",
  'moduli.lumi-solo-titolare': "Lumi's settings belong to the owner.",
  'moduli.lumi-gia-salvata': "•••••••• (already saved)",
  'moduli.lumi-stato-spento': "Off",
  'moduli.lumi-stato-acceso': "On",
  'moduli.lumi-stato-manca': "Key missing",
  'moduli.lumi-fonte-ambiente': "The key comes from the server's ANTHROPIC_API_KEY variable.",
  'moduli.lumi-fonte-file': "Key saved on this computer.",
  'moduli.lumi-cos-e': "Lumi is Kubo's assistant. You talk or write to it from the pill at the top: it searches, counts, prepares records and reshapes the system. Every change waits for your “Confirm”, and everyone sees only what their permissions allow.",
  'moduli.lumi-chiave': "Claude key",
  'moduli.lumi-salva-chiave': "Save the key",
  'moduli.lumi-incolla': "Paste the key",
  'moduli.lumi-togliere': "Remove the key? Lumi will stop answering.",
  'moduli.lumi-dove-chiave': "Create it at console.anthropic.com, under API Keys. It stays on this computer, in a file next to the data that only Kubo reads, and never reaches the browsers.",
  'moduli.lumi-acceso': "Lumi on",
  'moduli.lumi-limite': "Questions per minute per person",
  'moduli.lumi-da-provare': "Things to try",
  'moduli.lumi-esempio-1': "How much did I sell this week?",
  'moduli.lumi-esempio-2': "What do I need to reorder?",
  'moduli.lumi-esempio-3': "Add a size to products with S, M, L and XL",
  'moduli.lumi-esempio-4': "Make me a rentals section with customer, tool, from, to and status",
  'moduli.lumi-esempio-5': "When a rental is marked returned, let me know",
  'moduli.lumi-modello': "Model: {modello}.",
  'moduli.lumi-voce-accesa': "Real-time voice on.",
  'moduli.lumi-voce-browser': "Voice: the browser's own, where available.",
  'moduli.ag-adesso': "just now",
  'moduli.ag-agenda': "Calendar",
  'moduli.ag-calendario': "Calendar view",
  'moduli.ag-cruscotto': "Dashboard",
  'moduli.ag-aggiungi-voce': "Add the item",
  'moduli.ag-altri': {"one": "+{n} more", "other": "+{n} more"},
  'moduli.ag-e-altri': {"one": "and one more", "other": "and {n} more"},
  'moduli.ag-aria-grafico': "{titolo}: chart",
  'moduli.ag-barre': "Bars",
  'moduli.ag-linea': "Line",
  'moduli.ag-buongiorno': "Good morning",
  'moduli.ag-buon-pomeriggio': "Good afternoon",
  'moduli.ag-buonasera': "Good evening",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Change",
  'moduli.ag-cambia-widget': "Change the widget",
  'moduli.ag-nuovo-widget': "New widget",
  'moduli.ag-campo': "Field",
  'moduli.ag-colonne-per': "Columns: {nome}",
  'moduli.ag-una-colonna': "One column",
  'moduli.ag-come-oggi': "same as yesterday",
  'moduli.ag-come-settimana': "same as last week",
  'moduli.ag-come-mese': "same as last month",
  'moduli.ag-come-anno': "same as last year",
  'moduli.ag-rispetto-oggi': "{diff} vs yesterday ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} vs last week ({prima})",
  'moduli.ag-rispetto-mese': "{diff} vs last month ({prima})",
  'moduli.ag-rispetto-anno': "{diff} vs last year ({prima})",
  'moduli.ag-data-rif': "Reference date",
  'moduli.ag-prima': "Previous",
  'moduli.ag-dopo': "Next",
  'moduli.ag-fatto': "Done",
  'moduli.ag-forma': "Style",
  'moduli.ag-ha-creato': "created",
  'moduli.ag-ha-modificato': "edited",
  'moduli.ag-ha-archiviato': "archived",
  'moduli.ag-ha-ripristinato': "restored",
  'moduli.ag-in-sezione': "in {nome}",
  'moduli.ag-un-elemento': "an item",
  'moduli.ag-lista': "List",
  'moduli.ag-torna-lista': "Back to the list",
  'moduli.ag-media': "Average of…",
  'moduli.ag-somma': "Sum of…",
  'moduli.ag-quanti': "How many",
  'moduli.ag-misura': "Measure",
  'moduli.ag-modifica': "Edit",
  'moduli.ag-nome-voce': "Item name",
  'moduli.ag-nuova-voce': "New item",
  'moduli.ag-un-filtro': "Add at least one filter to the item",
  'moduli.ag-non-disegno': "I can't draw this",
  'moduli.ag-oggi': "Today",
  'moduli.ag-per': "By",
  'moduli.ag-periodo': "Period",
  'moduli.ag-periodo-oggi': "Today",
  'moduli.ag-periodo-settimana': "This week",
  'moduli.ag-periodo-mese': "This month",
  'moduli.ag-periodo-anno': "This year",
  'moduli.ag-periodo-ultimi_7': "Last 7 days",
  'moduli.ag-periodo-ultimi_30': "Last 30 days",
  'moduli.ag-periodo-ultimi_84': "Last 12 weeks",
  'moduli.ag-periodo-ultimi_365': "Last year",
  'moduli.ag-periodo-sempre': "All time",
  'moduli.ag-piede-grafico': "{periodo} · {totale} in total",
  'moduli.ag-piu-aggiungi': "+ Add",
  'moduli.ag-quale-data': "Which date",
  'moduli.ag-senza-titolo': "Untitled",
  'moduli.ag-spostato': "Moved",
  'moduli.ag-tipo': "Type",
  'moduli.ag-titolo': "Title",
  'moduli.ag-titolo-widget': "Give the widget a title",
  'moduli.ag-tutti': "all",
  'moduli.ag-utente-non-attivo': "Inactive user",
  'moduli.ag-vedi-calendario': "See on the calendar",
  'moduli.ag-vedi-elenco': "See the list",
  'moduli.ag-vedi-giorno': "See the day",
  'moduli.ag-vista-giorno': "Day",
  'moduli.ag-vista-settimana': "Week",
  'moduli.ag-vista-mese': "Month",
  'moduli.ag-w-numero': "Number",
  'moduli.ag-w-grafico': "Chart",
  'moduli.ag-w-attenzione': "Needs attention",
  'moduli.ag-w-ultime': "Latest changes",
  'moduli.ag-def-incassato-oggi': "Takings today",
  'moduli.ag-def-incassato-mese': "Takings this month",
  'moduli.ag-def-vendite-oggi': "Sales today",
  'moduli.ag-def-incassi-30': "Takings over the last 30 days",
  'moduli.ag-def-appuntamenti-oggi': "Appointments today",
  'moduli.ag-def-appuntamenti-settimana': "Appointments per week",
  'moduli.ag-def-preventivi-attesa': "Quotes awaiting reply",
  'moduli.ag-def-commesse-aperte': "Open jobs",
  'moduli.ag-def-accettato-mese': "Accepted this month",
  'moduli.ag-def-preventivi-mese': "Accepted quotes per month",
  'moduli.ag-def-articoli-riordinare': "Products to reorder",
  'moduli.ag-def-materiali-riordinare': "Materials to reorder",
  'moduli.ag-def-ordini-ritardo': "Late orders",
  'moduli.ag-def-vendite-aperte': "Sales open for more than 2 days",
  'moduli.ag-def-commesse-ritardo': "Late jobs",
  'moduli.ag-def-preventivi-senza-risposta': "Quotes with no reply for 7 days",
  'moduli.ag-def-appuntamenti-chiudere': "Past appointments to close",
  'moduli.ag-def-pacchetti-scaduti': "Expired packages with sessions left",
  'moduli.ag-def-attenzione': "Needs attention",
  'moduli.ag-def-ultime': "Latest changes",
  'moduli.ag-def-nuovi-mese': "{nome}: new this month",
  'moduli.ag-tutto-ok': "✓ All good: nothing to sort out.",
  'moduli.ag-nessuna-modifica': "No changes yet.",
  'moduli.ag-es-titolo': "E.g. Takings today",
  'moduli.im-menu': "Import from a spreadsheet, or export the list with the current filters",
  'moduli.im-importa-da': "Import from Excel or CSV…",
  'moduli.im-esporta-xlsx': "Export to Excel (.xlsx)",
  'moduli.im-esporta-csv': "Export to CSV",
  'moduli.im-nuova-dal-foglio': "+ A new section from the sheet",
  'moduli.im-scegli-file': "Choose an Excel (.xlsx) or CSV file",
  'moduli.im-trascina': "or drag it here. The first row must have the column names.",
  'moduli.im-esporta-tutto': "Export everything",
  'moduli.im-backup': "Full backup",
  'moduli.im-backup-nota': "A zip with a copy of the database (taken consistently even while people are working) and the attachments. Keep it on an external drive or in your own cloud.",
  'moduli.im-scarica-backup': "Download the backup",
  'moduli.im-importa-esporta': "Import and export",
  'moduli.im-api': "API and integrations",
  'moduli.im-dati': "Data",
  'moduli.im-dove': "Where the rows go",
  'moduli.im-non-importare': "— don't import",
  'moduli.im-crea-campo': "+ Create the field “{nome}” ({tipo})",
  'moduli.im-non-controllare': "Don't check: every row is new",
  'moduli.im-stesso': "Same “{nome}”",
  'moduli.im-stesso-unico': "Same “{nome}” (no duplicates)",
  'moduli.im-aggiorna': "update the existing one",
  'moduli.im-salta': "leave it, skip the row",
  'moduli.im-controllo': "Checking…",
  'moduli.im-importo': "Importing…",
  'moduli.im-importato': "Imported",
  'moduli.im-prova': "Try without saving",
  'moduli.im-importa-n': {"one": "Import {n} row", "other": "Import {n} rows"},
  'moduli.im-righe-in': {"one": "{n} row in “{file}”", "other": "{n} rows in “{file}”"},
  'moduli.im-riga': "Row",
  'moduli.im-errore': "Error",
  'moduli.im-file-errori': "rows to fix.csv",
  'moduli.im-prova-esito': "Trial run: nothing was saved",
  'moduli.im-esito-create': {"one": "created", "other": "created"},
  'moduli.im-esito-aggiornate': {"one": "updated", "other": "updated"},
  'moduli.im-esito-saltate': {"one": "skipped", "other": "skipped"},
  'moduli.im-esito-errori': "with errors",
  'moduli.im-cosa-non-va': "What's wrong",
  'moduli.im-e-altre': {"one": "…and one more.", "other": "…and {n} more."},
  'moduli.im-scarica-errori': "Download the rows with errors (.csv)",
  'moduli.im-correggi': "Fix them in the file and import them again: with the duplicate check nothing gets duplicated.",
  'moduli.im-vai-a': "Go to {nome}",
  'moduli.im-abbina': "Match the columns to the fields of {nome}. The first rows:",
  'moduli.im-ogni-colonna': "Each column becomes a field: check names and types.",
  'moduli.im-nome-sezione': "Name of the new section",
  'moduli.im-gia-presenti': "Existing rows",
  'moduli.im-se-trovo': "if I find them:",
  'moduli.im-formati': "Numbers like “1,234.50”, “1.234,50” or “€12” are accepted, dates as day/month/year (“31/12/2026”), and “yes / no”. Empty cells don't delete anything.",
  'moduli.doc-campo-ragione_sociale': "Company name",
  'moduli.doc-campo-piva': "VAT number",
  'moduli.doc-campo-codice_fiscale': "Tax code",
  'moduli.doc-campo-regime': "Tax regime",
  'moduli.doc-campo-via': "Address (street and number)",
  'moduli.doc-campo-cap': "Postcode",
  'moduli.doc-campo-comune': "Town",
  'moduli.doc-campo-provincia': "Province (code)",
  'moduli.doc-campo-telefono': "Phone",
  'moduli.doc-campo-email': "Email",
  'moduli.doc-campo-pec': "PEC",
  'moduli.doc-campo-codice_destinatario': "Your recipient code",
  'moduli.doc-campo-iban': "IBAN",
  'moduli.doc-campo-banca': "Bank",
  'moduli.doc-campo-aliquota': "Default VAT %",
  'moduli.doc-campo-colore': "Document colour",
  'moduli.doc-chiudi': "Close (Esc)",
  'moduli.doc-anteprima': "Print preview",
  'moduli.doc-stampa-pdf': "Print or save as PDF",
  'moduli.doc-modifica-modello': "Edit the template",
  'moduli.doc-xml-manca': "Something is missing before the XML file",
  'moduli.doc-sistema': "Fix these points and try again:",
  'moduli.doc-apri-dati': "Open the company details",
  'moduli.doc-scaricato': "Downloaded {nome}: now upload it to your intermediary's portal or to Fatture e Corrispettivi",
  'moduli.doc-dati-azienda': "Company details",
  'moduli.doc-modelli-stampa': "Print templates",
  'moduli.doc-documenti': "Documents",
  'moduli.doc-dati-salvati': "Company details saved",
  'moduli.doc-logo': "Logo",
  'moduli.doc-nessun-logo': "No logo",
  'moduli.doc-logo-tipo': "The logo must be a PNG or a JPEG",
  'moduli.doc-logo-grande': "The logo is too large: 300 KB at most",
  'moduli.doc-logo-caricato': "Logo uploaded",
  'moduli.doc-carica-logo': "Upload the logo",
  'moduli.doc-logo-nota': "PNG or JPEG, 300 KB at most. It goes at the top of every document.",
  'moduli.doc-indirizzo-completo': "Full address",
  'moduli.doc-fattura-elettronica': "E-invoicing (Italy)",
  'moduli.doc-fatturapa-nota': "Kubo prepares the FatturaPA (XML) file. To send it to SDI, upload it to the Agenzia delle Entrate's Fatture e Corrispettivi portal or to your intermediary: the steps are in docs/DOCUMENTI.md.",
  'moduli.doc-nessuna-stampa': "No section with lines to print. Add a template (shop, workshop, invoices) or a section with lines.",
  'moduli.doc-elenco-nota': "Every section with lines has its own A4 document. Change texts, columns and footer: the preview updates as you type.",
  'moduli.doc-documento': "Document",
  'moduli.doc-modello': "Template",
  'moduli.doc-personalizzato': "customised",
  'moduli.doc-predefinito': "default",
  'moduli.doc-sinistra': "left",
  'moduli.doc-destra': "right",
  'moduli.doc-salva-modello': "Save the template",
  'moduli.doc-modello-salvato': "Template saved",
  'moduli.doc-torna-predefinito': "Back to default",
  'moduli.doc-torna-conferma': "Go back to the default template? The changes to this template will be lost.",
  'moduli.doc-modello-predefinito': "Default template",
  'moduli.doc-crea-uno': "Create at least one document in {nome} to see the preview.",
  'moduli.doc-segnaposto': "Placeholders you can use",
  'moduli.doc-seg-campi': "Document fields: ",
  'moduli.doc-seg-collegati': "Linked (any of their fields): ",
  'moduli.doc-seg-azienda': "Your company: ",
  'moduli.doc-seg-colonne': "In the columns, each line: ",
  'moduli.doc-seg-campi-riga': " and the line's fields: ",
  'moduli.doc-seg-totali': "Totals: ",
  'moduli.doc-seg-oggi': " · today: ",
  'moduli.doc-seg-se': "A part shown only if the field has a value: ",
  'moduli.doc-seg-se-manca': "; only if it's empty: ",
  'moduli.doc-ed-titolo': "Document title",
  'moduli.doc-ed-sopra-destinatario': "Above the recipient",
  'moduli.doc-ed-destinatario': "Recipient",
  'moduli.doc-ed-dettagli': "Details at the top right",
  'moduli.doc-ed-colonne': "Line columns",
  'moduli.doc-ed-riepilogo-iva': "VAT summary by rate",
  'moduli.doc-ed-prezzi-ivati': "Prices include VAT",
  'moduli.doc-ed-note': "Notes",
  'moduli.doc-ed-pagamento': "Payment",
  'moduli.doc-ed-piede': "Footer",
  'moduli.doc-ed-colore-label': "Colour",
  'moduli.doc-ed-colore-azienda': "the company's",
  'moduli.doc-crea-fattura': "Create invoice",
  'moduli.doc-crea-fattura-nota': "A draft invoice with this document's customer and lines",
  'moduli.doc-fattura-creata': "Draft invoice created",
  'moduli.doc-nota-credito': "Credit note",
  'moduli.doc-nota-credito-nota': "Reverse this invoice with a draft credit note",
  'moduli.doc-nota-conferma': "Create a credit note reversing invoice {numero}?",
  'moduli.doc-nota-creata': "Draft credit note created",
  'moduli.doc-fatturapa-titolo': "Check and download the XML file for SDI",
  'moduli.doc-stampa-titolo': "Preview, print and PDF",
  'moduli.doc-stampa': "Print",
  'moduli.im-scarica-modello': "Download the template to fill in",
  'moduli.api-f-valuta': "number (19.9)",
  'moduli.api-f-data': "YYYY-MM-DD",
  'moduli.api-f-uno-fra': "one of: {fra}",
  'moduli.api-f-multipla': "list of option ids",
  'moduli.api-f-rel-molti': "list of {entita} ids",
  'moduli.api-f-rel': "{entita} id (read as { id, titolo })",
  'moduli.api-f-righe': "list of {entita} lines",
  'moduli.api-f-lettura': "read only",
  'moduli.api-f-contatore': "read only, automatic",
  'moduli.api-f-file': "list [{ id, nome }] of uploads",
  'moduli.api-copia': "Copy",
  'moduli.api-copiato': "Copied",
  'moduli.api-copia-mano': "Select and copy by hand",
  'moduli.api-inizia': "Starts with",
  'moduli.api-creato': "Created",
  'moduli.api-scade': "Expires",
  'moduli.api-ultimo-uso': "Last used",
  'moduli.api-mai': "never",
  'moduli.api-revocato': "revoked",
  'moduli.api-revoca': "Revoke",
  'moduli.api-revocare': "Revoke “{nome}”? Whoever uses it will no longer get in.",
  'moduli.api-nessun-token': "No tokens yet.",
  'moduli.api-a-cosa': "What it's for (e.g. Website, Accounts)",
  'moduli.api-30': "30 days",
  'moduli.api-90': "90 days",
  'moduli.api-anno': "one year",
  'moduli.api-non-scade': "never expires",
  'moduli.api-crea-token': "Create the token",
  'moduli.api-ecco': "Here's the token. Copy it now: it won't be shown again.",
  'moduli.api-valore': "Value",
  'moduli.api-elenco': "List (q = search, f = JSON filters, o = sort field:desc, p = page, n = per page up to 500)",
  'moduli.api-una-riga': "One row",
  'moduli.api-modifica': "Edit (only the fields you send)",
  'moduli.api-esporta': "Export to Excel",
  'moduli.api-tutte': "All sections",
  'moduli.api-ev-crea': "created",
  'moduli.api-ev-modifica': "edited",
  'moduli.api-ev-elimina': "archived",
  'moduli.api-ev-ripristina': "restored",
  'moduli.api-consegnate': {"one": "{n} delivered", "other": "{n} delivered"},
  'moduli.api-fallite': {"one": "{n} failed", "other": "{n} failed"},
  'moduli.api-in-attesa': "{n} pending",
  'moduli.api-segreto': "Secret: ",
  'moduli.api-mostra': "Show",
  'moduli.api-prova': "Send a test",
  'moduli.api-prova-partenza': "Test on its way",
  'moduli.api-registro': "Log",
  'moduli.api-elimina-webhook': "Delete the webhook “{nome}”?",
  'moduli.api-evento': "Event",
  'moduli.api-stato': "Status",
  'moduli.api-tentativi': "Attempts",
  'moduli.api-risposta': "Response",
  'moduli.api-quando': "When",
  'moduli.api-st-ok': "delivered",
  'moduli.api-st-attesa': "pending",
  'moduli.api-st-invio': "sending",
  'moduli.api-st-fallita': "failed",
  'moduli.api-riprova': "Retry",
  'moduli.api-nessuna-consegna': "No deliveries yet.",
  'moduli.api-nessun-webhook': "No webhooks yet.",
  'moduli.api-nome-wh': "Name (e.g. Accounts)",
  'moduli.api-url-wh': "https://… the receiving address",
  'moduli.api-aggiungi-wh': "Add the webhook",
  'moduli.api-wh-aggiunto': "Webhook added",
  'moduli.api-intro': "Connect Kubo to your website, your accounts or an automation. Every call has the same permissions as your role.",
  'moduli.api-tuoi-token': "Your tokens",
  'moduli.api-documentazione': "Documentation",
  'moduli.api-doc-1': "Every request carries the header ",
  'moduli.api-doc-2': ". Responses are JSON; errors have ",
  'moduli.api-doc-3': " and the right HTTP code (401, 403, 404, 422).",
  'moduli.api-openapi-1': "The OpenAPI 3 description (for Postman, Swagger or to generate a client) is at ",
  'moduli.api-openapi-2': ", with only the sections the token can see.",
  'moduli.api-allegati': "Attachments are first uploaded in chunks (POST /api/file/carica, then /api/file/carica/<id> with { da, pezzo in base64 }) and then put in the field as [{ \"id\": \"<id>\" }].",
  'moduli.api-wh-intro': "When something changes, Kubo sends a signed JSON POST to the address you choose. If it doesn't answer, it retries after 30 seconds, 2, 10 and 30 minutes, and 2 hours.",
  'moduli.api-sezioni': "Sections (none = all)",
  'moduli.api-quando-riga': "When a row is",
  'moduli.api-firma': "How to verify the signature",
};
