export default {
  'moduli.lumi-serve-chiave': "To answer I need the Claude key. I'll open **Admin → Lumi** for you: it takes a minute.",
  'moduli.lumi-serve-chiave-spento': "To answer I need the Claude key and to be switched back on. I'll open **Admin → Lumi** for you: it takes a minute.",
  'moduli.lumi-chiedi-titolare': "To answer I need the Claude key: ask the owner to add it in **Admin → Lumi**.",
  'moduli.lumi-spento': "Lumi is off: switch it back on in Admin → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi is almost ready: the Claude key is missing.",
  'moduli.lumi-apri': "Open",
  'moduli.lumi-settimana': "How's the week",
  'moduli.lumi-settimana-domanda': "How did this week go? Give me the main figures.",
  'moduli.lumi-accendi': "Turn on Lumi",
  'moduli.lumi-solo-titolare': "Lumi's settings belong to the owner.",
  'moduli.lumi-gia-salvata': "•••••••• (already saved)",
  'moduli.lumi-stato-spento': "Off",
  'moduli.lumi-stato-acceso': "On",
  'moduli.lumi-stato-manca': "Key missing",
  'moduli.lumi-fonte-ambiente': "The key comes from the server's ANTHROPIC_API_KEY variable.",
  'moduli.lumi-fonte-file': "Key saved on this computer.",
  'moduli.lumi-cos-e': "Lumi is Kubo's assistant. You talk or write to it from the pill at the top: it searches, counts, prepares records and reshapes the system. Every change waits for your “Confirm”, and everyone sees only what their permissions allow.",
  'moduli.lumi-chiave': "Claude key",
  'moduli.lumi-salva-chiave': "Save the key",
  'moduli.lumi-incolla': "Paste the key",
  'moduli.lumi-togliere': "Remove the key? Lumi will stop answering.",
  'moduli.lumi-dove-chiave': "Create it at console.anthropic.com, under API Keys. It stays on this computer, in a file next to the data that only Kubo reads, and never reaches the browsers.",
  'moduli.lumi-acceso': "Lumi on",
  'moduli.lumi-limite': "Questions per minute per person",
  'moduli.lumi-da-provare': "Things to try",
  'moduli.lumi-esempio-1': "How much did I sell this week?",
  'moduli.lumi-esempio-2': "What do I need to reorder?",
  'moduli.lumi-esempio-3': "Add a size to products with S, M, L and XL",
  'moduli.lumi-esempio-4': "Make me a rentals section with customer, tool, from, to and status",
  'moduli.lumi-esempio-5': "When a rental is marked returned, let me know",
  'moduli.lumi-modello': "Model: {modello}.",
  'moduli.lumi-voce-accesa': "Real-time voice on.",
  'moduli.lumi-voce-browser': "Voice: the browser's own, where available.",
  'moduli.ag-adesso': "just now",
  'moduli.ag-agenda': "Calendar",
  'moduli.ag-calendario': "Calendar view",
  'moduli.ag-cruscotto': "Dashboard",
  'moduli.ag-aggiungi-voce': "Add the item",
  'moduli.ag-altri': {"one": "+{n} more", "other": "+{n} more"},
  'moduli.ag-e-altri': {"one": "and one more", "other": "and {n} more"},
  'moduli.ag-aria-grafico': "{titolo}: chart",
  'moduli.ag-barre': "Bars",
  'moduli.ag-linea': "Line",
  'moduli.ag-buongiorno': "Good morning",
  'moduli.ag-buon-pomeriggio': "Good afternoon",
  'moduli.ag-buonasera': "Good evening",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Change",
  'moduli.ag-cambia-widget': "Change the widget",
  'moduli.ag-nuovo-widget': "New widget",
  'moduli.ag-campo': "Field",
  'moduli.ag-colonne-per': "Columns: {nome}",
  'moduli.ag-una-colonna': "One column",
  'moduli.ag-come-oggi': "same as yesterday",
  'moduli.ag-come-settimana': "same as last week",
  'moduli.ag-come-mese': "same as last month",
  'moduli.ag-come-anno': "same as last year",
  'moduli.ag-rispetto-oggi': "{diff} vs yesterday ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} vs last week ({prima})",
  'moduli.ag-rispetto-mese': "{diff} vs last month ({prima})",
  'moduli.ag-rispetto-anno': "{diff} vs last year ({prima})",
  'moduli.ag-data-rif': "Reference date",
  'moduli.ag-prima': "Previous",
  'moduli.ag-dopo': "Next",
  'moduli.ag-fatto': "Done",
  'moduli.ag-forma': "Style",
  'moduli.ag-ha-creato': "created",
  'moduli.ag-ha-modificato': "edited",
  'moduli.ag-ha-archiviato': "archived",
  'moduli.ag-ha-ripristinato': "restored",
  'moduli.ag-in-sezione': "in {nome}",
  'moduli.ag-un-elemento': "an item",
  'moduli.ag-lista': "List",
  'moduli.ag-torna-lista': "Back to the list",
  'moduli.ag-media': "Average of…",
  'moduli.ag-somma': "Sum of…",
  'moduli.ag-quanti': "How many",
  'moduli.ag-misura': "Measure",
  'moduli.ag-modifica': "Edit",
  'moduli.ag-nome-voce': "Item name",
  'moduli.ag-nuova-voce': "New item",
  'moduli.ag-un-filtro': "Add at least one filter to the item",
  'moduli.ag-non-disegno': "I can't draw this",
  'moduli.ag-oggi': "Today",
  'moduli.ag-per': "By",
  'moduli.ag-periodo': "Period",
  'moduli.ag-periodo-oggi': "Today",
  'moduli.ag-periodo-settimana': "This week",
  'moduli.ag-periodo-mese': "This month",
  'moduli.ag-periodo-anno': "This year",
  'moduli.ag-periodo-ultimi_7': "Last 7 days",
  'moduli.ag-periodo-ultimi_30': "Last 30 days",
  'moduli.ag-periodo-ultimi_84': "Last 12 weeks",
  'moduli.ag-periodo-ultimi_365': "Last year",
  'moduli.ag-periodo-sempre': "All time",
  'moduli.ag-piede-grafico': "{periodo} · {totale} in total",
  'moduli.ag-piu-aggiungi': "+ Add",
  'moduli.ag-quale-data': "Which date",
  'moduli.ag-senza-titolo': "Untitled",
  'moduli.ag-spostato': "Moved",
  'moduli.ag-tipo': "Type",
  'moduli.ag-titolo': "Title",
  'moduli.ag-titolo-widget': "Give the widget a title",
  'moduli.ag-tutti': "all",
  'moduli.ag-utente-non-attivo': "Inactive user",
  'moduli.ag-vedi-calendario': "See on the calendar",
  'moduli.ag-vedi-elenco': "See the list",
  'moduli.ag-vedi-giorno': "See the day",
  'moduli.ag-vista-giorno': "Day",
  'moduli.ag-vista-settimana': "Week",
  'moduli.ag-vista-mese': "Month",
  'moduli.ag-w-numero': "Number",
  'moduli.ag-w-grafico': "Chart",
  'moduli.ag-w-attenzione': "Needs attention",
  'moduli.ag-w-ultime': "Latest changes",
};
