// Area «sicurezza» (web/moduli/sicurezza.js): password, dispositivi collegati, impostazioni dell'azienda, poteri dei ruoli.
export default {
  'sicurezza.titolo': 'Security',
  'sicurezza.la-tua-password': 'Your password',
  'sicurezza.dispositivi-collegati': 'Signed-in devices',
  'sicurezza.dispositivo': '{browser} on {sistema}',
  'sicurezza.dispositivo-sconosciuto': 'Unknown device',
  'sicurezza.app-kubo': 'Kubo app',
  'sicurezza.iphone-ipad': 'iPhone or iPad',
  'sicurezza.password-diverse': "The two new passwords don't match",
  'sicurezza.password-cambiata': 'Password changed. Your other devices have been signed out.',
  'sicurezza.password-attuale': 'Current password',
  'sicurezza.password-nuova': 'New password',
  'sicurezza.password-regole': 'At least 8 characters; under 12, mix letters with numbers or symbols.',
  'sicurezza.password-ripeti': 'Repeat the new password',
  'sicurezza.cambia-password': 'Change password',
  'sicurezza.col-dispositivo': 'Device',
  'sicurezza.col-ultimo-uso': 'Last used',
  'sicurezza.col-indirizzo': 'Address',
  'sicurezza.questo': 'this one',
  'sicurezza.scollega': 'Sign out',
  'sicurezza.scollegati': { one: 'Signed out {n} device', other: 'Signed out {n} devices' },
  'sicurezza.scollega-altri': 'Sign out all the others',
  'sicurezza.impostazioni': 'Company settings',
  'sicurezza.inattivita': 'Close sessions idle for (minutes)',
  'sicurezza.allegati': 'Attachments: up to (MB)',
  'sicurezza.fuso': 'Time zone',
  'sicurezza.lumi-budget': 'Lumi: tokens per month (0 = no limit)',
  'sicurezza.lumi-usati': 'Used this month: {usati}',
  'sicurezza.webhook-interni': "Allow webhooks to the internal network (127.0.0.1, 192.168…). Leave it off if you're not sure what it's for.",
  'sicurezza.salvate': 'Settings saved',
  'sicurezza.salva': 'Save',
  'sicurezza.ruoli': 'Role permissions',
  'sicurezza.ruoli-nota': "Exporting an e-invoice uses up an invoice number; Lumi uses the company's tokens.",
  'sicurezza.col-ruolo': 'Role',
  'sicurezza.potere-fatturapa': 'Export FatturaPA',
  'sicurezza.potere-lumi': 'Use Lumi',
  'sicurezza.potere-aria': '{potere} for {ruolo}',
  'sicurezza.salvato': 'Saved',
  'sicurezza.persone': 'People',
  'sicurezza.col-nome': 'Name',
  'sicurezza.obbliga-cambio': 'Require a password change',
  'sicurezza.obbligo-fatto': '{nome} will change their password at next sign-in',
  'sicurezza.scollega-ovunque': 'Sign out everywhere',
  'sicurezza.scollegato-ovunque': "{nome}'s sessions closed on all devices",
  'sicurezza.nessun-altro': 'No one else yet.',
  'sicurezza.scegli-password': 'Choose your password',
  'sicurezza.provvisoria': 'The password you were given was temporary. Choose your own to continue.',
};
