// Treasury (web/moduli/tesoreria.js): due dates, bank reconciliation, cash-flow forecast, payment reminders, bank batches.
export default {
  'tesoreria.titolo': "Treasury",
  'tesoreria.scheda-scadenze': "Due dates",
  'tesoreria.scheda-banca': "Bank",
  'tesoreria.scheda-cassa': "Cash-flow forecast",
  'tesoreria.scheda-solleciti': "Reminders",
  'tesoreria.scheda-distinte': "Bank batches",
  'tesoreria.scheda-impostazioni': "Settings",
  'tesoreria.manca-fatture': "Due dates come from invoices: add the «Invoices and e-invoicing» template from Customise.",
  'tesoreria.da-incassare': "To collect",
  'tesoreria.da-pagare': "To pay",
  'tesoreria.di-cui-scaduto': "of which overdue {importo}",
  'tesoreria.saldo-netto': "Difference",
  'tesoreria.verso-attiva': "Collections from customers",
  'tesoreria.verso-passiva': "Payments to suppliers",
  'tesoreria.solo-scadute': "Overdue only",
  'tesoreria.cerca': "Search customer or document",
  'tesoreria.scadenza': "Due date",
  'tesoreria.documento': "Document",
  'tesoreria.cliente': "Customer",
  'tesoreria.fornitore': "Supplier",
  'tesoreria.importo': "Amount",
  'tesoreria.residuo': "Outstanding",
  'tesoreria.stato': "Status",
  'tesoreria.pagata': "Paid",
  'tesoreria.in-distinta': "In a batch",
  'tesoreria.scaduta-da': { one: "Overdue by {n} day", other: "Overdue by {n} days" },
  'tesoreria.parziale': "Part-paid",
  'tesoreria.aperta': "Open",
  'tesoreria.incassata': "Collected",
  'tesoreria.pagata-btn': "Paid",
  'tesoreria.acconto': "Part payment",
  'tesoreria.niente-scadenze': "No open due dates.",
  'tesoreria.scegli-nota': "Tick due dates to mark them paid or prepare the file for the bank.",
  'tesoreria.scelte': { one: "{n} selected · {importo}", other: "{n} selected · {importo}" },
  'tesoreria.segna-incassate': "Mark collected",
  'tesoreria.segna-pagate': "Mark paid",
  'tesoreria.distinta-riba': "Ri.Ba. batch",
  'tesoreria.distinta-sdd': "SDD direct debit",
  'tesoreria.distinta-sct': "SEPA transfers",
  'tesoreria.data-pagamento': "Payment date (YYYY-MM-DD)",
  'tesoreria.data-esecuzione': "Execution date at the bank (YYYY-MM-DD)",
  'tesoreria.data-accredito': "Credit or payment date (YYYY-MM-DD)",
  'tesoreria.importo-acconto': "Amount collected or paid",
  'tesoreria.importo-non-valido': "Invalid amount",
  'tesoreria.incassi-registrati': { one: "Collection recorded", other: "{n} collections recorded" },
  'tesoreria.pagamenti-registrati': { one: "Payment recorded", other: "{n} payments recorded" },
  'tesoreria.distinta-creata': "{nome} ready: {importo}. Upload the file to your online banking.",
  'tesoreria.nota-termini': "Due dates come from the invoice instalments, the due date, or the payment terms of the customer or supplier (for example 30/60/90 DFFM).",
  'tesoreria.err-sia': "The company's SIA code is missing (your bank gives it to you): enter it in the treasury settings.",
  'tesoreria.err-iban-azienda': "The company IBAN is missing or wrong: Documents → company details.",
  'tesoreria.err-banca-debitore': "{nome}: the IBAN of the customer's bank is missing from their record.",
  'tesoreria.err-cf-debitore': "{nome}: the VAT number or tax code is missing.",
  'tesoreria.err-importo': "{nome}: invalid amount to collect.",
  'tesoreria.err-id-creditore': "The SEPA creditor identifier is missing (your bank issues it): treasury settings.",
  'tesoreria.err-iban-debitore': "{nome}: customer IBAN missing or wrong.",
  'tesoreria.err-mandato-id': "{nome}: the SDD mandate reference has characters that aren't allowed or is longer than 35: fix it on the customer card (it must match the signed mandate exactly).",
  'tesoreria.err-mandato': "{nome}: the SDD mandate reference and date are missing from the customer record.",
  'tesoreria.err-iban-beneficiario': "{nome}: supplier IBAN missing or wrong.",
  'tesoreria.banca-titolo': "Bank statement and reconciliation",
  'tesoreria.manca-movimenti': "To import a bank statement you need the «Bank transactions» section.",
  'tesoreria.prepara': "Set up treasury",
  'tesoreria.preparata': { one: "Added {n} item", other: "Added {n} items" },
  'tesoreria.chiedi-titolare': "Ask someone who can customise the system.",
  'tesoreria.file-grande': "{nome} is too large",
  'tesoreria.importati': "Imported {n} transactions, {doppi} already there",
  'tesoreria.saldo-aggiornato': "Forecast balance updated: {importo} on {data}",
  'tesoreria.carica-estratto': "Drop the bank statement here, or click",
  'tesoreria.formati': "CAMT.053 (XML), CBI, or your bank's CSV or Excel",
  'tesoreria.abbinato': "Matched: due dates marked paid",
  'tesoreria.abbinato-differenza': "Matched; {importo} left over",
  'tesoreria.abbina-a': "Match to…",
  'tesoreria.abbina': "Match",
  'tesoreria.ignora': "Ignore",
  'tesoreria.ignora-nota': "Fees, internal transfers, salaries: transactions that don't settle an invoice",
  'tesoreria.nessuna-proposta': "No suggestion: pick one by hand below.",
  'tesoreria.da-abbinare': { one: "{n} transaction to match", other: "{n} transactions to match" },
  'tesoreria.tutto-abbinato': "Everything matched.",
  'tesoreria.abbinati-recenti': "Recently matched",
  'tesoreria.data': "Date",
  'tesoreria.descrizione': "Description",
  'tesoreria.mov-abbinato': "Matched",
  'tesoreria.mov-ignorato': "Ignored",
  'tesoreria.mov-da_abbinare': "To match",
  'tesoreria.annulla': "Undo",
  'tesoreria.nota-movimenti': "Transactions live in the «{sezione}» section: bank connections (open banking) fill it too.",
  'tesoreria.perche-importo': "same amount",
  'tesoreria.perche-importo-vicino': "similar amount",
  'tesoreria.perche-acconto': "part payment",
  'tesoreria.perche-numero': "invoice number",
  'tesoreria.perche-iban': "same IBAN",
  'tesoreria.perche-nome': "name",
  'tesoreria.perche-data': "close date",
  'tesoreria.perche-somma': "several invoices together",
  'tesoreria.perche-distinta': "batch credit",
  'tesoreria.grafico': "Expected income, outgoings and balance",
  'tesoreria.passo-settimana': "Weeks",
  'tesoreria.passo-mese': "Months",
  'tesoreria.senza-saldo': "The opening balance is missing: enter it in the settings, or import a CAMT.053 statement.",
  'tesoreria.apri-impostazioni': "Open settings",
  'tesoreria.scoperto': "Warning: cash goes below zero, down to {importo} on {data}.",
  'tesoreria.saldo-oggi': "Balance today",
  'tesoreria.saldo-dal': "from the balance on {data} plus transactions",
  'tesoreria.saldo-fine': "Expected balance",
  'tesoreria.punto-basso': "Lowest point",
  'tesoreria.entrate': "Income",
  'tesoreria.uscite': "Outgoings",
  'tesoreria.saldo': "Balance",
  'tesoreria.periodi': "By period",
  'tesoreria.periodo': "Period",
  'tesoreria.voci': "Where the numbers come from",
  'tesoreria.tipo': "Type",
  'tesoreria.voce-incasso': "Collection",
  'tesoreria.voce-pagamento': "Payment",
  'tesoreria.voce-previsione': "Forecast",
  'tesoreria.voce-contratto': "Recurring contract",
  'tesoreria.voce-tasse': "Taxes",
  'tesoreria.ritardo-medio': { one: "the customer pays {n} day late on average", other: "the customer pays {n} days late on average" },
  'tesoreria.niente-voci': "Nothing coming up in this period.",
  'tesoreria.aggiungi-previsione': "Add rent, salaries, loans and other forecasts",
  'tesoreria.sollecito-segnato': "Reminder recorded",
  'tesoreria.livello-1': "Friendly reminder",
  'tesoreria.livello-2': "Reminder",
  'tesoreria.livello-3': "Formal notice",
  'tesoreria.appena-sollecitato': "Recently reminded",
  'tesoreria.ritardo-giorni': { one: "{n} day late", other: "{n} days late" },
  'tesoreria.ultimo-sollecito': "Last reminder on {data} (level {livello})",
  'tesoreria.lettera': "Reminder text",
  'tesoreria.copia': "Copy text",
  'tesoreria.copiato': "Copied",
  'tesoreria.copia-no': "Couldn't copy: select the text by hand",
  'tesoreria.oggetto-sollecito': "Payment reminder",
  'tesoreria.scrivi-email': "Write the email",
  'tesoreria.segna-mandato': "Mark as sent",
  'tesoreria.niente-solleciti': "No customers are late.",
  'tesoreria.distinta-chiusa': "Batch closed: due dates marked paid",
  'tesoreria.distinta': "Batch",
  'tesoreria.creata': "Created",
  'tesoreria.quante': "Due dates",
  'tesoreria.pagata-il': "Paid on {data}",
  'tesoreria.accreditata-il': "Credited on {data}",
  'tesoreria.in-attesa': "Pending",
  'tesoreria.scarica': "Download",
  'tesoreria.segna-pagati': "Mark paid",
  'tesoreria.segna-accreditata': "Mark credited",
  'tesoreria.niente-distinte': "No batches yet: prepare them from the due dates.",
  'tesoreria.nota-distinte': "Upload the file to your online banking (Ri.Ba. in CBI format, SDD and transfers in SEPA XML). When the bank credits the batch, reconciliation suggests it by itself.",
  'tesoreria.salvate': "Settings saved",
  'tesoreria.sia': "SIA code",
  'tesoreria.bic': "Your bank's BIC (optional)",
  'tesoreria.id-creditore': "SEPA creditor identifier (for SDD)",
  'tesoreria.saldo-banca': "Account balance",
  'tesoreria.saldo-data': "Balance on",
  'tesoreria.sequenza-sdd': "SDD debit type",
  'tesoreria.seq-rcur': "Recurring (RCUR)",
  'tesoreria.seq-frst': "First of a series (FRST)",
  'tesoreria.seq-ooff': "One-off (OOFF)",
  'tesoreria.sezione-movimenti': "Bank transactions section",
  'tesoreria.ritardo-clienti': "In the forecast, shift collections by each customer's average delay",
  'tesoreria.salva': "Save",
  'tesoreria.banca-azienda': "The company account",
  'tesoreria.iban-azienda': "IBAN used for Ri.Ba., SDD and transfers: {iban}",
  'tesoreria.manca-iban': "The company IBAN is missing.",
  'tesoreria.dati-azienda': "Company details",
  'tesoreria.nota-sia': "Your bank gives you the SIA code and the creditor identifier when you activate Ri.Ba. and SDD. The suggested identifier is computed from the VAT number: check it with your bank.",
  'tesoreria.sezioni': "Sections",
  'tesoreria.sezioni-mancano': "«Bank transactions» or «Cash forecasts» are missing, as are the payment fields of customers and suppliers (terms, IBAN, SDD mandate).",
  'tesoreria.sezioni-ci-sono': "They're all there.",
  'tesoreria.termini': "Payment terms",
  'tesoreria.termini-nota': "Write them in the customer or supplier record. DF = invoice date, FM = end of month, +10 = the 10th of the next month. 30, 60, 90 days count as months.",
};
