export default {
  'viste.cerca-in': 'Search {nome}…',
  'viste.nuovo': '+ New',
  'viste.tabella': 'Table',
  'viste.kanban': 'Kanban',
  'viste.archiviati': 'Archived',
  'viste.viste-salvate': 'Saved views',
  'viste.colonne': 'Columns',
  'viste.raggruppa': 'Group',
  'viste.senza-gruppi': 'No grouping',
  'viste.gruppi-per': 'Group by: {nome}',
  'viste.salva-vista': 'Save view',
  'viste.tutti': 'All',
  'viste.per-tutti': 'For everyone',
  'viste.mie': 'Mine',
  'viste.filtri-tolti': 'Some filters in this view use fields you can\'t see, so I removed them',
  'viste.salva-modifiche': 'Save changes…',
  'viste.esempio-vista': 'E.g. To deliver this week',
  'viste.nome-vista': 'Give the view a name',
  'viste.salvata-tutti': 'View saved for everyone',
  'viste.salvata-te': 'View saved for you',
  'viste.vista-nome': 'View “{nome}”',
  'viste.salva-questa': 'Save this view',
  'viste.cosa-salva': 'Current filters, columns, groups and sort order.',
  'viste.la-vedono-tutti': 'Everyone can see it',
  'viste.solo-tu': 'Only you will see it.',
  'viste.elimina': 'Delete',
  'viste.elimina-vista': 'Delete the view “{nome}”?',
  'viste.vista-eliminata': 'View deleted',
  'viste.salva-nuova': 'Save as new',
  'viste.aggiorna': 'Update',
  'viste.salva': 'Save',
  'viste.come-inizio': 'Reset',
  'viste.nessuno': 'None',
  'viste.nessun-risultato': 'No results.',
  'viste.niente-archivio': 'Nothing archived.',
  'viste.ancora-nessuno': 'Nothing in {nome} yet.',
  'viste.crea-primo': '+ Create the first one',
  'viste.totale': 'Total ({n})',
  'viste.prime-di': 'Showing the first {k} of {n} (totals include them all)',
  'viste.in-tutto': { one: '{n} in total', other: '{n} in total' },
  'viste.crea': 'Create',
  'viste.creato': 'Created',
  'viste.salvato': 'Saved',
  'viste.nuovo-in': 'New in {nome}',
  'viste.archivia': 'Archive',
  'viste.archiviare': 'Archive it? You can restore it from the archive.',
  'viste.archiviato': 'Archived',
  'viste.ripristina': 'Restore',
  'viste.ripristinato': 'Restored',
  'viste.storia': 'History',
  'viste.archiviato-min': 'archived',
  'viste.automazione': 'automation',
  'viste.storia-creato': 'created',
  'viste.storia-ripristinato': 'restored',
  'viste.non-si-passa': 'You can\'t get here from “{da}”',
  'viste.al-salvataggio': 'when saved',
  'viste.piu-immagine': '+ Image',
  'viste.piu-file': '+ File',
  'viste.non-immagine': '“{nome}” isn\'t an image',
  'viste.o-trascina': 'or drag it here',
  'viste.righe-non-trovata': 'Line entity not found',
  'viste.aggiungi-riga': '+ Add line',
  'viste.creato-il': 'Created on',
  'viste.modificato-il': 'Modified on',
  'viste.periodo-oggi': 'today',
  'viste.periodo-ieri': 'yesterday',
  'viste.periodo-settimana': 'this week',
  'viste.periodo-mese': 'this month',
  'viste.periodo-ultimi_7': 'last 7 days',
  'viste.periodo-ultimi_30': 'last 30 days',
  'viste.periodo-anno': 'this year',
  'viste.op-uguale': 'is',
  'viste.op-diverso': 'is not',
  'viste.op-tra': 'between',
  'viste.op-contiene': 'contains',
  'viste.op-inizia': 'starts with',
  'viste.op-vuoto': 'is empty',
  'viste.op-nonvuoto': 'is not empty',
  'viste.op-in': 'is one of',
  'viste.op-prima': 'before',
  'viste.op-dopo': 'from',
  'viste.op-vero': 'is true',
  'viste.op-falso': 'is false',
  'viste.o': ' or ',
  'viste.tra-e': '{a} and {b}',
  'viste.io': 'me',
  'viste.me': 'me',
  'viste.io-maiuscolo': 'Me',
  'viste.piu-filtro': '+ Filter',
  'viste.cambia-filtro': 'Change filter',
  'viste.togli-tutti': 'Clear all',
  'viste.scegli-campo': 'Choose a field…',
  'viste.nel-periodo': 'in the period',
  'viste.testo': 'text',
  'viste.scegli-un-campo': 'Choose a field',
  'viste.manca-valore': 'The value is missing',
  'viste.nuovo-filtro': 'New filter',
  'viste.applica': 'Apply',
};
