// Il modulo WhatsApp dell'interfaccia (web/moduli/whatsapp.js): conversazioni, modelli, automazioni, impostazioni.
export default {
  'whatsapp.forse-stop': 'Looks like a request to stop receiving messages',
  'whatsapp.segna-stop': 'Mark as STOP',
  'whatsapp.s-approvato': "Approved",
  'whatsapp.s-in_attesa': "Pending",
  'whatsapp.s-rifiutato': "Rejected",
  'whatsapp.s-in_pausa': "Paused",
  'whatsapp.s-disattivato': "Disabled",
  'whatsapp.s-inviato': "Sent",
  'whatsapp.s-consegnato': "Delivered",
  'whatsapp.s-letto': "Read",
  'whatsapp.s-fallito': "Failed",
  'whatsapp.s-bloccato': "Stopped",
  'whatsapp.s-coda': "Queued",
  'whatsapp.s-ricevuto': "Received",
  'whatsapp.finestra-aperta': "Window open until {ora}",
  'whatsapp.finestra-chiusa': "Window closed: a template is needed",
  'whatsapp.attivo': "Active: {nome}",
  'whatsapp.nessuno': "No WhatsApp service is on.",
  'whatsapp.vai-connettori': "Connect it from the connectors",
  'whatsapp.conversazioni': "Conversations",
  'whatsapp.modelli': "Templates",
  'whatsapp.automazioni': "WhatsApp automations",
  'whatsapp.impostazioni': "Settings",
  'whatsapp.vuoto': "No messages yet.",
  'whatsapp.scegli': "Pick a conversation.",
  'whatsapp.c-servizio': "Service",
  'whatsapp.c-marketing': "Promotions",
  'whatsapp.si-no-si': "yes",
  'whatsapp.si-no-no': "no",
  'whatsapp.fonte-chiedi': "How did you collect the choice? (e.g. in-store form, website, in person)",
  'whatsapp.testo-chiedi': "The exact wording the customer agreed to:",
  'whatsapp.testo-predefinito': "I agree to receive WhatsApp messages from this business. I can reply STOP at any time.",
  'whatsapp.ok-servizio': "Service consent",
  'whatsapp.ok-marketing': "Promotions consent",
  'whatsapp.revoca': "Withdraw",
  'whatsapp.sconosciuto': "Number not in your contacts.",
  'whatsapp.crea-cliente': "Create customer",
  'whatsapp.crea-lead': "Create lead",
  'whatsapp.scrivi': "Write a reply…",
  'whatsapp.serve-modello': "Outside the 24-hour window: pick an approved template",
  'whatsapp.testo-libero': "Free text",
  'whatsapp.scegli-modello': "Pick a template",
  'whatsapp.k-servizio': "Service",
  'whatsapp.k-utility': "Utility",
  'whatsapp.k-marketing': "Marketing",
  'whatsapp.k-authentication': "Authentication",
  'whatsapp.costo': "Estimated cost",
  'whatsapp.inviato': "Message sent",
  'whatsapp.invia': "Send",
  'whatsapp.anteprima': "Preview",
  'whatsapp.sincronizzati': "Templates updated",
  'whatsapp.sincronizza': "Sync templates",
  'whatsapp.salvato': "Saved",
  'whatsapp.modelli-nota': "Each {{n}} variable takes its value from a field: for example cliente.nome or riga.quando.",
  'whatsapp.nessun-modello': "No templates: sync them or create one.",
  'whatsapp.corpo-esempio': "Hi {{1}}, your order is ready.",
  'whatsapp.esempi-esempio': "Mario; Tuesday at 3 pm",
  'whatsapp.nuovo-modello': "New template",
  'whatsapp.nuovo-nota': "Meta reviews it before approval, usually within minutes. Each variable needs an example. Templates with a PDF header are created in WhatsApp Manager.",
  'whatsapp.nome': "Name (lowercase, numbers, _)",
  'whatsapp.categoria': "Category",
  'whatsapp.lingua': "Language",
  'whatsapp.testo': "Text",
  'whatsapp.esempi': "Variable examples, separated by ;",
  'whatsapp.mandato-a-meta': "Template sent for approval",
  'whatsapp.manda-approvazione': "Submit for approval",
  'whatsapp.automazioni-nota': "Turn on the ones you need, pick the template and the timing. Before each send Kubo checks consent, STOP, quiet hours and limits.",
  'whatsapp.o-ore': "Hours before (e.g. 24, 2)",
  'whatsapp.o-giorni': "After how many days",
  'whatsapp.o-mesi': "Inactive for months",
  'whatsapp.o-link': "Review link",
  'whatsapp.o-testo': "Reply text",
  'whatsapp.esempio-da-approvare': "Template example: create it and get it approved, then pick it here.",
  'whatsapp.mancano': "Variables with no value: {n}",
  'whatsapp.salva': "Save",
  'whatsapp.r-promemoria': "Appointment reminder",
  'whatsapp.r-conferma': "Booking confirmation",
  'whatsapp.r-pronto': "Order ready or shipped",
  'whatsapp.r-documento': "Invoice or quote with PDF",
  'whatsapp.r-sollecito': "Payment reminder",
  'whatsapp.r-recensione': "Review request",
  'whatsapp.r-compleanno': "Birthday wishes",
  'whatsapp.r-riattivazione': "Win back inactive customers",
  'whatsapp.r-fuori_orario': "Out-of-hours reply",
  'whatsapp.rd-promemoria': "A message before the appointment (24 and 2 hours before, or as you like).",
  'whatsapp.rd-conferma': "As soon as a booking is created.",
  'whatsapp.rd-pronto': "When the status turns ready or shipped, with the tracking number if there is one.",
  'whatsapp.rd-documento': "When the invoice is issued or the quote sent: the PDF goes with a template that has a document header.",
  'whatsapp.rd-sollecito': "Every morning, for invoices overdue by N days (once per invoice).",
  'whatsapp.rd-recensione': "N days after the sale, with the link to your review page.",
  'whatsapp.rd-compleanno': "On the morning of the customer's birthday.",
  'whatsapp.rd-riattivazione': "To customers who have not come back for N months, once.",
  'whatsapp.rd-fuori_orario': "When a customer writes while you are closed: free text, at most once every 12 hours.",
  'whatsapp.serve-marketing': "Promotional: sent only to customers who agreed to promotions, never during quiet hours.",
  'whatsapp.non-possibile': "Your setup lacks the sections or fields this automation needs.",
  'whatsapp.modello': "Template",
  'whatsapp.i-prefisso': "Default country code",
  'whatsapp.i-silenzio-da': "Quiet from",
  'whatsapp.i-silenzio-a': "to",
  'whatsapp.i-silenzio-tutti': "Quiet hours also for automatic service messages",
  'whatsapp.i-limite-giorno': "Templates per day, in total",
  'whatsapp.i-limite-cliente': "Templates per day per customer",
  'whatsapp.i-marketing-giorni': "One promotional every how many days",
  'whatsapp.i-sconosciuti': "Senders not in your contacts",
  'whatsapp.i-apre': "Opens at",
  'whatsapp.i-chiude': "Closes at",
  'whatsapp.i-giorni': "Open days (0 = Sunday)",
  'whatsapp.i-t-marketing': "Marketing, € per message",
  'whatsapp.i-t-utility': "Utility, € per message",
  'whatsapp.i-t-authentication': "Authentication, € per message",
  'whatsapp.i-t-servizio': "Service, € beyond the free quota",
  'whatsapp.i-t-servizioGratisMese': "Free service messages per month (empty = all)",
  'whatsapp.i-t-twilio': "Twilio fee, € per message",
  'whatsapp.sc-chiedi': "Ask me (keep it as a number)",
  'whatsapp.sc-cliente': "Create a customer",
  'whatsapp.sc-lead': "Create a lead",
  'whatsapp.webhook': "Webhook URL",
  'whatsapp.webhook-meta': "Paste it on Meta (WhatsApp → Configuration) with the verify token on the connector page, and subscribe to messages and message_template_status_update. It must be reachable from the internet over https.",
  'whatsapp.webhook-360': "Kubo registers it on 360dialog by itself when the public address is set on the connector page.",
  'whatsapp.webhook-twilio': "Paste it on your Twilio WhatsApp sender as the incoming messages URL. The public address on the connector page must match what Twilio sees.",
  'whatsapp.apri-connettore': "Open the connector",
  'whatsapp.costi-mese': "This month",
  'whatsapp.nessun-costo': "No paid messages this month.",
  'whatsapp.costi-nota': "Estimate with Meta's prices for Italy ({data}): Meta's or your provider's invoice is what counts.",
  'whatsapp.regole': "Sending rules",
  'whatsapp.tariffe': "Prices",
  'whatsapp.tariffe-nota': "Meta updates the rate card every quarter: fix the amounts here when they change.",
  'whatsapp.registro': "Stopped or failed messages",
  'whatsapp.registro-vuoto': "Nothing to report.",
  'whatsapp.storia': "WhatsApp history",
  'whatsapp.senza-numero': "The customer has no phone number.",
  'whatsapp.apri-chat': "Open the conversation",
};
