// Compras (web/moduli/acquisti.js): reposición, pedidos en camino, recepciones, facturas de proveedores.
export default {
  'acquisti.titolo': "Compras",
  'acquisti.scheda-riordino': "Por reponer",
  'acquisti.scheda-arrivo': "En camino",
  'acquisti.scheda-fatture': "Facturas de proveedores",
  'acquisti.stato-bozza': "Borrador",
  'acquisti.stato-inviato': "Enviado",
  'acquisti.stato-parziale': "Recibido en parte",
  'acquisti.stato-arrivato': "Recibido",
  'acquisti.stato-annullato': "Anulado",
  'acquisti.serve-magazzino': "Para las compras hace falta una sección con existencias (artículos, recambios, materiales…).",
  'acquisti.non-pronti': "Las compras aún no están listas.",
  'acquisti.chiedi-titolare': "Pídeselo a quien puede personalizar el sistema.",
  'acquisti.magazzino': "Sección del almacén",
  'acquisti.prepara-titolo': "Preparar las compras",
  'acquisti.prepara-nota': "Kubo usa los «Pedidos a proveedores» que ya existen, o los crea, y añade la cantidad recibida, el estado «recibido en parte», el albarán y la factura del proveedor. Tus datos no cambian.",
  'acquisti.prepara': "Preparar",
  'acquisti.preparati': {"one": "Añadido {n} elemento", "other": "Añadidos {n} elementos"},
  'acquisti.niente-riordino': "Nada bajo mínimos: todo está por encima del umbral, o ya pedido.",
  'acquisti.fornitore': "Proveedor",
  'acquisti.scegli-fornitore': "Elige el proveedor…",
  'acquisti.da-ordinare': "Por pedir",
  'acquisti.senza-fornitore': "Sin proveedor",
  'acquisti.senza-fornitore-nota': "Estos artículos no tienen proveedor en su ficha: elígelo aquí.",
  'acquisti.articolo': "Artículo",
  'acquisti.giacenza': "Existencias",
  'acquisti.soglia': "Mínimo",
  'acquisti.in-arrivo': "En camino",
  'acquisti.costo': "Coste",
  'acquisti.totale-stimato': "Total estimado: {importo}",
  'acquisti.niente-scelto': "No has elegido nada que pedir",
  'acquisti.ordini-creati': {"one": "Creado {n} pedido en borrador", "other": "Creados {n} pedidos en borrador"},
  'acquisti.riordino-nota': "Bajo mínimos quiere decir existencias más lo ya pedido sin superar el umbral. Kubo propone volver al doble del umbral: ajusta las cantidades como quieras.",
  'acquisti.crea-ordini': "Crear los pedidos",
  'acquisti.crea-nota': "Un pedido en borrador por proveedor: revísalo y envíalo.",
  'acquisti.in-ritardo': "Con retraso: previsto el {data}",
  'acquisti.previsto': "Previsto el {data}",
  'acquisti.ricevi': "Recibir mercancía",
  'acquisti.ricevute-di': "{ricevuta} de {quantita}",
  'acquisti.niente-arrivo': "Ningún pedido en camino.",
  'acquisti.ordine-chiuso': "Este pedido ya está cerrado.",
  'acquisti.vedi-confronto': "Ver la comparación",
  'acquisti.ddt-segnaposto': "Número y fecha del albarán",
  'acquisti.ricevuto-tutto': "Mercancía recibida: pedido completo",
  'acquisti.ricevuto-parte': "Mercancía recibida: el pedido sigue abierto por el resto",
  'acquisti.ricevi-titolo': "Recibir mercancía: {numero}, {fornitore}",
  'acquisti.ddt': "Albarán del proveedor",
  'acquisti.data': "Fecha",
  'acquisti.ordinate': "Pedidas",
  'acquisti.gia-ricevute': "Ya recibidas",
  'acquisti.arrivate-ora': "Llegadas ahora",
  'acquisti.ricevi-nota': "Las cantidades llegadas entran enseguida en el almacén y el coste del artículo pasa a ser el coste medio ponderado. Lo que falta sigue en camino.",
  'acquisti.carica': "Cargar en almacén",
  'acquisti.annulla': "Cancelar",
  'acquisti.senza-fatture': "Para conciliar facturas hace falta la plantilla «Facturas y factura electrónica».",
  'acquisti.ordine': "Pedido",
  'acquisti.ricevuto': "Recibido",
  'acquisti.fattura-proposta': "Factura propuesta",
  'acquisti.candidata': "{numero}: {importo}",
  'acquisti.nessuna-fattura': "Ninguna factura de este proveedor",
  'acquisti.confronta': "Comparar",
  'acquisti.tutto-fatturato': "Cada mercancía recibida tiene su factura.",
  'acquisti.fatture-nota': "Kubo compara el valor de la mercancía recibida con la base imponible de las facturas del proveedor. Cuadra si la diferencia es de 1 € o del 1% como mucho.",
  'acquisti.abbinata': "Factura asociada",
  'acquisti.tolta': "Factura quitada",
  'acquisti.ordinato': "Pedido",
  'acquisti.fatturato': "Facturado",
  'acquisti.confronto-titolo': "{numero} · {fornitore}",
  'acquisti.torna': "Cuadra con la factura {numero}.",
  'acquisti.non-torna': "La factura {numero} no cuadra: diferencia {importo}.",
  'acquisti.togli': "Quitar",
  'acquisti.candidate': "Facturas candidatas",
  'acquisti.fattura': "Factura",
  'acquisti.imponibile': "Base imponible",
  'acquisti.differenza': "Diferencia",
  'acquisti.abbina': "Asociar",
  'acquisti.ricevimenti': "Recepciones",
  'acquisti.quantita': "Cantidad",
};
