// Area «avvio» (web/moduli/avvio.js) · Español.
export default {
  'avvio.avanti': "Siguiente",
  'avvio.indietro': "← Atrás",
  'avvio.azienda-es': "p. ej. Taller Ferri",
  'avvio.sottotitolo': "Diez preguntas y tu software de gestión está listo, hecho a la medida de tu trabajo. Todo se puede cambiar después.",
  'avvio.nome-attivita': "¿Cómo se llama tu negocio?",
  'avvio.d-settore': "¿A qué te dedicas?",
  'avvio.a-settore': "Elige el más parecido. Después se puede cambiar todo.",
  'avvio.o-settore-negozio': "Tienda y comercio",
  'avvio.sd-negozio': "Vendo en mostrador, con artículos y almacén",
  'avvio.o-settore-ristorante': "Restaurante y bar",
  'avvio.sd-ristorante': "Mesas, comandas, carta con alérgenos, reservas",
  'avvio.o-settore-laboratorio': "Taller artesano",
  'avvio.sd-laboratorio': "Presupuestos, encargos por fases, materiales",
  'avvio.o-settore-officina': "Reparaciones y servicio técnico",
  'avvio.sd-officina': "Vehículos o aparatos, intervenciones, recambios, garantías",
  'avvio.o-settore-studio': "Consulta y servicios",
  'avvio.sd-studio': "Agenda, fichas de cliente, bonos de sesiones",
  'avvio.o-settore-beauty': "Belleza y estética",
  'avvio.sd-beauty': "Agenda por cabina, tratamientos, bonos, productos",
  'avvio.o-settore-palestra': "Gimnasio y asociación",
  'avvio.sd-palestra': "Socios, cuotas y renovaciones, clases y asistencia",
  'avvio.o-settore-professionista': "Profesional y agencia",
  'avvio.sd-professionista': "Clientes, proyectos, horas, plazos, presupuestos",
  'avvio.o-settore-noleggio': "Alquiler",
  'avvio.sd-noleggio': "Bienes, disponibilidad, contratos desde/hasta, fianzas",
  'avvio.o-settore-altro': "Otro, empiezo de cero",
  'avvio.sd-altro': "Un software de gestión vacío: las secciones las creas tú",
  'avvio.d-offerta': "¿Vendes productos, servicios o ambos?",
  'avvio.o-offerta-prodotti': "Productos",
  'avvio.o-offerta-servizi': "Servicios",
  'avvio.o-offerta-entrambi': "Ambos",
  'avvio.d-magazzino': "¿Tienes almacén?",
  'avvio.a-magazzino': "Existencias, stock mínimo, qué volver a pedir.",
  'avvio.d-su_misura': "¿Haces trabajos a medida, con presupuestos?",
  'avvio.a-su_misura': "El presupuesto con sus partidas; cuando el cliente acepta, se abre el trabajo.",
  'avvio.d-appuntamenti': "¿Das citas o tomas reservas?",
  'avvio.a-appuntamenti': "Una agenda por persona o por recurso.",
  'avvio.d-fornitori': "¿Compras a proveedores?",
  'avvio.a-fornitori': "Ficha de proveedores y, si tienes almacén, los pedidos con la entrada de mercancía.",
  'avvio.d-fatture': "¿Emites facturas?",
  'avvio.a-fatture': "Numeradas por año, con IVA, vencimientos y el archivo de la factura electrónica.",
  'avvio.d-persone': "¿Cuántas personas usarán Kubo?",
  'avvio.o-persone-solo': "Solo yo",
  'avvio.o-persone-poche': "De 2 a 5",
  'avvio.o-persone-molte': "Más de 5",
  'avvio.d-squadra': "¿Quién trabaja contigo?",
  'avvio.a-squadra': "Cada uno entra con su email y ve lo que necesita para su rol. También se puede hacer después.",
  'avvio.d-lumi': "¿Quieres a Lumi, el asistente?",
  'avvio.a-lumi': "Le pides las cosas con palabras: «¿cuánto he vendido esta semana?», «añade la talla a los artículos». Él propone, tú confirmas.",
  'avvio.d-esempi': "¿Quieres ver Kubo con datos de ejemplo?",
  'avvio.a-esempi': "Clientes, ventas y citas ficticios pero creíbles, para probarlo todo. Se borran con un clic.",
  'avvio.o-si': "Sí",
  'avvio.o-no': "No",
  'avvio.collaboratore': "Colaborador (ve y edita, no elimina)",
  'avvio.lettura': "Solo lectura",
  'avvio.nome': "Nombre",
  'avvio.ruolo': "Rol",
  'avvio.togli': "Quitar",
  'avvio.altra-persona': "+ Otra persona",
  'avvio.password-provvisoria': "Cada uno recibe una contraseña provisional, que verás al final.",
  'avvio.sezioni': "Te preparo estas secciones",
  'avvio.nessuna-sezione': "Ninguna: empiezas de cero",
  'avvio.campi-spenti': { one: "{n} campo que no necesitas queda desactivado (se reactiva desde {personalizza})", other: "{n} campos que no necesitas quedan desactivados (se reactivan desde {personalizza})" },
  'avvio.persone-ruolo': { one: "Una persona con su rol", other: "{n} personas, cada una con su rol" },
  'avvio.lumi-acceso': "Lumi encendido",
  'avvio.lumi-spento': "Lumi apagado (lo enciendes cuando quieras)",
  'avvio.con-esempi': "Con datos de ejemplo, que se quitan con un clic",
  'avvio.senza-esempi': "Sin datos de ejemplo",
  'avvio.ci-siamo': "Ya casi está",
  'avvio.chi-sei': "Una última cosa: quién eres. Serás el titular, el que puede hacerlo todo.",
  'avvio.preparo': "Preparando Kubo…",
  'avvio.prepara': "Preparar Kubo",
  'avvio.pronto': "Kubo está listo",
  'avvio.consegna': "Da a cada uno su contraseña provisional. Esta pantalla no se vuelve a ver: cópialas ahora.",
  'avvio.entra': "Entrar en Kubo",
  'avvio.tappa-sezioni': "Tus secciones",
  'avvio.tappa-sezioni-testo': "Aquí está todo el software{esempi}. Cada sección es una lista que puedes buscar, filtrar, ordenar y ver en columnas.",
  'avvio.tappa-personalizza-testo': "¿Falta un campo? ¿Sobra alguno? Desde aquí añades, renombras y mueves campos sin perder nunca un dato. Las secciones nuevas se crean desde «{nuova}».",
  'avvio.tappa-lumi-testo': "Pide con palabras: «¿cuánto he vendido esta semana?», «añade la talla a los artículos». Lumi lee con tus permisos y propone; tú decides.",
  'avvio.tappa-cruscotto': "El panel",
  'avvio.tappa-cruscotto-testo': "Las cifras que importan y lo que requiere atención, al día mientras trabajas. Se cambia con «{modifica}», arriba.",
  'avvio.n-di': "{n} de {tot}",
  'avvio.salta': "Saltar",
  'avvio.capito': "Entendido",
  'avvio.promemoria': "Estás viendo datos de ejemplo",
  'avvio.toglili': "Quitarlos",
  'avvio.conferma-togli': "¿Quito todos los datos de ejemplo? Lo que has añadido tú se queda.",
  'avvio.tolte': { one: "{n} fila de ejemplo quitada", other: "{n} filas de ejemplo quitadas" },
  'avvio.aggiunte': { one: "{n} fila de ejemplo añadida", other: "{n} filas de ejemplo añadidas" },
  'avvio.togli-esempi': "Quitar los datos de ejemplo",
  'avvio.rimetti-esempi': "Volver a poner los datos de ejemplo",
  'avvio.pagina-titolo': "Datos de ejemplo y recorrido guiado",
  'avvio.ci-sono': { one: "Hay {n} fila de ejemplo, para probar Kubo sin miedo. Cuando estés listo, quítala: desaparece (aunque la hayas retocado), lo que has introducido tú se queda y, donde aún no hay nada tuyo, la numeración vuelve a empezar desde 1.", other: "Hay {n} filas de ejemplo: clientes, movimientos y citas ficticios, para probar Kubo sin miedo. Cuando estés listo, quítalas: desaparecen todas (también las que has retocado), lo que has introducido tú se queda y, donde aún no hay nada tuyo, la numeración vuelve a empezar desde 1." },
  'avvio.solo-titolare': "Solo el titular puede quitarlos.",
  'avvio.nessun-esempio': "No hay datos de ejemplo.",
  'avvio.rivedere': "¿Quieres volver a ver dónde está cada cosa?",
  'avvio.rifai-giro': "Repetir el recorrido guiado",
  'avvio.lato': "Datos de ejemplo y recorrido",
  'avvio.lato-sezione': "Primeros pasos",
};
