export default {
  'comune.benvenuto': 'Te damos la bienvenida a Kubo',
  'comune.benvenuto-sotto': 'El software de gestión que montas a tu manera. Empieza con una plantilla y luego cambia todo lo que quieras.',
  'comune.nome-azienda': 'Nombre de la empresa',
  'comune.tuo-nome': 'Tu nombre',
  'comune.email': 'Email',
  'comune.password': 'Contraseña',
  'comune.password-nuova': 'Contraseña (al menos 8 caracteres)',
  'comune.valuta': 'Moneda',
  'comune.da-dove': '¿Por dónde empezamos? (luego puedes añadir más)',
  'comune.codice-avvio': "Código de inicio (aparece en la terminal o en el registro donde se ejecuta Kubo)",
  'comune.codice-avvio-es': "p. ej. 3FA9C2D1",
  'comune.inizia': 'Empezar',
  'comune.lingua': 'Idioma',
  'comune.accedi-per': 'Inicia sesión para continuar.',
  'comune.accedi': 'Iniciar sesión',
  'comune.gestione': 'Gestión',
  'comune.nuova-sezione': 'Nueva sección',
  'comune.persone-permessi': 'Personas y permisos',
  'comune.esci': 'Cerrar sesión',
  'comune.personalizza': 'Personalizar',
  'comune.personalizza-sezione': 'Personalizar esta sección',
  'comune.nessuna-sezione': 'Todavía no hay secciones.',
  'comune.creane-una': 'Crea una',
  'comune.chiedi-titolare': 'Pide al titular que cree una.',
  'comune.qualcosa-non-va': 'Algo ha fallado',
  'comune.errore-n': 'Error {stato}',
  'comune.percento': '{n} %',
  'comune.si': 'Sí',
  'comune.no': 'No',
  'comune.si-min': 'sí',
  'comune.no-min': 'no',
  'comune.su': 'Subir',
  'comune.giu': 'Bajar',
  'comune.togli': 'Quitar',
  'comune.cerca': 'Buscar…',
  'comune.carico': 'Cargando…',
  'comune.avviso-esempi-aggiunti': "Datos de ejemplo añadidos",
  'comune.avviso-esempi-tolti': "Datos de ejemplo eliminados",
};
