export default {
  'connettori.terzi': "Un conector de terceros se copia en la carpeta «connettori» junto a los datos: lo enciendes aquí tras comprobar su suma.",
  'connettori.locale': "Instalado a mano",
  'connettori.rotto': "El conector no se carga: revisa el archivo connettore.js",
  'connettori.stato-acceso': "Encendido",
  'connettori.stato-spento': "Apagado",
  'connettori.stato-incompleto': "Por completar",
  'connettori.stato-cambiato': "Cambiado",
  'connettori.stato-rotto': "Roto",
  'connettori.mancano': "Falta todavía: {cosa}",
  'connettori.cambiato': "El archivo del conector cambió después de encenderlo: está parado hasta que lo vuelvas a encender comprobando la suma.",
  'connettori.accendi': "Encender",
  'connettori.spegni': "Apagar",
  'connettori.accendi-titolo': "¿Encender {nome}?",
  'connettori.potra': "Podrá:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "leer",
  'connettori.p-crea': "crear",
  'connettori.p-modifica': "modificar",
  'connettori.p-elimina': "eliminar",
  'connettori.somma': "Suma de control (SHA-256) del archivo: compárala con la que publicó su autor.",
  'connettori.da-approvare': "El código de este conector aún no se ha ejecutado: Kubo lo carga solo después de que confirmes la suma de abajo. Luego verás las secciones que puede usar.",
  'connettori.impostazioni': "Ajustes",
  'connettori.salvato-segreto': "Guardado",
  'connettori.cambia': "Cambiar",
  'connettori.togli': "Quitar",
  'connettori.interni': "Permitir direcciones de la red interna (un servidor en la tienda, una caja registradora)",
  'connettori.salva': "Guardar",
  'connettori.salvato': "Guardado",
  'connettori.prova': "Probar la conexión",
  'connettori.provo': "Probando…",
  'connettori.prova-ok': "Conexión correcta",
  'connettori.prova-no': "No funciona: {motivo}",
  'connettori.collegamento': "Conexión",
  'connettori.webhook': "Dirección del webhook",
  'connettori.webhook-aiuto': "Pégala en los ajustes de webhooks del servicio.",
  'connettori.indirizzo-segreto': "Dirección secreta",
  'connettori.indirizzo-aiuto': "Quien tenga esta dirección ve los datos: dásela solo a quien la necesite.",
  'connettori.account': "Cuenta",
  'connettori.collegato': "Conectada",
  'connettori.scollegato': "No conectada",
  'connettori.scade': "Caduca {quando}",
  'connettori.collega': "Conectar la cuenta",
  'connettori.ricollega': "Volver a conectar",
  'connettori.oauth-ok': "Cuenta conectada",
  'connettori.oauth-scaduto': "La conexión caducó: inténtalo de nuevo",
  'connettori.oauth-errore': "La conexión falló: mira el registro",
  'connettori.abbinamenti': "Correspondencia de campos",
  'connettori.abbinamenti-aiuto': "Los campos del conector y los de Kubo: si renombras un campo, la correspondencia se mantiene.",
  'connettori.sezione-manca': "Falta la sección «{nome}»",
  'connettori.facoltativo': "opcional",
  'connettori.salva-abbinamenti': "Guardar las correspondencias",
  'connettori.sincronizzazioni': "Sincronizaciones",
  'connettori.ogni': "cada {ogni}",
  'connettori.alle': "a las {alle}",
  'connettori.ultimo': "Última ejecución: {quando}",
  'connettori.prossimo': "próxima: {quando}",
  'connettori.sincronizza': "Sincronizar ahora",
  'connettori.giro-ok': "Hecho",
  'connettori.coda': "En cola: {attesa} · fallidas: {fallite}",
  'connettori.riprova': "Reintentar las fallidas",
  'connettori.registro': "Registro",
  'connettori.registro-vuoto': "Aún nada: aquí ves lo que llega y lo que sale.",
  'connettori.col-quando': "Cuándo",
  'connettori.col-verso': "Dirección",
  'connettori.col-esito': "Resultado",
  'connettori.col-cosa': "Qué",
  'connettori.verso-entrata': "entrante",
  'connettori.verso-uscita': "saliente",
  'connettori.verso-giro': "tarea programada",
  'connettori.verso-azione': "acción",
  'connettori.verso-prova': "prueba",
  'connettori.verso-oauth': "cuenta",
  'connettori.verso-sistema': "sistema",
  'connettori.esito-ok': "ok",
  'connettori.esito-errore': "error",
  'connettori.esito-avviso': "aviso",
  'connettori.esito-ignorato': "ignorado",
  'connettori.copia': "Copiar",
  'connettori.copiato': "Copiado",
  'connettori.annulla': "Cancelar",
  'connettori.conferma': "Confirmar",
  'connettori.fatto': "Hecho",
  // la libreria delle integrazioni e le ricette
  'connettori.libreria': "Biblioteca de integraciones",
  'connettori.libreria-sotto': "{n} integraciones · {accese} activas. Las claves quedan cifradas en Kubo y nunca vuelven al navegador.",
  'connettori.cerca': "Buscar: Stripe, factura, WhatsApp, envíos…",
  'connettori.categorie': "Categorías",
  'connettori.tutte': "Todas",
  'connettori.trovate': "{n} encontradas",
  'connettori.le-tue': "Activas",
  'connettori.nessuna': "No se ha encontrado ninguna integración.",
  'connettori.prova-http': "¿No está? Conéctalo con HTTP / API REST",
  'connettori.smanettoni': "Para los curiosos: la API de Kubo está descrita en OpenAPI 3.1 en /api/openapi-3.1.json, y un conector nuevo es una carpeta con un archivo (docs/CONNETTORI.md).",
  'connettori.f-gratis': "Gratis",
  'connettori.f-facili': "Fáciles",
  'connettori.f-italia': "Italia",
  'connettori.stato-da-approvare': "Por aprobar",
  'connettori.cat-pagamenti': "Pagos",
  'connettori.cat-cassa': "Caja y TPV",
  'connettori.cat-negozi-online': "Tiendas online",
  'connettori.cat-marketplace': "Marketplaces",
  'connettori.cat-fatturazione': "Facturación",
  'connettori.cat-contabilita': "Contabilidad",
  'connettori.cat-banche': "Bancos",
  'connettori.cat-spedizioni': "Envíos",
  'connettori.cat-whatsapp': "WhatsApp",
  'connettori.cat-messaggi': "Mensajería",
  'connettori.cat-email': "Email",
  'connettori.cat-sms': "SMS",
  'connettori.cat-calendario': "Calendario",
  'connettori.cat-prenotazioni': "Reservas",
  'connettori.cat-archivio': "Archivo y ficheros",
  'connettori.cat-produttivita': "Productividad",
  'connettori.cat-marketing': "Marketing",
  'connettori.cat-recensioni': "Reseñas",
  'connettori.cat-firma': "Firma",
  'connettori.cat-dati-aziende': "Datos de empresas",
  'connettori.cat-automazione': "Automatización",
  'connettori.cat-ia': "Inteligencia artificial",
  'connettori.cat-altro': "Otros",
  'connettori.costo-gratis': "Gratis",
  'connettori.costo-a-consumo': "Según uso",
  'connettori.costo-abbonamento': "Suscripción",
  'connettori.costo-contratto': "Con contrato",
  'connettori.diff-facile': "Fácil",
  'connettori.diff-media': "Media",
  'connettori.diff-difficile': "Para expertos",
  'connettori.zona-IT': "Italia",
  'connettori.zona-UE': "Europa",
  'connettori.zona-mondo': "Mundo",
  'connettori.prova-finto': "Probado con un servicio simulado",
  'connettori.prova-vero': "Probado con el servicio real",
  'connettori.prova-finto-aiuto': "Las pruebas automáticas usan un servicio simulado que responde como el real, según la documentación de las fuentes: antes de confiar en él, pruébalo en modo test.",
  'connettori.prova-vero-aiuto': "Este conector también se ha probado con el servicio real.",
  'connettori.sito': "Web del servicio",
  'connettori.apri': "Abrir",
  'connettori.cosa-serve': "Qué necesitas",
  'connettori.passi': "Paso a paso",
  'connettori.costo': "Coste",
  'connettori.difficolta': "Dificultad",
  'connettori.fonti': "Fuentes ({n})",
  'connettori.permessi-titolo': "Qué podrá tocar",
  'connettori.nessun-permesso': "Ninguna sección de Kubo: solo las llamadas que configures.",
  'connettori.r-nessuna': "Todavía no hay recetas. Añade una:",
  'connettori.r-tipo-uscita': "Saliente: cuando cambia una fila",
  'connettori.r-tipo-azione': "Botón en la ficha y Lumi",
  'connettori.r-tipo-entrata': "Entrante: el servicio escribe en Kubo",
  'connettori.r-nome': "Nombre de la receta",
  'connettori.r-attiva': "Activa",
  'connettori.r-sezione': "Sección",
  'connettori.r-eventi': "Cuando la fila se",
  'connettori.ev-crea': "crea",
  'connettori.ev-modifica': "modifica",
  'connettori.ev-elimina': "elimina",
  'connettori.ev-ripristina': "restaura",
  'connettori.r-metodo': "Método",
  'connettori.r-percorso': "Ruta (tras la dirección base) o dirección completa",
  'connettori.r-indirizzo': "Dirección que te da la plataforma (https://…)",
  'connettori.r-corpo': "Cuerpo (JSON con marcadores; vacío = toda la fila)",
  'connettori.r-segnaposto': "Marcadores: {campi}",
  'connettori.r-scrive': "Muestra la vista previa y pide confirmación antes de enviar",
  'connettori.r-modo': "Si la fila ya existe",
  'connettori.modo-crea-o-aggiorna': "actualízala, si no créala",
  'connettori.modo-crea': "crea siempre una fila nueva",
  'connettori.modo-aggiorna': "solo actualizar",
  'connettori.r-chiave': "Campo clave (para encontrar la fila)",
  'connettori.r-elenco': "Lista en el JSON (opcional, p. ej. items)",
  'connettori.r-idevento': "Id del evento en el JSON (opcional, contra duplicados)",
  'connettori.r-campi': "Correspondencias (vacío = las claves del JSON con los mismos nombres que los campos)",
  'connettori.r-da': "Ruta en el JSON (p. ej. cliente.email)",
  'connettori.r-a': "Campo de Kubo",
  'connettori.r-aggiungi-campo': "Añadir una correspondencia",
  'connettori.r-indirizzo-entrata': "Dirección para el servicio (POST JSON)",
  'connettori.r-salva-prima': "Guarda y activa para ver la dirección.",
  'connettori.copia': "Conectar otro servicio así",
  'connettori.copia-aiuto': "Un segundo servicio con su dirección, su autenticación y sus recetas.",
  'connettori.copia-nome': "Nombre del servicio (p. ej. CRM)",
  'connettori.copia-crea': "Crear",
  'connettori.copia-di': "Copia de «{nome}»",
  'connettori.togli-copia': "Quitar este servicio",
  'connettori.togli-copia-conferma': "¿Quitar «{nome}» con sus ajustes, secretos y registro?",
  'connettori.tutte-lettura': "Todas las secciones (solo lectura)",
  'connettori.tutte-sezioni': "Todas las secciones",
  'connettori.dispositivo': "Conectar con un código",
  'connettori.dispositivo-titolo': "Conectar {nome} con un código",
  'connettori.dispositivo-passi': "Abre la dirección de abajo (también desde el móvil), entra en el servicio y escribe este código. Kubo lo comprueba solo cada pocos segundos: puedes dejar esta ventana abierta.",
  'connettori.dispositivo-attesa': "Esperando la confirmación…",
  'connettori.dispositivo-scaduto': "El código ha caducado o se cerró la ventana: pulsa de nuevo «Conectar con un código».",
  'connettori.dispositivo-chiudi': "Cerrar",
  'connettori.ritorno': "Dirección de retorno (regístrala en el servicio)",
  'connettori.pubblico-titolo': "Dirección pública de Kubo",
  'connettori.pubblico-aiuto': "La dirección con la que los servicios llegan a Kubo desde internet (p. ej. https://kubo.tienda.es). La usan los webhooks y los retornos de todos los conectores; vacía = la del navegador.",
  'connettori.pubblico-salvato': "Dirección guardada",
  'connettori.r-con-accesso': "Enviar la clave o el token aunque la dirección esté en otro sitio",
};
