export default {
  'connettori.titolo': "Conectores",
  'connettori.spiega': "Conecta Kubo con los servicios que ya usas: pagos, tienda online, facturación electrónica, correo, calendario. Las claves quedan cifradas en Kubo y nunca vuelven al navegador.",
  'connettori.terzi': "Un conector de terceros se copia en la carpeta «connettori» junto a los datos: lo enciendes aquí tras comprobar su suma.",
  'connettori.ufficiale': "Oficial",
  'connettori.locale': "Instalado a mano",
  'connettori.rotto': "El conector no se carga: revisa el archivo connettore.js",
  'connettori.stato-acceso': "Encendido",
  'connettori.stato-spento': "Apagado",
  'connettori.stato-incompleto': "Por completar",
  'connettori.stato-cambiato': "Cambiado",
  'connettori.stato-rotto': "Roto",
  'connettori.mancano': "Falta todavía: {cosa}",
  'connettori.cambiato': "El archivo del conector cambió después de encenderlo: está parado hasta que lo vuelvas a encender comprobando la suma.",
  'connettori.accendi': "Encender",
  'connettori.spegni': "Apagar",
  'connettori.accendi-titolo': "¿Encender {nome}?",
  'connettori.potra': "Podrá:",
  'connettori.permesso': "{sezione}: {cosa}",
  'connettori.p-leggi': "leer",
  'connettori.p-crea': "crear",
  'connettori.p-modifica': "modificar",
  'connettori.p-elimina': "eliminar",
  'connettori.somma': "Suma de control (SHA-256) del archivo: compárala con la que publicó su autor.",
  'connettori.da-approvare': "El código de este conector aún no se ha ejecutado: Kubo lo carga solo después de que confirmes la suma de abajo. Luego verás las secciones que puede usar.",
  'connettori.impostazioni': "Ajustes",
  'connettori.salvato-segreto': "Guardado",
  'connettori.cambia': "Cambiar",
  'connettori.togli': "Quitar",
  'connettori.interni': "Permitir direcciones de la red interna (un servidor en la tienda, una caja registradora)",
  'connettori.salva': "Guardar",
  'connettori.salvato': "Guardado",
  'connettori.prova': "Probar la conexión",
  'connettori.provo': "Probando…",
  'connettori.prova-ok': "Conexión correcta",
  'connettori.prova-no': "No funciona: {motivo}",
  'connettori.collegamento': "Conexión",
  'connettori.webhook': "Dirección del webhook",
  'connettori.webhook-aiuto': "Pégala en los ajustes de webhooks del servicio.",
  'connettori.indirizzo-segreto': "Dirección secreta",
  'connettori.indirizzo-aiuto': "Quien tenga esta dirección ve los datos: dásela solo a quien la necesite.",
  'connettori.account': "Cuenta",
  'connettori.collegato': "Conectada",
  'connettori.scollegato': "No conectada",
  'connettori.scade': "Caduca {quando}",
  'connettori.collega': "Conectar la cuenta",
  'connettori.ricollega': "Volver a conectar",
  'connettori.oauth-ok': "Cuenta conectada",
  'connettori.oauth-scaduto': "La conexión caducó: inténtalo de nuevo",
  'connettori.oauth-errore': "La conexión falló: mira el registro",
  'connettori.abbinamenti': "Correspondencia de campos",
  'connettori.abbinamenti-aiuto': "Los campos del conector y los de Kubo: si renombras un campo, la correspondencia se mantiene.",
  'connettori.sezione-manca': "Falta la sección «{nome}»",
  'connettori.facoltativo': "opcional",
  'connettori.salva-abbinamenti': "Guardar las correspondencias",
  'connettori.sincronizzazioni': "Sincronizaciones",
  'connettori.ogni': "cada {ogni}",
  'connettori.alle': "a las {alle}",
  'connettori.ultimo': "Última ejecución: {quando}",
  'connettori.prossimo': "próxima: {quando}",
  'connettori.sincronizza': "Sincronizar ahora",
  'connettori.giro-ok': "Hecho",
  'connettori.coda': "En cola: {attesa} · fallidas: {fallite}",
  'connettori.riprova': "Reintentar las fallidas",
  'connettori.registro': "Registro",
  'connettori.registro-vuoto': "Aún nada: aquí ves lo que llega y lo que sale.",
  'connettori.col-quando': "Cuándo",
  'connettori.col-verso': "Dirección",
  'connettori.col-esito': "Resultado",
  'connettori.col-cosa': "Qué",
  'connettori.verso-entrata': "entrante",
  'connettori.verso-uscita': "saliente",
  'connettori.verso-giro': "tarea programada",
  'connettori.verso-azione': "acción",
  'connettori.verso-prova': "prueba",
  'connettori.verso-oauth': "cuenta",
  'connettori.verso-sistema': "sistema",
  'connettori.copia': "Copiar",
  'connettori.copiato': "Copiado",
  'connettori.annulla': "Cancelar",
  'connettori.conferma': "Confirmar",
  'connettori.fatto': "Hecho",
};
