// Area «desktop» (web/moduli/desktop.js): rete, backup e versioni nuove.
export default {
  'desktop.tipo-giornaliero': "Diaria",
  'desktop.tipo-modifica': "Antes de un cambio",
  'desktop.tipo-manuale': "Manual",
  'desktop.tipo-sicurezza': "Antes de una restauración",
  'desktop.tipo-caricato': "Subida desde fuera",
  'desktop.qr': "Código QR con la dirección",
  'desktop.rete-titolo': "Conecta otros dispositivos",
  'desktop.lato-rete': "Conectar dispositivos",
  'desktop.un-momento': "Un momento…",
  'desktop.copiato': "Copiado",
  'desktop.copia-fallita': "No se pudo copiar: selecciónalo a mano",
  'desktop.indirizzo': "Dirección",
  'desktop.altra-rete': "O bien, en otra red de la oficina",
  'desktop.copia-indirizzo': "Copiar la dirección",
  'desktop.codice': "Código",
  'desktop.passo-telefono': "Móvil o tableta:",
  'desktop.passo-telefono-testo': "enfoca el código con la cámara y toca el enlace.",
  'desktop.passo-computer': "Otro ordenador:",
  'desktop.passo-computer-codice': "abre el navegador y escribe la dirección. Con la app de Lumi, elige «Conectarse a Lumi en red» y escribe el código.",
  'desktop.passo-computer-indirizzo': "abre el navegador y escribe la dirección. Con la app de Lumi, elige «Conectarse a Lumi en red» y escribe la dirección.",
  'desktop.solo-qui': "Ahora Lumi solo responde a este ordenador.",
  'desktop.apri-rete': "Para usarlo también desde otros dispositivos, en la app de Lumi abre el menú de la barra superior (o del área de notificaciones) y activa «Abierto a la red local».",
  'desktop.da-terminale': "Si lo arrancas desde la terminal:",
  'desktop.non-in-rete': "Este ordenador no parece conectado a ninguna red. Conéctalo al wifi o al cable de la oficina y recarga la página.",
  'desktop.stessa-rete': "Los otros dispositivos tienen que estar en la misma red (el mismo wifi o el mismo cable). Si no se conectan, comprueba que el cortafuegos de este ordenador deje pasar a Lumi.",
  'desktop.backup': "Copias de seguridad",
  'desktop.fai-adesso': "Hacer una copia ahora",
  'desktop.copia-in-corso': "Copiando…",
  'desktop.fatto': "Copia hecha",
  'desktop.ultimo': "Última copia",
  'desktop.nessuno-ancora': "Ninguna todavía",
  'desktop.copie-tenute': "Copias guardadas",
  'desktop.in-tutto': "{peso} en total",
  'desktop.spiega-automatici': "Cada día Lumi hace por su cuenta una copia de la base de datos, y otra antes de cada cambio en la estructura o de cada importación. Guarda {giornalieri} copias diarias, {settimanali} semanales y {mensili} mensuales; las que haces a mano se quedan hasta que las borres. Los adjuntos van a la carpeta «allegati», copiando solo los nuevos.",
  'desktop.spiega-spenti': "Las copias automáticas están desactivadas (LUMI_BACKUP=0): acuérdate de hacerlas a mano o con tus herramientas.",
  'desktop.cartella-esempio': "Por ejemplo {a} o {b}",
  'desktop.cartella-nuova': "A partir de ahora las copias van ahí",
  'desktop.cartella-tornata': "Las copias vuelven junto a los datos",
  'desktop.scegli-cartella': "Elige una carpeta…",
  'desktop.dove': "Dónde van las copias",
  'desktop.in-memoria': "(base de datos en memoria: sin copias)",
  'desktop.nota-esterna': "Una carpeta elegida por ti. Si el disco no está conectado, la copia del día va junto a los datos y aquí aparece un aviso.",
  'desktop.nota-accanto': "Junto a los datos, en este ordenador. Mejor una segunda copia en otro sitio: un disco externo o una carpeta sincronizada (Dropbox, OneDrive, iCloud, Google Drive).",
  'desktop.usa-cartella': "Usar esta carpeta",
  'desktop.torna-accanto': "Volver junto a los datos",
  'desktop.vuoto': "Todavía no hay copias. La primera llega sola en pocos minutos, o hazla ahora.",
  'desktop.col-quando': "Cuándo",
  'desktop.col-tipo': "Tipo",
  'desktop.col-dimensione': "Tamaño",
  'desktop.accanto-ai-dati': "junto a los datos",
  'desktop.scarica': "Descargar",
  'desktop.ripristina': "Restaurar",
  'desktop.elimina': "Borrar esta copia",
  'desktop.elimina-conferma': "¿Borrar la copia del {quando}? Ya no se podrá restaurar.",
  'desktop.eliminato': "Copia borrada",
  'desktop.ripristino-titolo': "¿Volver a esta copia?",
  'desktop.ripristino-prima': "Todo volverá a estar como el",
  'desktop.ripristino-dopo': ". Todo lo que se hizo después desaparece de la vista.",
  'desktop.ripristino-nota': "Antes, Lumi hace una copia de cómo está todo ahora («{tipo}»): si cambias de idea, restauras esa y no pierdes nada. Quien esté trabajando en otros dispositivos verá que la página se recarga.",
  'desktop.capito': "Entendido, quiero volver a ese momento",
  'desktop.annulla': "Cancelar",
  'desktop.ripristino-in-corso': "Restaurando…",
  'desktop.ripristinato': "Restaurado",
  'desktop.ripristinato-altro': "El titular ha restaurado una copia: recargando…",
  'desktop.caricato': "Copia subida: {azienda}, {persone}, {sezioni}. La tienes al principio de la lista.",
  'desktop.persone': {"one": "{n} persona", "other": "{n} personas"},
  'desktop.sezioni': {"one": "{n} sección", "other": "{n} secciones"},
  'desktop.carica': "Subir una copia",
  'desktop.carica-nota': "Un archivo .db descargado desde aquí, también desde otro ordenador. Lumi lo comprueba y lo pone en la lista: luego decides tú si restaurarlo.",
  'desktop.scegli-file': "Elegir el archivo…",
  'desktop.uscita-versione': "Hay una versión nueva:",
  'desktop.novita': "novedades",
  'desktop.aggiornato': "Tienes la última versión.",
  'desktop.versioni': "Versiones nuevas",
  'desktop.stai-usando': "Estás usando Lumi",
  'desktop.controlla-ogni-giorno': "Comprobar cada día si hay una versión nueva y avisarme",
  'desktop.versioni-nota': "Lumi solo pregunta a GitHub el número de la última versión publicada: no envía datos de la empresa ni instala nada por su cuenta. Actualizas tú cuando quieras, después de hacer una copia.",
  'desktop.controlla-adesso': "Comprobar ahora",
  'desktop.avviso-versione': "Nueva versión de Lumi:",
  'desktop.dettagli': "Detalles",
  'desktop.chiudi': "Cerrar",
  'desktop.solo-titolare': "Las copias de seguridad las gestiona el titular.",
};
