// E-invoices (web/moduli/fatture.js): received invoices, virtual stamp duty, numbering.
export default {
  'fatture.aggiorna-chiedi': "Las facturas de Kubo han crecido: precios con hasta 8 decimales, caja de previsión, Administración Pública, facturas recibidas. ¿Añado ahora los campos nuevos? No se pierde ningún dato.",
  'fatture.aggiornato': "Facturas actualizadas",
  'fatture.bloccata': "Emitida · bloqueada",
  'fatture.bloccata-nota': "Una factura emitida ya no se modifica: se corrige con una nota de crédito o de débito. Puedes cambiar el estado del pago y las notas internas.",
  'fatture.bollo': "Timbre virtual",
  'fatture.bollo-nota': "El timbre se paga con el F24 (códigos 2521-2524) o desde el área reservada de la Agencia Tributaria, que cada trimestre calcula el importe. Cuentan las facturas emitidas con el timbre marcado.",
  'fatture.chiudi': "Cerrar",
  'fatture.codice-tributo': "Código de tributo",
  'fatture.crea-integrazione': "Crear integración",
  'fatture.da-integrare': "Por integrar",
  'fatture.da-pagare': "Por pagar",
  'fatture.da-versare': "A ingresar",
  'fatture.emesse': "Emitidas",
  'fatture.entro': "Antes del",
  'fatture.fatture-con-bollo': "Facturas con timbre",
  'fatture.fornitore-nuovo': "nuevo",
  'fatture.gia-importata': "{numero} ya estaba",
  'fatture.importa': "Importar facturas",
  'fatture.importata': "{numero} del {data} · {totale}",
  'fatture.integra-conferma': "¿Creo la integración (o autofactura) de la factura {numero}? Nace como borrador: la revisas y la emites tú.",
  'fatture.integra-nota': "Factura recibida con inversión del sujeto pasivo o de un proveedor extranjero: necesita la integración TD16-TD19.",
  'fatture.integrazione-creata': "Integración {tipo} creada como borrador",
  'fatture.intestata-ad-altri': "no está a nombre de tu NIF-IVA",
  'fatture.leggo': "Leyendo…",
  'fatture.manca-modello': "Añade primero el modelo «Facturas y factura electrónica».",
  'fatture.mancano': "Números que faltan",
  'fatture.nessun-buco': "sin huecos",
  'fatture.nessuna-emessa': "Ninguna factura emitida este año.",
  'fatture.niente-da-integrare': "Nada que integrar.",
  'fatture.niente-da-pagare': "Nada que pagar.",
  'fatture.numerazione': "Numeración",
  'fatture.numerazione-nota': "Los números van seguidos por serie y año, sin huecos. Un hueco suele venir de una factura introducida a mano: revísalo antes de emitir la siguiente.",
  'fatture.ricevute': "Recibidas",
  'fatture.ricevute-nota': "Descarga las facturas del buzón fiscal o de la PEC y arrástralas aquí: también las .p7m firmadas y los archivos con varias facturas. Kubo crea el proveedor y registra el gasto y el vencimiento.",
  'fatture.serie': "Serie",
  'fatture.serie-principale': "principal",
  'fatture.solo-xml': "Solo archivos .xml o .p7m",
  'fatture.stampa': "Imprimir",
  'fatture.titolo': "Facturas electrónicas",
  'fatture.totale': "Total",
  'fatture.trascina': "Arrastra aquí las facturas recibidas",
  'fatture.trascina-nota': "o toca para elegir los archivos (.xml, .xml.p7m)",
  'fatture.trimestre': "Trimestre",
  'fatture.trimestre-n': "{n}.º trimestre",
  'fatture.troppo-grande': "Archivo demasiado grande (5 MB como máximo)",
  'fatture.tutte-le-ricevute': "Todas las facturas recibidas →",
  'fatture.ultimo': "Último",
  'fatture.vedi': "Ver la factura",
  'fatture.vista': "Factura recibida",
};
