// Impuestos (web/moduli/fisco.js).
export default {
  'fisco.titolo': "Impuestos",
  'fisco.anno': "Año",
  'fisco.responsabilita': "Lumi calcula y prepara con los datos de tu gestión: revisa antes de pagar o presentar. La responsabilidad sigue siendo del contribuyente.",
  'fisco.scheda-riepilogo': "A pagar",
  'fisco.scheda-iva': "IVA",
  'fisco.scheda-forfettario': "Tanto alzado",
  'fisco.scheda-f24': "F24",
  'fisco.scheda-ritenute': "Retenciones",
  'fisco.scheda-scadenze': "Vencimientos",
  'fisco.scheda-commercialista': "Para el asesor",
  'fisco.scheda-impostazioni': "Ajustes",
  'fisco.da-pagare-anno': "Pendiente de pago este año",
  'fisco.prossimo': "Próximo pago",
  'fisco.niente': "Nada a la vista.",
  'fisco.regime': "Régimen",
  'fisco.coeff': "coeficiente {n}%",
  'fisco.regime-forfettario': "A tanto alzado (forfettario)",
  'fisco.regime-semplificato': "Simplificado",
  'fisco.regime-ordinario': "Ordinario",
  'fisco.periodicita-trimestrale': "IVA trimestral",
  'fisco.periodicita-mensile': "IVA mensual",
  'fisco.manca-ricevute': "Para el IVA de las compras y las retenciones, añade la sección «Facturas recibidas».",
  'fisco.apri-impostazioni': "Abrir los ajustes",
  'fisco.prossimi-versamenti': "Próximos pagos",
  'fisco.data': "Fecha",
  'fisco.cosa': "Qué",
  'fisco.codice': "Código",
  'fisco.anno-rif': "Año ref.",
  'fisco.importo': "Importe",
  'fisco.vedi-f24': "F24",
  'fisco.prossime-scadenze': "Próximos vencimientos",
  'fisco.mese-n': "Mes {n}",
  'fisco.trimestre-n': "{n}.º trimestre",
  'fisco.lipe-trimestre': "LIPE {n}.º trimestre",
  'fisco.liquidazioni': "Liquidaciones periódicas",
  'fisco.periodo': "Periodo",
  'fisco.iva-vendite': "IVA ventas",
  'fisco.iva-acquisti': "IVA deducible",
  'fisco.riporti': "Arrastres",
  'fisco.interessi': "Intereses 1%",
  'fisco.da-versare': "A pagar",
  'fisco.scadenza': "Vence",
  'fisco.a-credito': "a favor {importo}",
  'fisco.riportato': "se arrastra (hasta 100 €)",
  'fisco.acconto-dicembre': "Anticipo de IVA de diciembre",
  'fisco.acconto-dovuto': "Anticipo de {importo} con el método {metodo}: código {codice}, antes del {data}.",
  'fisco.acconto-no': "Anticipo no debido (menos de 103,29 € o faltan datos: añádelos en los ajustes).",
  'fisco.acconto-nota': "Histórico: 88% de lo pagado por el último periodo del año pasado. Previsional: 88% de lo que prevés para el último periodo de este año. Lumi elige el menor.",
  'fisco.metodo-storico': "histórico",
  'fisco.metodo-previsionale': "previsional",
  'fisco.lipe': "Comunicación de liquidaciones periódicas (LIPE)",
  'fisco.lipe-passo-1': "Descarga arriba el archivo XML del trimestre.",
  'fisco.lipe-passo-2': "Entra en «Fatture e Corrispettivi» en la web de la Agenzia delle Entrate con SPID, CIE o CNS.",
  'fisco.lipe-passo-3': "Abre el servicio de liquidaciones periódicas de IVA y elige enviar un archivo ya preparado.",
  'fisco.lipe-passo-4': "Sube el archivo y confirma: el sistema lo revisa enseguida.",
  'fisco.lipe-passo-5': "Descarga el acuse a los pocos minutos y guárdalo.",
  'fisco.lipe-nota': "Plazos: 31 de mayo, 30 de septiembre, 30 de noviembre y final de febrero. Si algo no cuadra, la precompilada de la Agencia ayuda a comparar.",
  'fisco.registri': "Libros de IVA",
  'fisco.registri-nota': "Los libros de ventas, compras y caja diaria están en el paquete para el asesor, en CSV y Excel.",
  'fisco.debito-prec': "deuda ant. {importo}",
  'fisco.credito-prec': "crédito ant. {importo}",
  'fisco.credito-anno': "crédito año ant. {importo}",
  'fisco.meno-acconto': "anticipo {importo}",
  'fisco.non-forfettario': "La empresa no está en el régimen a tanto alzado: cámbialo en los ajustes.",
  'fisco.sim-quanto': "Si cobro además (€)",
  'fisco.sim-esito': "Cobrando {piu} más pagas unos {tasse} más entre impuesto y cotizaciones: te quedan {resta}.",
  'fisco.niente-acconti': "Ningún anticipo debido.",
  'fisco.incassato': "Cobrado",
  'fisco.incassato-nota': "facturas con «Pagada el» este año",
  'fisco.reddito': "Renta",
  'fisco.contributi': "Cotizaciones INPS",
  'fisco.imposta': "Impuesto sustitutivo",
  'fisco.aliquota-n': "tipo {n}%",
  'fisco.soglia': "Umbral de 85.000 €",
  'fisco.soglia-nota': "Has usado el {usato}% del umbral: quedan {margine}. Por encima de 100.000 € sales del régimen de inmediato.",
  'fisco.simulazione': "Simulación",
  'fisco.simula': "Calcular",
  'fisco.acconti-anno': "Anticipos {anno}",
  'fisco.acconti-base': "Calculados sobre el impuesto del año anterior: {importo}.",
  'fisco.saldo-stima': "Saldo estimado a pagar el año que viene: {importo}.",
  'fisco.gestione-artigiani': "INPS artesanos",
  'fisco.gestione-commercianti': "INPS comerciantes",
  'fisco.gestione-separata': "Gestión separada",
  'fisco.gestione-cassa': "Caja profesional",
  'fisco.gestione-nessuna': "Ninguna",
  'fisco.stampa-f24': "Imprimir F24",
  'fisco.stampa': "Imprimir o guardar PDF",
  'fisco.chiudi': "Cerrar",
  'fisco.f24-del': "F24 del {data}",
  'fisco.sezione': "Sección",
  'fisco.rateazione': "Plazo / periodo",
  'fisco.sezione-erario': "Hacienda",
  'fisco.sezione-inps': "INPS",
  'fisco.sezione-locali': "Tributos locales",
  'fisco.f24-come': "Copia las líneas en F24 web (Agenzia delle Entrate) o en tu banca online. Si compensas un crédito, o el saldo es cero, tienes que usar los servicios de la Agencia.",
  'fisco.registro-ritenute': "Retenciones practicadas",
  'fisco.pagata-il': "Pagada el",
  'fisco.percipiente': "Perceptor",
  'fisco.compenso': "Honorario",
  'fisco.ritenuta': "Retención",
  'fisco.versare-entro': "Pagar antes del",
  'fisco.ritenute-vuoto': "Ninguna retención: se registran en las facturas recibidas de profesionales (retención y fecha de pago).",
  'fisco.riepilogo-cu': "Resumen para la CU y el 770",
  'fisco.cf': "Código fiscal",
  'fisco.causale': "Causal",
  'fisco.cu-nota': "Son los datos a declarar: la CU se entrega antes del 16 de marzo y se envía a la Agencia; el 770 antes del 31 de octubre. Lumi no los envía.",
  'fisco.scadenze-anno': "Vencimientos {anno}",
  'fisco.scadenze-nota': "Solo los vencimientos de tu régimen. Las fechas en sábado o festivo ya pasan al siguiente día laborable.",
  'fisco.dal': "Desde",
  'fisco.al': "Hasta",
  'fisco.scarica-pacchetto': "Descargar el zip",
  'fisco.pacchetto': "Paquete para el asesor",
  'fisco.pacchetto-cosa': "Un zip con copias XML de las facturas emitidas, libros de IVA, liquidaciones, libro de caja y retenciones en CSV y Excel, y un resumen en PDF.",
  'fisco.quando-professionista': "Cuándo hace falta de verdad un profesional",
  'fisco.pro-dichiarazioni': "Las declaraciones (renta, IVA anual, 770) puedes presentarlas tú con SPID; para que las presente otro hace falta un intermediario habilitado.",
  'fisco.pro-visto': "Para compensar en el F24 un crédito de IVA de más de 5.000 € hace falta el visto de conformidad de un profesional.",
  'fisco.pro-consulenza': "Elegir el régimen, la reducción INPS del 35%, aplazamientos, inspecciones y avisos: es asesoría, pregunta a un asesor fiscal.",
  'fisco.pro-redditi': "IRPEF, IRES e IRAP del régimen ordinario o simplificado los calcula el asesor o la precompilada, no Lumi.",
  'fisco.salva': "Guardar",
  'fisco.salvate': "Ajustes guardados",
  'fisco.sezioni': "Secciones para impuestos",
  'fisco.sezioni-cosa': "Añade «Facturas recibidas» (compras y retenciones) y, si vendes en mostrador, «Caja diaria».",
  'fisco.anche-corrispettivi': "También la caja diaria",
  'fisco.aggiungi-sezioni': "Añadir las secciones",
  'fisco.sezioni-aggiunte': "Secciones añadidas",
  'fisco.manca-piva': "Faltan el número de IVA o el código fiscal de la empresa.",
  'fisco.apri-documenti': "Añádelos en Documentos",
  'fisco.gruppo-regime': "Régimen y actividad",
  'fisco.gruppo-inps': "Cotizaciones INPS",
  'fisco.gruppo-forfettario': "Tanto alzado",
  'fisco.gruppo-iva': "IVA",
  'fisco.gruppo-altro': "Otros",
  'fisco.promemoria': "Impuestos: {cosa} el {data}",
  'fisco.imp-regime': "Régimen fiscal",
  'fisco.impn-regime': "Si no lo sabes, pregúntalo a tu asesor: es una elección que lo cambia todo.",
  'fisco.imp-periodicita': "Liquidación de IVA",
  'fisco.impn-periodicita': "Trimestral con el 1% de intereses, si tu volumen de negocio lo permite.",
  'fisco.imp-ateco': "Código ATECO",
  'fisco.impn-ateco': "Lo encuentras en el certificado de alta del número de IVA.",
  'fisco.imp-coefficiente': "Coeficiente de rentabilidad %",
  'fisco.impn-coefficiente': "Vacío: el de la tabla oficial para tu ATECO.",
  'fisco.imp-gestione': "Régimen de cotización",
  'fisco.impn-gestione': "Para las cajas profesionales Lumi no calcula las cotizaciones.",
  'fisco.imp-riduzione35': "Reducción del 35% de las cotizaciones",
  'fisco.impn-riduzione35': "Solo artesanos y comerciantes a tanto alzado que la han pedido al INPS.",
  'fisco.imp-ante1996': "Cotizaciones anteriores a 1996",
  'fisco.impn-ante1996': "Si cotizabas antes del 31/12/1995, el tope es de 93.707 € en lugar de 122.295 €.",
  'fisco.imp-aliquotaridotta': "Tipo del 5% (primeros cinco años)",
  'fisco.impn-aliquotaridotta': "Para actividades nuevas que cumplen los requisitos; si no, 15%.",
  'fisco.imp-impostaannoprecedente': "Impuesto sustitutivo del año pasado (€)",
  'fisco.impn-impostaannoprecedente': "Base de los anticipos. Vacío: lo calcula Lumi con los datos.",
  'fisco.imp-accontiversatiannoprecedente': "Anticipos pagados el año pasado (€)",
  'fisco.impn-accontiversatiannoprecedente': "Para calcular el saldo de junio.",
  'fisco.imp-contributiversati': "Cotizaciones pagadas este año (€)",
  'fisco.impn-contributiversati': "Se deducen de la renta. Vacío: se usa la estimación.",
  'fisco.imp-sedeinps': "Código de sede INPS",
  'fisco.impn-sedeinps': "Para la sección INPS del F24.",
  'fisco.imp-matricolainps': "Matrícula o código INPS",
  'fisco.impn-matricolainps': "En la gestión separada es tu código fiscal.",
  'fisco.imp-creditoannoprecedente': "Crédito de IVA del año pasado (€)",
  'fisco.impn-creditoannoprecedente': "Se usa en las liquidaciones mientras quede.",
  'fisco.imp-accontoivastorico': "Pagado por el último periodo del año pasado (€)",
  'fisco.impn-accontoivastorico': "Para el anticipo con el método histórico.",
  'fisco.imp-accontoivaprevisto': "Previsto para el último periodo de este año (€)",
  'fisco.impn-accontoivaprevisto': "Para el método previsional. Vacío: solo el histórico hasta que se cierre el último periodo.",
  'fisco.imp-camerale': "Derecho anual de la Cámara de Comercio (€)",
  'fisco.impn-camerale': "El importe te lo comunica tu Cámara de Comercio.",
  'fisco.imp-provinciacciaa': "Provincia de la Cámara de Comercio",
  'fisco.impn-provinciacciaa': "Sigla, por ejemplo MI.",
  'fisco.imp-bollo': "Timbre virtual en las facturas",
  'fisco.impn-bollo': "En el régimen a tanto alzado siempre está activo.",
  'fisco.imp-sostituto': "Soy retenedor",
  'fisco.impn-sostituto': "Pagas a profesionales reteniendo el impuesto.",
  'fisco.v-iva': "IVA del periodo {periodo}",
  'fisco.v-iva-saldo': "Saldo anual de IVA",
  'fisco.v-iva-acconto': "Anticipo de IVA",
  'fisco.v-forf-saldo': "Saldo del impuesto sustitutivo {anno}",
  'fisco.v-forf-acconto': "Anticipo del impuesto sustitutivo {anno}",
  'fisco.v-inps-acconto': "Anticipo de cotizaciones INPS {anno}",
  'fisco.v-inps-fissi': "Cotizaciones INPS fijas",
  'fisco.v-iva-integrazioni': "IVA de las integraciones, mes {periodo}",
  'fisco.v-bollo': "Timbre virtual, {periodo}.º trimestre",
  'fisco.v-ritenute': "Retenciones del mes {periodo}",
  'fisco.v-camerale': "Derecho de la Cámara de Comercio {anno}",
  'fisco.sc-iva-mese': "Pago de IVA del mes {periodo}",
  'fisco.sc-iva-trimestre': "Pago de IVA del {periodo}.º trimestre",
  'fisco.sc-iva-saldo': "Saldo anual de IVA",
  'fisco.sc-iva-acconto': "Anticipo de IVA",
  'fisco.sc-lipe': "LIPE del {periodo}.º trimestre",
  'fisco.sc-dichiarazione-iva': "Declaración de IVA {anno}",
  'fisco.sc-forf-saldo-acconto': "Saldo y primer anticipo del impuesto sustitutivo",
  'fisco.sc-redditi-saldo-acconto': "Saldo y primer anticipo de los impuestos sobre la renta",
  'fisco.sc-forf-acconto2': "Segundo anticipo del impuesto sustitutivo",
  'fisco.sc-redditi-acconto2': "Segundo anticipo de los impuestos sobre la renta",
  'fisco.sc-dichiarazione-redditi': "Declaración de la renta {anno}",
  'fisco.sc-inps-fissi': "Cotizaciones INPS fijas, plazo {periodo}",
  'fisco.sc-inps-saldo-acconto': "Cotizaciones INPS: saldo y anticipo",
  'fisco.sc-inps-riduzione': "Solicitud de la reducción INPS del 35%",
  'fisco.sc-bollo': "Timbre virtual, {periodo}.º trimestre {anno}",
  'fisco.sc-ritenute': "Retenciones del mes {periodo}",
  'fisco.sc-cu-consegna': "CU a los perceptores",
  'fisco.sc-cu-invio': "CU a la Agencia (trabajo autónomo)",
  'fisco.sc-modello-770': "Modelo 770",
  'fisco.sc-camerale': "Derecho de la Cámara de Comercio",
  'fisco.av-da-integrare': "Hay facturas recibidas con inversión del sujeto pasivo o del extranjero aún por integrar: hasta que emitas la integración (TD16-TD19, desde Facturas electrónicas) no entran en los registros de IVA.",
  'fisco.av-vicino-85': "Estás cerca del umbral de 85.000 €: si lo superas, el año que viene sales del régimen a tanto alzado.",
  'fisco.av-oltre-85': "Has superado los 85.000 €: el año que viene sales del régimen a tanto alzado. Háblalo con un asesor.",
  'fisco.av-oltre-100': "Has superado los 100.000 €: sales del régimen de inmediato, con IVA desde la operación que superó el umbral. Necesitas un asesor.",
  'fisco.av-fuori-dal-regime': "El año pasado cobraste más de 85.000 €: este año no podrías estar en el régimen a tanto alzado. Compruébalo con un asesor.",
  'fisco.av-contributi-stimati': "Las cotizaciones deducidas son una estimación: escribe en los ajustes las pagadas de verdad este año.",
  'fisco.av-cassa-professionale': "Con una caja profesional las cotizaciones las calcula la caja: Lumi no las cuenta.",
  'fisco.av-incassi-senza-data': "Algunas facturas pagadas no tienen «Pagada el»: cuentan en la fecha de la factura.",
  'fisco.av-visto-conformita': "El crédito de IVA supera 5.000 €: para compensarlo en el F24 hace falta el visto de conformidad.",
  'fisco.av-forfettario-niente-iva': "En el régimen a tanto alzado no hay IVA que liquidar ni LIPE: mira el panel del régimen.",
  'fisco.av-redditi-professionista': "IRPEF, IRES e IRAP no están aquí: los calcula el asesor o la precompilada.",
  'fisco.av-inps-cassetto': "Los plazos fijos del INPS son una estimación: el F24 oficial está en el Cassetto previdenziale.",
  'fisco.av-cu-intermediario': "Con 20 CU o más no bastan tus credenciales: hace falta Entratel o un intermediario.",
  'fisco.av-cu-fisconline': "Con menos de 20 CU puedes enviarlas tú con tus credenciales.",
  'fisco.imp-anno-rif': "Los valores «del año pasado» valen para las cuentas de {anno}: actualízalos a principio de año. Para otros años Lumi usa los datos.",
};
