export default {
  'gestione.tipo-testo': 'Texto',
  'gestione.tipo-testo_lungo': 'Texto largo',
  'gestione.tipo-numero': 'Número',
  'gestione.tipo-valuta': 'Importe ({simbolo})',
  'gestione.tipo-percentuale': 'Porcentaje',
  'gestione.tipo-data': 'Fecha',
  'gestione.tipo-data_ora': 'Fecha y hora',
  'gestione.tipo-si_no': 'Sí / No',
  'gestione.tipo-scelta': 'Opción',
  'gestione.tipo-scelta_multipla': 'Opción múltiple',
  'gestione.tipo-stato': 'Estado (flujo)',
  'gestione.tipo-relazione': 'Vínculo',
  'gestione.tipo-righe': 'Líneas (subtabla)',
  'gestione.tipo-calcolato': 'Calculado (fórmula)',
  'gestione.tipo-contatore': 'Numeración',
  'gestione.tipo-email': 'Email',
  'gestione.tipo-telefono': 'Teléfono',
  'gestione.tipo-url': 'Sitio web',
  'gestione.tipo-indirizzo': 'Dirección',
  'gestione.tipo-codice_a_barre': 'Código de barras',
  'gestione.tipo-durata': 'Duración (minutos)',
  'gestione.tipo-immagine': 'Imagen',
  'gestione.tipo-file': 'Archivo',
  'gestione.nome': 'Nombre',
  'gestione.esempio-sezione': 'p. ej. Alquileres',
  'gestione.archivia-campo': 'Archivar el campo (los valores se conservan)',
  'gestione.obbligatorio': 'Obligatorio',
  'gestione.senza-doppioni': 'Sin duplicados',
  'gestione.prima-opzione': 'Primera opción',
  'gestione.opzioni': 'Opciones, una por línea (colores: {colori})',
  'gestione.righe-di': 'Líneas de',
  'gestione.collegato-a': 'Vinculado a',
  'gestione.piu-di-uno': 'Más de uno',
  'gestione.campo-punta': 'Campo que apunta aquí (en la otra entidad)',
  'gestione.formula': 'Fórmula (p. ej. cantidad * precio · SUMA(lineas.total) · SI(stock <= minimo; "sí"; "no"))',
  'gestione.mostra-come': 'Mostrar como',
  'gestione.automatico': 'Automático',
  'gestione.importo': 'Importe',
  'gestione.formato-contatore': 'Formato ({AAAA} año, {N:4} número de 4 cifras)',
  'gestione.salva-modifiche': 'Guardar cambios',
  'gestione.dai-nome': 'Ponle un nombre',
  'gestione.piu-campo': '+ Campo',
  'gestione.personalizza-nome': 'Personalizar · {nome}',
  'gestione.icona': 'Icono',
  'gestione.nome-elemento': 'Nombre de cada elemento',
  'gestione.nota-dati': 'Renombrar y mover no toca los datos. Un campo que quitas se archiva con sus valores y se puede restaurar. Si un cambio de tipo perdiera valores, el guardado se detiene y te dice cuáles.',
  'gestione.password-8': 'Contraseña (8+)',
  'gestione.aggiungi': 'Añadir',
  'gestione.aggiunto': 'Añadido',
  'gestione.ruolo-cambiato': 'Rol cambiado',
  'gestione.disattiva': 'Desactivar',
  'gestione.riattiva': 'Reactivar',
  'gestione.ruolo': 'Rol',
  'gestione.nuova-persona': 'Nueva persona',
  'gestione.ruoli': 'Roles',
  'gestione.nota-ruoli': 'El titular puede hacerlo todo. Para los demás roles, elige sección por sección qué pueden hacer.',
  'gestione.nuovo-ruolo': '+ Nuevo rol',
  'gestione.nome-ruolo': 'Nombre del rol (p. ej. Mostrador, Taller)',
  'gestione.vede': 'Ve',
  'gestione.modifica': 'Modifica',
  'gestione.campi-nascosti-ruolo': 'Campos ocultos para este rol',
  'gestione.salva-ruolo': 'Guardar el rol',
  'gestione.ruolo-salvato': 'Rol guardado',
  'gestione.puo-personalizzare': 'Puede personalizar',
  'gestione.sezione': 'Sección',
  'gestione.campi-nascosti': 'Campos ocultos (⌘/Ctrl para elegir varios)',
  'gestione.ruolo-titolare': 'Titular',
  'gestione.ruolo-collaboratore': 'Colaborador',
  'gestione.ruolo-lettura': 'Solo lectura',
  'gestione.lingua-valuta': 'Idioma y moneda',
  'gestione.tua-lingua': 'Tu idioma',
  'gestione.tua-lingua-nota': 'Solo vale para ti, en todos tus dispositivos.',
  'gestione.azienda': 'Para toda la empresa',
  'gestione.lingua-modelli': 'Idioma de las plantillas nuevas',
  'gestione.lingua-modelli-nota': 'Las plantillas que añadas a partir de ahora llegan con los nombres en este idioma. Las secciones que ya existen no cambian.',
  'gestione.valuta-nota': 'Los importes se muestran en esta moneda. Los valores guardados no cambian: solo cambian el símbolo y el formato.',
  'gestione.esempio': 'Así: {numero} · {soldi} · {data}',
  'gestione.salvato-ricarico': 'Guardado: recargo la página',
  'gestione.settimana-da': 'La semana empieza el {giorno}.',
};
