// Almacén (web/moduli/magazzino.js): valor, inventario, movimientos.
export default {
  'magazzino.titolo': "Almacén",
  'magazzino.scheda-valore': "Valor",
  'magazzino.scheda-inventario': "Inventario",
  'magazzino.scheda-movimenti': "Movimientos",
  'magazzino.sezione': "Sección del almacén",
  'magazzino.nessuna-sezione': "Ninguna sección con existencias: añade el campo «giacenza» a los artículos.",
  'magazzino.valore': "Valor",
  'magazzino.al-costo': "al coste de los artículos",
  'magazzino.pezzi': "Unidades",
  'magazzino.articoli-n': {"one": "{n} artículo", "other": "{n} artículos"},
  'magazzino.sotto-scorta': "Bajo mínimos",
  'magazzino.negativi': {"one": "{n} artículo con existencias negativas: {nomi}", "other": "{n} artículos con existencias negativas: {nomi}"},
  'magazzino.senza-costo': {"one": "{n} artículo en existencias no tiene coste: no entra en el valor.", "other": "{n} artículos en existencias no tienen coste: no entran en el valor."},
  'magazzino.per-categoria': "Por categoría",
  'magazzino.categoria': "Categoría",
  'magazzino.articoli': "Artículos",
  'magazzino.senza-categoria': "Sin categoría",
  'magazzino.per-articolo': "Por artículo",
  'magazzino.codice': "Código",
  'magazzino.articolo': "Artículo",
  'magazzino.giacenza': "Existencias",
  'magazzino.costo': "Coste",
  'magazzino.scarica-csv': "Descargar CSV",
  'magazzino.nota-valore': "El valor es existencias × coste. Las compras mantienen el coste medio ponderado. Es el dato de existencias finales para el asesor.",
  'magazzino.inventario-nota': "Cuenta la mercancía en las estanterías: las existencias de ahora quedan como referencia y, al cerrar, cada artículo contado se corrige con la diferencia. Las ventas hechas mientras cuentas siguen bien.",
  'magazzino.continua': "Continuar «{nome}»",
  'magazzino.nuovo-inventario': "Empezar un inventario",
  'magazzino.inventari': "Inventarios",
  'magazzino.nome': "Nombre",
  'magazzino.iniziato': "Empezado",
  'magazzino.contati': "Contados",
  'magazzino.stato': "Estado",
  'magazzino.chiuso-il': "Cerrado el {data}",
  'magazzino.aperto': "Abierto",
  'magazzino.leggi-codice': "Lee un código (lector o teclado, luego Intro)",
  'magazzino.letto': "{nome}: {n}",
  'magazzino.cerca': "Buscar artículo o código",
  'magazzino.attesa': "Esperado",
  'magazzino.contata': "Contado",
  'magazzino.differenza': "Diferencia",
  'magazzino.chiudi-conferma': {"one": "¿Cerrar el inventario? Se corrige {n} existencia.", "other": "¿Cerrar el inventario? Se corrigen {n} existencias."},
  'magazzino.chiuso': {"one": "Inventario cerrado: {n} ajuste, {importo}", "other": "Inventario cerrado: {n} ajustes, {importo}"},
  'magazzino.differenze': "Diferencias",
  'magazzino.valore-differenze': "Valor de las diferencias",
  'magazzino.chiudi': "Cerrar el inventario",
  'magazzino.chiudi-nota': "Los artículos no contados se quedan como están.",
  'magazzino.quando': "Cuándo",
  'magazzino.movimento': "Movimiento",
  'magazzino.origine': "Origen",
  'magazzino.chi': "Quién",
  'magazzino.origine-iniziale': "Existencias iniciales",
  'magazzino.origine-modifica': "Modificación",
  'magazzino.origine-automazione': "Automático (ventas, pedidos, consumos)",
  'magazzino.origine-inventario': "Inventario",
  'magazzino.niente-movimenti': "Aún no hay movimientos.",
  'magazzino.nota-movimenti': "Cada cambio de existencias llega aquí solo, venga de donde venga: fichas, ventas, pedidos recibidos, importaciones, inventarios.",
};
