export default {
  'moduli.lumi-serve-chiave': "Para responder necesito la clave de Claude. Te abro **Gestión → Lumi**: es un minuto.",
  'moduli.lumi-serve-chiave-spento': "Para responder necesito la clave de Claude y que me vuelvas a encender. Te abro **Gestión → Lumi**: es un minuto.",
  'moduli.lumi-chiedi-titolare': "Para responder necesito la clave de Claude: pide al titular que la añada en **Gestión → Lumi**.",
  'moduli.lumi-spento': "Lumi está apagado: se vuelve a encender en Gestión → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi está casi listo: falta la clave de Claude.",
  'moduli.lumi-apri': "Abrir",
  'moduli.lumi-settimana': "Cómo va la semana",
  'moduli.lumi-settimana-domanda': "¿Cómo ha ido esta semana? Dame las cifras principales.",
  'moduli.lumi-accendi': "Encender Lumi",
  'moduli.lumi-solo-titolare': "Los ajustes de Lumi son cosa del titular.",
  'moduli.lumi-gia-salvata': "•••••••• (ya guardada)",
  'moduli.lumi-stato-spento': "Apagado",
  'moduli.lumi-stato-acceso': "Encendido",
  'moduli.lumi-stato-manca': "Falta la clave",
  'moduli.lumi-fonte-ambiente': "La clave viene de la variable ANTHROPIC_API_KEY del servidor.",
  'moduli.lumi-fonte-file': "Clave guardada en este ordenador.",
  'moduli.lumi-cos-e': "Lumi es el asistente de Kubo. Le hablas o le escribes desde la píldora de arriba: busca, cuenta, prepara fichas y cambia la forma del sistema. Cada cambio espera tu «Confirmar», y cada persona ve solo lo que sus permisos le dejan ver.",
  'moduli.lumi-chiave': "Clave de Claude",
  'moduli.lumi-salva-chiave': "Guardar la clave",
  'moduli.lumi-incolla': "Pega la clave",
  'moduli.lumi-togliere': "¿Quitar la clave? Lumi dejará de responder.",
  'moduli.lumi-dove-chiave': "La creas en console.anthropic.com, en API Keys. Se queda en este ordenador, en un archivo junto a los datos que solo lee Kubo, y nunca llega a los navegadores.",
  'moduli.lumi-acceso': "Lumi encendido",
  'moduli.lumi-limite': "Preguntas por minuto por persona",
  'moduli.lumi-da-provare': "Para probar",
  'moduli.lumi-esempio-1': "¿Cuánto he vendido esta semana?",
  'moduli.lumi-esempio-2': "¿Qué tengo que reponer?",
  'moduli.lumi-esempio-3': "Añade la talla a los artículos con S, M, L y XL",
  'moduli.lumi-esempio-4': "Hazme una sección de alquileres con cliente, herramienta, desde, hasta y estado",
  'moduli.lumi-esempio-5': "Cuando un alquiler pase a devuelto, avísame",
  'moduli.lumi-modello': "Modelo: {modello}.",
  'moduli.lumi-voce-accesa': "Voz en tiempo real encendida.",
  'moduli.lumi-voce-browser': "Voz: la del navegador, donde la haya.",
  'moduli.ag-adesso': "ahora",
  'moduli.ag-agenda': "Agenda",
  'moduli.ag-calendario': "Calendario",
  'moduli.ag-cruscotto': "Panel",
  'moduli.ag-aggiungi-voce': "Añadir el elemento",
  'moduli.ag-altri': {"one": "+{n} más", "other": "+{n} más"},
  'moduli.ag-e-altri': {"one": "y uno más", "other": "y {n} más"},
  'moduli.ag-aria-grafico': "{titolo}: gráfico",
  'moduli.ag-barre': "Barras",
  'moduli.ag-linea': "Línea",
  'moduli.ag-buongiorno': "Buenos días",
  'moduli.ag-buon-pomeriggio': "Buenas tardes",
  'moduli.ag-buonasera': "Buenas noches",
  'moduli.ag-saluto': "{saluto}, {nome}",
  'moduli.ag-cambia': "Cambiar",
  'moduli.ag-cambia-widget': "Cambiar el widget",
  'moduli.ag-nuovo-widget': "Nuevo widget",
  'moduli.ag-campo': "Campo",
  'moduli.ag-colonne-per': "Columnas: {nome}",
  'moduli.ag-una-colonna': "Una columna",
  'moduli.ag-come-oggi': "igual que ayer",
  'moduli.ag-come-settimana': "igual que la semana pasada",
  'moduli.ag-come-mese': "igual que el mes pasado",
  'moduli.ag-come-anno': "igual que el año pasado",
  'moduli.ag-rispetto-oggi': "{diff} respecto a ayer ({prima})",
  'moduli.ag-rispetto-settimana': "{diff} respecto a la semana pasada ({prima})",
  'moduli.ag-rispetto-mese': "{diff} respecto al mes pasado ({prima})",
  'moduli.ag-rispetto-anno': "{diff} respecto al año pasado ({prima})",
  'moduli.ag-data-rif': "Fecha de referencia",
  'moduli.ag-prima': "Anterior",
  'moduli.ag-dopo': "Siguiente",
  'moduli.ag-fatto': "Listo",
  'moduli.ag-forma': "Forma",
  'moduli.ag-ha-creato': "creó",
  'moduli.ag-ha-modificato': "modificó",
  'moduli.ag-ha-archiviato': "archivó",
  'moduli.ag-ha-ripristinato': "restauró",
  'moduli.ag-in-sezione': "en {nome}",
  'moduli.ag-un-elemento': "un elemento",
  'moduli.ag-lista': "Lista",
  'moduli.ag-torna-lista': "Volver a la lista",
  'moduli.ag-media': "Media de…",
  'moduli.ag-somma': "Suma de…",
  'moduli.ag-quanti': "Cuántos hay",
  'moduli.ag-misura': "Medida",
  'moduli.ag-modifica': "Editar",
  'moduli.ag-nome-voce': "Nombre del elemento",
  'moduli.ag-nuova-voce': "Nuevo elemento",
  'moduli.ag-un-filtro': "Pon al menos un filtro al elemento",
  'moduli.ag-non-disegno': "No consigo dibujarlo",
  'moduli.ag-oggi': "Hoy",
  'moduli.ag-per': "Por",
  'moduli.ag-periodo': "Periodo",
  'moduli.ag-periodo-oggi': "Hoy",
  'moduli.ag-periodo-settimana': "Esta semana",
  'moduli.ag-periodo-mese': "Este mes",
  'moduli.ag-periodo-anno': "Este año",
  'moduli.ag-periodo-ultimi_7': "Últimos 7 días",
  'moduli.ag-periodo-ultimi_30': "Últimos 30 días",
  'moduli.ag-periodo-ultimi_84': "Últimas 12 semanas",
  'moduli.ag-periodo-ultimi_365': "Último año",
  'moduli.ag-periodo-sempre': "Siempre",
  'moduli.ag-piede-grafico': "{periodo} · {totale} en total",
  'moduli.ag-piu-aggiungi': "+ Añadir",
  'moduli.ag-quale-data': "Qué fecha",
  'moduli.ag-senza-titolo': "Sin título",
  'moduli.ag-spostato': "Movido",
  'moduli.ag-tipo': "Tipo",
  'moduli.ag-titolo': "Título",
  'moduli.ag-titolo-widget': "Ponle un título al widget",
  'moduli.ag-tutti': "todos",
  'moduli.ag-utente-non-attivo': "Usuario inactivo",
  'moduli.ag-vedi-calendario': "Ver en el calendario",
  'moduli.ag-vedi-elenco': "Ver la lista",
  'moduli.ag-vedi-giorno': "Ver el día",
  'moduli.ag-vista-giorno': "Día",
  'moduli.ag-vista-settimana': "Semana",
  'moduli.ag-vista-mese': "Mes",
  'moduli.ag-w-numero': "Número",
  'moduli.ag-w-grafico': "Gráfico",
  'moduli.ag-w-attenzione': "Requiere atención",
  'moduli.ag-w-ultime': "Últimos cambios",
  'moduli.ag-def-incassato-oggi': "Cobrado hoy",
  'moduli.ag-def-incassato-mese': "Cobrado este mes",
  'moduli.ag-def-vendite-oggi': "Ventas de hoy",
  'moduli.ag-def-incassi-30': "Cobros de los últimos 30 días",
  'moduli.ag-def-appuntamenti-oggi': "Citas de hoy",
  'moduli.ag-def-appuntamenti-settimana': "Citas por semana",
  'moduli.ag-def-preventivi-attesa': "Presupuestos pendientes",
  'moduli.ag-def-commesse-aperte': "Encargos abiertos",
  'moduli.ag-def-accettato-mese': "Aceptado este mes",
  'moduli.ag-def-preventivi-mese': "Presupuestos aceptados por mes",
  'moduli.ag-def-articoli-riordinare': "Artículos para reponer",
  'moduli.ag-def-materiali-riordinare': "Materiales para reponer",
  'moduli.ag-def-ordini-ritardo': "Pedidos con retraso",
  'moduli.ag-def-vendite-aperte': "Ventas abiertas desde hace más de 2 días",
  'moduli.ag-def-commesse-ritardo': "Encargos con retraso",
  'moduli.ag-def-preventivi-senza-risposta': "Presupuestos sin respuesta desde hace 7 días",
  'moduli.ag-def-appuntamenti-chiudere': "Citas pasadas por cerrar",
  'moduli.ag-def-pacchetti-scaduti': "Bonos caducados con sesiones",
  'moduli.ag-def-attenzione': "Requiere atención",
  'moduli.ag-def-ultime': "Últimos cambios",
  'moduli.ag-def-nuovi-mese': "{nome}: nuevos este mes",
  'moduli.ag-tutto-ok': "✓ Todo en orden: nada que arreglar.",
  'moduli.ag-nessuna-modifica': "Todavía no hay cambios.",
  'moduli.ag-es-titolo': "P. ej. Cobrado hoy",
  'moduli.im-menu': "Importa desde una hoja o exporta la lista con los filtros actuales",
  'moduli.im-importa-da': "Importar desde Excel o CSV…",
  'moduli.im-esporta-xlsx': "Exportar a Excel (.xlsx)",
  'moduli.im-esporta-csv': "Exportar a CSV",
  'moduli.im-nuova-dal-foglio': "+ Una sección nueva a partir de la hoja",
  'moduli.im-scegli-file': "Elige un archivo Excel (.xlsx) o CSV",
  'moduli.im-trascina': "o arrástralo aquí. La primera fila debe tener los nombres de las columnas.",
  'moduli.im-esporta-tutto': "Exportar todo",
  'moduli.im-backup': "Copia de seguridad completa",
  'moduli.im-backup-nota': "Un zip con la copia de la base de datos (coherente aunque se esté trabajando) y los adjuntos. Guárdalo en un disco externo o en tu propia nube.",
  'moduli.im-scarica-backup': "Descargar la copia",
  'moduli.im-importa-esporta': "Importar y exportar",
  'moduli.im-api': "API e integraciones",
  'moduli.im-dati': "Datos",
  'moduli.im-dove': "Adónde van las filas",
  'moduli.im-non-importare': "— no importar",
  'moduli.im-crea-campo': "+ Crear el campo «{nome}» ({tipo})",
  'moduli.im-non-controllare': "No comprobar: cada fila es nueva",
  'moduli.im-stesso': "Mismo «{nome}»",
  'moduli.im-stesso-unico': "Mismo «{nome}» (sin duplicados)",
  'moduli.im-aggiorna': "actualiza la que ya existe",
  'moduli.im-salta': "déjala, salta la fila",
  'moduli.im-controllo': "Comprobando…",
  'moduli.im-importo': "Importando…",
  'moduli.im-importato': "Importado",
  'moduli.im-prova': "Probar sin guardar",
  'moduli.im-importa-n': {"one": "Importar {n} fila", "other": "Importar {n} filas"},
  'moduli.im-righe-in': {"one": "{n} fila en «{file}»", "other": "{n} filas en «{file}»"},
  'moduli.im-riga': "Fila",
  'moduli.im-errore': "Error",
  'moduli.im-file-errori': "filas por corregir.csv",
  'moduli.im-prova-esito': "Prueba: no se ha guardado nada",
  'moduli.im-esito-create': {"one": "creada", "other": "creadas"},
  'moduli.im-esito-aggiornate': {"one": "actualizada", "other": "actualizadas"},
  'moduli.im-esito-saltate': {"one": "omitida", "other": "omitidas"},
  'moduli.im-esito-errori': "con errores",
  'moduli.im-cosa-non-va': "Qué falla",
  'moduli.im-e-altre': {"one": "…y una más.", "other": "…y {n} más."},
  'moduli.im-scarica-errori': "Descargar las filas con errores (.csv)",
  'moduli.im-correggi': "Corrígelas en el archivo e impórtalas de nuevo: con el control de duplicados no se duplica nada.",
  'moduli.im-vai-a': "Ir a {nome}",
  'moduli.im-abbina': "Asocia las columnas a los campos de {nome}. Las primeras filas:",
  'moduli.im-ogni-colonna': "Cada columna se convierte en un campo: revisa nombres y tipos.",
  'moduli.im-nome-sezione': "Nombre de la nueva sección",
  'moduli.im-gia-presenti': "Filas que ya existen",
  'moduli.im-se-trovo': "si las encuentro:",
  'moduli.im-formati': "Se aceptan números como «1.234,50» o «12 €», fechas como «31/12/2026» y «sí / no». Las celdas vacías no borran nada.",
};
