export default {
  'moduli.lumi-serve-chiave': "Para responder necesito la clave de Claude. Te abro **Gestión → Lumi**: es un minuto.",
  'moduli.lumi-serve-chiave-spento': "Para responder necesito la clave de Claude y que me vuelvas a encender. Te abro **Gestión → Lumi**: es un minuto.",
  'moduli.lumi-chiedi-titolare': "Para responder necesito la clave de Claude: pide al titular que la añada en **Gestión → Lumi**.",
  'moduli.lumi-spento': "Lumi está apagado: se vuelve a encender en Gestión → Lumi.",
  'moduli.lumi-quasi-pronto': "Lumi está casi listo: falta la clave de Claude.",
  'moduli.lumi-apri': "Abrir",
  'moduli.lumi-settimana': "Cómo va la semana",
  'moduli.lumi-settimana-domanda': "¿Cómo ha ido esta semana? Dame las cifras principales.",
  'moduli.lumi-accendi': "Encender Lumi",
  'moduli.lumi-solo-titolare': "Los ajustes de Lumi son cosa del titular.",
  'moduli.lumi-gia-salvata': "•••••••• (ya guardada)",
  'moduli.lumi-stato-spento': "Apagado",
  'moduli.lumi-stato-acceso': "Encendido",
  'moduli.lumi-stato-manca': "Falta la clave",
  'moduli.lumi-fonte-ambiente': "La clave viene de la variable ANTHROPIC_API_KEY del servidor.",
  'moduli.lumi-fonte-file': "Clave guardada en este ordenador.",
  'moduli.lumi-cos-e': "Lumi es el asistente de Kubo. Le hablas o le escribes desde la píldora de arriba: busca, cuenta, prepara fichas y cambia la forma del sistema. Cada cambio espera tu «Confirmar», y cada persona ve solo lo que sus permisos le dejan ver.",
  'moduli.lumi-chiave': "Clave de Claude",
  'moduli.lumi-salva-chiave': "Guardar la clave",
  'moduli.lumi-incolla': "Pega la clave",
  'moduli.lumi-togliere': "¿Quitar la clave? Lumi dejará de responder.",
  'moduli.lumi-dove-chiave': "La creas en console.anthropic.com, en API Keys. Se queda en este ordenador, en un archivo junto a los datos que solo lee Kubo, y nunca llega a los navegadores.",
  'moduli.lumi-acceso': "Lumi encendido",
  'moduli.lumi-limite': "Preguntas por minuto por persona",
  'moduli.lumi-da-provare': "Para probar",
  'moduli.lumi-esempio-1': "¿Cuánto he vendido esta semana?",
  'moduli.lumi-esempio-2': "¿Qué tengo que reponer?",
  'moduli.lumi-esempio-3': "Añade la talla a los artículos con S, M, L y XL",
  'moduli.lumi-esempio-4': "Hazme una sección de alquileres con cliente, herramienta, desde, hasta y estado",
  'moduli.lumi-esempio-5': "Cuando un alquiler pase a devuelto, avísame",
  'moduli.lumi-modello': "Modelo: {modello}.",
  'moduli.lumi-voce-accesa': "Voz en tiempo real encendida.",
  'moduli.lumi-voce-browser': "Voz: la del navegador, donde la haya.",
};
