// Area «sicurezza» (web/moduli/sicurezza.js): password, dispositivi collegati, impostazioni dell'azienda, poteri dei ruoli.
export default {
  'sicurezza.titolo': 'Seguridad',
  'sicurezza.la-tua-password': 'Tu contraseña',
  'sicurezza.dispositivi-collegati': 'Dispositivos conectados',
  'sicurezza.dispositivo': '{browser} en {sistema}',
  'sicurezza.dispositivo-sconosciuto': 'Dispositivo desconocido',
  'sicurezza.app-kubo': 'App de Kubo',
  'sicurezza.iphone-ipad': 'iPhone o iPad',
  'sicurezza.password-diverse': 'Las dos contraseñas nuevas no coinciden',
  'sicurezza.password-cambiata': 'Contraseña cambiada. Se han desconectado los demás dispositivos.',
  'sicurezza.password-attuale': 'Contraseña actual',
  'sicurezza.password-nuova': 'Contraseña nueva',
  'sicurezza.password-regole': 'Al menos 8 caracteres; por debajo de 12, mezcla letras con números o símbolos.',
  'sicurezza.password-ripeti': 'Repite la contraseña nueva',
  'sicurezza.cambia-password': 'Cambiar contraseña',
  'sicurezza.col-dispositivo': 'Dispositivo',
  'sicurezza.col-ultimo-uso': 'Último uso',
  'sicurezza.col-indirizzo': 'Dirección',
  'sicurezza.questo': 'este',
  'sicurezza.scollega': 'Desconectar',
  'sicurezza.scollegati': { one: '{n} dispositivo desconectado', other: '{n} dispositivos desconectados' },
  'sicurezza.scollega-altri': 'Desconectar todos los demás',
  'sicurezza.impostazioni': 'Ajustes de la empresa',
  'sicurezza.inattivita': 'Cerrar las sesiones inactivas desde hace (minutos)',
  'sicurezza.allegati': 'Adjuntos: como máximo (MB)',
  'sicurezza.fuso': 'Zona horaria',
  'sicurezza.lumi-budget': 'Lumi: tokens al mes (0 = sin límite)',
  'sicurezza.lumi-usati': 'Usados este mes: {usati}',
  'sicurezza.webhook-interni': 'Permitir webhooks hacia la red interna (127.0.0.1, 192.168…). Déjalo desactivado si no sabes para qué sirve.',
  'sicurezza.salvate': 'Ajustes guardados',
  'sicurezza.salva': 'Guardar',
  'sicurezza.ruoli': 'Permisos de los roles',
  'sicurezza.ruoli-nota': 'Exportar la factura electrónica consume un número de envío; Lumi usa los tokens de la empresa.',
  'sicurezza.col-ruolo': 'Rol',
  'sicurezza.potere-fatturapa': 'Exportar FatturaPA',
  'sicurezza.potere-lumi': 'Usar Lumi',
  'sicurezza.potere-aria': '{potere} para {ruolo}',
  'sicurezza.salvato': 'Guardado',
  'sicurezza.persone': 'Personas',
  'sicurezza.col-nome': 'Nombre',
  'sicurezza.obbliga-cambio': 'Obligar a cambiar la contraseña',
  'sicurezza.obbligo-fatto': '{nome} cambiará la contraseña en el próximo acceso',
  'sicurezza.scollega-ovunque': 'Desconectar en todas partes',
  'sicurezza.scollegato-ovunque': 'Sesiones de {nome} cerradas en todos los dispositivos',
  'sicurezza.nessun-altro': 'No hay nadie más.',
  'sicurezza.scegli-password': 'Elige tu contraseña',
  'sicurezza.provvisoria': 'La contraseña que te dieron era provisional. Elige una propia para continuar.',
};
