// Tesorería (web/moduli/tesoreria.js): vencimientos, conciliación bancaria, previsión de caja, recordatorios, remesas.
export default {
  'tesoreria.titolo': "Tesorería",
  'tesoreria.scheda-scadenze': "Vencimientos",
  'tesoreria.scheda-banca': "Banco",
  'tesoreria.scheda-cassa': "Previsión de caja",
  'tesoreria.scheda-solleciti': "Recordatorios",
  'tesoreria.scheda-distinte': "Remesas",
  'tesoreria.scheda-impostazioni': "Ajustes",
  'tesoreria.manca-fatture': "Los vencimientos salen de las facturas: añade la plantilla «Facturas y factura electrónica» desde Personalizar.",
  'tesoreria.da-incassare': "Por cobrar",
  'tesoreria.da-pagare': "Por pagar",
  'tesoreria.di-cui-scaduto': "de ello vencido {importo}",
  'tesoreria.saldo-netto': "Diferencia",
  'tesoreria.verso-attiva': "Cobros de clientes",
  'tesoreria.verso-passiva': "Pagos a proveedores",
  'tesoreria.solo-scadute': "Solo vencidos",
  'tesoreria.cerca': "Buscar cliente o documento",
  'tesoreria.scadenza': "Vencimiento",
  'tesoreria.documento': "Documento",
  'tesoreria.cliente': "Cliente",
  'tesoreria.fornitore': "Proveedor",
  'tesoreria.importo': "Importe",
  'tesoreria.residuo': "Pendiente",
  'tesoreria.stato': "Estado",
  'tesoreria.pagata': "Pagado",
  'tesoreria.in-distinta': "En remesa",
  'tesoreria.scaduta-da': { one: "Vencido hace {n} día", other: "Vencido hace {n} días" },
  'tesoreria.parziale': "Pago parcial",
  'tesoreria.aperta': "Abierto",
  'tesoreria.incassata': "Cobrado",
  'tesoreria.pagata-btn': "Pagado",
  'tesoreria.acconto': "Pago parcial",
  'tesoreria.niente-scadenze': "No hay vencimientos abiertos.",
  'tesoreria.scegli-nota': "Marca los vencimientos para darlos por pagados o preparar el fichero para el banco.",
  'tesoreria.scelte': { one: "{n} elegido · {importo}", other: "{n} elegidos · {importo}" },
  'tesoreria.segna-incassate': "Marcar cobrados",
  'tesoreria.segna-pagate': "Marcar pagados",
  'tesoreria.distinta-riba': "Remesa Ri.Ba.",
  'tesoreria.distinta-sdd': "Adeudo SDD",
  'tesoreria.distinta-sct': "Transferencias SEPA",
  'tesoreria.data-pagamento': "Fecha del pago (AAAA-MM-DD)",
  'tesoreria.data-esecuzione': "Fecha de ejecución en el banco (AAAA-MM-DD)",
  'tesoreria.data-accredito': "Fecha del abono o del pago (AAAA-MM-DD)",
  'tesoreria.importo-acconto': "Importe cobrado o pagado",
  'tesoreria.importo-non-valido': "Importe no válido",
  'tesoreria.incassi-registrati': { one: "Cobro registrado", other: "{n} cobros registrados" },
  'tesoreria.pagamenti-registrati': { one: "Pago registrado", other: "{n} pagos registrados" },
  'tesoreria.distinta-creata': "{nome} lista: {importo}. Sube el fichero a la banca online.",
  'tesoreria.nota-termini': "Los vencimientos salen de los plazos de la factura, de su fecha de vencimiento o de las condiciones de pago del cliente o del proveedor (por ejemplo 30/60/90 DFFM).",
  'tesoreria.err-sia': "Falta el código SIA de la empresa (te lo da el banco): escríbelo en los ajustes de tesorería.",
  'tesoreria.err-iban-azienda': "Falta el IBAN de la empresa o es incorrecto: Documentos → datos de la empresa.",
  'tesoreria.err-banca-debitore': "{nome}: falta el IBAN del banco del cliente en su ficha.",
  'tesoreria.err-cf-debitore': "{nome}: falta el NIF o el código fiscal.",
  'tesoreria.err-importo': "{nome}: importe por cobrar no válido.",
  'tesoreria.err-id-creditore': "Falta el identificador de acreedor SEPA (lo emite el banco): ajustes de tesorería.",
  'tesoreria.err-iban-debitore': "{nome}: IBAN del cliente ausente o incorrecto.",
  'tesoreria.err-mandato': "{nome}: faltan la referencia y la fecha del mandato SDD en la ficha del cliente.",
  'tesoreria.err-iban-beneficiario': "{nome}: IBAN del proveedor ausente o incorrecto.",
  'tesoreria.banca-titolo': "Extracto y conciliación",
  'tesoreria.manca-movimenti': "Para importar el extracto hace falta la sección «Movimientos bancarios».",
  'tesoreria.prepara': "Preparar la tesorería",
  'tesoreria.preparata': { one: "Añadido {n} elemento", other: "Añadidos {n} elementos" },
  'tesoreria.chiedi-titolare': "Pídeselo a quien puede personalizar el sistema.",
  'tesoreria.file-grande': "{nome} es demasiado grande",
  'tesoreria.importati': "Importados {n} movimientos, {doppi} ya existían",
  'tesoreria.saldo-aggiornato': "Saldo de la previsión actualizado: {importo} el {data}",
  'tesoreria.carica-estratto': "Arrastra aquí el extracto, o haz clic",
  'tesoreria.formati': "CAMT.053 (XML), CBI, CSV o Excel del banco",
  'tesoreria.abbinato': "Conciliado: vencimientos marcados como pagados",
  'tesoreria.abbinato-differenza': "Conciliado; sobran {importo}",
  'tesoreria.abbina-a': "Conciliar con…",
  'tesoreria.abbina': "Conciliar",
  'tesoreria.ignora': "Ignorar",
  'tesoreria.ignora-nota': "Comisiones, traspasos, nóminas: movimientos que no cierran una factura",
  'tesoreria.nessuna-proposta': "Sin propuestas: elige a mano aquí abajo.",
  'tesoreria.da-abbinare': { one: "{n} movimiento por conciliar", other: "{n} movimientos por conciliar" },
  'tesoreria.tutto-abbinato': "Todo conciliado.",
  'tesoreria.abbinati-recenti': "Conciliados recientemente",
  'tesoreria.data': "Fecha",
  'tesoreria.descrizione': "Descripción",
  'tesoreria.mov-abbinato': "Conciliado",
  'tesoreria.mov-ignorato': "Ignorado",
  'tesoreria.mov-da_abbinare': "Por conciliar",
  'tesoreria.annulla': "Deshacer",
  'tesoreria.nota-movimenti': "Los movimientos están en la sección «{sezione}»: también la llenan las conexiones con el banco (open banking).",
  'tesoreria.perche-importo': "mismo importe",
  'tesoreria.perche-importo-vicino': "importe parecido",
  'tesoreria.perche-acconto': "pago parcial",
  'tesoreria.perche-numero': "número de factura",
  'tesoreria.perche-iban': "mismo IBAN",
  'tesoreria.perche-nome': "nombre",
  'tesoreria.perche-data': "fecha cercana",
  'tesoreria.perche-somma': "varias facturas juntas",
  'tesoreria.perche-distinta': "abono de la remesa",
  'tesoreria.grafico': "Entradas, salidas y saldo previstos",
  'tesoreria.passo-settimana': "Semanas",
  'tesoreria.passo-mese': "Meses",
  'tesoreria.senza-saldo': "Falta el saldo inicial: escríbelo en los ajustes o importa un extracto CAMT.053.",
  'tesoreria.apri-impostazioni': "Abrir los ajustes",
  'tesoreria.scoperto': "Atención: la caja baja de cero, hasta {importo} el {data}.",
  'tesoreria.saldo-oggi': "Saldo hoy",
  'tesoreria.saldo-dal': "desde el saldo del {data} más los movimientos",
  'tesoreria.saldo-fine': "Saldo previsto",
  'tesoreria.punto-basso': "Punto más bajo",
  'tesoreria.entrate': "Entradas",
  'tesoreria.uscite': "Salidas",
  'tesoreria.saldo': "Saldo",
  'tesoreria.periodi': "Por periodo",
  'tesoreria.periodo': "Periodo",
  'tesoreria.voci': "De dónde salen los números",
  'tesoreria.tipo': "Tipo",
  'tesoreria.voce-incasso': "Cobro",
  'tesoreria.voce-pagamento': "Pago",
  'tesoreria.voce-previsione': "Previsión",
  'tesoreria.voce-tasse': "Impuestos",
  'tesoreria.ritardo-medio': { one: "el cliente paga de media {n} día tarde", other: "el cliente paga de media {n} días tarde" },
  'tesoreria.niente-voci': "Nada a la vista en el periodo.",
  'tesoreria.aggiungi-previsione': "Añade alquiler, nóminas, préstamos y otras previsiones",
  'tesoreria.sollecito-segnato': "Recordatorio registrado",
  'tesoreria.livello-1': "Recordatorio amable",
  'tesoreria.livello-2': "Reclamación",
  'tesoreria.livello-3': "Requerimiento formal",
  'tesoreria.appena-sollecitato': "Reclamado hace poco",
  'tesoreria.ritardo-giorni': { one: "{n} día de retraso", other: "{n} días de retraso" },
  'tesoreria.ultimo-sollecito': "Último recordatorio el {data} (nivel {livello})",
  'tesoreria.lettera': "Texto del recordatorio",
  'tesoreria.copia': "Copiar el texto",
  'tesoreria.copiato': "Copiado",
  'tesoreria.copia-no': "No se pudo copiar: selecciona el texto a mano",
  'tesoreria.oggetto-sollecito': "Recordatorio de pago",
  'tesoreria.scrivi-email': "Escribir el correo",
  'tesoreria.segna-mandato': "Marcar como enviado",
  'tesoreria.niente-solleciti': "Ningún cliente con retraso.",
  'tesoreria.distinta-chiusa': "Remesa cerrada: vencimientos marcados como pagados",
  'tesoreria.distinta': "Remesa",
  'tesoreria.creata': "Creada",
  'tesoreria.quante': "Vencimientos",
  'tesoreria.pagata-il': "Pagada el {data}",
  'tesoreria.accreditata-il': "Abonada el {data}",
  'tesoreria.in-attesa': "Pendiente",
  'tesoreria.scarica': "Descargar",
  'tesoreria.segna-pagati': "Marcar pagados",
  'tesoreria.segna-accreditata': "Marcar abonada",
  'tesoreria.niente-distinte': "Aún no hay remesas: se preparan desde los vencimientos.",
  'tesoreria.nota-distinte': "El fichero se sube a la banca online (Ri.Ba. en formato CBI, SDD y transferencias en SEPA XML). Cuando el banco abona la remesa, la conciliación la propone sola.",
  'tesoreria.salvate': "Ajustes guardados",
  'tesoreria.sia': "Código SIA",
  'tesoreria.bic': "BIC de tu banco (opcional)",
  'tesoreria.id-creditore': "Identificador de acreedor SEPA (para SDD)",
  'tesoreria.saldo-banca': "Saldo de la cuenta",
  'tesoreria.saldo-data': "Saldo a fecha",
  'tesoreria.sequenza-sdd': "Tipo de adeudo SDD",
  'tesoreria.seq-rcur': "Recurrente (RCUR)",
  'tesoreria.seq-frst': "Primero de una serie (FRST)",
  'tesoreria.seq-ooff': "Único (OOFF)",
  'tesoreria.sezione-movimenti': "Sección de movimientos bancarios",
  'tesoreria.ritardo-clienti': "En la previsión, desplaza los cobros según el retraso medio de cada cliente",
  'tesoreria.salva': "Guardar",
  'tesoreria.banca-azienda': "La cuenta de la empresa",
  'tesoreria.iban-azienda': "IBAN usado para Ri.Ba., SDD y transferencias: {iban}",
  'tesoreria.manca-iban': "Falta el IBAN de la empresa.",
  'tesoreria.dati-azienda': "Datos de la empresa",
  'tesoreria.nota-sia': "El código SIA y el identificador de acreedor te los da el banco al activar Ri.Ba. y SDD. El identificador propuesto se calcula con el NIF: compruébalo con el banco.",
  'tesoreria.sezioni': "Secciones",
  'tesoreria.sezioni-mancano': "Faltan «Movimientos bancarios» o «Previsiones de caja», y los campos de pago de clientes y proveedores (condiciones, IBAN, mandato SDD).",
  'tesoreria.sezioni-ci-sono': "Están todas.",
  'tesoreria.termini': "Condiciones de pago",
  'tesoreria.termini-nota': "Se escriben en la ficha del cliente o del proveedor. DF = fecha de factura, FM = fin de mes, +10 = el día 10 del mes siguiente. 30, 60 y 90 días cuentan como meses.",
};
