export default {
  'viste.cerca-in': 'Buscar en {nome}…',
  'viste.nuovo': '+ Nuevo',
  'viste.tabella': 'Tabla',
  'viste.kanban': 'Kanban',
  'viste.archiviati': 'Archivados',
  'viste.viste-salvate': 'Vistas guardadas',
  'viste.colonne': 'Columnas',
  'viste.raggruppa': 'Agrupar',
  'viste.senza-gruppi': 'Sin grupos',
  'viste.gruppi-per': 'Grupos: {nome}',
  'viste.salva-vista': 'Guardar vista',
  'viste.tutti': 'Todos',
  'viste.per-tutti': 'Para todos',
  'viste.mie': 'Mías',
  'viste.filtri-tolti': 'Algunos filtros de esta vista usan campos que no ves: los he quitado',
  'viste.salva-modifiche': 'Guardar cambios…',
  'viste.esempio-vista': 'P. ej. Para entregar esta semana',
  'viste.nome-vista': 'Ponle un nombre a la vista',
  'viste.salvata-tutti': 'Vista guardada para todos',
  'viste.salvata-te': 'Vista guardada para ti',
  'viste.vista-nome': 'Vista «{nome}»',
  'viste.salva-questa': 'Guardar esta vista',
  'viste.cosa-salva': 'Filtros, columnas, grupos y orden actuales.',
  'viste.la-vedono-tutti': 'La ven todos',
  'viste.solo-tu': 'Solo la verás tú.',
  'viste.elimina': 'Eliminar',
  'viste.elimina-vista': '¿Eliminar la vista «{nome}»?',
  'viste.vista-eliminata': 'Vista eliminada',
  'viste.salva-nuova': 'Guardar como nueva',
  'viste.aggiorna': 'Actualizar',
  'viste.salva': 'Guardar',
  'viste.come-inizio': 'Como al principio',
  'viste.nessuno': 'Ninguno',
  'viste.nessun-risultato': 'Sin resultados.',
  'viste.niente-archivio': 'Nada en el archivo.',
  'viste.ancora-nessuno': 'Todavía no hay nada en {nome}.',
  'viste.crea-primo': '+ Crear el primero',
  'viste.totale': 'Total ({n})',
  'viste.prime-di': 'Muestro los primeros {k} de {n} (los totales cuentan todos)',
  'viste.in-tutto': { one: '{n} en total', other: '{n} en total' },
  'viste.crea': 'Crear',
  'viste.creato': 'Creado',
  'viste.salvato': 'Guardado',
  'viste.nuovo-in': 'Nuevo en {nome}',
  'viste.archivia': 'Archivar',
  'viste.archiviare': '¿Archivar? Se puede restaurar desde el archivo.',
  'viste.archiviato': 'Archivado',
  'viste.ripristina': 'Restaurar',
  'viste.ripristinato': 'Restaurado',
  'viste.storia': 'Historial',
  'viste.archiviato-min': 'archivado',
  'viste.automazione': 'automatización',
  'viste.storia-creato': 'creado',
  'viste.storia-ripristinato': 'restaurado',
  'viste.non-si-passa': 'Desde «{da}» no se puede pasar aquí',
  'viste.al-salvataggio': 'al guardar',
  'viste.piu-immagine': '+ Imagen',
  'viste.piu-file': '+ Archivo',
  'viste.non-immagine': '«{nome}» no es una imagen',
  'viste.o-trascina': 'o arrástralo aquí',
  'viste.righe-non-trovata': 'No se encuentra la entidad de las líneas',
  'viste.aggiungi-riga': '+ Añadir línea',
  'viste.creato-il': 'Creado el',
  'viste.modificato-il': 'Modificado el',
  'viste.periodo-oggi': 'hoy',
  'viste.periodo-ieri': 'ayer',
  'viste.periodo-settimana': 'esta semana',
  'viste.periodo-mese': 'este mes',
  'viste.periodo-ultimi_7': 'últimos 7 días',
  'viste.periodo-ultimi_30': 'últimos 30 días',
  'viste.periodo-anno': 'este año',
  'viste.op-uguale': 'es',
  'viste.op-diverso': 'no es',
  'viste.op-tra': 'entre',
  'viste.op-contiene': 'contiene',
  'viste.op-inizia': 'empieza por',
  'viste.op-vuoto': 'está vacío',
  'viste.op-nonvuoto': 'no está vacío',
  'viste.op-in': 'es uno de',
  'viste.op-prima': 'antes del',
  'viste.op-dopo': 'desde el',
  'viste.op-vero': 'es verdadero',
  'viste.op-falso': 'es falso',
  'viste.o': ' o ',
  'viste.tra-e': '{a} y {b}',
  'viste.io': 'yo',
  'viste.me': 'mí',
  'viste.io-maiuscolo': 'Yo',
  'viste.piu-filtro': '+ Filtro',
  'viste.cambia-filtro': 'Cambiar el filtro',
  'viste.togli-tutti': 'Quitar todos',
  'viste.scegli-campo': 'Elige el campo…',
  'viste.nel-periodo': 'en el periodo',
  'viste.testo': 'texto',
  'viste.scegli-un-campo': 'Elige un campo',
  'viste.manca-valore': 'Falta el valor',
  'viste.nuovo-filtro': 'Nuevo filtro',
  'viste.applica': 'Aplicar',
};
