// Il modulo WhatsApp dell'interfaccia (web/moduli/whatsapp.js): conversazioni, modelli, automazioni, impostazioni.
export default {
  'whatsapp.forse-stop': 'Parece una petición de no recibir más mensajes',
  'whatsapp.segna-stop': 'Marcar STOP',
  'whatsapp.s-approvato': "Aprobada",
  'whatsapp.s-in_attesa': "Pendiente",
  'whatsapp.s-rifiutato': "Rechazada",
  'whatsapp.s-in_pausa': "En pausa",
  'whatsapp.s-disattivato': "Desactivada",
  'whatsapp.s-inviato': "Enviado",
  'whatsapp.s-consegnato': "Entregado",
  'whatsapp.s-letto': "Leído",
  'whatsapp.s-fallito': "Fallido",
  'whatsapp.s-bloccato': "Detenido",
  'whatsapp.s-coda': "En cola",
  'whatsapp.s-ricevuto': "Recibido",
  'whatsapp.finestra-aperta': "Ventana abierta hasta las {ora}",
  'whatsapp.finestra-chiusa': "Ventana cerrada: hace falta una plantilla",
  'whatsapp.attivo': "Activo: {nome}",
  'whatsapp.nessuno': "Ningún servicio de WhatsApp activo.",
  'whatsapp.vai-connettori': "Conéctalo desde los conectores",
  'whatsapp.conversazioni': "Conversaciones",
  'whatsapp.modelli': "Plantillas",
  'whatsapp.automazioni': "Automatizaciones de WhatsApp",
  'whatsapp.impostazioni': "Ajustes",
  'whatsapp.vuoto': "Todavía no hay mensajes.",
  'whatsapp.scegli': "Elige una conversación.",
  'whatsapp.c-servizio': "Servicio",
  'whatsapp.c-marketing': "Promociones",
  'whatsapp.si-no-si': "sí",
  'whatsapp.si-no-no': "no",
  'whatsapp.fonte-chiedi': "¿Cómo recogiste la elección? (p. ej. formulario en tienda, web, de palabra)",
  'whatsapp.testo-chiedi': "Las palabras exactas que el cliente aceptó:",
  'whatsapp.testo-predefinito': "Acepto recibir mensajes de WhatsApp de este negocio. Puedo escribir STOP en cualquier momento.",
  'whatsapp.ok-servizio': "Consentimiento de servicio",
  'whatsapp.ok-marketing': "Consentimiento de promociones",
  'whatsapp.revoca': "Revocar",
  'whatsapp.sconosciuto': "Número fuera de la agenda.",
  'whatsapp.crea-cliente': "Crear cliente",
  'whatsapp.crea-lead': "Crear contacto por calificar",
  'whatsapp.scrivi': "Escribe una respuesta…",
  'whatsapp.serve-modello': "Fuera de la ventana de 24 horas: elige una plantilla aprobada",
  'whatsapp.testo-libero': "Texto libre",
  'whatsapp.scegli-modello': "Elige una plantilla",
  'whatsapp.k-servizio': "Servicio",
  'whatsapp.k-utility': "Utilidad",
  'whatsapp.k-marketing': "Marketing",
  'whatsapp.k-authentication': "Autenticación",
  'whatsapp.costo': "Coste estimado",
  'whatsapp.inviato': "Mensaje enviado",
  'whatsapp.invia': "Enviar",
  'whatsapp.anteprima': "Vista previa",
  'whatsapp.sincronizzati': "Plantillas actualizadas",
  'whatsapp.sincronizza': "Sincronizar plantillas",
  'whatsapp.salvato': "Guardado",
  'whatsapp.modelli-nota': "Cada variable {{n}} toma el valor de un campo: por ejemplo cliente.nome o riga.quando.",
  'whatsapp.nessun-modello': "Sin plantillas: sincronízalas o crea una.",
  'whatsapp.corpo-esempio': "Hola {{1}}, tu pedido está listo.",
  'whatsapp.esempi-esempio': "Mario; martes a las 15",
  'whatsapp.nuovo-modello': "Nueva plantilla",
  'whatsapp.nuovo-nota': "Meta la revisa antes de aprobarla, normalmente en pocos minutos. Cada variable necesita un ejemplo. Las plantillas con un PDF en el encabezado se crean en WhatsApp Manager.",
  'whatsapp.nome': "Nombre (minúsculas, números, _)",
  'whatsapp.categoria': "Categoría",
  'whatsapp.lingua': "Idioma",
  'whatsapp.testo': "Texto",
  'whatsapp.esempi': "Ejemplos de las variables, separados por ;",
  'whatsapp.mandato-a-meta': "Plantilla enviada a aprobación",
  'whatsapp.manda-approvazione': "Enviar a aprobación",
  'whatsapp.automazioni-nota': "Activa las que necesites, elige la plantilla y los tiempos. Antes de cada envío Lumi comprueba consentimiento, STOP, horas de silencio y límites.",
  'whatsapp.o-ore': "Horas antes (p. ej. 24, 2)",
  'whatsapp.o-giorni': "Después de cuántos días",
  'whatsapp.o-mesi': "Inactivo desde hace meses",
  'whatsapp.o-link': "Enlace para la reseña",
  'whatsapp.o-testo': "Texto de la respuesta",
  'whatsapp.esempio-da-approvare': "Ejemplo de plantilla: créala y haz que la aprueben, luego elígela aquí.",
  'whatsapp.mancano': "Variables sin valor: {n}",
  'whatsapp.salva': "Guardar",
  'whatsapp.r-promemoria': "Recordatorio de cita",
  'whatsapp.r-conferma': "Confirmación de reserva",
  'whatsapp.r-pronto': "Pedido listo o enviado",
  'whatsapp.r-documento': "Factura o presupuesto con PDF",
  'whatsapp.r-sollecito': "Recordatorio de pago",
  'whatsapp.r-recensione': "Solicitud de reseña",
  'whatsapp.r-compleanno': "Felicitación de cumpleaños",
  'whatsapp.r-riattivazione': "Reactivar clientes inactivos",
  'whatsapp.r-fuori_orario': "Respuesta fuera de horario",
  'whatsapp.rd-promemoria': "Un mensaje antes de la cita (24 y 2 horas antes, o como quieras).",
  'whatsapp.rd-conferma': "En cuanto se crea una reserva.",
  'whatsapp.rd-pronto': "Cuando el estado pasa a listo o enviado, con el número de seguimiento si lo hay.",
  'whatsapp.rd-documento': "Cuando la factura se emite o el presupuesto se envía: el PDF va con una plantilla con documento en el encabezado.",
  'whatsapp.rd-sollecito': "Cada mañana, para las facturas vencidas hace N días (una vez por factura).",
  'whatsapp.rd-recensione': "N días después de la venta, con el enlace a tu página de reseñas.",
  'whatsapp.rd-compleanno': "La mañana del cumpleaños del cliente.",
  'whatsapp.rd-riattivazione': "A quien no vuelve desde hace N meses, una sola vez.",
  'whatsapp.rd-fuori_orario': "Cuando un cliente escribe con el negocio cerrado: texto libre, como mucho una vez cada 12 horas.",
  'whatsapp.serve-marketing': "Promocional: solo a quien aceptó las promociones, nunca en horas de silencio.",
  'whatsapp.non-possibile': "Tu gestión no tiene las secciones o campos que necesita esta automatización.",
  'whatsapp.modello': "Plantilla",
  'whatsapp.i-prefisso': "Prefijo predeterminado",
  'whatsapp.i-silenzio-da': "Silencio desde las",
  'whatsapp.i-silenzio-a': "hasta las",
  'whatsapp.i-silenzio-tutti': "Silencio también para los mensajes automáticos de servicio",
  'whatsapp.i-limite-giorno': "Plantillas al día, en total",
  'whatsapp.i-limite-cliente': "Plantillas al día por cliente",
  'whatsapp.i-marketing-giorni': "Una promoción cada cuántos días",
  'whatsapp.i-sconosciuti': "Quien escribe y no está en la agenda",
  'whatsapp.i-apre': "Abre a las",
  'whatsapp.i-chiude': "Cierra a las",
  'whatsapp.i-giorni': "Días abiertos (0 = domingo)",
  'whatsapp.i-t-marketing': "Marketing, € por mensaje",
  'whatsapp.i-t-utility': "Utilidad, € por mensaje",
  'whatsapp.i-t-authentication': "Autenticación, € por mensaje",
  'whatsapp.i-t-servizio': "Servicio, € más allá de la cuota gratuita",
  'whatsapp.i-t-servizioGratisMese': "Mensajes de servicio gratis al mes (vacío = todos)",
  'whatsapp.i-t-twilio': "Recargo de Twilio, € por mensaje",
  'whatsapp.sc-chiedi': "Pregúntame (queda como número)",
  'whatsapp.sc-cliente': "Crear un cliente",
  'whatsapp.sc-lead': "Crear un contacto por calificar",
  'whatsapp.webhook': "Dirección del webhook",
  'whatsapp.webhook-meta': "Pégalo en Meta (WhatsApp → Configuración) con el token de verificación de la página del conector y suscríbete a messages y message_template_status_update. Debe ser accesible desde internet en https.",
  'whatsapp.webhook-360': "Lumi lo registra solo en 360dialog cuando la dirección pública está en la página del conector.",
  'whatsapp.webhook-twilio': "Pégalo en el remitente de WhatsApp de Twilio como dirección de mensajes entrantes. La dirección pública del conector debe ser la que ve Twilio.",
  'whatsapp.apri-connettore': "Abrir el conector",
  'whatsapp.costi-mese': "Este mes",
  'whatsapp.nessun-costo': "Ningún mensaje de pago este mes.",
  'whatsapp.costi-nota': "Estimación con las tarifas de Meta para Italia ({data}): vale la factura de Meta o de tu proveedor.",
  'whatsapp.regole': "Reglas de envío",
  'whatsapp.tariffe': "Tarifas",
  'whatsapp.tariffe-nota': "Meta actualiza la tarifa cada trimestre: corrige aquí los importes si cambian.",
  'whatsapp.registro': "Mensajes detenidos o fallidos",
  'whatsapp.registro-vuoto': "Nada que señalar.",
  'whatsapp.storia': "Historial de WhatsApp",
  'whatsapp.senza-numero': "El cliente no tiene número de teléfono.",
  'whatsapp.apri-chat': "Abrir la conversación",
};
