// Server messages in English (same keys as it.js).
export default {
  'accedi': 'Sign in to continue',
  'configurato': 'Already set up',
  'manca-azienda': 'The company name is missing',
  'tentativi': 'Too many attempts: try again in a few minutes',
  'no-schema': 'You can\'t customise the system',
  'id-diverso': 'Mismatched id',
  'no-xkubo': 'Request without the X-Kubo header',
  'troppo-grande': 'Too large',
  'json': 'Invalid JSON',
  'non-trovato': 'Not found',
  'interno': 'Internal error',
  'token-password': 'A token can\'t change passwords or PINs',
  'servono-nome-email': 'Name and email are required',
  'password-corta': 'The password must be at least 8 characters',
  'pin': 'The PIN must be 4–8 digits',
  'email-usata': 'A user with this email already exists',
  'credenziali': 'Wrong email or password',
  'pin-sbagliato': 'Wrong PIN',
  'utente-sconosciuto': 'Unknown user',
  'titolare-attivo': 'At least one active owner is required',
  'permesso': 'You don\'t have permission',
  'ruolo-titolare': 'The owner role can\'t be changed',
  'permesso-vedere': 'You don\'t have permission to view “{entita}”',
  'permesso-creare': 'You don\'t have permission to create in “{entita}”',
  'permesso-modificare': 'You don\'t have permission to edit “{entita}”',
  'permesso-eliminare': 'You don\'t have permission to delete in “{entita}”',
  'modello-sconosciuto': 'Unknown template',
  'lingua-sconosciuta': 'Unknown language',
  'valuta-sconosciuta': 'Unknown currency',
  'entita-sconosciuta': 'Unknown entity “{id}”',
  'deve-numero': '“{campo}” must be a number',
  'deve-importo': '“{campo}” must be an amount',
  'data-non-valida': '“{campo}”: invalid date (YYYY-MM-DD)',
  'data-ora-non-valida': '“{campo}”: invalid date and time',
  'email-non-valida': '“{campo}”: invalid email',
  'opzione-sconosciuta': '“{campo}”: unknown option “{valore}”',
  'stato-sconosciuto': '“{campo}”: unknown status “{valore}”',
  'transizione': '“{campo}”: can\'t go from “{da}” to “{a}”',
  'non-trovo': '“{campo}”: can\'t find “{valore}”',
  'utente-campo': '“{campo}”: unknown user',
  'allegato': '“{campo}”: invalid attachment',
  'unico': '“{campo}” must be unique: this value already exists',
  'filtro-campo': 'Filter on an unknown field “{campo}”',
  'operatore': 'Unknown operator “{op}”',
  'obbligatorio': '“{campo}” is required',
  'non-campo-di': '“{campo}” is not a field of {entita}',
  'non-modificabile': '“{campo}” can’t be changed',
  'percorso-non-valido': 'Invalid path',
  'id-entita': 'Invalid entity id “{id}” (lowercase, digits, _)',
  'manca-nome': 'the name is missing',
  'manca-campi': 'the field list is missing',
  'dove-campo': 'field “{id}”',
  'dove-azione': 'action {n}',
  'id-non-valido': 'invalid id',
  'id-ripetuto': 'duplicate id',
  'tipo-sconosciuto': 'unknown type “{tipo}”',
  'servono-opzioni': 'options are required',
  'opzione-id-nome': 'every option needs an id and a name',
  'transizione-sconosciuta': 'transition to an unknown status “{stato}”',
  'collegata-sconosciuta': 'unknown linked entity “{entita}”',
  'righe-sconosciuta': 'unknown line entity “{entita}”',
  'righe-relazione': '“{campo}” must be a link to “{entita}”',
  'manca-formato': 'the format is missing (e.g. F-{AAAA}-{N:4})',
  'formula-campo': 'the formula uses “{nome}”, which isn\'t a field',
  'non-esiste': '“{nome}” doesn\'t exist',
  'formula-non-valida': 'invalid formula ({_errore})',
  'titolo-sconosciuto': 'title: unknown field “{campo}”',
  'definizione': 'Invalid definition',
  'valori-tipo': 'field “{id}”: {n} values can\'t become {tipo} (e.g. “{esempio}”)',
  'valori-ripetuti': 'field “{id}”: there are already duplicate values, so it can\'t be unique',
  'perderebbe': 'This change would lose data',
  'entita-sconosciuta-schema': 'Unknown entity “{id}”',
  'usata': 'The entity is used by others',
  'automazione': 'Invalid automation',
  'entita-sconosciuta-min': 'unknown entity “{entita}”',
  'quando': 'invalid “when”: {valore}',
  'campo-sconosciuto-min': 'unknown field “{campo}”',
  'servono-azioni': 'actions are required',
  'composto': '{_dove}: {_resto}',
  'virgolette': 'Unclosed quotes',
  'carattere': 'Invalid character “{c}”',
  'parentesi': 'A closing parenthesis is missing',
  'atteso': 'Expected {simbolo}',
  'funzione': 'Unknown function {nome}',
  'incompleta': 'Incomplete formula',
  'inatteso': 'Unexpected symbol',
  'campo-formula': 'Unknown field “{nome}”',
  'formula': 'Invalid formula',
  'senza-date': '“{entita}” has no date fields',
  'periodo-agenda': 'Invalid period (from and to as YYYY-MM-DD)',
  'due-mesi': 'Two months at most at a time',
  'solo-cruscotto': 'Only people who customise the system can change the dashboard',
  'widget': 'Unknown widget type',
  'nome-vista': 'Give the view a name',
  'viste-tutti': 'Only people who customise the system can save views for everyone',
  'vista-non-trovata': 'View not found',
  'periodo-sconosciuto': 'Unknown period “{nome}”',
  'misura': 'Unknown measure “{misura}”',
  'campo-sconosciuto': 'Unknown field “{campo}”',
  'raggruppa': 'Can\'t group by “{campo}”',
  'periodo': 'Invalid period (YYYY-MM-DD)',
  'serve-data': 'The period needs a date field',
  'file-vuoto': 'The file is empty',
  'file-grande': 'The file is too large: {mb} MB at most',
  'troppi-file': 'Too many files uploaded in the last few hours: try again later',
  'caricamento': 'Unknown upload',
  'fuori-ordine': 'Chunk out of order',
  'pezzo': 'Invalid chunk',
  'file-non-arrivato': '“{campo}”: the file “{file}” didn\'t arrive, upload it again',
  'file-supera': '“{campo}”: “{file}” is over {mb} MB',
  'non-immagine': '“{campo}”: “{file}” isn\'t an image',
  'file-non-trovato': 'File not found',
  'token-gestione': 'A token can\'t manage tokens or webhooks: sign in to the app',
  'nome-token': 'Give the token a name (e.g. “Website”, “Accounts”)',
  'scadenza': 'Invalid expiry',
  'token-sconosciuto': 'Unknown token',
  'solo-webhook': 'Only the owner manages webhooks',
  'indirizzo': 'Invalid address',
  'http': 'The address must start with http:// or https://',
  'webhook': 'Unknown webhook',
  'import-non-arrivato': 'The file didn\'t arrive: upload it again',
  'import-leggere': 'Can\'t read the file: is it an .xlsx or a .csv?',
  'sezione': 'Unknown section',
  'sezione-nome': 'Unknown section “{id}”',
  'import-nuovi': 'Only people who can customise create new sections and fields',
  'nome-sezione': 'Give the new section a name',
  'una-colonna': 'Choose at least one column',
  'nessuna-colonna': 'No column is matched to a field',
  'doppioni': 'Unknown field for duplicates',
  'backup': 'Only the owner downloads the backup, from the app',
  'xlsx': 'The file isn\'t a valid .xlsx',
  'xlsx-rovinato': 'The .xlsx file is damaged',
  'grande': 'The file is too large',
  'zip': 'Unsupported zip compression',
  'nessun-foglio': 'There\'s no sheet in the file',
  'troppe-righe': 'The sheet has more than {n} rows: split it into several files',
  'xls': 'The old .xls format can\'t be read: in Excel use “Save as” → .xlsx or .csv',
  'foglio': 'An .xlsx or .csv sheet is needed',
  'non-numero': '“{valore}” isn\'t a number',
  'non-importo': '“{valore}” isn\'t an amount',
  'si-no': '“{valore}”: write yes or no',
  'non-data': '“{valore}” isn\'t a date (e.g. 31/12/2026)',
  'non-data-ora': '“{valore}” isn\'t a date and time (e.g. 31/12/2026 14:30)',
  'non-opzione': '“{valore}” isn\'t one of the options of “{campo}”',
  'non-vedere': 'You can\'t view “{entita}”',
  'non-c-e': '“{valore}” isn\'t in “{entita}”',
  'piu-di-uno': '“{valore}”: there\'s more than one with this name in “{entita}”',
  'non-persona': '“{valore}” isn\'t a user of the system',
  'lumi-titolare': 'Only the owner changes Lumi\'s settings',
  'lumi-chiave': 'This doesn\'t look like a Claude key (it starts with “sk-”)',
  'lumi-limite': 'The limit goes from 1 to 600 questions a minute',
  'lumi-spento': 'Lumi is off: the owner can turn it back on in Admin → Lumi.',
  'lumi-troppe': 'Too many questions in a short time: try again in a minute.',
  'lumi-risposta': 'Lumi didn\'t answer',
  'lumi-campo': 'Unknown field “{campo}” in {entita}',
  'lumi-data': 'Invalid date “{valore}”: use YYYY-MM-DD',
  'lumi-archiviata': 'there\'s already an archived section “{nome}” ({id}): restore it from Customise or pick another name',
  'doc-impostare': 'Only people who can customise the system change these details',
  'doc-righe': 'This section has no lines to print',
  'doc-colonna': 'At least one column is needed',
  'doc-regime': 'Unknown tax regime',
  'doc-cap': 'The postcode has 5 digits',
  'doc-provincia': 'The province is a 2-letter code (e.g. MI)',
  'doc-colore': 'Invalid colour',
  'doc-aliquota': 'Invalid VAT rate',
  'doc-logo': 'The logo must be a PNG or JPEG image',
  'doc-logo-grande': 'The logo is too large: 300 KB at most',
  'doc-png': 'The file isn\'t a PNG or a JPEG',
  'doc-fattura-doppia': 'There\'s already an invoice number {numero} in {anno}',
  'doc-numero-usato': 'Number already used this year',
  'doc-modello-fatture': 'First add the “Invoices and e-invoicing” template (Customise → templates).',
  'doc-gia-fattura': 'It\'s already an invoice',
  'doc-cliente': 'There\'s no customer to invoice in “{entita}”',
  'doc-storna': 'Only an issued invoice can be reversed: this one is still a draft',
  'doc-nota': 'It\'s already a credit note',
  'xml-ragione': "Your company details are missing: the company name (Documents → Company details).",
  'xml-piva': "Your company's VAT number is missing.",
  'xml-piva-errata': "Your company's VAT number is wrong: {_errore}.",
  'xml-regime': "Your company's tax regime is missing (for example RF01 standard or RF19 flat-rate).",
  'xml-indirizzo-azienda': "Your company's full address is missing (street, 5-digit postcode, town).",
  'xml-bozza': "The invoice is still a draft: issue it so it gets its number.",
  'xml-annullata': "The invoice is cancelled: it isn't sent to SDI. If it was already sent, reverse it with a credit note.",
  'xml-numero': "The invoice number is missing.",
  'xml-data': "The invoice date is missing.",
  'xml-righe': "The invoice has no lines.",
  'xml-cliente-nome': "The customer's name or company name is missing.",
  'xml-cliente-piva': "The customer's VAT number or tax code is missing.",
  'xml-codice-pa': "The recipient code has 6 characters: it's a public body and needs the FPA12 format (not supported yet).",
  'xml-codice-7': "The customer's recipient code must have 7 characters.",
  'xml-codice-manca': "The customer's recipient code is missing: add it to their record (or the PEC address; if they have none, write 0000000).",
  'xml-indirizzo-cliente': "The customer's full address is missing (street, 5-digit postcode, town).",
  'xml-provincia': "The customer's province must be the 2-letter code (e.g. MI).",
  'xml-indirizzo-estero': "The customer's address is missing (street and city).",
  'xml-bollo': "Lines without VAT exceed €77.47: tick “Virtual €2 stamp duty”.",
  'xml-ritenuta': "With withholding tax, the type and reason are required.",
  'xml-totale': "The invoice total is zero or negative (to reverse one, use a credit note with positive amounts).",
  'xml-rate': "Payment in instalments with no instalments: add them, or choose “Full payment”.",
};
