// Mensajes del servidor en español (mismas claves que it.js).
export default {
  'accedi': 'Inicia sesión para continuar',
  'configurato': 'Ya está configurado',
  'manca-azienda': 'Falta el nombre de la empresa',
  'tentativi': 'Demasiados intentos: vuelve a probar en unos minutos',
  'no-schema': 'No puedes personalizar el sistema',
  'id-diverso': 'El id no coincide',
  'no-xkubo': 'Solicitud sin la cabecera X-Kubo',
  'troppo-grande': 'Demasiado grande',
  'json': 'JSON no válido',
  'non-trovato': 'No encontrado',
  'interno': 'Error interno',
  'token-password': 'Con un token no se cambian contraseñas ni PIN',
  'servono-nome-email': 'Hacen falta nombre y email',
  'password-corta': 'La contraseña debe tener al menos 8 caracteres',
  'pin': 'El PIN tiene de 4 a 8 cifras',
  'email-usata': 'Ya existe un usuario con este email',
  'credenziali': 'Email o contraseña incorrectos',
  'pin-sbagliato': 'PIN incorrecto',
  'utente-sconosciuto': 'Usuario desconocido',
  'titolare-attivo': 'Hace falta al menos un titular activo',
  'permesso': 'No tienes permiso',
  'ruolo-titolare': 'El rol de titular no se modifica',
  'permesso-vedere': 'No tienes permiso para ver «{entita}»',
  'permesso-creare': 'No tienes permiso para crear en «{entita}»',
  'permesso-modificare': 'No tienes permiso para modificar «{entita}»',
  'permesso-eliminare': 'No tienes permiso para eliminar en «{entita}»',
  'modello-sconosciuto': 'Plantilla desconocida',
  'lingua-sconosciuta': 'Idioma desconocido',
  'valuta-sconosciuta': 'Moneda desconocida',
  'entita-sconosciuta': 'Entidad desconocida «{id}»',
  'deve-numero': '«{campo}» debe ser un número',
  'deve-importo': '«{campo}» debe ser un importe',
  'data-non-valida': '«{campo}»: fecha no válida (AAAA-MM-DD)',
  'data-ora-non-valida': '«{campo}»: fecha y hora no válidas',
  'email-non-valida': '«{campo}»: email no válido',
  'opzione-sconosciuta': '«{campo}»: opción desconocida «{valore}»',
  'stato-sconosciuto': '«{campo}»: estado desconocido «{valore}»',
  'transizione': '«{campo}»: no se puede pasar de «{da}» a «{a}»',
  'non-trovo': '«{campo}»: no encuentro «{valore}»',
  'utente-campo': '«{campo}»: usuario desconocido',
  'allegato': '«{campo}»: adjunto no válido',
  'unico': '«{campo}» debe ser único: este valor ya existe',
  'filtro-campo': 'Filtro sobre un campo desconocido «{campo}»',
  'operatore': 'Operador desconocido «{op}»',
  'obbligatorio': '«{campo}» es obligatorio',
  'non-campo-di': '«{campo}» no es un campo de {entita}',
  'non-modificabile': '«{campo}» no se puede modificar',
  'percorso-non-valido': 'Ruta no válida',
  'id-entita': 'id de entidad no válido «{id}» (minúsculas, números, _)',
  'manca-nome': 'falta el nombre',
  'manca-campi': 'falta la lista de campos',
  'dove-campo': 'campo «{id}»',
  'dove-azione': 'acción {n}',
  'id-non-valido': 'id no válido',
  'id-ripetuto': 'id repetido',
  'tipo-sconosciuto': 'tipo desconocido «{tipo}»',
  'servono-opzioni': 'hacen falta opciones',
  'opzione-id-nome': 'cada opción necesita id y nombre',
  'transizione-sconosciuta': 'transición hacia un estado desconocido «{stato}»',
  'collegata-sconosciuta': 'entidad vinculada desconocida «{entita}»',
  'righe-sconosciuta': 'entidad de las líneas desconocida «{entita}»',
  'righe-relazione': '«{campo}» debe ser un vínculo hacia «{entita}»',
  'manca-formato': 'falta el formato (p. ej. F-{AAAA}-{N:4})',
  'formula-campo': 'la fórmula usa «{nome}», que no es un campo',
  'non-esiste': '«{nome}» no existe',
  'formula-non-valida': 'fórmula no válida ({_errore})',
  'titolo-sconosciuto': 'título: campo desconocido «{campo}»',
  'definizione': 'Definición no válida',
  'valori-tipo': 'campo «{id}»: {n} valores no se convierten en {tipo} (p. ej. «{esempio}»)',
  'valori-ripetuti': 'campo «{id}»: ya hay valores repetidos, no puede ser único',
  'perderebbe': 'El cambio perdería datos',
  'entita-sconosciuta-schema': 'Entidad desconocida «{id}»',
  'usata': 'La entidad la usan otras',
  'automazione': 'Automatización no válida',
  'entita-sconosciuta-min': 'entidad desconocida «{entita}»',
  'quando': '«cuándo» no válido: {valore}',
  'campo-sconosciuto-min': 'campo desconocido «{campo}»',
  'servono-azioni': 'hacen falta acciones',
  'composto': '{_dove}: {_resto}',
  'virgolette': 'Comillas sin cerrar',
  'carattere': 'Carácter no válido «{c}»',
  'parentesi': 'Falta un paréntesis de cierre',
  'atteso': 'Se esperaba {simbolo}',
  'funzione': 'Función desconocida {nome}',
  'incompleta': 'Fórmula incompleta',
  'inatteso': 'Símbolo inesperado',
  'campo-formula': 'Campo desconocido «{nome}»',
  'formula': 'Fórmula no válida',
  'senza-date': '«{entita}» no tiene campos de fecha',
  'periodo-agenda': 'Periodo no válido (desde y hasta en AAAA-MM-DD)',
  'due-mesi': 'Dos meses como máximo cada vez',
  'solo-cruscotto': 'Solo quien personaliza el sistema cambia el panel',
  'widget': 'Tipo de widget desconocido',
  'nome-vista': 'Ponle un nombre a la vista',
  'viste-tutti': 'Solo quien personaliza el sistema guarda vistas para todos',
  'vista-non-trovata': 'Vista no encontrada',
  'periodo-sconosciuto': 'Periodo desconocido «{nome}»',
  'misura': 'Medida desconocida «{misura}»',
  'campo-sconosciuto': 'Campo desconocido «{campo}»',
  'raggruppa': 'No se puede agrupar por «{campo}»',
  'periodo': 'Periodo no válido (AAAA-MM-DD)',
  'serve-data': 'El periodo necesita un campo de fecha',
  'file-vuoto': 'El archivo está vacío',
  'file-grande': 'El archivo es demasiado grande: {mb} MB como máximo',
  'troppi-file': 'Demasiados archivos subidos en las últimas horas: inténtalo más tarde',
  'caricamento': 'Subida desconocida',
  'fuori-ordine': 'Fragmento fuera de orden',
  'pezzo': 'Fragmento no válido',
  'file-non-arrivato': '«{campo}»: el archivo «{file}» no ha llegado, súbelo otra vez',
  'file-supera': '«{campo}»: «{file}» supera {mb} MB',
  'non-immagine': '«{campo}»: «{file}» no es una imagen',
  'file-non-trovato': 'Archivo no encontrado',
  'token-gestione': 'Con un token no se gestionan tokens ni webhooks: entra desde la aplicación',
  'nome-token': 'Ponle un nombre al token (p. ej. «Web», «Contabilidad»)',
  'scadenza': 'Caducidad no válida',
  'token-sconosciuto': 'Token desconocido',
  'solo-webhook': 'Solo el titular gestiona los webhooks',
  'indirizzo': 'Dirección no válida',
  'http': 'La dirección debe empezar por http:// o https://',
  'webhook': 'Webhook desconocido',
  'import-non-arrivato': 'El archivo no ha llegado: súbelo otra vez',
  'import-leggere': 'No puedo leer el archivo: ¿es un .xlsx o un .csv?',
  'sezione': 'Sección desconocida',
  'sezione-nome': 'Sección desconocida «{id}»',
  'import-nuovi': 'Solo quien puede personalizar crea secciones y campos nuevos',
  'nome-sezione': 'Ponle un nombre a la nueva sección',
  'una-colonna': 'Elige al menos una columna',
  'nessuna-colonna': 'Ninguna columna está asociada a un campo',
  'doppioni': 'Campo para duplicados desconocido',
  'backup': 'Solo el titular descarga la copia de seguridad, desde la aplicación',
  'xlsx': 'El archivo no es un .xlsx válido',
  'xlsx-rovinato': 'El archivo .xlsx está dañado',
  'grande': 'El archivo es demasiado grande',
  'zip': 'Compresión zip no compatible',
  'nessun-foglio': 'El archivo no tiene ninguna hoja',
  'troppe-righe': 'La hoja tiene más de {n} filas: divídela en varios archivos',
  'xls': 'El antiguo formato .xls no se lee: en Excel usa «Guardar como» → .xlsx o .csv',
  'foglio': 'Hace falta una hoja .xlsx o .csv',
  'non-numero': '«{valore}» no es un número',
  'non-importo': '«{valore}» no es un importe',
  'si-no': '«{valore}»: escribe sí o no',
  'non-data': '«{valore}» no es una fecha (p. ej. 31/12/2026)',
  'non-data-ora': '«{valore}» no es una fecha con hora (p. ej. 31/12/2026 14:30)',
  'non-opzione': '«{valore}» no está entre las opciones de «{campo}»',
  'non-vedere': 'No puedes ver «{entita}»',
  'non-c-e': '«{valore}» no está en «{entita}»',
  'piu-di-uno': '«{valore}»: en «{entita}» hay más de uno con este nombre',
  'non-persona': '«{valore}» no es un usuario del sistema',
  'lumi-titolare': 'Solo el titular cambia los ajustes de Lumi',
  'lumi-chiave': 'No parece una clave de Claude (empieza por «sk-»)',
  'lumi-limite': 'El límite va de 1 a 600 preguntas por minuto',
  'lumi-spento': 'Lumi está apagado: el titular lo vuelve a encender en Gestión → Lumi.',
  'lumi-troppe': 'Demasiadas preguntas en poco tiempo: vuelve a probar en un minuto.',
  'lumi-risposta': 'Lumi no ha respondido',
  'lumi-campo': 'Campo desconocido «{campo}» en {entita}',
  'lumi-data': 'Fecha no válida «{valore}»: usa AAAA-MM-DD',
  'lumi-archiviata': 'ya hay una sección archivada «{nome}» ({id}): restáurala desde Personalizar o elige otro nombre',
  'doc-impostare': 'Solo quien puede personalizar el sistema cambia estos datos',
  'doc-righe': 'Esta sección no tiene líneas para imprimir',
  'doc-colonna': 'Hace falta al menos una columna',
  'doc-regime': 'Régimen fiscal desconocido',
  'doc-cap': 'El código postal tiene 5 cifras',
  'doc-provincia': 'La provincia es la sigla de 2 letras (p. ej. MI)',
  'doc-colore': 'Color no válido',
  'doc-aliquota': 'Tipo de IVA no válido',
  'doc-logo': 'El logo debe ser una imagen PNG o JPEG',
  'doc-logo-grande': 'El logo es demasiado grande: 300 KB como máximo',
  'doc-png': 'El archivo no es un PNG ni un JPEG',
  'doc-fattura-doppia': 'Ya hay una factura número {numero} en {anno}',
  'doc-numero-usato': 'Número ya usado este año',
  'doc-modello-fatture': 'Añade antes la plantilla «Facturas y factura electrónica» (Personalizar → plantillas).',
  'doc-gia-fattura': 'Ya es una factura',
  'doc-cliente': 'En «{entita}» no hay ningún cliente al que facturar',
  'doc-storna': 'Solo se anula una factura emitida: esta todavía es un borrador',
  'doc-nota': 'Ya es una nota de crédito',
  'xml-ragione': "Faltan los datos de tu empresa: la razón social (Documentos → Datos de la empresa).",
  'xml-piva': "Falta el NIF-IVA de tu empresa.",
  'xml-piva-errata': "El NIF-IVA de tu empresa no es correcto: {_errore}.",
  'xml-regime': "Falta el régimen fiscal de tu empresa (por ejemplo RF01 ordinario o RF19 a tanto alzado).",
  'xml-indirizzo-azienda': "Falta la dirección completa de tu empresa (calle, código postal de 5 cifras, municipio).",
  'xml-bozza': "La factura todavía es un borrador: emítela para que reciba su número.",
  'xml-annullata': "La factura está anulada: no se envía al SDI. Si ya se había enviado, anúlala con una nota de crédito.",
  'xml-numero': "Falta el número de la factura.",
  'xml-data': "Falta la fecha de la factura.",
  'xml-righe': "La factura no tiene líneas.",
  'xml-cliente-nome': "Falta el nombre o la razón social del cliente.",
  'xml-cliente-piva': "Falta el NIF-IVA o el código fiscal del cliente.",
  'xml-codice-pa': "El código de destinatario tiene 6 caracteres: es una Administración Pública y necesita el formato FPA12 (todavía no compatible).",
  'xml-codice-7': "El código de destinatario del cliente debe tener 7 caracteres.",
  'xml-codice-manca': "Falta el código de destinatario del cliente: escríbelo en su ficha (o la PEC; si no tiene, escribe 0000000).",
  'xml-indirizzo-cliente': "Falta la dirección completa del cliente (calle, código postal de 5 cifras, municipio).",
  'xml-provincia': "La provincia del cliente se escribe con la sigla de 2 letras (p. ej. MI).",
  'xml-indirizzo-estero': "Falta la dirección del cliente (calle y ciudad).",
  'xml-bollo': "Las líneas sin IVA superan 77,47 €: marca «Timbre virtual de 2 €».",
  'xml-ritenuta': "Con la retención hacen falta el tipo y la causa.",
  'xml-totale': "El total de la factura es cero o negativo (para anular usa una nota de crédito con importes positivos).",
  'xml-rate': "Pago a plazos sin plazos: añádelos o elige «Pago completo».",
  // fatture complete (fatture*.js, documenti-xml.js)
  'fat-autofattura-fornitore': "Falta el proveedor de la autofactura.",
  'fat-autofattura-collegata': "Falta la factura del proveedor que hay que integrar (número y fecha).",
  'fat-codice-ufficio': "El código de oficina de la Administración Pública tiene 6 letras o cifras.",
  'fat-cig': "El CIG tiene 10 letras o cifras.",
  'fat-cup': "El CUP tiene 15 letras o cifras.",
  'fat-cig-documento': "Con el CIG o el CUP hace falta el número del pedido o del contrato.",
  'fat-forfettario-split': "En el régimen a tanto alzado no hay IVA: nada de pago dividido.",
  'fat-ritenuta-righe': "La retención no tiene líneas a las que aplicarse: quita «excluida de la retención» de al menos una línea.",
  'fat-cassa-tipo': "Elige la caja de previsión (por ejemplo TC22 INPS).",
  'fat-cassa-natura': "La caja de previsión no lleva IVA: elige la naturaleza (p. ej. N4 o N2.2).",
  'fat-ddt': "La factura diferida debe citar los albaranes: añade número y fecha de al menos uno.",
  'fat-pa-esigibilita': "Factura a la Administración Pública: elige la exigibilidad del IVA (normalmente «pago dividido»).",
  'fat-bloccata': "La factura {numero} está emitida: ya no se modifica. Corrígela con una nota de crédito o de débito.",
  'fat-non-elimina': "La factura {numero} está emitida: no se elimina, dejaría un hueco en la numeración. Anúlala con una nota de crédito.",
  'fat-bloccato-campo': "Bloqueado tras la emisión",
  'fat-vuoto': "El archivo está vacío",
  'fat-grande': "El archivo es demasiado grande: 5 MB como máximo",
  'fat-non-fattura': "El archivo no es una factura electrónica",
  'fat-non-p7m': "El archivo no es una factura firmada (.p7m)",
  'fat-p7m-staccata': "La firma está «separada»: el .p7m no contiene la factura",
  'fat-p7m-rotto': "El archivo .p7m está dañado o incompleto",
  'fat-no-fornitori': "Falta la sección «Proveedores»",
  'fat-no-xml': "Esta factura recibida no tiene el archivo XML",
  'fat-gia-integrata': "Esta factura recibida ya tiene su integración",
  // avvio guidato, app desktop (backup, aggiornamenti, QR, rete), sicurezza
  'avvio-solo-titolare': "Solo el titular puede hacerlo",
  'avvio-esempi-ci-sono': "Los datos de ejemplo ya están",
  'agg-risposta': "La comprobación de versiones respondió {stato}",
  'agg-inattesa': "Respuesta inesperada",
  'bk-percorso': "Escribe la ruta completa de la carpeta (por ejemplo {a} o {b})",
  'bk-fuori-dati': "Elige una carpeta fuera de la de los datos",
  'bk-no-cartella': "Esta base de datos no tiene carpeta (está en memoria)",
  'bk-non-kubo': "El archivo no es una base de datos de Kubo",
  'bk-in-memoria': "Esta base de datos está en memoria",
  'qr-lungo': "Texto demasiado largo para el código QR",
  'rete-ipv4': "Dirección IPv4 no válida",
  'rete-scrivi': "Escribe una dirección o un código",
  'dk-solo-titolare': "Solo el titular gestiona copias de seguridad y actualizaciones",
  'dk-backup-sconosciuto': "Copia de seguridad desconocida",
  'dk-ripristino-corso': "Hay una restauración en curso",
  'dk-db-memoria': "La base de datos está en memoria",
  'dk-conferma': "Hace falta la confirmación",
  'dk-file-piccolo': "El archivo está vacío o es demasiado pequeño para ser una copia de seguridad",
  'dk-non-scrivo': "No consigo escribir en la carpeta de copias de seguridad",
  'dk-non-backup': "El archivo no es una copia de seguridad de Kubo (hace falta un archivo .db)",
  'sic-solo-titolare': "Solo el titular cambia los ajustes de seguridad",
  'sic-cambia-password': "Antes de continuar, cambia la contraseña que te dieron",
  'sic-pin-password': "Para cambiar el PIN hace falta la contraseña actual",
  'sic-password-sbagliata': "La contraseña actual no es correcta",
  'sic-no-fattura': "Tu rol no exporta la factura electrónica",
  'sic-no-lumi': "Lumi no está activo para tu rol",
  'sic-tipo-file': "Este tipo de archivo no se puede adjuntar (programas, scripts y páginas web)",
  'sic-token-password': "Con un token no se cambia la contraseña",
  'sic-password-diversa': "La nueva contraseña debe ser distinta de la anterior",
  'sic-sessione': "Sesión desconocida",
  'sic-persona': "Persona desconocida",
  'sic-fuso': "Zona horaria desconocida (p. ej. Europe/Madrid)",
  'sic-titolare-tutto': "El titular siempre puede hacerlo todo",
  'sic-ruolo': "Rol desconocido",
  'avvio-codice': "Hace falta el código de inicio: está en la terminal o en el registro de Kubo",
  'pw-lunga': "La contraseña es demasiado larga",
  'pw-comune': "Esta contraseña es de las más usadas: elige otra",
  'pw-facile': "Esta contraseña es demasiado fácil de adivinar",
  'pw-nome': "La contraseña no puede ser tu nombre ni tu email",
  'pw-mescola': "Con menos de 12 caracteres, mezcla letras con números o símbolos",
  // gli strumenti di Lumi dai moduli e la scheda delle fatture (lumi-strumenti.js, lumidoc.js)
  'lumi-strumento-sconosciuto': 'Herramienta de Lumi desconocida «{nome}»',
  'lumi-strumento-permesso': 'No puedes usar esta herramienta de Lumi',
  'lumi-argomenti': 'Argumentos no válidos para {nome}: {_dettaglio}',
  'lumi-strumento-scrive': 'Esta herramienta escribe: primero la ficha de confirmación',
  'lumi-strumento-senza-scheda': 'Esta herramienta no tiene ficha de confirmación',
  'lumi-conferma-diversa': 'La confirmación no coincide con la ficha: vuelve a hacer la propuesta',
  'lumidoc-cliente': 'Cliente',
  'lumidoc-riga': '{quantita} × {prezzo} · IVA {iva} = {totale}',
  'lumidoc-altre-righe': 'Otras {n} líneas',
  'lumidoc-cassa': 'Contribución a la caja {aliquota}%',
  'lumidoc-imponibile': 'Base imponible',
  'lumidoc-iva': 'IVA',
  'lumidoc-bollo': 'Timbre',
  'lumidoc-bollo-tuo': '2 € a tu cargo',
  'lumidoc-totale': 'Total',
  'lumidoc-ritenuta': 'Retención {aliquota}%',
  'lumidoc-netto': 'Por cobrar',
  'lumidoc-av-sdi': 'Para la factura electrónica: {_messaggio}',
  'lumidoc-nuova': 'Nueva factura',
  'lumidoc-in-bozza': 'Se crea como borrador: la revisas y luego la emites.',
  'lumidoc-av-forfettario': 'Régimen a tanto alzado: líneas sin IVA (naturaleza N2.2) y sin retención.',
  'lumidoc-av-no-ritenuta': 'En el régimen a tanto alzado los honorarios no llevan retención: la he quitado.',
  'lumidoc-av-aliquota': 'Tipo de IVA del {aliquota}% inusual: en Italia son 4, 5, 10 y 22%.',
  'lumidoc-av-ritenuta': 'Retención del {aliquota}% como en tus facturas anteriores.',
  'lumidoc-av-cassa': 'Contribución a la caja del {aliquota}% como en tus facturas anteriores.',
  'lumidoc-av-bollo': 'Timbre de 2 € añadido: las operaciones sin IVA superan 77,47 €.',
  'lumidoc-emetti': 'Emitir la factura',
  'lumidoc-numero': 'Número',
  'lumidoc-numero-nuovo': 'el siguiente de la serie',
  'lumidoc-data': 'Fecha',
  'lumidoc-dopo-emissione': 'Una vez emitida ya no se modifica: se corrige con una nota de crédito.',
  'lumidoc-nota': 'Nota de crédito',
  'lumidoc-nota-parziale': 'Nota de crédito parcial',
  'lumidoc-storna': 'Anula',
  'lumidoc-storna-di': 'factura {numero} del {data}',
  'lumidoc-av-gia-stornato': 'De esta factura ya se han anulado {importo}.',
};
