// Messages du serveur en français (mêmes clés que it.js).
export default {
  'accedi': 'Connectez-vous pour continuer',
  'configurato': 'Déjà configuré',
  'manca-azienda': 'Il manque le nom de l\'entreprise',
  'tentativi': 'Trop de tentatives : réessayez dans quelques minutes',
  'no-schema': 'Vous ne pouvez pas personnaliser le logiciel',
  'id-diverso': 'Identifiant différent',
  'no-xkubo': 'Requête sans l\'en-tête X-Kubo',
  'troppo-grande': 'Trop volumineux',
  'json': 'JSON non valide',
  'non-trovato': 'Introuvable',
  'interno': 'Erreur interne',
  'token-password': 'Un jeton ne permet pas de changer mots de passe et PIN',
  'servono-nome-email': 'Le nom et l\'e-mail sont obligatoires',
  'password-corta': 'Le mot de passe doit contenir au moins 8 caractères',
  'pin': 'Le PIN compte de 4 à 8 chiffres',
  'email-usata': 'Un utilisateur avec cet e-mail existe déjà',
  'credenziali': 'E-mail ou mot de passe incorrect',
  'pin-sbagliato': 'PIN incorrect',
  'utente-sconosciuto': 'Utilisateur inconnu',
  'titolare-attivo': 'Il faut au moins un gérant actif',
  'permesso': 'Vous n\'avez pas l\'autorisation',
  'ruolo-titolare': 'Le rôle de gérant ne se modifie pas',
  'permesso-vedere': 'Vous n\'avez pas l\'autorisation de voir « {entita} »',
  'permesso-creare': 'Vous n\'avez pas l\'autorisation de créer dans « {entita} »',
  'permesso-modificare': 'Vous n\'avez pas l\'autorisation de modifier « {entita} »',
  'permesso-eliminare': 'Vous n\'avez pas l\'autorisation de supprimer dans « {entita} »',
  'modello-sconosciuto': 'Modèle inconnu',
  'lingua-sconosciuta': 'Langue inconnue',
  'valuta-sconosciuta': 'Devise inconnue',
  'entita-sconosciuta': 'Entité inconnue « {id} »',
  'deve-numero': '« {campo} » doit être un nombre',
  'deve-importo': '« {campo} » doit être un montant',
  'data-non-valida': '« {campo} » : date non valide (AAAA-MM-JJ)',
  'data-ora-non-valida': '« {campo} » : date et heure non valides',
  'email-non-valida': '« {campo} » : e-mail non valide',
  'opzione-sconosciuta': '« {campo} » : option inconnue « {valore} »',
  'stato-sconosciuto': '« {campo} » : statut inconnu « {valore} »',
  'transizione': '« {campo} » : impossible de passer de « {da} » à « {a} »',
  'non-trovo': '« {campo} » : « {valore} » introuvable',
  'utente-campo': '« {campo} » : utilisateur inconnu',
  'allegato': '« {campo} » : pièce jointe non valide',
  'unico': '« {campo} » doit être unique : cette valeur existe déjà',
  'filtro-campo': 'Filtre sur un champ inconnu « {campo} »',
  'operatore': 'Opérateur inconnu « {op} »',
  'obbligatorio': '« {campo} » est obligatoire',
  'non-campo-di': '« {campo} » n’est pas un champ de {entita}',
  'non-modificabile': '« {campo} » ne peut pas être modifié',
  'percorso-non-valido': 'Chemin non valide',
  'id-entita': 'identifiant d\'entité non valide « {id} » (minuscules, chiffres, _)',
  'manca-nome': 'le nom manque',
  'manca-campi': 'la liste des champs manque',
  'dove-campo': 'champ « {id} »',
  'dove-azione': 'action {n}',
  'id-non-valido': 'identifiant non valide',
  'id-ripetuto': 'identifiant en double',
  'tipo-sconosciuto': 'type inconnu « {tipo} »',
  'servono-opzioni': 'il faut des options',
  'opzione-id-nome': 'chaque option a besoin d\'un identifiant et d\'un nom',
  'transizione-sconosciuta': 'transition vers un statut inconnu « {stato} »',
  'collegata-sconosciuta': 'entité liée inconnue « {entita} »',
  'righe-sconosciuta': 'entité des lignes inconnue « {entita} »',
  'righe-relazione': '« {campo} » doit être un lien vers « {entita} »',
  'manca-formato': 'le format manque (ex. F-{AAAA}-{N:4})',
  'formula-campo': 'la formule utilise « {nome} », qui n\'est pas un champ',
  'non-esiste': '« {nome} » n\'existe pas',
  'formula-non-valida': 'formule non valide ({_errore})',
  'titolo-sconosciuto': 'titre : champ inconnu « {campo} »',
  'definizione': 'Définition non valide',
  'valori-tipo': 'champ « {id} » : {n} valeurs ne deviennent pas {tipo} (ex. « {esempio} »)',
  'valori-ripetuti': 'champ « {id} » : il y a déjà des doublons, il ne peut pas être unique',
  'perderebbe': 'La modification ferait perdre des données',
  'entita-sconosciuta-schema': 'Entité inconnue « {id} »',
  'usata': 'L\'entité est utilisée par d\'autres',
  'automazione': 'Automatisation non valide',
  'entita-sconosciuta-min': 'entité inconnue « {entita} »',
  'quando': '« quand » non valide : {valore}',
  'campo-sconosciuto-min': 'champ inconnu « {campo} »',
  'servono-azioni': 'il faut des actions',
  'composto': '{_dove} : {_resto}',
  'virgolette': 'Guillemets non fermés',
  'carattere': 'Caractère non valide « {c} »',
  'parentesi': 'Il manque une parenthèse fermante',
  'atteso': '{simbolo} attendu',
  'funzione': 'Fonction inconnue {nome}',
  'incompleta': 'Formule incomplète',
  'inatteso': 'Symbole inattendu',
  'campo-formula': 'Champ inconnu « {nome} »',
  'formula': 'Formule non valide',
  'senza-date': '« {entita} » n\'a pas de champ date',
  'periodo-agenda': 'Période non valide (du et au en AAAA-MM-JJ)',
  'due-mesi': 'Deux mois au maximum à la fois',
  'solo-cruscotto': 'Seuls ceux qui personnalisent le logiciel modifient le tableau de bord',
  'widget': 'Type de widget inconnu',
  'nome-vista': 'Donnez un nom à la vue',
  'viste-tutti': 'Seuls ceux qui personnalisent le logiciel enregistrent des vues pour tous',
  'vista-non-trovata': 'Vue introuvable',
  'periodo-sconosciuto': 'Période inconnue « {nome} »',
  'misura': 'Mesure inconnue « {misura} »',
  'campo-sconosciuto': 'Champ inconnu « {campo} »',
  'raggruppa': 'Impossible de regrouper par « {campo} »',
  'periodo': 'Période non valide (AAAA-MM-JJ)',
  'serve-data': 'La période nécessite un champ date',
  'file-vuoto': 'Le fichier est vide',
  'file-grande': 'Le fichier est trop volumineux : {mb} Mo au maximum',
  'troppi-file': 'Trop de fichiers envoyés ces dernières heures : réessayez plus tard',
  'caricamento': 'Envoi inconnu',
  'fuori-ordine': 'Morceau dans le désordre',
  'pezzo': 'Morceau non valide',
  'file-non-arrivato': '« {campo} » : le fichier « {file} » n\'est pas arrivé, envoyez-le à nouveau',
  'file-supera': '« {campo} » : « {file} » dépasse {mb} Mo',
  'non-immagine': '« {campo} » : « {file} » n\'est pas une image',
  'file-non-trovato': 'Fichier introuvable',
  'token-gestione': 'Un jeton ne gère ni les jetons ni les webhooks : passez par l\'application',
  'nome-token': 'Donnez un nom au jeton (ex. « Site », « Comptabilité »)',
  'scadenza': 'Échéance non valide',
  'token-sconosciuto': 'Jeton inconnu',
  'solo-webhook': 'Seul le gérant gère les webhooks',
  'indirizzo': 'Adresse non valide',
  'http': 'L\'adresse doit commencer par http:// ou https://',
  'webhook': 'Webhook inconnu',
  'import-non-arrivato': 'Le fichier n\'est pas arrivé : envoyez-le à nouveau',
  'import-leggere': 'Impossible de lire le fichier : est-ce un .xlsx ou un .csv ?',
  'sezione': 'Section inconnue',
  'sezione-nome': 'Section inconnue « {id} »',
  'import-nuovi': 'Seuls ceux qui peuvent personnaliser créent des sections et des champs',
  'nome-sezione': 'Donnez un nom à la nouvelle section',
  'una-colonna': 'Choisissez au moins une colonne',
  'nessuna-colonna': 'Aucune colonne n\'est associée à un champ',
  'doppioni': 'Champ des doublons inconnu',
  'backup': 'Seul le gérant télécharge la sauvegarde, depuis l\'application',
  'xlsx': 'Le fichier n\'est pas un .xlsx valide',
  'xlsx-rovinato': 'Le fichier .xlsx est endommagé',
  'grande': 'Le fichier est trop volumineux',
  'zip': 'Compression zip non prise en charge',
  'nessun-foglio': 'Le fichier ne contient aucune feuille',
  'troppe-righe': 'La feuille a plus de {n} lignes : divisez-la en plusieurs fichiers',
  'xls': 'L\'ancien format .xls n\'est pas lisible : dans Excel, faites « Enregistrer sous » → .xlsx ou .csv',
  'foglio': 'Il faut une feuille .xlsx ou .csv',
  'non-numero': '« {valore} » n\'est pas un nombre',
  'non-importo': '« {valore} » n\'est pas un montant',
  'si-no': '« {valore} » : écrivez oui ou non',
  'non-data': '« {valore} » n\'est pas une date (ex. 31/12/2026)',
  'non-data-ora': '« {valore} » n\'est pas une date avec l\'heure (ex. 31/12/2026 14:30)',
  'non-opzione': '« {valore} » ne fait pas partie des options de « {campo} »',
  'non-vedere': 'Vous ne pouvez pas voir « {entita} »',
  'non-c-e': '« {valore} » n\'est pas dans « {entita} »',
  'piu-di-uno': '« {valore} » : il y en a plusieurs avec ce nom dans « {entita} »',
  'non-persona': '« {valore} » n\'est pas un utilisateur du logiciel',
  'lumi-titolare': 'Seul le gérant modifie les réglages de Lumi',
  'lumi-chiave': 'Cela ne ressemble pas à une clé Claude (elle commence par « sk- »)',
  'lumi-limite': 'La limite va de 1 à 600 questions par minute',
  'lumi-spento': 'Lumi est éteint : le gérant le rallume dans Gestion → Lumi.',
  'lumi-troppe': 'Trop de questions en peu de temps : réessayez dans une minute.',
  'lumi-risposta': 'Lumi n\'a pas répondu',
  'lumi-campo': 'Champ inconnu « {campo} » dans {entita}',
  'lumi-data': 'Date non valide « {valore} » : utilisez AAAA-MM-JJ',
  'lumi-archiviata': 'il y a déjà une section archivée « {nome} » ({id}) : restaurez-la depuis Personnaliser ou choisissez un autre nom',
  'doc-impostare': 'Seuls ceux qui peuvent personnaliser le logiciel modifient ces données',
  'doc-righe': 'Cette section n\'a pas de lignes à imprimer',
  'doc-colonna': 'Il faut au moins une colonne',
  'doc-regime': 'Régime fiscal inconnu',
  'doc-cap': 'Le code postal a 5 chiffres',
  'doc-provincia': 'La province est le sigle de 2 lettres (ex. MI)',
  'doc-colore': 'Couleur non valide',
  'doc-aliquota': 'Taux de TVA non valide',
  'doc-logo': 'Le logo doit être une image PNG ou JPEG',
  'doc-logo-grande': 'Le logo est trop volumineux : 300 Ko au maximum',
  'doc-png': 'Le fichier n\'est ni un PNG ni un JPEG',
  'doc-fattura-doppia': 'Il existe déjà une facture numéro {numero} en {anno}',
  'doc-numero-usato': 'Numéro déjà utilisé cette année',
  'doc-modello-fatture': 'Ajoutez d\'abord le modèle « Factures et facture électronique » (Personnaliser → modèles).',
  'doc-gia-fattura': 'C\'est déjà une facture',
  'doc-cliente': 'Dans « {entita} », il n\'y a pas de client à facturer',
  'doc-storna': 'Seule une facture émise peut être annulée : celle-ci est encore un brouillon',
  'doc-nota': 'C\'est déjà un avoir',
  'xml-ragione': "Il manque les données de votre entreprise : la raison sociale (Documents → Données de l'entreprise).",
  'xml-piva': "Il manque le numéro de TVA de votre entreprise.",
  'xml-piva-errata': "Le numéro de TVA de votre entreprise est incorrect : {_errore}.",
  'xml-regime': "Il manque le régime fiscal de votre entreprise (par exemple RF01 ordinaire ou RF19 forfaitaire).",
  'xml-indirizzo-azienda': "Il manque l'adresse complète de votre entreprise (rue, code postal à 5 chiffres, commune).",
  'xml-bozza': "La facture est encore un brouillon : émettez-la pour qu'elle reçoive son numéro.",
  'xml-annullata': "La facture est annulée : elle n'est pas envoyée au SDI. Si elle l'a déjà été, annulez-la par un avoir.",
  'xml-numero': "Il manque le numéro de la facture.",
  'xml-data': "Il manque la date de la facture.",
  'xml-righe': "La facture n'a pas de lignes.",
  'xml-cliente-nome': "Il manque le nom ou la raison sociale du client.",
  'xml-cliente-piva': "Il manque le numéro de TVA ou le code fiscal du client.",
  'xml-codice-pa': "Le code destinataire a 6 caractères : c'est une administration publique, il faut le format FPA12 (pas encore pris en charge).",
  'xml-codice-7': "Le code destinataire du client doit comporter 7 caractères.",
  'xml-codice-manca': "Il manque le code destinataire du client : indiquez-le dans sa fiche (ou la PEC ; s'il n'en a pas, écrivez 0000000).",
  'xml-indirizzo-cliente': "Il manque l'adresse complète du client (rue, code postal à 5 chiffres, commune).",
  'xml-provincia': "La province du client s'écrit avec le sigle de 2 lettres (ex. MI).",
  'xml-indirizzo-estero': "Il manque l'adresse du client (rue et ville).",
  'xml-bollo': "Les lignes sans TVA dépassent 77,47 € : cochez « Timbre virtuel de 2 € ».",
  'xml-ritenuta': "Avec la retenue à la source, il faut le type et le motif.",
  'xml-totale': "Le total de la facture est nul ou négatif (pour une annulation, utilisez un avoir avec des montants positifs).",
  'xml-rate': "Paiement échelonné sans échéances : ajoutez-les ou choisissez « Paiement complet ».",
  // fatture complete (fatture*.js, documenti-xml.js)
  'fat-autofattura-fornitore': "Il manque le fournisseur de l'autofacture.",
  'fat-autofattura-collegata': "Il manque la facture du fournisseur à intégrer (numéro et date).",
  'fat-codice-ufficio': "Le code de bureau de l'Administration publique a 6 lettres ou chiffres.",
  'fat-cig': "Le CIG a 10 lettres ou chiffres.",
  'fat-cup': "Le CUP a 15 lettres ou chiffres.",
  'fat-cig-documento': "Avec le CIG ou le CUP, il faut le numéro de la commande ou du contrat.",
  'fat-forfettario-split': "Le régime forfaitaire n'a pas de TVA : pas d'autoliquidation fractionnée.",
  'fat-ritenuta-righe': "La retenue n'a aucune ligne à laquelle s'appliquer : décochez « exclue de la retenue » sur au moins une ligne.",
  'fat-cassa-tipo': "Choisissez la caisse de prévoyance (par exemple TC22 INPS).",
  'fat-cassa-natura': "La contribution à la caisse est sans TVA : choisissez la nature (ex. N4 ou N2.2).",
  'fat-ddt': "La facture différée doit citer les bons de livraison : ajoutez le numéro et la date d'au moins un.",
  'fat-pa-esigibilita': "Facture à l'Administration publique : choisissez l'exigibilité de la TVA (en général « paiement scindé »).",
  'fat-bloccata': "La facture {numero} est émise : elle ne se modifie plus. Corrigez-la avec un avoir ou une note de débit.",
  'fat-non-elimina': "La facture {numero} est émise : elle ne se supprime pas, cela laisserait un trou dans la numérotation. Annulez-la avec un avoir.",
  'fat-bloccato-campo': "Verrouillé après l'émission",
  'fat-vuoto': "Le fichier est vide",
  'fat-grande': "Le fichier est trop volumineux : 5 Mo au maximum",
  'fat-non-fattura': "Le fichier n'est pas une facture électronique",
  'fat-non-p7m': "Le fichier n'est pas une facture signée (.p7m)",
  'fat-p7m-staccata': "La signature est « détachée » : le .p7m ne contient pas la facture",
  'fat-p7m-rotto': "Le fichier .p7m est abîmé ou incomplet",
  'fat-no-fornitori': "Il manque la section « Fournisseurs »",
  'fat-no-xml': "Cette facture reçue n'a pas le fichier XML",
  'fat-gia-integrata': "Cette facture reçue a déjà son intégration",
  // avvio guidato, app desktop (backup, aggiornamenti, QR, rete), sicurezza
  'avvio-solo-titolare': "Seul le titulaire peut le faire",
  'avvio-esempi-ci-sono': "Les données d'exemple sont déjà là",
  'agg-risposta': "La vérification des versions a répondu {stato}",
  'agg-inattesa': "Réponse inattendue",
  'bk-percorso': "Indique le chemin complet du dossier (par exemple {a} ou {b})",
  'bk-fuori-dati': "Choisissez un dossier en dehors de celui des données",
  'bk-no-cartella': "Cette base de données n'a pas de dossier (elle est en mémoire)",
  'bk-non-kubo': "Le fichier n'est pas une base de données Kubo",
  'bk-in-memoria': "Cette base de données est en mémoire",
  'qr-lungo': "Texte trop long pour le code QR",
  'rete-ipv4': "Adresse IPv4 non valide",
  'rete-scrivi': "Saisissez une adresse ou un code",
  'dk-solo-titolare': "Seul le titulaire gère les sauvegardes et les mises à jour",
  'dk-backup-sconosciuto': "Sauvegarde inconnue",
  'dk-ripristino-corso': "Une restauration est en cours",
  'dk-db-memoria': "La base de données est en mémoire",
  'dk-conferma': "Confirmation requise",
  'dk-file-piccolo': "Le fichier est vide ou trop petit pour être une sauvegarde",
  'dk-non-scrivo': "Impossible d'écrire dans le dossier des sauvegardes",
  'dk-non-backup': "Le fichier n'est pas une sauvegarde Kubo (il faut un fichier .db)",
  'sic-solo-titolare': "Seul le titulaire modifie les réglages de sécurité",
  'sic-cambia-password': "Avant de continuer, changez le mot de passe qui vous a été donné",
  'sic-pin-password': "Pour changer le PIN, il faut le mot de passe actuel",
  'sic-password-sbagliata': "Le mot de passe actuel est incorrect",
  'sic-no-fattura': "Votre rôle ne permet pas d'exporter la facture électronique",
  'sic-no-lumi': "Lumi n'est pas activé pour votre rôle",
  'sic-tipo-file': "Ce type de fichier ne peut pas être joint (programmes, scripts et pages web)",
  'sic-token-password': "On ne change pas le mot de passe avec un jeton",
  'sic-password-diversa': "Le nouveau mot de passe doit être différent de l'ancien",
  'sic-sessione': "Session inconnue",
  'sic-persona': "Personne inconnue",
  'sic-fuso': "Fuseau horaire inconnu (ex. Europe/Paris)",
  'sic-titolare-tutto': "Le titulaire peut toujours tout faire",
  'sic-ruolo': "Rôle inconnu",
  'avvio-codice': "Le code de démarrage est nécessaire : il se trouve dans le terminal ou le journal de Kubo",
  'pw-lunga': "Le mot de passe est trop long",
  'pw-comune': "Ce mot de passe fait partie des plus utilisés : choisissez-en un autre",
  'pw-facile': "Ce mot de passe est trop facile à deviner",
  'pw-nome': "Le mot de passe ne peut pas être votre nom ou votre e-mail",
  'pw-mescola': "En dessous de 12 caractères, mélangez lettres, chiffres ou symboles",
  // gli strumenti di Lumi dai moduli e la scheda delle fatture (lumi-strumenti.js, lumidoc.js)
  "lumi-strumento-sconosciuto": "Outil de Lumi inconnu « {nome} »",
  "lumi-strumento-permesso": "Vous ne pouvez pas utiliser cet outil de Lumi",
  "lumi-argomenti": "Arguments non valides pour {nome} : {_dettaglio}",
  "lumi-strumento-scrive": "Cet outil écrit : d'abord la fiche de confirmation",
  "lumi-strumento-senza-scheda": "Cet outil n'a pas de fiche de confirmation",
  "lumi-conferma-diversa": "La confirmation ne correspond pas à la fiche : refaites la proposition",
  "lumidoc-cliente": "Client",
  "lumidoc-riga": "{quantita} × {prezzo} · TVA {iva} = {totale}",
  "lumidoc-altre-righe": "{n} autres lignes",
  "lumidoc-cassa": "Contribution à la caisse {aliquota} %",
  "lumidoc-imponibile": "Montant HT",
  "lumidoc-iva": "TVA",
  "lumidoc-bollo": "Droit de timbre",
  "lumidoc-bollo-tuo": "2 € à votre charge",
  "lumidoc-totale": "Total",
  "lumidoc-ritenuta": "Retenue à la source {aliquota} %",
  "lumidoc-netto": "À encaisser",
  "lumidoc-av-sdi": "Pour la facture électronique : {_messaggio}",
  "lumidoc-nuova": "Nouvelle facture",
  "lumidoc-in-bozza": "Elle est créée en brouillon : vérifiez-la, puis émettez-la.",
  "lumidoc-av-forfettario": "Régime forfaitaire : lignes sans TVA (nature N2.2) et pas de retenue.",
  "lumidoc-av-no-ritenuta": "En régime forfaitaire les honoraires n'ont pas de retenue : je l'ai retirée.",
  "lumidoc-av-aliquota": "Taux de TVA de {aliquota} % inhabituel : en Italie ils sont de 4, 5, 10 et 22 %.",
  "lumidoc-av-ritenuta": "Retenue de {aliquota} % comme dans vos factures précédentes.",
  "lumidoc-av-cassa": "Contribution à la caisse de {aliquota} % comme dans vos factures précédentes.",
  "lumidoc-av-bollo": "Droit de timbre de 2 € ajouté : les opérations sans TVA dépassent 77,47 €.",
  "lumidoc-emetti": "Émettre la facture",
  "lumidoc-numero": "Numéro",
  "lumidoc-numero-nuovo": "le suivant de la série",
  "lumidoc-data": "Date",
  "lumidoc-dopo-emissione": "Une fois émise, elle ne se modifie plus : on la corrige avec un avoir.",
  "lumidoc-nota": "Avoir",
  "lumidoc-nota-parziale": "Avoir partiel",
  "lumidoc-storna": "Annule",
  "lumidoc-storna-di": "facture {numero} du {data}",
  "lumidoc-av-gia-stornato": "{importo} de cette facture ont déjà été crédités.",
};
