// I messaggi del server in italiano: sono i testi che il motore e i moduli lanciano già, scritti come modelli con i
// {parametri}. server/moduli/lingue.js li riconosce e li riscrive nella lingua dell'utente con la stessa chiave.
// I parametri con «_» davanti sono messaggi anche loro (si traducono a loro volta). Le altre lingue: stesse chiavi.
export default {
  // api.js, auth.js, permessi.js
  'accedi': 'Accedi per continuare',
  'configurato': 'Già configurato',
  'manca-azienda': 'Manca il nome dell\'azienda',
  'tentativi': 'Troppi tentativi: riprova fra qualche minuto',
  'no-schema': 'Non puoi personalizzare il gestionale',
  'id-diverso': 'id diverso',
  'no-xkubo': 'Richiesta senza intestazione X-Kubo',
  'troppo-grande': 'Troppo grande',
  'json': 'JSON non valido',
  'non-trovato': 'Non trovato',
  'interno': 'Errore interno',
  'token-password': 'Con un token non si cambiano password e PIN',
  'servono-nome-email': 'Servono nome ed email',
  'password-corta': 'La password deve avere almeno 8 caratteri',
  'pin': 'Il PIN è di 4-8 cifre',
  'email-usata': 'Esiste già un utente con questa email',
  'credenziali': 'Email o password sbagliate',
  'pin-sbagliato': 'PIN sbagliato',
  'utente-sconosciuto': 'Utente sconosciuto',
  'titolare-attivo': 'Serve almeno un titolare attivo',
  'permesso': 'Non hai il permesso',
  'ruolo-titolare': 'Il ruolo del titolare non si modifica',
  'permesso-vedere': 'Non hai il permesso di vedere in «{entita}»',
  'permesso-creare': 'Non hai il permesso di creare in «{entita}»',
  'permesso-modificare': 'Non hai il permesso di modificare in «{entita}»',
  'permesso-eliminare': 'Non hai il permesso di eliminare in «{entita}»',
  'modello-sconosciuto': 'Modello sconosciuto',
  'lingua-sconosciuta': 'Lingua sconosciuta',
  'valuta-sconosciuta': 'Valuta sconosciuta',
  // dati.js
  'entita-sconosciuta': 'Entità sconosciuta «{id}»',
  'deve-numero': '«{campo}» deve essere un numero',
  'deve-importo': '«{campo}» deve essere un importo',
  'data-non-valida': '«{campo}»: data non valida (AAAA-MM-GG)',
  'data-ora-non-valida': '«{campo}»: data e ora non valide',
  'email-non-valida': '«{campo}»: email non valida',
  'opzione-sconosciuta': '«{campo}»: opzione sconosciuta «{valore}»',
  'stato-sconosciuto': '«{campo}»: stato sconosciuto «{valore}»',
  'transizione': '«{campo}»: da «{da}» non si può passare a «{a}»',
  'non-trovo': '«{campo}»: non trovo «{valore}»',
  'utente-campo': '«{campo}»: utente sconosciuto',
  'allegato': '«{campo}»: allegato non valido',
  'unico': '«{campo}» deve essere unico: c\'è già questo valore',
  'filtro-campo': 'Filtro su un campo sconosciuto «{campo}»',
  'operatore': 'Operatore sconosciuto «{op}»',
  'obbligatorio': '«{campo}» è obbligatorio',
  'non-campo-di': '«{campo}» non è un campo di {entita}',
  'non-modificabile': '«{campo}» non si può modificare',
  'percorso-non-valido': 'Percorso non valido',
  // schema.js e automazioni.js
  'id-entita': 'id entità non valido «{id}» (minuscole, numeri, _)',
  'manca-nome': 'manca il nome',
  'manca-campi': 'manca l\'elenco dei campi',
  'dove-campo': 'campo «{id}»',
  'dove-azione': 'azione {n}',
  'id-non-valido': 'id non valido',
  'id-ripetuto': 'id ripetuto',
  'tipo-sconosciuto': 'tipo sconosciuto «{tipo}»',
  'servono-opzioni': 'servono le opzioni',
  'opzione-id-nome': 'ogni opzione vuole id e nome',
  'transizione-sconosciuta': 'transizione verso uno stato sconosciuto «{stato}»',
  'collegata-sconosciuta': 'entità collegata sconosciuta «{entita}»',
  'righe-sconosciuta': 'entità delle righe sconosciuta «{entita}»',
  'righe-relazione': '«{campo}» deve essere una relazione verso «{entita}»',
  'manca-formato': 'manca il formato (es. F-{AAAA}-{N:4})',
  'formula-campo': 'la formula usa «{nome}», che non è un campo',
  'non-esiste': '«{nome}» non esiste',
  'formula-non-valida': 'formula non valida ({_errore})',
  'titolo-sconosciuto': 'titolo: campo sconosciuto «{campo}»',
  'definizione': 'Definizione non valida',
  'valori-tipo': 'campo «{id}»: {n} valori non diventano {tipo} (es. «{esempio}»)',
  'valori-ripetuti': 'campo «{id}»: ci sono già valori ripetuti, non può essere unico',
  'perderebbe': 'La modifica perderebbe dati',
  'entita-sconosciuta-schema': 'Entità sconosciuta «{id}»',
  'usata': 'L\'entità è usata da altre',
  'automazione': 'Automazione non valida',
  'entita-sconosciuta-min': 'entità sconosciuta «{entita}»',
  'quando': '«quando» non valido: {valore}',
  'campo-sconosciuto-min': 'campo sconosciuto «{campo}»',
  'servono-azioni': 'servono delle azioni',
  'composto': '{_dove}: {_resto}',
  // formule.js
  'virgolette': 'Virgolette non chiuse',
  'carattere': 'Carattere non valido «{c}»',
  'parentesi': 'Manca una parentesi chiusa',
  'atteso': 'Atteso {simbolo}',
  'funzione': 'Funzione sconosciuta {nome}',
  'incompleta': 'Formula incompleta',
  'inatteso': 'Simbolo inatteso',
  'campo-formula': 'Campo sconosciuto «{nome}»',
  'formula': 'Formula non valida',
  // agenda e cruscotto
  'senza-date': '«{entita}» non ha campi data',
  'periodo-agenda': 'Periodo non valido (da e a in AAAA-MM-GG)',
  'due-mesi': 'Al massimo due mesi alla volta',
  'solo-cruscotto': 'Solo chi personalizza il gestionale cambia il cruscotto',
  'widget': 'Tipo di widget sconosciuto',
  'nome-vista': 'Dai un nome alla vista',
  'viste-tutti': 'Solo chi personalizza il gestionale salva viste per tutti',
  'vista-non-trovata': 'Vista non trovata',
  'periodo-sconosciuto': 'Periodo sconosciuto «{nome}»',
  'misura': 'Misura sconosciuta «{misura}»',
  'campo-sconosciuto': 'Campo sconosciuto «{campo}»',
  'raggruppa': 'Non si può raggruppare per «{campo}»',
  'periodo': 'Periodo non valido (AAAA-MM-GG)',
  'serve-data': 'Serve un campo data per il periodo',
  // file, import, token e webhook
  'file-vuoto': 'Il file è vuoto',
  'file-grande': 'Il file è troppo grande: al massimo {mb} MB',
  'troppi-file': 'Troppi file caricati nelle ultime ore: riprova più tardi',
  'caricamento': 'Caricamento sconosciuto',
  'fuori-ordine': 'Pezzo fuori ordine',
  'pezzo': 'Pezzo non valido',
  'file-non-arrivato': '«{campo}»: il file «{file}» non è arrivato, caricalo di nuovo',
  'file-supera': '«{campo}»: «{file}» supera {mb} MB',
  'non-immagine': '«{campo}»: «{file}» non è un\'immagine',
  'file-non-trovato': 'File non trovato',
  'token-gestione': 'Con un token non si gestiscono i token né i webhook: entra dall\'interfaccia',
  'nome-token': 'Dai un nome al token (es. «Sito», «Contabilità»)',
  'scadenza': 'Scadenza non valida',
  'token-sconosciuto': 'Token sconosciuto',
  'solo-webhook': 'Solo il titolare gestisce i webhook',
  'indirizzo': 'Indirizzo non valido',
  'http': 'L\'indirizzo deve iniziare con http:// o https://',
  'webhook': 'Webhook sconosciuto',
  'import-non-arrivato': 'Il file non è arrivato: caricalo di nuovo',
  'import-leggere': 'Non riesco a leggere il file: è un .xlsx o un .csv?',
  'sezione': 'Sezione sconosciuta',
  'sezione-nome': 'Sezione sconosciuta «{id}»',
  'import-nuovi': 'Solo chi può personalizzare crea sezioni e campi nuovi',
  'nome-sezione': 'Dai un nome alla nuova sezione',
  'una-colonna': 'Scegli almeno una colonna',
  'nessuna-colonna': 'Nessuna colonna abbinata a un campo',
  'doppioni': 'Campo per i doppioni sconosciuto',
  'backup': 'Solo il titolare scarica il backup, dall\'interfaccia',
  'xlsx': 'Il file non è un .xlsx valido',
  'xlsx-rovinato': 'Il file .xlsx è rovinato',
  'grande': 'Il file è troppo grande',
  'zip': 'Compressione dello zip non supportata',
  'nessun-foglio': 'Nel file non c\'è nessun foglio',
  'troppe-righe': 'Il foglio ha più di {n} righe: dividilo in più file',
  'xls': 'Il vecchio formato .xls non si legge: in Excel fai «Salva con nome» → .xlsx o .csv',
  'foglio': 'Serve un foglio .xlsx o .csv',
  'non-numero': '«{valore}» non è un numero',
  'non-importo': '«{valore}» non è un importo',
  'si-no': '«{valore}»: scrivi sì o no',
  'non-data': '«{valore}» non è una data (es. 31/12/2026)',
  'non-data-ora': '«{valore}» non è una data con l\'ora (es. 31/12/2026 14:30)',
  'non-opzione': '«{valore}» non è fra le opzioni di «{campo}»',
  'non-vedere': 'Non puoi vedere «{entita}»',
  'non-c-e': '«{valore}» non c\'è in «{entita}»',
  'piu-di-uno': '«{valore}»: in «{entita}» ce n\'è più di uno con questo nome',
  'non-persona': '«{valore}» non è una persona del gestionale',
  // Lumi
  'lumi-titolare': 'Solo il titolare cambia le impostazioni di Lumi',
  'lumi-chiave': 'Questa non sembra una chiave di Claude (inizia con «sk-»)',
  'lumi-limite': 'Il limite va da 1 a 600 domande al minuto',
  'lumi-spento': 'Lumi è spento: il titolare lo riaccende in Gestione → Lumi.',
  'lumi-troppe': 'Troppe domande in poco tempo: riprova fra un minuto.',
  'lumi-risposta': 'Lumi non ha risposto',
  'lumi-campo': 'Campo sconosciuto «{campo}» in {entita}',
  'lumi-data': 'Data non valida «{valore}»: usa AAAA-MM-GG',
  'lumi-archiviata': 'c\'è già una sezione archiviata «{nome}» ({id}): ripristinala da Personalizza o scegli un altro nome',
  // documenti
  'doc-impostare': 'Solo chi può personalizzare il gestionale cambia questi dati',
  'doc-righe': 'Questa sezione non ha righe da stampare',
  'doc-colonna': 'Serve almeno una colonna',
  'doc-regime': 'Regime fiscale sconosciuto',
  'doc-cap': 'Il CAP ha 5 cifre',
  'doc-provincia': 'La provincia è la sigla di 2 lettere (es. MI)',
  'doc-colore': 'Colore non valido',
  'doc-aliquota': 'Aliquota IVA non valida',
  'doc-logo': 'Il logo deve essere un\'immagine PNG o JPEG',
  'doc-logo-grande': 'Il logo è troppo grande: al massimo 300 KB',
  'doc-png': 'Il file non è un PNG o un JPEG',
  'doc-fattura-doppia': 'C\'è già una fattura numero {numero} nel {anno}',
  'doc-numero-usato': 'Numero già usato quest\'anno',
  'doc-modello-fatture': 'Aggiungi prima il modello «Fatture e fattura elettronica» (Personalizza → modelli).',
  'doc-gia-fattura': 'È già una fattura',
  'doc-cliente': 'In «{entita}» non c\'è un cliente a cui fare la fattura',
  'doc-storna': 'Si storna solo una fattura emessa: questa è ancora in bozza',
  'doc-nota': 'È già una nota di credito',
  // fattura elettronica (documenti-xml.js)
  'xml-ragione': "Mancano i dati della tua azienda: la ragione sociale (Documenti → Dati dell'azienda).",
  'xml-piva': "Manca la partita IVA della tua azienda.",
  'xml-piva-errata': "La partita IVA della tua azienda non va: {_errore}.",
  'xml-regime': "Manca il regime fiscale della tua azienda (per esempio RF01 ordinario o RF19 forfettario).",
  'xml-indirizzo-azienda': "Manca l'indirizzo completo della tua azienda (via, CAP di 5 cifre, comune).",
  'xml-bozza': "La fattura è ancora in bozza: emettila, così prende il suo numero.",
  'xml-annullata': "La fattura è annullata: non si manda allo SDI. Se era già stata mandata, stornala con una nota di credito.",
  'xml-numero': "Manca il numero della fattura.",
  'xml-data': "Manca la data della fattura.",
  'xml-righe': "La fattura non ha righe.",
  'xml-cliente-nome': "Manca il nome o la ragione sociale del cliente.",
  'xml-cliente-piva': "Manca la partita IVA o il codice fiscale del cliente.",
  'xml-codice-pa': "Il codice destinatario ha 6 caratteri: è una Pubblica Amministrazione, serve il formato FPA12 (non ancora supportato).",
  'xml-codice-7': "Il codice destinatario del cliente deve avere 7 caratteri.",
  'xml-codice-manca': "Manca il codice destinatario del cliente: scrivilo nella sua scheda (oppure la PEC; se non ce l'ha, scrivi 0000000).",
  'xml-indirizzo-cliente': "Manca l'indirizzo completo del cliente (via, CAP di 5 cifre, comune).",
  'xml-provincia': "La provincia del cliente va scritta con la sigla di 2 lettere (es. MI).",
  'xml-indirizzo-estero': "Manca l'indirizzo del cliente (via e città).",
  'xml-bollo': "Le righe senza IVA superano 77,47 €: spunta «Bollo virtuale da 2 €».",
  'xml-ritenuta': "Con la ritenuta servono il tipo e la causale.",
  'xml-totale': "Il totale della fattura è zero o negativo (per uno storno usa una nota di credito con importi positivi).",
  'xml-rate': "Pagamento a rate senza rate: aggiungile, o scegli «Pagamento completo».",
  // fatture complete (fatture*.js, documenti-xml.js)
  'fat-autofattura-fornitore': "Manca il fornitore dell'autofattura.",
  'fat-autofattura-collegata': "Manca la fattura del fornitore da integrare (numero e data).",
  'fat-codice-ufficio': "Il codice ufficio della Pubblica Amministrazione ha 6 lettere o cifre.",
  'fat-cig': "Il CIG ha 10 lettere o cifre.",
  'fat-cup': "Il CUP ha 15 lettere o cifre.",
  'fat-cig-documento': "Con il CIG o il CUP serve il numero dell'ordine o del contratto.",
  'fat-forfettario-split': "Nel regime forfettario non c'è IVA: niente scissione dei pagamenti.",
  'fat-ritenuta-righe': "La ritenuta non ha righe a cui applicarsi: togli «esclusa dalla ritenuta» da almeno una riga.",
  'fat-cassa-tipo': "Scegli la cassa previdenziale (per esempio TC22 INPS).",
  'fat-cassa-natura': "La cassa previdenziale è senza IVA: scegli la natura (es. N4 o N2.2).",
  'fat-ddt': "La fattura differita deve citare i DDT: aggiungi numero e data di almeno un DDT.",
  'fat-pa-esigibilita': "Fattura alla PA: scegli l'esigibilità IVA (di solito «scissione dei pagamenti»).",
  'fat-bloccata': "La fattura {numero} è emessa: non si modifica più. Correggila con una nota di credito o di debito.",
  'fat-non-elimina': "La fattura {numero} è emessa: non si elimina, lascerebbe un buco nella numerazione. Stornala con una nota di credito.",
  'fat-bloccato-campo': "Bloccato dopo l'emissione",
  'fat-vuoto': "Il file è vuoto",
  'fat-grande': "Il file è troppo grande: al massimo 5 MB",
  'fat-non-fattura': "Il file non è una fattura elettronica",
  'fat-non-p7m': "Il file non è una fattura firmata (.p7m)",
  'fat-p7m-staccata': "La firma è «staccata»: il .p7m non contiene la fattura",
  'fat-p7m-rotto': "Il file .p7m è rovinato o incompleto",
  'fat-no-fornitori': "Manca la sezione «Fornitori»",
  'fat-no-xml': "Questa fattura ricevuta non ha il file XML",
  'fat-gia-integrata': "Questa fattura ricevuta ha già la sua integrazione",
  // avvio guidato, app desktop (backup, aggiornamenti, QR, rete), sicurezza
  'avvio-solo-titolare': "Solo il titolare può farlo",
  'avvio-esempi-ci-sono': "I dati d'esempio ci sono già",
  'agg-risposta': "Il controllo delle versioni ha risposto {stato}",
  'agg-inattesa': "Risposta inattesa",
  'bk-percorso': "Scrivi il percorso completo della cartella (per esempio {a} o {b})",
  'bk-fuori-dati': "Scegli una cartella fuori da quella dei dati",
  'bk-no-cartella': "Questo database non ha una cartella (è in memoria)",
  'bk-non-kubo': "Il file non è un database di Kubo",
  'bk-in-memoria': "Questo database è in memoria",
  'qr-lungo': "Testo troppo lungo per il codice QR",
  'rete-ipv4': "Indirizzo IPv4 non valido",
  'rete-scrivi': "Scrivi un indirizzo o un codice",
  'dk-solo-titolare': "Solo il titolare gestisce backup e aggiornamenti",
  'dk-backup-sconosciuto': "Backup sconosciuto",
  'dk-ripristino-corso': "C'è un ripristino in corso",
  'dk-db-memoria': "Il database è in memoria",
  'dk-conferma': "Serve la conferma",
  'dk-file-piccolo': "Il file è vuoto o troppo piccolo per essere un backup",
  'dk-non-scrivo': "Non riesco a scrivere nella cartella dei backup",
  'dk-non-backup': "Il file non è un backup di Kubo (serve un file .db)",
  'sic-solo-titolare': "Solo il titolare cambia le impostazioni di sicurezza",
  'sic-cambia-password': "Prima di continuare cambia la password che ti hanno dato",
  'sic-pin-password': "Per cambiare il PIN serve la password attuale",
  'sic-password-sbagliata': "La password attuale non è giusta",
  'sic-no-fattura': "Il tuo ruolo non esporta la fattura elettronica",
  'sic-no-lumi': "Lumi non è attivo per il tuo ruolo",
  'sic-tipo-file': "Questo tipo di file non si può allegare (programmi, script e pagine web)",
  'sic-token-password': "Con un token non si cambia la password",
  'sic-password-diversa': "La nuova password deve essere diversa da quella di prima",
  'sic-sessione': "Sessione sconosciuta",
  'sic-persona': "Persona sconosciuta",
  'sic-fuso': "Fuso orario sconosciuto (es. Europe/Rome)",
  'sic-titolare-tutto': "Il titolare può sempre tutto",
  'sic-ruolo': "Ruolo sconosciuto",
  'avvio-codice': "Serve il codice di avvio: lo trovi nel terminale o nel log di Kubo",
  'pw-lunga': "La password è troppo lunga",
  'pw-comune': "Questa password è fra le più usate: scegline un'altra",
  'pw-facile': "Questa password è troppo facile da indovinare",
  'pw-nome': "La password non può essere il tuo nome o la tua email",
  'pw-mescola': "Sotto i 12 caratteri mescola lettere con cifre o simboli",
  // fisco (server/moduli/fisco.js)
  'fisco-impostazione': "Impostazione fiscale non valida: {campo}",
  'fisco-forfettario': "Nel regime forfettario non si fanno liquidazioni IVA né comunicazioni LIPE",
  'fisco-dati-azienda': "Per la comunicazione servono partita IVA e codice fiscale dell'azienda (Documenti → dati dell'azienda)",
  'fisco-anno': "Anno non valido",
  'fisco-periodo': "Periodo non valido",
  'fisco-nessun-versamento': "Nessun versamento in questa data",
  'fisco-solo-chi': "Solo chi può personalizzare cambia le impostazioni fiscali",
  // gli strumenti di Lumi dai moduli e la scheda delle fatture (lumi-strumenti.js, lumidoc.js)
  'lumi-strumento-sconosciuto': 'Strumento di Lumi sconosciuto «{nome}»',
  'lumi-strumento-permesso': 'Non puoi usare questo strumento di Lumi',
  'lumi-argomenti': 'Argomenti non validi per {nome}: {_dettaglio}',
  'lumi-strumento-scrive': 'Questo strumento scrive: prima la scheda di conferma',
  'lumi-strumento-senza-scheda': 'Questo strumento non ha una scheda di conferma',
  'lumi-conferma-diversa': 'La conferma non corrisponde alla scheda: rifai la proposta',
  'lumidoc-cliente': 'Cliente',
  'lumidoc-riga': '{quantita} × {prezzo} · IVA {iva} = {totale}',
  'lumidoc-altre-righe': 'Altre {n} righe',
  'lumidoc-cassa': 'Contributo cassa {aliquota}%',
  'lumidoc-imponibile': 'Imponibile',
  'lumidoc-iva': 'IVA',
  'lumidoc-bollo': 'Bollo',
  'lumidoc-bollo-tuo': '2 € a tuo carico',
  'lumidoc-totale': 'Totale',
  'lumidoc-ritenuta': "Ritenuta d'acconto {aliquota}%",
  'lumidoc-netto': 'Da incassare',
  'lumidoc-netto-nota': 'Netto a credito del cliente',
  'lumidoc-av-sdi': 'Per la fattura elettronica: {_messaggio}',
  'lumidoc-nuova': 'Nuova fattura',
  'lumidoc-in-bozza': 'Nasce in bozza: la controlli e poi la emetti.',
  'lumidoc-av-forfettario': 'Regime forfettario: righe senza IVA (natura N2.2) e niente ritenuta.',
  'lumidoc-av-no-ritenuta': "Nel regime forfettario i compensi non hanno la ritenuta d'acconto: l'ho tolta.",
  'lumidoc-av-aliquota': 'Aliquota IVA del {aliquota}% insolita: in Italia sono 4, 5, 10 e 22%.',
  'lumidoc-av-ritenuta': 'Ritenuta del {aliquota}% come nelle tue fatture precedenti.',
  'lumidoc-av-cassa': 'Contributo cassa del {aliquota}% come nelle tue fatture precedenti.',
  'lumidoc-av-bollo': 'Bollo da 2 € aggiunto: le operazioni senza IVA superano 77,47 €.',
  'lumidoc-emetti': 'Emissione della fattura',
  'lumidoc-numero': 'Numero',
  'lumidoc-numero-nuovo': 'il prossimo della serie',
  'lumidoc-data': 'Data',
  'lumidoc-dopo-emissione': "Dopo l'emissione non si modifica più: si corregge con una nota di credito.",
  'lumidoc-nota': 'Nota di credito',
  'lumidoc-nota-parziale': 'Nota di credito parziale',
  'lumidoc-storna': 'Storna',
  'lumidoc-storna-di': 'fattura {numero} del {data}',
  'lumidoc-av-gia-stornato': 'Di questa fattura sono già stati stornati {importo}.',
};
