// Mensagens do servidor em português do Brasil (mesmas chaves de it.js).
export default {
  'accedi': 'Entre para continuar',
  'configurato': 'Já configurado',
  'manca-azienda': 'Falta o nome da empresa',
  'tentativi': 'Muitas tentativas: tente de novo em alguns minutos',
  'no-schema': 'Você não pode personalizar o sistema',
  'id-diverso': 'id diferente',
  'no-xkubo': 'Requisição sem o cabeçalho X-Kubo',
  'troppo-grande': 'Grande demais',
  'json': 'JSON inválido',
  'non-trovato': 'Não encontrado',
  'interno': 'Erro interno',
  'token-password': 'Com um token não se mudam senhas nem PIN',
  'servono-nome-email': 'Nome e e-mail são obrigatórios',
  'password-corta': 'A senha precisa ter pelo menos 8 caracteres',
  'pin': 'O PIN tem de 4 a 8 dígitos',
  'email-usata': 'Já existe um usuário com este e-mail',
  'credenziali': 'E-mail ou senha incorretos',
  'pin-sbagliato': 'PIN incorreto',
  'utente-sconosciuto': 'Usuário desconhecido',
  'titolare-attivo': 'É preciso pelo menos um proprietário ativo',
  'permesso': 'Você não tem permissão',
  'ruolo-titolare': 'O papel de proprietário não pode ser alterado',
  'permesso-vedere': 'Você não tem permissão para ver «{entita}»',
  'permesso-creare': 'Você não tem permissão para criar em «{entita}»',
  'permesso-modificare': 'Você não tem permissão para editar «{entita}»',
  'permesso-eliminare': 'Você não tem permissão para excluir em «{entita}»',
  'modello-sconosciuto': 'Modelo desconhecido',
  'lingua-sconosciuta': 'Idioma desconhecido',
  'valuta-sconosciuta': 'Moeda desconhecida',
  'entita-sconosciuta': 'Entidade desconhecida «{id}»',
  'deve-numero': '«{campo}» precisa ser um número',
  'deve-importo': '«{campo}» precisa ser um valor',
  'data-non-valida': '«{campo}»: data inválida (AAAA-MM-DD)',
  'data-ora-non-valida': '«{campo}»: data e hora inválidas',
  'email-non-valida': '«{campo}»: e-mail inválido',
  'opzione-sconosciuta': '«{campo}»: opção desconhecida «{valore}»',
  'stato-sconosciuto': '«{campo}»: status desconhecido «{valore}»',
  'transizione': '«{campo}»: não dá para passar de «{da}» para «{a}»',
  'non-trovo': '«{campo}»: não encontro «{valore}»',
  'utente-campo': '«{campo}»: usuário desconhecido',
  'allegato': '«{campo}»: anexo inválido',
  'unico': '«{campo}» precisa ser único: esse valor já existe',
  'filtro-campo': 'Filtro em um campo desconhecido «{campo}»',
  'operatore': 'Operador desconhecido «{op}»',
  'obbligatorio': '«{campo}» é obrigatório',
  'non-campo-di': '«{campo}» não é um campo de {entita}',
  'non-modificabile': '«{campo}» não pode ser alterado',
  'percorso-non-valido': 'Caminho inválido',
  'id-entita': 'id de entidade inválido «{id}» (minúsculas, números, _)',
  'manca-nome': 'falta o nome',
  'manca-campi': 'falta a lista de campos',
  'dove-campo': 'campo «{id}»',
  'dove-azione': 'ação {n}',
  'id-non-valido': 'id inválido',
  'id-ripetuto': 'id repetido',
  'tipo-sconosciuto': 'tipo desconhecido «{tipo}»',
  'servono-opzioni': 'faltam as opções',
  'opzione-id-nome': 'cada opção precisa de id e nome',
  'transizione-sconosciuta': 'transição para um status desconhecido «{stato}»',
  'collegata-sconosciuta': 'entidade vinculada desconhecida «{entita}»',
  'righe-sconosciuta': 'entidade dos itens desconhecida «{entita}»',
  'righe-relazione': '«{campo}» precisa ser um vínculo com «{entita}»',
  'manca-formato': 'falta o formato (ex.: F-{AAAA}-{N:4})',
  'formula-campo': 'a fórmula usa «{nome}», que não é um campo',
  'non-esiste': '«{nome}» não existe',
  'formula-non-valida': 'fórmula inválida ({_errore})',
  'titolo-sconosciuto': 'título: campo desconhecido «{campo}»',
  'definizione': 'Definição inválida',
  'valori-tipo': 'campo «{id}»: {n} valores não viram {tipo} (ex.: «{esempio}»)',
  'valori-ripetuti': 'campo «{id}»: já há valores repetidos, não pode ser único',
  'perderebbe': 'A alteração perderia dados',
  'entita-sconosciuta-schema': 'Entidade desconhecida «{id}»',
  'usata': 'A entidade é usada por outras',
  'automazione': 'Automação inválida',
  'entita-sconosciuta-min': 'entidade desconhecida «{entita}»',
  'quando': '«quando» inválido: {valore}',
  'campo-sconosciuto-min': 'campo desconhecido «{campo}»',
  'servono-azioni': 'faltam as ações',
  'composto': '{_dove}: {_resto}',
  'virgolette': 'Aspas não fechadas',
  'carattere': 'Caractere inválido «{c}»',
  'parentesi': 'Falta fechar um parêntese',
  'atteso': 'Esperado {simbolo}',
  'funzione': 'Função desconhecida {nome}',
  'incompleta': 'Fórmula incompleta',
  'inatteso': 'Símbolo inesperado',
  'campo-formula': 'Campo desconhecido «{nome}»',
  'formula': 'Fórmula inválida',
  'senza-date': '«{entita}» não tem campos de data',
  'periodo-agenda': 'Período inválido (de e até em AAAA-MM-DD)',
  'due-mesi': 'No máximo dois meses por vez',
  'solo-cruscotto': 'Só quem personaliza o sistema muda o painel',
  'widget': 'Tipo de widget desconhecido',
  'nome-vista': 'Dê um nome à visualização',
  'viste-tutti': 'Só quem personaliza o sistema salva visualizações para todos',
  'vista-non-trovata': 'Visualização não encontrada',
  'periodo-sconosciuto': 'Período desconhecido «{nome}»',
  'misura': 'Medida desconhecida «{misura}»',
  'campo-sconosciuto': 'Campo desconhecido «{campo}»',
  'raggruppa': 'Não dá para agrupar por «{campo}»',
  'periodo': 'Período inválido (AAAA-MM-DD)',
  'serve-data': 'O período precisa de um campo de data',
  'file-vuoto': 'O arquivo está vazio',
  'file-grande': 'O arquivo é grande demais: no máximo {mb} MB',
  'troppi-file': 'Muitos arquivos enviados nas últimas horas: tente mais tarde',
  'caricamento': 'Envio desconhecido',
  'fuori-ordine': 'Parte fora de ordem',
  'pezzo': 'Parte inválida',
  'file-non-arrivato': '«{campo}»: o arquivo «{file}» não chegou, envie de novo',
  'file-supera': '«{campo}»: «{file}» passa de {mb} MB',
  'non-immagine': '«{campo}»: «{file}» não é uma imagem',
  'file-non-trovato': 'Arquivo não encontrado',
  'token-gestione': 'Com um token não se gerenciam tokens nem webhooks: entre pelo aplicativo',
  'nome-token': 'Dê um nome ao token (ex.: «Site», «Contabilidade»)',
  'scadenza': 'Validade inválida',
  'token-sconosciuto': 'Token desconhecido',
  'solo-webhook': 'Só o proprietário gerencia os webhooks',
  'indirizzo': 'Endereço inválido',
  'http': 'O endereço precisa começar com http:// ou https://',
  'webhook': 'Webhook desconhecido',
  'import-non-arrivato': 'O arquivo não chegou: envie de novo',
  'import-leggere': 'Não consigo ler o arquivo: é um .xlsx ou um .csv?',
  'sezione': 'Seção desconhecida',
  'sezione-nome': 'Seção desconhecida «{id}»',
  'import-nuovi': 'Só quem pode personalizar cria seções e campos novos',
  'nome-sezione': 'Dê um nome à nova seção',
  'una-colonna': 'Escolha pelo menos uma coluna',
  'nessuna-colonna': 'Nenhuma coluna está ligada a um campo',
  'doppioni': 'Campo para duplicados desconhecido',
  'backup': 'Só o proprietário baixa o backup, pelo aplicativo',
  'xlsx': 'O arquivo não é um .xlsx válido',
  'xlsx-rovinato': 'O arquivo .xlsx está corrompido',
  'grande': 'O arquivo é grande demais',
  'zip': 'Compressão zip não suportada',
  'nessun-foglio': 'O arquivo não tem nenhuma planilha',
  'troppe-righe': 'A planilha tem mais de {n} linhas: divida em vários arquivos',
  'xls': 'O antigo formato .xls não é lido: no Excel use «Salvar como» → .xlsx ou .csv',
  'foglio': 'É preciso uma planilha .xlsx ou .csv',
  'non-numero': '«{valore}» não é um número',
  'non-importo': '«{valore}» não é um valor',
  'si-no': '«{valore}»: escreva sim ou não',
  'non-data': '«{valore}» não é uma data (ex.: 31/12/2026)',
  'non-data-ora': '«{valore}» não é uma data com hora (ex.: 31/12/2026 14:30)',
  'non-opzione': '«{valore}» não está entre as opções de «{campo}»',
  'non-vedere': 'Você não pode ver «{entita}»',
  'non-c-e': '«{valore}» não está em «{entita}»',
  'piu-di-uno': '«{valore}»: em «{entita}» há mais de um com este nome',
  'non-persona': '«{valore}» não é um usuário do sistema',
  'lumi-titolare': 'Só o proprietário muda as configurações do Lumi',
  'lumi-chiave': 'Isso não parece uma chave do Claude (começa com «sk-»)',
  'lumi-limite': 'O limite vai de 1 a 600 perguntas por minuto',
  'lumi-spento': 'O Lumi está desligado: o proprietário liga de novo em Gestão → Lumi.',
  'lumi-troppe': 'Muitas perguntas em pouco tempo: tente de novo em um minuto.',
  'lumi-risposta': 'O Lumi não respondeu',
  'lumi-campo': 'Campo desconhecido «{campo}» em {entita}',
  'lumi-data': 'Data inválida «{valore}»: use AAAA-MM-DD',
  'lumi-archiviata': 'já existe uma seção arquivada «{nome}» ({id}): restaure em Personalizar ou escolha outro nome',
  'doc-impostare': 'Só quem pode personalizar o sistema muda esses dados',
  'doc-righe': 'Esta seção não tem itens para imprimir',
  'doc-colonna': 'É preciso pelo menos uma coluna',
  'doc-regime': 'Regime fiscal desconhecido',
  'doc-cap': 'O CEP italiano tem 5 dígitos',
  'doc-provincia': 'A província é a sigla de 2 letras (ex.: MI)',
  'doc-colore': 'Cor inválida',
  'doc-aliquota': 'Alíquota de IVA inválida',
  'doc-logo': 'O logo precisa ser uma imagem PNG ou JPEG',
  'doc-logo-grande': 'O logo é grande demais: no máximo 300 KB',
  'doc-png': 'O arquivo não é PNG nem JPEG',
  'doc-fattura-doppia': 'Já existe uma fatura número {numero} em {anno}',
  'doc-numero-usato': 'Número já usado este ano',
  'doc-modello-fatture': 'Adicione antes o modelo «Faturas e fatura eletrônica» (Personalizar → modelos).',
  'doc-gia-fattura': 'Já é uma fatura',
  'doc-cliente': 'Em «{entita}» não há um cliente para faturar',
  'doc-storna': 'Só se estorna uma fatura emitida: esta ainda é um rascunho',
  'doc-nota': 'Já é uma nota de crédito',
  'xml-ragione': "Faltam os dados da sua empresa: a razão social (Documentos → Dados da empresa).",
  'xml-piva': "Falta o número de IVA da sua empresa.",
  'xml-piva-errata': "O número de IVA da sua empresa está errado: {_errore}.",
  'xml-regime': "Falta o regime fiscal da sua empresa (por exemplo RF01 ordinário ou RF19 simplificado).",
  'xml-indirizzo-azienda': "Falta o endereço completo da sua empresa (rua, CEP de 5 dígitos, município).",
  'xml-bozza': "A fatura ainda é um rascunho: emita para que ela receba o número.",
  'xml-annullata': "A fatura está cancelada: não é enviada ao SDI. Se já foi enviada, estorne com uma nota de crédito.",
  'xml-numero': "Falta o número da fatura.",
  'xml-data': "Falta a data da fatura.",
  'xml-righe': "A fatura não tem itens.",
  'xml-cliente-nome': "Falta o nome ou a razão social do cliente.",
  'xml-cliente-piva': "Falta o número de IVA ou o código fiscal do cliente.",
  'xml-codice-pa': "O código do destinatário tem 6 caracteres: é um órgão público e precisa do formato FPA12 (ainda não suportado).",
  'xml-codice-7': "O código do destinatário do cliente precisa ter 7 caracteres.",
  'xml-codice-manca': "Falta o código do destinatário do cliente: escreva na ficha dele (ou a PEC; se não tiver, escreva 0000000).",
  'xml-indirizzo-cliente': "Falta o endereço completo do cliente (rua, CEP de 5 dígitos, município).",
  'xml-provincia': "A província do cliente se escreve com a sigla de 2 letras (ex.: MI).",
  'xml-indirizzo-estero': "Falta o endereço do cliente (rua e cidade).",
  'xml-bollo': "Os itens sem IVA passam de 77,47 €: marque «Selo virtual de 2 €».",
  'xml-ritenuta': "Com a retenção, são necessários o tipo e o motivo.",
  'xml-totale': "O total da fatura é zero ou negativo (para estornar use uma nota de crédito com valores positivos).",
  'xml-rate': "Pagamento parcelado sem parcelas: adicione as parcelas ou escolha «Pagamento integral».",
  // avvio guidato, app desktop (backup, aggiornamenti, QR, rete), sicurezza
  'avvio-solo-titolare': "Só o titular pode fazer isso",
  'avvio-esempi-ci-sono': "Os dados de exemplo já estão aqui",
  'agg-risposta': "A verificação de versões respondeu {stato}",
  'agg-inattesa': "Resposta inesperada",
  'bk-percorso': "Digite o caminho completo da pasta (por exemplo {a} ou {b})",
  'bk-fuori-dati': "Escolha uma pasta fora da pasta dos dados",
  'bk-no-cartella': "Este banco de dados não tem pasta (está na memória)",
  'bk-non-kubo': "O arquivo não é um banco de dados do Kubo",
  'bk-in-memoria': "Este banco de dados está na memória",
  'qr-lungo': "Texto longo demais para o código QR",
  'rete-ipv4': "Endereço IPv4 inválido",
  'rete-scrivi': "Digite um endereço ou um código",
  'dk-solo-titolare': "Só o titular gerencia backups e atualizações",
  'dk-backup-sconosciuto': "Backup desconhecido",
  'dk-ripristino-corso': "Há uma restauração em andamento",
  'dk-db-memoria': "O banco de dados está na memória",
  'dk-conferma': "É preciso confirmar",
  'dk-file-piccolo': "O arquivo está vazio ou é pequeno demais para ser um backup",
  'dk-non-scrivo': "Não consigo gravar na pasta de backups",
  'dk-non-backup': "O arquivo não é um backup do Kubo (é preciso um arquivo .db)",
  'sic-solo-titolare': "Só o titular altera as configurações de segurança",
  'sic-cambia-password': "Antes de continuar, troque a senha que você recebeu",
  'sic-pin-password': "Para trocar o PIN é preciso a senha atual",
  'sic-password-sbagliata': "A senha atual está errada",
  'sic-no-fattura': "Sua função não exporta a nota fiscal eletrônica",
  'sic-no-lumi': "O Lumi não está ativo para a sua função",
  'sic-tipo-file': "Este tipo de arquivo não pode ser anexado (programas, scripts e páginas web)",
  'sic-token-password': "Com um token não se troca a senha",
  'sic-password-diversa': "A nova senha precisa ser diferente da anterior",
  'sic-sessione': "Sessão desconhecida",
  'sic-persona': "Pessoa desconhecida",
  'sic-fuso': "Fuso horário desconhecido (ex.: America/Sao_Paulo)",
  'sic-titolare-tutto': "O titular sempre pode tudo",
  'sic-ruolo': "Função desconhecida",
  'avvio-codice': "É preciso o código de início: ele está no terminal ou no log do Kubo",
  'pw-lunga': "A senha é longa demais",
  'pw-comune': "Esta senha está entre as mais usadas: escolha outra",
  'pw-facile': "Esta senha é fácil demais de adivinhar",
  'pw-nome': "A senha não pode ser seu nome ou seu e-mail",
  'pw-mescola': "Com menos de 12 caracteres, misture letras com números ou símbolos",
  // fisco (server/moduli/fisco.js)
  'fisco-impostazione': "Configuração fiscal inválida: {campo}",
  'fisco-forfettario': "No regime simplificado (forfettario) não há apurações de IVA nem comunicações LIPE",
  'fisco-dati-azienda': "A comunicação precisa do número de IVA e do código fiscal da empresa (Documentos → dados da empresa)",
  'fisco-anno': "Ano inválido",
  'fisco-periodo': "Período inválido",
  'fisco-nessun-versamento': "Nenhum pagamento nesta data",
  'fisco-solo-chi': "Só quem pode personalizar altera as configurações fiscais",
};
