// Le lingue di Lumi. Ogni testo per chi usa il pannello sta qui, in un catalogo per lingua: il codice chiama
// t('chiave', { parametri }) e mai una frase scritta a mano. L'italiano è la lingua di partenza e di riserva: se una
// chiave manca in inglese si vede l'italiano (e test/lingua.mjs lo segnala).
// I parametri si scrivono {nome}; i plurali sono oggetti { one, other } scelti con Intl.PluralRules.
// t() NON fa l'escape: chi mette il testo nell'HTML fa l'escape dei parametri che vengono dai dati.

export const LINGUE = {
  it: { nome: 'Italiano', locale: 'it-IT', voce: 'it-IT' },
  en: { nome: 'English', locale: 'en-GB', voce: 'en-US' },
  // le altre lingue di Kubo (web/lingue): stesse chiavi dell'italiano
  es: { nome: 'Español', locale: 'es-ES', voce: 'es-ES' },
  fr: { nome: 'Français', locale: 'fr-FR', voce: 'fr-FR' },
  de: { nome: 'Deutsch', locale: 'de-DE', voce: 'de-DE' },
  pt: { nome: 'Português', locale: 'pt-BR', voce: 'pt-BR' },
};

export const CATALOGHI = {
  it: {
    'saluto.mattina': 'Buongiorno', 'saluto.pomeriggio': 'Buon pomeriggio', 'saluto.sera': 'Buonasera',
    'saluto.nome': '{saluto}, {nome}.', 'saluto.solo': '{saluto}.',
    'stato.ordine': 'Tutto in ordine.',
    'stato.davedere': { one: 'Una cosa da vedere', other: '{n} cose da vedere' },
    'stato.urgenti': { one: ', una urgente', other: ', {n} urgenti' },
    'stato.aggiornato': '{giorno} · aggiornato alle {ora}',
    'pillola.ordine': 'Tutto in ordine',
    'pillola.davedere': '{n} da vedere',
    'pillola.aria': 'Assistente {nome}: {stato}. Passa sopra o premi {tasti}.',
    'regione': 'Assistente',
    'campo.placeholder': 'Chiedi o cerca…',
    'campo.aria': 'Chiedi o cerca',
    'campo.ascolto': 'Ti ascolto', 'campo.esc': 'Esc annulla', 'campo.attimo': 'Un attimo…',
    'campo.senzaServer': 'Demo senza AI: prova «{esempio}»',
    'mic.parla': 'Parla (oppure tieni premuto {tasti})',
    'mic.noVoce': 'La voce non è disponibile qui: si può scrivere',
    'piede.parla': 'Tieni premuto per parlare',
    'piede.conferma': 'Chiede conferma prima di ogni modifica',
    'piede.schermo': 'Schermo condiviso: niente nomi né cifre a voce',
    'vedere.titolo': 'Da vedere · {n}',
    'vedere.adesso': 'controllato adesso',
    'vedere.altre': 'e altre {n}',
    'vedere.niente': 'Niente in sospeso',
    'vedere.nienteNota': 'Non c\'è niente che aspetta',
    'vedere.apri': 'Apri',
    'drop.titolo': 'Lascia qui il file',
    'drop.nota': '{nome} lo legge: PDF, foto, Excel, Word, CSV, XML, testo',
    'file.leggo': 'leggo', 'file.pronto': 'pronto', 'file.caricato': 'caricato',
    'file.togli': 'Togli {nome}',
    'file.domanda': { one: 'Ho condiviso questo file: leggilo e dimmi in breve che cosa contiene e che cosa posso farci.', other: 'Ho condiviso questi file: leggili e dimmi in breve che cosa contengono e che cosa posso farci.' },
    'file.etichetta': { one: '{nome}', other: '{n} file' },
    'file.nonDisponibile': 'Per leggere i file serve il collegamento a Claude',
    'conferma.titolo': 'Confermi?',
    'conferma.si': 'Conferma', 'conferma.no': 'Annulla',
    'conferma.voce': 'Puoi anche dire «conferma».', 'conferma.scrivi': 'Puoi anche scrivere «sì».',
    'esito.annullato': 'Annullato.', 'esito.annullatoNota': 'Non ho cambiato niente.',
    'esito.fatto': 'Fatto.', 'esito.errore': 'Non è andata: {errore}',
    'risposta.rifiuto': 'Su questo non posso aiutarti.',
    'risposta.vuota': 'Non ho una risposta per questo: prova a chiederlo in un altro modo.',
    'risposta.lunga': 'La risposta era troppo lunga: prova a chiedere una cosa alla volta.',
    'risposta.interrotta': 'La risposta si è interrotta: riprova.',
    'risposta.irraggiungibile': 'Non riesco a raggiungere l\'assistente: controlla la connessione.',
    'risposta.errore': 'L\'assistente non ha risposto (errore {stato}).',
    'risposta.ricomincio': 'Ricomincio da capo: la conversazione era lunga.',
    'risposta.nonCapito': 'Senza Claude capisco solo poche frasi. Prova: {esempi}.',
    'avviso.collega': 'Collega Claude per le risposte vere: questa è la demo senza AI.',
    'avviso.microfono': 'Serve il permesso per il microfono',
    'avviso.noMicrofono': 'Nessun microfono collegato',
    'avviso.noVoce': 'Voce non disponibile adesso',
    'pensa.leggo': 'Guardo i dati…', 'pensa.preparo': 'Preparo la proposta…', 'pensa.mostro': 'Preparo il riepilogo…',
    'mostra.elenco': 'Elenco',
    'riassunto.annullato': 'annullato',
    'tu': 'TU',
  },
  en: {
    'saluto.mattina': 'Good morning', 'saluto.pomeriggio': 'Good afternoon', 'saluto.sera': 'Good evening',
    'saluto.nome': '{saluto}, {nome}.', 'saluto.solo': '{saluto}.',
    'stato.ordine': 'All in order.',
    'stato.davedere': { one: 'One thing to look at', other: '{n} things to look at' },
    'stato.urgenti': { one: ', one urgent', other: ', {n} urgent' },
    'stato.aggiornato': '{giorno} · updated at {ora}',
    'pillola.ordine': 'All in order',
    'pillola.davedere': '{n} to look at',
    'pillola.aria': 'Assistant {nome}: {stato}. Hover or press {tasti}.',
    'regione': 'Assistant',
    'campo.placeholder': 'Ask or search…',
    'campo.aria': 'Ask or search',
    'campo.ascolto': 'Listening', 'campo.esc': 'Esc cancels', 'campo.attimo': 'One moment…',
    'campo.senzaServer': 'Demo without AI: try “{esempio}”',
    'mic.parla': 'Speak (or hold {tasti})',
    'mic.noVoce': 'Voice isn\'t available here: you can type',
    'piede.parla': 'Hold to speak',
    'piede.conferma': 'Asks before every change',
    'piede.schermo': 'Shared screen: no names or figures out loud',
    'vedere.titolo': 'To look at · {n}',
    'vedere.adesso': 'checked just now',
    'vedere.altre': 'and {n} more',
    'vedere.niente': 'Nothing pending',
    'vedere.nienteNota': 'Nothing is waiting',
    'vedere.apri': 'Open',
    'drop.titolo': 'Drop the file here',
    'drop.nota': '{nome} reads it: PDF, photos, Excel, Word, CSV, XML, text',
    'file.leggo': 'reading', 'file.pronto': 'ready', 'file.caricato': 'uploaded',
    'file.togli': 'Remove {nome}',
    'file.domanda': { one: 'I shared this file: read it and tell me briefly what it contains and what I can do with it.', other: 'I shared these files: read them and tell me briefly what they contain and what I can do with them.' },
    'file.etichetta': { one: '{nome}', other: '{n} files' },
    'file.nonDisponibile': 'Reading files needs the connection to Claude',
    'conferma.titolo': 'Confirm?',
    'conferma.si': 'Confirm', 'conferma.no': 'Cancel',
    'conferma.voce': 'You can also say “confirm”.', 'conferma.scrivi': 'You can also type “yes”.',
    'esito.annullato': 'Cancelled.', 'esito.annullatoNota': 'Nothing was changed.',
    'esito.fatto': 'Done.', 'esito.errore': 'It didn\'t work: {errore}',
    'risposta.rifiuto': 'I can\'t help with that.',
    'risposta.vuota': 'I don\'t have an answer for that: try asking another way.',
    'risposta.lunga': 'The answer was too long: try asking one thing at a time.',
    'risposta.interrotta': 'The answer stopped: try again.',
    'risposta.irraggiungibile': 'I can\'t reach the assistant: check the connection.',
    'risposta.errore': 'The assistant didn\'t answer (error {stato}).',
    'risposta.ricomincio': 'Starting over: the conversation was long.',
    'risposta.nonCapito': 'Without Claude I only understand a few sentences. Try: {esempi}.',
    'avviso.collega': 'Connect Claude for real answers: this is the demo without AI.',
    'avviso.microfono': 'The microphone needs permission',
    'avviso.noMicrofono': 'No microphone connected',
    'avviso.noVoce': 'Voice not available right now',
    'pensa.leggo': 'Looking at the data…', 'pensa.preparo': 'Preparing the proposal…', 'pensa.mostro': 'Preparing the summary…',
    'mostra.elenco': 'List',
    'riassunto.annullato': 'cancelled',
    'tu': 'YOU',
  },
  es: {
    'saluto.mattina': 'Buenos días', 'saluto.pomeriggio': 'Buenas tardes', 'saluto.sera': 'Buenas noches',
    'saluto.nome': '{saluto}, {nome}.', 'saluto.solo': '{saluto}.',
    'stato.ordine': 'Todo en orden.',
    'stato.davedere': { one: 'Una cosa por revisar', other: '{n} cosas por revisar' },
    'stato.urgenti': { one: ', una urgente', other: ', {n} urgentes' },
    'stato.aggiornato': '{giorno} · actualizado a las {ora}',
    'pillola.ordine': 'Todo en orden',
    'pillola.davedere': '{n} por revisar',
    'pillola.aria': 'Asistente {nome}: {stato}. Pasa el ratón por encima o pulsa {tasti}.',
    'regione': 'Asistente',
    'campo.placeholder': 'Pregunta o busca…',
    'campo.aria': 'Pregunta o busca',
    'campo.ascolto': 'Te escucho', 'campo.esc': 'Esc cancela', 'campo.attimo': 'Un momento…',
    'campo.senzaServer': 'Demo sin IA: prueba «{esempio}»',
    'mic.parla': 'Habla (o mantén pulsado {tasti})',
    'mic.noVoce': 'La voz no está disponible aquí: puedes escribir',
    'piede.parla': 'Mantén pulsado para hablar',
    'piede.conferma': 'Pide confirmación antes de cada cambio',
    'piede.schermo': 'Pantalla compartida: ni nombres ni cifras en voz alta',
    'vedere.titolo': 'Por revisar · {n}',
    'vedere.adesso': 'revisado ahora',
    'vedere.altre': 'y {n} más',
    'vedere.niente': 'Nada pendiente',
    'vedere.nienteNota': 'No hay nada esperando',
    'vedere.apri': 'Abrir',
    'drop.titolo': 'Suelta aquí el archivo',
    'drop.nota': '{nome} lo lee: PDF, fotos, Excel, Word, CSV, XML, texto',
    'file.leggo': 'leyendo', 'file.pronto': 'listo', 'file.caricato': 'subido',
    'file.togli': 'Quitar {nome}',
    'file.domanda': { one: 'He compartido este archivo: léelo y dime en pocas palabras qué contiene y qué puedo hacer con él.', other: 'He compartido estos archivos: léelos y dime en pocas palabras qué contienen y qué puedo hacer con ellos.' },
    'file.etichetta': { one: '{nome}', other: '{n} archivos' },
    'file.nonDisponibile': 'Para leer archivos hace falta la conexión con Claude',
    'conferma.titolo': '¿Confirmas?',
    'conferma.si': 'Confirmar', 'conferma.no': 'Cancelar',
    'conferma.voce': 'También puedes decir «confirmo».', 'conferma.scrivi': 'También puedes escribir «sí».',
    'esito.annullato': 'Cancelado.', 'esito.annullatoNota': 'No he cambiado nada.',
    'esito.fatto': 'Hecho.', 'esito.errore': 'No ha salido bien: {errore}',
    'risposta.rifiuto': 'Con esto no puedo ayudarte.',
    'risposta.vuota': 'No tengo respuesta para esto: prueba a preguntarlo de otra forma.',
    'risposta.lunga': 'La respuesta era demasiado larga: prueba a preguntar una cosa cada vez.',
    'risposta.interrotta': 'La respuesta se ha cortado: inténtalo otra vez.',
    'risposta.irraggiungibile': 'No consigo contactar con el asistente: revisa la conexión.',
    'risposta.errore': 'El asistente no ha respondido (error {stato}).',
    'risposta.ricomincio': 'Empiezo de nuevo: la conversación era larga.',
    'risposta.nonCapito': 'Sin Claude solo entiendo unas pocas frases. Prueba: {esempi}.',
    'avviso.collega': 'Conecta Claude para tener respuestas de verdad: esta es la demo sin IA.',
    'avviso.microfono': 'Hace falta permiso para el micrófono',
    'avviso.noMicrofono': 'No hay ningún micrófono conectado',
    'avviso.noVoce': 'La voz no está disponible ahora',
    'pensa.leggo': 'Miro los datos…', 'pensa.preparo': 'Preparo la propuesta…', 'pensa.mostro': 'Preparo el resumen…',
    'mostra.elenco': 'Lista',
    'riassunto.annullato': 'cancelado',
    'tu': 'TÚ',
  },
  fr: {
    'saluto.mattina': 'Bonjour', 'saluto.pomeriggio': 'Bon après-midi', 'saluto.sera': 'Bonsoir',
    'saluto.nome': '{saluto}, {nome}.', 'saluto.solo': '{saluto}.',
    'stato.ordine': 'Tout est en ordre.',
    'stato.davedere': { one: 'Une chose à voir', other: '{n} choses à voir' },
    'stato.urgenti': { one: ', une urgente', other: ', {n} urgentes' },
    'stato.aggiornato': '{giorno} · mis à jour à {ora}',
    'pillola.ordine': 'Tout est en ordre',
    'pillola.davedere': '{n} à voir',
    'pillola.aria': 'Assistant {nome} : {stato}. Survolez ou appuyez sur {tasti}.',
    'regione': 'Assistant',
    'campo.placeholder': 'Demandez ou cherchez…',
    'campo.aria': 'Demandez ou cherchez',
    'campo.ascolto': 'Je vous écoute', 'campo.esc': 'Échap pour annuler', 'campo.attimo': 'Un instant…',
    'campo.senzaServer': 'Démo sans IA : essayez « {esempio} »',
    'mic.parla': 'Parlez (ou maintenez {tasti})',
    'mic.noVoce': 'La voix n\'est pas disponible ici : vous pouvez écrire',
    'piede.parla': 'Maintenez pour parler',
    'piede.conferma': 'Demande confirmation avant chaque modification',
    'piede.schermo': 'Écran partagé : ni noms ni chiffres à voix haute',
    'vedere.titolo': 'À voir · {n}',
    'vedere.adesso': 'vérifié à l\'instant',
    'vedere.altre': 'et {n} autres',
    'vedere.niente': 'Rien en attente',
    'vedere.nienteNota': 'Rien n\'attend',
    'vedere.apri': 'Ouvrir',
    'drop.titolo': 'Déposez le fichier ici',
    'drop.nota': '{nome} le lit : PDF, photos, Excel, Word, CSV, XML, texte',
    'file.leggo': 'lecture', 'file.pronto': 'prêt', 'file.caricato': 'envoyé',
    'file.togli': 'Retirer {nome}',
    'file.domanda': { one: 'J\'ai partagé ce fichier : lis-le et dis-moi en bref ce qu\'il contient et ce que je peux en faire.', other: 'J\'ai partagé ces fichiers : lis-les et dis-moi en bref ce qu\'ils contiennent et ce que je peux en faire.' },
    'file.etichetta': { one: '{nome}', other: '{n} fichiers' },
    'file.nonDisponibile': 'Pour lire les fichiers, il faut la connexion à Claude',
    'conferma.titolo': 'Vous confirmez ?',
    'conferma.si': 'Confirmer', 'conferma.no': 'Annuler',
    'conferma.voce': 'Vous pouvez aussi dire « confirmer ».', 'conferma.scrivi': 'Vous pouvez aussi écrire « oui ».',
    'esito.annullato': 'Annulé.', 'esito.annullatoNota': 'Je n\'ai rien changé.',
    'esito.fatto': 'C\'est fait.', 'esito.errore': 'Ça n\'a pas marché : {errore}',
    'risposta.rifiuto': 'Je ne peux pas vous aider là-dessus.',
    'risposta.vuota': 'Je n\'ai pas de réponse : essayez de le demander autrement.',
    'risposta.lunga': 'La réponse était trop longue : demandez une chose à la fois.',
    'risposta.interrotta': 'La réponse s\'est interrompue : réessayez.',
    'risposta.irraggiungibile': 'Je n\'arrive pas à joindre l\'assistant : vérifiez la connexion.',
    'risposta.errore': 'L\'assistant n\'a pas répondu (erreur {stato}).',
    'risposta.ricomincio': 'Je repars de zéro : la conversation était longue.',
    'risposta.nonCapito': 'Sans Claude, je ne comprends que quelques phrases. Essayez : {esempi}.',
    'avviso.collega': 'Connectez Claude pour de vraies réponses : ceci est la démo sans IA.',
    'avviso.microfono': 'Il faut l\'autorisation du micro',
    'avviso.noMicrofono': 'Aucun micro branché',
    'avviso.noVoce': 'Voix indisponible pour le moment',
    'pensa.leggo': 'Je regarde les données…', 'pensa.preparo': 'Je prépare la proposition…', 'pensa.mostro': 'Je prépare le récapitulatif…',
    'mostra.elenco': 'Liste',
    'riassunto.annullato': 'annulé',
    'tu': 'VOUS',
  },
  de: {
    'saluto.mattina': 'Guten Morgen', 'saluto.pomeriggio': 'Guten Tag', 'saluto.sera': 'Guten Abend',
    'saluto.nome': '{saluto}, {nome}.', 'saluto.solo': '{saluto}.',
    'stato.ordine': 'Alles in Ordnung.',
    'stato.davedere': { one: 'Eine Sache zum Ansehen', other: '{n} Sachen zum Ansehen' },
    'stato.urgenti': { one: ', eine dringend', other: ', {n} dringend' },
    'stato.aggiornato': '{giorno} · aktualisiert um {ora}',
    'pillola.ordine': 'Alles in Ordnung',
    'pillola.davedere': '{n} zum Ansehen',
    'pillola.aria': 'Assistent {nome}: {stato}. Mit der Maus darüberfahren oder {tasti} drücken.',
    'regione': 'Assistent',
    'campo.placeholder': 'Fragen oder suchen…',
    'campo.aria': 'Fragen oder suchen',
    'campo.ascolto': 'Ich höre zu', 'campo.esc': 'Esc bricht ab', 'campo.attimo': 'Einen Moment…',
    'campo.senzaServer': 'Demo ohne KI: Probier „{esempio}“',
    'mic.parla': 'Sprechen (oder {tasti} gedrückt halten)',
    'mic.noVoce': 'Sprache ist hier nicht verfügbar: Du kannst schreiben',
    'piede.parla': 'Zum Sprechen gedrückt halten',
    'piede.conferma': 'Fragt vor jeder Änderung nach',
    'piede.schermo': 'Geteilter Bildschirm: keine Namen und Zahlen laut',
    'vedere.titolo': 'Zum Ansehen · {n}',
    'vedere.adesso': 'gerade geprüft',
    'vedere.altre': 'und {n} weitere',
    'vedere.niente': 'Nichts offen',
    'vedere.nienteNota': 'Nichts wartet',
    'vedere.apri': 'Öffnen',
    'drop.titolo': 'Datei hier ablegen',
    'drop.nota': '{nome} liest sie: PDF, Fotos, Excel, Word, CSV, XML, Text',
    'file.leggo': 'wird gelesen', 'file.pronto': 'bereit', 'file.caricato': 'hochgeladen',
    'file.togli': '{nome} entfernen',
    'file.domanda': { one: 'Ich habe diese Datei geteilt: Lies sie und sag mir kurz, was drinsteht und was ich damit machen kann.', other: 'Ich habe diese Dateien geteilt: Lies sie und sag mir kurz, was drinsteht und was ich damit machen kann.' },
    'file.etichetta': { one: '{nome}', other: '{n} Dateien' },
    'file.nonDisponibile': 'Zum Lesen von Dateien braucht es die Verbindung zu Claude',
    'conferma.titolo': 'Bestätigen?',
    'conferma.si': 'Bestätigen', 'conferma.no': 'Abbrechen',
    'conferma.voce': 'Du kannst auch „bestätigen“ sagen.', 'conferma.scrivi': 'Du kannst auch „ja“ schreiben.',
    'esito.annullato': 'Abgebrochen.', 'esito.annullatoNota': 'Ich habe nichts geändert.',
    'esito.fatto': 'Erledigt.', 'esito.errore': 'Das hat nicht geklappt: {errore}',
    'risposta.rifiuto': 'Dabei kann ich nicht helfen.',
    'risposta.vuota': 'Darauf habe ich keine Antwort: Frag es anders.',
    'risposta.lunga': 'Die Antwort war zu lang: Frag eine Sache nach der anderen.',
    'risposta.interrotta': 'Die Antwort wurde unterbrochen: Versuch es noch einmal.',
    'risposta.irraggiungibile': 'Ich erreiche den Assistenten nicht: Prüf die Verbindung.',
    'risposta.errore': 'Der Assistent hat nicht geantwortet (Fehler {stato}).',
    'risposta.ricomincio': 'Ich fange von vorn an: Das Gespräch war lang.',
    'risposta.nonCapito': 'Ohne Claude verstehe ich nur wenige Sätze. Probier: {esempi}.',
    'avviso.collega': 'Verbinde Claude für echte Antworten: Das ist die Demo ohne KI.',
    'avviso.microfono': 'Für das Mikrofon braucht es eine Erlaubnis',
    'avviso.noMicrofono': 'Kein Mikrofon angeschlossen',
    'avviso.noVoce': 'Sprache gerade nicht verfügbar',
    'pensa.leggo': 'Ich sehe mir die Daten an…', 'pensa.preparo': 'Ich bereite den Vorschlag vor…', 'pensa.mostro': 'Ich bereite die Übersicht vor…',
    'mostra.elenco': 'Liste',
    'riassunto.annullato': 'abgebrochen',
    'tu': 'DU',
  },
  pt: {
    'saluto.mattina': 'Bom dia', 'saluto.pomeriggio': 'Boa tarde', 'saluto.sera': 'Boa noite',
    'saluto.nome': '{saluto}, {nome}.', 'saluto.solo': '{saluto}.',
    'stato.ordine': 'Tudo em ordem.',
    'stato.davedere': { one: 'Uma coisa para ver', other: '{n} coisas para ver' },
    'stato.urgenti': { one: ', uma urgente', other: ', {n} urgentes' },
    'stato.aggiornato': '{giorno} · atualizado às {ora}',
    'pillola.ordine': 'Tudo em ordem',
    'pillola.davedere': '{n} para ver',
    'pillola.aria': 'Assistente {nome}: {stato}. Passe o mouse ou pressione {tasti}.',
    'regione': 'Assistente',
    'campo.placeholder': 'Pergunte ou busque…',
    'campo.aria': 'Pergunte ou busque',
    'campo.ascolto': 'Estou ouvindo', 'campo.esc': 'Esc cancela', 'campo.attimo': 'Só um momento…',
    'campo.senzaServer': 'Demo sem IA: experimente «{esempio}»',
    'mic.parla': 'Fale (ou segure {tasti})',
    'mic.noVoce': 'A voz não está disponível aqui: dá para escrever',
    'piede.parla': 'Segure para falar',
    'piede.conferma': 'Pede confirmação antes de cada alteração',
    'piede.schermo': 'Tela compartilhada: nada de nomes nem números em voz alta',
    'vedere.titolo': 'Para ver · {n}',
    'vedere.adesso': 'verificado agora',
    'vedere.altre': 'e mais {n}',
    'vedere.niente': 'Nada pendente',
    'vedere.nienteNota': 'Não há nada esperando',
    'vedere.apri': 'Abrir',
    'drop.titolo': 'Solte o arquivo aqui',
    'drop.nota': '{nome} lê: PDF, fotos, Excel, Word, CSV, XML, texto',
    'file.leggo': 'lendo', 'file.pronto': 'pronto', 'file.caricato': 'enviado',
    'file.togli': 'Remover {nome}',
    'file.domanda': { one: 'Compartilhei este arquivo: leia e me diga em poucas palavras o que ele contém e o que posso fazer com ele.', other: 'Compartilhei estes arquivos: leia e me diga em poucas palavras o que eles contêm e o que posso fazer com eles.' },
    'file.etichetta': { one: '{nome}', other: '{n} arquivos' },
    'file.nonDisponibile': 'Para ler arquivos é preciso a conexão com o Claude',
    'conferma.titolo': 'Confirma?',
    'conferma.si': 'Confirmar', 'conferma.no': 'Cancelar',
    'conferma.voce': 'Você também pode dizer «confirmo».', 'conferma.scrivi': 'Você também pode escrever «sim».',
    'esito.annullato': 'Cancelado.', 'esito.annullatoNota': 'Não mudei nada.',
    'esito.fatto': 'Feito.', 'esito.errore': 'Não deu certo: {errore}',
    'risposta.rifiuto': 'Com isso não posso ajudar.',
    'risposta.vuota': 'Não tenho resposta para isso: tente perguntar de outro jeito.',
    'risposta.lunga': 'A resposta ficou longa demais: pergunte uma coisa de cada vez.',
    'risposta.interrotta': 'A resposta foi interrompida: tente de novo.',
    'risposta.irraggiungibile': 'Não consigo falar com o assistente: verifique a conexão.',
    'risposta.errore': 'O assistente não respondeu (erro {stato}).',
    'risposta.ricomincio': 'Recomeçando do zero: a conversa estava longa.',
    'risposta.nonCapito': 'Sem o Claude entendo só algumas frases. Experimente: {esempi}.',
    'avviso.collega': 'Conecte o Claude para respostas de verdade: esta é a demo sem IA.',
    'avviso.microfono': 'É preciso permissão para o microfone',
    'avviso.noMicrofono': 'Nenhum microfone conectado',
    'avviso.noVoce': 'Voz indisponível agora',
    'pensa.leggo': 'Olhando os dados…', 'pensa.preparo': 'Preparando a proposta…', 'pensa.mostro': 'Preparando o resumo…',
    'mostra.elenco': 'Lista',
    'riassunto.annullato': 'cancelado',
    'tu': 'VOCÊ',
  },
};

// la lingua: quella chiesta dall'host, poi quella del browser, poi l'inglese (l'italiano solo se il browser è italiano)
export function scegliLingua(chiesta) {
  if (chiesta && Object.hasOwn(LINGUE, chiesta)) return chiesta;
  const sis = (typeof navigator !== 'undefined' && (navigator.languages?.[0] || navigator.language)) || '';
  const c = String(sis).slice(0, 2).toLowerCase();
  return Object.hasOwn(LINGUE, c) ? c : 'en';
}

const metti = (s, p) => (p ? String(s).replace(/\{(\w+)\}/g, (x, k) => (k in p ? String(p[k]) : x)) : String(s));

// un traduttore legato a una lingua: ogni istanza di Lumi ha il suo
export function traduttore(lingua) {
  const cod = Object.hasOwn(LINGUE, lingua) ? lingua : 'it';
  const regole = new Intl.PluralRules(LINGUE[cod].locale);
  const t = (chiave, p) => {
    let v = CATALOGHI[cod][chiave] ?? CATALOGHI.it[chiave];
    if (v == null) return chiave;
    if (typeof v === 'object') v = v[regole.select(Number(p?.n ?? 0))] ?? v.other;
    return metti(v, p);
  };
  t.lingua = cod; t.locale = LINGUE[cod].locale; t.voce = LINGUE[cod].voce;
  return t;
}
